### ISSUE TITLE
Configuration for rule "react/jsx-sort-props" is invalid

### ISSUE THREAD

**Issue by BenoitAverty** [airbnb/javascript#1000]
Hello,

I just made the switch to eslint 3, but I still have an error when saving a file (I use atom and linter-eslint)

```
Error: /home/<package>/node_modules/eslint-config-airbnb/rules/react.js: Configuration for rule "react/jsx-sort-props" is invalid: Value "data["0"].shorthandLast" has additional properties.

Referenced from: airbnb Referenced from: /home/<package>/.eslintrc
```

**Comment by BenoitAverty** [comment]
Never mind, it seems that atom was using the same linter for some reason. Closing and reopening my session did the trick.

**Comment by nathanmarks** [comment]
I'm seeing this after copy/pasting the installation code from the npm README.

```
Referenced from: airbnb
Referenced from: ./react-7240/.eslintrc.js
Error: ./react-7240/node_modules/eslint-config-airbnb/rules/react.js:
	Configuration for rule "react/jsx-sort-props" is invalid:
	Value "data["0"].shorthandLast" has additional properties.
```

**Comment by nathanmarks** [comment]
@ljharb The README is out of date. I installed the next/latest major versions of everything and the issue was resolved.

**Comment by ljharb** [comment]
What part of the readme is out of date? Please note you're supposed to use the bash script with `PKG` in it - not the literal `npm install` command after it.

**Comment by nathanmarks** [comment]
@ljharb 

That was 100% my fault.
