### ISSUE TITLE
Eslintrc - wich one should i use ?

### ISSUE THREAD

**Issue by mega-n3ss** [airbnb/javascript#1004]
Hi,

I'm implementing eslint to use the coding standard and it seems like your Javascript Coding Standard is pretty nice. So I installed eslint, eslint-plugin-import, eslint-plugin-react, and eslint-plugin-jsx-a11y (with npm). 

Then I follow your installation guide [Here](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb#eslint-config-airbnb-1). But I have too many .eslintrc

I don't know in wich one I should put the "extends": "airbnb".

>/usr/local/Cellar/node/6.3.1/libexec/npm/lib/node_modules/npm/node_modules/fs-vacuum/.eslintrc
/usr/local/lib/node_modules/bower/lib/node_modules/extend/.eslintrc
/usr/local/lib/node_modules/bower/lib/node_modules/form-data/.eslintrc
/usr/local/lib/node_modules/bower/lib/node_modules/inflight/.eslintrc
/usr/local/lib/node_modules/bower/lib/node_modules/request/.eslintrc
/usr/local/lib/node_modules/eslint-plugin-jsx-a11y/.eslintrc
/usr/local/lib/node_modules/eslint-plugin-jsx-a11y/node_modules/jsx-ast-utils/.eslintrc
/usr/local/lib/node_modules/eslint-plugin-react/node_modules/jsx-ast-utils/.eslintrc
/usr/local/lib/node_modules/npm/node_modules/fs-vacuum/.eslintrc

EDIT : After searching more, I suppose it's the .eslintrc.js i create with the `eslint --init`

**Comment by ljharb** [comment]
Yes, the ones inside node_modules are for your dependencies, which you won't be linting (and shouldn't need to be searching through)
