### ISSUE TITLE
Spurious no-cond-assign produced

### ISSUE THREAD

**Issue by Satyam** [airbnb/javascript#1007]
The following simplified code produces a `no-cond-assign` error on the first `if` caused by the assignments in the fat-arrow function within:

```js
'use strict';
const arr = [1, 2, 3];

if (arr.some(val => {
  let b = true;
  if (val === 2) {
    b = false;
  }
  return b;
})) console.log('returned true');
```

I linted the code above with the `eslint:recommended` style with the `"no-cond-assign": 2` rule explicitly added and also initializing my eslint config file through `eslint --init` and picking airbnb, google and standard styles.  The error **is only produced when using the airbnb style**, that is why I am reporting it here.  It also happens using `eslint-config-airbnb-base` and changing the eslintrc file to extend `airbnb-base`.

Here is the package.json
```json
{
  "name": "no-cond-assign",
  "version": "1.0.0",
  "description": "no-cond-assign",
  "main": "index.js",
  "scripts": {
    "test": "node index.js",
    "lint": "eslint . || exit 0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "eslint": "^3.2.2",
    "eslint-config-airbnb": "^10.0.0",
    "eslint-plugin-react": "^6.0.0"
  }
}
```
and eslint config:
```js
module.exports = {
    "extends": "airbnb",
    "plugins": [
        "react"
    ],
    // Not relevant, just to avoid unnecessary noise:
    "rules": {
      strict: 0,
      "no-console": 0
    }
};
```

**Comment by ljharb** [comment]
Thanks for the report! This seems like a bug in eslint core - it's just likely that a specific combination of rules triggers the bug, and our config has that combination.

I'd bet we could narrow it down by binary searching through the rules in base. If you try different eslint versions, and/or different base versions, do you see the same behavior?

**Comment by Satyam** [comment]
The issue showed up after I updated to the latest versions of eslint and related packages. It didn't happen with the 2.x version of eslint.  I am not sure about 3.x versions prior to the current one.  

None of the other preset styles offered by `eslint --init` nor the very basic `eslint:recommended` caused the error with eslint@3.x.  I didn't try other pre-configured styles (google, standard, etc) in previous versions since I don't actually use any of them.  I only tried them now in order to locate the source of the bug.

**Comment by ljharb** [comment]
The default for `no-cond-assign` is "except-parens" - we use "always".

In other words, this is expected behavior. The preferred approach is to assign the `some` result to a variable, and use the identifier inside the "if" condition.

As to why it changed from 2.x to 3.x, I'm assuming something in eslint changed so that it got fewer false positives.
