### ISSUE TITLE
Inconsistent Opinion on Function Expressions

### ISSUE THREAD

**Issue by peterkrieg** [airbnb/javascript#1008]
Just wanted to clarify something that was confusing to me and perhaps others reading.

[7.1](https://github.com/airbnb/javascript#functions--declarations) states that the following is "bad":

```
// bad
const foo = function () {};
```

However, [7.11](https://github.com/airbnb/javascript#functions--signature-spacing) states the following is "good":

```
// good
const x = function () {};
```

I understand [7.11](https://github.com/airbnb/javascript#functions--signature-spacing) is talking about spacing alone, but the fact that the example used was what _not_ to do in the previous section [7.1](https://github.com/airbnb/javascript#functions--declarations) seemed strange.

**Comment by ljharb** [comment]
7.1 probably needs to be revised a bit.
