### ISSUE TITLE
Incorrect import/extensions settings?

### ISSUE THREAD

**Issue by tleunen** [airbnb/javascript#1013]
In [this commit](https://github.com/airbnb/javascript/commit/b45fdcd60f6e08f13718bc2348e8d6ea1314e91c), the settings for `import/extensions` was added but this seems incorrect. I don't see that `node_modules` is a valid entry in the doc.

https://github.com/benmosher/eslint-plugin-import#importextensions

What does it mean exactly if it's valid?

**Comment by ljharb** [comment]
You're right, that seems like just a mistake in the commit (maybe a merge commit, or maybe i'm just an idiot)

**Comment by tleunen** [comment]
I didn't mean that ;) Thanks for the fix :)
