### ISSUE TITLE
Ternarie example is the same in better and best (15.6)

### ISSUE THREAD

**Issue by Maurize** [airbnb/javascript#1019]
As you can see, this example is in both sections - In better and best.
Maybe you should delete one of the examples to make it more clear.

![2016-08-18 09_10_43-airbnb_javascript_ javascript style guide](https://cloud.githubusercontent.com/assets/20089383/17765050/b8e37014-6523-11e6-9529-cc6f73898e4c.png)

**Comment by ljharb** [comment]
That line is there twice, but the "better" and "best" examples are two statements long - both of them share the same first statement, but have different second statements.

**Comment by Maurize** [comment]
Okay, I am merely the opinion that it is sufficient to have this line once - In the "better" section.
But if both are necessary for the seconds statements, it makes sense.
