### ISSUE TITLE
6.2 contradicts 18.12

### ISSUE THREAD

**Issue by AskYous** [airbnb/javascript#1027]
6.2 says that strings over 100 characters should **not** be split into new lines. 18.12 says they should be. Both provide contradicting examples.

**6.2**:

    // good
    const errorMessage = 'This is a super long error that was thrown because of Batman. When you stop to think about how Batman had anything to do with this, you would get nowhere fast.';

**18.12**:

    // bad
    const foo = 'Whatever national crop flips the window. The cartoon reverts within the screw. Whatever wizard constrains a helpful ally. The counterpart ascends!';

**Comment by ljharb** [comment]
Thanks - we definitely should update https://github.com/airbnb/javascript#whitespace--max-len so that "long line" examples are not composed of long strings.
