### ISSUE TITLE
Changed the value in json doesn't mean reassigned?

### ISSUE THREAD

**Issue by HamChao** [airbnb/javascript#1029]
`
let foo = {
  bar: 'msg'
};
if (something) {
  foo.bar = 'new message';
}
`

I'm using **let** because I've changed value inside this variable.
But I've been warned to use **const** instead.

Is this one doesn't call reassigned ?

**Comment by myknbani** [comment]
No it doesn't reassign the `foo` reference.  It's still the same object, only that you altered the `bar` property.

```javascript
let foo = { bar: 'msg' }

if (something) {
  foo = { bar: 'new message' }  // this needs a let, since { bar: 'new message' } is a different object
}
```

**Comment by ljharb** [comment]
Reassignment of `foo` requires `foo =`. You're simply mutating the object.
