### ISSUE TITLE
Consider adding a changelog

### ISSUE THREAD

**Issue by selbekk** [airbnb/javascript#1030]
It would be very nice to have a changelog whenever you bump your version numbers - so that I can figure out what changes to do whenever I want to upgrade.

Consider adding one!

**Comment by tleunen** [comment]
- base: https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/CHANGELOG.md
- "react": https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/CHANGELOG.md

😉

**Comment by selbekk** [comment]
Gah, sorry.
