### ISSUE TITLE
no-debugger is duplicated by no-restricted-syntax

### ISSUE THREAD

**Issue by pmcelhaney** [airbnb/javascript#1031]
Can we remove "DebuggerStatement" from `no-restricted-syntax`? It's already covered by `no-debugger`, so if I leave a debugger statement in I get two errors for the same issue.

**Comment by ljharb** [comment]
That's a fair point - no reason to force someone to override two rules.

**Comment by pmcelhaney** [comment]
That's gotta be some kind of record. 💯
