### ISSUE TITLE
eslint latest version incompatibility

### ISSUE THREAD

**Issue by amypellegrini** [airbnb/javascript#1038]
1. Installed eslint
2. Tried to install airbnb-eslint-config and get the following errors:

`UNMET PEER DEPENDENCY eslint@^3.3.0`
`npm WARN EPEERINVALID eslint-config-airbnb@10.0.1 requires a peer of eslint@^3.3.0 but none was installed.`

eslint latest is 3.3.1

**Comment by ljharb** [comment]
`^3.3.0` is a semver range which supports everything from `3.3.0` - `4.0.0` (not including 4.0.0). Check out http://semver.npmjs.com to see a visualization.

To install `airbnb-eslint-config` with all the right peer dependencies, use the command in the package [README](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb):
```sh
(
  export PKG=eslint-config-airbnb;
  npm info "$PKG" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs npm install --save-dev "$PKG"
)
```

**Comment by caisah** [comment]
Any plans on supporting the latest versions of those dependencies? Today I've just upgraded all my packages and broke the dependencies. It took me a while to figure things out...

Thanks for all the work you guys put in this.

**Comment by ljharb** [comment]
@caisah of which dependencies? The only thing we're out of date on (via semver ranges) is eslint-plugin-import, and #1101 is open to handle that in the next semver-major of eslint-config-airbnb-base.

**Comment by alexicum** [comment]
For global setup I used bash script:
```
(
  export PKG=eslint-config-airbnb;
  npm info -g "$PKG@latest" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs npm install -g "$PKG@latest"
)
```

**Comment by ljharb** [comment]
I'd discourage you from installing anything globally, especially a linter. Linting is a highly project-specific concern and should be installed locally.

**Comment by alexicum** [comment]
Yes of course, it's important to mention it.
Global installation is convenient during learning: no need to install linting for each project cloned from github.

**Comment by ljharb** [comment]
A project that doesn't have its own linting settings shouldn't be linted; that's what I'd hope newcomers would be learning.
