### ISSUE TITLE
Is there a way to count the eslint rules that exist in airbnb?

### ISSUE THREAD

**Issue by chrisjlee** [airbnb/javascript#1039]
For documentation purproses, I'm trying to do a diff between a homegrown eslint and one the airbnb version. Is there a way to count the number of rules that airbnb has?

**Comment by ljharb** [comment]
https://www.npmjs.com/package/eslint-find-rules provides `eslint-diff-rules` which may be helpful

**Comment by chrisjlee** [comment]
Thanks!
