### ISSUE TITLE
Help> Hiding a search container through escape button 

### ISSUE THREAD

**Issue by Ahedali** [airbnb/javascript#1040]
Hi guys, 

I did this function to hide search container by escape button but there is a problem i need help 
.spr-container .sprsearch-form and ico search is hiding automatically after pressing the escape button how to make it still active without hiding again. 

Thanks for your time. 

CODE : 

```
$(document).keyup(function(event) {
	
	    if (event.keyCode == 27) {
	   
        $('#sp_search_pro_1').slideToggle('fast');
        $('#spr-container').slideToggle();
        $('#sp_searchpro').slideToggle();
        $('#top1e_content_result').slideToggle();
		$('#suggest-list').slideToggle();
		 if($('.spr-container .sprsearch-form').hasClass('active_form')){
                        $('.spr-container .sprsearch-form').removeClass('active_form');
           }
else {

          $('.spr-container .sprsearch-form').addClass('active_form');
}

  if($('.icon-search').hasClass('active')){
                        $('.icon-search').removeClass('active');
 } else {
          $('.icon-search').addClass('active');
}
} 
});

```

**Comment by ljharb** [comment]
Hi! This repo is for discussing our JS style guide, and is not a place for general purpose JS help.

**Comment by Ahedali** [comment]
so where is the suitable place to discuss this issue?

**Comment by lencioni** [comment]
@Ahedali You might have some luck on [StackOverflow](https://stackoverflow.com/).
