### ISSUE TITLE
Error: Cannot read config file

### ISSUE THREAD

**Issue by stephenkingsley** [airbnb/javascript#1042]
when I `npm i` those package
```javascript

"eslint": "^3.3.1",
"eslint-config-airbnb": "^10.0.1",
"eslint-plugin-import": "^1.13.0",
"eslint-plugin-jsx-a11y": "^2.1.0",
"eslint-plugin-react": "^6.1.2",

```

the atom warning me:
`XXX/node_modules/eslint-config-airbnb/node_modules/eslint-config-airbnb-base/rules/strict.js Error: ENOENT: no such file or directory, open`

**Comment by ljharb** [comment]
Have you restarted atom since installing them?

**Comment by stephenkingsley** [comment]
thx! may be is this problem!

**Comment by josemigallas** [comment]
Having this issue now with VSCode:
**dependencies**
```
"eslint": "^4.19.1",
"eslint-config-airbnb": "^17.0.0",
```
**.babelrc**
```
{
    "extends": "airbnb",
    "rules": {
        ....
    }
}
```
