### ISSUE TITLE
Variable Ordering

### ISSUE THREAD

**Issue by merlinpatt** [airbnb/javascript#1045]
In your style guide, your only rule that is somewhat about variable order is to assign them where you need them.

If that rule is taken care of and you have multiple variable declarations, do you have an order preference? Alphabetical, logical (`start` before `end`), etc.

Same question applies to object key order and JSX attributes

**Comment by lencioni** [comment]
I'm not sure we have a preference in this style guide (I could be wrong!), but my personal preference is alphabetical because it is a simple and unambiguous rule that can be consistently and easily applied in all situations.

**Comment by ljharb** [comment]
As far as I'm aware, we do not have a preference for ordering of anything, except for "absolute imports/requires should come before relative imports/requires", and React component methods. 

Alphabetical certainly is simple and unambiguous, but is usually the kind of decision you want to make on a per-project level with the team.
