### ISSUE TITLE
eslint-config-airbnb not showing any problems

### ISSUE THREAD

**Issue by lbalceda** [airbnb/javascript#1046]
Not sure if i'm including the airbnb eslint plugin incorrectly, but it doesn't seem to be hitting any of the rules. While running just `./node_modules/.bin/eslint  < file name >`  it only seems to be picking up the jsx-a11y rules.

e.g. it will only return
```  
  31:19  error  Links must not point to "#". Use a more descriptive href or use a button instead  jsx-a11y/href-no-hash
  41:25  error  Links must not point to "#". Use a more descriptive href or use a button instead  jsx-a11y/href-no-hash
  45:19  error  Links must not point to "#". Use a more descriptive href or use a button instead  jsx-a11y/href-no-hash
  54:25  error  Links must not point to "#". Use a more descriptive href or use a button instead  jsx-a11y/href-no-hash 
```
Meanwhile, while using eslint-loader I get closer to 80 problems / what I expected, including things like `max-len` `indent`, `quotes` , etc.

My .eslintrc.json:

```{
    "extends": "airbnb",
    "plugins": [
        "react",
        "jsx-a11y",
        "import"
    ]
}```

From my package.json:
```  
    "eslint": "^3.4.0",
    "eslint-config-airbnb": "^10.0.1",
    "eslint-loader": "^1.5.0",
    "eslint-plugin-import": "^1.14.0",
    "eslint-plugin-jsx-a11y": "^2.2.0",
    "eslint-plugin-react": "^6.2.0",
```

**Comment by ljharb** [comment]
try adding `"root": true` to your `.eslintrc`, in case it's picking up `.eslintrc` files higher up - beyond that, does `npm ls` exit zero? What's `./node_modules/.bin/eslint --version`?

**Comment by lbalceda** [comment]
adding "root: true" didn't seem to change anything

```
{
	"extends": "airbnb",
	"root": true,
	"plugins": [
		"react",
		"jsx-a11y",
		"import"
	]
}
```

`npm ls` has exit code 0 . I've put the output here if that would be helpful [https://gist.github.com/lbalceda/6bda8f6efce3c93327c52cc9594e347b](https://gist.github.com/lbalceda/6bda8f6efce3c93327c52cc9594e347b) 

eslint version returns `v3.4.0`

**Comment by ljharb** [comment]
And you don't have any other `.eslintrc` files anywhere, nor any inline eslint override comments in the file you're trying to lint?

**Comment by lbalceda** [comment]
It appears my configuration was set up correctly, however my setup for `eslint-loader` was incorrect and causing confusion. It was running against already transpiled code vs running against source. Had to move it into a pre-loader

```
 module: {
    preLoaders: [
      {test: /\.js$/, loader: "eslint-loader", exclude: /node_modules/}
    ]
  }
```

Thank you for reaching out!

**Comment by iamyoki** [comment]
Try To Restart Eslint Server
