### ISSUE TITLE
Use "import/no-duplicates" instead of "no-duplicate-imports"

### ISSUE THREAD

**Issue by AlicanC** [airbnb/javascript#1054]
Both do the same thing except with [`import/no-duplicates`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-duplicates.md):
- Paths in the source code don't have to exactly match, they just have to point to the same module on the filesystem. (i.e. ./foo and ./foo.js)
- Flow type imports are distinguished from standard imports so we can `import` and `import type` from the same file.

**Comment by ljharb** [comment]
We already have `import/no-duplicates` enabled. Is there any downside to having both enabled?

**Comment by AlicanC** [comment]
If you have `no-duplicate-imports` enabled, you can't "`import` and `import type` from the same file".

**Comment by ljharb** [comment]
Ah, so this is specifically an issue with Flow types.

Since Airbnb doesn't currently use Flow, and my personal thinking is that files should export one thing (meaning the type should be in a separate file, if I understand correctly) - I think for now, this should be an app-level config that disables `no-duplicate-imports`.

**Comment by AlicanC** [comment]
> Airbnb doesn't currently use Flow

Oh, you should. It really speeds up development and prevents regression.

> this should be an app-level config that disables `no-duplicate-imports`

Sure. I haven't realised that you had both rules enabled (my bad) so it's not that big of a problem.

Having both enabled probably does nothing more than slowing down the lint though. Maybe you should consider disabling `no-duplicate-imports` anyways.
