### ISSUE TITLE
6.2 goes against 8.3 - string across multiple lines using string concatenation

### ISSUE THREAD

**Issue by Doweig** [airbnb/javascript#1058]
- [6.2](#strings--line-length) Strings that cause the line to go over 100 characters should not be written across multiple lines using string concatenation.

    > Why? Broken strings are painful to work with and make code less searchable.

    ```javascript
    // bad
    const errorMessage = 'This is a super long error that was thrown because \
    of Batman. When you stop to think about how Batman had anything to do \
    with this, you would get nowhere \
    fast.';

    // bad
    const errorMessage = 'This is a super long error that was thrown because ' +
      'of Batman. When you stop to think about how Batman had anything to do ' +
      'with this, you would get nowhere fast.';

    // good
    const errorMessage = 'This is a super long error that was thrown because of Batman. When you stop to think about how Batman had anything to do with this, you would get nowhere fast.';
    ```

  - [8.3](#arrows--paren-wrap) In case the expression spans over multiple lines, wrap it in parentheses for better readability.

    > Why? It shows clearly where the function starts and ends.

    ```js
    // bad
    [1, 2, 3].map(number => 'As time went by, the string containing the ' +
      `${number} became much longer. So we needed to break it over multiple ` +
      'lines.'
    );

    // good
    [1, 2, 3].map(number => (
      `As time went by, the string containing the ${number} became much ` +
      'longer. So we needed to break it over multiple lines.'
    ));
    ```
  - So can we or not break string across multiple lines?

**Comment by ljharb** [comment]
You should not. 8.3 simply needs updating.

**Comment by Doweig** [comment]
Would you suggest to replace the string example in 8.3 by another example of a long expression over multiple lines or removing 8.3 altogether?

**Comment by ljharb** [comment]
The former, it's still a useful example about arrow functions and implicit/explicit return.

**Comment by Doweig** [comment]
https://github.com/airbnb/javascript/pull/1065

**Comment by ljharb** [comment]
Thanks!
