### ISSUE TITLE
ESLint clash with prefer-template and quotes rules.

### ISSUE THREAD

**Issue by nruhe** [airbnb/javascript#1063]
Quotes rule overrides prefer-template, preventing \`\` from being used in the latest version of ESLint.

The allowTemplateLiterals [option](http://eslint.org/docs/rules/quotes#options) needs to be set in quote.
`"quotes": ["error", "single", { "allowTemplateLiterals": true }]`

**Comment by ljharb** [comment]
I'm not sure what you mean - the current config settings require that template literals only be used when there are newlines or interpolations. Otherwise, backticks should not be used.

**Comment by nruhe** [comment]
Woops! I had a misinterpretation of the effect of the `"allowTemplateLiterals": true` property due to a syntax mistake in my interpolation, causing it to be read as a string. This actually isn't a problem at all. I knew it seemed strange that nobody had reported it. Sorry about that!
