### ISSUE TITLE
Missing accumulator for reduce

### ISSUE THREAD

**Issue by bergus** [airbnb/javascript#1069]
In the [callback-return rule](/airbnb/javascript#arrays--callback-return), the `reduce` calls don't work and the examples appear to do different things anyway:
```js
// bad
const flat = {};
[[0, 1], [2, 3], [4, 5]].reduce((memo, item, index) => {
  const flatten = memo.concat(item);
  flat[index] = flatten;
});

// good
const flat = {};
[[0, 1], [2, 3], [4, 5]].reduce((memo, item, index) => {
  const flatten = memo.concat(item);
  flat[index] = flatten;
  return flatten;
});
```
Without `return`ing from the `reduce` callback, `memo` will be `undefined` and accessing `.concat` throws an exception.
Even in the "good" example, an initial value is missing, so `memo` is `undefined` at least in the first iteration.
I believe it should read
```
// bad
const flat = [];
[[0, 1], [2, 3], [4, 5]].forEach((item) => {
  flat = flat.concat(item);
});

// good
const flat = [[0, 1], [2, 3], [4, 5]].reduce((memo, item) => {
  return memo.concat(item);
}, []);
```
but maybe I'm missing altogether what the `flat` object is supposed to do in there and why `index` is used to assign to it.

**Comment by ljharb** [comment]
The "bad" example is bad because it doesn't return the accumulator.

When the initial value is omitted, the initial value is not `undefined` - it's the first item in the array - so the "good" example works perfectly.

**Comment by bergus** [comment]
Ah, I was under the expression that all the given examples would work the same, just that some were bad style and others were good style.
