### ISSUE TITLE
Error on style: PropTypes.object

### ISSUE THREAD

**Issue by ButuzGOL** [airbnb/javascript#1078]
Can somebody give a hint how to prevent error if component has 
style: PropTypes.object
?

**Comment by ljharb** [comment]
At the moment, you'd use an ignore comment to disable the rule for that line. Better, would be to use `.objectOf` and specify that it can only take strings, or an object of strings.

**Comment by sotayamashita** [comment]
@ButuzGOL Here is eslint rule. https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md
