### ISSUE TITLE
MultiLine String Concat Marked as Good Example

### ISSUE THREAD

**Issue by lawlerskates12** [airbnb/javascript#1081]
Hello,

In 6.2 the guidelines state that long strings shouldn't be broken up over multiple lines:

    // bad
    const errorMessage = 'This is a super long error that was thrown because ' +
    'of Batman. When you stop to think about how Batman had anything to do ' +
    'with this, you would get nowhere fast.';

Then in 8.4 the guidnelines show a good code exmple with this exact practice:

    // good
    [1, 2, 3].map(number => (
    `A long string with the ${number}. It's so long that we've broken it ` +
    'over multiple lines!'
    ));

**Comment by ljharb** [comment]
Thanks, there's still a few of these left to clean up.

**Comment by ljharb** [comment]
Fixed in a86d546c618f596003a7c6dbe0ee3d6ca61fe120
