### ISSUE TITLE
Configuration for rule "eol-last" is invalid: Value "always" must be an enum value.

### ISSUE THREAD

**Issue by chaintan17** [airbnb/javascript#1088]
Hi guys,
Look like this commit (https://github.com/airbnb/javascript/commit/e5f4eb57b4733d0b338f120842e719f6df51c035) make the lint failed.

```
Referenced from: /Users/xxx/node_modules/eslint-config-airbnb-base/index.js
Referenced from: airbnb
Referenced from: /Users/xxxx/package.json
Error: /Users/xxxx/node_modules/eslint-config-airbnb-base/rules/style.js:
	Configuration for rule "eol-last" is invalid:
	Value "always" must be an enum value.

![image](https://cloud.githubusercontent.com/assets/2979072/18807813/45b79cc6-827b-11e6-8f1f-44af40294e2b.png)
```

I will try submit a pull request.

**Comment by chaintan17** [comment]
ah... some how, it show on my `node_modules/eslint-config-airbnb/package.json` that i'm on `version 11.1.0` but look like the source code is `11.2.0`... for example, `/rules/style.js:29` is `'eol-last': ['error', 'always'],`

strange...

**Comment by danielbayerlein** [comment]
Same here: https://github.com/danielbayerlein/wintersmith-pattern-library/pull/2

**Comment by chaintan17** [comment]
@danielbayerlein i think,  in your case, you should also upgrade eslint to 3.6. The build should pass.

**Comment by danielbayerlein** [comment]
@chaintan17 You're right! Thank you for your support.

**Comment by ljharb** [comment]
Upgrading eslint is the solution to the OP as well.

**Comment by chaintan17** [comment]
@ljharb I still want to remain in `11.1.0` and eslint `3.5.0` because one of my dependency still dependent on eslint 3.5.0 (https://github.com/stylelint/stylelint)

But somehow, even set package.json to `v11.1.0`, the source code look like `v11.2.0`

```
    "eslint": "3.5.0",
    "eslint-config-airbnb": "11.1.0",
```

Do you have any idea please ?

**Comment by ljharb** [comment]
@chaintan17 That should work fine - try `npm prune && npm install`?

**Comment by chaintan17** [comment]
@ljharb no, it's not working.
Look like because it's trying to install `eslint-config-airbnb-base@7.2.0` while installing `eslint-config-airbnb@11.1.`
Please see below picture.
And make this corrupt.

Is it because changes in `eslint` suppose to be for major release ?
what do you think ?

![image](https://cloud.githubusercontent.com/assets/2979072/18813609/ff3bcc7c-8329-11e6-9940-5b0a998b27ad.png)

**Comment by ljharb** [comment]
@chaintan17 aha - try adding `eslint-config-airbnb-base` as a dependency locked to `7.1.0`?

**Comment by chaintng** [comment]
ah, yes! it works! 
thank you :))

**Comment by hozefaj** [comment]
I am seeing this error in spite of being on the latest version for both

```
"eslint": "^3.6.1",
"eslint-config-airbnb": "^11.2.0",
```

However locking `eslint-config-airbnb-base` to version `7.1.0` fixed the issue. But this does not seem scalable every time I do a `npm install`.

**Comment by ljharb** [comment]
Are you sure you are not using a global install? Try `npm uninstall -g eslint`

**Comment by nolandg** [comment]
Had exact same issues. I do not have it install globally. The eslint-config-airbnb-base 7.1.0 fix worked great. Not ideal though.

**Comment by ljharb** [comment]
@nolandg @hozefaj how are you running eslint? often `gulp-eslint` will bring in an older version of eslint, despite having it at the top level.

**Comment by hozefaj** [comment]
@ljharb Using `eslint` as a `devDependencies` within my application. Configured it to run with `Atom` editor and show warnings on save. I do have a `gulp` lint task, but the issue I see is thrown by the editor itself.

**Comment by ljharb** [comment]
@hozefaj the only thing I've seen with Atom is either mistakenly using a global eslint, or, not restarting Atom after updating node modules. Beyond that, unless you can reproduce the error on the command line directly, I'd file a bug with Atom.

**Comment by hozefaj** [comment]
@ljharb Thanks. You are right, it was Atom causing the issue.

**Comment by eugef** [comment]
I had the same error and updating `gulp-edlint` to the version `3.0.1` helped me.
