### ISSUE TITLE
Invalid import/extensions

### ISSUE THREAD

**Issue by ianaya89** [airbnb/javascript#1092]
Hey Guys, after update to version `8.0.0` eslint starts throwing this error message:

```
Error: /Users/ianaya89/Development/projects/fintechdev/MerchantSPA/node_modules/eslint-config-airbnb-base/rules/imports.js: Configuration for rule "import/extensions" is invalid: Value "always,[object Object]" has more items than allowed.
```

I try to override it in my rules file like this: `"import/extensions": 0`, but I get the same error.

I could not find documentation about the issue, any thoughts?

**Comment by ljharb** [comment]
You may not have updated `eslint-plugin-import` - can you use the install command in the readme of the package, so that all the proper peer deps are installed?

**Comment by ianaya89** [comment]
Thanks, that worked!
