### ISSUE TITLE
Why object should add a plus comma for the final property?

### ISSUE THREAD

**Issue by OneNewLife** [airbnb/javascript#1093]
Just like this:

``` javascript
var obj = {
  "a": 1,
  "b": 2,
  "c": 3,
};
```

Why Airbnb choose to add a plus comma for the final property?

**Comment by alexeyraspopov** [comment]
[This](http://eslint.org/docs/rules/comma-dangle) page has good explanation.

**Comment by ljharb** [comment]
As does [our guide](https://github.com/airbnb/javascript#commas--dangling) - primarily it's to minimize git diffs.
