### ISSUE TITLE
Is there also a generated complete version of the .eslintrc I could you?

### ISSUE THREAD

**Issue by pkyeck** [airbnb/javascript#1098]
I'm running my javascript code inside docker containers and mount a volume into the container for local development - so there are no `node_modules` on my local machine. Therefore I'd need a generated `.eslintrc` file that I could just place in the project's root folder so that SublimeText could pick that up.

Or am I missing something else? I haven't used eslint in a while, and never with extending other files ...

**Comment by ljharb** [comment]
The volume you mount would contain the `node_modules`, since it would be the project root. There's no practical way to usefully develop a JS app without access to all the node modules it depends on, with docker or otherwise.
