### ISSUE TITLE
Consider disabling react/no-unused-prop-types

### ISSUE THREAD

**Issue by billyjanitsch** [airbnb/javascript#1099]
The [react/no-unused-prop-types](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unused-prop-types.md) rule is currently [quite buggy](https://github.com/yannickcr/eslint-plugin-react/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20no-unused-prop-types). In combination with the recently-enabled ([here](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/react.js#L43)) [react/forbid-prop-types](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-prop-types.md), it makes writing propTypes for objects tricky.

For example, since `PropTypes.object` is forbidden, there's no way to get around yannickcr/eslint-plugin-react#833 (using `PropTypes.shape`) without disabling one of the two rules.

Would you consider disabling the rule until its kinks are ironed out?

**Comment by ljharb** [comment]
That does seem reasonable - there have been quite a lot of bugs around that rule.
