### ISSUE TITLE
Correctness of react/no-unescaped-entities

### ISSUE THREAD

**Issue by billyjanitsch** [airbnb/javascript#1100]
I wanted to raise a discussion of [react/no-unescaped-entities](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unescaped-entities.md), which was included in 12.0.0.

I think that `PropTypes.array`/`object`/`any` have (limited) valid use cases. Consider a basic custom select component:

``` js
const Select = props =>
  <Dropdown label={props.value.display}>
    {props.options.map(option =>
      <div onClick={() => props.onChange(option)}>{option.display}</div>
    )}
  </Dropdown>

Select.propTypes = {
  options: PropTypes.arrayOf(PropTypes.shape({
    display: PropTypes.string,
    value: PropTypes.any, // value can be anything
  })).isRequired,
  onChange: PropTypes.func.isRequired,
  value: PropTypes.shape({
    display: PropTypes.string,
    value: PropTypes.any, // value can be anything
  }).isRequired,
}
```

In this case, you actually _want_ the component to accept values of any type. Since it never renders them, there's no potential for type errors.

In general, as long as you aren't using these prop types to mean "a particular type of array/object/etc., but I was too lazy to figure out which one", they seem correct to me.

I'm guessing that you'll consider this enough of an exception to suggest disabling the rule on a case-by-case basis, but I'm finding quite a few occurrences of these in our codebase and at least wanted to ask for your opinion.

**Comment by ljharb** [comment]
Why would you want anything? It's a form input value, which can only be a string or a number.

**Comment by ljharb** [comment]
Happy to discuss further - at the moment the advice is to use eslint disable comments for the places you do want `PropTypes.any`.
