### ISSUE TITLE
eslint-plugin-import 2.0.0

### ISSUE THREAD

**Issue by tomkel** [airbnb/javascript#1104]
With new rules [`no-webpack-loader-syntax`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-webpack-loader-syntax.md) and [`no-unassigned-import`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unassigned-import.md).

[Changelog](https://github.com/benmosher/eslint-plugin-import/blob/master/CHANGELOG.md)

**Comment by ljharb** [comment]
Duplicate of #1101

**Comment by ljharb** [comment]
`eslint-config-airbnb` `v13.0.0` is now released.
