### ISSUE TITLE
Lots of overlap between airbnb JavaScript & Idiomatic JS - perhaps merge?

### ISSUE THREAD

**Issue by mikemaccana** [airbnb/javascript#111]
[Idiomatic.JS](https://github.com/rwaldron/idiomatic.js), derived from the JQuery style guidelines, is already a popular style with a *lot* of contribution from the wider JS community - the airbnb guide seems quite similar but a little shorter. 

There's good stuff in each that is missing from the other.

Both guides have been widely translated, but into a different set of languages. 

Could it be worth merging the airbnb styleguide into Idiomatic? Or vice versa?

Just a thought.

**Comment by hshoff** [comment]
Hi @mikemaccana, thanks for checking out the guide and apologies for the delayed response. There's enough room in the javascript world for multiple style guides. The important part is consistency.

**Comment by mikemaccana** [comment]
It doesn't really seem like you actually read what I wrote above, but ¯\_(ツ)_/¯

**Comment by goatslacker** [comment]
cc @rwaldron
