### ISSUE TITLE
Update eslint-plugin-import version

### ISSUE THREAD

**Issue by wagerfield** [airbnb/javascript#1112]
**Version:** 

```bash
eslint-config-airbnb@12.0.0
```

**Issue:**
```bash
npm WARN eslint-config-airbnb@12.0.0 requires a peer of eslint-plugin-import@^1.16.0 but none was installed
```

The latest version of `eslint-plugin-import` is now `2.0.0`, so when installing `eslint-plugin-import`, `eslint-config-airbnb`'s, peerDependency of `eslint-plugin-import@^1.16.0` is not satisfied.

Please could you update the peerDependency to `^2.0.0`?...or is there a reason why you have to use `^1.16.0`?

**Comment by ljharb** [comment]
Resolved by #1107 

The reason is that it's a breaking change, it just came out, and we haven't updated yet.

It's recommended to use the bash command in the readme of `eslint-config-airbnb` which will install the peer dependencies for you, at the proper version numbers.
