### ISSUE TITLE
no-unused-prop-types invalid error

### ISSUE THREAD

**Issue by schuchowsky** [airbnb/javascript#1116]
I have a component which receive a prop named _params_ which is a shape with the attribute **name**.

I use this prop in an TextField element,, but it stills give me the **no-unused-prop-types** error.

Please refer to the code below

```javascript
const ClientFilters = ({ fetch, fetching, params, onFilterNameChange }) => (
  <form style={styles.container} onSubmit={() => fetch()}>
    <TextField
      hintText="Pesquisa por nome"
      floatingLabelText="Nome"
      floatingLabelFixed
      value={params.name}
      onChange={onFilterNameChange}
    />
    <RaisedButton
      secondary
      icon={<FontIcon className="material-icons">search</FontIcon>}
      style={styles.searchButton}
      type="submit"
      disabled={fetching}
    />
  </form>
)

ClientFilters.propTypes = {
  fetch: PropTypes.func.isRequired,
  fetching: PropTypes.bool.isRequired,
  params: PropTypes.shape({
    name: PropTypes.string.isRequired,
  }),
  onFilterNameChange: PropTypes.func.isRequired,
}

export default ClientFilters
```

Any ideas on that? Is it a bug or am I doing anything wrong?
Thanks

**Comment by schuchowsky** [comment]
Here is the atom linter-eslint validation error:

![image](https://cloud.githubusercontent.com/assets/13025585/19223873/871a5c0e-8e50-11e6-8d0a-f020af7549e6.png)

**Comment by ljharb** [comment]
Please file this issue on [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react/issues/new), and be sure you're on v6.4.0 first (which fixed a number of bugs with this rule)

**Comment by schuchowsky** [comment]
Ok, I'll create there. And yes, I'm on v6.4.0. Thanks!
