### ISSUE TITLE
config install scripts do not force latest config version

### ISSUE THREAD

**Issue by OttlikG** [airbnb/javascript#1121]
I'm getting this error:

Error: eslint-config-airbnb/rules/react: Configuration for rule "react/no-did-mount-set-state" is invalid: Value "allow-in-func" must be an enum value.

Referenced from: airbnb Referenced from: /.../project/.eslintrc

This is the default: 'react/no-did-mount-set-state': [2, 'allow-in-func']
When I set this to: 'react/no-did-mount-set-state': 2

everything is fine.

**Comment by ljharb** [comment]
What version of eslint? Are you using a global or a local eslint?

**Comment by OttlikG** [comment]
I use the local one with this version: eslint@3.7.1

**Comment by ljharb** [comment]
What's your package.json look like?

**Comment by OttlikG** [comment]
```javascript
"devDependencies": {
  "babel-eslint": "^6.1.2",
  "eslint": "^3.7.1",
  "eslint-config-airbnb": "^1.0.2",
  "eslint-plugin-import": "^1.16.0",
  "eslint-plugin-jsx-a11y": "^2.2.3",
  "eslint-plugin-react": "^6.4.1",
}
```

Or which part are you interested in?

**Comment by ljharb** [comment]
That's an ancient eslint-config-airbnb. Please update to the latest, using the bash command in the read me.

**Comment by OttlikG** [comment]
I've used the script that you've provided here:
https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb

Tomorrow I'll try to manually upgrade.

**Comment by ljharb** [comment]
That script installed v1.0.2 of the config plugin? O.o

**Comment by OttlikG** [comment]
```
(
subsh>   export PKG=eslint-config-airbnb;
subsh>   npm info "$PKG" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs npm install --save-dev "$PKG"
subsh>
)
```
project_name@ /path/to/project
├── eslint@3.7.1 
├── eslint-config-airbnb@1.0.2 
├── eslint-plugin-import@1.16.0 
├── eslint-plugin-jsx-a11y@2.2.3 
├── eslint-plugin-react@6.4.1 

I ended up to manually install the latest version of eslint-config-airbnb (^12.0.0), and now works fine.

**Comment by ljharb** [comment]
Thanks, I'll update the script so it always installs the latest.
