### ISSUE TITLE
Pure function fat arrow + jsx in react native

### ISSUE THREAD

**Issue by vzhen** [airbnb/javascript#1124]
I already added .js in airbnb filename extension. However

```
const Address = (props) => {   // Error here, unexpected block statement
  return (
    <View>
      <Text>{props.data.line1}</Text>
    </View>
  );
}
```

If i add parenthesis

```
const Address = (props) => ({
  return (
    <View>  // Error here, Parsing error: unexpected token <
      <Text>{props.data.line1}</Text>
    </View>
  );
});
```

Any idea how to fix this error?

**Comment by petersendidit** [comment]
The code doesn't need the extra `{` `}`. The just wrapping the jsx in `(` `)` will do the trick.

```jsx
const Address = (props) => (
  <View>
    <Text>{props.data.line1}</Text>
  </View>
);
```

But if you are trying to follow the style guide, the [Class vs React.createClass vs stateles](https://github.com/airbnb/javascript/tree/master/react#class-vs-reactcreateclass-vs-stateless) section states that it really should look like this:

```jsx
function Address(props) {
  return (
    <View>
      <Text>{props.data.line1}</Text>
    </View>
  );
}

**Comment by vzhen** [comment]
Thank you, it works
