### ISSUE TITLE
Inconsistency on code examples

### ISSUE THREAD

**Issue by Goncalom** [airbnb/javascript#1125]
On line 15.3, "Use shortcuts" on the airbnb.io it says:
http://airbnb.io/javascript/#comparison--shortcuts

```
// bad
if (collection.length > 0) {
  // ...stuff...
}

// good
if (collection.length) {
  // ...stuff...
}
```

But on the github page, it is reversed:
https://github.com/airbnb/javascript#comparison--if

```
// bad
if (collection.length) {
  // ...stuff...
}

// good
if (collection.length > 0) {
  // ...stuff...
}
```
Which is the correct one?

**Comment by ljharb** [comment]
The repo is correct - I have to manually update the airbnb.io page. I'll do that now.

**Comment by rudzikdawid** [comment]
![just learn this](https://i.stack.imgur.com/35MpY.png)

**Comment by ljharb** [comment]
That is from http://zero.milosz.ca/ but I'm not sure why you posted it here?
