### ISSUE TITLE
Upgrade eslint-config-airbnb (not -base) to eslint-plugin-import@^2.0.1

### ISSUE THREAD

**Issue by elliottsj** [airbnb/javascript#1127]
#1101 upgraded eslint-config-airbnb-base, but eslint-config-airbnb is still on eslint-plugin-import@^1.16.0

**Comment by ljharb** [comment]
That's intentional, until eslint-config-airbnb-base gets a semver-major release.

**Comment by ljharb** [comment]
`eslint-config-airbnb` `v13.0.0` is now released.
