### ISSUE TITLE
Question about modifying with forEach

### ISSUE THREAD

**Issue by controversial** [airbnb/javascript#1130]
The example for 13.6 contains the snippet
```javascript
array.forEach((value) => {
  value += 1;
});
```
However, this style guide forbids modifying the value of an element.

What's the recommended way to change a property of all elements in an array? I'm working with changing the `.style` of DOM nodes in an array, so using `.map()` doesn't really feel right to me...

**Comment by ljharb** [comment]
Whoops, that's not a very good example :-) I'll fix it.

In the case of DOM nodes, because "the DOM", you can't avoid mutation. So, in that case only, it'd be appropriate to use an inline eslint override comment. At Airbnb we don't tend to run into that problem because we use React.

**Comment by controversial** [comment]
Ok. Thanks for the swift response!
