### ISSUE TITLE
Peer-depend on eslint-plugin-import@2.0.0

### ISSUE THREAD

**Issue by callumlocke** [airbnb/javascript#1146]
would would help reduce annoying warnings if eslint-config-airbnb could update its eslint-plugin-import peer dependency to 2.0.0

**Comment by ljharb** [comment]
What warnings? Until eslint-config-airbnb is published to support v2, you're supposed to still have v1.

**Comment by ljharb** [comment]
At any rate this is intentionally being held off, blocked on https://github.com/benmosher/eslint-plugin-import/pull/630 as well as a few eslint-plugin-react bugs.

**Comment by tleunen** [comment]
@ljharb Maybe you could create an issue with a v13 milestone with the list of internals and externals tickets you'd like to have fixed before releasing a v13? It should help people find out why the react config is still v12 based on base v8 and import 1.16

**Comment by ljharb** [comment]
I suppose I can do that; but it's clear people aren't doing any searching before filing issues or making PRs, so I doubt that would help much except allow for a terser and more informative way to close said issues/PRs :-p

**Comment by pozylon** [comment]
2.1.0 is here with merged https://github.com/benmosher/eslint-plugin-import/pull/630

**Comment by ljharb** [comment]
@pozylon thanks, i'm aware, since it's my PR

**Comment by ljharb** [comment]
`eslint-config-airbnb` `v13.0.0` is now released.
