### ISSUE TITLE
Why is no-loop-func used alongside no-var?

### ISSUE THREAD

**Issue by callumlocke** [airbnb/javascript#1147]
Why require `no-loop-func` if you also require `no-var`?

The [docs for no-loop-func](http://eslint.org/docs/rules/no-loop-func) explain that it's safe to define a function inside a loop, providing you use `const` and `let` instead of `var`:

```js
// In this case, each function created within the loop returns a
// different number as expected:
for (let i = 0; i < 10; i++) {
    funcs[i] = function() {
        return i;
    };
}
```

Here's a real-world example that would be less readable if I followed no-loop-func:

```js
for (const bucketId of bucketIds) {
  context[bucketId] = states
    .map(state => ({ // eslint complains about this
      code: state.code.toUpperCase(),
      winner: state.winner ? state.winner.toLowerCase() : null,
    }))
  ;
}
```

Is there a reason I'm missing?

**Comment by ljharb** [comment]
a) you should file an issue on no-loop-func to allow that case, and b) there are many browsers, spanning many many years, that had incorrect semantics for `let`, so it's still not safe to rely on that unless you're transpiling.

That said, the style guide absolutely disallows all loops, including for..of, so this shouldn't even come up :-)

**Comment by callumlocke** [comment]
>  style guide absolutely disallows all loops

do you mean functions in loops? or loops?

**Comment by ljharb** [comment]
Loops, in any form, of any kind. (`forEach`, `map`, and friends aren't loops, they're iterations)

**Comment by callumlocke** [comment]
oh wow. I had no idea. Any plan to enforce that with the eslint config (if it's even possible to ban all loops)?

**Comment by ljharb** [comment]
The base eslint config already bans everything except a normal for loop (including your for..of loop) - the next release of the main eslint config will do so as well.

Banning normal for loops is a bit restrictive due to the lack of a `range` builtin in JS, but eventually that will be included too.

**Comment by callumlocke** [comment]
Interesting. What about cases where you need to use `await` or `yield` inside a loop?

**Comment by ljharb** [comment]
The guide also disallows generators, so no `yield`, and we don't yet recommend using `await`, because they can only be reliably transpiled atm with `regenerator-runtime`.

However, if you show me a non-contrived example of either, I'll be happy to show you a better one that doesn't need a loop.

**Comment by callumlocke** [comment]
OK right now I can't think of a good example that couldn't reasonably be done without loops. I'll come back to you if I think of one!

btw what do you mean by the lack of a 'range' builtin? What would that do?

**Comment by ljharb** [comment]
`range(0, 3)` would produce `[0, 1, 2]`.

**Comment by alexlukelevy** [comment]
How about within `while` loops?

**Comment by ljharb** [comment]
@alexlukelevy what use case do you have for that?

**Comment by alexlukelevy** [comment]
I'm performing a BFS of a graph using a queue, then for the node that is dequeued at the beginning of the loop I want to run some function over it's ancestors that also requires a handle on the node itself (i.e. a closure). At the end of the loop I enqueue any descendants.

Something like the below... 

```js
const queue = [root];

while(queue.length > 0) {
  const node = queue.shift();

  node.ancestors.forEach((ancestor) => {
    console.log(`${ancestor.name} is an ancestor of ${node.name}`);
  });
  
  node.descendants.forEach((descendant) => {
    queue.push(descendant);
  });
}
```

Airbnb base eslint config allows `while` loops though right? Curious to see if this could be rewritten without a `while` and still maintain readability.

**Comment by ljharb** [comment]
No, the guide disallows all loops (although the linter config may not forbid them).

**Comment by alexlukelevy** [comment]
@ljharb how would you rewrite the above then?

**Comment by ljharb** [comment]
@alexlukelevy 
i dunno, something like this:
```js
function getDescendants(node)
  node.ancestors.forEach((ancestor) => {
    console.log(`${ancestor.name} is an ancestor of ${node.name}`);
  });

  return node.descendants.reduce((acc, descendant) => (
    acc.concat(descendant, getDescendants(descendant))
  ), []);
}

queue.reduce((acc, item) => acc.concat(item, getDescendants(item)), []);
```
(i'm not super clear on what you're trying to do here, so my exact code might not work out of the box, but the concept hopefully comes across)

**Comment by dancherb** [comment]
@ljharb why are loops so bad? (feel free to just link me to an article). is it mainly code readability? I've heard performance-wise a manual for loop beats e.g. forEach/filter/map.

**Comment by ljharb** [comment]
@dancherb Loops fail to clearly signal the intention of your code, and as such should be avoided whenever possible (prefer higher-order functions, such as .map, .reduce, .filter, ...). See also: http://qr.ae/RNMEGA and https://gist.github.com/robotlolita/7643014
