### ISSUE TITLE
jsx-a11y/anchor-has-content throws error

### ISSUE THREAD

**Issue by andresmijares** [airbnb/javascript#1163]
For some reason, when I run the package "as it is", it throw 

Referenced from: airbnb
...  Configuration for rule "jsx-a11y/anchor-has-content" is invalid:
        Value "" is the wrong type.

I know this is not the jsx-a11y repo, but, If I run it separate, it works fine.

No rules were added to the .eslintrc file

Any ideas?

**Comment by raspo** [comment]
With version 3.0.0 `eslint-plugin-jsx-a11y` updated their schema to accept objects ([changelog](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/CHANGELOG.md)).

We'll have to stick to `eslint-plugin-jsx-a11y@2.2.3` until `eslint-config-airbnb` supports the new API.

**Comment by ljharb** [comment]
Please use the install command in the package read me to ensure the correct peer dep versions are installed.

**Comment by barbalex** [comment]
@ljharb: On what systems does that install command work? Does not seem to work on windows 10

**Comment by ljharb** [comment]
@barbalex it works on everything but windows. If you're on windows (unless you can suggest a command that would work), you'll need to look at the package.json, look at all the peerDependencies and their versions, and manually add them to your own package.json as explicit devDependencies (which is how all peerDeps on npm work, absent a command like this)

**Comment by p4bloch** [comment]
Running `npm i -D eslint-plugin-jsx-a11y@2.2.3` solved this for me on OSX, as suggested by @raspo

**Comment by zachlysobey** [comment]
@ljharb, please excuse me if I'm being dense... but I don't see any "install command in the package read me"

I searched the following for the word "install" as well as "npm i" and didn't find anything

https://github.com/airbnb/javascript/blob/master/README.md

**Comment by gergoerdosi** [comment]
You can find it in the README of the package:

https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb#eslint-config-airbnb-1

**Comment by zhangolve** [comment]
I also have the problems ,thank you so I can solve the problem.
here is my config
```
 "eslint": "3.x",
  "eslint-config-airbnb": "latest",
   "eslint-plugin-import": "^2.2.0",
   "eslint-plugin-jsx-a11y": "^2.x.x",
   "eslint-plugin-react": "4.x",
```

I hope this can help others.lol

**Comment by ljharb** [comment]
@zhangolve if you follow the instructions in the package readme, you'll never have the wrong peer dep versions installed.

**Comment by zhangolve** [comment]
@ljharb   Actually ，I just want to update my repo package , by the way ,here is my previous config
```
"eslint": "2.x",
 "eslint-config-airbnb": "6.x",
 "eslint-plugin-react": "4.x",
```
When I found OMG  eslint-config-airbnb had published v13.0 ,I realized I should update it .

But when I just update eslint-config-airbnb to the latest version.I found error tips show me I have to install 
jsx-a11y.And when I installed the package of the latest version,there was another error like the issue mentioned .

I have read the [eslint-config-airbnb](https://www.npmjs.com/package/eslint-config-airbnb) usage ,maybe not understood it .

anyway ,thank you for all help.

**Comment by ljharb** [comment]
@zhangolve yes, but the way to do that is to use the `npm install` command under "Ensure packages are installed with correct version numbers by running:".

**Comment by colsson22** [comment]
I ran the install command from the airbnb README and this problem remains in the atom eslinter.
- Are the packages in that command currently working?
- Could my problem be because of some global npm install, how is that removed?

**Comment by ljharb** [comment]
@colsson22 you need to restart atom after any node_modules changes.

**Comment by colsson22** [comment]
@ljharb I did restart atom several times, but that seems like a probable explanation. Thank you for answering me 👍

**Comment by samkelleher** [comment]
I just did a fresh install (using the config script in the readme) v4 of `eslint-plugin-jsx-ally` was installed and v4.0.0 is listed as a valid peer dependency.

However, I still get the error.

**Comment by ljharb** [comment]
@samkelleher are you sure you're running your local eslint, and not the global one?

**Comment by samkelleher** [comment]
Wow super quick @ljharb  thanks. Yes installed it locally. I thought it would be weird for such a problem to to happen so I deleted my node_modules and tried again, now it works. Bizarre. I should have have tried this before commenting, came back here to delete the comment and you had already replied! Thanks. 👏🏻
