### ISSUE TITLE
phpstorm airbnb codingstyle

### ISSUE THREAD

**Issue by SerkanSipahi** [airbnb/javascript#1164]
@ljharb hi there, thanks for the awesome codingstyle-guideline :) My question, it is possible to import the codingstyle to phpstorm?

**Comment by ljharb** [comment]
As long as phpstorm supports eslint, then yes. I'm not sure how to integrate it since I don't use phpstorm.

**Comment by SerkanSipahi** [comment]
i think its support eslint. Where can i find the eslint file?

**Comment by SerkanSipahi** [comment]
https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base ?

**Comment by ljharb** [comment]
https://npmjs.com/eslint-config-airbnb-base. Instructions are in the readme.

**Comment by SerkanSipahi** [comment]
@ljharb thanks :)
see also (How to set up ESLint with Airbnb):
* https://www.themarketingtechnologist.co/how-to-get-airbnbs-javascript-code-style-working-in-webstorm/
* https://www.themarketingtechnologist.co/eslint-with-airbnb-javascript-style-guide-in-webstorm/
