### ISSUE TITLE
Where to disable: A base filename should exactly match the name of its default export.

### ISSUE THREAD

**Issue by jirikolarik** [airbnb/javascript#1165]
Hey,

I need to revert this rule: https://github.com/airbnb/javascript#naming--filename-matches-export but I cannot find where it is.

Does anyone know? 

Thanks

**Comment by ljharb** [comment]
We don't yet have a rule that enforces that. Can you provide the full error you're getting?

**Comment by jirikolarik** [comment]
You're absolutely right, my bad. I assumed that wrongly by going though the docs. Thanks!
