### ISSUE TITLE
ignore 'import/no-extraneous-dependencies' devDependencies checking for webpack files?

### ISSUE THREAD

**Issue by chentsulin** [airbnb/javascript#1168]
Maybe `gulpfile.js`, `Gruntfile` or other task runner files also can be listed to ignore.

```js
'import/no-extraneous-dependencies': ['error', {
  devDependencies: [
    'spec/**', 
    'test/**', 
    'tests/**', 
    '**/__tests__/**',
    'webpack.config.js',
    'webpack.config.*.js',
    'gulpfile.js',
    'Gruntfile',
  ],
  optionalDependencies: false,
}],
```

Any feedback?

**Comment by ljharb** [comment]
That sounds like a great idea. I'd be happy to accept a PR.

**Comment by Willibaur** [comment]
Hi all,
I've been through many of the Issues on this repo, and could not find what I'm looking for so I'm going to leave my question here, I have this rule in my `.eslintrc.js`

`'import/no-extraneous-dependencies': ["error", { devDependencies: true, }],`

But is still giving my a bunch of errors, all of them like this one

` 1:1  error  'ember' should be listed in the project's dependencies. Run 'npm i -S ember' to add it  import/no-extraneous-dependencies`

Any help would be appreciated
Thanks in advance

**Comment by ljharb** [comment]
@Willibaur a new issue on eslint-plugin-import is the appropriate place to file that.

**Comment by Willibaur** [comment]
Thanks @ljharb I did that, so answer for this can be found here 
https://github.com/benmosher/eslint-plugin-import/issues/422#issuecomment-292606152
just in case some else has the same problem.
