### ISSUE TITLE
Extend `import/no-extraneous-dependencies` ignore list

### ISSUE THREAD

**Issue by andrepolischuk** [airbnb/javascript#1174]
What do you think about adding follow patterns to ignore list?

```js
'test.js',
'test-*.js',
'**/*.test.js',
```

Like in [AVA](https://github.com/avajs/ava-files/blob/master/index.js#L22-L26)

**Comment by ljharb** [comment]
Those are some pretty broad patterns :-/ but sure, I'd be open to adding them. We should probably add comments to that list to explain the source of each group of those patterns.
