### ISSUE TITLE
UNMET PEER DEPENDENCY with eslint@^3.9.1

### ISSUE THREAD

**Issue by zz-zhangzhao** [airbnb/javascript#1176]
* node: v6.9.1
* npm: v3.10.8

I install the lastest version of eslint in global first. And then I install the eslint-config-airbnb.But there are something trouble with it :
![image](https://cloud.githubusercontent.com/assets/18140164/20238599/0df62cfa-a92a-11e6-8a06-a1bc2efdbf7e.png)

I try to `npm uninstall -g eslint-config-airbnb`, `npm cache clean` and reinstall again . It doesn't worked for me.

Is there anything trouble with the version number in the `package.json`?

sorry for bothering..

**Comment by zz-zhangzhao** [comment]
solved it by:
```
(
  export PKG=eslint-config-airbnb;
  npm info "$PKG@latest" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs  npm install -g "$PKG@latest"
)
```

**Comment by ljharb** [comment]
Nothing should be installed globally; eslint and all the relevant deps should only be installed locally, in each project that requires it.

Indeed though, the command in the readme is the way to ensure the right peer dep versions are installed.
