### ISSUE TITLE
Configuration for rule "func-name-matching" is invalid

### ISSUE THREAD

**Issue by astanciu** [airbnb/javascript#1179]
Error:.../node_modules/eslint-config-airbnb-base/rules/style.js: Configuration for rule "func-name-matching" is invalid: Value "always,[object Object]" has more items than allowed. Value "always" is the wrong type.

Not sure what happened here, but suddenly this started happening.

**Comment by ljharb** [comment]
Run the install command in the readme for eslint-config-airbnb-base to ensure your peer dependencies are correct - also make sure you've restarted your editor (like Atom) if you're using one.
