### ISSUE TITLE
[bug] please update npm package's dist

### ISSUE THREAD

**Issue by geminiyellow** [airbnb/javascript#1180]
here is copy from `node_module`

```
  "rawSpec": "^13.0.0",

...

  "peerDependencies": {
    "eslint": "^3.9.1",
    "eslint-plugin-jsx-a11y": "^2.2.3",
    "eslint-plugin-import": "^2.1.0",
    "eslint-plugin-react": "^6.6.0"
  },
```

and here is from github code

```
 "version": "13.0.0",
 
...

 "peerDependencies": {
    "eslint": "^3.10.2",
    "eslint-plugin-jsx-a11y": "^3.0.1",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-react": "^6.7.1"
  },
```

**Comment by ljharb** [comment]
Yes, thanks, I'm aware that we have unreleased code. This is intentional - I'll release a breaking change of `eslint-config-airbnb` with the v3 dep of `eslint-plugin-jsx-a11y` when it's ready.

In the meantime, please stick with the peer dependencies that the package readme's install command installs.

**Comment by Kerumen** [comment]
@ljharb Any ETA for this? It's been 2 weeks that my CI is unhappy.. Thanks!

**Comment by ljharb** [comment]
@Kerumen the solution is to use the install command in the readme, so that all the peer deps are properly and explicitly specified in your package.json. If that had been the case, your CI would never have been broken.

**Comment by Kerumen** [comment]
@ljharb I did this.
But the rule `react/jsx-indent` broke with ternaries in `eslint-plugin-react@6.6.0` and was fixed in `6.7.0`. I know I could just disable the rule but I wanted to know why are you waiting to release the new version.

Thanks for the answer anyway.

**Comment by ljharb** [comment]
`eslint-plugin-react` 6.7.0 is allowed by the semver range of `eslint-config-airbnb` - `npm install` should update you to that the instant it was published.

**Comment by Kerumen** [comment]
Oh yes! My bad.. Sorry for the trouble.
