### ISSUE TITLE
airbnb-base:10.0.1 and atom linter-eslint don't seem to work together

### ISSUE THREAD

**Issue by andrehagemeier** [airbnb/javascript#1184]
I'm not quite sure if this is a problem of this airbnb release or if the current atom plugin is just not capable of handling this version (maybe it doesn't even support eslint3?) but if it was such a general problem, I guess others would have come across (and hopefully solved it) too:

I'm following the installation instruction for airbnb-base: I run 
```
(
  export PKG=eslint-config-airbnb;
  npm info "$PKG@latest" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs   npm install --save-dev "$PKG@latest"
)
```
to get all the matching versions. It'll give me:
```
    "eslint": "^3.10.2",
    "eslint-config-airbnb-base": "^10.0.1",
    "eslint-plugin-import": "^2.2.0",
```

When I now use airbnb-base: 
```
{
    "extends": "airbnb-base"
}
```
my linter-eslint (8.0.0) will throw an error:
```
Error: .../node_modules/eslint-config-airbnb-base/rules/imports.js:
	Configuration for rule "import/no-unresolved" is invalid:
	Value "data["0"].caseSensitive" has additional properties.
Referenced from: airbnb-base
Referenced from: .../.eslintrc.json
```
If I go back to older versions of airbnb-base (like a 1.x.x version) it works again... Has anybody seen this and knows how to fix it?

**Comment by ljharb** [comment]
Have you restarted Atom after the npm install? Atom seems to be incapable of updating its plugins mid-session.

**Comment by sean-stanley** [comment]
I had a similar issue. What resolved for me was updating my global eslint package as atom seems to have been using that to read my package.json. 

`npm update eslint -g`

Does that resolve for you?

**Comment by ljharb** [comment]
Alternatively, `npm uninstall -g eslint`, because you shouldn't have a linter installed globally - only per-project.

**Comment by andrehagemeier** [comment]
Well that's embarrassing, I was sure I didn't run a global eslint installation anymore.. but turns out I did. So removing it solved my problem. Thanks a lot
