### ISSUE TITLE
Airbnb legacy rules are not applying

### ISSUE THREAD

**Issue by thejourneydude** [airbnb/javascript#1191]
I'm using Atom 1.12.6. I have successfully installed all necessary modules. My `.eslintrc` looks like...

```
{
  "extends": "airbnb-base/legacy",
  "parser": "babel-eslint",
  "env": {
    "jasmine": true,
    "mocha": true
  }
}
```

When atom lints the following code...

```
var hello = this;

if (hello !== '') {
  // ...stuff...
}

function user(options) {
  this.name = options.name;
}

user({ name: 'jason' });

```

The code passes with flying colors. If I run the following code `varr name = "asdf";` then the linter will alert to me an error. That makes me thing that ESLint is working. What's stranger is that if I change `.eslintrc` to 

```
{
  "extends": "airbnb-base",
  "parser": "babel-eslint",
  "env": {
    "jasmine": true,
    "mocha": true
  }
}
```

Airbnb non-legacy errors will appear. Am I missing something here? Shouldn't I expect an error to appear when running the legacy code? For example, Airbnb legacy states that their should never be saved references of `this`.

**Comment by ljharb** [comment]
Have you restarted Atom? Atom has a bug where it doesn't reload linter settings until you restart it.

**Comment by thejourneydude** [comment]
Yes I've restarted it multiple times to no avail.

**Comment by ljharb** [comment]
Ah - you're using `babel-eslint`. If you're using the "legacy" config, you can't use the babel parser - you need to use the default parser.

**Comment by thejourneydude** [comment]
That's interesting. I removed the parser but the error is still persisting. This is after restarting Atom. 

```
{
  "extends": "airbnb-base/legacy",
  "env": {
    "jasmine": true,
    "mocha": true
  }
}

```

I also tried `"parser": "espree"` but that didn't work either.

**Comment by ljharb** [comment]
i think it's "default" but removing it is best.

I'm looking at your original code example - what is the code you expect to fail on "legacy"?

**Comment by thejourneydude** [comment]
`var hello = this;`

**Comment by ljharb** [comment]
What's wrong with that? That's value ES1 code.

**Comment by thejourneydude** [comment]
I was reviewing this rule in particular. Am I misunderstanding the rule?

https://github.com/airbnb/javascript/tree/es5-deprecated#naming--self-this

**Comment by ljharb** [comment]
That's part of the styleguide, but it's not something that's linted against. Not all of the style guide is, or even *can* be, linted against programmatically.

**Comment by thejourneydude** [comment]
Got it. We can close this. Sorry for the trouble and thanks for the clarification.
