### ISSUE TITLE
Can I avoid peer dependency warnings for JSX & React?

### ISSUE THREAD

**Issue by keithrz** [airbnb/javascript#1192]
I've got an .eslintrc setup for server-side Node project that only extends airbnb/base.  We don't use any JSX or React.

I'm not including eslint-plugin-jsx-ally nor eslint-plugin-react in my package.json.  I get the following warnings when I npm install:
├── UNMET PEER DEPENDENCY eslint-plugin-jsx-a11y@^2.2.3
└── UNMET PEER DEPENDENCY eslint-plugin-react@^6.6.0

npm WARN eslint-config-airbnb@13.0.0 requires a peer of eslint-plugin-jsx-a11y@^2.2.3 but none was installed.
npm WARN eslint-config-airbnb@13.0.0 requires a peer of eslint-plugin-react@^6.6.0 but none was installed.

Are these my only 2 options:
* include packages in package.json that I won't use
* see the warning about UNMET PEER DEPENDENCY every time I run npm install

This has been discussed previously in #451 and #366, but I didn't see any mention of the npm warnings.  Those discussions were over a year ago, so maybe we did not have the peer dependencies back then?

A snippet of my package.json:

  "devDependencies": {
    "eslint": "3.11.1",
    "eslint-config-airbnb": "13.0.0",
    "eslint-html-reporter": "0.5.2",
    "eslint-plugin-import": "2.1.0",

Thank you for the wonderful style guide!!

**Comment by vojty** [comment]
https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base

**Comment by ljharb** [comment]
Correct - airbnb/base is deprecated; use the separate eslint-config-airbnb-base package instead, for just this reason.

**Comment by ljharb** [comment]
(For future reference, the alternative solution is always to add the peer dependencies required, whether you "use" them or not)

**Comment by keithrz** [comment]
Got it.  New package.json (switched to airbnb-base):

  "devDependencies": {
    "eslint": "3.11.1",
    "eslint-config-airbnb-base": "10.0.1",
    "eslint-html-reporter": "0.5.2",
    "eslint-plugin-import": "2.1.0",

.eslintrc

Previous:
  "extends": "airbnb/base"

Now:
  "extends": "airbnb-base"

Thank you!!!
