### ISSUE TITLE
UNMET PEER DEPENDENCY eslint-plugin-jsx-a11y@^2.2.3

### ISSUE THREAD

**Issue by khankuan** [airbnb/javascript#1207]
Hi, I noticed that the version for eslint-plugin-jsx-a11y shows `^3.0.2` but the npm package installed uses `^2.2.3`.

**Comment by ljharb** [comment]
Yes, that is intentional - the package hasn't been updated yet. If you use the `npm install` command in the readme for `eslint-config-airbnb`, you'll always get the right peer dependency versions installed.

**Comment by khankuan** [comment]
Will there be any new releases?

**Comment by ljharb** [comment]
At some point, certainly. Is there a reason that you need v3 of eslint-plugin-jsx-a11y right now?

**Comment by khankuan** [comment]
No, just got confused why its out of sync with npm. Thanks for update :)

**Comment by khankuan** [comment]
And atom starts popping out error: `Configuration for rule "jsx-a11y/anchor-has-content" is invalid:
	Value "" is the wrong type.`

**Comment by ljharb** [comment]
Atom has a bug where you need to restart it when you make any node_modules change.

**Comment by khankuan** [comment]
Oh interesting, seems like thats the problem. Thanks!

**Comment by Aid19801** [comment]
I've tried restarting Atom and i'm still getting the same error. Goes away if i switch to Google lint. but unfortunately our team are aligned with AirBnB style.  Any ideas how i can fix this relatively quickly? 

![image](https://cloud.githubusercontent.com/assets/15033409/21639788/c498a1a0-d269-11e6-88e0-f382179bcb6f.png)

**Comment by ljharb** [comment]
@Aid19801 do you have v3 of `eslint-plugin-jsx-a11y` installed? Our config isn't compatible with that yet - stick to v2.

**Comment by UnsungHero97** [comment]
@ljharb is a fix for this on the roadmap?

**Comment by ljharb** [comment]
It's not something that needs fixing - it's just the nature of peer deps in npm - but it's up to v3 on master, so whenever the next release happens, it'll be included.

**Comment by Aid19801** [comment]
@ljharb thanks mate, will take a look shortly and come back to you.

**Comment by ljharb** [comment]
Just published v14.0.0 of the main config, and v11.0.1 of the base config.

(#1162, #1166, #1182, #1186, #1207, #1212, #1222)
