### ISSUE TITLE
no-useless-return breaks consistency

### ISSUE THREAD

**Issue by felixsanz** [airbnb/javascript#1210]
This is a weird example but i'll try.

```javascript
function f(p) {
  if (p === 'a') {
    // some lines of code
    await sideEffect1()
    
    return
  }
  
  if (p === 'b') {
    // some lines of code
    await sideEffect2()
    
    return
  }

  if (p === 'c') {
    // some lines of code
    await sideEffect3()
    
    return
  }
}
```

Here the rule `no-useless-return` is complaining about the last `return`. I agree that it's useless and i can avoid it, but it will break consistency with the other `if`s.

If i remove the last `return`, in the future as i need more blocks like this, when i add a new one at the bottom i'll have to also add the return on the previous one. So whenever i add a new `if` block i will have to modify the last one too.

I don't use `else-if` because **the blocks are a bit large** and having them separated by an empty line instead of having `} else if (p ==== 'c') {` is way more clear (using `else-if` there is no empty lines as separator). It's easier to identify where a block starts and where it ends.

What is the best approach here?

If describing my use case helps, this function takes as input a CSS theme and fix some selectors and properties. Some themes needs more fixes than others, and different workarounds, so i enclose themes using ifs, like `if (theme === 'red')`,  `if (theme === 'blue')`, etc. Whenever i add new themes i'll have to create a new block and i'll prefer to avoid having to add the `return` to the last one.

After all, this is about consistency

**Comment by ljharb** [comment]
Good question.

On the one hand, I think `no-useless-return` could perhaps benefit from an option that allows a useless return inside a conditional block.

On the other, if you have a large block, it should really be refactored out into a separate function - if you do that, does the problem resolve itself?

**Comment by felixsanz** [comment]
The second option will still complain if I want to use multiple `if`s to separate the logic.

If you meant refactor + `else-if` well, that works, but as i add more cases it will be a bit messy.

```javascript
  if (p === 'a') {
    await refactoredFn1()
  } else if (p === 'b') {
    await refactoredFn2()
  } else if (p === 'c') {
    await refactoredFn3()
  }
```

This avoids the need of `return` and the rule will not complain, but it looks so condensed and having 10 `else-if` will make it look so ugly. In my upper example you can spot the logic faster than in this one.

I tend to apply the philosophy "a function should do just ONE thing and do it well".

Because of this, i prefer to **not** refactor this into smaller functions, because the function is just doing one thing, fixing themes. It's the theme name (an argument of the function) what separates the logic needed to make an output (in this case i save the file to disk so it's a side-effect, I'm just using `return` to quit the function execution and avoid checking all other `ifs` that will not match anymore).

So, the first proposal, having an option that allows a useless return inside a conditional sounds great, because I've seen many times the use of `return` (inside `if` blocks) just to quit the function and avoid passing across all the other `ifs`. This rule will break consistency in those cases, complaining about the last block.

**Comment by ljharb** [comment]
Right - but every `if` branch is another thing it's doing - so from the outside, your function is doing one thing, but inside it, it's doing many things, and it would be good to make each of *those* be a function that does one thing.

At any rate, please feel free to file an upstream issue on eslint requesting that option, and we can consider enabling it if/once it's released.
