### ISSUE TITLE
Setup eslint-config-airbnb without Bash?

### ISSUE THREAD

**Issue by woojoo666** [airbnb/javascript#1213]
It doesn't look like the command in the README works on Windows computers, but when I try to install the dependencies manually it sets off a lot of "unmet peer dependency" warnings, probably due to incompatible versions of each dependency. Is there a way to install the correct versions on Windows?

**Comment by ljharb** [comment]
Indeed the command doesn't work on Windows - I'd love to include one that does but I don't know how to write it.

The readme says "which produces a command like" and shows `npm install --save-dev eslint-config-airbnb eslint@^#.#.# eslint-plugin-jsx-a11y@^#.#.# eslint-plugin-import@^#.#.# eslint-plugin-react@^#.#.#` - that command *will* work on windows, except that the "#.#.#" will be replaced by the proper peerDependency version. To locate those versions, check http://npmcdn.com/eslint-config-airbnb/package.json under "peerDependencies".

**Comment by woojoo666** [comment]
perfect, the peer dependencies versions were exactly what I needed, surprised there isn't any mention of it on the README. Not everybody has linux :)

**Comment by ljharb** [comment]
If you want to write a PR that improves the wording for Windows users, especially if it adds an alternative instruction section for them, that'd be very much appreciated!

(Note that these sort of peer dep requirements are universal throughout the entire npm ecosystem when a package has peer deps, but that doesn't mean they're easy to understand)

**Comment by woojoo666** [comment]
Alright, I tried to word it best I could: #1214

**Comment by woojoo666** [comment]
@ljharb I wasn't able to respond to your comment on my pull request before you closed the request, but I just wanted to mention that I used "Linux/OSX" instead of "non-Windows" because Windows users can actually use [Git Bash](https://git-for-windows.github.io/) (or equivalently, [MinGW](http://www.mingw.org/)). On the other hand, this command doesn't work with Windows 10's new Bash feature, because the Bash shell can't run Windows executables (in this case, "npm")

**Comment by ljharb** [comment]
@woojoo666 no prob :-) "Linux/OSX" is just fine. However, that command should definitely work on BashOnWindows, and if it doesn't, please file a bug report with them directly :-)

Closed in #1214.

**Comment by woojoo666** [comment]
oh I know its a problem with Windows, not this repo, just wanted to mention it :)
