### ISSUE TITLE
react-native configuration flow example

### ISSUE THREAD

**Issue by julesmoretti** [airbnb/javascript#1216]
Hello there:

I have been battling trying to find a solid react-native setup example, that I can quickly install but have not yet found the ideal solution yet.

For some setups I get:
* `'styles' was used before it was defined`
for others:
* `JSX not allowed in files with extension '.js' `
and so on...
and of course I read a few suggestions like:
`"react/jsx-filename-extension": ["error", { "extensions": [".js", ".jsx"] }],`

But there is no turn key solution/tutorial for this please...

So the furthest cleanest setup I have seen so far but not complete is:

running in your terminal:
```
export PKG=eslint-config-airbnb;
npm info "$PKG@latest" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs npm install --save-dev "$PKG@latest"
```

Then create a `.eslintrc` file and paste:

```
{
  "extends": "airbnb",
}
```

But now this alone is not sufficient for a react-native app... so please please please advise and update docs :) 

Thank you.

**Comment by ljharb** [comment]
https://github.com/airbnb/javascript/issues/982#issuecomment-268397656 covers the jsx concern. Everything else, as far as I'm aware, is a legitimate issue that needs fixing.

**Comment by julesmoretti** [comment]
@ljharb - cool so hopefully some jshint ninja already has a solution and will soon share the wisdom :)

**Comment by ljharb** [comment]
@julesmoretti jshint? this is for eslint. What other problems do you have that need a solution? `no-use-before-define`, for example, is a legit error.

**Comment by julesmoretti** [comment]
@ljharb - that was a typo on my end, my bad.

The list starts to pile up and I rolled those configuration back so from memory things like:
`expected an identifier and instead saw ' <';`
`use this on render()...`
`style not declared`

So ideally what I am looking for is a really straight forward instruction on how to set up jslint for react-native with Airbnb's style guide. That details the necessary configurations to not have the above messages when using for example js filetype due to it being react-native and so on.

And hopefully not individual pieces of the whole solution for anyone to put together in the best possible way.

**Comment by ljharb** [comment]
@julesmoretti The instructions you posted in https://github.com/airbnb/javascript/issues/1216#issue-196809137, combined with the override from https://github.com/airbnb/javascript/issues/982#issuecomment-268397656, should be more than sufficient. At that point, you will very likely get many errors - that's when you need to fix them one at a time :-)

**Comment by julesmoretti** [comment]
Alright so almost there but not quite... So here we go:

Steps so far to try to fool proof this:
using react-native-cli@2.0.1

```
react-native init hello
cd hello
export PKG=eslint-config-airbnb;
npm info "$PKG@latest" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs npm install --save-dev "$PKG@latest"
touch .eslintrc
```

In the .eslintrc:
```
{
  "extends": "airbnb",
  "rules": {
    "react/jsx-filename-extension": ["error", { "extensions": [".js", ".jsx"] }],
  }
}
```

Then when editing the `index.android.js` to:

```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

export default class hello extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.android.js
        </Text>
        <Text style={styles.instructions}>
          Double tap R on your keyboard to reload,{'\n'}
          Shake or press menu button for dev menu
        </Text>
      </View>
    );
  }
}

AppRegistry.registerComponent('hello', () => hello);
```

Then when running `./node_modules/.bin/eslint index.android.js` I get:

```
  34:16  error  Component should be written as a pure function  react/prefer-stateless-function
```

So when I try to rewrite it into a pure function as such:

```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

const hello = () => ({
  return (
    <View style={styles.container}>
      <Text style={styles.welcome}>
        Welcome to React Native!
      </Text>
      <Text style={styles.instructions}>
        To get started, edit index.android.js
      </Text>
      <Text style={styles.instructions}>
        Double tap R on your keyboard to reload,{'\n'}
        Shake or press menu button for dev menu
      </Text>
    </View>
  );
});

export default hello;

AppRegistry.registerComponent('hello', () => hello);
```

and re-running `./node_modules/.bin/eslint index.android.js` I get:

```
36:5  error  Parsing error: Unexpected token <
```

And this is just using the default react-native lean template... Any ideas?

**Comment by julesmoretti** [comment]
EDIT:

So this works:

```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

function hello() {
  return (
    <View style={styles.container}>
      <Text style={styles.welcome}>
        Welcome to React Native!
      </Text>
      <Text style={styles.instructions}>
        To get started, edit index.android.js
      </Text>
      <Text style={styles.instructions}>
        Double tap R on your keyboard to reload,{'\n'}
        Shake or press menu button for dev menu
      </Text>
    </View>
  );
}

AppRegistry.registerComponent('hello', () => hello);
```

But going to test it out a little more thoroughly with another imported component

**Comment by ljharb** [comment]
@julesmoretti that's because your first arrow function was invalid syntax - it was combining implicit and explicit return. However, our style guide requires normal (non-arrow) functions for SFCs, so the latter example is better anyways.

**Comment by julesmoretti** [comment]
@ljharb - How would you still write the component using `export default class hello extends React.Component {` or better, in order to maintain functionalities like componentDidMount and yet have the lint pass the test?

Is there an equivalent to `/* eslint-disable global-require */` but for pure functions? or a way to write it better? 

An example would be most welcome.

**Comment by ljharb** [comment]
if the component has lifecycle methods, the linter won't require it be an SFC.

**Comment by julesmoretti** [comment]
Perfect! I updated the .eslintrc and added the no-console: 0

```
{
  "extends": "airbnb",
  "rules": {
    "react/jsx-filename-extension": ["error", { "extensions": [".js", ".jsx"] }],
    "no-console": 0,
  }
}
```

Thank you!
