### ISSUE TITLE
Example 18.6 (whitespace chaining) is not consistent with 6.3 (template strings, interpolation)

### ISSUE THREAD

**Issue by wachunei** [airbnb/javascript#1218]
[Chaining example](https://github.com/airbnb/javascript#whitespace--chains) marked as "good" is generating a string with concatenation (`'translate(' + (radius + margin) + ',' + (radius + margin) + ')`), whilst [6.3](https://github.com/airbnb/javascript#es6-template-literals) states that template strings should be used.

Let me know if this is actually a mistake, I'd be happy to fork, fix, and PR this. If this is not a mistake, please let me know why.

**Comment by ljharb** [comment]
It's not a mistake so much as left over from before we made the rule to prefer template literals. A PR would be quite welcome.

**Comment by wachunei** [comment]
PR'd #1219
