### ISSUE TITLE
Question about concatenating two variables

### ISSUE THREAD

**Issue by felixsanz** [airbnb/javascript#1225]
Probably a stupid question but in the style guide i can't find a recommendation for this two:

```javascript
const a = 'abc'; const b = '123'; a + b
// vs
const a = 'abc'; const b = '123'; `${a}${b}`
```

Which one is prefered? I know there is a rule that enforces [template strings when concatenating string literals](https://github.com/airbnb/javascript#es6-template-literals). But what about when all elements are variables and none is a string literal?

**Comment by ljharb** [comment]
That's string concatenation, so, always a template literal. A linter rule can't enforce your scenario, but string concatenation should never be done using `+` once you have template literals available.
