### ISSUE TITLE
Getting an error on Atom: 'func-name-matching'

### ISSUE THREAD

**Issue by eladams** [airbnb/javascript#1228]
eslint-config-airbnb version: 13.0.0
eslint version: 3.12.1 (not globally installed)

I've run the script from the docs for peer decencies installation.
After restart I still received:
```
Configuration for rule "func-name-matching" is invalid: Value "always,[object Object]" has more items than allowed. Value "always" is the wrong type.
```

**'Solution': Installing eslint globally and setting Atom eslint configuration to run the global eslint and not the local one.**

**Comment by ljharb** [comment]
That's definitely not the proper solution - if you have only a local eslint installed, and Atom is configured to use it, and you've restarted Atom after any node_modules or eslint config change, it should work properly.
