### ISSUE TITLE
Multiline imports and exports

### ISSUE THREAD

**Issue by felixsanz** [airbnb/javascript#1229]
[10.8](https://github.com/airbnb/javascript#modules--multiline-imports-over-newlines) says:

> 10.8 Multiline imports should be indented just like multiline array and object literals.

Only imports? What about exports?

---

Also, on section [18.5](https://github.com/airbnb/javascript#whitespace--newline-at-end) the example contains:

```javascript
// good
import { es6 } from './AirbnbStyleGuide';
  // ...
export default es6;↵
```

It shouldn't be like this?

```javascript
// good
import {
  es6,
} from './AirbnbStyleGuide';
  // ...
export default es6;↵
```

It also happens on [10.3](https://github.com/airbnb/javascript#modules--no-export-from-import) and maybe at [10.4](https://github.com/airbnb/javascript#modules--no-duplicate-imports).

I can PR if i'm right here. If not, what number is good to go multiline?

**Comment by ljharb** [comment]
That's always entirely arbitrary. Both of your examples are equally fine.

**Comment by hosseinmd** [comment]
why this is bad
```js 
export { es6 } from './AirbnbStyleGuide';
```
I usually use that in the index file of a module.

is this bad too? why?
```js 
export * from './AirbnbStyleGuide';
```
I always use this way for export types

and about the last one

```js
export const foo = 'foo';
```
