### ISSUE TITLE
I'm so confused about Object.assign code

### ISSUE THREAD

**Issue by Hushabyme** [airbnb/javascript#1230]
The original code is:
`const original = { a: 1, b: 2 };    
const copy = { ...original, c: 3 }; // copy => { a: 1, b: 2, c: 3 }`

`...` operator just use to iterable object,like Array or Set.
How could it use this method?
Thank you for your explaining.

**Comment by ljharb** [comment]
`...` on arrays or iterables is "array spread", used inside an object literal, it's "object spread", per the [stage 3 proposal](https://github.com/sebmarkbage/ecmascript-rest-spread).
