### ISSUE TITLE
3.8 TypeError: original is not iterable

### ISSUE THREAD

**Issue by Naggi-Goishi** [airbnb/javascript#1232]
In 3.8, 

```javascript
// very bad
const original = { a: 1, b: 2 };
const copy = Object.assign(original, { c: 3 }); // this mutates `original` ಠ_ಠ
delete copy.a; // so does this

// bad
const original = { a: 1, b: 2 };
const copy = Object.assign({}, original, { c: 3 }); // copy => { a: 1, b: 2, c: 3 }

// good
const original = { a: 1, b: 2 };
const copy = { ...original, c: 3 }; // copy => { a: 1, b: 2, c: 3 }

const { a, ...noA } = copy; // noA => { b: 2, c: 3 }
```

I tried to run good code, it gives me *TypeError: original is not iterable*
this error.

**Comment by ljharb** [comment]
That error sounds like it's coming from array spread - this is object spread, which doesn't use iterability. Can you share a jsfiddle that reproduces your issue?

**Comment by Naggi-Goishi** [comment]
Thank you for your quick reply!
I tried to apply this good code to my code but it does not works, so I do like below.
https://jsfiddle.net/Naggi810/awf4mz29/
but, it give me, the error, **TypeError: original is not iterable**

**Comment by ljharb** [comment]
@Naggi-Goishi in this case, that's not object spread, that's array/iterable spread into a function call. https://jsfiddle.net/awf4mz29/1/ would be object spread (which no browser supports yet, but babel does)

**Comment by Naggi-Goishi** [comment]
Oh, I see, 
> no browser supports yet
I at first, the error, **SyntaxError: invalid property id**
And in order to see what going on, I wrote code like above.
Thank you !
