### ISSUE TITLE
Tool to set up eslint-config-airbnb without bash

### ISSUE THREAD

**Issue by nathanhleung** [airbnb/javascript#1233]
I saw the creator of #1213 was having problems installing all the peer dependencies for the config on Windows, since the bash command doesn't work. I was having the same type of trouble, but I didn't want to manually copy the version of each peer dependency _every_ time I wanted to start a new project.

I wrote up a generalized cli (which works on all platforms, not just Windows!) to help install peerDeps (inspired by this use case) called [install-peerdeps](https://github.com/nathanhleung/install-peerdeps) - let me know if this helps!

**Comment by ljharb** [comment]
Thanks, this looks great! What about `--save` and `--save-dev`? The usefulness isn't just installing it, it's putting the proper versions in your package.json.

**Comment by ljharb** [comment]
Once that exists, I'd love a PR into the readmes for both packages that suggests using `install-peerdeps` as an alternative to the bash command.

**Comment by nathanhleung** [comment]
I've got a `--dev` flag for devDependencies, but even better, it detects whether the project is running yarn or npm, and then runs either `yarn add` or `npm install --save`!

(here are the full usage instructions)
```
Usage: install-peerdeps <package>[@<version>], default version is 'latest'

Installs the specified package along with correct peerDeps.

Options:

  -h, --help     output usage information
  -V, --version  output the version number
  -d, --dev      Install the package as a devDependency
```

I'll submit a PR as soon as I can!

**Comment by ljharb** [comment]
I'd definitely prefer it not to autodetect things - projects can use both npm and yarn, and I'd want to recommend a tool that asked the user to make the choice. Similarly, I'd want "modify package.json or yarn.lock" not to be the default; users should have to ask for it.

**Comment by nathanhleung** [comment]
Got it, I'll add those options to the cli and let you know.

**Comment by nathanhleung** [comment]
One note though,, Yarn purposely prohibits you from installing a "silent dependency" (i.e. one that is missing from package.json). In other words, there's [no alternative to `npm install`](https://yarnpkg.com/en/docs/migrating-from-npm) in Yarn and package.json/yarn.lock is always edited when a package is installed.

However, I'll add the yarn/npm option to the cli - if a user wants to install the eslint config silently, they'll just have to use npm.

**Comment by ljharb** [comment]
That's fair - but npm users are the far larger group, and I don't want their expectations surprised :-)

**Comment by nathanhleung** [comment]
I've added two new options, `--yarn` and `--silent`:

```
Usage: install-peerdeps <package>[@<version>], default version is 'latest'

Installs the specified package along with correct peerDeps.

Options:

  -h, --help     output usage information
  -V, --version  output the version number
  -d, --dev      Install the package as a devDependency
  -S, --silent   If using npm, don't save in package.json
  -Y, --yarn     Install with yarn
```

Does this look good to you? If so, I'd be happy to submit a pull adding it to the README.

On another note, thanks for the feedback - I sometimes get too caught up in the speed of the ecosystem and forget that 90% of users are still on NPM, Koa is nowhere close to overtaking Express, etc - hopefully [install-peerdeps](https://github.com/nathanhleung/install-peerdeps) sufficiently considers most use cases, now!

**Comment by ljharb** [comment]
That sounds much better - the usage I'd want to recommend then is `install-peerdeps --dev eslint-config-airbnb`.

**Comment by nathanhleung** [comment]
Great, I'll get to work on the PR!
