### ISSUE TITLE
 why?  [] = 1 [] = '1'

### ISSUE THREAD

**Issue by zhangbowei** [airbnb/javascript#1237]
```
> [0][0] = '1'
'1'
> [0][0]
0
> [] = 1
TypeError: undefined is not a function
> [] = '1'
'1'
```

**Comment by ljharb** [comment]
The first example is because assignments return their value.
The second is because the 0th element in the array `[0]` is zero.
The third is just broken; I suspect that if it wasn't a repl you'd get a different error.
The fourth is the same as the first.
