### ISSUE TITLE
Airbnb's `padded-blocks` ESLint rule definition may be incorrect

### ISSUE THREAD

**Issue by treybrisbane** [airbnb/javascript#1240]
In the Airbnb style guide, [section 18.8](https://github.com/airbnb/javascript#whitespace--padded-blocks) states to "not pad your blocks with blank lines". To enforce this via ESLint, the `padded-blocks` rule is used in [style.js](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/style.js#L317).

Currently, `padded-blocks` is set to `['error', 'never']`. This, however, means that `switch` statements and `class` declarations are not being checked correctly (the documentation around this was a bit poor - see [this](https://github.com/eslint/eslint/issues/7868) issue).

In order to correctly enforce this for _all_ blocks, the `padded-blocks` rule needs to be set to `['error', { blocks: 'never', classes: 'never', switches: 'never' }]`. :)

**Comment by ljharb** [comment]
Thanks for filing this - I am indeed following that eslint rule but I didn't realize we weren't using the object form of the config.

What would be ideal is a PR that converts to the identical object form first, but with a TODO comment marked "semver-major" to enable the new warnings.

**Comment by 91aman** [comment]
@ljharb Can I take this up and send a PR with the changes?

**Comment by ljharb** [comment]
Please! That's what the "help wanted" label is meant to mean :-)

**Comment by 91aman** [comment]
@ljharb I have created a pull request with the changes requested.

**Comment by kjesek** [comment]
is this issue still available?

**Comment by ljharb** [comment]
@kjesek #1255 already exists.
