### ISSUE TITLE
weird issue with `react/jsx-no-bind`

### ISSUE THREAD

**Issue by Kufert** [airbnb/javascript#1248]
this is my `.eslintrc`:
```
{
    "root": true,
    "parser": "babel-eslint",
    "extends": "airbnb",
    "ecmaFeatures": {
        "classes": true,
        "jsx": true
    },
    "plugins": [
      "react"
    ],
    "rules": {
      "react/display-name": 1,
      "react/jsx-filename-extension":0,
      "react/jsx-no-bind": 2,
      "semi": [ 2, "never" ],
      "import/no-extraneous-dependencies": 0,
      "no-use-before-define": 0,
      "no-underscore-dangle": 0,
      "import/prefer-default-export": 0,
    }
}
```

For some reason, the rule `react/jsx-no-bind` doesn't work for me while extending `airbnb`. If I remove the `"extends": "airbnb",`, I get lint errors, but when I extend, lint ignores any setting I might have and doesn't show errors/warning at all.

**Comment by ljharb** [comment]
What version of eslint etc do you have installed? What's your `package.json` look like?

(also you don't need the `ecmaFeatures` at all, but that's unrelated)

**Comment by Kufert** [comment]
my `package.json`
```
{
  "name": "my-react",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": "5.10.0",
    "npm": "3.5.0"
  },
  "dependencies": {
    "babel": "^6.5.2",
    "babel-cli": "^6.6.5",
    "babel-core": "^6.7.4",
    "babel-loader": "^6.2.4",
    "babel-polyfill": "^6.7.4",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-0": "^6.5.0",
    "babel-runtime": "^6.6.1",
    "es5-shim": "^4.5.7",
    "expose-loader": "^0.7.1",
    "imports-loader": "^0.6.5",
    "react": "^15.0.0",
    "react-bootstrap": "^0.30.7",
    "react-dom": "^15.0.0",
    "react-dropzone": "^3.8.0",
    "react-on-rails": "6.3.2",
    "react-redux": "^4.4.1",
    "redux": "^3.6.0",
    "redux-logger": "^2.7.4",
    "superagent": "^3.3.1",
    "webpack": "^1.12.14"
  },
  "devDependencies": {
    "eslint": "^3.13.1",
    "eslint-config-airbnb": "^14.0.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^3.0.2",
    "eslint-plugin-react": "^6.9.0"
  }
}
```
I'm using the local eslint by runnitn `/node_modules/eslint/bin/eslint.js app`. Actual versions installed:
```
├── babel@6.5.2
├── babel-cli@6.18.0
├── babel-core@6.21.0
├── babel-loader@6.2.10
├── babel-polyfill@6.20.0
├── babel-preset-es2015@6.18.0
├── babel-preset-react@6.16.0
├── babel-preset-stage-0@6.16.0
├── babel-runtime@6.20.0
├── es5-shim@4.5.9
├── eslint@3.13.1
├── eslint-config-airbnb@14.0.0
├── eslint-plugin-import@2.2.0
├── eslint-plugin-jsx-a11y@3.0.2
├── eslint-plugin-react@6.9.0
├── expose-loader@0.7.1
├── imports-loader@0.6.5
├── node-pre-gyp@0.6.32 extraneous
├── react@15.4.1
├── react-bootstrap@0.30.7
├── react-dom@15.4.1
├── react-dropzone@3.8.0
├── react-on-rails@6.3.2
├── react-redux@4.4.6
├── redux@3.6.0
├── redux-logger@2.7.4
├── superagent@3.3.1
└── webpack@1.14.0
```

**Comment by ljharb** [comment]
(also node 5 is EOL'd so you want to be on 4, 6, or 7, but that's also unrelated)

ok, all that looks good.

What happens if you specify "parser" *after* specifying "extends"?

Also, instead of running a command inside node_modules directly, what if you use an npm run-script to run `eslint`?

**Comment by Kufert** [comment]
Same behavior - when extending I get no `react/jsx-no-bind` errors, but when I remove the extend I get the errors. 

just to make sure I follow, you meant to change the order so that *extends* is first and *parser* follows in the `.eslintrc` file?

**Comment by ljharb** [comment]
yes, that's what i meant

**Comment by Kufert** [comment]
Yea, so I tried rearranging and running using `npm`, both methods yielded the same results. Really weird...

**Comment by ljharb** [comment]
Is it possible you could create a repo that reproduces this issue so I can try locally?

**Comment by photolio** [comment]
Just stumbled upon the same issue.
What helped me out there is setting all possible options for the rule:
```javascript
"extends": "airbnb",
"rules": {
  "react/jsx-no-bind": [ 
    2, 
    {
        "ignoreRefs": false,
        "allowArrowFunctions": false,
        "allowBind": false
    }
  ]
}
```

**Comment by Kufert** [comment]
I ended up using  `"react/jsx-no-bind": [2, {}]`

**Comment by ljharb** [comment]
This suggests it might be a bug in `eslint-plugin-react`.

@Kufert if you can reproduce it with that plugin directly (without the airbnb config), a bug report there would be *very* helpful.

**Comment by edgar0011** [comment]
> [2, {}]

but in yml, that is a different story :-)

**Comment by ljharb** [comment]
Sure, but why would you want to use yml for config when you have any other choice

**Comment by edgar0011** [comment]
> Sure, but why would you want to use yml for config when you have any other choice

1) you come to a project wehere yaml already is, due to many reasons
2) yaml has some advantages over json:
Advantages of YAML:
In YAML, there is no extra delimiter is used. So it is the lightweight than XML and JSON.
YAML, not using delimiter also makes the reading light and simple. (I am not sure if you agree with this point. Because many geeks find it easier to read the data in content delimiter or tags separate those.)
YAML makes the data understanding easy. So it is useful in case of configuration.
YAML has a wide variety of uses and popular for. It can be used for configuration, then from transferring data to storing intermediate data.
YAML is the superset of JSON. You heard it right. Whatever valid JSON code you have, it will be parsed by YAML compiler. So choosing YAML over JSON for your project you have one advantage. You can parse both JSON and YAML code with the single parser (YAML parser).
source: https://www.csestack.org/advantages-disadvantages-yaml/
