### ISSUE TITLE
Is ESLint 'no-iterator' rule appropriate for 'Don't use iterators' advice?

### ISSUE THREAD

**Issue by vsemozhetbyt** [airbnb/javascript#1249]
See https://github.com/airbnb/javascript#iterators--nope.

It seems the ['no-iterator'](http://eslint.org/docs/rules/no-iterator.html) rule has a very restricted aim. Moreover, it contains this advice which contradicts the 11.1 part:
> You should use ECMAScript 6 iterators and generators instead.

**Comment by ljharb** [comment]
`no-iterator` is linting against a never-standard feature that should never be used.

The rule's advice is to use ES6 iterators and generators to achieve identical goals, which is fine.

This guide, however, forbids such things, and requires you use array iteration methods instead.

I agree that perhaps `no-iterator` is only loosely correlated with the "don't use iterators" section, but it's not entirely unrelated, and there's no better place to put it i think.
