### ISSUE TITLE
JS Style Guide JSCS Links for ES5 or ES6

### ISSUE THREAD

**Issue by NathanielPrescott** [airbnb/javascript#1256]
Howdy,

Currently I am trying to implement the airbnb style guide for a project which is using ES5 and will not be upgrading to ES6 any time soon.  After looking at the ES6 style guide and the ES5 (deprecated) style guide the links provided are to the same preset.  My question is, are these presets compatible with ES5?

The preset is linked below:
https://github.com/jscs-dev/node-jscs/blob/master/presets/airbnb.json

Thank you!

**Comment by ljharb** [comment]
JSCS is deprecated and shut down, and their airbnb preset is way out of date. You should only be using `eslint`, whether for ES5 or later.

https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base#eslint-config-airbnb-baselegacy is available for you to eslint with, if you need it.
