### ISSUE TITLE
new error

### ISSUE THREAD

**Issue by ysbpysbp** [airbnb/javascript#1265]
const foo = [1, 2];
const bar = foo;

bar[0] = 9;

console.log(foo[0], bar[0]);

VM403:1 Uncaught SyntaxError: Identifier 'foo' has already been declared
    at <anonymous>:1:1 
in chrome

**Comment by vsemozhetbyt** [comment]
It seems you try to run this code twice in the console, so in the second attempt all identifiers are redeclared.

**Comment by ljharb** [comment]
Indeed, the console/repl isn't truly reflective of a real environment. You'll want to create block-level variables inside a block, or else restart the repl when you want to reuse a variable name.
