### ISSUE TITLE
Trailing comma in function call after spread operator

### ISSUE THREAD

**Issue by vsemozhetbyt** [airbnb/javascript#1266]
In the part [19.2](https://github.com/airbnb/javascript/blob/master/README.md#commas--dangling) there is a confusing comment above the last example:
```js
// good (note that a comma must not appear after a "rest" element)
createHero(
  firstName,
  lastName,
  inventorOf,
  ...heroArgs
)
```
1. This is actually a spread operator.
2. ESLint reports `Missing trailing comma` for this case.
3. It seems there are no restrictions for using trailing commas in function calls after spread operator:
```js
'use strict';

function createHero(
  firstName,
  lastName,
  inventorOf,
  ...heroArgs
) {
  console.log(heroArgs);
}

createHero(
  'firstName',
  'lastName',
  'inventorOf',
  ...['a', 'b'],
  ...['c', 'd'],
);
```
```
node --harmony_trailing_commas test.js
[ 'a', 'b', 'c', 'd' ]
```

**Comment by ljharb** [comment]
Indeed, the example shows a spread operator, but the comment is not referring to the example. It's referring to the (identical) rest operator, which does not appear. A PR to make it less confusing is welcome.

**Comment by ljharb** [comment]
(also please don't ever use harmony flags for any reason except as a v8 developer to test v8; they're for broken/unstable features, and do not reflect accurate usage)
