### ISSUE TITLE
README update for JSCS deprecated links

### ISSUE THREAD

**Issue by NathanielPrescott** [airbnb/javascript#1272]
I noticed that the JSCS links in the README.md file currently link to the deprecated JSCS github pages.  There should probably be something that states that these are deprecated and where to find the documentation for es6 and es5-deprecated eslint.

The README files on:
https://github.com/airbnb/javascript

Should have the following added to the end of the 'JSCS - Airbnb Style Preset':
(Depricated, please use [ESlint](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base))

---

The README file on:
https://github.com/airbnb/javascript/tree/es5-deprecated/es5

Should have the following added to the end of the 'JSCS - Airbnb Style Preset':
(Depricated, please use [ESlint](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base#eslint-config-airbnb-baselegacy))

**Comment by ljharb** [comment]
This sounds reasonable (alternatively, just removing any mentions of jscs).

**Comment by NathanielPrescott** [comment]
My thoughts are that there are still companies using JSCS but who may want to start using airbnb's style guide.  This could be one of their first steps to switching to eslint.  At least it is with the company I am currently at.

Will get a pull request up soon.

**Comment by ljharb** [comment]
jscs was shut down April of 2016, so it's getting pretty late in the game to make the switch - but I'm comfortable with leaving the jscs mentions for the time being, to help people transitioning.

**Comment by NathanielPrescott** [comment]
Here is the pull request: https://github.com/airbnb/javascript/pull/1273

I was not able to change the airbnb/javascript/tree/es5-deprecated/es5 due to being unable to access that tree (or not understanding how I would).  Is there a way to make the proper README.md file change or is that something I do not have access to do?

https://github.com/airbnb/javascript/tree/es5-deprecated/es5/README.md

**Comment by ljharb** [comment]
The ES5 guide (since it's deprecated) isn't available under anything but a tag. Since the entire ES5 guide is only there for posterity, I don't think there's any need to update it.

**Comment by aboyton** [comment]
How many rules in Airbnb's style guide are enforced by JSCS but not ESLint?

A superficial search returned:
* `requireObjectDestructuring`
* `requireArrayDestructuring`
* `disallowArrayDestructuringReturn`
* `requirePaddingNewLinesAfterBlocks`
* `requireDollarBeforejQueryAssignment`

But it's a bit hard for me to work out if the ESLint version does exactly what the JSCS version of a rule does.

**Comment by ljharb** [comment]
`requireObjectDestructuring` and `requireArrayDestructuring` → `prefer-destructuring`
`requirePaddingNewLinesAfterBlocks` → `padded-blocks`

I think `disallowArrayDestructuringReturn` has a rule as well?

Either way, the eslint team has committed to creating or adapting rules such that 100% of jscs enforcement is possible with eslint - they're pretty close to complete.

**Comment by aboyton** [comment]
Great to hear. Thanks for the quick response.

**Comment by ljharb** [comment]
jscs rules have been removed since jscs is dead.
