### ISSUE TITLE
how can we stop a `nodejs` server started?

### ISSUE THREAD

**Issue by fatimazbouj** [airbnb/javascript#1277]
hello,
i start my `server.js` by the command line 

>  node server.js>node.log &

i use the `proc_open` function to execute the cmd

now is there a way to stop it,althought i use the `proc_close` function but it still running,i try the `exec('kill'.PID);` too but it's not stoped att all ,how can i do it?

**Comment by ljharb** [comment]
This repo is about our JavaScript style guide, and isn't for general-purpose questions - I recommend visiting #node.js on Freenode IRC.

**Comment by fatimazbouj** [comment]
okey i'm sorry for this

**Comment by fatimazbouj** [comment]
okey i'm sorry for this


2017-01-23 18:38 GMT+00:00 Jordan Harband <notifications@github.com>:
