### ISSUE TITLE
Contradiction in Functions  guide

### ISSUE THREAD

**Issue by jruts** [airbnb/javascript#1279]
Reading through the guide on Github and the guide on airbnb.io there seems to be a contradiction in the functions part.

https://github.com/airbnb/javascript#functions
http://airbnb.io/javascript/#functions

Which one is preferred and why?

**Comment by ljharb** [comment]
The github one is the source of truth; I'll update the airbnb.io one now.

The "why" is explained in the github link.

**Comment by jruts** [comment]
Thanks for the response!
