### ISSUE TITLE
Where to place operators in a multi-line ternary?

### ISSUE THREAD

**Issue by pconerly** [airbnb/javascript#1281]
My team uses airbnb's styleguide as our default for coding style, although we do deviate occasionally.

Does airbnb have an opinion on where the operators should go in a multi-line ternary?

It's not specifically talked about anywhere, but there is the example:
```
// better
const foo = maybe1 > maybe2
  ? 'bar'
  : maybeNull;
```

one of our engs prefers this, with the justification that it's easier to read. If you read the first line by itself, then having the `?` at the end lets you know that this is a ternary and is continuing. Otherwise, if you're skimming the code very fast, you might think that you're assigning `foo` a boolean value.
```
const foo = maybe1 > maybe2 ?
  'bar' :
  maybeNull;
```

And again, we're using multi-line ternaries because we have some long expressions and values to be assigned.

**Comment by ljharb** [comment]
Currently https://github.com/airbnb/javascript#comparison--nested-ternaries does *permit* multiline ternaries, although it discourages them. I'd strongly encourage you to use `let` and `if`/`else` rather than multiline ternaries.

That said, the former is the only style I would expect to see one:
```js
const foo = condition
  ? a
  : b;
```

**Comment by rsolomon** [comment]
> I'd strongly encourage you to use let and if/else rather than multiline ternaries.

Can you elaborate on why you feel that to be the correct approach? Type safety is much easier when you disallow mutations and discourage nullable objects. Ternaries meet both criteria, whereas `let` often necessitates a host of additional checks.

**Comment by ljharb** [comment]
@rsolomon I'm not sure why type safety comes into play when you're talking about assignments; nor am I sure what you mean by "nullable objects".

If you want to use a ternary so you can use `const`, that's great! In that case, use lots of intermediate variables so that you never need to split a ternary across multiple lines.

**Comment by rsolomon** [comment]
You're right, I misinterpreted your statement as discouraging ternaries in general, not just multilines.

**Comment by w0251251** [comment]
return ( multiline === 'example' ) ? (
  <Foo />
) : (
  <Bar />
)

**Comment by ljharb** [comment]
Aside from the spaces inside the conditional parens, and the redundant parens around said conditional, that's indeed exactly how I'd expect multiline ternaries in JSX to be indented.

**Comment by patoezequiel** [comment]
I tend to use the following format:

```
const foo = ( condition )
    ? a
    : b;
```

**Comment by ljharb** [comment]
That works well for normal code; but for jsx, i find it makes the indentation awkward.

**Comment by Zamiell** [comment]
This issue can be probably be closed now - the main style guide has a pretty good section on ternaries as of the time of this writing.

**Comment by K3UL** [comment]
I know this is closed but it comes really high in google results when searching multiline ternaries.
I  would recommend using the following.

```javascript
const foo = (condition
    ? a
    : b);
```

Both hypothesis are much more readable than with the `?` at the end of the line, and the parenthesis makes it impossible to think this is just a boolean assignment, a dev eye will immediately notice an open parenthesis without its closing counterpart.

**Comment by ljharb** [comment]
@k3ul i'd modify that, since the closing boundary (paren/bracket/brace) of a multiline construct should always begin a line, just like the opening boundary should always end one:
```js
const foo = (
  condition
    ? a
    : b
);
```

**Comment by K3UL** [comment]
Yep that is what I meant sorry, I edited the other snippet and went a little fast, thanks !
