### ISSUE TITLE
Atom beautification config.

### ISSUE THREAD

**Issue by love2dishtech** [airbnb/javascript#1282]
The default rules for the "atom-beautify" does not play very well with the airbnb eslint config rules. Also, the config options available are also not enough to be tuned.

Is there a plugin or config options available for auto beautification in atom while still maintaining the consistency of airbnb eslint rules.

**Comment by ljharb** [comment]
Can you elaborate on "does not play very well"? This sounds like something you'd need to file on `atom-beautify` - typically linter plugins just run `eslint --fix`, and the things that can't be autofixed, must be manually fixed by a human.

**Comment by love2dishtech** [comment]
Yeah. Agree. I am filling it on atom-beautify. I was wondering, and hence posted it as a question to understand, what is the standard technique recommended by airbnb/community around. What should be the right way to go. Or, is there any config options available for plugins like atom-beautify and esformatter to help sort this out via Atom.

**Comment by ljharb** [comment]
I think the most common approach is for editors to merely show violations, and for any autofixing to be done on the command line with `eslint --fix`.

**Comment by love2dishtech** [comment]
Cool. Let me check with the beautification plugins to see possible adherence to airbnb styling guide.
