### ISSUE TITLE
Unmet peer dependency

### ISSUE THREAD

**Issue by pronebird** [airbnb/javascript#1283]
`npm i eslint-config-airbnb --save-dev`

>├─┬ eslint-config-airbnb@14.0.0 
>│ ├── eslint-config-airbnb-base@11.0.1 
>│ └── UNMET PEER DEPENDENCY eslint-plugin-import@^2.2.0
>├── UNMET PEER DEPENDENCY eslint-plugin-import@^2.2.0
>├── UNMET PEER DEPENDENCY eslint-plugin-jsx-a11y@^3.0.2
>└── UNMET PEER DEPENDENCY eslint-plugin-react@^6.9.0

Why is it broken?

**Comment by ljharb** [comment]
Please use the install command in the package readme; this will install the correct peer dependencies.

**Comment by just-boris** [comment]
By the way it worth mentioning, that NPM 3+ will not install peer dependencies for you. You need to explicitly declare them in your `package.json`

@ljharb why do you keep them as peers? The most common use case for the code-style will be `npm install eslint-config-airbnb`, then write `{"extends": "airbnb"}`, and you will be set. 
Currently, you need to do an extra step and install those dependencies as well. `package.json` of average project becomes longer and longer.

**Comment by ljharb** [comment]
@just-boris eslint requires that it work that way; if they're not peers, none of the rules will work or be overrideable.

**Comment by just-boris** [comment]
Do you mean the issue: https://github.com/eslint/eslint/issues/3458?

Thanks for explanation, now I understand why do I need to do so.

**Comment by gazpachu** [comment]
@pronebird @just-boris @ljharb I still have problems to have the latest version working.

I get this error message everytime I open a file: `/node_modules/eslint-config-airbnb/rules/react-a11y.js: Configuration for rule "jsx-a11y/href-no-hash" is invalid: Value "[object Object]" no (or more than one) schemas match.

Referenced from: airbnb Referenced from: /Users/martosj/Dev/Webs/commit-frontend/.eslintrc.js`

These are the packages I'm using:

```
"eslint": "^3.15.0",
    "eslint-config-airbnb": "^14.0.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^3.0.2 || ^4.0.0",
    "eslint-plugin-react": "^6.9.0",
```

**Comment by ljharb** [comment]
Are you sure the versions on disk are correct, and that you've restarted atom? What's `npm ls` say?

**Comment by pronebird** [comment]
I think we can close this issue since as it turned out peer deps have to be installed manually.

**Comment by ljharb** [comment]
@gazpachu that seems like eslint updated to catch an error it was missing before. I'd just fix your code.

**Comment by gazpachu** [comment]
@ljharb I'm afraid that's not the case. If I remove the tab, I get this:

<img width="650" alt="screen shot 2017-03-03 at 17 39 18" src="https://cloud.githubusercontent.com/assets/1721288/23559789/6b8d53b0-0038-11e7-9ad9-90b9a28d0322.png">

And if I add the tab, I get this:

<img width="527" alt="screen shot 2017-03-03 at 17 40 12" src="https://cloud.githubusercontent.com/assets/1721288/23559799/7a81e7c8-0038-11e7-84a4-a1721cb42be0.png">

**Comment by ljharb** [comment]
Do you use tabs or spaces for indentation?

**Comment by gazpachu** [comment]
tabs

**Comment by ljharb** [comment]
In that case, you need to disable the `no-tabs` rule entirely. Airbnb uses spaces, so the guide comes configured to ban all tab characters.
