### ISSUE TITLE
Generator/coroutine: "Missing function expression name (func-names)"

### ISSUE THREAD

**Issue by nmors** [airbnb/javascript#1284]
I have a simple example of code here which fails eslint, is there a preferred way of expressing the following?

``` js
const render = co.wrap(function* (itemId, opts = {}) {
   ...yield...
   ...yield...
})
```

using bluebird instead of co gives same results:

```js
const render = P.coroutine(function* (itemId, opts = {}) {
   ...yield...
   ...yield...
)}
```

The lint error is "Missing function expression name (func-names)"

Thanks!

**Comment by ljharb** [comment]
This style guide does not allow use of generators.

The `func-name` rule, however, requires that you name your functions - ie, `function* foo(…) {…}`.
