### ISSUE TITLE
Use eslint-plugin-es5 for ES5 config

### ISSUE THREAD

**Issue by ai** [airbnb/javascript#1285]
If users set `es5` config, in my opinion, they want to write on ES5. So we should warn them about ES6 features, because they could brake IE/Safari.

There is a special plugin for ES5: https://github.com/nkt/eslint-plugin-es5

Should we use it?

**Comment by ljharb** [comment]
I don't think it's a good idea to add an extra dependency for all of the people using babel, for the minority that are not.
