### ISSUE TITLE
Update a11y removed rules and dependecy.

### ISSUE THREAD

**Issue by logicoder** [airbnb/javascript#1290]
As found in related issue https://github.com/evcohen/eslint-plugin-jsx-a11y/issues/175 with the latest 4.0 release the a11y plugin changed some rules.

**Comment by logicoder** [comment]
Release notes https://github.com/evcohen/eslint-plugin-jsx-a11y/releases/tag/4.0.0

**Comment by ljharb** [comment]
Thanks, but I have intentionally not made this upgrade yet. Our linter config is only supported with the versions of our peer deps that the command in the readme installs.

**Comment by logicoder** [comment]
OK 😄

If anyone ends up here, I added "jsx-a11y/no-marquee": 0 to my rules as a temporary workaround.

There are also other rules added in the release.

Thanks for your great work.

**Comment by ljharb** [comment]
Update to v14.1.0 and the no-marquee rule is removed; so you can use either v3 or v4 of the jsx-a11y plugin.

v15.0.0 will require v4, and will enable no-distracting-elements.
