### ISSUE TITLE
Replace eslint-plugin-react with eslint-plugin-inferno?

### ISSUE THREAD

**Issue by screendriver** [airbnb/javascript#1292]
Hi,

I want to use [eslint-config-airbnb](https://www.npmjs.com/package/eslint-config-airbnb) but also want to use [Inferno](https://www.infernojs.org) instead of [React](https://facebook.github.io/react/).

Unfortunately `eslint-config-airbnb` depends on `eslint-plugin-react`. Is there an easy way where I can replace `eslint-plugin-react` with `eslint-plugin-inferno` and everything works as expected?

**Comment by ljharb** [comment]
No easy way. You'd have to manually disable all the react rules, and then enable all of the inferno rules you want. Alternatively, you could start with eslint-config-airbnb-base, and then layer inferno and jsx-a11y on top of that.

**Comment by screendriver** [comment]
Thank you for the **very quick** response! 😳 👍
