### ISSUE TITLE
why don't use collection.length

### ISSUE THREAD

**Issue by cloudyan** [airbnb/javascript#1293]
https://github.com/airbnb/javascript#comparison--shortcuts

```
// bad
if (collection.length) {
  // ...
}

// good
if (collection.length > 0) {
   why don't use shortcuts
  // ...
}
```

**Comment by ljharb** [comment]
Because explicit comparisons are clearer. If you do an explicit comparison, then nobody needs to think about the truthiness of numbers, nor do they need to guess if you intentionally were comparing to `0`, or if you made a typo and forgot to include a comparison.
