### ISSUE TITLE
Code Failure when adding trailing comma to function arguments.

### ISSUE THREAD

**Issue by ssmith-wombatweb** [airbnb/javascript#1296]
When I add a trailing comma to the last argument to urlModel.add() the code breaks. When I remove it everything works fine.

```js
describe('Testing Adding URL', () => {
  it('Testing', (done) => {
    urlModel.add(
      { URL: 'http://www.asdfawegaasdg.com' },
      (error) => {
        it('There was an error adding the URL.', (done) => {
          done();
        });
      },
      (u) => {
        it('The URL was added successfully.', (done) => {
          done();
        });
      }
    );
    done();
  });
});
```

**Comment by ssmith-wombatweb** [comment]
The issue arises when it is formatted like so:

describe('Testing Adding URL', () => {
  it('Testing', (done) => {
    urlModel.add(
      { URL: 'http://www.asdfawegaasdg.com' },
      (error) => {
        it('There was an error adding the URL.', (done) => {
          done();
        });
      },
      (u) => {
        it('The URL was added successfully.', (done) => {
          done();
        });
      });
    done();
  }
  );
});

**Comment by ssmith-wombatweb** [comment]
But not like:
describe('Testing Adding URL', () => {
  it('Testing', (done) => {
    urlModel.add(
      { URL: 'http://www.asdfawegaasdg.com' },
      (error) => {
        it('There was an error adding the URL.', (done) => {
          done();
        });
      },
      (u) => {
        it('The URL was added successfully.', (done) => {
          done();
        });
      });
    done();
  });
});

**Comment by ljharb** [comment]
This guide expects you're using http://npmjs.com/babel-preset-airbnb, which transpiles the ES2017 feature of trailing function commas.

**Comment by Dzenly** [comment]
Is this topic about this rule:

https://github.com/airbnb/javascript#functions--signature-invocation-indentation
```
// good
console.log(
 foo,
 bar,
 baz,
);
```
?

**Comment by ljharb** [comment]
Yes.

Closing because it's been answered.
