### ISSUE TITLE
Is there CONTRIBUTING.md

### ISSUE THREAD

**Issue by sotayamashita** [airbnb/javascript#1297]
I made PR #1295 and you overwrote my commit message. I think we need a rule for commit message to avoid overwriting commit messages. If there is the rule, it could be good for contributors. For example, we need create the rule like below:

- [Tests]  ~ for test
- [eslint config] ~ for eslint rule
- [guide][react] ~ for gude ? 

What do you think ?

**Comment by ljharb** [comment]
A few points:
 - it's always acceptable and expected for maintainers to edit commit messages, rebase, squash, etc, upon merging - neither the original commit message nor commit authorship should be expected to be retained (although authorship generally is, out of courtesy)
 - The existing git log should indicate the conventions that are used.
 - I'd be fine with a PR that documented our commit messages (we'd probably need some back-and-forth on the PR before it was final), although this is the first time it's really come up.

**Comment by sotayamashita** [comment]
> it's always acceptable and expected for maintainers to edit commit messages, rebase, squash, etc, upon merging - neither the original commit message nor commit authorship should be expected to be retained (although authorship generally is, out of courtesy)

I understand the necessity of maintainers to edit.

 > I'd be fine with a PR that documented our commit messages (we'd probably need some back-and-forth on the PR before it was final), although this is the first time it's really come up.

In Airbnb, there is the rule of commit message ? if it is, I think we can create new one based on existing rule.

**Comment by ljharb** [comment]
No, we don't have any commit message convention that spans projects.

**Comment by gergoerdosi** [comment]
Earlier I created a Git guide at the company I used to work. You can use it as an inspiration:

https://github.com/ideas/guides/tree/master/git

**Comment by sotayamashita** [comment]
@ljharb I will create a CONTRIBUTING.md in reference to existing commit log. 

@gergoerdosi I appreciate it :smile:

**Comment by sotayamashita** [comment]
@ljharb I just close it because I am busy now. If I create the PR, I reopen this issue.
