### ISSUE TITLE
React-Native + AirBnB's ESLint configuration

### ISSUE THREAD

**Issue by ItsNoHax** [airbnb/javascript#1305]
We have started using ESLint in our react-native project and I am interested to find out what the ideal settings are.

I currently have the following in my .eslintrc.json file.

```
{
    "extends": ["airbnb", "plugin:react-native/all"],
    "plugins": [
        "react-native"
    ]
}
```

Some questions I have: I keep seeing this "parser": 'babel-eslint' but when I went to their github they mention this is no longer neccesary. Should I be using it or not?

**Comment by ItsNoHax** [comment]
Also if someone could Label this as a question, would be great!

**Comment by tomkel** [comment]
https://node.green shows which features are supported natively in different versions of node.
Here's another view: http://kangax.github.io/compat-table/es2016plus/

Basically, use `parser: "eslint"` until something breaks, which indicates that you are using an ES feature which hasn't made it into node yet. Then switch to `"babel-eslint"`.

**Comment by ItsNoHax** [comment]
Got all info I need
