### ISSUE TITLE
why using the 4 space === tab ?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [airbnb/javascript#1306]
# why using the 4 space === tab ?

**Comment by ljharb** [comment]
We use 2-space tabs, as you can see [here](https://github.com/airbnb/javascript#whitespace--spaces).

This was chosen primarily because it's the most common indentation in Ruby, which the majority of Airbnb's developers at the time used primarily.

**Comment by xgqfrms-GitHub** [comment]
Anyway, I don't like this!
it make codes to tight for bad view!

**Comment by ljharb** [comment]
You are more than welcome to use eslint configuration overrides, or to fork this styleguide, to make any changes you like.
