### ISSUE TITLE
Style-free ESLint Config

### ISSUE THREAD

**Issue by jacobp100** [airbnb/javascript#1307]
What are your thoughts on a purely style-free config, so that people (me) can use prettier to do this?

**Comment by SimenB** [comment]
You can use https://github.com/lydell/eslint-config-prettier on top of airbnb

**Comment by ljharb** [comment]
Bad style is a bug too, and prettier simply can't possibly enforce enough rules automatically to be an eslint replacement.

You certainly can use prettier if you prefer it to eslint autofixing, but this guide and I highly discourage limiting yourself to only enforcing things that can be autofixed. Additionally, if eslint autofixing lacks anything prettier has, I'm sure filing an issue on eslint would be helpful.
