### ISSUE TITLE
Naming conventions for stateful components

### ISSUE THREAD

**Issue by NitroBAY** [airbnb/javascript#1316]
I'm new to React and there's a lot of new terms etc. I try to do things rights so I try to use your guidelines (thanks for that BTW).
Let's think about a card component.
As far as I understand I should split elements in a stateful components and a stateless function.
For instance I have a list of drugs (legal drugs, not silkroad V3.0 ^^), I want to display a list of `Card` so, doing my best to follow good patterns, I have a stateless function : 
```
export default function Card(props) {
  return (
    <div className="drug-card card hoverable">
{/*Here goes my HTML*/}
    </div>
  );
}
```
Plus a component with all logic (subscribe to data, states etc.) whereas stateless function only cares about props it receives from the stateful component.
Am I right ?
Let's assume than yes for now.  Here's my question : where should I put, or at least where do you put, the stateful components and the stateless function. In the same file, in the same folder, with different names for each files : `Index.jsx` for the stateless component and `Container.jsx` for the stateful component.

Is this a good pattern for example ?

![image](https://cloud.githubusercontent.com/assets/9869317/23383803/6f25821a-fd48-11e6-9b54-f83f923facc8.png)

I hope I didn't irritate you with what's is very probably noob questions but the React land is new for me.

**Comment by ljharb** [comment]
It's a fine question. I don't think this guide should proscribe a strict naming convention here. Having `CardContainer` seems fine, but I've also seen `ConnectedCard`, or `StatefulCard`, etc.

**Comment by NitroBAY** [comment]
Very thanks. As I didn't find anything about that in issues I was afraid that I was totally missing the point.

**Comment by NitroBAY** [comment]
Okay I could think anyway about the naming convention, even though I follow guidelines I didn't totally lost my brain.
Still one question if one has `Card/CardContainer.jsx`, do you think that one should still follow your guidelines and use `Card/Index.jsx` for the stateless function ?

**Comment by ljharb** [comment]
One of them should be `Card/index.jsx` (lowercase `index`, always) - whether the stateful or stateless one is the index depends on which one you consistently want to import from elsewhere in the app.

**Comment by NitroBAY** [comment]
Okay. Another unrelated question (sorry for polluting this thread) what do you use for css with react ? Inline css, modulus css or like me you have a less/sass file in the folder along with components ?

**Comment by ljharb** [comment]
We currently use Aphrodite for CSS. https://github.com/airbnb/javascript/tree/master/css-in-javascript may be helpful here.

(I'm going to close this issue but feel free to keep discussing)

**Comment by NitroBAY** [comment]
Sorry to keep talking in this thread but I think the choice pre-processor vs react inline style is not an easy decision and I've struggled with that decision so I want to share my experience (even tho probably nobody is gonna read it).
Here's my experience on SASS/LESS/CSS vs inline style with React : 
After your message I try to make the more proper sass possible (following your guideline actually) : every `.scss` style a react element and thus every file start by `.ElementName { // my style }`. I strictly followed your guidelines, use BEM and OOCSS (to use BEM I've been using mixins so inside my `.ElementName { @include element('element-name') { // my style } }).`). Trying to make the best of what css + pre-preprocessors could do for me makes me understand (not just by reading but by creating my own experience) what inline style could bring : 
- It brings really enclosed style. Yeah even though you can all put inside `.Element {}` where Element is your react component or your UI element you got to make a lot of a work to follow BEM and have encapsulated style (create folder with both your React elt and your css the  import the css into an import file, define mixins to complies to BEM, everytime create a `.Element` and put all inside). Even though it's working this way I feel that using react inline style is just going to feel better as you don't need a complex organisation so your sass matches your React components as defining inline style inside your component is made to fit your component.
- I remembered why sometime in my life I thought "I can use js helpers in my HTML with blaze (a library where you define HTML template) but not in my `scss` and that makes that I just cannot change the theme if I want. There's no way as you can change css with JS, but when it's a generated from sass css you cannot change the colors as it's been defined in a sass variable. So yeah React allows you to use JS when generating css and that's cool, probably the best use case is themes.
- I can have everything in a single file. At first this seem to be a bad practice but actually it's not. This is AWESOME. React is awesome because it allows to create a real component fully independent from everything else : for the first time we could really just give a *single* file that contains everything CSS + HTML + JS. So sharing components is really possible and that's awesome. If you created something cool in your app sharing to other devs or reuse it somewhere else was complex : move the HTML (or the HTML+JS template), the CSS or the SASS (if it's a file which need a pre-processor you need special requirments to compile it etc.) + the JS. I finally feel how great is React.
So inline style is better in React land but one must first get the point of the components and try to make sass that fits with the components to understand that (or maybe I'm slow to understand, probably...).

**Comment by NitroBAY** [comment]
Then @ljharb (sorry to keep asking questions who are furthermore off-topic but I cannot find thought about that, maybe your guideline could show the way maybe I'm thinking wrong) do you agree that importing 3rd party css should better be done via a `.css` file included in `head` that inline styled ?
