### ISSUE TITLE
Question about JavaScript Style Guide 3.8 object spread operator

### ISSUE THREAD

**Issue by RadianSmile** [airbnb/javascript#1321]
The example goes 
```javascript
//good
const original = { a: 1, b: 2 };
const copy = { ...original, c: 3 }; // copy => { a: 1, b: 2, c: 3 }

const { a, ...noA } = copy; // noA => { b: 2, c: 3 }
```

But the [MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Spread_operator) says that 
>  the spread operator can be applied only to iterable objects

The `original` object is not iterable. How could you make the example code work? 

And in my test, `console.log(...original)` really get errors.

**Comment by RadianSmile** [comment]
Sorry, the code works fine in babel repl.

**Comment by ljharb** [comment]
MDN is referring to the array spread operator; here it's the object spread operator.
