### ISSUE TITLE
Rule modification for `comma-dangle`

### ISSUE THREAD

**Issue by kirkstrobeck** [airbnb/javascript#1327]
```js
'comma-dangle': ['error', {
  arrays: 'always-multiline',
  objects: 'always-multiline',
  imports: 'always-multiline',
  exports: 'always-multiline',
  functions: 'always-multiline',
}],
```

becomes

```json
"comma-dangle": [
  "error",
  {
    "arrays": "always-multiline",
    "exports": "always-multiline",
    "functions": "never",
    "imports": "always-multiline",
    "objects": "always-multiline"
  }
],
```

**Comment by ljharb** [comment]
Why would we want to do that? It was very intentional to require trailing function commas.

This guide assumes you're using https://npmjs.com/babel-preset-airbnb and the equivalent, trailing function commas are in ES2017, and everywhere a trailing comma can exist, this guide claims it must exist.

**Comment by kirkstrobeck** [comment]
Hmm, I am using that, but this has thrown errors in my code. Also, isn’t it against the mindset of a function as it often has specific airity unlike arrays and objects?

**Comment by ljharb** [comment]
No, a function's length is the number of non-defaulted arguments it has - `function f(a, b, c = 3) {}` has a length of 2.

The reason to use trailing commas is *solely* to avoid noisy git diffs when adding or removing a line - it conveys zero semantic meaning in arrays, objects, or functions.
