### ISSUE TITLE
Cannot find module 'estraverse-fb'

### ISSUE THREAD

**Issue by garrettmaring** [airbnb/javascript#1331]
Error:

`Cannot find module 'estraverse-fb`

After running:

```
(
  export PKG=eslint-config-airbnb;
  npm info "$PKG@latest" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs npm install --save-dev "$PKG@latest"
)
```

and then running `eslint app` the above error is show.

**Comment by ljharb** [comment]
You're running the globally installed eslint - you should `npm uninstall -g eslint`.

Your locally installed eslint should only be ran via an `npm run-script`, configured in the "scripts" field of your `package.json`.
