### ISSUE TITLE
(eslint-config-airbnb): Unable to resolve path for image resource in React Native (import/no-unresolved)

### ISSUE THREAD

**Issue by xareelee** [airbnb/javascript#1332]
I got the following errors using `eslint-config-airbnb`:

```
  12:25  error  Unable to resolve path to module '../img/Login_flag_1.png'               import/no-unresolved
  13:30  error  Unable to resolve path to module '../img/Login_arrowDown.png'            import/no-unresolved
  14:32  error  Unable to resolve path to module '../img/Login_policyCheckbox_tick.png'  import/no-unresolved
  15:34  error  Unable to resolve path to module '../img/Login_policyCheckbox.png'       import/no-unresolved
```

Source code:

```js
const flagImg = require('../img/Login_flag_1.png');
const arrowDownImg = require('../img/Login_arrowDown.png');
const policyCheckImg = require('../img/Login_policyCheckbox_tick.png');
const policyUncheckImg = require('../img/Login_policyCheckbox.png');
```

The paths of the images are correct. 

Are those errors normal? Will this issue be fixed? How can I suppress those errors?

**Comment by ljharb** [comment]
You can't require images in node by default - only `.js`, `.json`, and `.node`.

If you've set up custom loading (webpack, I assume), you need to configure eslint-plugin-import with that - see https://github.com/benmosher/eslint-plugin-import#resolvers.

**Comment by xareelee** [comment]
Sorry, I did not demonstrate clearly.

I'm developing React Native. I use `require` for static image resources.

**Comment by ljharb** [comment]
I understand, but that's still not how `require` works by default; so you'd still need to configure eslint-plugin-import so it knows what to do with images.

**Comment by xareelee** [comment]
@ljharb Thanks for rapid reply. 

Do you have any suggestion about how to configure `eslint-plugin-import` to check whether a image source exists?

**Comment by ljharb** [comment]
I suspect the [issues](https://github.com/benmosher/eslint-plugin-import/issues) for eslint-plugin-import will help.
