### ISSUE TITLE
Mutually exclusive no-confusing-arrow and arrow-body-style rules

### ISSUE THREAD

**Issue by kozhevnikov** [airbnb/javascript#1334]
It seems `airbnb-base` eslint config makes `no-confusing-arrow` and `arrow-body-style` rules impossible to fix when ternary operator is used?

```
items.map(item => item.name ? item.name.en : null)
error  Arrow function used ambiguously with a conditional expression  no-confusing-arrow
```
http://eslint.org/docs/rules/no-confusing-arrow

```
items.map((item) => { return item.name ? item.name.en : null; })
error  Unexpected block statement surrounding arrow body  arrow-body-style
```
http://eslint.org/docs/rules/arrow-body-style

**Comment by ljharb** [comment]
`items.map(item => (item.name ? item.name.en : null))`

**Comment by kozhevnikov** [comment]
Thanks. In my defence `no-confusing-arrow` rule doc shows `(a) => (1 ? 2 : 3)` as incorrect code and `(a) => { return 1 ? 2 : 3; }` as correct.

**Comment by ljharb** [comment]
PRs to improve the docs are always appreciated :-)
