### ISSUE TITLE
Question about Object in Arrays

### ISSUE THREAD

**Issue by JPeer264** [airbnb/javascript#1338]
I did not found any style definitions about object in arrays. Which one of the following is preferred?

```js
const someArray = [{
  one: 'value',
  two: 'value',
}, {
  one: 'value',
  two: 'value',
}];
```
or
```js
const someArray = [
  {
    one: 'value',
    two: 'value',
  },
  {
    one: 'value',
    two: 'value',
  },
];
```

**Comment by ljharb** [comment]
The latter would be most consistent with the rest of the guide, but I think either could be fine as long as you're consistent throughout your codebase.

**Comment by dani-sc** [comment]
The second one has the advantage that it leads to cleaner git diffs when adding additional objects.

**Comment by ljharb** [comment]
Well stated - that's why it's most consistent with the rest of the guide, and is also the sole motivation for adding trailing commas everywhere.

**Comment by JPeer264** [comment]
Wouldn't it be good to put that into the styleguide?

**Comment by ljharb** [comment]
Sure! If someone wants to write up a PR adding that section, that'd be great.

**Comment by JPeer264** [comment]
Alright I will do an PR 👍
