### ISSUE TITLE
Configuration for rule 'no-useless-escape' is invalid

### ISSUE THREAD

**Issue by leftynaut** [airbnb/javascript#1344]
I've installed airbnb-base in a project the exact same way I've installed it in a few other projects:
````
yarn add eslint-config-airbnb-base eslint eslint-plugin-import --dev
````

And I'm using the same .eslintrc config file that I'm using in a few other projects: [here](http://pastebin.com/d3tz5RZj)

But for some reason on this one project, after installing airbnb-base - I now get this error:
````
/Users/leftynaut/project/node_modules/eslint-config-airbnb-base/rules/best-practices.js: Configuration for rule "no-useless-escape" is invalid: Cannot read property 'Symbol(Symbol.iterator)' of undefined Referenced from: airbnb-base Referenced from: /Users/leftynaut/project/.eslintrc
````

I had a simple custom rule list beforehand that was working normally in this project. Any idea why this could have happened?

**Comment by ljharb** [comment]
What version of node are you running? Can you confirm what versions of those three eslint packages ended up being installed?

**Comment by leftynaut** [comment]
Node 6.9.5
````
"eslint": "^3.17.0",
"eslint-config-airbnb-base": "^11.1.1",
"eslint-plugin-import": "^2.2.0",
````

**Comment by ljharb** [comment]
If you upgrade eslint to v3.18.0 (to grab any bugfixes) does it still happen?

**Comment by ljharb** [comment]
(btw your ignorePattern for max-len isn't needed, since all imports are from strings, and ignoreStrings is on)

**Comment by leftynaut** [comment]
Yup. 3.18 fixed it --- weird. Thanks for the help (and tip on ignorePattern)

**Comment by ljharb** [comment]
Glad to hear it!

**Comment by milo-** [comment]
Something similar just started happening for me today. Slightly different error though: 

`Configuration for rule "no-useless-escape" is invalid:
undefined is not a function`

Running eslint: 3.18.0 and and eslint-config-airbnb: 14.1.0

**Comment by ljharb** [comment]
@milo- is this on the command line, or in an editor? Are you running a local eslint, or a global one?

**Comment by milo-** [comment]
Doh, a dependency I added recently added an invalid shim. That bubbled up as the above error. Sorry about that, i've got it working now.
