### ISSUE TITLE
SQL Table/Column names and Javascript named in a isomorphic way

### ISSUE THREAD

**Issue by calebeaires** [airbnb/javascript#1346]
How should I name sql database columns and tables as nodejs code always is using its reference as object keys. How to name essentially id names but columns too. 

**The way things is right now**
```
mysql> SHOW COLUMNS FROM Person;
+------------+----------+------+-----+---------+----------------+
| Field 
+------------+----------+------+-----+---------+----------------+
| Id 
| Name
| LivingCountry
+------------+----------+------+-----+---------+----------------+
5 rows in set (0.00 sec)
```

Will be used on the javascript nodejs app like 

```
        let city = {
            Id: 2,
            Name: 'Kent',
            LivingCountry: 'New Yourk'
        }
```

**Is is correct to do like below?**

```
mysql> SHOW COLUMNS FROM person;
+------------+----------+------+-----+---------+----------------+
| Field
+------------+----------+------+-----+---------+----------------+
| personId
| name
| livingCountry
+------------+----------+------+-----+---------+----------------+
5 rows in set (0.00 sec)
```

So, object on nodejs app will be used like this:

```
        let city = {
            personId: 2,
            name: 'Kent',
            livingCountry: 'New Yourk'
        }
```

The question is important because I would like to easy code and maintain the code. SQL has its pattern but the app is essentially javascript typed. It will be better if I make SQL Table/Column names and Javascript named in a isomorphic way.

**What do you experts say about that?**

**Comment by ljharb** [comment]
It's more correct, yes. Only constructor functions should be capitalized.

It's also uncommon in my experience in SQL to capitalize column names in that manner; they're typically lowercased and snake_cased.

**Comment by debrice** [comment]
@ljharb How would you deal with such situation: if your data layer would return your models attribute snake_cased but your front end would be expecting those object attributes to be camelCase ?

I find myself wondering if it's better to adopt a global convention (snake_case vs camelCase on both sides) or having a point of conversion at the backend or the front end (middleware ?) does the conversion.

**Comment by ljharb** [comment]
Two choices:
 1. use camelCase everywhere, but keep using snake_case only for server-generated attributes
 1. always manually convert to camelCase after you get the data back from the network, and use camelCase everywhere.

If you have to pick a global convention on both sides, JavaScript should win - ie, camelCase.

**Comment by debrice** [comment]
Good advice, thank you!
