### ISSUE TITLE
Configuration for rule "no-param-reassign" is invalid 

### ISSUE THREAD

**Issue by kartiklad** [airbnb/javascript#1349]
I think the latest version of eslint-config-airbnb-base v11.1.2 is giving me an error whenever I use the airbnb config with eslint. 

Error log:

```
Error: <project>/node_modules/eslint-config-airbnb-base/rules/best-practices.js:
	Configuration for rule "no-param-reassign" is invalid:
	Value "data["0"].ignorePropertyModificationsFor" has additional properties.

Referenced from: <project>/node_modules/eslint-config-airbnb-base/index.js
Referenced from: airbnb
```

Am I doing something wrong?

**Comment by ljharb** [comment]
That means you didn't update eslint along with it - ie, you didn't update the peer deps.

Rerun the install command in the package readme to update the peer deps to the right versions.

**Comment by kartiklad** [comment]
@ljharb oh ok! Thanks a lot that a very quick response. It works now.
