### ISSUE TITLE
Using special characters in JSX.

### ISSUE THREAD

**Issue by remcohaszing** [airbnb/javascript#1350]
Sometimes it's desired to render special characters in text in JSX that must be somehow escaped, for example single quotes.

Invalid:
```jsx
<p>This isn't valid</p>
```

Method 1:
```jsx
<p>{"This isn't valid"}</p>
```

Method 2:
```jsx
<p>This isn&apos;t valid</p>
```

I personally prefer method 1, but my coworker seems to prefer method 2. I believe consistency is the most important here.

I think this is a common issue and the airbnb style guide could recommend one of these two methods.

**Comment by ljharb** [comment]
Straight quotes are typographically incorrect; always use `“ ” ‘ ’` instead in text.

Note that `{"This isn\'t valid"}` would be quite valid.
