### ISSUE TITLE
Configuration for rule "no-unused-expressions" is invalid

### ISSUE THREAD

**Issue by CNBlackJ** [airbnb/javascript#1351]
I removed node_module/ folder, and run `npm install`,it throw error`Configuration for rule "no-unused-expressions" is invalid`, in [stackoverflow](http://stackoverflow.com/questions/43039265/got-configuration-for-rule-no-unused-expressions-is-invalid-on-linux-but-not) I found the same problem, but I can not solve this problem.
* After I annotate `no-unused-expressions` in the [`eslint-config-airbnb-base/rules/best-practices.js`](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/best-practices.js#L2340), it have not this error.

**Comment by ljharb** [comment]
Your eslint is out of date. If you use the install command in the readme, it will install the proper peer dependencies.
