### ISSUE TITLE
Document no-restricted-syntax options

### ISSUE THREAD

**Issue by Arcanemagus** [airbnb/javascript#1353]
With [ESLint v3.19.0](http://eslint.org/blog/2017/03/eslint-v3.19.0-released) the ability to provide custom messages for `no-restricted-syntax` was added. It would be great if the current [use](https://github.com/airbnb/javascript/blob/b8d8d6e56f0c1d817af002da0f81b57f45ba24db/packages/eslint-config-airbnb-base/rules/style.js#L257) of `no-restricted-syntax` could have some descriptive messages added.

**Comment by ljharb** [comment]
Great idea!
