### ISSUE TITLE
Patch release with breaking change

### ISSUE THREAD

**Issue by jackkainov** [airbnb/javascript#1355]
Hi, we have these versions in our project:
```
"eslint": "~3.18.0"
"eslint-config-airbnb": "~14.0.0",
```
With recent patch release our setup broke. Was there any purpose to release changes as a patch release? 
Release : https://github.com/airbnb/javascript/releases/tag/eslint-config-airbnb-base-v11.1.3
Change: https://github.com/airbnb/javascript/commit/74071a809c22fa1104fe5d86bcd1eda949e1d0d9

From my point of view it should be a minor release, because the new functionality was added, it was an enhancement for a new eslint version that requires update for a minor eslint version.
https://github.com/airbnb/javascript/issues/1353

**Comment by hultberg** [comment]
This might be more a bug. I get this while attempting to lint files:
```
fatal: Error: /project/node_modules/eslint-config-airbnb-base/rules/style.js: Configuration for rule "no-restricted-syntax" is invalid: Value "[object Object]" is the wrong type. Referenced from: /project/node_modules/eslint-config-airbnb-base/index.js Referenced from: airbnb Referenced from: /project/.eslintrc.json
```

**Comment by jackkainov** [comment]
@hultberg Have you tried to update minor eslint version to 3.19.*? It helped me.

**Comment by hultberg** [comment]
@jackkainov I editied my comment after you commented, but I already have the latest eslint. :smile:

**Comment by hultberg** [comment]
I just downgraded `eslint-config-airbnb` to `14.0` (`npm i eslint-config-airbnb@14.0`), awaiting fix.

**Comment by maxkorz** [comment]
Same here. I'm using the latest available version of eslint and eslint-plugin-import

**Comment by jackkainov** [comment]
Our setup that works
├─┬ eslint@3.19.0
├─┬ eslint-config-airbnb@14.1.0
│ └── eslint-config-airbnb-base@11.1.3

**Comment by hultberg** [comment]
Wow. I was under the impression that the atom package I was using for eslinting used the locally installed one, however, that is not the case. It used eslint 3.18.0. I switched to another package that *is* using the locally installed eslint, and now it works. Sorry for the inconvenience. :tada:

**Comment by ljharb** [comment]
The issue is that eslint was not up to date.

We do not consider a peer dep update a breaking change; if you install the package using the command in the readme, you'll get the updated peer deps; similarly, if you `npm install` and have everything properly specified with a `^` semver range (not with `~`, which does not upgrade minors, only patches), `eslint` will always be updated correctly.

There's nothing to fix here.

**Comment by maxkorz** [comment]
@ljharb hi. Could you tell me what's wrong with my setup? I'm using Windows

```
C:\frontend>npm info "eslint-config-airbnb-base@latest" peerDependencies
{ eslint: '^3.19.0', 'eslint-plugin-import': '^2.2.0' }

C:\frontend>npm view eslint version
3.19.0

C:\frontend>npm view eslint-plugin-import version
2.2.0

C:\frontend>npm view eslint-config-airbnb-base version
11.1.3

C:\frontend>gulp lint
[21:51:25] Requiring external module babel-register
[21:51:26] [Building for Production environment]
[21:51:26] Using gulpfile C:\frontend\gulpfile.babel.js
[21:51:26] Starting 'lint'...
[21:51:26] 'lint' errored after 73 ms
[21:51:26] Error: Cannot find module 'eslint-module-utils/resolve'
Referenced from: airbnb-base
Referenced from: C:\frontend\.eslintrc
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\frontend\node_modules\eslint-plugin-import\lib\rules\rules\no-unresolved.js:6:1)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\frontend\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

```

**Comment by maxkorz** [comment]
Oops. I just found out that the error occurs after I run `npm prune`

> This command removes "extraneous" packages. If a package name is provided, then only packages matching one of the supplied names are removed.
> 
> Extraneous packages are packages that are not listed on the parent package's dependencies list.

```
C:\frontend>npm prune
- callsite@1.0.0 node_modules\callsite
- better-assert@1.0.2 node_modules\better-assert
- eslint-import-resolver-node@0.2.3 node_modules\eslint-import-resolver-node
- ms@0.7.1 node_modules\eslint-module-utils\node_modules\ms
- debug@2.2.0 node_modules\eslint-module-utils\node_modules\debug
- pkg-dir@1.0.0 node_modules\pkg-dir
- eslint-module-utils@2.0.0 node_modules\eslint-module-utils
npm WARN client@0.0.0 No repository field.
```
It used to work fine before this update

**Comment by ljharb** [comment]
`npm prune` is supposed to remove everything that's not in `package.json` - i'm not sure where any of those pruned dependencies come from, but if any of them are peer deps of any of your *other* deps (or of, perhaps, eslint-plugin-import) and not in your package.json, then that would cause this.

**Comment by maxkorz** [comment]
@ljharb could you please take a look at this log https://gist.github.com/maxkorz/3e5c3f316350e6643c91d30742706f67
I do:
```
npm init
npm install eslint --save
npm info "eslint-config-airbnb-base@latest" peerDependencies
npm install eslint-plugin-import --save
npm install eslint-config-airbnb-base --save
npm list (no errors)
npm prune
npm list (missing deps in eslint-config-airbnb-base)
```
I don't think this is expected behavior. I have 51 dependency in my package.js and only `eslint-config-airbnb-base` have this problem with `npm prune`

**Comment by ljharb** [comment]
The package readme has an install command that works on Windows; your commands don't necessarily install the correct versions.

as I said - it might be a bug in eslint-plugin-import, I'm not sure. (Running `npm prune` every time is not a common use case, since nobody else is running into this).

I can see [here](https://github.com/benmosher/eslint-plugin-import/blob/master/package.json#L83) that both of these are deps of eslint-plugin-import, so perhaps it's a bug in npm?

If you use --save-dev (since eslint is a dev dep, not a runtime dep) or better, use the install command in the readme, what happens both before and after `npm prune`?

**Comment by maxkorz** [comment]
If I use --save-dev `npm prune` doesn't remove anything. But I'm using NODE_ENV=development for a development server and NODE_ENV=production for a production server. When the NODE_ENV environment variable is set to production, npm will not install modules listed in devDependencies. That's why I install everything into dependencies. That way I don't have to worry about NODE_ENV variable. `npm prune` also have different behavior based on NODE_ENV:

> If the --production flag is specified or the NODE_ENV environment variable is set to production, this command will remove the packages specified in your devDependencies

But as I said, I don't have this kind of problem with any other package.

I found out this issue is definitely connected to NODE_ENV:

package.json:
```
{
  "name": "frontend",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "eslint": "^3.19.0",
    "eslint-config-airbnb-base": "^11.1.3",
    "eslint-plugin-import": "^2.2.0"
  }
}
```
```
C:\frontend>SET NODE_ENV=development

C:\frontend>npm prune // nothing gets removed
npm WARN frontend@1.0.0 No description
npm WARN frontend@1.0.0 No repository field.

C:\frontend>SET NODE_ENV=production

C:\frontend>npm prune
- eslint-import-resolver-node@0.2.3 node_modules\eslint-import-resolver-node
- ms@0.7.1 node_modules\eslint-module-utils\node_modules\ms
- debug@2.2.0 node_modules\eslint-module-utils\node_modules\debug
- pkg-dir@1.0.0 node_modules\pkg-dir
- eslint-module-utils@2.0.0 node_modules\eslint-module-utils
npm WARN frontend@1.0.0 No description
npm WARN frontend@1.0.0 No repository field.
```

As you can see the `npm prune` command removes packages only if variable NODE_ENV is set to `production`. Any thoughts?

**Comment by ljharb** [comment]
You shouldn't be running npm install in production at all :-/ but this is definitely off topic.

Does the same thing happen with NODE_ENV set to development but `npm prune --production`?

**Comment by maxkorz** [comment]
Yes.
```
C:\frontend>SET NODE_ENV=development

C:\frontend>npm prune
npm WARN frontend@1.0.0 No description
npm WARN frontend@1.0.0 No repository field.

C:\frontend>npm prune --production
- eslint-import-resolver-node@0.2.3 node_modules\eslint-import-resolver-node
- ms@0.7.1 node_modules\eslint-module-utils\node_modules\ms
- debug@2.2.0 node_modules\eslint-module-utils\node_modules\debug
- pkg-dir@1.0.0 node_modules\pkg-dir
- eslint-module-utils@2.0.0 node_modules\eslint-module-utils
npm WARN frontend@1.0.0 No description
npm WARN frontend@1.0.0 No repository field.
```

Please note that `npm prune` doesn't remove any dependency of `eslint` itself.

```
C:\frontend2>npm list --depth 1
frontend@1.0.0 C:\frontend2
`-- eslint@3.19.0
  +-- babel-code-frame@6.22.0
  +-- chalk@1.1.3
  +-- concat-stream@1.6.0
  +-- debug@2.6.3
  +-- doctrine@2.0.0
  +-- escope@3.6.0
  +-- espree@3.4.1
  +-- esquery@1.0.0
  +-- estraverse@4.2.0
  +-- esutils@2.0.2
  +-- file-entry-cache@2.0.0
  +-- glob@7.1.1
  +-- globals@9.17.0
  +-- ignore@3.2.6
  +-- imurmurhash@0.1.4
  +-- inquirer@0.12.0
  +-- is-my-json-valid@2.16.0
  +-- is-resolvable@1.0.0
  +-- js-yaml@3.8.2
  +-- json-stable-stringify@1.0.1
  +-- levn@0.3.0
  +-- lodash@4.17.4
  +-- mkdirp@0.5.1
  +-- natural-compare@1.4.0
  +-- optionator@0.8.2
  +-- path-is-inside@1.0.2
  +-- pluralize@1.2.1
  +-- progress@1.1.8
  +-- require-uncached@1.0.3
  +-- shelljs@0.7.7
  +-- strip-bom@3.0.0
  +-- strip-json-comments@2.0.1
  +-- table@3.8.3
  +-- text-table@0.2.0
  `-- user-home@2.0.0


C:\frontend2>npm install && npm update && npm prune
npm WARN frontend@1.0.0 No description
npm WARN frontend@1.0.0 No repository field.
npm WARN frontend@1.0.0 No description
npm WARN frontend@1.0.0 No repository field.
```

As you can see, eslint have a lot of dependencies and there's nothing to install or update and still `npm prune` doesn't remove anything.

**Comment by ljharb** [comment]
I'm not sure what to tell you - can you file a separate issue for this, with a summary of this info?

**Comment by maxkorz** [comment]
Yeah will do. Also I'm going to open issue about this here https://github.com/npm/npm

**Comment by maxkorz** [comment]
@ljharb I found existing issue that describes the problem: https://github.com/npm/npm/issues/15669
`eslint-plugin-import`'s package.json has `eslint-module-utils` and `eslint-import-resolver-node` dependencies listed in both dependencies and devDependencies

**Comment by ljharb** [comment]
That's just an npm bug then. You can certainly make a pr to eslint-plugin-import to remove the dev dep entries.
