### ISSUE TITLE
Configuration for rule "arrow-parens" is invalid

### ISSUE THREAD

**Issue by shreyas-a** [airbnb/javascript#1359]
Configuration for rule "arrow-parens" is invalid: Value "as-needed,[object Object]" has more items than allowed.  Referenced from: airbnb-base Referenced from: my-repo/.eslintrc

`"devDependencies": {
    "eslint": "^3.19.0",
    "eslint-config-airbnb-base": "^11.1.3",
    "eslint-plugin-import": "^2.2.0"
 }`

**Comment by ljharb** [comment]
Are you sure you're running the local eslint and not a global one? How are you running eslint? Is it on the command line or in an editor?

**Comment by ljharb** [comment]
The as-needed change is from many eslint versions ago, fwiw.

**Comment by shreyas-a** [comment]
OPPS! my bad. Since i had nested package jsons, the inner one was having older eslint version. Apologies for wasting time & thanks for your instant help!
