### ISSUE TITLE
Version 11.1.3 is broken

### ISSUE THREAD

**Issue by ivanbanov** [airbnb/javascript#1360]
![image](https://cloud.githubusercontent.com/assets/2953018/24732729/05a16250-1a49-11e7-93f7-fb548b14f1b5.png)

**Comment by ljharb** [comment]
Nope, you just don't have an up to date eslint. If you run `npm ls` you'll see that eslint is not updated properly; if you run the install command in the package readme, you'll ensure all the peer deps are correctly loaded in your package.json.
