### ISSUE TITLE
Contradiction Between 23.2 (getters/setters) and 23.4 (get() and set() functions)

### ISSUE THREAD

**Issue by justinwilaby** [airbnb/javascript#1367]
There appears to be a direct contradiction between [23.2](https://github.com/airbnb/javascript#accessors--no-getters-setters) and [23.4](https://github.com/airbnb/javascript#accessors--consistent). 

The documentation provides reasoning that the use of getters and setters "... cause unexpected side effects and are harder to test, maintain, and reason about.". But then allows the use .of `get(key)` and `set(key, val)` which are actually much, much worse for unexpected side-effects, testability, maintainability and reasoning about and provide little benefit over accessors and have huge incompatibilities with the vast majority of smart IDEs.

**get() and set() functions Does not...**
1. Allow refactoring when property names change. You must find all usages of `jedi.get('lightsaber')` manually. This is incompatible with most smart IDEs and may lead to enormous application-wide failures if one is missed.
2. Allow you to define read-only properties without placing logic in the `set(key, val)` that throws for particular properties or requires using `Object.defineProperty` in the constructor to declare the backing variable as read-only. e.g. `Object.defineProperty('someProperty', {writable: false});`
3. Catch misspellings of keys e.g. `jedi.set('lightsabber', lightsaberInstance)`. IDEs will not show a warning or error at all.
4. Allow the developer to quickly glance at the class to determine it's "shape". It's not immediately clear which properties are available or whether they are read-only or writable.
5. Provide any auto-complete feedback whatsoever. Most developers don't use VIM or Notepad to write large scale enterprise software. No intelli-sense or autocomplete makes developing painful.
6. Provide a concrete way to access or set properties. When do I use `get()` over direct property access? When should I use `set()`? If set gives a developer trouble, she/he might just access the backing property directly.
7. Many more reasons this is a problem...

**getters/setters Does...**
1. Provide a concrete class shape that is easily knowable and readily identifiable read-only properties.
2. Provide an easy (and native) way to enforce read-only properties without implementing this logic manually and for every read-only property.
3. Provides feedback from the IDE including autocomplete and easy refactoring. Most IDEs will complain when a property name is misspelled when accessing it.
4. Allows the developer the flexibility to initialize the property value when first accessed (if needed) without having to create a huge switch statement in a `get(key)` function.
5. Allows the developer to cast primitives without having a huge switch statement in a `set(key, val)` function. e.g. `set variable(value){ value = +value; this.backingVariable = value;}`

**recommendation**
Allow getters/setters "with caution" and define an acceptable use case and provide implementation examples.

**Comment by ljharb** [comment]
ES5 getters/setters are the problem - "getFoo" and "setFoo" methods are totally fine. They are better for side effects because it is apparent at their usage site that they are functions. Your concerns about shape are unfounded, since you'd initialize all data properties in the constructor.

Something that looks and acts like a data property *should only be a data property*. Using ES5 getters/setters makes functions pretend to be data properties.

What IDEs need to work better is irrelevant; JS is absolutely most commonly written in editors, not IDEs - and a good tool bends to your code, never the other way around.

This guide will continue to advise never using get/set, for any reason, in any circumstance.

**Comment by justinwilaby** [comment]
Hi there! Actually, I wasn't talking about getFoo() or setFoo() at all. I was talking about the recommendation to use `get('arbitraryKey')` and `set('arbitraryKey', arbitraryValue);` This pattern requires the use of string keys and bracket notation when accessing the backing instance property and has no way to tell if that property "belongs" to that class or not. 

Also, how do you reconcile the use of the get/set signatures conflicting with the function signatures of the much more capable [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) object? 

Also, with that pattern, you could get code like this:
```
if(jedi.get('lightsabler') !== someValue){
  jedi.set('lightsabber', someValue);
}
```
or this:
```
class Jedi{
  get(property){
    return this[property];
  }
  set(property, value){
  switch(peropertyName){
   case 'lightsaber':
     // do stuff
    break;
    // Tons of other cases below
  }
 }
}
```
This is obviously a lot less desirable than a well formed getter/setter pair. Mutators have had a long history of uses in several languages. Not recommending them is like not recommending ES6 classes because they are prototypes that pretend to be classes.

**Comment by ljharb** [comment]
`Proxy` should also be avoided; it's massively slow and allows for some really awful metaprogramming patterns - and `get foo() {}` doesn't conflict with the `get() {}` method on a Proxy handler object anyways.

I agree that a `get` and `set` that take an arbitrary key are not ideal - that example likely dates from when we used Backbone.

Mutators' long history of use in other languages is a big part of why, in modern web dev, it's considered a bad practice.
