### ISSUE TITLE
Translation: Persian

### ISSUE THREAD

**Issue by EmpireWorld** [airbnb/javascript#1373]
Hi @airbnb.

I wana to translate this repo in Persian language.

Please Guide me.

**Comment by ljharb** [comment]
@EmpireWorld typically what's one is:
 1. fork the repo
 1. make a branch for a later pull request
 1. translate it on master
 1. make a pull request (from the branch) that adds a link to your fork
 1. follow this repo, and keep your translation updated

Thanks!
