### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by evheniy** [airbnb/javascript#1377]
Hi

https://github.com/airbnb/javascript/tree/master/react#props

A lot of places with "Me waving hello"
Maybe "We having hello"?
Or is this joke?

**Comment by ljharb** [comment]
That's a valid partial English sentence that might describe a picture, and what the subject is doing.

"We having" wouldn't be proper English in any circumstances.

If I misunderstood your question, I'm happy to reopen.
