### ISSUE TITLE
React.createClass is deprecated

### ISSUE THREAD

**Issue by TheLordHighExecutioner** [airbnb/javascript#1382]
The React style guide recommends using React.createClass, but this feature will soon be deprecated.

**Comment by ljharb** [comment]
The guide already says so: https://github.com/airbnb/javascript/tree/master/react#class-vs-reactcreateclass-vs-stateless

You'll also be able to continue using `create-react-class` for the forseeable future if you want, it's just the `createClass` property on `React` that they've (already) deprecated.

Is there a specific place where you see createClass being recommended?

**Comment by TheLordHighExecutioner** [comment]
Just kidding, I misread that entry!
