### ISSUE TITLE
Question: Using Enzyme and React

### ISSUE THREAD

**Issue by JPeer264** [airbnb/javascript#1384]
By default `comma-dangles` on functions are set to `always-multiline`. How do you actually handle the following test example:

```js
const wrapper = shallow(
  <Component>
    <MyComponent />
  </Component> // this will require a comma-dangle here
);
```

Do you disable this specific rule in tests if you use `enzyme` or do you have an internal workaround?

**Comment by ljharb** [comment]
This isn't specifically an enzyme question, but it does come up a lot with `shallow`.

Here's what the rule requires:
```jsx
const wrapper = shallow(
  <Component>
    <MyComponent />
  </Component>,
);
```
or
```jsx
const wrapper = shallow((
  <Component>
    <MyComponent />
  </Component>
));
```

**Comment by ljharb** [comment]
(for the record, we comply with the rule)
