### ISSUE TITLE
transfer a value to boolean

### ISSUE THREAD

**Issue by MAYDAY1993** [airbnb/javascript#1390]
I'm wondering why using !! is best and Boolean() is good but new Boolean is bad,can you provide some references or some pratice to help me understand this rule? I know that using new Boolean can new an object and we can other methods to this object ,etc.Thank you for answering
[https://github.com/airbnb/javascript#coercion--booleans](url)

**Comment by ljharb** [comment]
Sure!

`new Boolean()` produces an object - as opposed to a boolean primitive. This is a holdover from Java patterns, and should always be avoided, as there's not really any use case to use so-called "boxed primitives" - ie, object versions of a primitive.

`Boolean(x)` and `‼x` are equivalent except that `‼` is syntax, and as such, can't ever be broken by somebody replacing the global `Boolean`. Separately, `‼` is a common idiom for "cast to boolean" in many programming languages, so it's easy to understand.

**Comment by MAYDAY1993** [comment]
@ljharb got it,  !! and Boolean's rule is the same,right?That means using !! is simplier ,I will use !! for casting to boolean
