### ISSUE TITLE
Document about the restriction of Math.pow()?

### ISSUE THREAD

**Issue by OpenGG** [airbnb/javascript#1392]
[Changelog](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/CHANGELOG.md#1000--2016-11-06) said

> prefer ** over Math.pow

But [Airbnb JavaScript Style Guide](https://github.com/airbnb/javascript) didn't explain why.

**Comment by ljharb** [comment]
We could add a section; but in general, syntax should always be preferred over API when they're equivalent.

**Comment by eneko89** [comment]
Are you taking into account that ** operator is an ES2016 (ES7) feature, while the style guide is supposed to be ES2015 (ES6) compatible?

We are having troubles in our company with this, cause the linter is telling us that we should prefer ** over Math.pow, but Babel (with ES6 presets) doesn't parse it.

**Comment by ljharb** [comment]
@eneko89 I'm not sure where you see that the style guide is limited to ES2015 - this is a JavaScript style guide. As soon as a feature is stage 4, and thus in the language, this guide may require it.

It's expected you're using https://npmjs.com/babel-preset-airbnb or the equivalent. Transforming `**` is particularly trivial, so there's not really a good reason not to be using it.

**Comment by HouCoder** [comment]
We're having the same problem with @eneko89.

Would be better to have a ES7 section to specifically mention new ES7 syntaxes in README, just like what you did for ES6: [ECMAScript 6+ (ES 2015+) Styles](https://github.com/airbnb/javascript#ecmascript-6-es-2015-styles).

**Comment by ljharb** [comment]
Note that the section is 2015+, not 2015. A PR to add a note about `**` would be appreciated.

If you're using babel-preset-airbnb, it should just work - I suggest that.

**Comment by HouCoder** [comment]
I made a PR for the `**` operator, feel free to have a look, thanks: https://github.com/airbnb/javascript/pull/1469

**Comment by micky2be** [comment]
I don't understand why one would prefere using `**` over `Math.pow`
`++` and `--` or forbidden but `**` is good?
In term of readability I prefere to see `Math.pow` a thousand time more than `**`

**Comment by ljharb** [comment]
@micky2be ** does not mutate a variable, it produces a new value - so yes, ++/-- is bad.

Math.pow is only more readable if you're familiar with its use in JS - ** is more common in other languages, so it's more readable overall.

**Comment by ljharb** [comment]
Closed in #1469.

**Comment by micky2be** [comment]
@ljharb if you ask Crowkford, it's better to avoid `++` because it makes fomula difficult to read.
This is why for me forcing the use of `**` doesn't make sense to me.
The fact that it exists in other languages does not change that.

`widht * height ** dist / time` <- is it a typo or is this normal

**Comment by ljharb** [comment]
Luckily we have another rule to force parens there, ensuring its readability.

**Comment by sjorsvanheuveln** [comment]
My uglifyJS was actually crashing because I changed Math.pow() into **. Must be a Babel setup thing on my end... So how do disable this linting error for only **?

**Comment by ljharb** [comment]
@sjorsvanheuveln if you're using https://npmjs.com/babel-preset-airbnb then you won't run into trouble here. It's far better to just transpile `**` than to disable the linting error.

**Comment by piuccio** [comment]
By the way for reference the setting is [here](https://github.com/airbnb/javascript/blob/8ed1d855bbefccbb147fe17d902a18c8f9aa3977/packages/eslint-config-airbnb-base/rules/best-practices.js#L195) if you really want, you can copy that and remove the parts you don't need
