### ISSUE TITLE
Provide a full config example

### ISSUE THREAD

**Issue by EmpireWorld** [airbnb/javascript#1394]
Hi.

Please provide a full eslint config example in the end, that makes easy for everyone to copy and paste that.

Like this:
```json
{
  "no-var": true
}
```

Thanks.

**Comment by ljharb** [comment]
@EmpireWorld i have no idea what you're referring to; the point of using our eslint config is that you don't copy and paste anything.

Perhaps https://npmjs.com/eslint-config-airbnb-base is what you're looking for?

**Comment by EmpireWorld** [comment]
I mean write all description configurations in one example.

**Comment by ljharb** [comment]
That's what eslint's docs are for; you'll notice that each rule lists the eslint rule(s) that it applies to is a link to the relevant documentation.

**Comment by EmpireWorld** [comment]
So write total of eslint rule links in a single config.
