### ISSUE TITLE
jsx-a11y/img-has-alt changed to jsx-a11y/alt-text in newer jsx-a11y

### ISSUE THREAD

**Issue by philwhln** [airbnb/javascript#1404]
> Always include an alt prop on <img> tags. If the image is presentational, alt can be an empty string or the <img> must have role="presentation". eslint: jsx-a11y/img-has-alt

eslint-plugin-jsx-a11y v5.0.0 changes this...
> [breaking] Refactor img-has-alt rule into alt-text rule

**Comment by ljharb** [comment]
`eslint-config-airbnb` is not currently compatible with v5 of eslint-plugin-jsx-a11y.

If you run `npm ls`, you'll see that you have invalid dependencies installed; if you fix them, you won't see this error.

The next major release of `eslint-config-airbnb` will support v5 of `eslint-plugin-jsx-a11y`; until then, you have to stick with v4.

**Comment by philwhln** [comment]
Thanks @ljharb! and for the quick response 👍
