### ISSUE TITLE
Update Peer Dependency to Support eslint-plugin-jsx-a11y v5.0

### ISSUE THREAD

**Issue by virgofx** [airbnb/javascript#1405]
Need to update the peer dependency `eslint-plugin-jsx-a11y` to 5.0 which has various bugfixes.

**Comment by ljharb** [comment]
It's a semver-major bump; bugfixes go in a patch.

It's already updated on master, pending a release.

In the meantime, continue to use v4.

**Comment by virgofx** [comment]
@ljharb Awesome. How soon till next major release. Desperately needing these fixes :)
