### ISSUE TITLE
Definition for rule 'jsx-a11y/img-has-alt' was not found

### ISSUE THREAD

**Issue by Areks** [airbnb/javascript#1406]
https://github.com/evcohen/eslint-plugin-jsx-a11y/pull/220  Refactor img-has-alt to alt-text

**Comment by filipposarzana** [comment]
Confirm, rules has change and it's breaking us too

**Comment by gkatsanos** [comment]
Same.

**Comment by reneruiz** [comment]
It looks like the team is at least aware: https://github.com/airbnb/javascript/commit/121a95d71524032bfa858271b318aa6e19553dfc#diff-e16356eb9f3a7a45b636115432854777

**Comment by ljharb** [comment]
Run `npm ls` and you'll see that your dependencies are invalid. The airbnb config does not currently support v5 of the jsx plugin, only v4.

Fix your dependencies, and you won't have any errors. The eslint config readme has a command you can run to ensure your peer deps are correct.

**Comment by stepankuzmin** [comment]
The problem is still here. `eslint-config-airbnb@15.0.1` has peer dependency `eslint-plugin-jsx-a11y@^5.0.1`, but I'm getting `Definition for rule 'jsx-a11y/img-has-alt' was not found `

**Comment by knowbody** [comment]
can this be reopened as this is a bug in the current version of `eslint-config-airbnb@15.0.1`

**Comment by ljharb** [comment]
@stepankuzmin @knowbody what does `npm ls` say?

**Comment by DJTB** [comment]
same issue with the following

`npm info eslint-config-airbnb@latest peerDependencies`
 ```
{ eslint: '^3.19.0',
  'eslint-plugin-jsx-a11y': '^5.0.1',
  'eslint-plugin-import': '^2.2.0',
  'eslint-plugin-react': '^7.0.1' }
```
  
`npm ls`
```
├─┬ eslint@3.19.0
├── eslint-config-airbnb@15.0.1
├── eslint-config-airbnb-base@11.2.0
├─┬ eslint-import-resolver-webpack@0.8.1
├─┬ eslint-plugin-import@2.2.0
├─┬ eslint-plugin-jsx-a11y@5.0.3
├── eslint-plugin-react@7.0.1
├── eslint-plugin-redux-saga@0.3.0
```

`package.json`
```
    "eslint-config-airbnb": "~15.0.1",
    "eslint-config-airbnb-base": "~11.2.0",
    "eslint-import-resolver-webpack": "0.8.1",
    "eslint-plugin-import": "2.2.0",
    "eslint-plugin-jsx-a11y": "~5.0.3",
    "eslint-plugin-react": "7.0.1",
    "eslint-plugin-redux-saga": "0.3.0",
```

**Comment by ljharb** [comment]
@DJTB those should all be correct. How are you running `eslint` to get the error? Are you sure you're running the local one, and not a global one (or gulp-eslint etc)?

**Comment by DJTB** [comment]
hey @ljharb, sorry I deleted my comment when I realised it wasn't valid - and then you probably replied by email. I had a `jsx-a11y/img-has-alt` rule getting picked up from `$HOME/.eslintrc` - so my situation was a false alert.

**Comment by ljharb** [comment]
No worries :-) I'll delete our mini-convo then.

**Comment by VinSpee** [comment]
Hi! I am having this same issue.

I tried

`yarn list`:
```bash
❯ yarn list | grep a11y
├─ eslint-plugin-jsx-a11y@4.0.0

```

`npm info "eslint-config-airbnb@latest" peerDependencies`
```bash
❯ npm info "eslint-config-airbnb@latest" peerDependencies
{ eslint: '^3.19.0',
  'eslint-plugin-jsx-a11y': '^5.0.1',
  'eslint-plugin-import': '^2.2.0',
  'eslint-plugin-react': '^7.0.1' }
```

I saw that the `peerDep` version for `eslint-plugin-jsx-a11y` _is_ `^5.0.1`, so I tried upgrading that as well. Still getting errors like:

`Definition for rule 'jsx-a11y/alt-text' was not found [Error/jsx-    a11y/alt-text]`

**Comment by gkatsanos** [comment]
@VinSpee how about if you `rm -rf node_modules && npm install` ?

**Comment by VinSpee** [comment]
@gkatsanos tried that. I _am_ getting different errors for each version (4.x and 5.x):

`@4.0.x`:

```sh
  1 | Definition for rule 'jsx-a11y/alt-text' was not found [Error/jsx-a11y/alt-text]
  2 | Definition for rule 'jsx-a11y/interactive-supports-focus' was not found [Error/jsx-a11y/interactive-supports-focus]
  3 | Definition for rule 'jsx-a11y/no-noninteractive-element-interactions' was not found [Error/jsx-a11y/no-noninteractive-element-interactions]
  4 | Definition for rule 'jsx-a11y/media-has-caption' was not found [Error/jsx-a11y/media-has-caption]
  5 | Definition for rule 'jsx-a11y/no-interactive-element-to-noninteractive-role' was not found [Error/jsx-a11y/no-interactive-element-to-noninteractive-role]
  6 | Definition for rule 'jsx-a11y/no-noninteractive-element-to-interactive-role' was not found [Error/jsx-a11y/no-noninteractive-element-to-interactive-role]
  7 | Definition for rule 'jsx-a11y/no-noninteractive-tabindex' was not found [Error/jsx-a11y/no-noninteractive-tabindex]
```

`@5.0.1`:

```sh
1 | Definition for rule 'jsx-a11y/img-has-alt' was not found [Error/jsx-a11y/img-has-alt]
2 | Definition for rule 'jsx-a11y/onclick-has-focus' was not found [Error/jsx-a11y/onclick-has-focus]
3 | Definition for rule 'jsx-a11y/onclick-has-role' was not found [Error/jsx-a11y/onclick-has-role]
```

**Comment by ljharb** [comment]
What does `npm ls` tell you? If it exits nonzero, nothing will work properly - resolve that first.

**Comment by jtraub** [comment]
I had the same problem, but `npm ls` exited with 0 status and all `eslint-config-airbnb` peerDependencies were met.

I spent almost 30 minutes before I realized that this rule was mentioned in project `.elintrc`. Writing this to others who will be facing the same problem: don't forget to check your eslint config.

**Comment by savovs** [comment]
Until this is resolved, try these versions: 
```
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^15.0.1",
    "eslint-loader": "^1.8.0",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^5.0.1",
    "eslint-plugin-react": "^7.1.0",
```

**Comment by ljharb** [comment]
Or, instead of trying to install specific versions, *use the install command in the readme in the first place* which always does the right thing.
