### ISSUE TITLE
Peer dependencies out of date on npm registry?

### ISSUE THREAD

**Issue by nullterminated** [airbnb/javascript#1413]
$ npm info "eslint-config-airbnb@14.1.0" peerDependencies
 
{ eslint: '^3.15.0',
  'eslint-plugin-jsx-a11y': '^3.0.2 || ^4.0.0',
  'eslint-plugin-import': '^2.2.0',
  'eslint-plugin-react': '^6.9.0' }

But https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/package.json

  "peerDependencies": {
    "eslint": "^3.19.0",
    "eslint-plugin-jsx-a11y": "^5.0.1",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-react": "^7.0.1"
},

When I yarn install, 

warning "eslint-config-airbnb@14.1.0" has incorrect peer dependency "eslint-plugin-jsx-a11y@^3.0.2 || ^4.0.0".
warning "eslint-config-airbnb@14.1.0" has incorrect peer dependency "eslint-plugin-react@^6.9.0".

As I have the 5.0.1 & 7.0.1 versions respectively.

**Comment by ljharb** [comment]
They are not out of date; the airbnb config simply does not yet support v5 and v7 of these deps. `npm ls` will tell you that your deps are invalid.

Use the install command in the readme of the airbnb config to get the proper versions.

At some future date, `eslint-config-airbnb` will certainly support these versions, but it doesn't yet.

**Comment by nullterminated** [comment]
Oh, I see the problem. I was looking at head on master, when I should have been looking at the tag. n00b question. Sorry about that.

**Comment by ljharb** [comment]
no prob :-) v15.0.0 of the main config, and v11.2.0 of the base config, have just been released.
