### ISSUE TITLE
Question: Compatibility with eslint@4

### ISSUE THREAD

**Issue by sompylasar** [airbnb/javascript#1421]
It's in `beta` as of now: https://github.com/eslint/eslint/releases/tag/v4.0.0-beta.0

It should introduce changes required to support TypeScript linting with eslint: https://github.com/eslint/typescript-eslint-parser/issues/77#issuecomment-284189144

What do you think?

**Comment by ljharb** [comment]
The config will not be compatible with eslint 4 until it's fully released; and likely a ways after that.

Since this guide does not permit any type systems - it only allows JavaScript - any TypeScript-related rules are not going to be turned on, so that's not really relevant to us.

**Comment by sompylasar** [comment]
Refs https://github.com/airbnb/javascript/issues/1447
