### ISSUE TITLE
Unmet peer dependencies with the latest version ?

### ISSUE THREAD

**Issue by Clafouti** [airbnb/javascript#1422]
Hi,
`npm info "eslint-config-airbnb@latest" peerDependencies`

returns
```
{ eslint: '^3.19.0',
'eslint-plugin-jsx-a11y': '^5.0.1',
'eslint-plugin-import': '^2.2.0',
'eslint-plugin-react': '^7.0.1' }
```

but when I install those packages, I still have 2 unmet dependencies : 

```
UNMET PEER DEPENDENCY eslint-plugin-jsx-a11y@2.2.3 
UNMET PEER DEPENDENCY eslint-plugin-react@6.4.1 
```

Any idea ?

EDIT : I was looking for an answer and found [this](https://github.com/evcohen/eslint-plugin-jsx-a11y/issues/232) so I guess I'm in the same boat (using CRA).

**Comment by ljharb** [comment]
Yep, the issue is that other things in your tree are incompatible with the latest version of eslint-config-airbnb.

You can either downgrade to v14, or you can upgrade/replace the other things with something better.

**Comment by Peripona** [comment]
@ljharb is it better to wait, if it is going to be fixed in sometime soon ?
on our project instead on downgrading to v14 and downgrading all peer dependencies based on that. 
We wish to keep up to date with v15 and jsx@latest and allothers@latest
thanks

**Comment by ljharb** [comment]
It's now released, so you can upgrade using the install command in the readme to get the proper peer deps.

It's not important to always be on latest' and in eslint's ecosystem it's often not possible. The convenience of using a shared config means the tradeoff of not having full control over the dependency versions/
