### ISSUE TITLE
Confusing Alignment & Spacing examples

### ISSUE THREAD

**Issue by kevinch** [airbnb/javascript#1423]
From [Alignment](https://github.com/airbnb/javascript/tree/master/react#alignment):
```
// good
<Foo
  superLongParam="bar"
  anotherSuperLongParam="baz"
/>
```
and from [Spacing](https://github.com/airbnb/javascript/tree/master/react#spacing):
```
// bad
<Foo
 />
```
_Proposition:_

**Alignment**:
```
// bad
<Foo
  superLongParam="bar"
  anotherSuperLongParam="baz"
/>

// good
<Foo
  superLongParam="bar"
  anotherSuperLongParam="baz" />
```
**Spacing**:
No changes.

**Comment by ljharb** [comment]
In fact your alignment examples are reversed; your "good" example must never appear, and only your "bad" example is "good".

**Comment by ljharb** [comment]
Specifically, using `/>` on the same line like that both means that the `<Foo` and `/>` aren't aligned, and it increases the amount of git diff churn when you have to add a new prop after `anotherSuperLongParam`.

**Comment by kevinch** [comment]
Just saw the `tag` section and got it. Thanks for the heads up @ljharb .
