### ISSUE TITLE
Stricter rules for comments

### ISSUE THREAD

**Issue by raduserbanescu** [airbnb/javascript#1425]
As per the documentation on [comments](https://github.com/airbnb/javascript#comments) (sections 18.2 & 18.3) I think stricter rules can be enforced. Below is something I have tested in my projects.

```diff
-    'line-comment-position': ['off', {
+    'line-comment-position': ['error', {
       position: 'above',
       ignorePattern: '',
       applyDefaultPatterns: true,
     }],
```

```diff
-    'no-inline-comments': 'off',
+    'no-inline-comments': 'error',
```

```diff
     'spaced-comment': ['error', 'always', {
       line: {
         exceptions: ['-', '+'],
-        markers: ['=', '!'], // space here to support sprockets directives
+        markers: ['=', '!', '/'], // space here to support sprockets directives
       },
       block: {
         exceptions: ['-', '+'],
         markers: ['=', '!'], // space here to support sprockets directives
-        balanced: false,
+        balanced: true,
       }
     }],
```

The `/` marker is commonly used by some libraries (ex: [angular-gettext](https://github.com/rubenv/angular-gettext/)) to denote documentation.

```javascript
/// Special comment
```

**Comment by ljharb** [comment]
They indeed can be; we've intentionally chosen not to, as there doesn't seem to be much value in legislating comments in this way. Since comments should never describe "what" (should never be documentation), only "why" or history/motivation, this just doesn't come up much in practice.

**Comment by raduserbanescu** [comment]
Ok, I understand your reasons. I only thought that since they were in the documentation, they could also be in the lint configuration. I will still use them in my projects where it will make sense.

One more question if I may. As per section [18.1](https://github.com/airbnb/javascript#comments--multiline) I know you use `/** ... */` for multi-line comments and from this [issue comment](https://github.com/airbnb/javascript/issues/1276#issuecomment-274577353) I see you do not encourage JSDoc.

But isn't this a JSDoc style comment? (possible problems for the JSDoc parser?)

```javascript
/**
 * Multiple
 * lines
 * comment
 */
```

...instead of the common C style comment (although I find that it does't look as good)

```javascript
/*
 * Multiple
 * lines
 * comment
 */
```

**Comment by ljharb** [comment]
Generally I'd say you're absolutely right! For `line-comment-position`, we've configured it properly, we just haven't enabled it; I'd love a PR that fixed the configuration in `spaced-comment` though.

It's a JSDoc-style comment if it's following the conventions for jsdoc; certainly if a jsdoc parser would break on it, it's not jsdoc-style.

I don't think there's a particularly strong reason to start multiline comments with `/**`, but I also don't think there's a strong reason not to. Since we disallow JSDoc, JSDoc's conventions don't exist for us :-)

**Comment by raduserbanescu** [comment]
I will make a PR just for the `spaced-comment` option. Should I also include the extra `/` marker?

Thank you for your clarification regarding `/** ... */` multi-line comments.

I will do it next week as I am on the road at the moment.

**Comment by ljharb** [comment]
I don't see much value in supporting the extra `/` marker, but the rest seems good.
