### ISSUE TITLE
[Q] Not all airbnb rules are linted

### ISSUE THREAD

**Issue by szachara** [airbnb/javascript#1428]
We have enabled `airbnb-base` in our elint config file, but rules like https://github.com/airbnb/javascript#comments--singleline are not linted.

All lint rules, which don't have eslint id ( like eslint: brace-style jscs: disallowNewlineBeforeBlockStatements ) are not linted, it's this correct behavior? May be I missed something.

So linted are only rules, which have eslint id.

Thank you for advices.

**Comment by szachara** [comment]
Here is our eslint config:
```
{
  "root": true,
  "env": {
    "browser": true,
    "commonjs": true,
    "es6": true,
    "jquery": true
  },
  "extends": [
//    "eslint:recommended",
    "airbnb-base",
    "plugin:import/errors",
    "plugin:import/warnings"
  ],
  "parser": "babel-eslint",
  "parserOptions": {
    "sourceType": "module"
  },
  "plugins": [
    "jsdoc"
  ],
  "globals": {
    "crystal": false
  },
  "rules": {
    // Basic
    "indent": ["error", 4],
    "linebreak-style": ["error", "unix"],
    "quotes": ["error", "single"],
    "semi": ["error", "always"],

    // Our Custom
    "import/no-extraneous-dependencies": 0,
    "no-console": "off",
    "class-methods-use-this": ["error", { "exceptMethods": ["exportSubmit"] }],

    // JSDoc Plugin
    "jsdoc/check-param-names": 1,
    "jsdoc/check-tag-names": 1,
    "jsdoc/check-types": 1,
    "jsdoc/newline-after-description": 1,
    "jsdoc/require-param": 1,
    "jsdoc/require-param-type": 1,
    "jsdoc/require-returns-type": 1,
    // Disabled
    "jsdoc/require-description-complete-sentence": 1,
    "jsdoc/require-hyphen-before-param-description": 1,
    "jsdoc/require-param-description": 1,
    "jsdoc/require-returns-description": 1
  }
}
```

**Comment by ljharb** [comment]
It would be impossible to lint everything in our guide; many of them will forever require human review.

If you see something in our guide that *can* be linted, and do not see a corresponding rule enabled in the config, please open an issue for that specific omission.

**Comment by szachara** [comment]
So I suppose, that it's normal behavior.
I asked, because I wanted to know, if there is something wrong on my side ( e.g. in config ).

**Comment by ljharb** [comment]
It's normal behavior, yes.

**Comment by szachara** [comment]
Thank you for advice 💯 good news for me, that everything works well ;), solved
