### ISSUE TITLE
Spread syntax

### ISSUE THREAD

**Issue by NorthFred** [airbnb/javascript#1430]
In section 3.8 of the JavaScript styleguide, you suggest to use the spread operator to copy an object.
But by default, aren't objects non-iterable in JavaScript?

>     3.8 Prefer the object spread operator over Object.assign to shallow-copy objects. Use the object rest operator to get a new object with certain properties omitted.

```
    // very bad
    const original = { a: 1, b: 2 };
    const copy = Object.assign(original, { c: 3 }); // this mutates `original` ಠ_ಠ
    delete copy.a; // so does this

    // bad
    const original = { a: 1, b: 2 };
    const copy = Object.assign({}, original, { c: 3 }); // copy => { a: 1, b: 2, c: 3 }

    // good
    const original = { a: 1, b: 2 };
    const copy = { ...original, c: 3 }; // copy => { a: 1, b: 2, c: 3 }

    const { a, ...noA } = copy; // noA => { b: 2, c: 3 }


```

**Comment by ljharb** [comment]
Yes, but the object spread operator (which is a stage 3 language proposal) uses Object.assign semantics, while the array spread operator uses iterator protocol semantics.
