### ISSUE TITLE
no-param-reassign : recommended approach? 

### ISSUE THREAD

**Issue by gkatsanos** [airbnb/javascript#1433]
I'm doing the following : 
```
  [...document.querySelectorAll('.selection')].forEach((element) => {
    element.textContent = 'all';
  });
```
and naturally I get 

```console
  27:5  error  Assignment to property of function parameter 'element'  no-param-reassign
```

Besides adding a manual comment exception, is there any other way to avoid this? 
Thanks in advance for any answer

**Comment by ljharb** [comment]
No, that requires a manual comment exception.

**Comment by gkatsanos** [comment]
Thanks

**Comment by noelzubin** [comment]
Yes there is
```
 [...document.querySelectorAll('.selection')].forEach((element) => {
    const el = element;
    el.textContent = 'all';
  });
```
this is not a hack. This is the right fix for that eslint rule

**Comment by ljharb** [comment]
in that case, you can avoid an extra array by doing:
```js
  Array.prototype.forEach.call(document.querySelectorAll('.selection'), (element) => {
    const el = element;
    el.textContent = 'all';
  });
```
instead of the needless array spread.

**Comment by gkatsanos** [comment]
I was aware, but I find the Array spread a bit nicer/easier to read, more concise..

**Comment by ljharb** [comment]
But slower and less correct :-)

**Comment by gkatsanos** [comment]
Define "less correct". Does it give a different result?

**Comment by ljharb** [comment]
That’s fair; the result is the same, but it takes more steps to get there. Also, NodeLists have a forEach method on them directly.
