### ISSUE TITLE
4.5 First case's comment should be bad

### ISSUE THREAD

**Issue by vinceyi** [airbnb/javascript#1435]
4.5  Use return statements in array method callbacks.
First case's comment should be bad

**Comment by ljharb** [comment]
You're referring to https://github.com/airbnb/javascript#arrays--callback-return? What's bad about that?

**Comment by vinceyi** [comment]
Oh, I misunderstand that.
```
// good
[1, 2, 3].map((x) => {
  const y = x + 1;
  return x * y;
`});`
```

The arrow function will return the value by default . Needn't a return statement.
My mistake. Sorry for that.
