### ISSUE TITLE
ESLint - make it easier to find out how to use, and fix link

### ISSUE THREAD

**Issue by dandv** [airbnb/javascript#1445]
For those new to ESLint, it's not clear from the README how to use the `.eslintrc`. Also [the link to .eslintrc](https://github.com/airbnb/javascript/blob/master/linters/.eslintrc) doesn't point to anything useful (that file just reads `extends: 'airbnb'`).

By contrast, [eslint-config-google](https://github.com/google/eslint-config-google) is far clearer and [links to the actual file](https://github.com/google/eslint-config-google/blob/master/index.js).

**Comment by ljharb** [comment]
Specifically, it seems that eslint-config-google links to http://eslint.org/docs/user-guide/configuring#extending-configuration-files and http://eslint.org/docs/user-guide/configuring.

Those do seem useful, but I'm surprised someone not already familiar with eslint would be looking at the readme of an eslint config.

**Comment by dandv** [comment]
I meant that Google's README links to [the actual file](https://github.com/google/eslint-config-google/blob/master/index.js), in the last paragraph before the LICENSE heading.

This was useful when I noticed that ESLint didn't check for indentation and wondered what was going on. Turns out that Google's .eslintrc removed the `indent` rule a few months ago.

The main reason I wish these recommended styles linked to the ruleset is comparison shopping: I'm looking to adopt a popular style that's closest to mine. Having the two `.eslintrc` files side by side would make this comparison easy.

**Comment by ljharb** [comment]
ah - we don't have a single file though. Our config is built up from 5-7 files , using JS.

**Comment by ljharb** [comment]
Also, there's hundreds of rules - I'd think reading the guide would tell you about our style better than the rule config would.

**Comment by postmeback** [comment]
I think this can be closed down. @ljharb
