### ISSUE TITLE
react/jsx-no-bind: how to borrow some methods and pass them as props to child?

### ISSUE THREAD

**Issue by zheeeng** [airbnb/javascript#1446]
I'm making a text editor via ACE Editor, and now I re-crafted a search box as a child component.

In parent component, I stored the Ace Editor ref in `this.editorRef` and I can access the instance by 'this.editorRef.editor', the editor instance provides some methods like find, findNext, findPrev, replace, replaceAll and others.

I  want to pass some methods of the editor instance to child `<SearchBox />`, I wrote codes like

```
render () {
  const { editor } = this.editorRef
  const { find, findNext, findPrev, replace, replaceAll } = editor
  return (
    <SearchBox
      find={find.bind(editor)}
      findNext={findNext.bind(editor)}
      findPrev={findPrev.bind(editor)}
      replace={replace.bind(editor)}
      replaceAll={replaceAll.bind(editor)}
    />
  )
}
```

does the jsx-no-bind lint consider this situation? Or any suggestion to improve these codes?

**Comment by ljharb** [comment]
In general, passing around a stateful object like `editor` is very unidiomatic for React - so what you're trying to do (passing the methods) is better than passing `editor`.

What I'd probably recommend is - in the same ref callback that assigns `this.editorRef` - store all the bound functions on the instance. iow, `this.editor = { find: find.bind.editor(), findNext: findNext.bind(editor) }` etc - that way, you can pass `this.editor.find` around in the render path without having to rebind it.

**Comment by zheeeng** [comment]
@ljharb thx for you suggestion.
