### ISSUE TITLE
prefer-reflect is deprecated

### ISSUE THREAD

**Issue by fernandopasik** [airbnb/javascript#1451]
From eslint v3.9.0 this option is deprecated.

I see that in the base this option is off and with a TODO comment

```
// suggest using Reflect methods where applicable
// http://eslint.org/docs/rules/prefer-reflect
// TODO: enable?
'prefer-reflect': 'off',
```
Since current eslint dependency version is 3.19.0, I would suggest at least to replace the _**enable?**_ comment with a **_deprecated rule and to be removed in a later version_**?

**Comment by ljharb** [comment]
Removing the TODO makes sense; but there's no need to comment further, because every deprecated rule will remain in our config forever (off, generally) until eslint crashes due to it being specified.
