### ISSUE TITLE
[eslint-config-airbnb] Unexpected top-level property "ecmaFeatures".

### ISSUE THREAD

**Issue by elegos** [airbnb/javascript#1454]
Hi,

I've been trying to install version 15.0.1, but I'm encountering the following error:

    ESLint configuration is invalid:
    	- Unexpected top-level property "ecmaFeatures".
    
    Referenced from: airbnb
    Referenced from: /app/.eslintrc Error: /app/node_modules/eslint-config-airbnb/rules/react-a11y.js:
    	ESLint configuration is invalid:
    	- Unexpected top-level property "ecmaFeatures".

I saw that arount one month ago a fix was released in the master channel, but no new version has been made available on npm/yarn.

Is there a way to pull the git repo directly? I don't know how to specify the subdirectory of the javascript project.

Thanks

**Comment by ljharb** [comment]
We are not yet compatible with eslint v4; please use the install command in the package readme to ensure you have the proper peer deps. Also, `npm ls` will report errors for you - it has to exit zero before anything else will work properly.

See also, #1447.

**Comment by elegos** [comment]
Hi @ljharb thanks for the reply. I've manually run the info command and installed the correct eslint version, suggested by the deps (3.19.0). I'm using Atom with the eslint plugin, and I'm pretty sure it's using the local eslint, as I've not installed it locally (for double check, I've completely removed eslint and installed it again).

This is my package.json:

    {
      "name": "app",
      "version": "0.1.0",
      "private": true,
      "dependencies": {
        "babel-preset-stage-3": "^6.24.1",
        "material-ui": "^0.18.3",
        "react": "^15.6.0",
        "react-dom": "^15.6.0",
        "react-router": "^4.1.1",
        "react-router-dom": "^4.1.1",
        "react-tap-event-plugin": "^2.0.1"
      },
      "devDependencies": {
        "eslint": "^3.19.0",
        "eslint-config-airbnb": "git+ssh://git@github.com:airbnb/javascript.git",
        "eslint-config-airbnb-base": "^11.2.0",
        "eslint-plugin-import": "^2.2.0",
        "eslint-plugin-jsx-a11y": "^5.0.1",
        "eslint-plugin-react": "^7.0.1",
        "react-scripts": "1.0.7"
      },
      "scripts": {
        "start": "react-scripts start",
        "build": "react-scripts build",
        "test": "react-scripts test --env=jsdom",
        "eject": "react-scripts eject"
      }
    }

**Comment by ljharb** [comment]
I'm confused because eslint 3 doesn't validate configs; only eslint 4 does. So it shouldn't be possible to get that error unless you're on v4.

**Comment by elegos** [comment]
Hi @ljharb,

I'm confused, too. Here is the `yarn list|grep eslint` output:

    ├─ babel-eslint@7.2.3
    ├─ eslint-config-airbnb-base@11.2.0
    ├─ eslint-config-airbnb@2.0.0
    ├─ eslint-config-react-app@1.0.4
    ├─ eslint-import-resolver-node@0.2.3
    ├─ eslint-loader@1.7.1
    ├─ eslint-module-utils@2.0.0
    ├─ eslint-plugin-flowtype@2.33.0
    ├─ eslint-plugin-import@2.2.0
    │  ├─ eslint-import-resolver-node@^0.2.0
    │  ├─ eslint-module-utils@^2.0.0
    ├─ eslint-plugin-jsx-a11y@5.0.3
    ├─ eslint-plugin-react@7.0.1
    ├─ eslint@3.19.0
    │  ├─ babel-eslint@7.2.3
    │  ├─ eslint-config-react-app@^1.0.4
    │  ├─ eslint-loader@1.7.1
    │  ├─ eslint-plugin-flowtype@2.33.0
    │  ├─ eslint-plugin-import@2.2.0
    │  ├─ eslint-plugin-jsx-a11y@5.0.3
    │  ├─ eslint-plugin-react@7.0.1
    │  ├─ eslint@3.19.0

**Comment by paranoidjk** [comment]
+1 with this problem. Hope eslint-config-airbnb will upgrade to compatible with eslint v4 soon 😄

**Comment by ljharb** [comment]
@paranoidjk see #1447. There's nothing wrong with sticking with v3 in the meantime.

**Comment by elegos** [comment]
@ljharb it seems that the Atom's `linter-eslint` wasn't finding the eslint installation under node_modules, fallbacking to the eslint version shipped with the plugin. Today I've reconfigured the project and the editor and seems to work fine now :)

Thanks for the support :+1:

**Comment by artyomtrityak** [comment]
I have same issue with such config:

```json
    "babel-eslint": "^7.2.3",
    "eslint": "^4.0.0",
    "eslint-config-airbnb": "^15.0.1",
    "eslint-plugin-import": "^2.3.0",
    "eslint-plugin-jsx-a11y": "^5.0.3",
    "eslint-plugin-react": "^7.1.0"
```

`./node_modules/.bin/eslint .` throws same error

**Comment by ljharb** [comment]
@artyomtrityak yes, `npm ls` will show an error because eslint v4 is not yet compatible with eslint-config-airbnb.

**Comment by alp82** [comment]
I could get rid of the errors by editing two files:

1. `eslint-config-airbnb/rules/react` 
2. `eslint-config-airbnb/rules/react-a11y`

Be sure to **not** use `ecmaFeatures` as a top level configuration item:
```
module.exports = {
  // ecmaFeatures: {
  //   jsx: true,
  // },
  
  // other config items
}
```

Instead, nest it into `parserOptions`:
```
module.exports = {
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
  },

  // other config items
}
```

No idea, if that's the correct fix though, i just does not throw any errors anymore.

**Comment by ljharb** [comment]
@alp82 yes, that's invalid in eslint 4 but is ignored in eslint 3. It's already removed in master; we just haven't released a version compatible with eslint 4 - which is why anybody running into this is using invalid dependencies.

**Comment by alp82** [comment]
Thanks for the response. Any ETA on when you plan to release the eslint 4 compatible version?

**Comment by ljharb** [comment]
@alp82 follow #1447 for that - it's blocked by some peer deps, so it always takes a couple weeks. Luckily, there's no hurry, since eslint v3 continues to work fine.

**Comment by MFry** [comment]
I am having the same problem even after downgrading to eslint@3.19.0 with Visual Studio Code (and the eslint plugin) and after wasting half a day trying to fix this without success I think I might just need to wait for v4 update before using airbnb.

**Comment by ljharb** [comment]
@MFry are you sure VSC isn't using a global eslint v4? if so, you can surely configure it to use a locally installed eslint.

**Comment by MFry** [comment]
@ljharb I uninstalled every global except create-react-app.
I double checked `yarn global ls` and it confirmed it. I also tried the SO fix and it didn't work for either  v3 or V4.

**Comment by ljharb** [comment]
Presumably you've also restarted VSC after uninstalling those things… I'm not really sure :-/

It seems apparent that you have a copy of v4 somewhere and that's what VSC is running - you can certainly wait until #1447 is resolved, but then it'll just pop up again when v5, v6, etc comes out - so you may want to spend the time finding a proper fix now :-/

**Comment by ScottRFrost** [comment]
I was able to resolve this issue on my end by making a local .eslintrc.json file.  I used the command in VS Code once provided by the ESLint extension, but here's the text of the file if anyone needs it:
```
{
    "env": {
        "browser": true,
        "commonjs": true,
        "es6": true,
        "node": true
    },
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "sourceType": "module"
    },
    "rules": {
        "no-const-assign": "warn",
        "no-this-before-super": "warn",
        "no-undef": "warn",
        "no-unreachable": "warn",
        "no-unused-vars": "warn",
        "constructor-super": "warn",
        "valid-typeof": "warn"
    }
}
```

**Comment by ljharb** [comment]
@ScottRFrost you always need to have a local eslintrc file. in this case you're not extending the airbnb config tho?

**Comment by ScottRFrost** [comment]
Just mentioning that I had the same error and what I did to fix it in case others encountered the same.  Nothing about the error would lead you to believe it's related to a missing config file.  I'm not extending.

**Comment by ljharb** [comment]
@ScottRFrost right, what i'm saying is that if you're not extending airbnb or airbnb-base, then this repo is irrelevant to your issue.

**Comment by ljharb** [comment]
v16 is now released.
