### ISSUE TITLE
Chaining variable assignments Example

### ISSUE THREAD

**Issue by gandhirahul** [airbnb/javascript#1457]
There is an issue with the example mentioned in the following section

> 13.5 Don’t chain variable assignments.

**Accessing the value of `a` would throw an Uncaught ReferenceError: a is not defined.**

[https://github.com/airbnb/javascript#variables--no-chain-assignment](url)

````
// bad
(function example() {
  // JavaScript interprets this as
  // let a = ( b = ( c = 1 ) );
  // The let keyword only applies to variable a; variables b and c become
  // global variables.
  let a = b = c = 1;
}());

console.log(a); // undefined
console.log(b); // 1
console.log(c); // 1

``` `

**Comment by ljharb** [comment]
You'll notice that `a` is scoped to the function, so *outside* the function, it's indeed `undefined`.

**Comment by gandhirahul** [comment]
Accessing the variable outside the function would throw an **Uncaught ReferenceError**: a is not defined.

**Comment by ljharb** [comment]
That would only be true in strict mode. In sloppy mode, it will be `undefined`.

**Comment by gandhirahul** [comment]
Assuming that variable `a` is a non-existent variable outside the function and then trying to access it, would definitely throw an error even in sloppy mode.
Ref:
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Not_defined

**Comment by ljharb** [comment]
Fair point. I suppose we could add a `let a;` above the IIFE.

I think the purpose of the example is clear regardless, but that's certainly a good tweak.

**Comment by gandhirahul** [comment]
The example clearly fulfills its purpose but at the same time creates ambiguity regarding the scope of the variables.

Also, then we would be adding `let a; let b; let c;` for the next example.

So, `undefined` should be replaced with the **Uncaught ReferenceError**.

```
// good
(function example() {
  let a = 1;
  let b = a;
  let c = a;
}());

console.log(a); // undefined
console.log(b); // undefined
console.log(c); // undefined

**Comment by ljharb** [comment]
Juts `let a`, because the point is that `b` and `c` become *globals*.

The example isn't warning about the hazards of accessing a variable outside its scope - in other words, the bad part is that b and c's values *are* accessible outside the scope, because they're global.

**Comment by gandhirahul** [comment]
Well, there are two examples mentioned in that code snippet.

The first example behaves exactly like what you described above.
Here, accessing the value of `a` would throw an Uncaught ReferenceError.

```
// bad
(function example() {
  // JavaScript interprets this as
  // let a = ( b = ( c = 1 ) );
  // The let keyword only applies to variable a; variables b and c become
  // global variables.
  let a = b = c = 1;
}());

console.log(a); // undefined
console.log(b); // 1
console.log(c); // 1
```
The second example is having all of the three variables inside the function only.
So, accessing the value of any variable `a, b, c` would throw an Uncaught ReferenceError.
```
// good
(function example() {
  let a = 1;
  let b = a;
  let c = a;
}());

console.log(a); // undefined
console.log(b); // undefined
console.log(c); // undefined
```

So, writing `undefined` over there would make a developer think that the values are (somehow) still defined in the global scope, which is not the case.

**Comment by ljharb** [comment]
Gotcha.

If you're interested in making a PR, let's just change the `undefined` comment to "throws ReferenceError" in all 4 places :-) that seems easiest. Thoughts?

**Comment by gandhirahul** [comment]
Perfect

I just created a new PR with the above mentioned changes.
Also, it would be awesome if you could remove that `invalid` label.

Cheers!

**Comment by ljharb** [comment]
Looks like #1458
