### ISSUE TITLE
No compatible version found: eslint-plugin-react@^#.#.#

### ISSUE THREAD

**Issue by dsomel21** [airbnb/javascript#1459]
I am on Ubuntu 16.04, and it has been a mission trying to configure airbnb styling guide with eslint. 
Initially, I was trying to install eslint-config-airbnb, `npm i -S eslint-config-airbnb` but I kept getting a 

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2

```

I even looked at [this guys thing that had the same problem](https://github.com/airbnb/javascript/issues/465) but it didn't help. 

I have not used eslint before, so to be 100% honest, I don't know when or why to run `eslint app`

**Comment by ljharb** [comment]
That's just a warning, it's not an error - you can ignore it.

**Comment by dsomel21** [comment]
Thanks ljharb, I am still having slight issues, but I tihnk this issue can be closed :)

**Comment by ljharb** [comment]
Ah, if you're getting the error in the title, then you copypasted the wrong command from the readme :-)

**Comment by delhibabu86** [comment]
I am also seeing similar issue 


:\Development\source\75\ReactJS>npm install --save-dev eslint-config-airbnb eslint@^#.#.# eslint-plugin-jsx-a11y@^#.#.# eslint-plugin-import@^#.#.# eslint-plugin-react@^#.#.#
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "eslint-config-airbnb" "eslint@#.#.#" "eslint-plugin-jsx-a11y@#.#.#" "eslint-plug
in-import@#.#.#" "eslint-plugin-react@#.#.#"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: eslint-plugin-react@#.#.#
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.6.0, 1.6.1, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.2.0, 2.3.0, 2.4.0, 2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.7.0, 2.7.1,
 3.0.0, 3.1.0, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.3.0, 3.3.1, 3.3.2, 3.4.0, 3.4.1, 3.4.2, 3.5.0, 3.5.1, 3.6.0, 3.6.1, 3.6.2, 3.6.3, 3.7.0, 3.7.1, 3.8.0, 3.9.0, 3.10.0, 3.11.0, 3.11.1, 3.11.2, 3.11.3, 3.12.0, 3.13.0, 3.13.1, 3
.14.0, 3.15.0, 3.16.0, 3.16.1, 4.0.0-rc.0, 4.0.0-rc.1, 4.0.0, 4.1.0, 4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.3.0, 5.0.0, 5.0.1, 5.1.0, 5.1.1, 5.2.0, 5.2.1, 5.2.2, 6.0.0-alpha.1, 6.0.0-alpha.2, 6.0.0-rc.0, 6.0.0-rc.1, 6.0.0, 6.1.0,
 6.1.1, 6.1.2, 6.2.0, 6.2.1, 6.2.2, 6.3.0, 6.4.0, 6.4.1, 6.5.0, 6.6.0, 6.7.0, 6.7.1, 6.8.0, 6.9.0, 6.10.0, 6.10.1, 6.10.2, 6.10.3, 7.0.0-rc.0, 7.0.0-rc.1, 7.0.0, 7.0.1, 7.1.0, 7.2.0, 7.2.1, 7.3.0, 7.4.0-rc.0, 7.4.0-rc.1,
 7.4.0
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by ljharb** [comment]
@delhibabu86 it's for the same reason: you're not following the instructions. The command with "#" in it is an *example* - not meant to be run directly. For windows, there's a specific section in the npm package's readme.
