### ISSUE TITLE
Add installation instructions for yarn

### ISSUE THREAD

**Issue by dandv** [airbnb/javascript#1462]
`yarn info "eslint-config-airbnb@latest" peerDependencies` returns undefined.

I used `yarn add --dev eslint-config-airbnb-base eslint-plugin-import`.

**Comment by ljharb** [comment]
imo knowing that you need to run `yarn add --dev` is one of the costs of adopting "not npm". I'm not sure I see the benefit of putting it in the readme.

**Comment by dandv** [comment]
I've installed hundreds of npm modules so far, and none of them had instructions of `eslint-config-airbnb`'s sort:

![image](https://user-images.githubusercontent.com/33569/27443812-23b512ec-5729-11e7-8811-4028e1e51572.png)

yarn users refer to (or have memorized) "yarn to npm cheatsheets" and know how to run `yard add --dev`, but the equivalent process for the commands in the screenshot isn't as straightforward.

**Comment by ljharb** [comment]
That's true - installing peer deps can be tricky, and we have a lot of them due to the way eslint works.

I guess it'd be fine to add a sentence about yarn after all the npm instructions.

Separately, a more instructive sentence at the top of `eslint-config-airbnb`'s readme that points to `eslint-config-airbnb-base`, and vice versa, would be a useful PR.

**Comment by dandv** [comment]
I've submitted two quick PRs, [1](https://github.com/airbnb/javascript/pull/1463), [2](https://github.com/airbnb/javascript/pull/1464).

I've added the yarn instructions before npm because they're a single line, and would be lost after the pagefull of npm instructions. Hope that's okay.

**Comment by dandv** [comment]
I understand that, but I fear that seeing the long npm instructions with the special syntax, yarn users will just go the npm route (or try `yarn info` like me), since the yarn line is below the fold.

While a quick `yarn` line with the npm instructions readily visible one line below would meet the expectations of both types of devs.

**Comment by ljharb** [comment]
Thanks, I think this is a good addition.
