### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by dcorb** [airbnb/javascript#1468]
In http://airbnb.io/javascript/ 
The links to the guides http://airbnb.io/javascript/react/ and http://airbnb.io/javascript/css-in-javascript/ are broken

**Comment by ljharb** [comment]
Thanks; that's unavoidable with github's automatic page generation mechanism, since it doesn't generate subdirectories.

I'd recommend consuming the content via github.

**Comment by BeauBouchard** [comment]
recently the `href-no-hash` rule from `eslint-plugin-jsx-a11y` was also removed, 
links to [href-no-hash.md](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/href-no-hash.md) seem to have been removed in https://github.com/evcohen/eslint-plugin-jsx-a11y/commit/a14617528cda23c6c88902ace1d083e4e13ac271

**Comment by ljharb** [comment]
@BeauBouchard that's a separate issue; however, once we ship eslint v4 support, we'll have to remove that link anyways, so there's not really a need to update it.

**Comment by mnjit20** [comment]
seems this should be closed, as its working fine.

**Comment by mnjit20** [comment]
closed fixed
