### ISSUE TITLE
WARN: eslint-config-airbnb@15.0.1 requires a peer of eslint@^3.19.0 but none was installed.

### ISSUE THREAD

**Issue by vedtam** [airbnb/javascript#1478]
Hi,

With all dependencies updated, I get the following warning:

`npm WARN eslint-config-airbnb@15.0.1 requires a peer of eslint@^3.19.0 but none was installed.`

package json: 

```
{
  "name": "grapql-server",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "start": "nodemon ./server.js --exec babel-node"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "body-parser": "^1.15.2",
    "cors": "^2.8.0",
    "express": "4.15.3",
    "graphql": "^0.10.0",
    "graphql-tools": "^1.1.0",
    "express-graphql": "^0.6.1",
    "lodash": "^4.15.0",
    "multer": "^1.2.1",
    "mysql": "^2.12.0",
    "nodemailer": "^4.0.1",
    "request": "^2.81.0",
    "sequelize": "^4.2.1",
    "socket.io": "^2.0.3"
  },
  "devDependencies": {
    "babel-cli": "6.24.1",
    "babel-core": "^6.17.0",
    "babel-eslint": "^7.0.0",
    "babel-plugin-inline-import": "^2.0.1",
    "babel-polyfill": "6.23.0",
    "babel-preset-es2015": "6.24.1",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-0": "6.24.1",
    "eslint": "^4.1.1",
    "eslint-config-airbnb": "^15.0.1",
    "eslint-plugin-import": "^2.0.1",
    "eslint-plugin-react": "^7.1.0",
    "nodemon": "^1.9.1"
  },
  "eslintConfig": {
    "parser": "babel-eslint",
    "extends": [
      "airbnb/base",
      "plugin:import/errors"
    ],
    "rules": {
      "no-use-before-define": 0,
      "arrow-body-style": 0,
      "dot-notation": 0,
      "no-console": 0
    },
    "env": {
      "mocha": true
    }
  }
}
```

Could please someone tell me why, or how to fix it?
Thanks!

**Comment by ljharb** [comment]
That's because the airbnb config isn't yet compatible with eslint v4. Use the install command in the readme to ensure you have the proper peer deps installed - `npm ls` will exit successfully when everything's correct.

**Comment by luftywiranda13** [comment]
@ljharb we've seen many users misunderstood updated other dependencies like this. 
Don't you think we need to update the docs? I mean like telling the users to stick to the exact version we specified in the installation section?

**Comment by ljharb** [comment]
@luftywiranda13 the docs are already quite clear; see the [instructions](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base#eslint-config-airbnb-base-1). peerDependencies aren't intuitive or easy to understand, unfortunately, but the problem seems to be that users don't read the docs at all; not that the docs aren't clear enough.

**Comment by joshsylvester** [comment]
I'm sorry to bring up a closed issue, but has the airbnb config been updated to support eslint v4 yet? I also noticed a strange mismatch between `eslint-config-airbnb-base` and `eslint-config-airbnb`... since one seems to require the other, should they match dependencies?
```
$ npm info "eslint-config-airbnb-base@latest" peerDependencies
{ eslint: '^4.6.0', 'eslint-plugin-import': '^2.7.0' }
```

```
$ npm info "eslint-config-airbnb@latest" peerDependencies
{ eslint: '^3.19.0 || ^4.3.0',
  'eslint-plugin-jsx-a11y': '^5.1.1',
  'eslint-plugin-import': '^2.7.0',
  'eslint-plugin-react': '^7.1.0' }
```

```
npm WARN eslint-config-airbnb@15.0.1 requires a peer of eslint@^3.19.0 but none was installed.
```

**Comment by ljharb** [comment]
@joshsylvester that was added in v15.1 - https://npmcdn.com/eslint-config-airbnb@15.1.0/package.json - it supports both eslint v3 and v4. When v16 is released, it will require v4.

You shouldn't ever need to directly depend on `eslint-config-airbnb-base` when using `eslint-config-airbnb` - but yes, currently the latest version of the base config is not yet compatible with the main config, and for the same reason, the peer dep versions will be different (when using "latest").

**Comment by ljharb** [comment]
v16 is now released.
