### ISSUE TITLE
for of loop warning

### ISSUE THREAD

**Issue by James2516** [airbnb/javascript#1479]
![](http://i.imgur.com/CrIvOlI.png)

Why does this throw an error? data.json is an array of objects. 
How else should i iterate through it?

**Comment by ljharb** [comment]
`data.forEach(…)`, `data.map(…)`, etc.

https://gist.github.com/ljharb/58faf1cfcb4e6808f74aae4ef7944cff might be helpful, as might [section 11.1](https://github.com/airbnb/javascript#iterators--nope) in the guide.
