### ISSUE TITLE
JSX Expression Formatting (spaces after opening and before closing braces)

### ISSUE THREAD

**Issue by ecbrodie** [airbnb/javascript#1493]
What is Airbnb's interpretation for the formatting rules for spaces after opening and before closing braces? To illustrate:

```javascript
// Option 1: No spaces
<div>{foo(1, "abc")}</div>

// Option 2: Yes spaces
<div>{ foo(1, "abc") }</div>
```

Thank you.

**Comment by ljharb** [comment]
Option 1. JS curlies should have padding spaces; jsx curlies never should.

**Comment by ecbrodie** [comment]
Thank you for the fast reply @ljharb

**Comment by ecbrodie** [comment]
Sorry, one more question @ljharb . Do you think this should be explicitly mentioned in this project's style guide? If so, I can make the PR.

**Comment by ljharb** [comment]
Yes, it should, and that'd be great!
