### ISSUE TITLE
Bug happened when both "eol-last" and "semi" exist.

### ISSUE THREAD

**Issue by ifibercc** [airbnb/javascript#1495]
why this can pass the rule?
```
ReactDOM.render(<App />, document.getElementById('root'))
;
```
even this:
```
ReactDOM.render(<App />, document.getElementById('root'))


;
```
but eslint give me a "no-multiple-empty-lines" error when I use 3 blank line
```
ReactDOM.render(<App />, document.getElementById('root'))



;
```
so it cause a bug when I use ESLint auto fix func:
```
ReactDOM.render(<App />, document.getElementById('root'))

```
after fix the code above but reserve a "eol-last" rule not fixed
```
ReactDOM.render(<App />, document.getElementById('root'))
;
```

**Comment by ljharb** [comment]
`eol-last` means there has to be a newline at the end of the file.

It's a really good point that your first example passes `semi` - could you file an issue on eslint itself about that? I'd be happy to help advocate for making the rule more restrictive.

**Comment by not-an-aardvark** [comment]
You should use the [`semi-style`](http://eslint.org/docs/rules/semi-style) rule if you want to enforce against the first example.
