### ISSUE TITLE
Confusing example for multiline comment

### ISSUE THREAD

**Issue by pratyushtewari** [airbnb/javascript#1497]
Hi,
The example of [18.1 Use /** ... */ for multi-line comments](https://github.com/airbnb/javascript#comments--multiline) is confusing my team as they though they should **not use @param** or other JSDoc features.

Does it make more sense to be more consistent in good and bad like in the below example:

```javascript
// bad
// make() returns a new element
// based on the passed in tag name
//
// @param {String} tag
// @return {Element} element
function make(tag) {

  // ...

  return element;
}

// good
/**
 * make() returns a new element
 * based on the passed-in tag name
 *
 * @param {String} tag
 * @return {Element} element
 */
function make(tag) {

  // ...

  return element;
}
```

**Comment by ljharb** [comment]
While that's not the purpose of this specific item, yes, you should not use JSDoc-style comments.

**Comment by pratyushtewari** [comment]
See if this pull request makes sense.

https://github.com/airbnb/javascript/pull/1498
