### ISSUE TITLE
Yarn instructions for eslint-config-airbnb potentially installs incorrect version of peer dependencies

### ISSUE THREAD

**Issue by epan** [airbnb/javascript#1508]
# Context
The Yarn instructions at [eslint-config-airbnb](https://www.npmjs.com/package/eslint-config-airbnb) readme currently installs the latest version of each peer dependency.

# Expected
Following the yarn instructions would install the correct peer dependencies.

# Actual
I encountered the error `Definition for rule 'jsx-a11y/href-no-hash' was not found` when running `yarn run eslint .` after following the Yarn instructions.

The Yarn instructions install the latest version of `eslint-plugin-jsx-a11y` which installs `eslint-plugin-jsx-a11y@6.0.2` but the peer dependency is `eslint-plugin-jsx-a11y@^5.1.1`

`eslint-config-airbnb` depends on a rule that no longer exists in `plugin-jsx-a11y@6.0.2`

# Workaround
1. Install package with `yarn add -D eslint-config-airbnb`
1. Run `npm info "eslint-config-airbnb@latest" peerDependencies` to get list of peer dependencies and their respective versions
1. `yarn add -D [dependency@version]` eg, `yarn add -D eslint-plugin-jsx-a11y@^5.1.1`
1. Repeat for each peer dependency listed in step 2

**Comment by ljharb** [comment]
Airbnb doesn't use yarn. If you'd like to make a PR that improves the yarn instructions, that'd be great - if not, and they're incorrect, a PR to remove them would be fine too.

**Comment by epan** [comment]
@ljharb I did my best - https://github.com/airbnb/javascript/pull/1511 Happy to revise as much as needed. Thanks for all this awesomeness around here.
