### ISSUE TITLE
Using stage-2 syntax will be fatal

### ISSUE THREAD

**Issue by songzhengxu** [airbnb/javascript#1513]
Use Arrow Function in Class Property  for Handling `this`
`handleChange = () => {
 code..
};`
i  enable  enable stage-2 in Babel. but ESLint will be fatal error
`Parsing error: Unexpected token = (Fatal)`

What should I do ?

**Comment by ljharb** [comment]
This styleguide explicitly forbids using pre-stage-3 features. Class fields only recently attained stage 3, and certainly until eslint adds support for it, we won't be permitting it.

In other words, what you should do is "not use class fields yet".
