### ISSUE TITLE
Clarification regarding react/prop-types validation and react router dom

### ISSUE THREAD

**Issue by rsancheza09** [airbnb/javascript#1519]
I am getting the alert, that I have to validate in prop types match, but I think it is not necessary.

import React from 'react';

```javascript
const Header = (props) => {
  const { match } = props; // 'match' is missing props validation (react/prop-types)
  return (
    <div>
      <h1>Hello</h1>
      <h3>ID: {match.params.id}</h3>
    </div>
  );
};

export default Header;
```

Do I need to validate it? What's the new convention?

Regards

**Comment by ljharb** [comment]
It's definitely necessary; every prop should have a propType (also, every SFC should be a non-arrow function, per this guide).

In your case, it looks like:
```jsx
match: PropTypes.shape({
  params: PropTypes.shape({
    id: PropTypes.node,
  }).isRequired,
}).isRequired
```
would be the minimal propType - you could restrict it further to `PropTypes.string`, perhaps?

**Comment by rsancheza09** [comment]
Thanks @ljharb but compiling the project and using this piece of code
```javascript
import React from 'react';
import PropTypes from 'prop-types';

const Header = (props) => {
  const { match } = props;
  return (
    <div>
      <h1>Hello</h1>
      <h3>ID: {match.params.id}</h3>
    </div>
  );
};

Header.propTypes = {
  match: PropTypes.shape({
    params: PropTypes.shape({
      id: PropTypes.string,
    }),
  }),
};

export default Header;
```

I am getting now this error, that's the reason that I think that **'match'** maybe should not be necessary.

> propType "match" is not required, but has no corresponding defaultProp declaration.  react/require-default-props

**Comment by ljharb** [comment]
My original code has isRequireds, use them and you wont have that error.

**Comment by rsancheza09** [comment]
Cool thanks.
