### ISSUE TITLE
Confusing dot-notation and no-underscore-dangle

### ISSUE THREAD

**Issue by pewstiepoll** [airbnb/javascript#1520]
Hi!
I have an object returned to me from third-party API. Object has following structure:
`object = {
    _links: ...
}`

When I'm trying to access `_links` object using dot-notation like this: `object._links` I've got `no-underscore-dangle` error while trying to get object property with brakets `object['_links']` leads to `dot-notation` error. How to deal with such rules confusion?

**Comment by ljharb** [comment]
If you don't control the object structure, you'll have to use an override comment for `no-underscore-dangle`.

**Comment by pewstiepoll** [comment]
@ljharb so `no-underscore-dangle` has higher priority to be overwritten, right?
Many thanks!

**Comment by ljharb** [comment]
It's not about "priority", it's that it has a leading underscore, so that's the rule that's complaining about it.

**Comment by pewstiepoll** [comment]
#
