### ISSUE TITLE
Enforce the use of modules

### ISSUE THREAD

**Issue by guillaumervls** [airbnb/javascript#1527]
Hi,

The guide says to use `import` instead of `require` :
https://github.com/airbnb/javascript#modules--use-them

However it's not enforced :
https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/imports.js#L98-L100

Am I missing something ?

Cheers

**Comment by ljharb** [comment]
It's impossible for a JS linter to exhaustively cover a style guide, so it's totally fine for the guide to mandate something that our linter config does not enforce.

In this specific case, `require` is still needed for conditional static dependencies, so there's still an occasional use case for it; and the rule docs say "It is also fairly noisy if you have a larger codebase that is being transitioned from CommonJS to ES6 modules." which applies to most large codebases.
