### ISSUE TITLE
Reasoning behind not allowing named function callbacks?

### ISSUE THREAD

**Issue by TiddoLangerak** [airbnb/javascript#1541]
The eslint config has the rule `prefer-arrow-callback` turned on, with `allowedNamedFunctions : false`. This surprises me: the styleguide earlier mentions that it's good to name functions for locating them in call stacks ([7.1](https://github.com/airbnb/javascript#functions--declarations)). Disallowing named callbacks seems to be inconsistent with that, and can especially hurt debuggability of higher-order functions (`debounce`, `memoize`, etc.). Is this done intentionally? And if so, why?

**Comment by ljharb** [comment]
It's set to the default value; there's no intention behind it.

It seems reasonable to set it to `true`; however, typically you don't need to locate callbacks in call stacks, since the function containing them tends to be named.
