### ISSUE TITLE
[Vuex compatibility] no-param-reassign - add `state` to the ignorePropertyModificationsFor array.

### ISSUE THREAD

**Issue by wujekbogdan** [airbnb/javascript#1542]
in [Vuex](https://github.com/vuejs/vuex) (a state manager for Vue.js) [state mutations are required](https://vuex.vuejs.org/en/mutations.html), so the airbnb config is not compatible with Vuex. In order to fix this incompatibility issue the `state` property must be added to the  `ignorePropertyModificationsFor` array.

``` js
"no-param-reassign": [
  "error",
  {
    "props": true,
    "ignorePropertyModificationsFor": [
      "state", // For Vuex mutations
      "acc", // for reduce accumulators
      "e", // for e.returnvalue
      "ctx", // for Koa routing
      "req", // for Express requests
      "request", // for Express requests
      "res", // for Express responses
      "response", // for Express responses
      "$scope", // for Angular 1 scopes
    ]
  }
],
```

**Comment by ljharb** [comment]
That would be a horrifically bad practice in React (mutating `this.state`), and Airbnb uses React (and doesn't use Vue) - I don't think this is something we can add.

**Comment by wujekbogdan** [comment]
I see.

Btw, IMO the Airbnb style guide (and the Eslint config) should be framework-agnostic. So all these frameworks-specific properties (`request`, `$scope`, `ctx`, etc) shouldn't be included in the base Airbnb Eslint config.

It would be great if there were separate npm modules that add frameworks compatibility (like `eslint-config-airbnb-react` `eslint-config-airbnb-angular`, etc).

**Comment by ljharb** [comment]
There's `eslint-config-airbnb-base`, which is framework-agnostic, and `eslint-config-airbnb` which is for React.

Since this is Airbnb's config, we need to prioritize Airbnb's choice of framework. The base config has lots of things we don't use, but that don't conflict with our usage - this change would.
