### ISSUE TITLE
Definition for rule 'jsx-a11y/href-no-hash' was not found  jsx-a11y/href-no-hash

### ISSUE THREAD

**Issue by joyran** [airbnb/javascript#1545]
eslint-plugin-jsx-a11y has already removed the rule jsx-a11y/href-no-hash [commit](https://github.com/evcohen/eslint-plugin-jsx-a11y/commit/a14617528cda23c6c88902ace1d083e4e13ac271), shall eslint-config-airbnb remove this rule?

https://github.com/airbnb/javascript/blob/fc7fae620f625701a5614fb9cf9ec1e9c49bcc70/packages/eslint-config-airbnb/rules/react-a11y.js#L37

**Comment by ljharb** [comment]
When it upgrades to v6, yes. If you run `npm ls` you'll see your dependencies are invalid.

Please run the install command in `eslint-config-airbnb`'s readme to ensure you have the proper peer dependency versions installed.

Follow #1482 for the upgrade to v6.

**Comment by ljharb** [comment]
v16 is now released.
