### ISSUE TITLE
How set Airbnb Javascript code styling in my Intellij IDEA project

### ISSUE THREAD

**Issue by vagg777** [airbnb/javascript#1553]
Does anybody know how to setup the Airbnb Javascript code styling in a Intellij IDEA project? I keep finding guides only for Webstorm.

I tried **Settings -> Languages and Frameworks -> Javascript**, but the Javascript language list does not contain Airbnb style.

https://i.stack.imgur.com/xYsqp.png

Then I tried to go to **Setting -> Editor -> Code Style -> Javascript**, but again I see no option for Airbnb styling.

https://i.stack.imgur.com/TDNQf.png

I literally have no idea how I am supposed to add it to my project.

**Comment by ljharb** [comment]
Configure it for eslint, and use eslint-configure-airbnb or eslint-config-airbnb-base?

**Comment by mariogillazaro** [comment]
Hey @vagg777 the truth is that nobody has made an Intellij code style XML with Airbnb styles, at least not that I know. If you happen to find that config file do two things: 1. Share it with me; 2. Go to *Settings -> Editor -> Code Style -> Javascript*, there you will see a dropdown with the word **scheme** on the left. Next to it there are three dots with a menu that lets you import said code style XML. After importing it you will be able to press **Option + Command + L** and Webstorm automatically will enforce Airbnb rules.

**Comment by lokori** [comment]
Would be nice, but apparently no one has done it so far. Eventually someone will do it :)

**Comment by matejthetree** [comment]
following

**Comment by ljharb** [comment]
@matejthetree you can do that by clicking "subscribe" on the right; you don't need to ping everyone involved in the thread with a comment.

**Comment by lykhatskyi** [comment]
[https://gist.github.com/mentos1386/aa18c110dc272514d592ec27e98128be](url)

**Comment by weihongyu12** [comment]
I think we can go to WebStorm official vote, let WebStorm officially support this feature.

[https://youtrack.jetbrains.com/issue/WEB-27521](https://youtrack.jetbrains.com/issue/WEB-27521)

**Comment by amtdevops** [comment]
does this helps?
https://www.themarketingtechnologist.co/eslint-with-airbnb-javascript-style-guide-in-webstorm/

**Comment by mchambaud** [comment]
In Intellij, open `.eslintrc` and right click -> `Apply ESLint Code Style Rules`

![image](https://user-images.githubusercontent.com/360109/81200548-1a739100-8f92-11ea-895f-e2e419547b8f.png)

**Comment by henryobiaraije** [comment]
> In Intellij, open `.eslintrc` and right click -> `Apply ESLint Code Style Rules`
> 
> ![image](https://user-images.githubusercontent.com/360109/81200548-1a739100-8f92-11ea-895f-e2e419547b8f.png)

This is actually a better approach. 
You get to apply your already existing eslint rules as a coding style.
