### ISSUE TITLE
npm README.md old, not updated (eslint-config-airbnb)

### ISSUE THREAD

**Issue by sparcut** [airbnb/javascript#1560]
Haven't dealt with publishing npm packages, so not sure if you have control over this.

Nevertheless, the README.md is different on the npm page for `eslint-config-airbnb` than what is in the git repo.

Pretty sure the change was made in #1508 re: #1511, but the `eslint-config-airbnb-base` looks to be updated.

![github and npm readme.md](https://user-images.githubusercontent.com/16233822/30580258-3bff2816-9d5f-11e7-9588-c74f60b01060.png)

**Comment by ljharb** [comment]
This isn't a bug; it's a normal thing that happens all the time. It means that what's on github hasn't yet been published to npm.

When I'm ready to publish `eslint-config-airbnb`, I'll do so; but until then, it's fine that they're different.

**Comment by sparcut** [comment]
Alright, it's just that it took me a bit to figure out the problem described in #1508, since yarn instructions were incorrect on npm page.

Cheers the prompt response.
