### ISSUE TITLE
How to avoid eval & not using classes in my specific case

### ISSUE THREAD

**Issue by htinc** [airbnb/javascript#1561]
Hello,

I'm writing a modular fully JavaScript-based operating system (Its more of a website than a real OS). 
When I started writing this project (On my mobile phone), there was no ES6 (Or I didn't know of it). 

The first example uses Eval. How can I avoid that? [This is my development suite for my OS](https://dotcdn.us/webos-prod/). In the [file](https://dotcdn.us/webos-prod/js/engine.js]) I have a eval, because I load the desired application with a request. The [file](https://dotcdn.us/webos-prod/apps/com.test.weather.hs) isn't a pure json, because it contains functions, which you cant do in json. So I cant use a JSON.parse. How can i avoid using eval in this case?

My second problem is security. I made a port of my webOS and created a "module" based clone, with only a command line [here](https://dotcdn.us/webos-core/). In all my modules, eg the [kernel module](https://dotcdn.us/webos-core/js/kernel.js), I use a special notation for classes/modules:

```js
const testModule = (function () {
  var modulePrivate = {
    // Things that have to be available to all classes of this module but not to anything else
  }
  var modulePublic = {
    TestClass: function () { // A class without any restrictions/access management
      var private = {
        // Things needed by this instance
      };

      var public = {
        // Publicly available functions/properties
      };
      return public;
    },
    AccessManagedClass: function (keys) { // A class without any restrictions/access management
      var private = {
        // Things needed by this instance
      };

      var public = {
        killProcess: function (name) {
           if (access.validate("taskManagement", keys) {
             // Validated keys
           }
        };
        // Publicly available functions/properties
      }
      return public;
    }
  }

  access.register("taskManagement");

  return modulePublic;
})();
```
```js
var test = testModule.TestClass();
var key = access.taskManagement();
var authorizedManager = testModule.AccessManagedClass(key);
authorizedManager.killProcess("think"); // whatever
```

How can I isolate this with classes. Security is very important in my case. Private things should stay private. 

Hoping for a better alternative & thank you a lot for reading all this shit ;D
The code format is messed up dunno why, maybe only in the preview
Levi

**Comment by ljharb** [comment]
JS currently does not have privacy except via closure.

I don't see any use of `eval` in your examples.

However, there is *no* safe way to evaluate user-provided JS code unless you've built your own sandbox in which to execute it.

We can keep discussing here, but since this issue isn't relevant to Airbnb's JavaScript style guide, I'm going to close this issue.
