### ISSUE TITLE
indent rule ignoredNodes needs to include 'JSXElement'

### ISSUE THREAD

**Issue by damonmaria** [airbnb/javascript#1569]
Currently the following is impossible to not cause as ESlint error with AirBnB rules:
```jsx
const Form = ({ logo, styles }) => (
  <form
    onSubmit={(e) => {
      ...
    }}
  >
    <img alt="Logo" src={logo} style={styles.logo} />
  </form>
)
```

If the single `>` by itself (closing the opening `<form`) is indented 2, then the `indent` rule complains that it wants 4 spaces instead of 2. If I use 4 spaces then `react/jsx-closing-bracket-location` complains that it doesn't align with the opening tag.

The AirBnB rules try to handle this with the following on the `indent` rule: `ignoredNodes: ['JSXElement *']`. But I think this means it misses top level elements. When I change the option to: `ignoredNodes: ['JSXElement *', 'JSXElement']` then the above code sample is OK.

Versions:
eslint-config-airbnb@^15.1.0
eslint@^4.7.2

**Comment by ljharb** [comment]
Thanks, great catch. Want to make a PR?

**Comment by damonmaria** [comment]
Actually. I realised I had kinda messed up and had `eslint-config-airbnb-base@^12.0.0` as well, where as eslint-config-airbnb stipulates `eslint-config-airbnb-base@^11.3.0`. So this is actually not a current issue, but will crop up as soon as eslint-config-airbnb moves to the next version of eslint-config-airbnb-base.

Sorry, I wouldn't be able to spare the time right now for a PR.
