### ISSUE TITLE
Array - When you need to copy an array use Array#slice

### ISSUE THREAD

**Issue by gsklee** [airbnb/javascript#157]
You might wanna remove or rectify this entry. I ran the test with Chrome 34.0.1847.116 and it showed that the while loop method was the fastest; actually according to jsPerf, the while loop method has been the fastest since Chrome 25.0.1354.

**Comment by ljharb** [comment]
Performance should be the last consideration applied to code, and typically a style guide is often violated when making performance optimizations.

The cleanest and clearest way to copy an Array is via `slice`, so that's the proper thing for a style guide to recommend.

**Comment by abdulhannanali** [comment]
`slice` also happens to be fastest for me too. ljharb is right on this. Preoptimizations can hurt the code quality.
