### ISSUE TITLE
install warns requires a peer of eslint ...

### ISSUE THREAD

**Issue by webmobiles** [airbnb/javascript#1571]
is relevant this warning ?
```

npm WARN eslint-config-airbnb@15.1.0 requires a peer of eslint-plugin-jsx-a11y@^5.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@15.1.0 requires a peer of eslint-plugin-import@^2.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@15.1.0 requires a peer of eslint-plugin-react@^7.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@11.3.2 requires a peer of eslint-plugin-import@^2.7.0 but none is installed. You must install peer dependencies yourself.

```

must I install by hand or just do nothing?

**Comment by ljharb** [comment]
Very relevant. It means you didn't install using the installation command in the readme for the package; that would ensure you have the proper peer dep versions.

In general, though, yes - peer deps must be installed manually.

**Comment by webmobiles** [comment]
yes, i've install with yarn add eslint

then eslint --init

i've tought that choosing airbnb style would install automatically, thanks

**Comment by ljharb** [comment]
Unfortunately that's both a flaw in yarn, and a separate flaw in `eslint --init`.

**Comment by webmobiles** [comment]
sorry i did not find the readme on https://github.com/airbnb/javascript, just

`Note: this guide assumes you are using Babel, and requires that you use babel-preset-airbnb or the equivalent. It also assumes you are installing shims/polyfills in your app, with airbnb-browser-shims or the equivalent.
`

it's not clear for me

**Comment by ljharb** [comment]
Not the readme of the guide; the readme of the *package*. See https://npmjs.com/eslint-config-airbnb

**Comment by webmobiles** [comment]
thanks i've got it , just is not clear on the link , what is for : eslint-config-airbnb/base 
eslint-config-airbnb/legacy

**Comment by webmobiles** [comment]
i dont' know why , with yarn check i've got this: (but eslint is working on my webstorm)

```
warning "eslint-config-airbnb#eslint-plugin-react@^7.1.0" could be deduped from "7.4.0" to "eslint-plugin-react@7.4.0"
error "eslint-config-airbnb-base#eslint@^4.7.2" doesn't satisfy found match of "eslint@3.19.0"
warning "react-scripts#eslint-config-react-app#eslint-plugin-react@^7.1.0" could be deduped from "7.4.0" to "eslint-plugin-react@7.4.0"
warning "react-scripts#eslint-plugin-jsx-a11y#eslint@^2.10.2 || ^3 || ^4" could be deduped from "4.4.1" to "react-scripts#eslint@4.4.1"
warning "react-scripts#eslint-plugin-react#eslint@^3.0.0 || ^4.0.0" could be deduped from "4.4.1" to "react-scripts#eslint@4.4.1"
warning "react-scripts#fsevents#node-pre-gyp@^0.6.36" could be deduped from "0.6.38" to "node-pre-gyp@0.6.38"

```

**Comment by ljharb** [comment]
You need eslint 4, not eslint 3.

**Comment by webmobiles** [comment]
i've delete yarn.lock, node-modules folder, reinstall accord the guide and it's working, thanks for your help !
