### ISSUE TITLE
Update "Adjacent JSX elements must be wrapped in an enclosing tag" for React 16

### ISSUE THREAD

**Issue by KamuelaFranco** [airbnb/javascript#1575]
React 16 does not require container elements. Is this going to be updated?

**Comment by ljharb** [comment]
Airbnb still uses React 15; however I'm not sure you're correct.

React 16 allows you to return an array of elements, but jsx syntax itself requires the enclosing tag.

Can you provide an example?

**Comment by monsonjeremy** [comment]
@ljharb 
From the React 16 Docs:

```
render() {
  // No need to wrap list items in an extra element!
  return [
    // Don't forget the keys :)
    <li key="A">First item</li>,
    <li key="B">Second item</li>,
    <li key="C">Third item</li>,
  ];
}
```

**Comment by ljharb** [comment]
@monsonjeremy that's an array of elements; note the brackets.

If you removed those, you'd get a syntax error, since they'd need to be wrapped in an enclosing tag.

**Comment by KamuelaFranco** [comment]
I'm agreeing with @ljharb here and thinking there's nothing that's actually amiss with the current implementation. Feel free to close.

**Comment by natakina** [comment]
I forgot a comma and also get this error.

**Comment by ljharb** [comment]
You can either use a trailing comma, or wrap the jsx in parens (extra parens, perhaps, if it’s already in a function call).
