### ISSUE TITLE
Array destructuring is not the best. Might remove it from the rules

### ISSUE THREAD

**Issue by mt-micky** [airbnb/javascript#1577]
As seen on the following issue we can't always expect an array to be destructured.
https://github.com/eslint/eslint/issues/9386

```js
    'prefer-destructuring': ['error', {
      AssignmentExpression: {
        array: false
      },
    }, {
      enforceForRenamedProperties: false,
    }],
```

**Comment by ljharb** [comment]
While I agree that the example in the linked issue is absurd; I'd say that indexing directly into an array is a massive code smell. If that could be linted against, it'd absolutely be forbidden.

What's your use case where you have a list of values and you need the 13th one, of all things?

**Comment by mt-micky** [comment]
The code example is absolutely bonkers, I admit. But I still find it really strict.
In my code I in fact only need the second element of a list. While I could rewrite the code a different way I find it also absurd be forced to destructure the array to get `values[1]` out.

**Comment by ljharb** [comment]
I'd say that's appropriate. If it's being used as a tuple - as a struct - then destructuring is correct. If it's being used as a list, then it should only be operated on as a list, all at once - never by grabbing an arbitrary index.

I'd say you should use an override comment for the "bonkers" code that it's causing an issue on; but any form of indexing into an array remains a code smell, and it's fine that a bad coding practice conflicts with a linting rule.

**Comment by mt-micky** [comment]
On the side note, I opened this issue as a notification.
You do what you think is correct for you.
