### ISSUE TITLE
Prefer destructuring invalid rule

### ISSUE THREAD

**Issue by jaesung2061** [airbnb/javascript#1580]
I'm getting an issue which I believe was caused by this commit? https://github.com/airbnb/javascript/commit/5aa203eaa88fb7febfb1ccf8736e896ca0959049#diff-5838a00e5ed5932b1af705c34ada1300L114

I get the following error:

	Module build failed: Error: /Users/jeff/projects/plot-factory-app/resources/assets/vue/node_modules/eslint-config-airbnb-base/rules/style.js:
		Configuration for rule "indent" is invalid:
		Value "data["1"].ImportDeclaration" has additional properties.
		Value "data["1"].flatTernaryExpressions" has additional properties.
		Value "data["1"].ignoredNodes" has additional properties.

**Comment by jaesung2061** [comment]
Weirdly, as soon as I submit an issue, I think to upgrade my packages. I was using an outdated version.

**Comment by bithavoc** [comment]
I was seeing this with `eslint: 3.x` since it's what I found in the readme at https://github.com/babel/babel-eslint, switch to 4.x and it works now.
