### ISSUE TITLE
function-paren-newline error vs. max-len error

### ISSUE THREAD

**Issue by blord-fullscreen** [airbnb/javascript#1584]
The snippet:

```
export default connect(mapStateToProps, mapDispatchToProps)(
  generateDndContextWithBackend(SiteEditorContainer));
```

gives me the error `Unexpected newline after "("`

But when I remove the newline:

```
export default connect(mapStateToProps, mapDispatchToProps)(generateDndContextWithBackend(SiteEditorContainer));
```

I get the `max-len` error, because the line is longer than 100 characters.

What's the way to fix this to avoid all errors? `function-paren-newline` isn't currently smart enough to take account of line length, which seems like a shortcoming, especially now that we have highly evolved line-length tools like Prettier. I understand that there are tradeoffs, and best practices may conflict, but in principle there should be an error-free way to write this code that isn't highly contorted. Solution?

**Comment by yutin1987** [comment]
I have the same issue, happened at function-paren-newline

bad
```
    const wrapper = shallow(
      <Tabbar active={0}>
        <Tabbar.Tab>Teb 1</Tabbar.Tab>
        <Tabbar.Tab>Teb 2</Tabbar.Tab>
      </Tabbar>,
    );
``

bad
```
const wrapper = shallow(<Tabbar active={0}>
      <Tabbar.Tab>Teb 1</Tabbar.Tab>
      <Tabbar.Tab>Teb 2</Tabbar.Tab>
                            </Tabbar>)

const wrapper = shallow(<Tabbar active={0}>
      <Tabbar.Tab>Teb 1</Tabbar.Tab>
      <Tabbar.Tab>Teb 2</Tabbar.Tab>
    </Tabbar>);
```
react/jsx-indent vs react/jsx-closing-bracket-location on end line

**Comment by blord-fullscreen** [comment]
@yutin1987 That is actually a different problem. None of your lines above look too long.Perhaps something is odd with your config. Try pasting into the [Prettier playground](https://prettier.io/playground/).

**Comment by ljharb** [comment]
Prettier has nothing to do with this; this guide does not endorse or recommend using Prettier.

@yutin1987 what about this:
```js
export default connect(mapStateToProps, mapDispatchToProps)(
  generateDndContextWithBackend(SiteEditorContainer),
);
```

**Comment by blord-fullscreen** [comment]
@ljharb That doesn't work. In fact, it doubles the error:
```
Unexpected newline after "("
Unexpected newline before ")"
```

**Comment by yutin1987** [comment]
@ljharb @blord-fullscreen thank you for your answer.

because it is too long, the maximum line length of 100. (max-len)
```
const wrapper = shallow(<Tabbar active={0}><Tabbar.Tab>Teb 1</Tabbar.Tab><Tabbar.Tab>Teb 2</Tabbar.Tab></Tabbar>);
```
so, I need multiline.

```
    // exceeds the maximum line length of 100. (max-len)
    shallow(<Tabbar active={0}><Tabbar.Tab>Teb 1</Tabbar.Tab><Tabbar.Tab>Teb 2</Tabbar.Tab></Tabbar>);

    // Closing tag of a multiline JSX expression must be on its own line. (react/jsx-closing-tag-location)
    shallow(<Tabbar active={0}>
      <Tabbar.Tab>Teb 1</Tabbar.Tab><Tabbar.Tab>Teb 2</Tabbar.Tab></Tabbar>);

    // Expected indentation of 4 space characters but found 12. (react/jsx-indent)
    shallow(<Tabbar active={0}>
      <Tabbar.Tab>Teb 1</Tabbar.Tab><Tabbar.Tab>Teb 2</Tabbar.Tab>
            </Tabbar>);

    // Expected closing tag to match indentation of opening. (react/jsx-closing-tag-location)
    shallow(<Tabbar active={0}>
      <Tabbar.Tab>Teb 1</Tabbar.Tab><Tabbar.Tab>Teb 2</Tabbar.Tab>
    </Tabbar>);

    // Unexpected newline after '('. (function-paren-newline)
    // Unexpected newline before ')'. (function-paren-newline)
    shallow(
      <Tabbar active={0}>
        <Tabbar.Tab>Teb 1</Tabbar.Tab><Tabbar.Tab>Teb 2</Tabbar.Tab>
      </Tabbar>
    );
```

**Comment by ljharb** [comment]
This seems like it's actually a bug in the `function-paren-newline` rule (or an unavoidable conflict with `max-len`).

For now, you may want to disable that rule entirely; I'll leave this open to investigate disabling it in the config itself.

**Comment by the-noob** [comment]
Hopefully I'm not wrong but you are using ["multiline"](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/style.js#L87) (default) so this should work ?

```JavaScript
const isLocalhost = Boolean(
  window.location.hostname === 'localhost' ||
  // [::1] is the IPv6 localhost address.
  window.location.hostname === '[::1]' ||
  // 127.0.0.1/8 is considered localhost for IPv4.
  window.location.hostname.match(
    /^127(?:\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}$/,
  ),
);
```
Also posted in the ESLint [issue](https://github.com/eslint/eslint/issues/9411#issuecomment-341423200)

**Comment by ljharb** [comment]
@yutin1987 fwiw, this is how we handle your example:
```jsx
shallow((
  <Tabbar active={0}>
    <Tabbar.Tab>Teb 1</Tabbar.Tab><Tabbar.Tab>Teb 2</Tabbar.Tab>
  </Tabbar>
));
```
or

```jsx
shallow(
  <Tabbar active={0}>
    <Tabbar.Tab>Teb 1</Tabbar.Tab><Tabbar.Tab>Teb 2</Tabbar.Tab>
  </Tabbar>,
);
```

**Comment by devourment77** [comment]
The second option given still gives me the error. Including the training comma still complains about `Unexpected newline after '('. (function-paren-newline)`

```
<FormItem label="Full Name">
    {getFieldDecorator(fullName.id, fullName.options)(
        <Input type="text" size="large" placeholder="First & Last Name" />,
    )}
</FormItem>
```

**Comment by ljharb** [comment]
@devourment77 
```jsx
<FormItem label="Full Name">
    {getFieldDecorator(fullName.id, fullName.options)((
        <Input type="text" size="large" placeholder="First & Last Name" />
    ))}
</FormItem>
```

**Comment by ljharb** [comment]
I consider it as the multiline jsx is one unit, wrapped in parens - and that’s passed into a function.

**Comment by ljharb** [comment]
Closing; happy to reopen if there's something actionable here.
