### ISSUE TITLE
eslint-config-airbnb v16.0.0 doesn't work with CRA after eject

### ISSUE THREAD

**Issue by James2516** [airbnb/javascript#1586]
https://github.com/James2516/eslint-airbnb
The repo is created with create-react-app + npm run eject.

Running `npm i && npm start` gives an error:

```
./src/index.js
Module build failed: Error: /Users/a/Desktop/eslint-not-working/node_modules/eslint-config-airbnb/rules/react.js:
	Configuration for rule "react/jsx-boolean-value" is invalid:
	Value "never,[object Object]" should NOT have more than 1 items.

Referenced from: /Users/a/Desktop/eslint-not-working/node_modules/eslint-config-airbnb/index.js
Referenced from: /Users/a/Desktop/eslint-not-working/.eslintrc
    at Array.forEach (<anonymous>)
    at Array.reduceRight (<anonymous>)
    at Array.reduceRight (<anonymous>)
```

This only happens with v16.0.0.

**Comment by ljharb** [comment]
Run `npm ls` - does it exit nonzero? If so, the dep graph is invalid, and nothing can be expected to work.

If this is the case, then it's a bug in CRA (probably not handling peer deps properly), and it'd be great to file it there.

**Comment by Kandychen88** [comment]
Could any body knows how to stopped receiving those so many mail every day very minutes 





--

Kandy Liu
RGL International Business
Email: 18221430110@163.com
WWW.RGLINTERNATIONAL.COM

At 2017-10-12 14:42:24, "Jordan Harband" <notifications@github.com> wrote:


Run npm ls - does it exit nonzero? If so, the dep graph is invalid, and nothing can be expected to work.

If this is the case, then it's a bug in CRA (probably not handling peer deps properly), and it'd be great to file it there.

**Comment by ljharb** [comment]
@Kandychen88 you're probably watching the repository; go to https://github.com/airbnb/javascript and click on "unwatch".

I'll delete these comments now, since they're off topic.

**Comment by Kandychen88** [comment]
Thanks you kindly advise but seems haven't fond the path of  unwatch , could you please help to show some step for me . 
Great to heard from you .





--

Kandy Liu
RGL International Business
Email: 18221430110@163.com
WWW.RGLINTERNATIONAL.COM

At 2017-10-12 14:48:12, "Jordan Harband" <notifications@github.com> wrote:


@Kandychen88 you're probably watching the repository; go to https://github.com/airbnb/javascript and click on "unwatch".

I'll delete these comments now, since they're off topic.

**Comment by ljharb** [comment]
@Kandychen88 on the desktop Github site, it's in the upper right corner, next to the star and fork buttons. On the mobile site, it's on the upper right next to the star button.

If that doesn't resolve your issue, please file a *new* issue on this repo instead of replying to the notification email.

**Comment by ljharb** [comment]
What did it turn out to be?

**Comment by James2516** [comment]
https://github.com/James2516/eslint-airbnb/blob/master/package.json#L23-L63
I had 2 different versions installed and it seems like either CRA/airbnb is using the wrong version of its dependencies.

**Comment by ljharb** [comment]
indeed, eslint-config-airbnb v16 requires v6 of eslint-plugin-jsx-a11y (also, all eslint things should be devDeps, not runtime deps).

**Comment by James2516** [comment]
CRA put it in runtime deps. See https://github.com/facebookincubator/create-react-app/issues/3209

**Comment by yummyelin** [comment]
Same issue here.

"eslint-config-airbnb": "^16.1.0",
"eslint-plugin-jsx-a11y": "6.0.2",

**Comment by heyitshannes** [comment]
Found the issue. After ejecting CRA, there is a dep on eslint-config-react-app which depends on an earlier version of eslint-plugin-jsx-a11y. After removing eslint-config-react-app, and moving all eslint deps to dev-deps, everything started working as expected.

**Comment by vickvasquez** [comment]
After moving dev-dependencies run this command.
(
  export PKG=eslint-config-airbnb;
  npm info "$PKG@latest" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs npm install --save-dev "$PKG@latest"
)

**Comment by A1ex5andr** [comment]
remove `eslint-config-react-app`

install `npm i --save-dev eslint eslint-loader eslint-plugin-flowtype eslint-config-airbnb eslint-plugin-import eslint-plugin-jsx-a11y`

**Comment by lionel95200x** [comment]
Doesn't work for me too

**Comment by hiyangguo** [comment]
Me too.
