### ISSUE TITLE
Template string with special character are getting inappropriately converted to quoted string

### ISSUE THREAD

**Issue by riwu** [airbnb/javascript#1593]
```<input placeholder={`line1\nline2`} ></input>``` gets auto fixed into 
`<input placeholder="line1\nline2" />` which treats the `\n` literally. 

Versions:
    "eslint-config-airbnb": "^16.0.0",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^6.0.2",
    "eslint-plugin-react": "^7.4.0"

**Comment by ljharb** [comment]
Thanks; would you please file this upstream on eslint-plugin-react: https://github.com/yannickcr/eslint-plugin-react/issues/new ?
