### ISSUE TITLE
`ForOfStatement` rules with yield (no-restricted-syntax)

### ISSUE THREAD

**Issue by VincentLanglet** [airbnb/javascript#1603]
Hello

I use redux-saga, and when I write

`function* () {
   for (const key of Object.keys(obj)) {
     yield stuff(key, obj[key]);
   }
 }`

I get the message

`iterators/generators require regenerator-runtime, which is too heavyweight for this guide to allow them. Separately, loops should be avoided in favor of array iterations`

But i didn't found any explanation of the good way to write this function.

I need the stuff with the first key to be finished before the stuff with the second key before ...

Is it possible with the airbnb config ?

**Comment by ljharb** [comment]
My understanding is that redux-saga requires generators, and the airbnb config forbids them - so there's not really a good way to do it. You could do `function () { return Object.entries(obj).map(entry=> stuff(entry)).values(); }`, however.

**Comment by VincentLanglet** [comment]
That's what I suspected.

Since the technical team wishes to follow the standard airbnb and uses redux-saga, I think to disable this rule.

Thank you for your answer.
