### ISSUE TITLE
flycheck issues ecmaFeatures deprecated error at every change when loading airbnb with "extends" property

### ISSUE THREAD

**Issue by zebralight** [airbnb/javascript#1623]
I reported this issue initially here: https://github.com/flycheck/flycheck/issues/1350 and received the following advice and am forwarding this:

> The problem is exit code 1 that comes from xml parser. eslint will print deprecation warning before actual XML output. Right now flycheck does not distinguish strout and stderr so everything that we get from eslint we feed to XML parser. My understanding is that changing this will also have implications to other parsers in flycheck. See GH-1323.
> 
> Easy solution is to take airbrb config and paste it in your .eslintrc file and than remove ecmaFeatures from config. You can run eslint --print-config . to get resolved config without any extends.
> 
> You can also try to downgrade eslint to a version that does not have ecmaFeatures deprecated until that ruleset gets removed from airbrb eslint config.
> 
> You should let airbnb plugin maintainers know that ecmaFeatures is deprecated and should be removed.
> 
> Long term solution is to modify flycheck to parse JSON output from eslint instead of XML. That way we can use flycheck-parse-json to remove all non JSON data (all deprecation warnings).

**Comment by ljharb** [comment]
I'm not familiar with flycheck; regardless, are you using the latest version of the eslint config? If you're using eslint v4.8, then you aren't.

**Comment by ljharb** [comment]
The top-level ecmaFeatures property was removed from the "legacy" endpoint in v11.3.1 of `eslint-config-airbnb-base`, if that's what you're using: https://github.com/airbnb/javascript/commit/0d938aecf20e2a6ad586e08155e177a25d12bc5e#diff-0e05d3ae9436a386fda69c8e08701785

**Comment by zebralight** [comment]
Thanks, ljharb.  I tried a number of other things, but I'm pretty sure that updating my version of eslint was what made the error messages go away!
