### ISSUE TITLE
Some link issues in README.md

### ISSUE THREAD

**Issue by vsemozhetbyt** [airbnb/javascript#1626]
I am not sure how to fix them, so there is just a report.

1. Possibly outdated hashes:

    [Popular JavaScript Coding Conventions on GitHub](http://sideeffect.kr/popularconvention/#javascript)
    [Read ECMA-262’s note on this issue](http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-262.pdf#page=97)

2. `ERR_CONNECTION_TIMED_OUT`

    [Dustin Diaz](http://dustindiaz.com/)

3. `ERR_CONNECTION_REFUSED`

    [Draft ECMA 2015 (ES6) Spec](https://people.mozilla.org/~jorendorff/es6-draft.html)

4.  `404 Not found`

    [3Blades/javascript](https://github.com/3blades/javascript)
    [bisk/javascript](https://github.com/Bisk/javascript/)
    [gawkermedia/javascript](https://github.com/gawkermedia/javascript)
    [huballin/javascript](https://github.com/huballin/javascript)
    [kickorstick/javascript](https://github.com/kickorstick/javascript)
    [muber/javascript](https://github.com/muber/javascript)
    [natgeo/javascript](https://github.com/natgeo/javascript)
    [reidev/js-style-guide](https://github.com/rei/code-style-guides/blob/master/docs/javascript.md)
    [springload/javascript](https://github.com/springload/javascript)

**Comment by ljharb** [comment]
http://sideeffect.kr/popularconvention/#javascript is as up to date as is needed at this time (and the hash still works); the spec link was removed in ES6, so I'll remove it here.

I've removed 2 and updated 3. For 4, I've updated all those links to point at the username instead of the former repo.
