### ISSUE TITLE
Add staticContext to list of no-param-reassign "ignorePropertyModificationsFor" 

### ISSUE THREAD

**Issue by jnields** [airbnb/javascript#1639]
The property `staticContext` is passed to react-router components during server-side-rendering, and assignment to properties in this object is used to convey information to the server, e.g. response status codes.
 
https://reacttraining.com/react-router/web/api/StaticRouter/context-object

Would you be willing to add `staticContext` to the list of OK params to reassign?

https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/best-practices.js#L174

**Comment by ljharb** [comment]
That seems reasonable, sure.

**Comment by PupoSDC** [comment]
Similar to this (old) request. Could we also add "state" for vuex mutations ?

An example code snippet from [vuex's documentation](https://vuex.vuejs.org/guide/mutations.html) that triggers this rule:

```JS
const store = new Vuex.Store({
  state: {
    count: 1
  },
  mutations: {
    increment (state) {
      // mutate state
      state.count++
    }
  }
})
```
