### ISSUE TITLE
What are the risks of mixing shorthand properties with valued ones?

### ISSUE THREAD

**Issue by mk-pmb** [airbnb/javascript#1642]
The BOM PR is still on my todo, don't worry. I hope it's ok to ask the next explanation nonetheless, becuase I just found another part I don't understand. As for rule 3.5 "Group your shorthand properties…" it states:

> Why? It’s easier to tell which properties are using the shorthand.

What's the benefit thereof? Why is it important to see what's shorthand? What are the risks of mixing them?

**Comment by lencioni** [comment]
Oddly enough, we were discussing just this thing internally this morning. Stay tuned.

**Comment by ljharb** [comment]
This user's questions about it in IRC prompted the internal discussion ;-)

**Comment by mk-pmb** [comment]
Nope, I only read the question in the log hours later. I'm Sven_vB.

**Comment by mk-pmb** [comment]
Did the discussion yield any news yet?

**Comment by ljharb** [comment]
I'm afraid we still haven't achieved any consensus.

**Comment by mk-pmb** [comment]
So what's the news? Are there reasons now?

**Comment by ljharb** [comment]
No consensus was able to be reached. If that changes, this can be reopened.
