### ISSUE TITLE
javascript, why get json err? 

### ISSUE THREAD

**Issue by jinpengchina** [airbnb/javascript#1644]
> checkTicker()
> function checkTicker() {
>   var dao = new XMLHttpRequest();
> 
>  //dao.open("GET", "https://api.fanyi.baidu.com/api/trans/vip/translate?q=hello&from=en&to=zh&appid=20171120000097357&salt=1435660288&sign=bcd4bc3fe3b120dddea66560f8533891",true);
> 
>   dao.open("GET", "https://poloniex.com/public?command=returnTicker", true);
> 
>   document.write("===111===") 
>   dao.onreadystatechange = function() 
>   {
>         document.write("==222==") 
>         document.write(dao.status) 
> 
>   }
>   dao.send();
> }

if i use url "poloniex.com" to get json, not problem, and "dao.status" is 200;

but if i use url "baidu" to get json, get nothing , and "dao.status" is 0;

all of this 2 url can get json in chrome .

why url baidu can not get json, and how to do ?

**Comment by ljharb** [comment]
@jinpengchina this repo is for Airbnb's javascript style guide, and is not a resource for general JS help.

I'm going to close this. I'd suggest researching the same-origin policy, and CORS.
