### ISSUE TITLE
ESLint 'anchor-is-valid' rule interfering with react-router-dom

### ISSUE THREAD

**Issue by tshen8** [airbnb/javascript#1647]
```
    'jsx-a11y/anchor-is-valid': ['error', {
      components: ['Link'],
      specialLink: [],
      aspects: ['noHref', 'invalidHref', 'preferButton'],
    }],
```
The current configuration will cause `<Link to="/route" />` to be marked as invalid, as it does not have an `href` attribute. Internally, the `Link` component will transform the `to` prop and render an anchor element that does have an `href`.

`to` just needs to be added to the `specialLink` array. 

I'd be happy to open a PR if everyone is okay with this change.

**Comment by ljharb** [comment]
Not everyone uses react-router; this change (while correct) is generally something you'd want to do in your own app.

**Comment by tshen8** [comment]
@ljharb then I'm a little confused as to why the current configuration validates the `Link` component, without allowing for the `to` prop. Unless it's referring to the lower case `<link>` tag?

**Comment by ljharb** [comment]
@tshen8 hm, that is a fair point.

So yes, we should either remove `Link` or add `to`; and the latter makes the most sense. A PR would be great, thanks! :-)

**Comment by ljharb** [comment]
(looks like #1648 covers it)
