### ISSUE TITLE
one-const is incompatible with destructure rule

### ISSUE THREAD

**Issue by greggman** [airbnb/javascript#1649]
The [one const rule 13.2](https://github.com/airbnb/javascript#variables--one-const) says

> Use one const or let declaration per variable
>
>       // bad
>       // (compare to above, and try to spot the mistake)
>       const items = getItems(),
>           goSportsTeam = true,
>           dragonball = 'z';
>       
>       // good
>       const items = getItems();
>       const goSportsTeam = true;
>       const dragonball = 'z';

But the [destructure rule](https://github.com/airbnb/javascript#destructuring--object) requires declaring multiple variables per const

>       // good
>       function getFullName(user) {
>         const { firstName, lastName } = user;

Seems inconsistent?!??

**Comment by ljharb** [comment]
Fair point; the wording could be better. "Use one `const` or `let` declaration per variable or assignment" seems like it would cover destructuring?

**Comment by parulgupta26** [comment]
@ljharb - I've raised PR for this - https://github.com/airbnb/javascript/pull/1927
