### ISSUE TITLE
JS Style Guide Website

### ISSUE THREAD

**Issue by MaxShalom** [airbnb/javascript#1650]
### Hello,
This style guide is very useful, however, it can be hard to read and use on Github, so, I have turned it into a website listed below, using @surge-sh:

[http://js-styleguide.surge.sh/](http://js-styleguide.surge.sh/)

I would love to update it as the README is updated, and would love if someone made me a contributor in order to do so quicker. Also, I plan to add the other Airbnb style guides soon. As of now, I had to take out the table of contents and links to the top of the page, but it still works fine. Hope this helps people and if someone would like to help out that would be great. 

Pictures:

![image](https://user-images.githubusercontent.com/23295246/33533969-8ac13504-d872-11e7-850f-ddada6dd5979.png)

![image](https://user-images.githubusercontent.com/23295246/33533996-bbc1f2f6-d872-11e7-843f-e94ba5400e57.png)

**Comment by MaxShalom** [comment]
Added a reference link to the website on the Style Guide file and submitted a pull request. #1651

**Comment by ljharb** [comment]
I don't agree that it's hard to read or use Github for anyone who's writing JavaScript (the audience for this style guide); plus, there's http://airbnb.io/javascript/ already.

Either way, we wouldn't want to direct people to a website we don't retain control over.
