### ISSUE TITLE
Cannot validate indentation of prop values using default eslint-airbnb-preset and eslint-plugin-react

### ISSUE THREAD

**Issue by n1313** [airbnb/javascript#1658]
OSX 10.12.6, eslint 4.9.0, eslint-plugin-react 7.4.0, babel-eslint 8.0.1, eslint-config-airbnb 16.1.0, eslint-config-airbnb-base 12.1.0.

This code does not trigger any warnings on default values for `indent`, `react/jsx-indent` and `react/jsx-indent-props`:

```
return (
  <Component
    prop={true}
    anotherProp={[
      {
        id: 1
      },
  {
        id: 2
  }
    ]}
  />
);
```

My expectation is that the value of `anotherProp` would be treated as a regular array of objects, triggering an `indent` or `jsx-indent-props` warning for mis-indented curly braces around second object.

The issue [seems to be caused](https://github.com/yannickcr/eslint-plugin-react/issues/1599) by default value of `indent.ignoredNodes`: `[ "JSXElement", "JSXElement *" ]`. If I remove `JSXElement *`, the warning triggers as expected. Is this behaviour desired?

**Comment by ljharb** [comment]
No, I think `JSXElement *` is overly broad.

My intention is that `indent` will ignore any nodes that are JSX; but it should still warn on JS values inside them.
