### ISSUE TITLE
Section 15.8 Enclose operators of README.MD

### ISSUE THREAD

**Issue by laurentiu-ilici** [airbnb/javascript#1659]
The two functions do not return the same thing:
//given as bad example where it's unclear that the && preceeds the || operator
if (a || b && c) //more code 

//given as the good way, but actually does something different from the if above
if((a || b) && c) //more code

I am not sure if it is intentional but the two "if"s which look like they should be equivalent are actually not. I guess the intention was to say for the second one if (a || (b && c)) in order to emphasize that this gets evaluated like this. Would gladly submit a PR for this :).

**Comment by ljharb** [comment]
Thanks, that'd be great :-) probably worth including all three examples, illustrating the meaningful difference and potential for confusion.

**Comment by laurentiu-ilici** [comment]
I can't upload my branch, I am not sure if this is because I misstyped my credentials/sms security code or because I am not a contributor. It doesn't ask  me for the credentials a second time though. Any ideas?

**Comment by ljharb** [comment]
@laurentiu-ilici fork the repo, push the branch to your fork, and make the PR from there.

**Comment by laurentiu-ilici** [comment]
Done: https://github.com/airbnb/javascript/pull/1661
It took more to fork and such than to actually contribute :))

**Comment by ljharb** [comment]
Closed in #1661.
