### ISSUE TITLE
Single parameter arrows should always omit parens

### ISSUE THREAD

**Issue by erights** [airbnb/javascript#1672]
On https://github.com/airbnb/javascript#functions--reassign-params
Why is

```js
// bad
[1, 2, 3].map(x => {
  const y = x + 1;
  return x * y;
});
```

bad? I do that all the time. The extra parens are more verbose whether or not the body uses curlies.

**Comment by ljharb** [comment]
This guide (from our internal company usage) has decided on this standard; which is that one-arg implicit return arrow functions are the only place where arg parens may be permitted. eslint added a special option to their linter rule to allow for our style, which our linter config enforces.
