### ISSUE TITLE
Avoiding * imports is even more important

### ISSUE THREAD

**Issue by erights** [airbnb/javascript#1674]
Re https://github.com/airbnb/javascript#modules--no-wildcard

An additional reason to avoid * imports:

In a module without * imports, every use occurrence of a variable name either refers to a defining occurrence in the same module text, or it is free (refers to a global). In a module with * imports, you can't tell statically from the module text by itself. Further, if the imported module exports a name that collides with a global, it will invisibly shadow that global in the importing module.

**Comment by ljharb** [comment]
Very very good points; I'm all for adding more reasons to avoid star imports :-)

**Comment by ljharb** [comment]
> In a module with * imports, you can't tell statically from the module text by itself. Further, if the imported module exports a name that collides with a global, it will invisibly shadow that global in the importing module.

This is actually not true; `import *` only works with `as foo`, ie, it imports into a namespace object. No variables can possibly be shadowed by `import *` statements except the static `as` identifier.
