### ISSUE TITLE
Recommend that switch branches always have curlies

### ISSUE THREAD

**Issue by erights** [airbnb/javascript#1676]
https://github.com/airbnb/javascript#comparison--switch-blocks
recommends curlies only when the branch has a declaration. This is a maintenance hazard. I always happily use curlies there. We should recommend that. It's also a simpler recommendation to remember, and easier for the eye to spot a violation.

**Comment by ljharb** [comment]
Our eslint configuration enforces the use of these curlies when necessary; to be following this guide, one must also be using our linter config.
