### ISSUE TITLE
Properties 12.2

### ISSUE THREAD

**Issue by stevewood593** [airbnb/javascript#1684]
Hi,

I think you guys mean "Use bracket notation [] when accessing properties with a function," at [12.2](https://github.com/airbnb/javascript#properties--bracket) in the airbnb style guide. Right now it says "Use bracket notation [] when accessing properties with a variable."

**Comment by ljharb** [comment]
I'm not sure what you mean by "with a function" - how is `obj[variableContainingKeyName]` using a function?

**Comment by stevewood593** [comment]
I think the difference between 12.1 and 12.2 is that the 12.2 example occurs within a function:

````javascript
function getProp(prop) {
  return luke[prop];
}

**Comment by ljharb** [comment]
The rule is referring to bracket notation regardless of context; that it’s a function is irrelevant.

**Comment by stevewood593** [comment]
Ok, I get it.
