### ISSUE TITLE
prop-types in react router

### ISSUE THREAD

**Issue by GravityMsc** [airbnb/javascript#1692]
I use `eslint-config-airbnb` rules. and here is my code example.
```jsx
const PrivateRoute = ({ component: Component, ...rest }) => (
  <Route
    {...rest}
    render={props => (
      authLogin ?
        <Component {...props} /> :
        <Redirect to={{
          pathname: '/login',
          state: { from: props.location },
        }}
        />
    )}
  />
);
PrivateRoute.propTypes = {
  component: PropTypes.element.isRequired,
};
```
[eslint] 'location' is missing in props validation (react/prop-types)

I wonder what should I do to fix it? I've attempted to fix but useless

**Comment by ljharb** [comment]
For the record, our style guide prohibits arrow function SFCs; that should be `function PrivateRoute(`.

The error message is that your propTypes lack "location"; as you can see in `PrivateRoute.propTypes = {`, you haven't specified `location`.

Try:
```jsx
PrivateRoute.propTypes = {
  component: PropTypes.element.isRequired,
  location: Redirect.propTypes.state.from, // if this doesn't work because Redirect badly specifies its propTypes, then:
  location: PropTypes.object, // or whatever the most precise propType you can come up with is
};
```

**Comment by GravityMsc** [comment]
Thank you. And I misunderstand the 'props'. I rewrite it in `Route.propTypes`. Sorry for bothering you
