### ISSUE TITLE
Some problem with prefer ** than Math.pow

### ISSUE THREAD

**Issue by hurrytospring** [airbnb/javascript#1696]
In ios 10.2, safari seems to not support for **;

```
let a= 3 ** 10;
```
throw an error : unexpected token '*'

**Comment by ljharb** [comment]
The exponentiation operator is new in ES2017; not every browser or engine will support it.

This guide and linter config requires that you be using babel, and https://npmjs.com/babel-preset-airbnb or the equivalent.
