### ISSUE TITLE
Add import/no-self-import rule?

### ISSUE THREAD

**Issue by wenkanglin** [airbnb/javascript#1701]
As the title say, I found that the rule [import/no-self-import](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-self-import.md) hasn't been  defined at airbnb. Maybe we should add and open this rule with below config at `eslint-config-airbnb-base/rules/imports.js`?

```js
'import/no-self-import': 'error'
```

**Comment by ljharb** [comment]
That's because that rule hasn't been released in eslint-plugin-import yet.
