### ISSUE TITLE
Add componentDidCatch to exceptMethods for class-methods-use-this

### ISSUE THREAD

**Issue by alexbaulch** [airbnb/javascript#1703]
Hey guys,

I just spotted that if you add a `componentDidCatch` class method to a Component class it triggers the `class-method-use-this` eslint rule. As far as I can see it is just a case of adding the `componentDidCatch` to the `exceptMethods` for the `class-method-use-this` in this [file](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/react.js).

If this is the case more than happy to do a PR for the change but not sure what the process is.

Thanks,

Alex

**Comment by ljharb** [comment]
@alexbaulch thanks, that'd be great! When updating it, please also update the React pragma in the config to be v16.

**Comment by ljharb** [comment]
Fixed in #1704.

**Comment by katerberg** [comment]
Hey, this would be super helpful to me. Is this released yet? I can't figure out which PRs are in each release.

**Comment by ljharb** [comment]
It's not released yet. If you click to the PR, and then click on the [commit](https://github.com/airbnb/javascript/pull/1704/commits/53b2d7d245ba4abefc0429bfda4a46f099b9ace5), you'll see that it's in master, but not in any release tags.
