### ISSUE TITLE
prefer-destructuring rule triggers when mutating `let` binding

### ISSUE THREAD

**Issue by abonander** [airbnb/javascript#1705]
When you have the following:

    let foo;
    // ...
    foo = bar.foo;

The `prefer-destructuring` rule triggers on the last line even though there's no way to actually mutate a `let` binding with destructuring (`{ foo } = bar;` is a syntax error).

**Comment by ljharb** [comment]
`({ foo } = bar);`

**Comment by abonander** [comment]
That works, but looks worse than the original IMO. Still, not a problem with the rule itself, so closing.
