### ISSUE TITLE
Add storybooks exceptions to eslint config

### ISSUE THREAD

**Issue by canda** [airbnb/javascript#1706]
Shouldn't we add to the eslint rule `import/no-extraneous-dependencies` the files that are stories for storybook?
Their dependencies are actually dev dependencies.

the expression could be '**/*.stories.{js,jsx}'

**Comment by ljharb** [comment]
That's not the convention we follow for our storybook files (we do not colocate production files with dev files, so stories, like tests, live in their own top-level directory with a parallel structure to the actual code); also, using storybook itself isn't necessarily universal. I don't think this is useful for the time being.

**Comment by OR13** [comment]
One way to handle this, if you do colocate... (modify for jsx as needed).

```
eslint --ext js --ignore-pattern *.stories.js src
```
