### ISSUE TITLE
Why cuddled elses? (brace style)

### ISSUE THREAD

**Issue by merlinpatt** [airbnb/javascript#1709]
For control statements, why do you prefer `else`s to be on the same line as the if ending brace? [16.2](https://github.com/airbnb/javascript#blocks--cuddled-elses)

Under [8.3 - wrapping parens](https://github.com/airbnb/javascript#arrows--paren-wrap), you state that wrapping parens shows clearly where the function starts and ends.

I think that having the `else` block start on the same line is less clear than if it starts on a separate line. This is especially the case if the code blocks are small. You might read the `if` and skip over `else` entirely.

Currently preferred - same line
```
if (test) {
  thing1();
} else {
  thing2();
}
```
vs
Separate lines
```
if (test) {
  thing1();
}
else {
  thing2();
}
```

**Comment by ljharb** [comment]
This is a subjective preference, but specifically, the `else` is *part* of the `if` - it's not a separate piece - so it shouldn't begin a new line.

In general, we follow [One True Brace Style](https://en.wikipedia.org/wiki/Indentation_style#Variant:_1TBS_(OTBS)).
