### ISSUE TITLE
I'd like to update Korean translation link

### ISSUE THREAD

**Issue by ParkSB** [airbnb/javascript#1713]
Currently, Korean translation document is linked to [tipjs/javascript-style-guide](https://github.com/tipjs/javascript-style-guide). I respect their works, but there aren't any activities from Aug 2017. (I sent PR at the beginning of January, but it is on hold with out any response until now.)
I have forked @tipjs's repository, and update all of the contents, so I suggest changing Korean translation document link to [ParkSB/javascript-style-guide](https://github.com/ParkSB/javascript-style-guide). What do you think of it?

**Comment by ljharb** [comment]
That sounds great - can you make the PR? I'll try to find someone internal who can review it.

**Comment by ljharb** [comment]
Thanks, closed in #1714 :-)
