### ISSUE TITLE
Multiple configuration rules invalid

### ISSUE THREAD

**Issue by Will-GitHub94** [airbnb/javascript#1716]
Package versions *(all latest)*:

- eslint @ 4.16.0
- eslint-config-airbnb @ 16.1.0
- eslint-config-airbnb-base @ 12.1.0

My `.eslintrc` extends "airbnb-base".<br>Attempting to run my application results in:

```
Error: E:\Documents\Projects\base_server_db\node_modules\eslint-config-airbnb-base\rules\es6.js:
      Configuration for rule "prefer-destructuring" is invalid:
      Value "data["0"].VariableDeclarator" has additional properties.
      Value "data["0"].AssignmentExpression" has additional properties.
```

Looking at the rule, it looks perfectly reasonable:
```javascript
// Prefer destructuring from arrays and objects
// http://eslint.org/docs/rules/prefer-destructuring
'prefer-destructuring': ['error', {
    VariableDeclarator: {
        array: false,
        object: true,
    },
    AssignmentExpression: {
        array: true,
        object: true,
    },
}, {
   enforceForRenamedProperties: false,
}],
```

To see if any other rules were "invalid", I commented this one out and got a similar error to do with `indent`.

```
Error: E:\Documents\Projects\base_server_db\node_modules\eslint-config-airbnb-base\rules\style.js:
        Configuration for rule "indent" is invalid:
        Value "data["1"].ImportDeclaration" has additional properties.
        Value "data["1"].flatTernaryExpressions" has additional properties.
        Value "data["1"].ignoredNodes" has additional properties.
```

Is this a known issue? If not, what would be causing this? I have looked at an [SO question](https://stackoverflow.com/questions/39988501/what-does-has-additional-properties-mean-in-an-error-message-about-an-eslintr) similar and there was also an additional [issue](https://github.com/airbnb/javascript/issues/1352) raised early last year for this **but** these 2 solutions both say to update packages which is not possible here.<br>Any ideas?

**Comment by ljharb** [comment]
Almost certainly, the issue is that you're running a global eslint (which shouldn't even be installed).

What exact command are you using to run eslint?

**Comment by Will-GitHub94** [comment]
Running it via gulp.<br>
The task is:
```javascript
// ESLint JS linting task
gulp.task("eslint", () => {
	const assets = union(
		defaultAssets.server.gulpConfig,
		defaultAssets.server.allJS,
		testAssets.tests.server,
		testAssets.tests.e2e
	);

	return gulp.src(assets)
		.pipe(plugins.eslint())
		.pipe(plugins.eslint.format());
});
```

**Comment by ljharb** [comment]
In that case it might be a gulp bug; can you. try running it on the command line?

**Comment by Will-GitHub94** [comment]
Yes, that works so is clearly an issue with the task runner then. I will close
