### ISSUE TITLE
Trailing semicolons for chained methods

### ISSUE THREAD

**Issue by okaybenji** [airbnb/javascript#1717]
Following the rationale for additional trailing commas, doesn't it also follow that chained method calls should end with semicolons on a new line?

```
doAThing()
  .doAnotherThing()
  .doYetAnotherThing()
;
```

You'll get better diffs, and debugging will be easier.

Sometimes you want to change the order of execution, e.g.:
```
doAThing()
  .doYetAnotherThing() // Moved this line up.
  .doAnotherThing()
;
```
And it will still work, even if you change which method gets called last, without shuffling your semicolons around. 

Similarly, you can tack a function on the end without doing the semicolon shuffle:
```
doAThing()
  .doAnotherThing()
  .doYetAnotherThing()
  .doOneLastThing()
;
```
You also have the freedom to comment out the last line without losing your semicolon:
```
doAThing()
  .doAnotherThing()
//.doYetAnotherThing()
;
```

**Comment by ljharb** [comment]
That's certainly an interesting suggestion, and it definitely would follow the "minimize diffs" category.

However, chained method calls are a fundamentally different concept than "lists of things", and the likelihood that those will change is pretty low - it's not simply reordering a list; the logic will likely be fundamentally different in a different order.

**Comment by okaybenji** [comment]
I can see why some would see chained method calls as fundamentally different from "lists of things." It probably depends quite a bit on the sorts of projects you work on and your coding style. Functional programmers may see chained method calls as a list of transformations. And in my work, we have a lot of chunks of code that look something like this:

```
const aTextEntity = new TextEntity()
  .text('This is a text entity')
  .textAlign('center')
  .fontSize('40px')
  .fontWeight('bold')
  .shadowSize(1)
  .shadowBlur(6)
  .strokeSize(6)
  .strokeColor('#000')
  .shadowColor('rgba(0, 0, 0, 0.75)')
  .center(0)
  .bottom(50);
```

You can probably see how adding properties like this could lead to several instances of ugly diffs. I wonder how difficult it would be to collect data from Github to find out how common this problem is.

**Comment by ljharb** [comment]
A truly functional style would use a pipeline operator, and not be chained :-)

At any rate, while I certainly agree that your reasoning is consistent with the trailing comma reasoning, and I think it'd be totally defensible to define this style in your own project, it's not one Airbnb will likely ever use.

**Comment by okaybenji** [comment]
That's fair enough, thanks for reading it over and evaluating the idea.

Just BTW, you're wrong about the functional style. This is pretty common for functional-leaning JS programmers:

```
someArray
  .filter(removeSomeItems)
  .map(doSomeTransformation)
  .sort(arrangeThemInSomeWay)
  .etc(youGetTheIdea);
```
