### ISSUE TITLE
Error Date calculation error

### ISSUE THREAD

**Issue by big-dinner** [airbnb/javascript#1725]
```js
// set time 2018/1/31
var date_obj = new Date(2018,0,31);
console.log(date_obj);

// show month
var current_month = date_obj.getMonth();
console.log(current_month);

// get next month
var next_month = parseInt(current_month)+1;
console.log(next_month);

// set month
date_obj.setMonth(next_month);

// show result
console.log(date_obj);

the result show that month is mar not feb

![image](https://user-images.githubusercontent.com/34903283/35905960-dbdd6086-0c23-11e8-84b5-4db889883a7f.png)
```

**Comment by ljharb** [comment]
This seems like a general JS question, and not one specific to this styleguide.

I'd recommend using https://npmjs.com/moment instead of using the native Date object.

**Comment by ljharb** [comment]
Because that would break the entire internet that's already relying on how `Date` works, probably.

**Comment by big-dinner** [comment]
in especial, when the date involve February

**Comment by gergoerdosi** [comment]
This is the expected behavior of `setMonth()`, see the documentation for more details:

> The current day of month will have an impact on the behaviour of this method. Conceptually it will add the number of days given by the current day of the month to the 1st day of the new month specified as the parameter, to return the new date. For example, if the current value is 31st August 2016, calling setMonth with a value of 1 will return 2nd March 2016. This is because in 2016 February had 29 days.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setMonth

**Comment by big-dinner** [comment]
thank you，I often read this page by chinese,but the chinese page usually not detailed like en-US.
