### ISSUE TITLE
Exposed endpoint for non-style based rules only

### ISSUE THREAD

**Issue by gyandeeps** [airbnb/javascript#1738]
I want to use all the non-style based rules from airbnb. I am trying to start a new project and i want to enforce non-styles rules first.

If this endpoint doesn't exists then is it possible to enhance the api to have such an endpoint?
I am willing to do the work. Thanks

**Comment by ljharb** [comment]
Typically, calling some rules “style” is used to marginalize their importance.

Style-based rules are *every bit as critical* as any other kind of rules, and catch bugs just the same.

Although our rule files are split by eslint’s categories, one of which is “style”, we won’t be making t any easier for people to catch fewer bugs based on a belief that “style” is something that can be deferred.

**Comment by gyandeeps** [comment]
because i have been using `prettier` for styling.

**Comment by ljharb** [comment]
Our linter configs are not yet compatible with prettier; with the next release, you should be able to use prettier-eslint with our guide and it should correct all the incorrect styles prettier outputs. You won’t want to disable any of our rules, however, or you won’t be following this guide.

Prettier has its own eslint config already that disables all the core rules it conflicts with; i wouldn’t recommend using that, but it may suffice in the meantime.
