### ISSUE TITLE
Why should we not use Generators in react native according to Airbnb

### ISSUE THREAD

**Issue by Ayyagaries** [airbnb/javascript#1739]
I have an app that uses React saga that uses generators. I was getting some syntax error with Eslint 
[eslint] Unexpected unnamed generator function. (func-names). I was reading the documentation and found this. 

11.2 Don’t use generators for now.
Why? They don’t transpile well to ES5.

I am new to react native. Can someone help me understand?

**Comment by ljharb** [comment]
Our styleguide is primarily written for web react (and universal node code), and generators transpile into something too heavyweight for web usage.

In React Native, generators can be used natively, so this advice doesn’t apply - although there are many other reasons to avoid generators, they aren’t enumerated by the guide at this time. So, your best bet is to override the syntax rule that forbids generators (func-names is something different, your generator functions should still have names).

**Comment by dcbrwn** [comment]
@ljharb Is this restriction still actual in mid 2019? I mean it's still in the config, but conceptually is it still makes sense to disallow generators?

**Comment by ljharb** [comment]
Yes.
