### ISSUE TITLE
Indentation of object destructuring default parameter

### ISSUE THREAD

**Issue by raxell** [airbnb/javascript#1741]
What's wrong with the indentation of this function? Why the linter expects an additional level of indentation?

```js
function x({
  a,
  b,
} = {
  a: 1, // Expected indentation of 4 spaces but found 2
  b: 2, // Expected indentation of 4 spaces but found 2
}) { // Expected indentation of 2 spaces but found 0
  // ...
}
```

If I do the same with variables the linter does not complain, it seems a contradiction.

```js
const {
  a,
  b,
} = {
  a: 1,
  b: 2,
};
```

**Comment by ljharb** [comment]
Indeed, this might be a bug with the indent rule with default arguments.

Can you file this on eslint itself?

**Comment by raxell** [comment]
There it is: https://github.com/eslint/eslint/issues/10001

**Comment by 321ckatz123** [comment]
I think this can be closed in light of root eslint bug that @raxell posted not being reproducible.
