### ISSUE TITLE
about Component Naming?

### ISSUE THREAD

**Issue by jamieYou** [airbnb/javascript#1752]
https://github.com/airbnb/javascript/tree/master/react#naming
```
Component Naming: Use the filename as the component name. For example, ReservationCard.jsx should have a reference name of ReservationCard. However, for root components of a directory, use index.jsx as the filename and use the directory name as the component name:

// bad
import Footer from './Footer/Footer';

// bad
import Footer from './Footer/index';

// good
import Footer from './Footer';
```
I very much agree with this naming.
But colleagues responded. In the editor, search the file, you can not directly find the corresponding file name. Can only find the corresponding folder, then click to view.
Is there any solution?

**Comment by ljharb** [comment]
Most editors have a “jump to file” box where you can type a few chars of the directory name, and a few chars of the filename, and find it exceedingly quickly. If your editor is smart enough, and what you type matches a dir name, it should also include “index” there too.

**Comment by jamieYou** [comment]
@ljharb 
Thank you. My first use of "folder / file name" this way, but not valid.
Now change to separate words by spaces. This is valid.
