### ISSUE TITLE
Asynchronous iteration (for-await-of) and ForOfStatement deprecation

### ISSUE THREAD

**Issue by vsemozhetbyt** [airbnb/javascript#1754]
```js
'use strict';

(async () => {
  for await (const item of [Promise.resolve('a'), Promise.resolve('b')]) {
    console.log(item);
  }
})();
```
```console
  4:3  error  iterators/generators require regenerator-runtime, which is too heavyweight for this guide to allow them. Separately, loops should be avoided in favor of array iterations  no-restricted-syntax
```

Should the `ForOfStatement` entry in `no-restricted-syntax` be alleviated in such cases? Maybe it is worth to remove the second part of the message ("loops should be avoided in favor of array iterations"), since there seems to be no easy different way for array asynchronous iteration?

Is there a way for AST parser to distinguish an async `ForOfStatement` from a sync one?

**Comment by ljharb** [comment]
In this case, you're iterating an array of promises you already have, so using async iteration provides precisely zero benefit.
```js
[Promise.resolve('a'), Promise.resolve('b')].forEach((promise) => {
  promise.then((item) => { console.log(item); });
});
```

Regardless, no, it should be alleviated in no cases, because the transpilation of it still currently requires regenerator-runtime.

**Comment by vsemozhetbyt** [comment]
Sorry, it was just a simplified example. What about something like this?

https://nodejs.org/download/nightly/v10.0.0-nightly201803035a55a71150/docs/api/stream.html#stream_readable_asynciterator

**Comment by ljharb** [comment]
@vsemozhetbyt if you're in a node-only environment, you can certainly override rules that are concerned with transpilation overhead.

**Comment by halitaydin** [comment]
### How can I implement this for await loop with airbnb?

It warn me _'iterators/generators require regenerator-runtime, which is too heavyweight for this guide to allow them. Separately, loops should be avoided in favor of array iterations.'_ when i use for await loop. (no-restricted-syntax)

Note: The code works fine with the for await loop.

```javascript
const range = {
  from: 1,
  to: 5,

  [Symbol.asyncIterator]() { // (1)
    return {
      current: this.from,
      last: this.to,

      async next() { // (2)
        // note: we can use "await" inside the async next:
        await new Promise((resolve) => setTimeout(resolve, 1000)); // (3)

        if (this.current <= this.last) {
          const result = { done: false, value: this.current };
          this.current += 1;
          return result;
        }
        return { done: true };
      },
    };
  },
};

(async () => {
  for await (const value of range) { // (4)
    console.log(value); // 1,2,3,4,5
  }
})();
```

**Comment by ljharb** [comment]
@halitaydin why do you need a custom async iterator for a range of numbers, let alone one from 1 to 5?
```js
function range(from, to) {
  return Array.from({ length: to - from }, (_, i) => from + i);
}
range(1, 5)
```

If you have a concrete use case that actually makes sense as an iterator, sync or async, i'm happy to review it.

**Comment by halitaydin** [comment]
@ljharb I know I can use normal range function. But I have faced this issue when learning JavaScript on [https://javascript.info/async-iterators-generators](url) website.

I think I will never use this type of function but I just curious.

Thank you for your help.

**Comment by ljharb** [comment]
For learning how the language works, a style guide isn’t going to be super helpful. Use every part of the language to learn! A style guide helps you mitigate and avoid and minimize the bad parts, once you already know how they work.

**Comment by halitaydin** [comment]
I see, thank you for your advice.
