### ISSUE TITLE
Why complexity is off?

### ISSUE THREAD

**Issue by yeion7** [airbnb/javascript#1758]
Why the rule complexity is off by default?

https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/best-practices.js#L14

**Comment by ljharb** [comment]
In practice, it's not a very useful metric.

**Comment by yeion7** [comment]
Why is not useful?, in teory could evoid complexity, not?

**Comment by ljharb** [comment]
@yeion7 that's the theory. In practice, it doesn't really help.
