### ISSUE TITLE
Is it recommended to start a function name with is? Since it is not a typical verb 

### ISSUE THREAD

**Issue by dman777** [airbnb/javascript#1763]
When using a shortcut for a boolean variable, the example convention given is great:

```
// good
if (isValid) {
  // ...
}
```

I try to start all my named functions with a verb....a name to express it does something. 

In the case of a function that returns a Boolean, is it acceptable to start it with `is` like you would a true or false variable? The guide does not explicitly state but I was wondering if a personal preference could be given.  

```javaScript
const isValid = () => true;

if (isValid()) {
}
```

**Comment by ljharb** [comment]
Yes, I think that it's fine - ideal, even - to name predicates with an "is" or "has" prefix.

**Comment by dman777** [comment]
Thanks!
