### ISSUE TITLE
How can i use airbnb-eslint in my ejected create-react-app project?

### ISSUE THREAD

**Issue by mov1er** [airbnb/javascript#1764]
I had ejected my create-react-app project and installed "eslint-config-airbnb-base"

added .editorconfig,.eslintignore,.eslintrc.js three files in root catalog

![3](https://user-images.githubusercontent.com/16483316/37410498-be0da628-27db-11e8-93d7-90a1fe343bcc.png)

![0](https://user-images.githubusercontent.com/16483316/37411170-21d11cde-27dd-11e8-897d-4c8cc28519aa.png)

![1](https://user-images.githubusercontent.com/16483316/37411255-5d81f9ce-27dd-11e8-8030-8ebd5257183d.png)

![2](https://user-images.githubusercontent.com/16483316/37411283-6ede3372-27dd-11e8-8b00-b1461498cb76.png)

But it doesn't work,where goes wrong?

I guess some entries haven't been modified in somewhere?

**Comment by ljharb** [comment]
First, what does `npm ls` say? If that exits nonzero, nothing can be expected to work.

Second, you'll want to use eslint-config-airbnb (not "base") if you're using react.

**Comment by mov1er** [comment]
@ljharb npm start well and compiled successfully,don't have any warning or error

**Comment by ljharb** [comment]
@mov1er `npm ls`, not `npm start` - they're different.

**Comment by mov1er** [comment]
@ljharb  here it is
![_20180320194148](https://user-images.githubusercontent.com/16483316/37652523-c94a4a2e-2c76-11e8-981f-ecfde5a4eec1.png)

**Comment by ljharb** [comment]
So, all those errors are an indication that you have an incorrect dependency graph; if you run `npm prune` and then `npm ls`, what do you get?

**Comment by mov1er** [comment]
@ljharb 
Unhandled rejection RangeError: Maximum call stack size exceededill install loadIdealTree
 when I run npm prune

**Comment by ljharb** [comment]
@mov1er in that case, `rm -rf node_modules && npm install && npm ls`?

**Comment by mov1er** [comment]
@ljharb  I just did that, and the same situation ocurred when I run ` npm ls` or `npm prune`

**Comment by ljharb** [comment]
Can you copy/paste the *text* of the `npm ls` error? Screenshots of text are difficult to work with.

**Comment by mov1er** [comment]
@ljharb There are only 3 lines now.
npm ERR! peer dep missing: react-native@*, required by react-native-collapsible@0.9.0
npm ERR! peer dep missing: react-native@*, required by react-native-drawer-layout@1.3.2
npm ERR! peer dep missing: ajv@^6.0.0, required by ajv-keywords@3.1.0

**Comment by ljharb** [comment]
Looks like you need to add an explicit top-level dependency on `react-native` and `ajv`; but i didn't realize that CRA is compatible with react-native.

**Comment by philihp** [comment]
If [mov1er/cnode-react](https://github.com/mov1er/cnode-react) you're seeing this issue; when CRA ejects, it leaves some eslint configuration in your `package.json`:
```json
"eslintConfig": {
  "extends": "react-app"
}
```
Make sure you only specify your config in one location; either from `.eslintrc` or embedded in `package.json`.
