### ISSUE TITLE
Question regarding console log/warn/error

### ISSUE THREAD

**Issue by SimpleCookie** [airbnb/javascript#1765]
Hello, what is the practise regarding the console functions? It's strictly not allowed in production, sure. But what about pushing code with console functions to a Github repo. Is it considered fine to use them on dev and test environments?

**Comment by ljharb** [comment]
It's considered fine to use them in development; but not to commit code with them, no.

In directories that contain node-only scripts, it's a good idea to disable the `no-console` rule.

**Comment by SimpleCookie** [comment]
I can see there are committed bnb code with console logs. If it's not fine, why has it been done?

What is the motivation behind it having console functions committed? They'll be stripped from production anyways, and the help with debugging issues. 

Say you have a snippet function foo which takes bar as parameter. You always send in  bar, it shouldn't fail.
But you check if bar is defined anyways, and log a message if it's not. The log will only occur during development, if a developer has changed the behaviour of how foo is called. So then you'd know directly what goes wrong and where.

Sure you'll say stacktrace, but what if foo calls an API request with bar and returns a NPE without further information?
You could potentially spend quite a bit of time debugging. When it could actually have been avoided in the first place, at the cost of nothing.

**Comment by ljharb** [comment]
They definitely aren't stripped from production; I'm not sure where you'd get that idea. Can you show me where there's committed code with console.logs (that isn't node-only), and I can clean it up?

If it should never get an undefined "bar", it should *crash* - it should throw an exception, everywhere, and fail in production too. An exception is exceptional; having your program continue when things are in an unknown state can lead to wrong behavior.

The best solution to avoid spending time debugging is lots of automated tests, and making everything fail as fast and as loudly as possible, as often as possible.

**Comment by SimpleCookie** [comment]
I'm sorry I don't think I was clear enough. When I said "a github.com repo", I meant one in general. Say, if you're using uglify to strip console logs, would it be fine then?

The reason to why I am asking is because I want to understand to motivators behind this choice. But if they aren't stripped, then of course that would be a valid reason. I just assumed one would strip them for production. 

It might have been node.js, the react sketch has it if I remember correctly. So does https://github.com/airbnb/enzyme in multiple files. But I didn't pay attention to if it was node or not.

**Comment by ljharb** [comment]
react sketchapp is node-only; enzyme is a testing framework.

It’s always ok to override rules when they don’t make sense for you - but more bugs are caused (and information leaked) by allowing console statements in code, than debugging time is saved by doing so - so we choose to forbid them.

**Comment by SimpleCookie** [comment]
At first glance it sounds like a fair argument, but I have never experienced how a console.log can cause a bug? And I don't quite understand how a console.log would leak information considering it's all client-side. It's already there to begin with, so logging it or not makes no difference? If someone really wanted to retrieve that information, they could do so anyways.

I find this to be a interesting topic, so I appreciate your replies.

**Comment by ljharb** [comment]
For one, many versions of IE don't have `console` in production, so it crashes your entire webpage.

The issue with "leaking" is that developers often put in debugging information that shouldn't be available to users; eg, `console.log('this line is because Secret Project X needs it for the launch next month!')` - comments are almost always stripped by minification, but logging calls are almost always left intact.

**Comment by ljharb** [comment]
Every rule may depend on the project itself :-) however, I'd say that if you ship code to clients (eg browsers), then I would personally recommend you consider it an unbreakable rule.

**Comment by SimpleCookie** [comment]
Thank you @ljharb
