### ISSUE TITLE
Include "accumulator" in exceptions to no-param-reassign

### ISSUE THREAD

**Issue by naomiajacobs** [airbnb/javascript#1767]
We love the `acc` exception to `no-param-reassign`, found [here](https://github.com/airbnb/javascript/blob/90235cab7c060d69430001cf17aa28ff74da86b4/packages/eslint-config-airbnb-base/rules/best-practices.js#L175). However, we would love to also include "accumulator" as the full word carries more meaning and is more accessible for developers less familiar with JS idioms. We'd love to add this - what are your thoughts on us opening a PR with the change?

**Comment by naomiajacobs** [comment]
We went ahead and opened the PR in case y'all like the change! See https://github.com/airbnb/javascript/pull/1768

**Comment by ljharb** [comment]
Fixed by #1768.
