### ISSUE TITLE
Link to reddit/styleguide is broken

### ISSUE THREAD

**Issue by opennota** [airbnb/javascript#1769]
https://github.com/reddit/styleguide/ returns 404.

**Comment by ljharb** [comment]
This was added in https://github.com/airbnb/javascript/commit/a3a0af93ed84b2da231558efea02c5d66364ffb7 by @ajacksified - any idea what happened to reddit's styleguide repo?

**Comment by anshgoel99** [comment]
I think There is an error in the code

**Comment by kamronbatman** [comment]
FYI, it says on @ajacksified's profile that he no longer works for Reddit. He probably doesn't even know what happened.

**Comment by ljharb** [comment]
@kamronbatman i'm aware; he no longer works at airbnb either. I'm hoping he'll know someone still there who can check.

**Comment by ajacksified** [comment]
🤷‍♂️ I can ask around.

**Comment by marsonya** [comment]
The link has been removed in this PR #2362
