### ISSUE TITLE
Prefer default export not working for const variable

### ISSUE THREAD

**Issue by AjayPoshak** [airbnb/javascript#1786]
If I have single export in a file like this
```
export const url = "google.com";
```
It shows me linting error for prefer-default-export, but making it default would throw me this error
`Parsing error: Unexpected token const`

**Comment by ljharb** [comment]
Because that’s not a default export; if you want it default you’ll have to do it in two lines:
```jsx
const url = ‘google.com’;
export default url;
```

**Comment by AjayPoshak** [comment]
This solves my problem. Cool, thanks 🎉
