### ISSUE TITLE
Group export - yay or nay?

### ISSUE THREAD

**Issue by tpiros** [airbnb/javascript#1788]
I was wondering which one is better, to do a group export or do individual exports:

```javascript
export const a = 1;
export const b = 2;

// vs

const a = 1;
const b = 2;

export {
  a,
  b
}
```

**Comment by praveeno** [comment]
I like second one

**Comment by Bamieh** [comment]
for a few exports and a small file I use the second one. For a large file with only named exports I explicitly export each one to reduce mistakes.
