### ISSUE TITLE
The flag emojis don't show up on Windows

### ISSUE THREAD

**Issue by ParkSB** [airbnb/javascript#1789]
I think the idea of replacing flag images with emoji (#1787) is cool. 
However, Windows doesn't support national flag emoji yet, so it doesn't look intuitive in my environment.

![screenshot 2018-04-21 at 11 23 20](https://user-images.githubusercontent.com/6410412/39079501-19a95e08-4557-11e8-8b42-57c9932046a8.png)

I'm using Windows 10, Chrome 66.0.3359.117.

**Comment by ljharb** [comment]
Seems like maybe we need to revert #1787, until Github can fix its bug. @lencioni?
