### ISSUE TITLE
Perhaps allowing no-plusplus

### ISSUE THREAD

**Issue by zhujinxuan** [airbnb/javascript#1795]
I can understand the concern in https://github.com/airbnb/javascript/issues/540, but there is one advantage for ++ and --;

In JS, ++ and -- always returns number; therefore, JIT is always pleased to treak the result as int.  For +=1, the JIT may think the return can be a string.  

I know there are excessive trickiness for ++ or --; but I think we only need to disallow things like `array[index++] = ....`?

**Comment by ljharb** [comment]
This style guide requires you use array iteration methods, and largely forbids loops entirely - separately, JIT performance, while a nice bonus, is not a high priority when aiming for clean code.

Additionally, engines are able to optimize even some .forEach/.map/etc calls to be *just as fast* as a for loop, so in some cases this concern wouldn't even apply anyways.

**Comment by zhujinxuan** [comment]
Thanks @ljharb . I will close this issue.
