### ISSUE TITLE
Improves the map, reduce and filter lint error

### ISSUE THREAD

**Issue by sayedsaeedhosseini** [airbnb/javascript#1804]
Please improve the map, reduce and filter callback methods style guide.
If the line exceeds the maximum line length.

example:
```javascript
arr.map(
   currentValue => (
       /* some code comes here */
    )
)
```

**Comment by ljharb** [comment]
Although we enable the `max-len` rule, line length ends up being a really poor proxy for managing complexity. In the case you mention, I'd suggest overriding the `max-len` rule instead.

**Comment by ImanMh** [comment]
@sayedsaeedhosseini how about this: 

```
arr.map(currentValue => (
  /* some code comes here */
))
```

**Comment by sayedsaeedhosseini** [comment]
I think it`s better. 
```javascript
arr.map(
   currentValue => (
       /* some code comes here */
    )
)
```
@ljharb  @ImanMh  What is your mind?
