### ISSUE TITLE
Add `getSnapshotBeforeUpdate` to `exceptMethods` of `class-methods-use-this`

### ISSUE THREAD

**Issue by arcticicestudio** [airbnb/javascript#1805]
The new [`getSnapshotBeforeUpdate`][react-docs] `React.Component` lifecycle method, introduced in React 16.3, is currently [not listed in the `exceptMethods` array of the `class-methods-use-this` rule][code] (package `eslint-config-airbnb`).

This results in a error/warning when no `this` keyword is used within this method.

![gh-1805-preview](https://user-images.githubusercontent.com/7836623/39990737-aa4ed348-576d-11e8-91f3-72a5328f5b9b.png)

Besides, I think that the now deprecated lifecycles prefixed with `UNSAFE_` should be included too. If you agree the title of the issue should be adjusted.

I can submit a PR if this change is accepted.

[react-docs]: https://reactjs.org/docs/react-component.html#getsnapshotbeforeupdate
[code]: https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/react.js#L20-L33

**Comment by ljharb** [comment]
Thanks - I'll update the config for this rule when I update eslint-plugin-react, and also when I update the react version in "settings".
