### ISSUE TITLE
Which is more appropriate in a promise callback with a extra arg? function pointer or function

### ISSUE THREAD

**Issue by dman777** [airbnb/javascript#1810]
Which style is more appropriate when there is a extra argument in a callback? 

A function pointer using a bind to pass the extra arg:
```javascript
promise
  .then(foo.bind(this, bar))
```

Or a callback without using a function pointer:
```javascript
promise
  .then(foobar => foo(bar, foobar))
```

**Comment by ljharb** [comment]
The latter, primarily because `.bind` is often slow outside of super-modern v8 - but also because most functions don't need `this`, so in your example, the lack of reliance on `this` is more clear.

**Comment by dman777** [comment]
👍 Thanks!
