### ISSUE TITLE
To be fixed: string evaluates to false also when equals to "0"

### ISSUE THREAD

**Issue by grabmy** [airbnb/javascript#1814]
In the document, I see:

> Strings evaluate to false if an empty string '', otherwise true

Hum, actually, a string also evaluates to false if it is equal to "0". It should be added.
See https://codepen.io/anon/pen/LmaKaG?editors=0010#0

**Comment by ljharb** [comment]
See `if ('0') { console.log('y') } else { console.log('n') }`

**Comment by aboyton** [comment]
Well I've learnt something new, "Truthy values that actually `== false`". https://stackoverflow.com/questions/19839952/all-falsey-values-in-javascript

**Comment by ljharb** [comment]
From an IRC factoid: 
> The 'falsy' values in JavaScript are undefined, null, 0, -0, NaN, '', and false. The 'truthy' values are all other values. All objects are truthy. There is nothing both truthy and falsy, or neither truthy nor falsy.

**Comment by grabmy** [comment]
Ok nevermind, my bad.
It's just that when I make a condition with a non-boolean variable, you compare it to false.
I updated the codepen. Would be useful to have these informations in the document if it's not already the case
https://codepen.io/anon/pen/LmaKaG?editors=0010#0

**Comment by ljharb** [comment]
> I sometimes compare it to false

If you're going to do that with `=== false`, and that matches your intention, that's fine - but if you're checking that it's falsy, `if (!x)` is better.
