### ISSUE TITLE
How to style currying properly?

### ISSUE THREAD

**Issue by sstativa** [airbnb/javascript#1821]
Currying was mentioned here a couple times but I could find any clear explanation how to "style" it properly.

Consider this code for example

```js
let fn = a => b => c => {
  // there will be some complex logic
  console.log(a, b, c);
  return a + b + c;
}
```

ESLint throws the error **arrow-parens** `Expected parentheses around arrow function argument having a body with curly braces` and forces me to style the code this way (which looks a bit "off" and inconsistent to me)

```js
let fn = a => b => (c) => {
  // there will be some complex logic
  console.log(a, b, c);
  return a + b + c;
}
```

If I try to achieve consistency by using the following styling, I will get another error **arrow-parens** `Unexpected parentheses around single function argument having a body with no curly braces`

```js
let fn = (a) => (b) => (c) => {
  // there will be some complex logic
  console.log(a, b, c);
  return a + b + c;
}
```
Is there any "convention" on how to style curryed functions?

**Comment by ljharb** [comment]
That the functions are curried has no impact on what this guide recommends; the second example above is indeed the correct way.

**Comment by jacktuck** [comment]
@sstativa I agree with you there it looks inconsistent I prefer 1 and 3 over 2. That said that's just my opinion and all the rules here are naturally very opinionated xD
