### ISSUE TITLE
On React guide, put translation section at the top

### ISSUE THREAD

**Issue by jonatassales** [airbnb/javascript#1830]
I speak Portuguese as mother language and read the entire guide until realize there was a Portuguese translation for it.

**Comment by ljharb** [comment]
The phrase "This guide is available in other languages too. See [Translation](https://github.com/airbnb/javascript#translation)" appears at the top of the guide, is this not sufficient?

**Comment by jonatassales** [comment]
Skipped that! My bad. Maybe the flags are more appealing
