### ISSUE TITLE
Release notes?

### ISSUE THREAD

**Issue by olstenlarck** [airbnb/javascript#1835]
Heya! Just seen that there is new major versions for both. I highly depend on them and need to see what breaking. I can look over the comments to detect `[breaking]` but it would be more easier in bullet list.

**Comment by justinhp** [comment]
@olstenlarck Actually, they are here:
https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/CHANGELOG.md
https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/CHANGELOG.md

**Comment by ljharb** [comment]
Each package has a changelog file. Reviewing the commits is the best way - any release notes would be restating the commit messages, since all the changes involve upgrading deps and enabling/disabling rules.

**Comment by olstenlarck** [comment]
Ooooh.. yea yea. Forgot to check for changelogs :laughing: :rocket:
