### ISSUE TITLE
Clarification on PascalCase for filenames

### ISSUE THREAD

**Issue by andrewb273** [airbnb/javascript#1842]
I see that PascalCase is recommended for JSX component files

> **Filename:** Use PascalCase for filenames. E.g., ReservationCard.jsx.

However is this recommendation also for all non-JSX files? E.g. a file which just exports an instance of an object, like so:

    export const myObj = {};

Should this be `myObj.js` or `MyObj.js`? It'd be great to make it explicitly clear in the README.

**Comment by ljharb** [comment]
Yes, the naming conventions apply to all files.

As to your specific question - a default export is what a module *is*, and a named export is what a module *has*. The name should reflect what it is first, and what it has if there's no default export. What does your file conceptually export overall?

**Comment by andrewb273** [comment]
Thanks for the response, I meant for it to be a `default` and thus `myObj.js` would be a fair filename. Do you think it's worth clarifying this in the README, namely that the rule is applicable to not just .jsx files?

**Comment by ljharb** [comment]
Why are you default-exporting an object? What is the actual usage of your module?

The readme applies to all JavaScript; the [react guide](https://github.com/airbnb/javascript/tree/master/react) deals with react-specific things, like jsx.

**Comment by andrewb273** [comment]
import ClientConfig from "../models/be/ClientConfig";

    const element = document.getElementById('config');
    const config: ClientConfig = JSON.parse(element.innerText);
    export default config;

FYI I'm using TypeScript. It's a dynamic server-side render for the general configuration of the app (API endpoint etc), and I have a TS interface which automatically keeps up to date with the JSON render. This seemed like the simplest solution to me, even if it is mildly peculiar.

**Comment by ljharb** [comment]
ah ok - in this case, you're exporting a single item - not a namespace, but "data". So, I'd say a camelCase name is appropriate.

(React Components are constructed; and constructors use PascalCase)

**Comment by andrewb273** [comment]
Ok great. Thanks for the guidance!
