### ISSUE TITLE
[eslint-config-airbnb-base] DeprecationWarning

### ISSUE THREAD

**Issue by surfaceowl** [airbnb/javascript#1845]
I'm getting a new warning from `eslint-config-airbnb-base` after upgrading eslint to 5.0.1

(node:23992) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "node_modules\eslint-config-airbnb-base\index.js")

**devDependencies**
```
...
    "eslint": "^5.0.1",    
    "eslint-config-airbnb": "^17.0.0",
    "eslint-config-standard": "^12.0.0-alpha.0",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.9.1",
...
```

**Comment by mikeerickson** [comment]
I too am receiving this error, just added eslint-loader to webpack project this morning

Recommended fix?

```
Use 'parserOptions.ecmaVersion' instead. (found in "airbnb-base")
```

**Comment by ljharb** [comment]
eslint 5 is not yet compatible with the airbnb config (see #1834) - when `npm ls` exits nonzero, nothing can be expected to work.

**Comment by mikeerickson** [comment]
@ljharb Awesome, thanks for quick response, I will revert to ESLint 4.x for the time being.
