### ISSUE TITLE
Support for `getDerivedStateFromProps` lifecycle method

### ISSUE THREAD

**Issue by miachenmtl** [airbnb/javascript#1847]
I see that PR #1831 adds support for new React 16.3 lifecycle methods. However, I don't see `getDerivedStateFromProps` on the list. Could it be added? (My particular issue is with `class-methods-use-this`.)

**Comment by arcticicestudio** [comment]
[`getDerivedStateFromProps`][docs] is already a `static` function which is man purpose of the `class-methods-use-this` rule:

> If a class method does not use this, it can sometimes be made into a static function.

[docs]: https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops

**Comment by ljharb** [comment]
indeed, static methods never need to use `this`; so gDSFP doesn't apply.
