### ISSUE TITLE
react/sort-comp: getDerivedStateFromProps 

### ISSUE THREAD

**Issue by devourment77** [airbnb/javascript#1850]
After updating to v17, I am getting 'getDerivedStateFromProps should be placed after componentDidUpdate`.  I want to say previously in v16 the rule was below the constructor... does the new placement make sense?

**Comment by ljharb** [comment]
Yes - the bug was in eslint-plugin-react (you'd see the change on v16 as well, with a fully updated eslint-plugin-react). Specifically, gDSFP is both a static method and a lifecycle method, and the sorting logic was wrong.

See https://github.com/yannickcr/eslint-plugin-react/pull/1795 / https://github.com/yannickcr/eslint-plugin-react/issues/1793

**Comment by ljharb** [comment]
Ooh, good call - we do override the defaults.

I think the change (which would still have shown up in v16) is that gDSFP in "statics" vs "lifecycle" changed.

In other words, `gDSFP` moved from "everything-else" to "statics" in eslint-plugin-react. We could/should add it to `lifecycle`, but that would still result in it appearing above the constructor.

**Comment by devourment77** [comment]
Okay cool.  I was in refactor mode with my npm updated and was hoping not to have to move em around again too much.

Do you think the order will change at all for 17.x (even if it is just to match the react plugin)?  

Internally debating if I delay the class method shuffle or not.

Appreciate all the feedback and thanks for your time on my isssues / questions today!

**Comment by ljharb** [comment]
I do not expect the ordering to change further (although there may be new React lifecycle methods added to the "lifecycle" group)

**Comment by devourment77** [comment]
To be clear, you do see it moving to statics right?  Not below componentDidUpdate (my current error, plugin is updated).

**Comment by ljharb** [comment]
Since `lifecycle` is primarily for instance methods, i think it would be in "statics"
