### ISSUE TITLE
eslint: experimentalObjectRestSpread option is deprecated

### ISSUE THREAD

**Issue by bugeats** [airbnb/javascript#1870]
Using eslint `v5.1.0`:

> DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in eslint-config-airbnb/node_modules/eslint-config-airbnb-base/index.js")

I care because this deprecation message is screwing up my editor.

**Comment by ljharb** [comment]
We don't support eslint 5 yet - see #1834 - so your dependency graph is invalid. Until `npm ls` exits zero, you can't rely on anything to work.

Downgrade to v4 in the meantime, and then your dependencies won't be invalid, and you won't get any deprecation messages.
