### ISSUE TITLE
Possible mistake in example 4.7 Use return statements in array method callbacks

### ISSUE THREAD

**Issue by EddyVinck** [airbnb/javascript#1872]
[4.7](https://github.com/airbnb/javascript#arrays--callback-return) Use return statements in array method callbacks.

`acc[index] = flatten;` makes no difference for the output in the second (good) example. Should this line be removed or am I missing something here?

This is currently in the docs. 
```js
// bad - no returned value means `acc` becomes undefined after the first iteration
[[0, 1], [2, 3], [4, 5]].reduce((acc, item, index) => {
  const flatten = acc.concat(item);
  acc[index] = flatten;
});

// good
[[0, 1], [2, 3], [4, 5]].reduce((acc, item, index) => {
  const flatten = acc.concat(item);
  acc[index] = flatten; 
  return flatten;
});
```

I am suggesting this:
```js
// better?
[[0, 1], [2, 3], [4, 5]].reduce((acc, item) => {
  const flatten = acc.concat(item);
  return flatten;
});
```

I can make a PR if you want.

**Comment by ljharb** [comment]
The mutation of `acc` isn't really the issue; the point of the example is to show the added `return`.

The `concat` isn't actually necessary at all; it's the mutation and the return that matters.

**Comment by EddyVinck** [comment]
Makes sense. I guess I was looking too much into the code and forgot what the purpose of the examples was.
