### ISSUE TITLE
label-has-for deprecated in 6.1

### ISSUE THREAD

**Issue by merlinpatt** [airbnb/javascript#1873]
In `jsx-a11y`, `label-has-for` is now deprecated as of 6.1.

https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/label-has-for.md

I believe it has been replaced entirely by [label-has-associated-control](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/v6.1.0/docs/rules/label-has-associated-control.md)

**Comment by ljharb** [comment]
Yes, this has already been handled with 7dda84a335f5903d72c9423dc17f33f2c9813d2a.

We'll be leaving both rules enabled for the time being.

**Comment by tuanalumi** [comment]
Are you considering to remove `label-has-for`? The rule is incorrect, as both `nesting` and `id` are required. This might produce an error on this markup:

```html
<input type="file" id="inputGroupFile01" />
<label htmlFor="inputGroupFile01">Choose file</label>
```

**Comment by ljharb** [comment]
I'm confused by your comment, since that markup *should* error, as it's incorrect - both nesting and ID must be required.

**Comment by tuanalumi** [comment]
I didn't know that both of them are really required, because I know that either `id` or `nesting` is enough to make the input get focused when clicking on label. But I might not know about a11y.

Related issue in `eslint-plugin-jsx-a11y` repo: https://github.com/evcohen/eslint-plugin-jsx-a11y/issues/314#issuecomment-326756926

**Comment by ljharb** [comment]
Unfortunately either is not enough, on every device. For example, Dragon (a11y software) requires linking and ignores nesting, and many other assistive devices require nesting and ignore linking.

Both are required.

**Comment by fergusjordantw** [comment]
@ljharb is there a specific reason `label-has-for` and `label-has-associated-control` are both still enabled? Is it possible to remove the deprecated `label-has-for`?

**Comment by ljharb** [comment]
@fergusjordantw i plan to remove the deprecated one in the next semver-major.
