### ISSUE TITLE
What is the cleanest way to build multi-line strings?

### ISSUE THREAD

**Issue by chrisngobanh** [airbnb/javascript#1876]
As the title mentions, what do you all think is the cleanest way to build an multi-line string.

For example, what if I want to define a function that builds a multiline string that looks like the following:
```
Your groups:
Group1
Group2
```

Here are examples of ways I was considering accomplishing this:
(The function in the example is necessary to show how strange the indentation in code will look for template strings)

```
function doSomething() {
  const text = 'Your groups:'
    + '\nGroup1'
    + '\nGroup2';
  return text;
}
```
vs

```
// Subsequent lines in the string have no indent in code because we don't want indents in the string
function doSomething() {
  const text = `Your groups:
Group1
Group2`;
  return text;
}
```

**Comment by chrisngobanh** [comment]
Other example is putting the strings into an array and then joining:
```
function doSomething() {
  const text = ['Your groups', 'Group1', 'Group2'].join('\n');
  return text;
}
```

**Comment by ljharb** [comment]
Joining an array is a legacy hack from when that was faster in ancient browsers; in anything even remotely modern, there's not a huge benefit.

A template literal is the proper way to build a multiline string. There's tagged template literal libs like https://www.npmjs.com/package/dedent and https://www.npmjs.com/package/deline tho, that can make this cleaner.

**Comment by ljharb** [comment]
Closing; this seems answered.

**Comment by ugultopu** [comment]
@chrisngobanh If you are okay with using a Babel plugin, I [developed a Babel plugin named "Dedent Template Literals"](https://github.com/ugultopu/babel-plugin-dedent-template-literals) that does just that. Example:

```javascript
const httpRFC = `                Hypertext Transfer Protocol -- HTTP/1.1

                 Status of this Memo

                    This document specifies an Internet standards track protocol for the
                    Internet community, and requests discussion and suggestions for
                    improvements.  Please refer to the current edition of the "Internet
                    Official Protocol Standards" (STD 1) for the standardization state
                    and status of this protocol.  Distribution of this memo is unlimited.

                 Copyright Notice

                    Copyright (C) The Internet Society (1999).  All Rights Reserved.`;

console.log(httpRFC);
```

Will print:

```
                Hypertext Transfer Protocol -- HTTP/1.1

Status of this Memo

   This document specifies an Internet standards track protocol for the
   Internet community, and requests discussion and suggestions for
   improvements.  Please refer to the current edition of the "Internet
   Official Protocol Standards" (STD 1) for the standardization state
   and status of this protocol.  Distribution of this memo is unlimited.

Copyright Notice

   Copyright (C) The Internet Society (1999).  All Rights Reserved.
```

The reason I developed this plugin is because "the right way" of solving this problem is at the compile-time. That is, before this plugin, I used do just what you did. I was putting the lines in an array and joining them with a newline:

```javascript
[
  '                Hypertext Transfer Protocol -- HTTP/1.1',
  '',
  'Status of this Memo',
  '',
  '   This document specifies an Internet standards track protocol for the',
  // etc.
].join('\n')
```

Code formatting-wise, this was the cleanest solution because you can indent each element of the array as you wish. However, this results in the code running in run-time to do something, where everything for that operation is known at the compile (development) time. Hence, this is _not_ "the right way" of solving this problem. Another issue was that instead of just using template literals, I had to use a "hack" like putting each line in an array and joining them at run-time. This meant extra code and extra typing. Hence, I developed this plugin.

**Comment by ljharb** [comment]
You don’t need a babel plugin for this: https://npmjs.com/dedent

**Comment by ugultopu** [comment]
@ljharb Doesn't that do it by running the string through a function, hence at run-time? The purpose of my plugin is to do it as compile-time, since no run-time information is required for this.

**Comment by ljharb** [comment]
Yea, fair enough.

**Comment by ugultopu** [comment]
@ljharb Also, with the software that you linked, you have to prepend all your template literals with `dedent`, whereas with my Babel plugin, you don't need to prepend them with anything. You would just type your template literals as you did before, and the leading whitespace would be removed at compile time. This means cleaner code.

**Comment by ljharb** [comment]
It means more magic/implicit code, and you may not *want* every template literal dedented. “Less code” isn’t the same as “cleaner”.

**Comment by ugultopu** [comment]
@ljharb Right, it is more "magic", just like using JSX is magic, or using ES-next features now is magic. In addition to enabling you to write cleaner template literals, there is nothing that my plugin cannot accomplish where conventional template literals do. For example, with the conventional template literals:

```javascript
function f() {
  const str = `This
is
a multi-line
  string that
spans
    over lines`;
}
```

With my plugin, it is just:

```javascript
function f() {
  const str = `This
               is
               a multi-line
                 string that
               spans
                   over lines`;
}
```

Much more easier to understand at a glance.

However, I agree that it can be a challenge to integrate it into an already existing codebase, if there are a lot of multi-line template literals in it. On a fresh repository though, no issues whatsoever.
