### ISSUE TITLE
From the source code to the execution?

### ISSUE THREAD

**Issue by ahmedbenammar029** [airbnb/javascript#1881]
reading from different ressources really got me lost , can you please guide me through these steps :

1- source code

2- compiler :

===> 1-Hoisting , set variables to undifined and functions to ( ??? i don’t know )
===> 2-declare a var or a function after a validation from the scope engine
===> 3-tokenize our code
===> 4-create AST
===> 5-convert source code to byte code

3- execution context (done with the compiler, now the engine turn : V8 or spidermonkey … ) :

var age = 30 ;

here the engine ;

----------------- the creation phase of the execution context --------------------

===> 1 : create a property in the "Global "variable object nammed age and set the value to undifined
===> 2 : check with the scope engine
===> 3 : determine the value of ‘this’ (unnecessary here )

------------------ the execution phase ---------------------------------------

the engine assign a LHS referrence to the age variable

**Comment by ahmedbenammar029** [comment]
can you pelase guys respond i can't really move forward from this point

**Comment by ljharb** [comment]
This repo is a style guide for JavaScript; you seem to be asking how JavaScript engines might work, which is a more general question - this really isn't the right venue for this.

Either way, the answer will be unique to a single implementation, and won't be helpful in a generic sense.
