### ISSUE TITLE
JSX bracket indent issue

### ISSUE THREAD

**Issue by pdyx2828** [airbnb/javascript#1886]
code: 

```jsx
const a = (
  <Component
    props={(
      <ol>
        <li>1</li>
        <li>1</li>
        <li>1</li>
      </ol>
)} // <== no error reported, expect 4 spaces
  />
);
```

after remove `'JSXExpressionContainer'` from `ignoredNodes` of indent's option, eslint report error correctly

**Comment by ljharb** [comment]
This should be handled by eslint-plugin-react's `jsx-indent` rule; please file an issue there.
