### ISSUE TITLE
[ESLINT_LEGACY_OBJECT_REST_SPREAD]

### ISSUE THREAD

**Issue by kmaitski** [airbnb/javascript#1888]
Hey I was following #1834  since I was getting the same warning.  I have since upgraded to the latest airbnb config and eslint hoping that it would solve the issue for me, but I am still getting the same message.  I have run the peer deps install command for `eslint-config-airbnb`.  When I run `npm ls` I get what looks like a huge dependency tree/graph.  My .eslintrc is inside of my package.json and looks like this:
```
"eslintConfig":{  
        "parser": "babel-eslint",  
        "plugins": [  
            "react"  
        ],  
        "rules": {  
            "import/extensions": "off",  
            "import/no-unresolved": "off"  
        },  
        "extends": [  
            "airbnb-base",  
            "plugin:react/recommended"  
        ],  
        "env": {  
            "browser": true  
        }  
    }
```

And my dev dependencies are:
```
        "eslint": "^5.3.0",  
        "eslint-config-airbnb": "^17.1.0",  
        "eslint-config-airbnb-base": "^13.1.0",  
        "eslint-loader": "^2.1.0",  
        "eslint-plugin-import": "^2.14.0",  
        "eslint-plugin-jsx-a11y": "^6.1.1",  
        "eslint-plugin-react": "^7.11.1"
```

And the warning message is: `(node:2750) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "airbnb-base")`

If anyone has any information I would be very appreciative.

**Comment by ljharb** [comment]
if you look in `node_modules/eslint-config-airbnb-base/package.json`, what is the version listed?

Separately, why are you extending airbnb-base and react, when you have the main "airbnb" config available?

Try changing your config to this:
```js
"eslintConfig": { 
        "extends": [  
            "airbnb"
        ],
        "parser": "babel-eslint",
        "rules": {  
            "import/extensions": "off",  // these should really be on, though
            "import/no-unresolved": "off"  
        },
        "env": {  
            "browser": true  
        }  
    }
```

**Comment by kmaitski** [comment]
After that change this is the new output: `(node:3070) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "../../../../usr/local/lib/node_modules/eslint-config-airbnb/node_modules/eslint-config-airbnb-base/index.js")
(node:3070) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "airbnb-base")`

**Comment by ljharb** [comment]
ahhh that looks like you've got those installed globally. Run `npm uninstall -g eslint`, and make sure you're running the *local* eslint.

**Comment by kmaitski** [comment]
Awesome thank you so much!  It is working as it should now.  Thanks again!
