### ISSUE TITLE
special objects like regex

### ISSUE THREAD

**Issue by stevemao** [airbnb/javascript#189]
Hi, how come no one mentions about regex? I see people using re to prefix a regex object.

Also the best practice to write Date etc..

**Comment by goatslacker** [comment]
What do you mean by best practice to write Date?

Are you referring to something like `+new Date()`, `Date.now()`, etc...?

**Comment by stevemao** [comment]
naming conventions for regex. such as `rtrim` and `rmsPrefix`

How should i name my dates? `dateCurr`, `dateTmr`?

**Comment by goatslacker** [comment]
We don't have an opinion on naming besides avoiding single letter names: https://github.com/airbnb/javascript#naming-conventions

**Comment by ljharb** [comment]
We don't use [hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation) at Airbnb, with the sole exception of variables containing jQuery objects.

As always, feel free to fork the style guide and make your own changes!
