### ISSUE TITLE
Add more clarity around nested conditionals

### ISSUE THREAD

**Issue by dmayerdesign** [airbnb/javascript#1892]
In the section on control statements (https://github.com/airbnb/javascript#control-statements) you give the following example for a correctly nested `if` in the event that your conditions have really long names. Here's the code from that section:

```
// good
if (
  (foo === 123 || bar === 'abc')
  && doesItLookGoodWhenItBecomesThatLong()
  && isThisReallyHappening()
) {
  thing1();
}
```

But what if your _nested_ condition has really long variable names too? E.g.
```
if (
  (whatIfTheseVariablesHadUneccessarilyLongNames === 123 || andYouDidntWantToExtractThemIntoAFunction === 'abc')
  && doesItLookGoodWhenItBecomesThatLong()
  && isThisReallyHappening()
) {
  thing1();
}
```

I would assume/suggest the following:
```
if (
  (
    whatIfTheseVariablesHadUneccessarilyLongNames === 123
    || andYouDidntWantToExtractThemIntoAFunction === 'abc'
  )
  && doesItLookGoodWhenItBecomesThatLong()
  && isThisReallyHappening()
) {
  thing1();
}
```

But is that assumption correct? Of course, 99% of the time the correct answer is to turn them into a function and avoid awkward, hard-to-read if statements, but they are _sometimes_ necessary.

Thanks in advance!

**Comment by ljharb** [comment]
Yes, that assumption is correct :-)

**Comment by dmayerdesign** [comment]
Thanks for the prompt response, @ljharb! And thanks to you and your team for this awesome style guide.
