### ISSUE TITLE
Configuration for rule "react/jsx-no-bind" is invalid:

### ISSUE THREAD

**Issue by liuzhiyang0113** [airbnb/javascript#1893]
./src/index.js
Module build failed: Error: /Users/mac/Desktop/study/eject-study/demo3/node_modules/eslint-config-airbnb/rules/react.js:
	Configuration for rule "react/jsx-no-bind" is invalid:
	Value "[object Object]" should NOT have additional properties.

Referenced from: /Users/mac/Desktop/study/eject-study/demo3/node_modules/eslint-config-airbnb/index.js
Referenced from: /Users/mac/Desktop/study/eject-study/demo3/.eslintrc.js
    at Array.forEach (<anonymous>)
    at Array.reduceRight (<anonymous>)
    at Array.reduceRight (<anonymous>)

**Comment by ljharb** [comment]
What does `npm ls` say? If that exits nonzero then your dependency graph is invalid, and nothing can be expected to work.

**Comment by liuzhiyang0113** [comment]
that is not say.but i add  extends: ['airbnb']  to .eslintrc.js ,it can not build.

**Comment by ljharb** [comment]
@liuzhiyang0113 yes, i understand that. but i'm saying that's only the case if you have incompatible versions of `eslint-config-airbnb` and `eslint-plugin-react` installed, which `npm ls` will show you.

**Comment by liuzhiyang0113** [comment]
thank you , Sir,it's useful to me.

**Comment by dherault** [comment]
I too have this error since I updated my dependencies. Here is my package.json file:
```
    "eslint": "^5.4.0",
    "eslint-config-airbnb": "17.1.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-react": "^7.11.1"
```
Reverting to `"eslint-config-airbnb": "17.0.0",` removes the error.

**Comment by ljharb** [comment]
@dherault if using v17.1 you `rm -rf node_modules && npm install`, do you still get the error? Where do you get the error? If in your editor or bundler, can you try on the command line?

**Comment by gurbraj** [comment]
I am getting this same error after following this tutorial up to ejecting (npm run eject):

https://medium.freecodecamp.org/setting-up-internationalization-in-react-from-start-to-finish-6cb94a7af725

**Comment by ljharb** [comment]
@gurbraj i don't believe CRA is trivially compatible with our config; you probably need to adjust a bunch of version numbers after ejecting to make it work.

**Comment by laureen71** [comment]
Removing node_modules directory and running `npm install` fixed it for me.

**Comment by youdy** [comment]
Same problem here, anyone manage a fix?

**Comment by zebrallel** [comment]
it fixed for me when i use old eslint version

  "eslint": "4.10.0",
  "eslint-config-airbnb": "13.0.0",
  "eslint-config-react-app": "^2.1.0",
  "eslint-loader": "1.9.0",
  "eslint-plugin-flowtype": "2.39.1",
  "eslint-plugin-import": "2.8.0",
  "eslint-plugin-jsx-a11y": "2.2.3",
  "eslint-plugin-react": "7.4.0",

**Comment by kaflan** [comment]
@zebrallel 
How to fix. Can you tell steps for me. How fixed please =)

**Comment by krazyjakee** [comment]
@zebrallel your version of eslint works for me. Eslint `5.3.0` did not.

**Comment by ljharb** [comment]
@kaflan @krazyjakee make sure `npm ls` passes; to do this, use the install peerdeps command on the readme of eslint-config-airbnb. It should work fine with eslint 5.

**Comment by filipegorges** [comment]
@kaflan @krazyjakee I was having the same issue as you guys, and following what @ljharb said, I was able to fix my problem with `npx install-peerdeps --dev eslint-config-airbnb`, as stated on the [readme of eslint-config-airbnb](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb). 

I'm guessing some defaults were overwritten during eject, so reapplying the settings did the trick :)

**Comment by agurtovoy** [comment]
Generally speaking, @gurbraj is correct:
> i don't believe CRA is trivially compatible with our config

That said, if you are determined to make it work, here's how to do it:
 - Examine your `yarn.lock` file / `npm ls` output to find what versions of `eslint` / `eslint-plugin-react` (and any other plugins that are giving your grievance) are required by your version of `react-scripts` (the CRA's underlaying engine).
 - Go through `eslint-config-airbnb` version listed on https://www.npmjs.com/package/eslint-config-airbnb and run `npm info "eslint-config-airbnb@x.x.x" peerDependencies` for each version that you think might work to find the best match.
- Install the correct versions of each package taken from the "best match" output.

For `react-scripts@1.1.5`, the above leads to the following "best match":
```
  "devDependencies": {
    "eslint": "^4.10.0",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^6.0.2",
    "eslint-plugin-react": "^7.4.0",
```

**Comment by ljharb** [comment]
@biosboy what does npm ls print out?
