### ISSUE TITLE
Consider turn on the Rules those StandardJS did

### ISSUE THREAD

**Issue by kaiye** [airbnb/javascript#1900]
I recently compared the configuration of Airbnb and StandardJS and found that, if the following rules enabled may help make the code clearer and less error-prone.
[https://sqren.github.io/eslint-compare/](https://sqren.github.io/eslint-compare/)

* no-extra-parens
* accessor-pairs
* no-unmodified-loop-condition
* no-useless-call
* handle-callback-err

**Comment by ljharb** [comment]
This guide does not allow accessors or mutators, so accessor-pairs wouldn’t provide value - same with loops and no-unmodified-loop-condition.

handle-callback-err is node-specific, is very hard to lint properly, and is unnecessary now that promises exist.

no-useless-call can have false positives or negatives - not everything with a call or apply property is a function.

As for no-extra-parens, there are cases where parens are helpful for readability - and such a rule would destroy information the programmer intended to leave behind.

**Comment by kaiye** [comment]
@ljharb Thank you for your guidance. In order to make other people with the same confusion more clear, let me try to explain it again. See if I understand correctly.

**accessor-pairs**
https://github.com/airbnb/javascript#accessors
`24.2 Do not use JavaScript getters/setters as they cause unexpected side effects and are harder to test, maintain, and reason about. `

**no-unmodified-loop-condition**
use Array filter/map/reduce methods and  custom loop function, such as `times(3, ( )=>{ … })`, instead of a for-loop.

**handle-callback-err**
use `util.promisify()` to convert the callback-based function like fs.readFile() to the Promise-based function, then resolve errors in the catch() block, or use try…catch with async/await.

**no-extra-parens**
`Sometimes parens are helpful for readability`, I agree.
StandardJS has a `functions` option configured in this rule. The parentheses outside the function seem to make the code look less readable.

**no-useless-call**
From the official docs of [eslint](https://eslint.org/docs/rules/no-useless-call), I don't see the negative effects of this rule. Can you give some examples?

**Comment by ljharb** [comment]
It could have false positives or false negatives - any object could have a function called “call” or “apply” - and it’s impossible for eslint to reliably know statically that a given variable is a function.

**Comment by ljharb** [comment]
Closing; please open specific issues or PRs for each rule you'd like to enable (that hasn't been addressed above).
