### ISSUE TITLE
"0:0 error Module Error [...]" when using with webpack

### ISSUE THREAD

**Issue by Bardyl** [airbnb/javascript#1909]
Hello,

Using this in my `package.json` file :  
```
    [...],
    "babel-eslint": "^9.0.0",
    "eslint": "^4.16.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-loader": "^2.1.0",
    "eslint-plugin-import": "^2.8.0",
    "webpack": "^4.17.1",
    [...]
```

and this in my `.eslintrc`:
```
{
    "parser": "babel-eslint",
    "rules": {
        [...]
    }, 
    "globals": {
        [...]
    }
    "extends": "airbnb-base"
```

It seems there is a bug when using `webpack --mode development` (even in production mode). It returns me this:

```
./assets/javascripts/forum.es6
  0:0  error  Module Error (from ./node_modules/eslint-loader/index.js):

./assets/javascripts/global.es6
  0:0  error  Module Error (from ./node_modules/eslint-loader/index.js):

✖ 2 problems (2 errors, 0 warnings)


npm ERR! Linux 4.15.17-1-pve
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! humanoid-redesign@3.0.0 dev: `webpack --mode development`
npm ERR! Exit status 1
```

It's not a problem with my es6 files: if I remove their content, the problem is still there.

If I remove the `airbnb-base` line in my `.eslintrc` config file, everything works fine.

Maybe it can be a problem with Eslint directly, but i'm really not sure after trying to remove `airbnb-base` in my `.eslintrc` file.

Thanks for any help with this.

**Comment by ljharb** [comment]
I'm not sure what eslint-loader is, but I would strongly discourage from running the linter as part of your build process.

Separately, try moving the "extends" in your config up to the top - before your rule overrides.

**Comment by jaythomas** [comment]
This doesn't look like it's related to the airbnb configuration at all.

@Bardyl those look to be linting errors in your application (`./assets/javascripts/forum.es6` and `./assets/javascripts/global.es6`) as the error message says and they're being collected and emitted by eslint-loader as part of your webpack process.

@ljharb there is nothing wrong with linting as part of your webpack process. It can help development greatly. Moving the key in the object won't do anything either as the order of keys in the object is completely arbitrary from eslint's point of view.

**Comment by Bardyl** [comment]
Thanks for your help @jaythomas!

I'm ashamed. I didn't try to run ESLint on my files. And yes, there were problems with them (an import which works fine before, but I removed it and now, compilation works fine).

But this is not answering to the main problem: why the error reported is focused on line `0:0` with no reason? With Webpack 3, I had the correct reason with info with the line causing the problem.

It seems this is happening only with my root .es6 files. If I put a JS error (a `aaa` string on top of required file), the error is well returned (even if I have strange new line returns)

```
./assets/javascripts/blocks/Search.es6
  21:37  error  Module Error (from ./node_modules/eslint-loader/index.js):
                /var/www/blogs/wp-content/themes/humanoid-redesign/assets/javascripts/blocks/Search.es6
                error  Expected an assignment or function call and instead saw an
                expression  no-unused-expressions   1:1  error  'aaa' is not
                defined                                                   no-undef
                1:4  error  Missing
                semicolon                                                      semi
                3:1  error  Import in body of module; reorder to
                top                               import/first   4:1  error  Import in
                body of module; reorder to top
                import/first  ✖ 5 problems (5 errors, 0 warnings)   3 errors, 0
                warnings potentially fixable with the `--fix` option.

✖ 1 problem (1 error, 0 warnings)
```

I can provide more information if this can help to solve any issue.

**Comment by jaythomas** [comment]
Unfortunately I don't have an answer. I'm assuming your eslint-loader version is the latest? This really seems like either a conflict with loaders/plugins or it is a bug in eslint-loader itself. You may want to open an issue on the [eslint repo](https://github.com/webpack-contrib/eslint-loader) and provide your entire webpack.config.js so that others can reproduce your issue.

Since you mentioned it only affects files in the root of your context folder, so as a workaround you may want to just make an entry file with nothing in it but a require/import that loads your current index file so that it can be linted.

**Comment by Bardyl** [comment]
Thanks for your help. I'll make more tests based on lasts conclusions and I'll go on right repo if necessary :).

**Comment by ljharb** [comment]
@jaythomas what's "wrong" is that your entire website stops working when you have a linting error, which introduces unnecessary friction, and encourages linting *less* so that it obstructs your build less - when in fact, you should be linting as much as possible.

You're right about the order of the config keys :-)

**Comment by stevemao** [comment]
`no-underscore-dangle`. Sometimes it's not possible with third party libs

In some folders I have to do:

```js
"import/prefer-default-export": "off",
"import/no-default-export": "error"
```
