### ISSUE TITLE
Opposite behavior of the rule 'one-var'

### ISSUE THREAD

**Issue by lukeZhangMengxi** [airbnb/javascript#1911]
Hi, I applied the rule 13.2 eslint: one-var

and I got the opposite response from ESLint as your description.

If I have the code below, 
```js
// good
const items = getItems();
const goSportsTeam = true;
const dragonball = 'z';
```
I would get errors/warnings:
`eslint: one-var - Combine this with previous const statement`

And the code below seems what the rule wants
```js
// bad
const items = getItems(),
  goSportsTeam = true,
  dragonball = 'z';
```

**Comment by ljharb** [comment]
I'm confused; I wouldn't expect `one-var` to apply to const/let, but also we have it [configured](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/style.js#L410) to "never", which requires *multiple* declarations.

**Comment by lukeZhangMengxi** [comment]
Oh, ok I configured it to warn. Thanks!

**Comment by ljharb** [comment]
It should not be necessary to do that; when extending airbnb's config you simply need to not configure it yourself, and it should require the "good" code.
