### ISSUE TITLE
README - Question about Modules

### ISSUE THREAD

**Issue by jvrdom** [airbnb/javascript#1912]
On the section of modules (https://github.com/airbnb/javascript#modules) suggest that the best way to export/import is like this:

```javascript
import { es6 } from './AirbnbStyleGuide';
export default es6;
```

But I tested and I saw that you export as ```default``` so, why do you import as a named import? If you do what is defined in the documentation you will get undefined on ```es6``` 

Is that okey? Or is just an example?

Thanks :)

**Comment by ljharb** [comment]
In this example (which yes, is just an example) the file doing `export default` is different than `AirbnbStyleGuide`, so presumably there's a named export in that file.
