### ISSUE TITLE
函数封装传参问题

### ISSUE THREAD

**Issue by menciusKael** [airbnb/javascript#1915]
![image](https://user-images.githubusercontent.com/29659731/45470881-e8307280-b761-11e8-8877-5e6c720f2928.png)
![image](https://user-images.githubusercontent.com/29659731/45471034-642aba80-b762-11e8-976e-c1159e3f42b0.png)
![image](https://user-images.githubusercontent.com/29659731/45471096-9a683a00-b762-11e8-9cff-4d315fdf7f75.png)
![image](https://user-images.githubusercontent.com/29659731/45471590-23cc3c00-b764-11e8-8eb4-b1f0f28206a8.png)
现在这样封装，写的代码还是太多，主要在那一堆参数，可以再怎么优化封装一下？？求指点

**Comment by ljharb** [comment]
I can't translate screenshots of text; and the translation of the text that's here doesn't seem helpful.
