### ISSUE TITLE
Use of classes in javascript ?

### ISSUE THREAD

**Issue by ShintaroNippon** [airbnb/javascript#1921]
Hi there!
Can one explain me please if i should use classes in javascript or using prototype...
I have this doubt.
Can someone clarify this point in 2018...

Thanks in advance.
Carlos VIeira

**Comment by ljharb** [comment]
If you are using inheritance (`new` or `this` or prototypes), *only* use `class` (when using babel or targeting new enough engines), since 2014 or so.

Also, prefer composition over inheritance.
