### ISSUE TITLE
Is "[eslint] Do not use 'new' for side effects. (no-new)" rule still correct for singleton class?

### ISSUE THREAD

**Issue by RonWang** [airbnb/javascript#1925]
I have created a singleton class as an application level cache to fulfil my business logic. Since it's a singleton, I just need to instantiate the class using "new" at the start of my application.
```
new ConfigSingleton(configFilePath);
```
Is this a valid use case of using new here, since I treat the class as singleton?

**Comment by ljharb** [comment]
No, it’s not, that should be a function instead of a class.
