### ISSUE TITLE
Best way to deal with `operator-linebreak` and long line length

### ISSUE THREAD

**Issue by KayakinKoder** [airbnb/javascript#1926]
In a few places where code is indented a bit and we have something like this: `myObject.ProbablyTooLong.PropertyName = somethingElse.That.IsLong;`

We had previously broken the line up to avoid `max-len` violations:
```
myObject.ProbablyTooLong.PropertyName
       = somethingElse.That.IsLong;
```

A recent update now gives us `operator-linebreak` errors, `There should be no line break before or after '='`

Does anyone have suggestions on best practice here? Thank you

**Comment by ljharb** [comment]
I'd disable the `max-len` rule for this case; line length is a poor proxy anyways for managing complexity.

Our guide also discourages mutation - what object are you deeply modifying?

**Comment by KayakinKoder** [comment]
As always, thanks, I'll have to do some reading on how to avoid mutations.
