### ISSUE TITLE
Webpack config function executing multiple times when using `resolve.alias` and `eslint-import-resolver-webpack`

### ISSUE THREAD

**Issue by andreyvolokitin** [airbnb/javascript#1932]
### Description

If `webpack.config.js` represents config as a function with `resolve.alias` defined, and when we `import`/`require` this alias later in the code while using `eslint-import-resolver-webpack` for resolving imports in eslint, then webpack config function executing additionally multiple times: one time for each `import` with alias. It happens when `.eslintrc.js` uses `eslint-config-airbnb-base` and defines wepback import resolver as follows:
```js
module.exports = {
  'extends': ['airbnb-base'],
  // 'extends': ['jquery'],
  // 'extends': ['google'],
  'settings': {
    'import/resolver': {
      'webpack': {
        'config': path.join(__dirname, 'webpack.config.js')
      }
    }
  }
};
```

It doesn't happen when `.eslintrc.js` uses `eslint-config-google` or `eslint-config-jquery`

--------

### How to reproduce

1. Clone a test repo: https://github.com/andreyvolokitin/testcase1
2. Run `npm i && npm run build`. The webpack build log in the console will contain multiple additional `execute config` strings, one for each usage of `resolve.alias` in `src/js/index.js`:
```
test
execute config
execute config
execute config
```
3. Open `.eslintrc.js` and change a config in use (to `jquery` or `google`), and run `npm run build` again. The build log in console will contain only one instance of `execute config`:
```
test
execute config
```

**Comment by ljharb** [comment]
This is functionality that's part of `eslint-plugin-import`, not this config - if instead you could file this there, that'd be great.

The reason you don't see it with those other shared eslint configs is likely that they don't enable the relevant import plugin rules.

**Comment by andreyvolokitin** [comment]
Yeah, I was wondering where I could file this, thanks
