### ISSUE TITLE
How to reduce the dimension of multidimensional array gracefully！

### ISSUE THREAD

**Issue by gitMyPtro** [airbnb/javascript#1937]
```js
function arrDeepMap(arr) {
  for (let i = 0; i < arr.length; i++) {
    if (Object.prototype.toString.apply(arr[i]) == '[object Array]') {
      let tempArr = arr[i]
      arr.splice(i, 1, ...tempArr)
    }
  }
  return arr
}
```

**Comment by ljharb** [comment]
This really isn't the venue for this type of question, but:
 1. use `Array.isArray`, not `Object.prototype.toString`
 1. never use `splice`, it's incredibly unperformant and has a very unintuitive API, and it mutates
 1. I'm not entirely sure what you're asking - could you provide the input data, and desired output data?

I'm going to close this, but feel free to provide the followup info and we can keep discussing.

**Comment by strayiker** [comment]
Hello. I think u are looking for something like this
https://lodash.com/docs/4.17.10#flatten
https://lodash.com/docs/4.17.10#flattenDeep

You can use it as is or look into source to understand how it been realized

**Comment by ljharb** [comment]
https://npmjs.com/array.prototype.flat, but perhaps yes.
