### ISSUE TITLE
Add support for React Hooks

### ISSUE THREAD

**Issue by kripod** [airbnb/javascript#1944]
I would suggest to enforce the [Rules of Hooks](https://reactjs.org/docs/hooks-rules.html) for React v16.7.0-alpha and beyond. A linter plugin is already available under the package [eslint-plugin-react-hooks](https://www.npmjs.com/package/eslint-plugin-react-hooks).

**Comment by ljharb** [comment]
It’s still an alpha (for only 3-4 days); it’s not safe to rely on in production yet - at least until it’s considered stable by the React team.

Separately, adding an extra plugin to the config is semver-majpr and we’re very unlikely to do it without very good reason and a lot of time and consideration.

**Comment by kripod** [comment]
@ljharb Thank you for the fast review! I just wanted to raise an issue for tracking the progress of addition, as a reference for curious minds experimenting with the latest APIs.

**Comment by ljharb** [comment]
Even when stable, it’s not a given that this config should include it.

I’m pretty unclear on the wisdom of react relying on a linter rule to ensure a feature is used safely, and I’m hopeful that decision will be revisited before the feature ships.

**Comment by ljharb** [comment]
If insufficient time is going to be provided for non-Facebook employees to weigh in on new features and decisions, then I’m not sure what the point of calling things “unstable” is. ¯\\\_(ツ)_/¯

**Comment by brodybits** [comment]
I will try to make it a little more clear: from the very long discussion in <https://github.com/reactjs/rfcs/pull/68> there some very well-explained concerns and alternatives but so far nothing seems to be strong enough to counter the tide toward finalization. Any ideas?

**Comment by leoyli** [comment]
I totally agree...  The issue is coming from the call order dependency, which is impossible to do static analysis before run-time.

**Comment by xeoneux** [comment]
[eslint-plugin-react-hooks](https://www.npmjs.com/package/eslint-plugin-react-hooks) just hit v1.0.0. I've been using `eslint-config-airbnb` for a long time especially for react and would love to see `eslint-plugin-react-hooks` make its way to the peer deps for all the react hooks goodness 😄

**Comment by jalal246** [comment]
It's in react [docs ](https://reactjs.org/docs/hooks-overview.html#%EF%B8%8F-rules-of-hooks)now:

> We provide a linter plugin to enforce these rules automatically. We understand these rules might seem limiting or confusing at first, but they are essential to making Hooks work well.

**Comment by realcredit1** [comment]
no hooks keep all eslint congig
