### ISSUE TITLE
prefer-default-export encourages code that cannot take advantage of treeshaking

### ISSUE THREAD

**Issue by citypaul** [airbnb/javascript#1945]
I was reading through this issue: https://github.com/airbnb/javascript/issues/1365

I couldn't help but pay attention to this comment: https://github.com/airbnb/javascript/issues/1365#issuecomment-347045895

>It's sadly a style I've seen too much to export an object with all of the "named" exports as members. This then breaks tree-shaking (for obvious reasons), where as you can tree-shake if you export them all separately.

I understand the `prefer-default-export` rule applies only to files that are exporting one thing, and named exports are preferred where more than one thing is to be exported. However, I can't help but feel this rule encourages developers to refactor towards exporting a single object containing each module to export as a key:

```js
export default {
	myFirstThing,
	mySecondThing
}
```

Doing this prevents treeshaking, which has significant performance implications.

I understand the counter to this argument could be that developers should know better, but isn't a linter supposed to help with exactly these kinds of things in the first place? 

## Suggestion

Consider insisting all exports are named exports, in order to prevent the tendency to refactor towards code that cannot take advantage of treeshaking.

The reason this is an issue for tree shaking is explained directly here: 

http://exploringjs.com/es6/ch_modules.html#_are-named-exports-necessary-why-not-default-export-objects

Related article:

https://blog.neufund.org/why-we-have-banned-default-exports-and-you-should-do-the-same-d51fdc2cf2ad?gi=665a7fcc8284

**Comment by ljharb** [comment]
As you said, if you only export one thing, then there’s nothing to tree shake in the first place - which is what this guide encourages. As for export defaulting an object - you’re right that a developer who doesn’t know better may do that, and there may be linter rules we could employ to help catch that.

However, if you are even the least bit concerned about bundle size, then you and your team are already past the point where you need to learn about these things. Using named exports does not, in fact, automatically allow naive treeshaking - you still have to avoid sharing closure state between named exports, for example.

A default export is what a module *is*, a named export is what a module *has*. Most modules should *be* something. Bundle size and treeshaking concerns are optimizations, and very very low on the list compared to mental models and conceptual correctness, which relate to maintainability and ability to reason about your code.
