### ISSUE TITLE
[Suggestion] `import ... from ...` should specify file extensions

### ISSUE THREAD

**Issue by zilong-thu** [airbnb/javascript#1947]
In systems that use ECMAScript Modules, many developers (me included) declare `import` like this:

```javascript
import util from '../util';
```

It works. But the declaration is somehow confusing.  To module loaders, they have to guess the path of '../util' by querying the file system at multiple locations, it might be '../util.js', or '../util/index.js', or some other types (e.g, '../util/index.vue', or '../util.vue'). To developers who are not quite familiar with the project, the same confusion exists.

Ryan Dahl gave a talk at JSConf EU 2018 titled "10 Things I Regret About Node.js". One of the regrets is **require("module") without the extension ".js"**:

+ Needlessly less explicit.
+ Not how browser javascript works. You cannot omit the ".js" in a script tag src attribute.
+ The module loader has to query the file system at multiple locations trying to guess what the user intended.

I think it's time to make a change: specify the file extension we import from. Like this:

```javascript
import util from '../util.js'
```

**Comment by ljharb** [comment]
It is very critical to always omit the file extension to allow for maximum refactorability, and our linting config enforces this.

Module loaders can always trivially use `require.resolve`, or similar, to resolve a specifier to a full path.

That particular talk is full of attempts to “regret” the very reasons node is successful, and I’d recommend not taking it to heart.

This will not be changing, and the best practice for the entire ecosystem will remain to always omit the extension.
