### ISSUE TITLE
I encountered such problems when I was using it.

### ISSUE THREAD

**Issue by Bigpawn** [airbnb/javascript#1949]
Configuration for rule "react/jsx-no-bind" is invalid:
	Value {"ignoreRefs":true,"allowArrowFunctions":true,"allowFunctions":false,"allowBind":false,"ignoreDOMComponents":true} should NOT have additional properties.

**Comment by ljharb** [comment]
What does `npm ls` say? If it exits nonzero, your dependency graph is invalid, and nothing can be expected to work.
