### ISSUE TITLE
react/forbid-prop-types is not allowing arrays & objects

### ISSUE THREAD

**Issue by 321ckatz123** [airbnb/javascript#1952]
The react/forbid-prod-types lint rule forbids using arrays & objects (this is also the default), but no mention of it is in the README as to which policy it is breaking (granted, I assume it is because you should be explicit about what the array or object contains, using `arrayOf` and `shape` respectively).

**Comment by ljharb** [comment]
We have a number of rules in the config that aren't mentioned in the guide, and vice versa.

Indeed, the reason is because you should be explicit about what the array or object contains. A PR to add a section would be appreciated!

**Comment by rahilvora** [comment]
https://github.com/airbnb/javascript/pull/1984 PR for this issue. @ljharb Kindly review it.

**Comment by ljharb** [comment]
Fixed by #1984.
