### ISSUE TITLE
React: suggested naming convention for component stylesheet files

### ISSUE THREAD

**Issue by ghbakhtiari** [airbnb/javascript#1959]
In either of these cases is there any suggestion for naming the stylesheet files?

```
MyComponent/
  -index.jsx
  -styles.css
```

```
SomeComponent/
  -MyComponentA.jsx
  -MyComponentA.css
  -MyComponentB.jsx
  -MyComponentB.css
  -index.jsx
  -styles.css
```

**Comment by ljharb** [comment]
We don’t use stylesheet files (https://github.com/airbnb/javascript/tree/master/css-in-javascript) so we have no convention for them.
