### ISSUE TITLE
Converting object into Json (stringify)

### ISSUE THREAD

**Issue by sbala69gmail** [airbnb/javascript#1969]
Hi ,

I have one doubt in stringify an object.

In input is below: 

```
var obj = [{'name' : 'Jenisha', 'lastName' : 'dalin'}];
obj.__used = true;
```

**My expected output:** 
```
JSON.stringify(obj, undefined, 4);
"[
    {
        "name": "Jenisha",
        "lastName": "dalin"
    }
],
"__used" : true
"
```

**But the results are:**

```
JSON.stringify(obj, undefined, 4);
"[
    {
        "name": "Jenisha",
        "lastName": "dalin"
    }
]"
```

"__used" param removed. is any alternate function available to stringify an object.

Thanks in advance.

**Comment by ljharb** [comment]
In this case, you’re attaching the property to the *array*, and while arrays are objects that can have properties, in JSON, the stringify algorithm ignores those.

If you have an *object* at the top level, then you can stick properties on that.

This repo is not for general javascript help, however - it’s for our javascript style guide - so I’m closing the issue.
