### ISSUE TITLE
Using Array.map() without using currentValue (no-unused-vars)

### ISSUE THREAD

**Issue by borrascador** [airbnb/javascript#1970]
I'm in a situation where I'm trying to make an array of random x y coordinates but the underscore in the map function is being flagged as an unused var. I'm not sure if there is a better way to write this or if I should simply do an inline ignore in this case.

In short: how do I avoid the `no-unused-vars` error when I don't need the `currentValue` required by the `Array.map()` method?

```javascript
const getRandomInt = max => Math.floor(Math.random() * Math.floor(max));
const myCoolArray = new Array(25)
  .fill({})
  .map(_ => ({
    x: getRandomInt(100),
    y: getRandomInt(100)
  }))
```

**Comment by ljharb** [comment]
I’d suggest never using `new Array` ever, for any reason, full stop.

What you want here is:
```js
const myCoolArray = Array.from({ length: 25 }, () => ({
  x: getRandomInt(100),
  y: getRandomInt(100),
});
```

**Comment by ljharb** [comment]
To your original question, instead of `_`, use `()`.

**Comment by ericblade** [comment]
TIL Array.from({length: X}) . . I don't believe that trick is widely known.

**Comment by ljharb** [comment]
https://github.com/airbnb/javascript#arrays--from-array-like :-)

**Comment by borrascador** [comment]
Thanks @ljharb !! That's a very neat solution.
