### ISSUE TITLE
[ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning

### ISSUE THREAD

**Issue by leimonio** [airbnb/javascript#1971]
Sorry in advance for opening this issue again, but checking `eslint-config-airbnb-base` `peerDependencies` I can see that eslint > v5 should be supported.

When running eslint on my repo I'm still getting
`[ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in ".eslintrc.js")`

In `package.json`
```
...
"eslint": "5.3.0",
"eslint-config-airbnb-base": "^13.1.0",
...
```

**Comment by ljharb** [comment]
The latest version of the base config is v17.1.0; you’re on v13.1. Try upgradingto the latest of both it and eslint itself.

**Comment by leimonio** [comment]
@ljharb How is the latest v17.1.0 https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/package.json#L3?

**Comment by ljharb** [comment]
Oops, you’re right, i was thinking of the main config.

Can you try upgrading to latest eslint before i reopen this?
