### ISSUE TITLE
Do you have a specification for new line after import?

### ISSUE THREAD

**Issue by fifn2** [airbnb/javascript#1978]
What does this styleguide think about newlines after imports? eslint [import/newline-after-import]
```js
import quotes from './quotes';
import people from './people';
import elem from './elem';
console.log(quotes, people, elem);
```
or
```js
import quotes from './quotes';
import people from './people';
import elem from './elem';

console.log(quotes, people, elem);
```

**Comment by ljharb** [comment]
https://github.com/airbnb/javascript/blob/80920a07c5144148d2987f39fb9558246552648e/packages/eslint-config-airbnb-base/rules/imports.js#L150

**Comment by fifn2** [comment]
So, one newline after imports, right/

**Comment by ljharb** [comment]
Yes, there’s a separate rule that should be stopping > 1 successive newline.

**Comment by fifn2** [comment]
Thanks, sorry. Maybe you should have an import section in the readme?

**Comment by ljharb** [comment]
We have https://github.com/airbnb/javascript#modules, but I'm not sure how valuable it'd be to add a whole section that requires adding a newline for readability purposes.

**Comment by fifn2** [comment]
I mean maybe just like a rule or something. It is a bit weird to have a
whole section, but a rule would be good.

**Comment by ljharb** [comment]
We already have a rule - one to enforce > 0 newlines after imports, and one to prevent > 1 newline anywhere.

**Comment by fifn2** [comment]
You should write it directly in the style guide under the module section.

**Comment by ljharb** [comment]
Right - that's what I'm claiming wouldn't have much value :-) what would be the goal?

**Comment by ljharb** [comment]
Sure, but i worry about adding noise to the guide for a relatively common sense rule that’s covered by the linting config.

**Comment by fifn2** [comment]
I mean, to me this doesn't seem very common sense.

**Comment by tunnckoCore** [comment]
@fifn2 I don't see how it isn't. If you are new here and curious and considering to switch to that guide, then you should try it while you reading it. And if you did that you wouldn't open that issues because you would see linting error with that example that you gave here.
