### ISSUE TITLE
Vim Options?

### ISSUE THREAD

**Issue by pertrai1** [airbnb/javascript#198]
I was wondering if there was a way to add the lint options as you do for ST2 for Vim?

**Comment by jeffvandyke** [comment]
For anyone stumbling on this from a web search like I did, the ALE project at <https://github.com/w0rp/ale> integrates out of the box with eslint installed as a global package. Haven't figured out yet how to get vim <kbd>=</kbd> indentation to work

**Comment by JESii** [comment]
@jeffvandyke What's your issue with vim `=` indentation... the basic feature or issues with `=` and ALE?
