### ISSUE TITLE
Would I put commas in an array inside of an object?

### ISSUE THREAD

**Issue by fifn2** [airbnb/javascript#1981]
```js
// good - git diff with trailing comma
const hero = {
     firstName: 'Florence',
     lastName: 'Nightingale',
+    inventorOf: ['coxcomb chart', 'modern nursing'],
};
```
I noticed that in [20.2](https://github.com/airbnb/javascript#commas--dangling), the object inventor field doesn't have a comma after 'modern nursing'. Am I supposed to put trailing commas in arrays inside of objects, like:
```js
// good - git diff with trailing comma
const hero = {
     firstName: 'Florence',
     lastName: 'Nightingale',
+    inventorOf: ['coxcomb chart', 'modern nursing',],
};
```

**Comment by fifn2** [comment]
Thank you.

**Comment by fifn2** [comment]
They still go in an array not in an object, right?

**Comment by ljharb** [comment]
Our guide requires trailing commas (at the end of the line) everywhere they're allowed - thus, in arrays, objects, and function calls/signatures.

**Comment by ljharb** [comment]
So, `const array = ['foo', 'bar', 'baz',];` would *not* have a trailing comma, because the line is ended by `];`.
