### ISSUE TITLE
Dated and wrong rule should get finally updated: Only .js files should contain JSX

### ISSUE THREAD

**Issue by desmap** [airbnb/javascript#1982]
Found a two years old PR and an epic discussion which was unfortunately locked despite most voted for abandoning a dated rule.

In 2019, nobody calls files containing JSX .jsx.  @gaearon 's arguments two years ago were crystal clear, consistent and significantly upvoted by the majority while just few could follow @ljharb thoughts on topic.

I don't want to redo this discussion because there is no need. This rule is blatantly wrong, creates unnecessary work, does not reflect reality and is bad practice for the reasons Dan stated well in https://github.com/facebook/create-react-app/issues/87#issuecomment-234627904 and https://github.com/airbnb/javascript/pull/985#issuecomment-239145468

Hence, we all would be happy if PR https://github.com/airbnb/javascript/pull/985 got finally reopened & merged without another tedious discussion.

**Comment by ljharb** [comment]
It will not be reopened or merged; the reasons remain unchanged, it will never be “dated” unless jsx becomes a standard part of the language, and we continue to follow it inside Airbnb and on all our public projects.

Please feel free to fork and/or override any decisions we make that you disagree with.
