### ISSUE TITLE
FormData object forms submit data

### ISSUE THREAD

**Issue by xiaohaook** [airbnb/javascript#1986]
<img width="288" alt="2019-01-07 10 28 29" src="https://user-images.githubusercontent.com/19567662/50746024-12092a00-1268-11e9-8f48-947b81c964f3.png">
I hope TC39 can add set attribute to replace the repeatedly submitted key on the FormData instance when the user creates the FormData object through the HTML form. At present, it seems that only append can submit data.

**Comment by ljharb** [comment]
FormData isn't part of the JS language; it's part of the browser, so TC39 has nothing to do with it.

Either way, this repo is for Airbnb's JavaScript style guide, not for the JS language.
