### ISSUE TITLE
Dead link in 14.1 (about typeof no longer being safe)

### ISSUE THREAD

**Issue by lilymatcha** [airbnb/javascript#1989]
The named link, which is about why typeof is no longer safe, [links to a website with an expired domain](http://es-discourse.com/t/why-typeof-is-no-longer-safe/15
). Is there an alternate resource we could link to on this subject?

**Comment by ljharb** [comment]
Sure, let's update it to https://web.archive.org/web/20180227052223/http://es-discourse.com/t/why-typeof-is-no-longer-safe/15

**Comment by ljharb** [comment]
The site's now working again. Thanks for reporting!

**Comment by stansv** [comment]
At least since yesterday I observe this site is down again :confused:

**Comment by ljharb** [comment]
Thanks, I've pinged @kangax on twitter and here; hopefully we can get it restored.
