### ISSUE TITLE
Why is the definition of a variable is moved after using?

### ISSUE THREAD

**Issue by nikolay-govorov** [airbnb/javascript#2002]
The require of the `package.json` is moved later — the resulting code will not work

Why such code:
```js
const pkg = require('../package.json')

if (!process.version !== pkg.engines.node) { /* .. */ }

const app = require('yargs')
const updateNotifier = require('update-notifier')
```

will be turned into such:
```js
 
if (!process.version !== pkg.engines.node) { /* .. */ }

const app = require('yargs');
const updateNotifier = require('update-notifier');
const pkg = require('../package.json');
```

I use MacOS, `node@10.10.0`, `npm@6.4.1`, `eslint@5.13.0`, `eslint-config-airbnb-base@13.1.0`

**Comment by ljharb** [comment]
I’m not sure what you mean - is a rule autofixer doing that? If so, it’d need to be filed on the appropriate project - eslint core, the import plugin, the react plugin, or the a11y plugin.

Are you sure you have the latest version of all your eslint packages?

**Comment by nikolay-govorov** [comment]
Yes, it's about `eslint --fix` command with config inherited from `eslint-config-airbnb-base`. All packages use the latest versions

**Comment by ljharb** [comment]
If you don’t use --fix, what rule is warning on that line?

**Comment by nikolay-govorov** [comment]
```
1:13  error  `../package.json` import should occur after import of `update-notifier`  import/order
```

**Comment by ljharb** [comment]
Thanks - please file this issue on https://github.com/benmosher/eslint-plugin-import instead, and be sure to include the versions of all your eslint packages.

**Comment by nikolay-govorov** [comment]
@ljharb, it bug. [This bug resolved](https://github.com/benmosher/eslint-plugin-import/issues/1252) in `2.16.0`  version, but this ptoject use `2.15.0` version

**Comment by ljharb** [comment]
Always good to update to the latest :-)
