### ISSUE TITLE
max-len rule does not match format in Eslint docs

### ISSUE THREAD

**Issue by simmo** [airbnb/javascript#2009]
Ref: https://eslint.org/docs/rules/max-len

`rules/style.js` specifies the line length as 100 in an array value rather than as `code` property in the options object.

**Comment by ljharb** [comment]
Indeed; but if you check the [rule source](https://github.com/eslint/eslint/blob/master/lib/rules/max-len.js#L60-L68), you'll see it also supports the integer format, since [v0.22.0](https://github.com/eslint/eslint/commit/83f479d3937f31ec794d78333dd9d1da7b92fc76).
