### ISSUE TITLE
Forget string delimiters and always use template literals?

### ISSUE THREAD

**Issue by andyearnshaw** [airbnb/javascript#2015]
I've thought about this with my own code quite a few times and have considered using template string delimiters for *all* my strings.  Why?

 - Free escape sequence linting
 - Supports multiline strings
 - Faster refactoring - you want to add expression placeholders to a string; if the string already has the template delimiters then there's no need to change them
 - Escape frequency. In most languages, grave accents ("back-ticks") are seldom used on their own without combining. Personally, the only time I find myself using back-ticks are with markdown, but I use `'` as an apostrophe inside strings (e.g. error messages, test titles, etc) all the time. Escape characters look ugly and break up the natural reading flow of text, and changing the quotes to avoid escaping slows productivity

I'm having trouble thinking up downsides.  I doubt there's any realistic performance difference, as parsing a template literal with no placeholders should not require any more effort than parsing a string literal. Compilers/minifiers can also just change them to standard strings anyway.  There's maybe a half-argument for differentiation between static and template strings, but syntax highlighters don't (usually) differentiate and the difference between `'` and <code>`</code> is not large enough when scanning code, so I don't think it's a particularly great loss.

Personally, I feel like ordinary string literals are redundant now that we have template strings, but maybe the community can give a good reason why not to just use template strings everywhere.  Either way, I thought this would be the ideal place to discuss it, and possibly convert the discussion to a feature request if the overall sentiment is positive.

**Comment by ljharb** [comment]
Quoted strings are still required in import statements and strict mode pragmas, so backticks *can’t* be used for all strings.

As for escape frequency, straight quotes are typographically incorrect in prose, and thus should never be used in the use cases you cite - those should always only be curly quotes, avoiding the escaping problem entirely.

**Comment by andyearnshaw** [comment]
Damn, I forgot about imports. If I wanted to be consistent then the idea of
template strings everywhere is a non-starter, without a language change. I
suspect this is due to avoiding confusion around using templates with
interpolation for imports, so the idea would probably be contentious.

I don't worry about "curly" quotes inside error messages and other such
strings, and the other points regarding refactoring still stand, but I
guess this is moot and the issue should be closed as there is no point
having the discussion.

I suppose editor plugins to reduce these pain points would be a better
idea.
