### ISSUE TITLE
Reword the no-iterators reasoning.

### ISSUE THREAD

**Issue by flying-sheep** [airbnb/javascript#2019]
([11.1](https://github.com/airbnb/javascript#iterators--nope))

Everything has been said in #1122, and the conclusions are

- generators are slow after being compiled to ES5
- `map`/`filter`/… are better than loops when they can be used
- `forEach` is worse than loops, because it looks like it’s functional yet it’s as impure* as loops. In good code, using loops would signal that there’s impurity, and they’re there for a reason.
- loops are able to contain `await` and `yield`, and make for much nicer and clearer code when one uses those constructs (compared to using e.g. the Promise API with `reduce`)
- `forEach` is still recommended because of the first point – `forEach` is faster than generators-compiled-to-ES5.

I think that needs to be reflected in that section somehow. Iterators and loops should be avoided *if* there’s purity or if ES5 needs to be targeted. If not, and one uses IO, non-trivial async code or things have to be mutated, loops are better.

*purity: In functional lingo, “purity” means the absence of side effects like mutation of state or IO.

**Comment by ljharb** [comment]
forEach is not worse than loops; loops are the worst regardless.

**Comment by flying-sheep** [comment]
You’re pretty alone with that opinion. Nobody disagreed with me in https://github.com/airbnb/javascript/issues/1122#issuecomment-267170449 (:+1: 16, :-1: 0) that the following code is cleaner than a reduce-based solution:

```js
for (const url of urls) {
  await download(url)
}
```

Also you’ve forgotten this: I pointed out in https://github.com/airbnb/javascript/issues/1122#issuecomment-265109832 (:+1: 28, :-1: 1) that both `forEach` and `for..of` are about side effects, while the latter signals it better. You initially got confused but later, you said

> @flying-sheep lol fair point, both are for side effects since for..of isn't an expression. forget that part.

---

Conclusion: people agree with me that *in an environment where iterators don’t cost runtime*, loops are better than `forEach` to signal that side effects happen, and that (other than `forEach` they integrating better with `await` and `yield`.

Your blanket statement about `forEach` being better is therefore not an objective truth.

**Comment by ljharb** [comment]
@flying-sheep I'm not alone in it, but that's not really relevant - it's the position of this guide, which is Airbnb's. `forEach` imo signals side effects better than `for..of`.

It's not about being an objective truth - but *for this guide*, `forEach` is always better than any loop, full stop.

I don't think this needs further discussion.

**Comment by mighty9245** [comment]
@ljharb, ok, what you'll use instead for await?

**Comment by ljharb** [comment]
@mighty9245 the use cases for async iterators are rare, and the last time I looked at an airbnb codebase, there was no need for them anywhere.

**Comment by paeolo** [comment]
@ljharb I know this issue is closed but I don't get your answer to @mighty9245. Do you imply that async iteration is so useless that it should be banned through a linter?

**Comment by flying-sheep** [comment]
They are of course not. Just like normal iterators, they’re a natural match for e.g. a stream of incoming events. And like anything else, the async variation is used when there’s IO happening.

JavaScript has a long history of registering callbacks for events. That doesn’t make a callback-based approach more natural, just more familiar for JS devs. In other fields, iteration is the natural way to do things.

And in fact, it has several advantages. The most important one is the control flow being much simpler. Instead of registering event handlers and climbing through a complex chain of callbacks, you descend into a clear flow of branches. Putting breakpoints into the latter to understand some bug is a much better experience than in the former.

**Comment by paeolo** [comment]
@flying-sheep Couldn't agree more with you, and I am also ok with AirBnb not using `for await` but as you said it doesn't sound like a general truth.. Note that there is a library out there to wrap things the way you want: https://github.com/ReactiveX/IxJS.
