### ISSUE TITLE
multiline-comment-style rule is off

### ISSUE THREAD

**Issue by bryankennedy** [airbnb/javascript#2020]
I was reading rule [18.1](https://github.com/airbnb/javascript#comments--multiline) and noticed that I've never seen my airbnb configured linter say anything about this. I looked in the [rules and noticed that the starred-block option is spelled out but it set to off](https://github.com/airbnb/javascript/blob/b85baeafed8b66fdd9756439a0b8774860147913/packages/eslint-config-airbnb-base/rules/style.js#L237).

Is there a reason why this is set to `off` vs `error`?

**Comment by ljharb** [comment]
It’s not a rule we enforce; however, the configuration is set up how we *would* enforce it so you can easily enable it.

**Comment by bryankennedy** [comment]
Ah that makes sense. Thanks for clarifying.

Is there a way to differentiate rules in the documentation that are enforced, or on, versus the ones that simply have the way it would be enforced if it were on?

**Comment by ljharb** [comment]
We don’t currently have a way to distinguish that, no.

**Comment by ljharb** [comment]
@Zamiell that is a reasonable expectation, but not an accurate one. Some guidelines, as rules, would be too noisy on a legacy codebase, for example.

Everything in the readme is a strict rule that's important to follow. Which subset of it is enforced by the linter doesn't affect the importance of individual guidelines.
