### ISSUE TITLE
`Unexpected use of file extension "js"` for browser import

### ISSUE THREAD

**Issue by markymark** [airbnb/javascript#2021]
Similar to the issue reported in [this](https://github.com/airbnb/javascript/issues/1592#issuecomment-424903766) comment, I'm seeing the above style guide error when importing a module.

If I omit the extension then the check passes, but the browser is unable to resolve the import (404). `import` itself is documented in [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) article--note the consistent use of file extensions there.

Is there a recommended way this should be resolved by the guide?

Thanks.

**Comment by ljharb** [comment]
I'm not sure what you mean - are you using a bundler, or are you trying to send down native, untranspiled ESM to the browser?

Native `import` in the browser uses URLs - the browser doesn't care about extensions one way or the other. So, the exact URL you import needs to be served by your server.

However, I strongly suggest you always use a bundler, and don't bother sending down native ESM at the moment. It's slow, and isn't supported in that many used browser versions yet.

**Comment by markymark** [comment]
Thank you, it's the same as the linked commenter explained, to reproduce. I think his comment got lost in the discussion over the original issue.

Maybe I'm wrong (often), but aren't modules supported by all major browsers since 2017/8? (So multiple articles have told me, anyway!)

**Comment by ljharb** [comment]
@markymark by the *latest version* of all major browsers, but the latest version doesn't matter, only "what is used" matters - and many users don't have that support available.

Regardless, you'll want to always use a bundler and transpile to CJS for the forseeable future.

If you make a different choice, you may want to override some of our linter settings, all of which assume you're following the best practice of using babel and a bundler.

**Comment by mindflow** [comment]
I ran into this problem myself. I bundle both jsm and cjs files with rollup which are both supported in the browser. But as you say, the browser requires to .js extension to be present. When coding I omit the .js extension, and I have a postprocess step in the rollup config which adds it inn.

Here is a part of my rollup config:
`import multiEntry from 'rollup-plugin-multi-entry';
import postprocess from 'rollup-plugin-postprocess';
import uglify from "rollup-plugin-uglify-es";

export default [{
    input: "src/**/*.js",
    external: [ 'coreutil_v1' ],
    output: {
        name: 'xmlparser_v1',
        file: "dist/jsm/xmlparser_v1.js",
        sourcemap: "inline",
        format: "es"
    },
    plugins: [
        multiEntry(),
        postprocess([
            [/(?<=import\s*(.*)\s*from\s*)['"]((?!.*[.]js).*)['"];/, '\'./$2.js\'']
        ]),
        uglify()
    ]
}`

**Comment by ljharb** [comment]
No, that’s not what i said - browsers do not care about extensions whatsoever; only node does. Browser ESM requires the exact URL, which isn’t a file path.

Your solution seems like a fine workaround prior to node shipping ESM.

**Comment by mindflow** [comment]
@ljharb I get what you are saying. But the browser also support relative paths, so if the structure is the same on file system as on web, that is interoperable, so far as the post process is done for the .js extension.

**Comment by ljharb** [comment]
It already can't/shouldn't be, or else you'd be serving node_modules directly :-)
