### ISSUE TITLE
Install eslint airbnb packages in parent folder of project root?

### ISSUE THREAD

**Issue by ZYinMD** [airbnb/javascript#2024]
I'm working on a team project which doesn't have and will not have a shared `.eslintrc` file. I use the eslint plugin for VSCode and put my `.eslintrc` in the parent folder of the project. I imagine other team members are doing similar things.

Now I want to set up airbnb for myself to use, but that involves adding quite a few packages into `package.json`, which I don't want to do, because I'm afraid of affecting other people. 

I tried to `npm init` the parent folder and set up airbnb there, but it doesn't seem to have any effect inside the project folder. 

My question is: 

1. Is there a way to set up airbnb packages in the parent folder of project root?

2. If not, I think I can just go ahead and set up airbnb, and put the `.eslintrc` into `.gitignore`. I'm sure the current `package.json` does not have any packages named `eslint*`. If I add those packages, will that possibly affect other team members?

(May or may not be relevant: the project root is actually a node app which contains a folder called `client` as the front end, which is a react project that has 
its own `package.json`. I'm actually working in `client`)

**Comment by ljharb** [comment]
I'm a bit confused. What affect are you worried it will have on other people to have the deps in the root package.json?

You can always make a package.json and an `.eslintrc` in your subfolder, and install the deps there as well.

**Comment by ZYinMD** [comment]
1. To answer your question about what I was worrying: since the project doesn't have a committed `.eslintrc`, I think everybody secretly has their own `.eslintrc`. I'm new to the team and don't want to make the decision to add a bunch of new packages, of course they may have no effect, but I'm actually not very clear on how those packages work, so I was hesitant.

2. I didn't understand what you meant by "making a subfolder and install the deps there". My original goal was "secretly do my own linting without committing my setup to the repo", that's why I was trying to install the packages in the parent folder of the repo.

3. Update on my situation: after submitting this issue, I realized the packages in the repo's parent folder actually seem to work, it's just super super slow to lint (first squiggles took 10+ minutes to show). I'll observe more and report back.

**Comment by ljharb** [comment]
If you want to secretly do your own linting; then I'd install all the relevant packages globally - however, I'd suggest not applying linting tools to a project where it's not enforced in CI and used by all developers. Every dev in a project should use the same standards, even if those are "no linting".

Regardless, this is more of a general discussion of how eslint works, and isn't specific to this styleguide, so I'm going to close it - feel free to continue discussing here.

**Comment by ZYinMD** [comment]
I've concluded my test and updated the original post for future googlers. Thanks.
