### ISSUE TITLE
Node.js requires file extension in esm import path

### ISSUE THREAD

**Issue by golopot** [airbnb/javascript#2030]
Currently this config disallows adding extensions like `.js` and `.jsx` in import path. This contradicts node.js's plan for esm that [extension are mandatory](https://nodejs.org/api/esm.html#esm_mandatory_file_extensions).

> #### Mandatory file extensions
> A file extension must be provided when using the import keyword. Directory indexes (e.g. './startup/index.js') must also be fully specified.
> This behavior matches how import behaves in browser environments, assuming a typically configured server.

https://github.com/airbnb/javascript/blob/1310ade9d0e4d1e5625f29b89d4c902bebc8cc11/packages/eslint-config-airbnb-base/rules/imports.js#L136-L142

**Comment by ljharb** [comment]
That's not node's plan - I'm a member of the modules group. That's just the current default implementation. Extension resolution is shipped behind an additional flag, and my hope is that it will be enabled by default prior to unflagging node's native implementation.

Regardless, prior to node's implementation being unflagged, its flagged implementation should have *no bearing whatsoever* on any ecosystem decisions, since for all intents and purposes, node's ESM system does not exist yet.

**Comment by FergusonSean** [comment]
Should this issue be reopened given the newly published node 14 esm implementation does require file extensions?

**Comment by ljharb** [comment]
@FergusonSean unfortunately yes, node v12.7+, v13.7+, and v14+ have an ESM implementation that does not do resolution. Extensions (on relative files, or packages without "exports" only) are required when using `import`.

However, this guide currently recommends using babel and not native ESM, and even were it to recommend that, the relevant linting tools (`eslint-plugin-import`, in particular) does not yet support ESM or "exports" resolution - so the time to make changes is still a ways off.

**Comment by kalinchernev** [comment]
@ljharb i'm not sure I understand your suggestion based on the current situation for node libraries which want to keep as native as possible and still use the airbnb-base? I mean, turning off the rule is possible obviously, but doesn't feel like a real solution.

**Comment by ljharb** [comment]
@kalinchernev this guide requires you use babel, even on latest node, which includes authoring in ESM and transpiling to CJS.

**Comment by kalinchernev** [comment]
I understood, thanks @ljharb

**Comment by perrin4869** [comment]
[`webpack`](https://webpack.js.org/api/module-methods/) seems to have gone we way of `nodejs` here, so now packages with `type: module` won't bundle correctly unless the file extension is included either. In this case it is not desirable to compile all the way to `cjs` either
