### ISSUE TITLE
Is it okay to use code formatter such as Prettier ? 

### ISSUE THREAD

**Issue by ramazord** [airbnb/javascript#2034]
Hi, i would like to ask a question, while following Airbnb Javascript React Styleguide is it okay to use code formatter such as Prettier ?

**Comment by ljharb** [comment]
At the moment, our config conflicts with prettier, so you’d have to use eslint-config-prettier to disable all the conflicting rules. However, theoretically you wouldn’t need prettier, since eslint already has autofix.
