### ISSUE TITLE
Add componentDidCatch to lifecycle for react/sort-comp

### ISSUE THREAD

**Issue by mofojed** [airbnb/javascript#2040]
There was previously a ticket to add the new React lifecycle methods to the config: https://github.com/yannickcr/eslint-plugin-react/issues/1767

It looks like the other methods were added to lifecycle, but componentDidCatch was not: https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/react.js#L274

**Comment by rahilvora** [comment]
If this is still open, can I work on it?

**Comment by ljharb** [comment]
Sure, that'd be great, thanks!

**Comment by rahilvora** [comment]
Cool, ill look into it.

**Comment by rahilvora** [comment]
I see `componentDidCatch` is already added in the rules https://github.com/airbnb/javascript/blob/036612ec3d8af223d2a3adc40aca70365b5612fd/packages/eslint-config-airbnb/rules/react.js#L44

**Comment by rahilvora** [comment]
Should we close this issue?

**Comment by mofojed** [comment]
It needs to be added to the `lifecycle` methods. It is not there in the tree you specified or in `master`: https://github.com/airbnb/javascript/blob/036612ec3d8af223d2a3adc40aca70365b5612fd/packages/eslint-config-airbnb/rules/react.js#L273

**Comment by rahilvora** [comment]
I am sorry about that. I'll create a PR asap.

**Comment by rahilvora** [comment]
PR for this https://github.com/airbnb/javascript/pull/2060
