### ISSUE TITLE
[Question] break line after braces

### ISSUE THREAD

**Issue by Zagym** [airbnb/javascript#2041]
Hi,

I didn't find in the doc if we always should break line after a brace in function/anonymous function.

```javascript
el.addEventListener("click", () => { foo(); };

// or

el.addEventListener("click", () => { 
    foo();
};
```

**Comment by SandroMiguel** [comment]
For me, both may be correct. Depends on line width.

**Comment by ljharb** [comment]
The first one is acceptable to me as long as there's only a single statement (and as always, no comma operators).

However, see https://github.com/airbnb/javascript#blocks--braces - the guide currently recommends the latter pattern.
