### ISSUE TITLE
question: why doesn't Javascript have optional static typing ?

### ISSUE THREAD

**Issue by catastrop** [airbnb/javascript#2045]
tc39 is adding new things to JS. But why not optional static typing ?

If they do it, we don't have to use Typescript anymore and being able to pass type information to the engine.

We will have less dev dependency.

**Comment by ljharb** [comment]
Please stop cross-posting this all over the place.

Per https://github.com/tc39/proposals/issues/223#issuecomment-504765936

> Closing, since this repo isn’t the proper place to have these discussions - please try es-discuss or our discourse. https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal / https://es.discourse.group
