### ISSUE TITLE
Error in strings inside React

### ISSUE THREAD

**Issue by ilanolkies** [airbnb/javascript#2055]
This is a result after eslint:

```js
                  <ul>
                    <li>
                      <div>
                        <i>_hash bytes32</i>
                      </div>
                      <code>
0x
                        {sha3(name.split('.')[0])}
                      </code>
                    </li>
                    <li>
                      <i>_owner address</i>
:
                      {strings.mycrypto_bid_select_owner}
                    </li>
                  </ul>
```

**Comment by ljharb** [comment]
What error?

**Comment by ilanolkies** [comment]
When I run eslint --fix over this code, this is the result. The errors are the `0x` and the `:` at left without indentation.

**Comment by ljharb** [comment]
The `jsx-indent` rule is supposed to cover this; however, I think it doesn't at the moment.

Closing in favor of https://github.com/yannickcr/eslint-plugin-react/issues/2318 and https://github.com/yannickcr/eslint-plugin-react/issues/1662.
