### ISSUE TITLE
Performance test for "Try/Catch Cost In a Loop" is down

### ISSUE THREAD

**Issue by deathemperor** [airbnb/javascript#2063]
https://jsperf.com/try-catch-in-loop-cost returns
```
{
    statusCode: 500,
    error: "Internal Server Error",
    message: "An internal server error occurred"
}
```

**Comment by Crow-EH** [comment]
The edition of the revision was still possible, so I just to duplicated it in a new one.

PR incoming.

**Comment by Crow-EH** [comment]
These links are dead too, I'll handle them in the same commit :
* https://jsperf.com/jquery-find-vs-context-sel/13
* https://jsperf.com/ya-string-concat

**Comment by Crow-EH** [comment]
Losing the Browserscope data is too bad though.

[There's an existing issue on jsperf](https://github.com/jsperf/jsperf.com/issues/495).
