### ISSUE TITLE
`ESLint couldn't find the config "airbnb" to extend from.`

### ISSUE THREAD

**Issue by garyking** [airbnb/javascript#2066]
After upgrading to the latest version of this config, v18, and to eslint v6, and without changing any of my ESLint config, I get the following error when I try to lint:

```
> eslint .

Oops! Something went wrong! :(

ESLint: 6.1.0.

ESLint couldn't find the config "airbnb" to extend from. Please check that the name of the config is correct.
```

Is there something wrong with the latest config?

**Comment by ljharb** [comment]
Is your eslint local or global? What does your config look like?

**Comment by garyking** [comment]
The `eslint` is global, along with all `eslint`-related packages (config, plugins). 

Let me clean up my config to as small as possible, while still being able to reproduce the error...

**Comment by garyking** [comment]
Here's my `.eslintrc.js` in one of my projects that produces the error with the command `eslint .`:

```js
module.exports = {
  extends: 'airbnb',
};
```

**Comment by garyking** [comment]
I think I fixed it by installing the eslint plugins locally to the global eslint config file.

**Comment by garyking** [comment]
Nevermind, I still get errors when linting any of my projects that import the config from another dir...

**Comment by garyking** [comment]
Okay `--resolve-plugins-relative-to` seems to help too.

**Comment by ParagDineshGupta** [comment]
npm i -g eslint@^5.3.0 eslint-config-airbnb eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react

**Comment by ljharb** [comment]
That downgrades eslint to v5 instead of v6, however.

**Comment by ParagDineshGupta** [comment]
npm i -g eslint@^6.1.0 eslint-config-airbnb eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react

can solve the problem

**Comment by ljharb** [comment]
Since eslint is now up to 6.2.1, perhaps they release a bugfix for the resolution.

**Comment by CaptainYarb** [comment]
Try running `npm i eslint-config-airbnb` in your user HOME directory.

**Comment by ljharb** [comment]
You don’t want anything installed in your home dir, only locally per project.

**Comment by nomasprime** [comment]
@ljharb why? Are there any references that would be useful?

**Comment by ljharb** [comment]
@nomasprime because anything that's related to a project but isn't locally part of that project is something that all the other developers of that project can't benefit from.

If a project isn't linted *as part of the project*, it simply should not be linted.

**Comment by nomasprime** [comment]
@ljharb understood but what about linting to improve your code generally? It can still be overridden by a project.

Isn't there also the possibility that rules might be applied consistently across an organisation, ie, across multiple projects?

**Comment by ljharb** [comment]
It's not an improvement if every developer on the project can't share in it.

To apply rules across an org, you'd still want to configure the org's shared config in each project.

**Comment by nomasprime** [comment]
Understand your point @ljharb.

I did some experimenting and it looks like local configs override the global one anyway so not sure what the downside would be.

Whenever I jump into an editor, even outside a repo when I'm just dabbling, it's nice having linting because it helps teach me to write better code. It's personal improvement.

**Comment by karenbridson** [comment]
> Try running `npm i eslint-config-airbnb` in your user HOME directory.
> 
> Edit: only use this if you want it globally used

THIS JUST SAVED ME... many thanks. solved this exact error entirely, on all my VSCode repos...
