### ISSUE TITLE
Opinion on formatting if else if else block?

### ISSUE THREAD

**Issue by codeHatcher** [airbnb/javascript#207]
I know what I would choose but I thought I would mention it here. What's the style guide for if else if else formatting.

```javascript
if (condition) {
  //stuff
} else {
  //stuff
}
```
vs
```javascript
if (condition) {
  //stuff
}
else {
  //stuff
}
```

I think the choice is obvious but, "I've heard it both ways".

**Comment by jcurtis** [comment]
What about an `if else`? 

```
if (condition) {
  // stuff
} else if (condition2) {
  // stuff
} else {
  // stuff
}
```

vs

```
if (condition) {
  // stuff
} 
else if (condition2) {
  // stuff
} else {
  // stuff
}
```

**Comment by ljharb** [comment]
See http://en.wikipedia.org/wiki/Indent_style#Variant:_1TBS - ie, always the former, also called "cuddled elses". K&R is repugnant.

**Comment by ljharb** [comment]
This is addressed with https://github.com/airbnb/javascript#16.2

**Comment by jsejcksn** [comment]
Trying out some thread necromancy:

Where can I see addressed the aspect of implicit vs explicit `else` blocking? I've been thinking a lot about this today:

``` js
if (condition) {
  // stuff
} else if (condition2) {
  // stuff
} else {
  // stuff
}
```

vs

``` js
if (condition) {
  // stuff
} else {
  if (condition2) {
    // stuff
  }
} else {
  // stuff
}
```

**Comment by ljharb** [comment]
JS is single-threaded; I’m not sure what “thread necromancy” you’re referring to.

Those two code blocks aren’t equivalent; I’m not sure the second one is even valid syntax (because of the double else)

**Comment by jcurtis** [comment]
> thread necromancy

I think he meant reviving this discussion thread, not the JS thread

**Comment by jsejcksn** [comment]
^ The first part was a joke about reviving this conversation thread.

And you're right: I made a syntax mistake when I copied the above example to use as my own. Here's the corrected second example:

``` js
if (condition) {
  // stuff
} else {
  if (condition2) {
    // stuff
  } else {
    // stuff
  } 
}
```

**Comment by ljharb** [comment]
@jsejcksn lol oh, sorry i missed the joke.

so i'm not sure what you're asking - nesting the if/else under an else seems messy, when you could collapse "if + else + if/else" into "if, else if, else".

**Comment by jsejcksn** [comment]
What you pointed out is exactly what I was bringing up about implicit and explicit.

What you called "messy" was simply the use of brackets—just like the `if` statements. You could easily write

``` js
if (condition)
  // stuff
else if (condition2)
  //stuff
```
[This MDN article has more on `if...else`.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/if...else)

I'm not trying to get involved in a tennis match here, but I just wanted to know what the airbnb style guide has to say about explicit blocking vs implicit in regard to `if...else` because much of the other aspects of the style guide seem to prefer explicit-ness.

**Comment by ljharb** [comment]
Indeed; I don't think we have a section on it, but I think you can look at our config's `no-else-return` setting to easily intuit that in a question about those styles, we would clearly choose the first over the second of the examples [here](https://github.com/airbnb/javascript/issues/207#issuecomment-390565557).

**Comment by jsejcksn** [comment]
> I don't think we have a section on it,

I take it this hasn't been formally discussed. Could you bring this up to be addressed?

> but I think you can look at our config's no-else-return setting to easily intuit that in a question about those styles, we would clearly choose the first over the second of the examples here.

I don't understand how `return` statements relate to explicit blocking.

**Comment by ljharb** [comment]
> I don't understand how `return` statements relate to explicit blocking.

Specifically, this code:
```js
if (x) {
  return 1;
} else {
  return 2;
}
```
should instead be:
```js
if (x) {
  return 1;
}
return 2;
```

Similarly, this code:
```js
if (x) {
  foo();
} else {
  if (y) {
    bar();
  }
}
```
should instead be:
```js
if (x) {
  foo();
} else if (y) {
  bar();
}
```

Nesting should be minimized whenever possible without sacrificing clarity.

**Comment by jsejcksn** [comment]
Oh, sorry—I know what the `no-else-return` rule is that you mentioned (`else` statements are unnecessary for `return`s if preceded by an `if` with a `return`), but I'm not sure how it relates to the issue I raised.

**Comment by ljharb** [comment]
Specifically that the two code patterns are similar, even if the specifics are different, and in general, consistency and readability would win out in a case like this.

**Comment by jsejcksn** [comment]
Oh, I see. Will you post here if there is a team discussion about it?

**Comment by ljharb** [comment]
Sure, will do!
