### ISSUE TITLE
Example in 8.2 confusing

### ISSUE THREAD

**Issue by Dreamsorcerer** [airbnb/javascript#2071]
I can't understand the examples given in section 8.2:

```
// bad
[1, 2, 3].map((number) => `A string containing the ${number}.`);

// good
[1, 2, 3].map((number) => `A string containing the ${number + 1}.`);
```

Why is the first bad, and the second good? Neither have side-effects, so surely both are good?

**Comment by ljharb** [comment]
That looks to have mistakenly added in https://github.com/airbnb/javascript/commit/820745d61090139193cf9257b88974e36dfc9b35#diff-04c6e90faac2675aa89e2176d2eec7d8R963-R965 / #1863, probably a bad rebase. I'll clean it up.
