### ISSUE TITLE
ESLint returns "no-unused-expressions" error with LayoutAnimation documentation code snippet

### ISSUE THREAD

**Issue by jvmunhoz** [airbnb/javascript#2073]
I'm an intern at my company, and was recently tasked with fixing the ESLint errors of the code (a true intern job). That said, I'm still a beginner with React native, so any mistakes I make, please correct me.

In the app, LayoutAnimation is used in lots of screens, and according to the [React Native's documentation](https://facebook.github.io/react-native/docs/layoutanimation), for Android support, the following line must be added:

`UIManager.setLayoutAnimationEnabledExperimental && UIManager.setLayoutAnimationEnabledExperimental(true);`

Since it's an Android specific configuration, I've put it in the beggining of the constructor, only running if the Platform being used is Android. 

But it then returns an ESLint error: 

`ESLint: Expected an assigenment or function call and instead saw an expression.(no-unused-expressions)`

After some research, by using **allowShortCircuit** in the .eslintrc config, I'm able to bypass this error, but I wouldn't like to change it for the entire project/file. Would there be any way to rewrite this snippet so that this error wouldn't occur?

For a snippet in the documentation to trigger an error in ESLint is kinda strange...

I'm using ESLint 4.17.0

**Comment by ljharb** [comment]
Yes, it's best not to abuse value selection operators for flow control.
```js
if (UIManager.setLayoutAnimationEnabledExperimental) { UIManager.setLayoutAnimationEnabledExperimental(true); }
```

**Comment by jvmunhoz** [comment]
I imagined It would be something like this, but since I haven't actually implemented a Layout Animation I was kinda insecure about changing something present in the official documentation.

Thx for the help

**Comment by ljharb** [comment]
np!

I'd even suggest making a PR to the docs to make it match idiomatic JS code style (which is never to use `&&` when an `if` will do)

**Comment by jvmunhoz** [comment]
Where would I do this though?

**Comment by ljharb** [comment]
https://github.com/facebook/react-native-website/blob/master/docs/layoutanimation.md - there's an "edit" button on the upper right corner of the docs webpage.
