### ISSUE TITLE
Can I safely remove nativeEvent and gestureState from a PanResponder handler?

### ISSUE THREAD

**Issue by jvmunhoz** [airbnb/javascript#2075]
Take this code for instance:

```js
onPanResponderGrant: (e, gestureState) => {
        // Set the initial value to the current state
        this.state.pan.setOffset({ x: this.state.pan.x._value, y: this.state.pan.y._value });
        this.state.pan.setValue({ x: 0, y: 0 });
        Animated.spring(this.state.scale, { toValue: 1.1, friction: 3 }).start();
      },
```

In this case, both **e** and **gestureState** receive a _no-unused-var_ ESLint error, since well, they aren't actually used. Could I safely rewrite this sentence like this?

```js
      onPanResponderGrant: () => {
        // Set the initial value to the current state
        this.state.pan.setOffset({ x: this.state.pan.x._value, y: this.state.pan.y._value });
        this.state.pan.setValue({ x: 0, y: 0 });
        Animated.spring(this.state.scale, { toValue: 1.1, friction: 3 }).start();
      },
```

Or the fact that the objects **e** and **gestureState** are not being used on this handler means that PanResponder is being used the wrong way? (the app is fully functional, btw)

**Comment by ljharb** [comment]
The only observable difference to callers would be the length of the function changing; in practice if you aren’t using the arguments, you shouldn’t name them.

As to whether not using them is conceptually incorrect, that entirely depends on the library you’re using.

**Comment by jvmunhoz** [comment]
I've started my internship in the last few weeks, so I'm still kinda insecure about these little changes haha. Thanks for the help.

The library in question is React Native's [PanResponder](https://facebook.github.io/react-native/docs/panresponder.html)
