### ISSUE TITLE
Allow triple-slash (///) comments for type checking

### ISSUE THREAD

**Issue by clshortfuse** [airbnb/javascript#2076]
The basic proposal is to change `spaced-comment` to support `///`. I'm using this override:

```
"spaced-comment": ["error", "always", {
      "line": {
        "exceptions": ["-", "+"],
        "markers": ["=", "!", "/"] 
      },
      "block": {
        "exceptions": ["-", "+"],
        "markers": ["=", "!", ":", "::"],
        "balanced": true
      }
    }]
```
Triple-slash directives allow you to configure TypeScript to use a different library when checking JS files. 

See: https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html

For example, for service workers files (`sw.js`) I use the following header:

```
/// <reference types="types-serviceworker" />
/* eslint-env browser, serviceworker */
```

**Comment by ljharb** [comment]
Seems reasonable.

**Comment by Sayan-dev** [comment]
can i work on it

**Comment by ljharb** [comment]
Anyone can, that's what "pull request wanted" means :-)
