### ISSUE TITLE
Bug: "import/*" not applied

### ISSUE THREAD

**Issue by simlu** [airbnb/javascript#2077]
For some reason airbnb does not run the `import/*` rules. Since I can't see anything wrong with the setup, I'm assuming this is a bug in airbnb, but it might be elsewhere.

Easiest way to reproduce is to download the test project below and run `. debug.sh` (tested on ubuntu).

Printing out the active rules (`debug.json` file generated) shows that for example `import/no-useless-path-segments` is active as `error`. Since `index.js` contains `const data = require('../src/data');` I would expect that rule to fire. However the only eslint message I get is `no-console`.

And yes, the eslintrc file is picked up correctly.

Minimal test case:
[test-project.zip](https://github.com/airbnb/javascript/files/3526127/test-project.zip)

**Comment by ljharb** [comment]
This seems like a bug for eslint; if `--print-config` includes it, then the rule is active.

**Comment by simlu** [comment]
Created a bug report in eslint now: https://github.com/eslint/eslint/issues/12150

**Comment by ljharb** [comment]
Closing, pending that issue. Thanks!

**Comment by simlu** [comment]
After the discussion [here](https://github.com/eslint/eslint/issues/12150), would it be reasonable to request changing it so that rule `import/no-useless-path-segments` fires for `require` as well as for `import`?

Aka `"import/no-useless-path-segments": [2, { "commonjs": true }]`
