### ISSUE TITLE
Failed to load plugin 'jsx-a11y' declared '/.eslintrc » eslint-config-airbnb 

### ISSUE THREAD

**Issue by kacperborkowski** [airbnb/javascript#2078]
Hi,

I have problem after installing `eslint-config-airbnb`. In output of ESLint I have error:
`Failed to load plugin 'jsx-a11y' declared in 'frontend/.eslintrc » eslint-config-airbnb » /Users/user/Documents/GitHub/app/frontend/node_modules/eslint-config-airbnb/rules/react-a11y.js': Cannot find module 'eslint-plugin-jsx-a11y'`

Here's my `package.json` devDependecies:
`
"devDependencies": {
   "eslint": "^6.1.0",
   "eslint-config-airbnb": "^18.0.1",
   "eslint-config-prettier": "^6.1.0",
   "eslint-plugin-import": "^2.18.2",
   "eslint-plugin-jsx-a11y": "^6.2.3",
   "eslint-plugin-react": "^7.14.3",
   "eslint-plugin-react-hooks": "^1.7.0",
   "husky": "^3.0.4",
   "lint-staged": "^9.2.3",
   "prettier": "^1.18.2",
   "pretty-quick": "^1.11.1"
  }
`
Summary - ESLint is not working on my project. Project was created with `create-react-app`.

**Comment by ljharb** [comment]
It's definitely working on other projects, so I'm not sure why it's having an issue. I assume `package.json` is inside `frontend/`?

**Comment by mosinve** [comment]
Also got this error

**Comment by kacperborkowski** [comment]
> It's definitely working on other projects, so I'm not sure why it's having an issue. I assume `package.json` is inside `frontend/`?

Yes.

**Comment by gabskoro** [comment]
Yep, having the same issue, just with the `eslint-plugin-import` plugin.

package.json
```
{
  ...
  "eslint": "6.3.0",
  "eslint-config-airbnb-base": "14.0.0",
  "eslint-plugin-import": "2.18.2"
}
```

And in the Visual Studio Code output, I'm getting the following error
```
[Info  - 3:46:13 PM] ESLint server stopped.
[Info  - 3:46:14 PM] ESLint server running in node v10.11.0
[Info  - 3:46:14 PM] ESLint server is running.
[Info  - 3:46:16 PM] ESLint library loaded from: /Users/gabskoro/dev/fo-frontend/node_modules/eslint/lib/api.js
[Error - 3:46:18 PM] 
Failed to load plugin 'import' declared in 'fo-frontend/.eslintrc » eslint-config-airbnb-base » /Users/gabskoro/dev/fo-frontend/node_modules/eslint-config-airbnb-base/rules/imports.js': Cannot find module 'eslint-plugin-import'
Require stack:
- /Users/gabskoro/dev/__placeholder__.js
Happened while validating /Users/gabskoro/dev/fo-frontend/src/secure/app/main-navigation/main-navigation-help/main-navigation-help.component.js
This can happen for a couple of reasons:
1. The plugin name is spelled incorrectly in an ESLint configuration file (e.g. .eslintrc).
2. If ESLint is installed globally, then make sure 'eslint-plugin-import' is installed globally as well.
3. If ESLint is installed locally, then 'eslint-plugin-import' isn't installed correctly.

Consider running eslint --debug /Users/gabskoro/dev/fo-frontend/src/secure/app/main-navigation/main-navigation-help/main-navigation-help.component.js from a terminal to obtain a trace about the configuration files used.
```

And then after running the recommended command with the `-debug` parameter, I'm getting this 
```
eslint:file-enumerator Start to iterate files: [ '/Users/gabskoro/dev/fo-frontend/src/secure/app/main-navigation/main-navigation-help/main-navigation-help.component.js' ] +0ms
  eslint:file-enumerator File: /Users/gabskoro/dev/fo-frontend/src/secure/app/main-navigation/main-navigation-help/main-navigation-help.component.js +1ms
  eslint:cascading-config-array-factory Load config files for /Users/gabskoro/dev/fo-frontend/src/secure/app/main-navigation/main-navigation-help. +0ms
  eslint:cascading-config-array-factory No cache found: /Users/gabskoro/dev/fo-frontend/src/secure/app/main-navigation/main-navigation-help. +0ms
  eslint:config-array-factory Config file not found on /Users/gabskoro/dev/fo-frontend/src/secure/app/main-navigation/main-navigation-help +0ms
  eslint:cascading-config-array-factory No cache found: /Users/gabskoro/dev/fo-frontend/src/secure/app/main-navigation. +0ms
  eslint:config-array-factory Config file not found on /Users/gabskoro/dev/fo-frontend/src/secure/app/main-navigation +0ms
  eslint:cascading-config-array-factory No cache found: /Users/gabskoro/dev/fo-frontend/src/secure/app. +1ms
  eslint:config-array-factory Config file not found on /Users/gabskoro/dev/fo-frontend/src/secure/app +1ms
  eslint:cascading-config-array-factory No cache found: /Users/gabskoro/dev/fo-frontend/src/secure. +0ms
  eslint:config-array-factory Config file not found on /Users/gabskoro/dev/fo-frontend/src/secure +0ms
  eslint:cascading-config-array-factory No cache found: /Users/gabskoro/dev/fo-frontend/src. +0ms
  eslint:config-array-factory Config file not found on /Users/gabskoro/dev/fo-frontend/src +0ms
  eslint:cascading-config-array-factory No cache found: /Users/gabskoro/dev/fo-frontend. +0ms
  eslint:config-array-factory Loading legacy config file: /Users/gabskoro/dev/fo-frontend/.eslintrc +1ms
  eslint:config-array-factory Config file found: /Users/gabskoro/dev/fo-frontend/.eslintrc +58ms
  eslint:config-array-factory Loading {extends:"airbnb-base"} relative to /Users/gabskoro/dev/fo-frontend/.eslintrc +23ms
  eslint:config-array-factory Loaded: eslint-config-airbnb-base@14.0.0 (/Users/gabskoro/dev/fo-frontend/node_modules/eslint-config-airbnb-base/index.js) +4ms
  eslint:config-array-factory Loading JS config file: /Users/gabskoro/dev/fo-frontend/node_modules/eslint-config-airbnb-base/index.js +0ms
  eslint:config-array-factory Loading {extends:"/Users/gabskoro/dev/fo-frontend/node_modules/eslint-config-airbnb-base/rules/best-practices.js"} relative to /Users/gabskoro/dev/fo-frontend/node_modules/eslint-config-airbnb-base/index.js +3ms
  eslint:config-array-factory package.json was not found: Cannot find module '/Users/gabskoro/dev/fo-frontend/node_modules/eslint-config-airbnb-base/rules/best-practices.js/package.json'
Require stack:
- /Users/gabskoro/dev/fo-frontend/node_modules/eslint-config-airbnb-base/index.js +0ms
  eslint:config-array-factory Loaded: /Users/gabskoro/dev/fo-frontend/node_modules/eslint-config-airbnb-base/rules/best-practices.js (/Users/gabskoro/dev/fo-frontend/node_modules/eslint-config-airbnb-base/rules/best-practices.js) +0ms
  eslint:config-array-factory Loading JS config file: /Users/gabskoro/dev/fo-frontend/node_modules/eslint-config-airbnb-base/rules/best-practices.js +0ms
  eslint:config-array-factory Loading {extends:"/Users/gabskoro/dev/fo-frontend/node_modules/eslint-config-airbnb-base/rules/errors.js"} relative to /Users/gabskoro/dev/fo-frontend/node_modules/eslint-config-airbnb-base/index.js +1ms
  eslint:config-array-factory package.json was not found: Cannot find module '/Users/gabskoro/dev/fo-frontend/node_modules/eslint-config-airbnb-base/rules/errors.js/package.json'
Require stack:
- /Users/gabskoro/dev/fo-frontend/node_modules/eslint-config-airbnb-base/index.js +1ms
  eslint:config-array-factory Loaded: /Users/gabskoro/dev/fo-frontend/node_modules/eslint-config-airbnb-base/rules/errors.js (/Users/gabskoro/dev/fo-frontend/node_modules/eslint-config-airbnb-base/rules/errors.js) +0ms
  eslint:config-array-factory Loading JS config file: /Users/gabskoro/dev/fo-frontend/node_modules/eslint-config-airbnb-base/rules/errors.js +0ms
  eslint:config-array-factory Loading {extends:"/Users/gabskoro/dev/fo-frontend/node_modules/eslint-config-airbnb-base/rules/node.js"} relative to /Users/gabskoro/dev/fo-frontend/node_modules/eslint-config-airbnb-base/index.js +1ms
  eslint:config-array-factory package.json was not found: Cannot find module '/Users/gabskoro/dev/fo-frontend/node_modules/eslint-config-airbnb-base/rules/node.js/package.json'
...
```

Btw, removing the `node_modules` folder didn't help :)

**Comment by cwbuecheler** [comment]
Ran into this same issue. DevDependencies:

```
  "devDependencies": {
    "babel-eslint": "^10.0.2",
    "eslint": "^6.3.0",
    "eslint-config-airbnb": "^18.0.1",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.14.3",
    "eslint-plugin-react-hooks": "^1.7.0",
  },
```

.eslintrc.json

```
{
  "parser": "babel-eslint",
  "extends": ["airbnb"]
}
```

Output in VS Code console, slightly obscured to preserve client anonymity:

```
[Info  - 10:53:56 AM] ESLint server stopped.
[Info  - 10:53:56 AM] ESLint server running in node v10.11.0
[Info  - 10:53:56 AM] ESLint server is running.
[Info  - 10:54:01 AM] ESLint library loaded from: d:\...\repo\client\node_modules\eslint\lib\api.js
[Error - 10:54:02 AM] 
Failed to load plugin 'jsx-a11y' declared in 'client\.eslintrc.json » eslint-config-airbnb » D:\...\repo\client\node_modules\eslint-config-airbnb\rules\react-a11y.js': Cannot find module 'eslint-plugin-jsx-a11y'
Require stack:
- D:\...\repo\__placeholder__.js
Happened while validating D:\...\repo\client\components\ChartDisplay.js
This can happen for a couple of reasons:
1. The plugin name is spelled incorrectly in an ESLint configuration file (e.g. .eslintrc).
2. If ESLint is installed globally, then make sure 'eslint-plugin-jsx-a11y' is installed globally as well.
3. If ESLint is installed locally, then 'eslint-plugin-jsx-a11y' isn't installed correctly.

Consider running eslint --debug D:\...\repo\client\components\ChartDisplay.js from a terminal to obtain a trace about the configuration files used.
```

A few notes:
* I do not have eslint installed globally
* I do not have any eslint plugins installed globally
* I've manually checked and all of the required plugins are installed in `\repo\client\node_modules\`
* This project uses Next.js, which I think operates on top of create-react-app
* I'm running Windows 10 with Node 10.16.3 LTS ... no idea why the Eslint extension says it's running in v10.11.0
* If I change `extends` to `airbnb/hooks` I get the same basic error but looking for the hooks plugin instead of the a11y plugin.

**Comment by cwbuecheler** [comment]
Just a quick follow-up. Checked on my MacBook Pro and the error's identical, so it's not some goofy Windows thing.

**Comment by ljharb** [comment]
@cwbuecheler do you get the error on the command line on either system? If it only happens in your editor, then it’s an issue with the editor itself. Vscode, for example, has an open issue about eslint and the working directory it invokes it with.

**Comment by cwbuecheler** [comment]
@ljharb - Ah. Yes, it might be a VS code issue, then. If I manually run eslint, like this:

```
../node_modules/eslint/bin/eslint.js ChartDisplay.js
```

Then it correctly outputs some lint errors. I'll set up an auto-linting on save script so I can at least see the output in the console. Hopefully VS Code will fix the issue soon.

**Comment by ljharb** [comment]
Closing in favor of https://github.com/microsoft/vscode-eslint/issues/696; if someone's still having the issue with "not vscode", please file it on eslint core, as "how eslint loads plugins" is not something this config can affect.

**Comment by cwbuecheler** [comment]
I know this is closed but just in case anyone is running into this issue, here's what was happening: I had loaded a top-level folder in VS code that contained a few items, but mostly just `client` and `server` folders. I had installed eslint and its dependencies in each of those folders, and was getting the error shown above. The fix? install eslint at the top level. It's stupid, since I don't need or want a node_modules folder at the top level, but it's worth it to have in-editor linting.

**Comment by kacperborkowski** [comment]
So, anyone resolved this? It's really anoying...

**Comment by cwbuecheler** [comment]
@kacperborkowski - did you try installing eslint and its dependencies at the top level of the project you're loading in Code? eg if your structure is:
```
/Users/user/Documents/GitHub/app/frontend/
```
But you're loading all of `/app` into VS Code as a project, you'll need to install ESlint and all the dependencies in `/app`. It's not going to work if you only have ESlint and the deps installed in `/frontend`, unless you only load that folder (and sub-folders) in as the top level of the project.

**Comment by kacperborkowski** [comment]
> @kacperborkowski - did you try installing eslint and its dependencies at the top level of the project you're loading in Code? eg if your structure is:
> 
> ```
> /Users/user/Documents/GitHub/app/frontend/
> ```
> 
> But you're loading all of `/app` into VS Code as a project, you'll need to install ESlint and all the dependencies in `/app`. It's not going to work if you only have ESlint and the deps installed in `/frontend`, unless you only load that folder (and sub-folders) in as the top level of the project.

Ok, it's worked. Thanks.

**Comment by martinowren** [comment]
> @kacperborkowski - did you try installing eslint and its dependencies at the top level of the project you're loading in Code? eg if your structure is:
> 
> ```
> /Users/user/Documents/GitHub/app/frontend/
> ```
> 
> But you're loading all of `/app` into VS Code as a project, you'll need to install ESlint and all the dependencies in `/app`. It's not going to work if you only have ESlint and the deps installed in `/frontend`, unless you only load that folder (and sub-folders) in as the top level of the project.

You sir, just fixed my whole life <3

**Comment by cwbuecheler** [comment]
@martinowren - glad to be of service!

**Comment by Abibibi** [comment]
> @kacperborkowski - did you try installing eslint and its dependencies at the top level of the project you're loading in Code? eg if your structure is:
> 
> ```
> /Users/user/Documents/GitHub/app/frontend/
> ```
> 
> But you're loading all of `/app` into VS Code as a project, you'll need to install ESlint and all the dependencies in `/app`. It's not going to work if you only have ESlint and the deps installed in `/frontend`, unless you only load that folder (and sub-folders) in as the top level of the project.

Thank you! I confirm that this worked for me too! just launched a `yarn init` at the root of my repo, copied the code below and then typed `yarn`

```
{
  "name": "serialkiller",
  "version": "1.0.0",
  "main": "index.js",
  "repository": "git@github.com:O-clock-Universe/projet-SerialKiller.git",
  "author": "Abibibi <abeba.ngwe@gmail.com>",
  "license": "MIT",
  "devDependencies": {
    "@babel/core": "*",
    "@babel/plugin-proposal-class-properties": "*",
    "@babel/plugin-proposal-object-rest-spread": "*",
    "@babel/preset-env": "*",
    "@babel/preset-react": "*",
    "@babel/register": "*",
    "autoprefixer": "*",
    "babel-eslint": "*",
    "babel-loader": "*",
    "chai": "*",
    "css-loader": "*",
    "enzyme": "*",
    "enzyme-adapter-react-16": "*",
    "eslint": "*",
    "eslint-config-airbnb": "*",
    "eslint-import-resolver-webpack": "*",
    "eslint-plugin-import": "*",
    "eslint-plugin-jsx-a11y": "*",
    "eslint-plugin-react": "*",
    "file-loader": "*",
    "html-webpack-plugin": "*",
    "ignore-styles": "*",
    "mini-css-extract-plugin": "*",
    "mocha": "*",
    "node-sass": "*",
    "optimize-css-assets-webpack-plugin": "*",
    "postcss": "*",
    "postcss-loader": "*",
    "sass-loader": "*",
    "style-loader": "*",
    "stylelint": "*",
    "stylelint-config-recommended": "*",
    "uglifyjs-webpack-plugin": "*",
    "webpack": "*",
    "webpack-cli": "*",
    "webpack-dev-server": "*"
},
  "scripts": {
    "test": "mocha --require tests/.setup.js tests/**/*.test.js",
    "test:watch": "mocha --watch --require tests/.setup.js tests/**/*.test.js",
    "start": "webpack-dev-server",
    "clean": "rm -rf dist",
    "clean:all": "rm -rf dist node_modules",
    "build:dev": "NODE_ENV=development webpack",
    "build:dev:win": "set NODE_ENV=development && webpack",
    "build:prod": "NODE_ENV=production webpack --mode production",
    "build:prod:win": "set NODE_ENV=production && webpack --mode production",
    "save-deps": "node updateDeps.js"
  }
}
```

**Comment by rtgdemming** [comment]
For other people not wanting to reinstall all their npm dependencies:
Edit the settings.json of your workspace and add
`"eslint.workingDirectories":["{YOUR_FOLDER}"]`
to the `"settings"` object.

**Comment by sktguha** [comment]
@rtgdemming thanks . it worked for me on mac. on command line it was working but in vscode it was not working. now it has worked

**Comment by floriansr** [comment]
Same here thank you so much @rtgdemming !!

**Comment by thienedits** [comment]
I am still getting this error. I am using vscode on windows, have .eslintrc in the root folder opened in vscode as well.

**Comment by eegcode** [comment]
I did not get the solution of top level folder and blah blah blah. I mean I did not understand. Anyone please explain a bit more.

**Comment by nonstopper0** [comment]
I am having the same issue but this solution doesn't make sense for me. Just working in a simple create-react-app. I have not touched any related to ESLINT and my project was working fine last night but yet when I opened my project this morning this error appeared...

**Comment by karanalpe** [comment]
> I am having the same issue but this solution doesn't make sense for me. Just working in a simple create-react-app. I have not touched any related to ESLINT and my project was working fine last night but yet when I opened my project this morning this error appeared...
> 
> No higher level project folders and I'm opening directly into the CRA through VSCODE

The same error here. I tried many things
- Add eslint.workingDirectories (auto and project)
- Downgraded version
- Change local .eslintrc.js to /src
- Reinstall VsCode and Plugins
- ...


I'm using:
- macOs 10.15.7
- vsCode 1.54.2 (Universal)
- ESLint plugin vsCode 2.1.17
- Prettier plugin vsCode 6.2.0
- package.json
```
{
  "name": "curso-node-typescript",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "dev": "nodemon src/server.ts",
    "build": "sucrase ./src -d ./dist --transforms typescript,imports"
  },
  "devDependencies": {
    "@types/cors": "^2.8.9",
    "@types/express": "^4.17.9",
    "@types/mongoose": "^5.10.3",
    "@typescript-eslint/eslint-plugin": "^4.10.0",
    "@typescript-eslint/parser": "^4.10.0",
    "eslint": "^7.15.0",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-plugin-import": "^2.22.1",
    "nodemon": "^2.0.6",
    "sucrase": "^3.16.0",
    "typescript": "^4.1.3"
  },
  "dependencies": {
    "cors": "^2.8.5",
    "eslint-config-prettier": "^7.0.0",
    "eslint-import-resolver-typescript": "^2.3.0",
    "eslint-plugin-prettier": "^3.3.0",
    "express": "^4.17.1",
    "mongoose": "^5.11.8",
    "prettier": "^2.2.1"
  }  
}
```
- .eslintrc.js
```
module.exports = {
  env: {
    browser: true,
    es2021: true,
  },
  extends: [
    'plugin:@typescript-eslint/recommended',
    'prettier/@typescript-eslint',
    'airbnb-base',
  ],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaVersion: 12,
    sourceType: 'module',
  },
  plugins: ['@typescript-eslint'],
  rules: {
    'linebreak-style': 0,
    'no-console': 'off',
    'class-methods-use-this': 'off',
    'max-len': 'off',
    'no-unused-vars': 'off',
    'no-shadow': 'off',
    'consistent-return': 'off',
    'lines-between-class-members': 'off',
    'no-use-before-define': 'off',
    'no-param-reassign': 'off',
    'no-undef': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    '@typescript-eslint/no-empty-function': 'off',
    '@typescript-eslint/no-unused-vars': 'off',
    'import/extensions': [
      'error',
      'ignorePackages',
      {
        js: 'never',
        jsx: 'never',
        ts: 'never',
        tsx: 'never',
      },
    ],
  },
  settings: {
    'import/resolver': {
      typescript: {},
    },
  },
};

```


Look this error:
```
[Info  - 8:28:42 AM] ESLint server is starting
[Info  - 8:28:43 AM] ESLint server running in node v12.18.3
[Info  - 8:28:43 AM] ESLint server is running.
[Info  - 8:28:46 AM] ESLint library loaded from: /Users/macbook/Documents/dev/git/curso-fullstack-back-template/node_modules/eslint/lib/api.js
[Error - 8:28:48 AM] 
Failed to load plugin '@typescript-eslint' declared in '../../../../.eslintrc.js': Cannot find module '@typescript-eslint/eslint-plugin'
Require stack:
- /Users/macbook/Documents/__placeholder__.js
Referenced from: /Users/macbook/Documents/.eslintrc.js
Happened while validating /Users/macbook/Documents/dev/git/curso-fullstack-back-template/src/app.ts
This can happen for a couple of reasons:
1. The plugin name is spelled incorrectly in an ESLint configuration file (e.g. .eslintrc).
2. If ESLint is installed globally, then make sure '@typescript-eslint/eslint-plugin' is installed globally as well.
3. If ESLint is installed locally, then '@typescript-eslint/eslint-plugin' isn't installed correctly.

Consider running eslint --debug /Users/macbook/Documents/dev/git/curso-fullstack-back-template/src/app.ts from a terminal to obtain a trace about the configuration files used.
[Error - 8:28:49 AM] 
Failed to load plugin '@typescript-eslint' declared in '../../../.eslintrc.js': Cannot find module '@typescript-eslint/eslint-plugin'
Require stack:
- /Users/macbook/Documents/__placeholder__.js
Referenced from: /Users/macbook/Documents/.eslintrc.js
Happened while validating /Users/macbook/Documents/dev/git/curso-fullstack-back-template/.eslintrc.js
This can happen for a couple of reasons:
1. The plugin name is spelled incorrectly in an ESLint configuration file (e.g. .eslintrc).
2. If ESLint is installed globally, then make sure '@typescript-eslint/eslint-plugin' is installed globally as well.
3. If ESLint is installed locally, then '@typescript-eslint/eslint-plugin' isn't installed correctly.

Consider running eslint --debug /Users/macbook/Documents/dev/git/curso-fullstack-back-template/.eslintrc.js from a terminal to obtain a trace about the configuration files used.
```

I NEED HELP

**Comment by ljharb** [comment]
@karanjthakkar why do you have an eslint config inside your Documents folder, instead of in each individual project?

**Comment by karanjthakkar** [comment]
Wrong Karan 😁 cc: @karanalpe

**Comment by ljharb** [comment]
@karanjthakkar sorry about that! GitHub autocomplete failed me.

**Comment by nonstopper0** [comment]
My bug eventually just went away after a computer restart like nothing every happened. 

I would love to know what is happening under the hood that is causing this issue.

**Comment by karanalpe** [comment]
> @karanalpe why do you have an eslint config inside your Documents folder, instead of in each individual project?

Thanks for the answer. After many attempts. I managed to solve the problem. 

When I installed the extension esLint and prettier at vsCode, was enabled globally (/Users/macbook/Documents/).

For resolved my problem, I set the parameter root = true in .eslintrc.js. That way eslint started to capture the file correctly. Look:

```
[Info  - 1:02:29 PM] ESLint server is starting
[Info  - 1:02:30 PM] ESLint server running in node v12.18.3
[Info  - 1:02:30 PM] ESLint server is running.
[Info  - 1:02:34 PM] ESLint library loaded from: /Users/macbook/Documents/dev/git/curso-fullstack-back-final/node_modules/eslint/lib/api.js
```

**Comment by ljharb** [comment]
Global configs are deprecated in eslint. Everything should be only installed, and configured, per-project.

**Comment by jamidwyer** [comment]
If anyone else ends up here with this error, I'm embarrassed to say that in my case, I had manually typed a11y as "ally" with the letter "l" in my eslintrc.

**Comment by ebereber** [comment]
-delete node modules and package-lock.json
- npm install --force

**Comment by waisay1422** [comment]
hello bro this gpu problem upgrade you pc

**Comment by marjanganjizadeh** [comment]
error :[eslint] Failed to load config "react-app" to extend from.
delete  these two iteme in package.json :
"eslintConfig": {
    "extends": [
      "react-app", (delete)
      "react-app/jest" (delete)
    ]
  },  
and write :
  "eslintConfig": {
    "extends": []
  },

**Comment by diegomtzb** [comment]
Old post still could help. In my case it started to happen when installed React DevTools Chrome extension. Uninstalled it and error gone.

**Comment by Eunit99** [comment]
> -delete node modules and package-lock.json
> 
> * npm install --force

I did this and the issue was resolved. Basically, I ran his command in my work directory:

`rm -r node_modules/ && rm package-lock.json && npm i -f` and that was all.

Hope this helps someone.
