### ISSUE TITLE
Add support for latest version of eslint-plugin-react-hooks

### ISSUE THREAD

**Issue by kaiyoma** [airbnb/javascript#2084]
If you install the latest version of all eslint-related libraries, `yarn install` spits out this warning:

```
eslint-config-airbnb@18.0.1" has incorrect peer dependency "eslint-plugin-react-hooks@^1.7.0".
```

eslint-plugin-react-hooks is now up to version 2.0.1.

**Comment by ljharb** [comment]
Indeed, at the moment we only support v1.

What are the breaking changes in v2?

**Comment by kaiyoma** [comment]
I'm actually not sure. I only noticed the `yarn install` warning and figured I should open an issue.

**Comment by ljharb** [comment]
Someone filed #2083 but also didn’t answer the question.

**Comment by tomprats** [comment]
Looks like the breaking change is forbidding top level use*() calls:

- Version Change: https://github.com/facebook/react/pull/16528
- Code Change: https://github.com/facebook/react/pull/16455

**Comment by DavidHenri008** [comment]
Is there some change concerning this warning?

**Comment by AndreiBehel** [comment]
Any updates on this issue?

**Comment by balovbohdan** [comment]
Any progress, guys?

**Comment by oleblaesing** [comment]
I'm also interested in solving this issue. Are there some updates on those open PRs?

**Comment by LiveFreeAndRoam** [comment]
I am also seeing this issue.

What are the plans for airbnb's support for latest eslint-plugin-react-hooks?  If it is no longer keeping pace then I will begin migrating my team away from it.  In which case, I'd appreciate alternative recommendations.

**Comment by ljharb** [comment]
This is done in #2090
