### ISSUE TITLE
UNSAFE methods

### ISSUE THREAD

**Issue by nedimcimpo** [airbnb/javascript#2091]
Unsafe lifecycle methods should be named accordingly

UNSAFE_componentWillMount()
UNSAFE_componentWillUpdate()
UNSAFE_componentWillReceiveProps()

**Comment by ljharb** [comment]
That’s advice that only applies to you if you’re using React 16.3+, and that React itself will tell you about - I’m not sure what’s actionable here, so I’ll close this.
