### ISSUE TITLE
Undescore param name

### ISSUE THREAD

**Issue by alexalannunes** [airbnb/javascript#2092]
Why colors of the param names on a function changes color when put _ (underscore)?

### without underscore
![aaaa](https://user-images.githubusercontent.com/16847836/65266607-c6429c00-dae9-11e9-82ff-e17cc317e104.png)

### With underscore
![bbb](https://user-images.githubusercontent.com/16847836/65266634-d2c6f480-dae9-11e9-9b78-2d8ed6a50d1a.png)

**Comment by ljharb** [comment]
That’s up to your particular editor and code highlighting settings - i don’t know why.

**Comment by alexalannunes** [comment]
Sorry :)

**Comment by alexalannunes** [comment]
Someone can delete this issue?
