### ISSUE TITLE
Configure function-call-argument-newline rule

### ISSUE THREAD

**Issue by galvarez421** [airbnb/javascript#2094]
It seems that all non-deprecated and non-removed rules currently on https://eslint.org/docs/rules/ are configured in the base config except for `function-call-argument-newline`.

The style guide does not seem to specify the preferred style in this case, but the following configuration seems to be generally consistent with the other style rules:

`'function-call-argument-newline': ['error', 'consistent'],`

**Comment by ljharb** [comment]
let’s add it now as “off”, with a comment to enable it later as minor or major

**Comment by rahilvora** [comment]
Can I work on this?

**Comment by ljharb** [comment]
yep, that's what the label means :-)

**Comment by mrseanbaines** [comment]
Looks like this is already done?
https://github.com/airbnb/javascript/blob/64b965efe0355c8290996ff5a675cd8fb30bf843/packages/eslint-config-airbnb-base/rules/style.js#L79-L81

**Comment by ljharb** [comment]
You're right; added in dee4f172e752f3e6180f88409aa4424de02f9d4c as part of #2108.
