### ISSUE TITLE
Suggest labeling 'good first issue' for newcomers.

### ISSUE THREAD

**Issue by SunflowerPKU** [airbnb/javascript#2095]
I find many popular projects recommend certain issues for newcomers to help them contribute successfully. They often label these issues using tags such as 'good first issue', 'easy', 'for newbie', etc. I suggest we can use this mechanism to attract newcomers. How do you think of my suggestion?

**Comment by ljharb** [comment]
This really isn’t the kind of project that encourages casual contribution; we have the “pull request wanted” label already for things that are amenable to PRs.
