### ISSUE TITLE
[JS style problem 19.5] How to end files with a single newline character?

### ISSUE THREAD

**Issue by ginhton** [airbnb/javascript#2096]
a note from [19.5](https://github.com/airbnb/javascript#whitespace--newline-at-end)

Where is the difference between the first snippet and the third when I am using an editor to code.

```javascript
// bad
import { es6 } from './AirbnbStyleGuide';
  // ...
export default es6;

// bad
import { es6 } from './AirbnbStyleGuide';
  // ...
export default es6;↵
↵

// good
import { es6 } from './AirbnbStyleGuide';
  // ...
export default es6;↵
```

**Comment by ljharb** [comment]
It means you'll want to configure your editor such that when you save a file, it automatically adjusts trailing newlines such that if you `cat` the file on the command line, it has a trailing newline.

**Comment by ginhton** [comment]
Thank you!
