### ISSUE TITLE
How to fix no-useless-escape in RegExp?

### ISSUE THREAD

**Issue by jvmunhoz** [airbnb/javascript#2098]
I receive a no-useless-escape ESLint error on the second **\\?** when writing a RegExp like this:

```js
RegExp(/\?navegacao=([^\?]*)/)
```

for use in strings like this 
```js
mov-react-native-login?navegacao=PayOrReceiveReadingQRCode
```

So the second **"?"** should not be escaped?

```js
RegExp(/\?navegacao=([^?]*)/)
```

I've also seen other people recommending to escape the **"\\"**, but I don't actually understand why...

```js
RegExp(/\?navegacao=([^\\?]*)/)
```

I've tested all 3 cases, ["\\?"](https://i.imgur.com/L7WurDx.png), ["?"](https://i.imgur.com/y3oPkvX.png) and ["\\\\?"](https://i.imgur.com/urdujaE.png), all to the same result. So, what would be the best use to follow the no-useless-escape rule?

**Comment by ljharb** [comment]
Yes, that's correct - inside a character class, the `?` has no special meaning and thus does not need to be escaped.

Yes, follow the rule - that's why this config enables it.
