### ISSUE TITLE
Unexpected token =, for component props.

### ISSUE THREAD

**Issue by nazarposhta** [airbnb/javascript#2099]
Hi. I'm just getting error  `Unexpected token =` when trying to write prop parameter to React component. 
Like this: 
![Screenshot 2019-09-27 at 09 21 29](https://user-images.githubusercontent.com/7795112/65750376-8478ad80-e108-11e9-9ff7-3dcb019e237f.png)

```
    "eslint": "^6.4.0",
    "eslint-config-airbnb": "^18.0.1",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.14.3",
    "eslint-plugin-react-hooks": "^1.7.0",
```
```
{
    "env": {
        "browser": true,
        "es6": true
    },
    "extends": [
        "airbnb"
    ],
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": 2018,
        "sourceType": "module"
    },
    "plugins": [
        "react"
    ],
    "rules": {
    }
}
```

**Comment by ljharb** [comment]
That's because class fields is stage 3, and eslint doesn't support features until they're stage 4. You have to use a different parser if you want to support nonstandard features.

**Comment by nazarposhta** [comment]
`npm install --save-dev babel-eslint`
and 
`"parser": "babel-eslint",` - in the *.eslintrc.json* file resolved the problem
