### ISSUE TITLE
[eslint-config-airbnb] Update react/sort-comp rule to allow static variables

### ISSUE THREAD

**Issue by alexplumb** [airbnb/javascript#2107]
As of `eslint-plugin-react@7.15.0`, the `static-methods` rule for `react/sort-comp` has seen a breaking change: it's been split into `static-methods` and `static-variables`. [See the relevant pull request](https://github.com/yannickcr/eslint-plugin-react/pull/2408)

Please change the [rule for react/sort-comp](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/react.js#L241) to allow for static variables like so:

```
order: [
        'static-variables',
        'static-methods',
        'instance-variables',
        'lifecycle',
        '/^on.+$/',
        'getters',
        'setters',
        '/^(get|set)(?!(InitialState$|DefaultProps$|ChildContext$)).+$/',
        'instance-methods',
        'everything-else',
        'rendering',
      ],
```

**Comment by ljharb** [comment]
It's not a breaking change; `static-methods` never checked what `static-variables` checks. Adding that seems reasonable, though, and it'd be semver-patch since the airbnb guide currently doesn't allow using class fields at all.

**Comment by alexplumb** [comment]
Ah, makes sense. I upgraded to the newest version and suddenly it was complaining that my static variables had to be at the bottom of the class definition.
