### ISSUE TITLE
react/sort-comp event handlers

### ISSUE THREAD

**Issue by jeffvandyke** [airbnb/javascript#2116]
This might have been gone over before, but a common practice for event handlers (currently documented as `/^on.+$/`) is to start them with `handle...`, as in `handleClick()`. This is seen all over the React docs, including the home page, and it allows a clear convention for names of props (`/^on.+$/`) vs handlers defined on that instance (`/^handle.+$/`).

Since some people might allow usage of `on` as the method name of a handler, is there any opposition to add (`/^handle.+$/`) before the (`/^on.+$/`) entry for the `react/sort-comp` rule?

**Comment by ljharb** [comment]
This is something you could configure for yourself, so your question is about changing the default?

**Comment by jeffvandyke** [comment]
I think it's common enough of a practice (React docs) to make the default, but that's my opinion, and I'm curious if others concur.

**Comment by ljharb** [comment]
The React docs recommend a number of antipatterns that this guide does not :-) but in this case it doesn't seem problematic to allow.

**Comment by jeffvandyke** [comment]
Awesome! I might have time to get that implemented... (and I agree on the other react doc recommendations, good to handle those instances on a case-by-case basis)
