### ISSUE TITLE
Prevent repeated require statements for the same module

### ISSUE THREAD

**Issue by marcospgp** [airbnb/javascript#2119]
Currently this:

```js
const { exec } = require("child_process");
const { execSync } = require("child_process");
```

is allowed. There should be a rule that forces this to be done in a single line:

```js
const { exec, execSync } = require("child_process");
```

**Comment by ljharb** [comment]
Please file an issue on eslint core or eslint-plugin-import; once the rule exists we can discuss enabling it here.

**Comment by marcospgp** [comment]
https://www.npmjs.com/package/eslint-plugin-import

> Ensure imports point to a file/module that can be resolved. (no-unresolved)

Doesn't the rule already exist? I even think I've had it work before with this config... not sure though!
