### ISSUE TITLE
many if blocks vs switch-case

### ISSUE THREAD

**Issue by myBestSoftAndPref** [airbnb/javascript#2120]
First variant should be theoretically faster, second variant is shorter and more explicit. I don't know which is better. Just imagine how many sub blocks will be for a case with more then 100 variables if you choose the variant with `if`.
```js
const cond = 'blue';
const one =  'green';
const two = 'red';
const three = 'blue';

// bad???
if(cond === one) {
  // do one
} else if (cond === two) {
  // do two
} else if(cond === three) {
  // do three
}

// good???
switch(true) {
  case cond === one: {
    // do one
    break;
  }
  case cond === two: {
    // do two
    break;
  }
  case cond === three: {
    // do three
    break;
  }
}
```

**Comment by ljharb** [comment]
Performance is not the most important consideration, and in neither case do i suspect it would be a bottleneck.

The primary consideration is readability, maintainability, and how prone the pattern is to bugs. switch fails all of these tests.
