### ISSUE TITLE
computed property brackets

### ISSUE THREAD

**Issue by luhaopeng** [airbnb/javascript#2127]
[19.16](https://github.com/airbnb/javascript#whitespace--computed-property-spacing)

> Enforce spacing inside of computed property brackets.
> ``` javascript
> // bad
> obj[foo ]
> obj[ 'foo']
> var x = {[ b ]: a}
> obj[foo[ bar ]]
> 
> // good
> obj[foo]
> obj['foo']
> var x = { [b]: a }
> obj[foo[bar]]
> ```

I'm not sure if I get it right, but, should it be 'Avoid' instead of 'Enforce' ?

**Comment by ljharb** [comment]
"enforce" means either "require" or "forbid" - in htis case, it's enforcing the absence of spaces.

**Comment by ljharb** [comment]
See also https://github.com/airbnb/javascript/pull/1946#discussion_r229344251

**Comment by luhaopeng** [comment]
Oh I see...Thanks!
