### ISSUE TITLE
class-methods-use-this is enforced, but not documented

### ISSUE THREAD

**Issue by IGassmann** [airbnb/javascript#2129]
The ESLint rule `class-methods-use-this` is enforced, however, it is currently not documented.

It would be nice to mention that it is okay to override the rule for when a spec from an external library requires to overwrite a method as a regular function (and not as a static method) and does not use this inside the function body. See https://gitter.im/airbnb/javascript?at=5d9ca07deac5612d22d83151.

**Comment by ljharb** [comment]
It's OK to override any rule, but certainly the rationale for this rule should be added to the guide.

**Comment by IGassmann** [comment]
Closed by https://github.com/airbnb/javascript/pull/2130
