### ISSUE TITLE
react/static-property-placement rule conflict

### ISSUE THREAD

**Issue by corsicanec82** [airbnb/javascript#2139]
Hello!

In the rule react/static-property-placement, eslint-plugin-react sets the value of static public field to enabled by default.
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/static-property-placement.md#when-static-public-field-is-enabled-default

But eslint-config-airbnb sets this rule to a property assignment. And I don’t see where it is written about it. There is a conflict, and when using airbnb I can not use the recommendations of the plugin react.

Tell me, it should be so or is it a bug? 
Thanks.

**Comment by ljharb** [comment]
The airbnb guide has not yet been updated to allow class fields (which received stage 3 relatively recently), until that time, the guide forbids their use.

**Comment by ljharb** [comment]
Also, eslint's default parser (which the airbnb guide uses) only parses stage 4 proposals.

In the meantime, you can override rule configs yourself if needed.
