### ISSUE TITLE
bug in no-multiple-empty-lines

### ISSUE THREAD

**Issue by Zamiell** [airbnb/javascript#2140]
The following comment:

https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/style.js#L314-L316

implies that there should be no new lines at the beginning of a file. But that is not what the rule is configured to do. Currently, the rule allows one empty line at the beginning of a file, which seems strange. For example:

Dog1.js
```
// This is how my dog class should be, with no empty lines at the beginning of the file
class Dog {}
```

Dog2.js
```

// I accidentally put a new line at the beginning of the file,
// but the Airbnb eslint rules don't care about this and give no errors
class Dog {}
```

Dog3.js
```


// I accidentally put two new lines at the beginning of the file,
// the Airbnb eslint rules care about this and throw an error
class Dog {}
```

It looks like `maxBOF: 1` should be changed to `maxBOF: 0`, correct me if I am wrong.

**Comment by ljharb** [comment]
This was added in a344d6c8e7f21e6af107ed3e335068bf6a621c5d.

Changing it to 0 seems reasonable (I'm not sure why it wasn't set that way to begin with) but it's a breaking change, so the PR would have to wait until the next one.
