### ISSUE TITLE
Cannot find module 'eslint-plugin-import'

### ISSUE THREAD

**Issue by Rotinx** [airbnb/javascript#2141]
I've been encountering this issue while trying to setup eslint with airbnb. Using this npx package.
https://www.npmjs.com/package/eslint-config-airbnb-base

ESlint output
```bash
Failed to load plugin 'import' declared in 'server\.eslintrc.js » eslint-config-airbnb-base » Z:\Development\JS\Nuxt-Test-App\zuka-ma-shlong\server\node_modules\eslint-config-airbnb-base\rules\imports.js': Cannot find module 'eslint-plugin-import'
```
package.json
```json
{
  "name": "server",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "cors": "^2.8.5",
    "eslint": "6.1.0",
    "eslint-config-airbnb-base": "14.0.0",
    "eslint-plugin-import": "^2.18.2",
    "express": "^4.17.1"
  }
}
```
.eslintrc.js
```js
module.exports = {
  env: {
    browser: true,
    commonjs: true,
    es6: true,
    node: true,
  },
  extends: [
    'airbnb-base',
  ],
  globals: {
    Atomics: 'readonly',
    SharedArrayBuffer: 'readonly',
  },
  parserOptions: {
    ecmaVersion: 2018,
  },
  rules: {
  },
};
```
eslint-plugin-import is however installed locally aswell as eslint. 

I've attempted installing the package with yarn which also didn't seem to work either. [Issue link](https://github.com/facebook/create-react-app/issues/6391)

At this point I've ran out of ideas to get this working.

**Comment by ljharb** [comment]
How are you running eslint?

**Comment by Rotinx** [comment]
locally ./node_modules/.bin/eslint 
I also have the eslint plugin installed.

**Comment by ljharb** [comment]
Does npm ls exit successfully?

**Comment by Rotinx** [comment]
yes.

**Comment by ljharb** [comment]
What version of node and npm?

**Comment by Rotinx** [comment]
v10.16.3 Nodejs
6.9.0 NPM

**Comment by ljharb** [comment]
I'm pretty confused; that should work fine. You can try `npm install -g npm@6.12`, but i doubt that will make a difference.

**Comment by Rotinx** [comment]
mmmm yeah same I'll give it a crack.

**Comment by Rotinx** [comment]
Nope didn't work.
Proof eslint import is installed.
![image](https://user-images.githubusercontent.com/39930952/69897018-be855a80-13aa-11ea-9c9a-ca98c62364b8.png)

**Comment by ljharb** [comment]
Seems like an issue worth filing on eslint itself, then.

**Comment by Rotinx** [comment]
I wonder if it's only me having this issue.

**Comment by Rotinx** [comment]
I've now also tried the latest verison of npm (6.13.1) it also doesn't work.

**Comment by ljharb** [comment]
6.13 is broken on WSL; i'd try 6.12 explicitly.

**Comment by Rotinx** [comment]
Yeah tried it before and it didn't work either sadly.

**Comment by ljharb** [comment]
Thanks for filing https://github.com/eslint/eslint/issues/12623

**Comment by Rotinx** [comment]
no problem :)

**Comment by Tedotieno** [comment]
The problem could be:  eslint compatibility issues between eslint and eslint-config-airbnb-base

I downgraded to the latest eslint verson 5 through npm i eslint@^5 and it worked for me.

Hope it helps.

**Comment by Rotinx** [comment]
The problem was I was using eslint outside of the root directory of the project.
Thank you for following up.

**Comment by joelb01-github** [comment]
@Rotinx I seem to have the same issue as you; can you please expand on your solution and what you meant by "was used outside the root directory"?

**Comment by Rotinx** [comment]
Hey @joelb01-github, unfortunately I can not entirely recall. I realise now looking back my explanation is terrible sorry about that. I believe it was due to me having ealint installed twice within the same directory.

/ (Installed here) 
/Frontend (also installed here)

Though I'm not sure if that's the solution sorry. I would throw the project your having a issue with into a separate folder outside of the root project folder to test if it works outside of it.

**Comment by joelb01-github** [comment]
@Rotinx thanks for coming back to me :)

I ended up making it work; in my case my `.eslintrc` had a wrong syntax - the error was quite misleading tho..

**Comment by Rotinx** [comment]
@joelb01-github np, I agree it's a bit of a pain.

**Comment by chrisribe** [comment]
> Hey @joelb01-github, unfortunately I can not entirely recall. I realise now looking back my explanation is terrible sorry about that. I believe it was due to me having ealint installed twice within the same directory.
> 
> / (Installed here)
> /Frontend (also installed here)
> 
> Though I'm not sure if that's the solution sorry. I would throw the project your having a issue with into a separate folder outside of the root project folder to test if it works outside of it.

I was able to get my eslint working in visual studio code by opening the subfolder where my node_modules reside,

My project structure is:
-Main Folder
-->api
-->auth
-->db
-->**ui** (npm folder with eslint etc)

So opened the ui folder and it loaded.

**Comment by andreasvirkus** [comment]
@joelb01-github thank you!! Wrestled with this for quite some time. Cleaning out my ESLint config finally resolved it.
