### ISSUE TITLE
Bad example for 7.13 Never reassign parameters. eslint:

### ISSUE THREAD

**Issue by kosmom** [airbnb/javascript#2142]
```
// good
function f3(a) {
  const b = a || 1;
  // ...
}
```
When you call function without parameter `f3()` and with parameter equals `false` do you have equals result
`f3() -> b=1`
`f3(0) -> b=1`
do you expectations see `f3(0) -> b=0`

**Comment by ljharb** [comment]
In this case, the `||` is intended to produce `1` whenever `a` is falsy, so i think the example is fine.

**Comment by kosmom** [comment]
Ok. It can be understood as set variable default parameter.
In context as reassign parameter it's good example
