### ISSUE TITLE
Section 7.2 (IIFE wrapping) example has an error

### ISSUE THREAD

**Issue by grubin667** [airbnb/javascript#2144]
I believe the example:

`// immediately-invoked function expression (IIFE)
(function () {
  console.log('Welcome to the Internet. Please follow me.');
}());`

should be:

`// immediately-invoked function expression (IIFE)
(function () {
  console.log('Welcome to the Internet. Please follow me.');
})();`

Last line has misplaced parenthesis, no?

**Comment by ljharb** [comment]
No - the invoking parentheses for IIFEs should go inside the containing parens. The IIFE is a single unit contained by parens, and the invocation is part of that unit.

**Comment by grubin667** [comment]
Sorry, Jordan, but I'm not convinced. See [https://flaviocopes.com/javascript-iife/](url) and [https://developer.mozilla.org/en-US/docs/Glossary/IIFE](url).

They sure look like my "should be".

**Comment by ljharb** [comment]
It’s syntactically valid either way - “should” in this case is a matter of opinion, and I’ve stated the one this guide holds.

MDN is a wiki, so i can certainly update it, but it’s not an authority either way.
