### ISSUE TITLE
const is a global variable and it is not block scoped.

### ISSUE THREAD

**Issue by ikeola13** [airbnb/javascript#2149]
<img width="901" alt="Screen Shot 2020-01-07 at 10 03 22 AM" src="https://user-images.githubusercontent.com/29949632/71882561-febbc380-3134-11ea-99a5-4d16cec31dc7.png">

console.log(b); // ReferenceError --> this is invalid. this line returns 1.

**Comment by ericblade** [comment]
Seems like you have a 'b' hanging out in your global scope for some reason.

![image](https://user-images.githubusercontent.com/1451847/71884186-cea8fc00-3105-11ea-98cf-9114dc9793ac.png)

**Comment by ikeola13** [comment]
true true. 
seen that and checked it. 
you are correct
