### ISSUE TITLE
TypeValue: Cannot read property 'properties' of undefined

### ISSUE THREAD

**Issue by rostaryms** [airbnb/javascript#2152]
Hi,

I'm following along a video online tutorial where I'm trying to type in 'npm run dev'. I get the error below. Anyone know what's going on?

![JS_Error](https://user-images.githubusercontent.com/56840832/72834055-137c7900-3c56-11ea-82d0-3efab01e3d4b.png)

**Comment by ljharb** [comment]
This is a repo for Airbnb's JavaScript style guide, not a general help repo.

That said, this looks like an error from webpack-cli, so you'll want to file it there.
