### ISSUE TITLE
ESLint couldn't find the config "airbnb" to extend from

### ISSUE THREAD

**Issue by vadimhp** [airbnb/javascript#2156]
Hello,

I ran `npx install-peerdeps -g eslint-config-airbnb` and then `npm -g install eslint-config-airbnb` as an administrator, and this is my `.eslintrc` file in my user home directory:

```
{
  "env": {
    "es6": true,
    "browser": true,
    "jquery": true
  },
  "extends": "airbnb"
}
```

but still, when I try to `eslint file.js`, it's giving me the following error:
```
Oops! Something went wrong! :(

ESLint: 6.1.0.

ESLint couldn't find the config "airbnb" to extend from. Please check that the name of the config is correct.

The config "airbnb" was referenced from the config file in "C:\Users\vadim\.eslintrc".

If you still have problems, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

Does anybody have any idea what's going on?

**Comment by ljharb** [comment]
All eslint things must be installed locally, not globally.

**Comment by vadimhp** [comment]
I just ran the same things without the `-g` flags in the project directory and still get the same error

**Comment by ljharb** [comment]
It looks like you have an `.eslintrc` inside your user dir - I'd remove that, and make sure you've added an `.eslintrc` in your project dir, with `"root": true` in it.

**Comment by vadimhp** [comment]
That worked! Thanks a lot Jordan!
