### ISSUE TITLE
Disable the prefer-object-spread rule for airbnb-base/legacy?

### ISSUE THREAD

**Issue by justinhelmer** [airbnb/javascript#2169]
Hello,

We are in the process of revamping a large volume of code using ESLint + airbnb. We are using the `airbnbn-base/legacy` version, because the codebase is not transpiled and must support a large range of browsers.

One thing I noticed is that the `prefer-object-spread` rule is not disabled, which surprised me. Running `eslint --fix` converts all `Object.assign({}, obj)` statements to `{ ...obj }`. Since the [Object/Rest spread proposal](https://github.com/tc39/proposal-object-rest-spread) didn't land into the spec until [2018](https://github.com/tc39/proposals/blob/master/finished-proposals.md), I was surprised to see that this rule was still enabled in legacy.

Was this perhaps an oversight, or is there something I am missing? The spread operator does not have the [support we need](https://caniuse.com/#search=javascript%20spread) to use at this time.

Maybe I am misunderstanding the meaning of `legacy` and we need to more carefully analyze the complete ruleset?

Thanks for the info.

**Comment by ljharb** [comment]
Yes, that should be disabled in the legacy config - i'd say it's an oversight.
