### ISSUE TITLE
Add best conditional rule to Arrays 4.7 

### ISSUE THREAD

**Issue by umairx97** [airbnb/javascript#2187]
Add "best" style guide rule to Arrays [4.7](https://github.com/airbnb/javascript#arrays--callback-return) 
Currently, this is written on the documentation 
```
// good
inbox.filter((msg) => {
  const { subject, author } = msg;
  if (subject === 'Mockingbird') {
    return author === 'Harper Lee';
  }

  return false;
});
```

I think it would be better combining conditionals based on [Eslint Operator Line break](https://eslint.org/docs/rules/operator-linebreak)  and [no mixed operators](https://eslint.org/docs/2.13.1/rules/no-mixed-operators) 

So a simple && or || will be efficient

**Comment by ljharb** [comment]
from the PR:
> I'm not sure this adds any value to this particular rule; that we're using simple logic here for the sake of examples isn't really material. Pretend that each return value is 10 statements, and it can't be collapsed into a single expression.

**Comment by umairx97** [comment]
Closing this
