### ISSUE TITLE
Eslint comment re: 'no-warning-comments' opposes actual rule

### ISSUE THREAD

**Issue by alystair** [airbnb/javascript#2189]
See https://github.com/airbnb/javascript/blame/3493b060ec5efddc8a06733b5dbfe9f33cbce63e/packages/eslint-config-airbnb-base/rules/best-practices.js#L316-L317

Inverse of the comment, saying 'disallow'. Which is correct? :)

**Comment by ljharb** [comment]
The comment comes from https://eslint.org/docs/rules/no-warning-comments (as do they all), and doesn't relate to the config.
