### ISSUE TITLE
Question about the naming convention

### ISSUE THREAD

**Issue by bfunc** [airbnb/javascript#2191]
I have a question about the naming convention, I need to define and export namespace object, should it be PascalCased or not?
the styleguide specifies:
_23.3 Use PascalCase only when naming constructors or classes. eslint: new-cap_
but then, there is this statement:
_23.8 Use PascalCase when you export a constructor / class / singleton / function library / bare object._
It looks for me like a contradiction. I can't wrap my head around it, please help.

**Comment by ljharb** [comment]
Can you provide some code? “export namespace object” sounds like you’re using export syntax, but also exporting a single object rather than using individual named exports.

**Comment by bfunc** [comment]
Sure, should be a diffrence in regular naming i.e defining a const and export?

**Code examples:**
first one, pretty sure the naming in camelCase is right here
```javascript
const someState = {
    pages: {
        selected: 'info',
        list: [
            { key: 'info', name: 'Info' },
            { key: 'users', name: 'Users' }
        ]
    }
}

export default someState ;
export { someState as intialState};
```
and second one, PascalCased as stated in guide (23.8), is it right? it is basically the same object (not constructor) as first one..
```javascript
const MyApp = {
    author: 'Peter Griffin'
}

export default MyApp;
export { MyApp as App};
```

**Comment by ljharb** [comment]
That looks right (altho it’s not good to export it twice; it’s either what the module *is*, and thus the default export, or it’s something the module *has*, and thus a named export)

**Comment by bfunc** [comment]
Please do not pay attention for export twice, is just for example. 
I cannot understand why in one case naming should be in CamelCase and in other in PascalCase, while it is same instance types? Yes, in this example there is difference in meaning, but it is subtle and easly can be messed up in different cases.. is there a strict rule how those cases can be differentiated?

**Comment by ljharb** [comment]
No, like many things, it's a conceptual difference, and requires human decision.

**Comment by bfunc** [comment]
Ok, I got the point. Just double check
```javascript
// this is bad
const InitialState = {
    pages: {
        selected: 'info'
    }
}
```
```javascript
// this is not good (better to be PascalCase), but ok
const myApp = {
    title: 'SuperApp'
}
```
Is it right?

**Comment by ljharb** [comment]
Yes, both of those seem incorrect to me.

**Comment by bfunc** [comment]
@ljharb thank you for clearing things up
