### ISSUE TITLE
relax react-hooks plugin peer dep?

### ISSUE THREAD

**Issue by billyjanitsch** [airbnb/javascript#2195]
Hi @ljharb,

It looks like you published eslint-config-airbnb@18.1.0 to npm yesterday, but didn't push some associated commits to the GitHub repo. In particular, [package.json](https://github.com/airbnb/javascript/blob/e6e6414c973d6aa5f3672296fe3cf6c399ca570a/packages/eslint-config-airbnb/package.json#L3) still lists its version as 18.0.1.

The other change that I noticed is that master's peer dependency on eslint-plugin-react-hooks is [listed as `^2.0.0 || ^1.7.0`](https://github.com/airbnb/javascript/blob/e6e6414c973d6aa5f3672296fe3cf6c399ca570a/packages/eslint-config-airbnb/package.json#L82), but the published version's dependency is on [`^2.5.0 || ^1.7.0`](https://unpkg.com/browse/eslint-config-airbnb@18.1.0/package.json).

I was going to ask if this could be relaxed back to `^2.0.0 || ^1.7.0`. The 2.5.0 release includes a [somewhat controversial change](https://github.com/facebook/react/pull/17385). Basically, one of its rules now uses ESLint's new ["suggestions" feature](https://github.com/eslint/eslint/pull/12384) instead of the auto-fix feature. Most IDE extensions haven't caught up to this feature, and there's currently no way to apply suggestions via the ESLint CLI, so I imagine many users will want to pin this dependency at 2.4.0 until they are able to properly use 2.5.0. This is not possible with the current peer dep range.

(Happy to make a new issue for this, or rename this issue, once those commits are on GH!)

Thanks, as always, for your work maintaining these configs. 😊

**Comment by ljharb** [comment]
Yes, thanks, I’m aware :-) the tags aren’t there, it’s just not pushed to master yet.

From reading the description in the PR, yes, I’ll relax it back to v2.3 in a patch.
