### ISSUE TITLE
Advise against multiple assignment in var declaration

### ISSUE THREAD

**Issue by hkdobrev** [airbnb/javascript#221]
I'd suggest to include a section in the guide explaining the scoping problems of this:

``` js
function foo() {
    var a = b = c = 1;
}
```

and to advise against it.

See http://stackoverflow.com/questions/1758576/multiple-left-hand-assignment-with-javascript

**Comment by alexreardon** [comment]
Is this redundant given that the `var` keyword is discouraged? https://github.com/airbnb/javascript/tree/es6#references

**Comment by ljharb** [comment]
@alexreardon no, you can still do `const a = b = c = 3;`

**Comment by awesomeaniruddh** [comment]
I'd like to take this on!

**Comment by ljharb** [comment]
@awesomeaniruddh thanks, that'd be great! Since we now basically forbid var in its entirety, we should focus this guide section on `const` and `let`, and make sure to link to the relevant eslint rule.

**Comment by awesomeaniruddh** [comment]
@ljharb There doesn't appear to be a relevant eslint rule.

**Comment by ljharb** [comment]
@awesomeaniruddh I believe http://eslint.org/docs/rules/one-var with the option "never" is the one I'm thinking of - we enable that [here](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/style.js#L238-L239)

**Comment by awesomeaniruddh** [comment]
@ljharb  Ah, my bad. I didn't notice that the rule works for this particular situation too. PR incoming ASAP!
