### ISSUE TITLE
Organize Imports

### ISSUE THREAD

**Issue by jorenbroekema** [airbnb/javascript#2215]
Hi!

I use VSCode as my editor and found out about the organize imports feature:
```json
{
    "editor.codeActionsOnSave": {
        "source.organizeImports": true
    }
}
```

For me this is a life changer, because it does essentially 4 things:
1. Sort import declarations by import path/source type (bare module vs absolute vs relative)
2. Alphabetically sort import declarations of the same import path/source type
3. Alphabetically sort import specifiers within an import declaration
4. Remove unused import declarations

(I tried to use babylon terminology, sorry if I got it wrong)

For 2 and 3 it seems similar to https://eslint.org/docs/rules/sort-imports but I haven't verified whether the behaviour is identical.

For 4, https://www.npmjs.com/package/eslint-plugin-unused-imports seems similar.

For 1 sadly I haven't had the time to look into if there's something out there that does this through eslint, but let me know if you know something!

Of course for all 4, they would need to be fixable by `--fix`

If all those requirements are met, we have a way to enable smooth import organising through eslint, which makes it possible to enable this in any CI, or through a command, rather than being dependent on someone's editor and their editor's settings.

Then of course the question remains whether this is something that's interesting for airbnb base config.

Right now, my team for example, has to deal with my annoying unrelated import changes in PRs which is not great, would be cool if we could run eslint --fix to fix it once and for all, and to keep it nice in an effortless way :)

**Comment by ljharb** [comment]
See eslint-plugin-import’s order rule, which you’re welcome to enable.

**Comment by jorenbroekema** [comment]
Ah sweet thanks, hadn't found that one yet, looks like it ticks all the boxes
