### ISSUE TITLE
Importing class methods from separate files

### ISSUE THREAD

**Issue by vettloffah** [airbnb/javascript#2216]
I would like to separate a long class file into multiple files by moving some methods to new files. What would be the recommended way to do that and stay inline with air bnb styling? Couldn't find anything in the docs. Thank you.

**Comment by ljharb** [comment]
The recommended way to do that is to not have a long class at all.

This isn't really an airbnb style guide question, and it's not really practical to split up a class definition (the design for it in the language basically requires it all be in the same file), so I'll close this.
