### ISSUE TITLE
label-has-associated-control throws an error in a simple situation

### ISSUE THREAD

**Issue by artur-13** [airbnb/javascript#2220]
![Аннотация 2020-05-05 210043](https://user-images.githubusercontent.com/39243562/81100709-a85d6680-8f15-11ea-8fde-af564725c0ac.png)
![Аннотация 2020-05-05 211924](https://user-images.githubusercontent.com/39243562/81101006-1d30a080-8f16-11ea-885b-88f9ed130783.png)
[Repo](https://github.com/artur-13/test-eslint) with example.
About project: cra + airbnb eslint config
Node ver: 10.19.0

**Comment by ljharb** [comment]
This is correct; the airbnb config requires *both* nesting and for-ID linking - ie, the input also has to be inside the label.

**Comment by artur-13** [comment]
Ok, thanks. I did not think to see [rule](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/react-a11y.js#L66). But how can I fix the case with the block between label and control? The block should not trigger the input

**Comment by ljharb** [comment]
Why are the label and the control not placed together? That seems like a confusing UI.

**Comment by artur-13** [comment]
> confusing UI
I think so too. The person who is responsible for the design and UI thinks that the non-clickable message between the elements of the form is ok.
Could you tell me, maybe there is a thread which provides arguments in favor of "both". 
I will share with the designer

**Comment by ljharb** [comment]
Specifically, it's that there are some devices that *only* link the input and the label when they're nested; and there's others that *only* do it when they're ID-linked. The majority, of course, support either one.

Accessibility is about 100%, which means that this design *excludes nonzero humans*, so I wouldn't consider it an OK design.
