### ISSUE TITLE
JSX: Group your true props at the beginning of your object declaration.

### ISSUE THREAD

**Issue by mfulton26** [airbnb/javascript#2222]
For similar reasons to [Group your shorthand properties at the beginning of your object declaration.](https://github.com/airbnb/javascript#objects--grouped-shorthand) should JSX `true` props not be grouped first too?

```jsx
// bad
<option
  id="option0"
  selected
/>

// good
<option
  selected
  id="option0"
/>
```

**Comment by ljharb** [comment]
See #1642; afaik there's still no internal consensus on keeping or dropping that object requirement, which means there wouldn't be any consensus on adding that requirement elsewhere.

Happy to reopen if Airbnb's internal position on it changes.
