### ISSUE TITLE
ESLint: 'React' is defined but never used.(no-unused-vars) when I add /** @jsx jsx */ pragma

### ISSUE THREAD

**Issue by hartey11** [airbnb/javascript#2228]
How do I stop eslint throwing an error when I use the jsx pragma.

I'm using the airbnb config and I've tried adding "react/jsx-uses-react": 1, as a rule which hasn't worked.

Do I need to include plugin:react/recommended in the extends when using airbnb?
```
.eslintrc.js

  extends: [
    "airbnb",
    "airbnb/hooks",
    "plugin:react-redux/recommended",
    "plugin:prettier/recommended",
    "prettier/react",
  ],
  settings: {
    react: {
      version: "detect",
    },
  },
  plugins: ["emotion", "graphql", "prettier", "react-redux"],
  rules: {
    "emotion/jsx-import": "error",
    "emotion/no-vanilla": "error",
    "emotion/import-from-emotion": "error",
    "emotion/styled-import": "error",
    "react/jsx-filename-extension": [1, { extensions: [".js", ".jsx"] }],
    "graphql/template-strings": [
      `error`,
      {
        env: `relay`,
        tagName: `graphql`,
      },
    ],
  },
```
```
layout.js

/* ESLint: 'React' is defined but never used.(no-unused-vars) */
import React from "react" 
import PropTypes from "prop-types"
import { useStaticQuery, graphql } from "gatsby"

/** @jsx jsx */
import { Global, css, jsx } from "@emotion/core"
import { ThemeProvider } from "emotion-theming"
```

**Comment by ljharb** [comment]
If you're using the jsx pragma, then you don't need React to be in scope when jsx is present.

**Comment by hartey11** [comment]
If I remove react I start getting `JSX is used without importing React`

<img width="511" alt="Screenshot 2020-05-16 at 9 29 06 pm" src="https://user-images.githubusercontent.com/6071669/82129665-555c9c80-97bc-11ea-969c-c75580ddf131.png">

**Comment by ljharb** [comment]
and in that case, that's the rule you need to disable :-) that rule assumes you're using normal jsx.

**Comment by hartey11** [comment]
lol and how do I find out which rule it is and disable it?
