### ISSUE TITLE
Do all JavaScript code should be in ES modules?

### ISSUE THREAD

**Issue by iwis** [airbnb/javascript#2234]
On issue https://github.com/airbnb/javascript/issues/722 I have found: _"all code should be inside a module"_. However there is no such information on the https://airbnb.io/javascript/ page. 

Generally, do all JavaScript code should be in ES modules according to Airbnb style?

**Comment by ljharb** [comment]
Yes, this guide assumes you’re using Babel and are authoring everything as ESM, and transpiling it to CJS.
