### ISSUE TITLE
js.

### ISSUE THREAD

**Issue by Syihabuddin22** [airbnb/javascript#2247]
Make a function to change the input format. The input accepts a data type in the form of a string and some arguments to be replaced by the next defined parameter.

Input1		:
format_input(“Hello {0} {1}”, “Eko”, “Cool!”)
	Output1	:
Hello Eko Cool!

**Comment by ljharb** [comment]
This doesn't seem actionable.

**Comment by Syihabuddin22** [comment]
why doesn't seem actionable?

Pada tanggal Sab, 20 Jun 2020 14:10 Jordan Harband <notifications@github.com
menulis:

**Comment by ljharb** [comment]
This is a repository for airbnb's javascript style guide and eslint config. It looks like you're posting a homework assignment for javascript, but that wouldn't make sense for this repo.

**Comment by Syihabuddin22** [comment]
That's right sir, that's my homework, but it's so hard, my funds intend to
ask to you,
I'm sorry for everything 🙏🙏🙏

Pada tanggal Sab, 20 Jun 2020 14:24 Jordan Harband <notifications@github.com
menulis:
