### ISSUE TITLE
Move generated parenthesis for IIFE into the parens

### ISSUE THREAD

**Issue by MathRobin** [airbnb/javascript#225]
Hi,

I would like to suggest a really small but important for JSLint users. I refer to this error in JSLint : https://jslinterrors.com/move-the-invocation-into-the-parens-that-contain-the-function

You have this :

    var SkinnedMesh = (function (THREE) {
      var SkinnedMesh = function SkinnedMesh() {
        //...
      };
      SkinnedMesh.prototype.update = function () {
        //...
      };
      return SkinnedMesh;
    })(THREE);

But to be JSLint valid, it should be :

    var SkinnedMesh = (function (THREE) {
      var SkinnedMesh = function SkinnedMesh() {
        //...
      };
      SkinnedMesh.prototype.update = function () {
        //...
      };
      return SkinnedMesh;
    }(THREE));

As you can see, it's a small improvement but it's important OMHO.

**Comment by hshoff** [comment]
Hi @MathRobin thanks for checking out the style guide!

This is style choice that we made at Airbnb. Feel free to use the JSLint/Crockford style IIFE, the important part is consistency in the codebase.

For more info:
https://github.com/airbnb/javascript/pull/85
https://github.com/airbnb/javascript/issues/21

:beers:

**Comment by shenoydev** [comment]
@hshoff : Is -there any options config setting we could use to disable this warning ?

**Comment by ljharb** [comment]
@shenoydev you can certainly override the eslint rule, just like any other rule can be overridden.

That said, IIFEs shouldn't be needed in a world with modules, so this ideally shouldn't even come up :-)
