### ISSUE TITLE
react/no-multi-comp was disabled, but the style guide still recommends following it

### ISSUE THREAD

**Issue by speicus** [airbnb/javascript#2254]
`react/no-multi-comp` was disabled back in the beginning of 2019: https://github.com/airbnb/javascript/pull/2006

However, the style guide still states:

> # Basic rules
> Only include one React component per file. 
> * However, multiple Stateless, or Pure, Components are allowed per file. eslint: react/no-multi-comp.

https://github.com/airbnb/javascript/tree/master/react

**Comment by ljharb** [comment]
That’s because the guidance still applies, but the rule was found to be too restrictive.
