### ISSUE TITLE
No header or overview information at the top of each file?

### ISSUE THREAD

**Issue by nonopolarity** [airbnb/javascript#2259]
I am sorry maybe I missed something...

At many companies, including Google, they have some kind of overview file header.  Something that might be 1 line, or up to 3, 4 lines, the describe what the file does or what it is about.  And then any link to the docs or the index page of the docs.

Doing so usually is good so that if some developer in the future needs to look at 50 files, he won't need to browse 50 x 200 = 10,000 lines but can browse 50 lines (or 50 x 2 lines) and get a good overall idea of those 50 files.

Is this not specified here or just let each company decide to do it or not... In practice I did find it tremendously useful.  The person writing it may take 1 or 2 minutes, but the benefits for everybody who need to look at the file in the future is much more than this 1 or 2 minutes.

**Comment by ljharb** [comment]
Per-file header boilerplate is redundant, and messy, and serves zero purpose. The files are part of a repo, and can't be used in isolation from them - and the repo has a license, and a readme, and that's more than sufficient documentation for all files contained within.

**Comment by nonopolarity** [comment]
> Per-file header boilerplate is redundant, and messy, and serves zero purpose.

This is somewhat of a strong and all-the-way statement.  I do know that many companies use it, including Apple, Oracle, Microsoft, Google.  Google has the @fileoverview, for example: https://google.github.io/styleguide/jsguide.html#file-fileoverview

I think it may be good that if a group or company decides to use it, there is some mentioning of how it can be.

**Comment by ljharb** [comment]
This guide doesn't forbid use of that pattern, certainly, but it very much does not encourage it (and Airbnb does not use that pattern internally, as far as I am aware).

This is Airbnb's style guide, and I don't think it makes much sense to give advise for the few large companies that have chosen to follow this pattern, presumably at the advice of their legal team.

**Comment by nonopolarity** [comment]
wait, my main concern is not about the legal notice.  My main concern is about something like:

```
//
// This component is for the user click open the purchase options box and see the 
// items in a multiple column fashion.  Such usage is typical in the Mac buy-flow.
// Documentation:   abc.apple.com/store/docs/design/components
//
```

**Comment by ljharb** [comment]
That's just a multiline comment, which your project can legislate any way it likes :-) it's a bit out of scope for this style guide.

**Comment by nonopolarity** [comment]
this is a multiline comment, but it is also a special type of multiline comment called header information.
