### ISSUE TITLE
Extending 'airbnb-base' doesn't recognize custom import resolver 'babel-plugin-root-import' settings

### ISSUE THREAD

**Issue by koiralakiran1** [airbnb/javascript#2260]
Hi,
I'm using `babel` along with this plugin ['babel-plugin-root-import'](https://www.npmjs.com/package/babel-plugin-root-import). It also provides in the documentation about how to make it work with Eslint and VS Code (with `jsconfig.json`).

The things mentioned in the documentation were working fine until I tried to extend the `eslint-config-airbnb-base` in my eslint file. Eslint is throwing `eslint(import/no-unresolved)` error. However, babel and VS-Code redirection to custom paths are working fine.
![image](https://user-images.githubusercontent.com/11130898/88452689-84f4e880-ce80-11ea-8382-e74b0b236291.png)

Here are my config files:
`.eslintrc`
```JSON
{
    "$schema": "http://json.schemastore.org/eslintrc",
    "env": {
        "node": true
    },
    "extends": "airbnb-base",
    "parserOptions": {
        "ecmaVersion": 7,
        "sourceType": "module"
    },
    "rules": {
    },
    "plugins": [
        "import"
    ],
    "settings": {
        "import/resolver": {
            "babel-plugin-root-import": {}
        }
    }
}
```
`.babelrc`
![image](https://user-images.githubusercontent.com/11130898/88452768-0d738900-ce81-11ea-9628-dff664a19211.png)

Also, if I use `eslint-config-google` instead of `eslint-config-airbnb` in my `eslintrc` file, it's working fine (no ESLint error is thrown).
![image](https://user-images.githubusercontent.com/11130898/88452854-c6d25e80-ce81-11ea-92f8-6f3a3d072217.png)

Thanks

**Comment by ljharb** [comment]
The last part is likely because eslint-config-google doesn’t enable this particular rule.

I agree that should work; please file an issue on eslint-plugin-import instead, as it’s not an issue with this config.

**Comment by koiralakiran1** [comment]
Hmm.
Thanks, @ljharb.
Didn't realize that even on using a wrong path or filename 'eslint-config-google' didn't throw any errors.

**Comment by ljharb** [comment]
Few shared configs are as thorough as this one :-)
