### ISSUE TITLE
The JavaScript Style Guide Guide Reference link is broken in README.md

### ISSUE THREAD

**Issue by jeffvandyke** [airbnb/javascript#2262]

**Comment by ljharb** [comment]
@lencioni the wiki seems to have been disabled on this repo; it's required for this link.

**Comment by lencioni** [comment]
Which link?

**Comment by lencioni** [comment]
Ah, I found it https://github.com/airbnb/javascript/wiki/The-JavaScript-Style-Guide-Guide

I've re-enabled the wiki, but to be honest I'm not really sure it adds much value. We should probably just move this content to the readme or something instead.

**Comment by ljharb** [comment]
Fair; I'd left it up for the historical author/date metadata :-)

**Comment by jeffvandyke** [comment]
Ah, I thought it was going to be a link to the guiding principles of the Airbnb style guide, which I'm very curious to know about, as in: where's a good line between being too opinionated about everything versus allowing too much variability and looseness when looking for inconsistent patterns.

**Comment by ljharb** [comment]
@jeffvandyke a rough take on the guiding principle imo is "legislate everything that's possible, and that seems to be a tangible benefit" balanced with "avoid creating too much churn in the airbnb codebase" and "allow for alternative patterns when they equally avoid bugs and comprehension issues".

**Comment by jeffvandyke** [comment]
Hmm, that'd be a good one for README.md! I think that's really helpful information for those of us looking for a quick value evaluation of this style guide, and if there's anything more like that it'd be great to have documented.
