### ISSUE TITLE
Airbnb + mdx eslint

### ISSUE THREAD

**Issue by bucurvladadrian** [airbnb/javascript#2266]
Hi,

Hi,

I got airbnb to work correctly on jsx files, but my project also contains mdx files.
I installed [eslint-mdx](https://github.com/mdx-js/eslint-mdx) and I can't figure it out how to make it work with airbnb plugin.

In eslintrc file, I added mdx lint to extends:

```
"extends": [
    "airbnb",
    "plugin:mdx/recommended"
  ],
```

I am using eslint v7.5.

When I run the eslint, I get jsx errors from MDX files, instead of MDX errors.

Are these two compatible? Is it possible to run them both?

**Comment by ljharb** [comment]
I believe you'd have to use `overrides`, and only run the mdx plugin on mdx files, and disable all the JS rules in that overrides section. (no idea what mdx files are)
