### ISSUE TITLE
React multiline conditional component style

### ISSUE THREAD

**Issue by heyitaki** [airbnb/javascript#2267]
Hello! The following formatting is what I'm currently using for multi-line conditional components in React. Would love to get your opinion on this, as the guide only has an opinion on single line components.

Multiline conditional (regardless of if component is single or multiple lines):
```
{someReallyLongConditional
  && anotherLongConditional
  && (
    <Component 
      prop={prop}
    />
  )
}
```

Multiline ternary operator (again regardless of if components span multiple lines):
```
{someConditional ? (
  <Component />
) : (
  <Component 
    variant={somethingElse}
  />
)}
```

In the first case above, don't think it makes sense to stack the closing `)` with the final `}` so that they can represent the correct depth, but there are no supporting example in the style guide. 

Thanks!

**Comment by ljharb** [comment]
I'd format both of those exactly like that.

**Comment by heyitaki** [comment]
Added these examples in this [pull request](https://github.com/airbnb/javascript/pull/2269) if it is helpful. I would imagine this would also close #520

**Comment by google-mapsformless** [comment]
@heyitaki https://reactdev.space/questions/what-is-the-best-way-to-implement-a-multiconditional-statement-to-enhance-the-styling-of-a-react-component
