### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by atassis** [airbnb/javascript#2268]
Are you going to support typescript? If there is any aspiration in supporting the typescript with another sub config as hooks or whitespace are, I can do that by myself. It is very uncomfortable to move the same rules from one project to another, will be better for dozens if we create a faster approach.

**Comment by ljharb** [comment]
Duplicate of #1919.

**Comment by atassis** [comment]
@ljharb 2 years have passed, an issue is locked and not closed. And I have asked several more questions because the position of Airbnb is not clear.
