### ISSUE TITLE
 Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x.

### ISSUE THREAD

**Issue by saurav2501** [airbnb/javascript#2270]
Unable to install packages using command npx install-peerdeps --dev eslint-config-airbnb. While running getting following error 👍 npm WARN deprecated mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)

**Comment by ljharb** [comment]
That’s just a warning, and one that can be forever ignored. It shouldn’t interfere with installations.
