### ISSUE TITLE
Revisit/realign `curly` to eslint-defaults value of "all"

### ISSUE THREAD

**Issue by richthegeek** [airbnb/javascript#2271]
The `curly` option was set 5 years ago based on the eslint default rules of the time: https://github.com/airbnb/javascript/commit/daea8a638f1f42cd609f1b68b748ad323be31c10

Since then eslint has, of course, updated a lot of rules and configuration and part of that is specifying the new default `curly` value of `all`

I'd like to discuss aligning the config with that decision, as it seems the decision in this config was not consciously made and is now out of date.

Suggested label: `yak-shaving` 😉

**Comment by ljharb** [comment]
It was set that way because that’s the style Airbnb uses, and continues to use.

I certainly suggest setting it to “all” yourself, but unless Airbnb’s internal style has changed, this rule’s setting won’t either.
