### ISSUE TITLE
Bad example labeled as good in 21.1 Semicolons section.

### ISSUE THREAD

**Issue by PaperFlu** [airbnb/javascript#2272]
```javascript
// bad - raises exception
const luke = {}
const leia = {}
[luke, leia].forEach((jedi) => jedi.father = 'vader')

// good
const luke = {};
const leia = {};
[luke, leia].forEach((jedi) => {
  jedi.father = 'vader';
});
```

Copied as above. The "good" example acturally leads to a famous `no-param-reassign` error.

By the way, I have no idea how to write airbnb-style code when it comes to this need. Some may suggest a `for` loop, but oops, it's another `no-iterator` problem. `const parents = { father: 'vader' }; luke = { ...luke, ...parents }`? That will lose the reference of the original object.

Looking for your help. Thanks in advance.

**Comment by ljharb** [comment]
The latter, yes - you’re not supposed to retain the reference to the original object :-)

**Comment by ljharb** [comment]
As for the example, it’s good in the context of this section, even if it conflicts with another section.

**Comment by PaperFlu** [comment]
¯\\_(ツ)_/¯   Teared my hair out and can't figure one.

**Comment by ljharb** [comment]
Closing for now, but we can reopen if a better example is suggested.
