### ISSUE TITLE
about array add a item question

### ISSUE THREAD

**Issue by zhoufanglu** [airbnb/javascript#2273]
* please see this
```js
  let arr = []
  const template = new Array(100).fill(1)
  /**********************method first***********************/
  template.forEach(i=>{
    arr.push(i)  // look this arr
  })
```
```js
  let arr = []
  const template = new Array(100).fill(1)
  /**********************method second***********************/
  template.forEach((i,index)=>{
    arr[index] = i //look this arr
  })
```
I wonder what is the difference between these two methods!
please tell me, thank you!!!

**Comment by ljharb** [comment]
Don't ever use `new Array`, for one - that creates a sparse array.

Specifically, this is what you should be doing for this case:
```js
const template = Array.from({ length: 100 }, (, i) => i);
```

**Comment by zhoufanglu** [comment]
> Don't ever use `new Array`, for one - that creates a sparse array.
> 
> Specifically, this is what you should be doing for this case:
> 
> ```js
> const template = Array.from({ length: 100 }, (, i) => i);
> ```

Ok, Thank you for telling me about array creation, But my problem is the new items in the array

**Comment by ljharb** [comment]
What new items?

**Comment by zhoufanglu** [comment]
> What new items?

I made a mistake in the demo before, so I modified it. Please check it again

**Comment by ljharb** [comment]
I'm still confused. This guide tells you to avoid mutation, so if you want a range of 0 to 99 in an array, you do it when creating that array - not via `push`.

In other words, never add anything to an array - create a new array with `concat` that has the original items, and the new ones.

**Comment by zhoufanglu** [comment]
> I'm still confused. This guide tells you to avoid mutation, so if you want a range of 0 to 99 in an array, you do it when creating that array - not via `push`.
> 
> In other words, never add anything to an array - create a new array with `concat` that has the original items, and the new ones.

sorry, My English is a little bad, using software translation.   
Look at the example above, The `arr` results are the same, What is the difference between the two implementations？

**Comment by ljharb** [comment]
Between the two you provided - both of which you should avoid - the difference is that `.push` is a clearer and also likely more optimized way to add an item to an array than "writing an index just out of bounds" is.

**Comment by zhoufanglu** [comment]
> Between the two you provided - both of which you should avoid - the difference is that `.push` is a clearer and also likely more optimized way to add an item to an array than "writing an index just out of bounds" is.

Thank you for your answer！
