### ISSUE TITLE
typeof is no longer safe -  dead link

### ISSUE THREAD

**Issue by dman777** [airbnb/javascript#2274]
Hello,

From https://github.com/airbnb/javascript#hoisting--about, the link for http://es-discourse.com/t/why-typeof-is-no-longer-safe/15 is no longer working. 

Thank you.

**Comment by ljharb** [comment]
Duplicate of https://github.com/airbnb/javascript/issues/1989#issuecomment-630148995; in the meantime, https://web.archive.org/web/20200121061528/http://es-discourse.com/t/why-typeof-is-no-longer-safe/15 can be used.

**Comment by ljharb** [comment]
Looks like es-discourse won't be restored; i'll update the guide with the archive.org link.

**Comment by feiaaa** [comment]
now it's no longer working again

**Comment by ljharb** [comment]
@feiaaa the archive.org link above works fine.
