### ISSUE TITLE
eslint-config-airbnb: Integration unclear

### ISSUE THREAD

**Issue by akullpp** [airbnb/javascript#2289]
I'd like to write a PR to make the usage a bit more clear when it comes to integration with other ESLint configs/plugins.

There are a myriad of articles on medium, each writing something different and I have the feeling that the most are wrong about the usage, so that's a real deficit.

Let us take a modern example where we have an app created with CRA. Let us assume we have all up to date (peer) dependencies installed:

```
"eslint": "*",
"eslint-config-airbnb": "*",
"eslint-config-prettier": "*",
"eslint-plugin-import": "*",
"eslint-plugin-jsx-a11y": "*",
"eslint-plugin-prettier": "*",
"eslint-plugin-react": "*",
"eslint-plugin-react-hooks": "*"
```

Ideally, I assume the `extends`-section would look like this:

```
"extends": [
  "airbnb",
  "airbnb/hooks",
  "plugin:prettier/recommended",
  "prettier/react"
],
```

and the `plugins`-section like this:

```
"plugins": [
  "prettier"
],
```

since airbnb depends on the plugins `import/jsx-a11y/react/react-hooks` and I'd assume that they are loaded automatically if that's possible with ESLint's plugin system. 

Since the ESLint's config system is quite simple I assume that the configuration of the peer dependencies is not needed in the `extends`-section and `airbnb` uses the respective `plugins` with their recommended settings.

However many articles manually add these configurations and plugins separately. The current documentation does not provide clarity about this question.

**Comment by ljharb** [comment]
They're loaded automatically as long as the peer deps are valid - ie, as long as `npm ls` exits zero. For CRA specifically, I'm not sure that's actually possible without ejecting (but I haven't kept up with the status).

You're also correct in that you don't need to explicitly mention any "plugins" that a shared config already brings in - airbnb's config already does so for all of its peer deps. It doesn't hurt to mention them twice though, so it's not that important.

**Comment by akullpp** [comment]
Thank's I'll do a PR to update the docs.

**Comment by cjones26** [comment]
@akullpp @ljharb -- I'm struggling to understand here -- being that CRA already has, for example, ESLint installed as a dependency of react-scripts, is it still absolutely necessary for us to install ESLint as a peer dep?  Maybe this is a question more targeted at the CRA team.

**Comment by ljharb** [comment]
@cjones26 yes, because otherwise CRA, and you, might have a different version of eslint.

If the versions don't match up, then it's not compatible with CRA.

**Comment by cjones26** [comment]
> @cjones26 yes, because otherwise CRA, and you, might have a different version of eslint.
> 
> If the versions don't match up, then it's not compatible with CRA.

Got it, thanks @ljharb!
