### ISSUE TITLE
Update the reason for preferring object destructuring?

### ISSUE THREAD

**Issue by michaelaflores** [airbnb/javascript#2293]
The explanation for the preference for destructuring says:
> Destructuring saves you from creating temporary references for those properties.

I've found that devs used to _not_ destructuring find it such a big change that this explanation doesn't seem like a good reason, especially if there's an established habit of referencing object properties inline and not creating temporary references anyways. i.e. rather than:
```js
// bad
function getFullName(user) {
  const firstName = user.firstName;
  const lastName = user.lastName;

  return `${firstName} ${lastName}`;
}
```
They are writing
```js
// better?
function getFullName(user) {
  return `${user.firstName} ${user.lastName}`;
}
```

While I personally find this verbose and repetitive even in this small example, a developer coming from _never_ using destructuring finds it to be far more straightforward and are thus resistant to this rule.

I say all this to ask, are there any additional reasons Airbnb prefers destructuring, and should those be included in the explanation for the rule?

**Comment by ljharb** [comment]
In your example, avoiding the repetition of `firstName` and `lastName` adds a ton of value that may indeed not be immediately apparent. Repetition is more to read, and more chances to make a mistake.

**Comment by michaelaflores** [comment]
That's a fair reason. I suppose another good reason is that the shape of object parameters are apparent at the function's definition line, rather than needing to read the full function and find every place `user.` is used. I'd personally love to see these reasons or any others included in the ReadMe, as this is one of the rules that can cause the most change when introducing this ruleset to an existing project.

If there's a possibility of this change having value, I'd be glad to write this up in a PR.

**Comment by ljharb** [comment]
Sure, a PR to improve the prose explaining a guideline would be appreciated.
