### ISSUE TITLE
Don't use base64 source

### ISSUE THREAD

**Issue by jimmywarting** [airbnb/javascript#2297]
**Feature request summary**

base64 takes up more memory and increases the payload needed to download & upload. It also waste time on decoding/encoding. So would it makes sense to forbid, warn or suggest alternative methods towards the use of using the `FileReader.readAsDataURL()` and `canvas.toDataURL()`?

The issue: `<img src="data:image/png;base64,iVBORw...`

**What is the motivation or use case for not using this?**
To reduce bandwidth and memory usage and time spent on encoding/decoding.

I help out a lot of ppl on stackoverflow and I have come across  many developer using `fileReader.readAsDataURL` on a `<input type="file">` both on StackOverflow and in the wild just to show some preview image of what a client just selected or dragged into the browser instead of just creating a direct pointer to the file on the user's disk and consume `file.size * 1.33` more memory

object urls loads faster since you would not have to decode it to base64 with `fr.readAsDataURL` and then decode it back to binary again by the underlying `<img>` you have then also increased the memory usage on the clients device.
it also takes more code to do the following:
```js
fr = new FileReader()
fr.onload = () => {
  img.src = fr.result
}
fr.readAsDataURL(file)
```
As compared to the sync version:
```js
// This hardly makes any file processing. 
// It just create a reference point that blob/file
// So it almost creates no more memory usage.
img.src = URL.createObjectURL(file)
```
So b/c the fileReader is async some tend to wrap it around promises and complex components also which also can be a waste. 
Some also made the [mistake](https://stackoverflow.com/questions/11829537/html5-filereader-how-to-return-result) of thinking that the FileReader could be sync or don't know how to "return" the value.

json+binary (or rather json+base64) isn't a grate fit either for a rest api, it takes ~33% more bandwidth. so it also takes longer to send. and the server has to do more work.

**The alternative solution**
- Like i have already mention, `URL.createObjectURL` is a grate supplement.
- For the cases with rest api's it's better to use multipart formdata, protobuf, bson or something else if you are dealing with binary data.
- b/c the FileReader is asynchronous some decides to wraps them in promises. And b/c nobody ever register more than one onload event listener it could just as well have been a callback based `readAsDataURL(file, cb)` but wasn't designed that way anyway. but now the blob prototype have new promise reading methods: `await blob.arrayBuffer()`, `blob.text()` but too support more browser you could do `await new Response(blob).arrayBuffer()`.

`fr.readAsBinaryString` is discouraged (better to use arrayBuffer instead) and dataURL is a bad practice IMO so i don't see much reason to keep using the FileReader at all. unless for cases where you need to polyfill the new reading methods.
Deno, and Node (at least node-fetch) have some blob implementations also. So on the server there isn't any single source of truth for holding blobs so one FileReader polyfill can't read another blob implementation cuz they store the underlying content in some other methods. The only united way to read it cross environments is throught the new blob reading methods.

**Comment by ljharb** [comment]
If you're looking for an eslint rule, the appropriate place to file this would be on an eslint plugin. This project doesn't make eslint rules, it only consumes and configures them.

As for a guide recommendation, this seems too coarse-grained and broad to be useful. There are plenty of valid use cases to use base64 URLs, and there are many considerations that can outweigh bandwidth/size considerations. I think this is best left up to the individual developer, who has the full context of the app they're using. (data URLs are decidedly *not* a bad practice, in a general sense)

**Comment by 1Mouse** [comment]
@jimmywarting
Hi this discussion was really helpful and I totally got your point.
but what way do you suggest to send the file to backend?
