### ISSUE TITLE
100 free web security issues learning in 20 hours including javascript issues

### ISSUE THREAD

**Issue by udaydatrak** [airbnb/javascript#2299]
Hi Guys,

I made a video on how to learn 100 unique security issues learning in just 20 hours without any basics.

I would like you to add these in your features list. People from across the globe already started giving hundreds of positive comments.

Search in YouTube for "100 bug bounty lessons uday datrak" To learn including web application development and setup too.

https://www.youtube.com/playlist?list=PL_bkTzUc1BufnQyGt6-9hSly2PqsDmd09

**Comment by ljharb** [comment]
Congrats on your video. It's not really appropriate for this style guide, however.
