### ISSUE TITLE
Inconsistent use of periods before code snippets

### ISSUE THREAD

**Issue by ClimbsRocks** [airbnb/javascript#231]
Some sentences leading into code snippets end in periods, others don't have any punctuation. The lack of consistency is odd for a repo of this importance, particularly a style guide. 

Period before code snippet: 
![image](https://cloud.githubusercontent.com/assets/7017045/5930894/d8a1b8c8-a64a-11e4-93a4-8255ac85ab4d.png)

No punctuation before code snippet: 
![image](https://cloud.githubusercontent.com/assets/7017045/5930932/28dff5b6-a64b-11e4-811a-53e346dba466.png)

**Comment by hshoff** [comment]
Agree! Thank you.
