### ISSUE TITLE
Ambiguous rules

### ISSUE THREAD

**Issue by ijunyu** [airbnb/javascript#2345]
16.1
// good
if (test) return false;
// bad
function foo() { return false; }

19.14
// good
function foo() { return true; }
if (foo) { bar = 0; }

Do I need braces for if with only one line of statements?
Is the writing of this function good or bad?

Thanks

**Comment by ljharb** [comment]
The guide requires braces with multiline statements; it strongly recommends using them with one-line statements, but the linter config does not enforce it on one-line statements.
