### ISSUE TITLE
Value "" has less items than allowed 

### ISSUE THREAD

**Issue by cjm771** [airbnb/javascript#2352]
I get this error from trying to do the default settings in vscode. I believe it was working before, but for some reason it keeps hitting this issue:

**Relevant Global npm packages**
```
├── eslint@7.14.0
├── eslint-config-airbnb-base@14.2.1
├── eslint-plugin-es5@1.5.0
├── eslint-plugin-import@2.22.1
├── install-peerdeps@2.0.3
```

**To produce**
```
{
  "extends": "airbnb-base"
}
```
**Error**

`Configuration for rule "import/no-unused-modules" is invalid: 	Value "" has less items than allowed.  Referenced from: airbnb-base Referenced from: /path/to/.eslintrc`

Can't find any errors like that as a reference on the net. Any ideas?

**Comment by ljharb** [comment]
Run `npm ls` - does it exit successfully?

**Comment by cjm771** [comment]
yes. You know what, was able to run on cli. Stange. Uninstalling + reinstalling vscode eslint extension seems to have fixed issue.

**Comment by ljharb** [comment]
In general, when the CLI works and an editor doesn't, it's an editor bug.
