### ISSUE TITLE
unable to resolve dependency tree because eslint-plugin-react-hooks 4.0 doesn't list eslint 7 compatibility

### ISSUE THREAD

**Issue by maco** [airbnb/javascript#2355]
While resolving: undefined@undefined
Found: eslint@7.2.0
node_modules/eslint
  dev eslint@"7.2.0" from the root project
  peer eslint@"^5.16.0 || ^6.8.0 || ^7.2.0" from eslint-config-airbnb@18.2.1
  node_modules/eslint-config-airbnb
    dev eslint-config-airbnb@"18.2.1" from the root project
  peer eslint@"^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0" from eslint-plugin-import@2.22.1
  node_modules/eslint-plugin-import
    dev eslint-plugin-import@"^2.22.1" from the root project
    peer eslint-plugin-import@"^2.22.1" from eslint-config-airbnb@18.2.1
    node_modules/eslint-config-airbnb
      dev eslint-config-airbnb@"18.2.1" from the root project
  peer eslint@"^3 || ^4 || ^5 || ^6 || ^7" from eslint-plugin-jsx-a11y@6.4.1
  node_modules/eslint-plugin-jsx-a11y
    dev eslint-plugin-jsx-a11y@"^6.4.1" from the root project
    peer eslint-plugin-jsx-a11y@"^6.4.1" from eslint-config-airbnb@18.2.1
    node_modules/eslint-config-airbnb
      dev eslint-config-airbnb@"18.2.1" from the root project
  peer eslint@"^3 || ^4 || ^5 || ^6 || ^7" from eslint-plugin-react@7.21.5
  node_modules/eslint-plugin-react
    dev eslint-plugin-react@"^7.21.5" from the root project
    peer eslint-plugin-react@"^7.21.5" from eslint-config-airbnb@18.2.1
    node_modules/eslint-config-airbnb
      dev eslint-config-airbnb@"18.2.1" from the root project

Could not resolve dependency:
peer eslint@"^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0" from eslint-plugin-react-hooks@4.0.0
node_modules/eslint-plugin-react-hooks
  dev eslint-plugin-react-hooks@"4.0.0" from the root project
  peer eslint-plugin-react-hooks@"^4 || ^3 || ^2.3.0 || ^1.7.0" from eslint-config-airbnb@18.2.1
  node_modules/eslint-config-airbnb
    dev eslint-config-airbnb@"18.2.1" from the root project

**Comment by ljharb** [comment]
That's because you're using v4.0.0 of eslint-plugin-react-hooks. v4.0.1 was the one that added eslint 7 to peerDeps.

Fixing this doesn't require any change in this package, because of semver ranges - you can update your lockfile.

**Comment by maco** [comment]
That's how I thought semantic versions _should_ work, but this is what it did. I'm pretty sure I didn't already have eslint-plugin-react-hooks in my lockfile, either, since this project didn't have any linters up to this point.

**Comment by ljharb** [comment]
Hmm - `dev eslint-plugin-react-hooks@"4.0.0" from the root project` implies that you do have it. Perhaps you have `save-exact` set in your npm config (which is a very bad idea)?
