### ISSUE TITLE
How do Airbnb teams integrate the style guide into Typescript projects?

### ISSUE THREAD

**Issue by spencermefford** [airbnb/javascript#2357]
I've been scouring the Internet to see how other people have been using the Airbnb Style Guide in Typescript projects, but there are a lot of variations. 

There isn't any mention of Typescript in this repository that I can find. I know that Airbnb is buying into Typescript internally (see [this video](https://www.youtube.com/watch?v=P-J9Eg7hJwE&feature=youtu.be&t=702)), and I'd love to know how the Airbnb teams are integrating the style guide into their Typescript projects.

Have you made a different npm package to support this that isn't public? In the meantime, I can use some of the other solutions I've found in the wild, but I'd really love to know how Airbnb officially does this.

Thank you!

**Comment by ljharb** [comment]
Airbnb does not yet have any public solution for this.

**Comment by spencermefford** [comment]
Thanks, @ljharb for the quick response! 

Hopefully, Airbnb will release official support for the Typescript style guide in the future. Looking forward to it 😄

**Comment by ljharb** [comment]
Closing in favor of #1919.
