### ISSUE TITLE
Questions about jsx props

### ISSUE THREAD

**Issue by hemmingson** [airbnb/javascript#2358]
I have some doubts about this [topic](https://github.com/airbnb/javascript/tree/master/react#props).
> Omit the value of the prop when it is explicitly `true`.

```jsx
// bad
<Foo
  hidden={true}
/>

// good
<Foo hidden />
```
It was also written in the [docs](https://reactjs.org/docs/jsx-in-depth.html#props-default-to-true), so it may not a bad choice. I might be thinking wrong.

Anyway, thank you for contributing the best guidance.

**Comment by ljharb** [comment]
React's docs are not objective best practices, they're just the way some folks on the react team wrote the examples.

For us, "matching the behavior of HTML" far, far outweighs the negligible chance of confusion with ES6 object shorthand.
