### ISSUE TITLE
Invalid infinity in import/no-cycle rule

### ISSUE THREAD

**Issue by KristjanTammekivi** [airbnb/javascript#2359]
https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/imports.js#L237

        Configuration for rule "import/no-cycle" is invalid:
        Value "∞" should be integer.

**Comment by KristjanTammekivi** [comment]
Yarn link somehow conflicted with older eslint-plugin-import which didn't allow infinity symbol, never mind

**Comment by mifas** [comment]
Getting this issue in WebStorm and command line eslint
Node v14
