### ISSUE TITLE
Receiving defined but never used while using in another file 

### ISSUE THREAD

**Issue by CreaTorAlexander** [airbnb/javascript#2367]
I am not using es6 modules I just include my scripts in the html file.
`    <script language="javascript" type="text/javascript" src="./scripts/processhandling.js"></script>
`

I call the functions in the html or in other scripts but the linter says `aodv_clear_statistics' is defined but never used.eslintno-unused-vars` because I don't call it in the same file.

How can I avoid this or how can I turn off this rule?

Here my .eslintrc.json
```
{
    "env": {
        "browser": true,
        "es2021": true,
        "node": true
    },
    "extends": [
        "airbnb-base"
    ],
    "parserOptions": {
        "ecmaVersion": 12
    },
    "rules": {
    }
}

```

**Comment by ljharb** [comment]
This guide assumes that you're using modules - whether CJS or ESM modules - which is something modern web dev requires.

You can add `/* globals aodv_clear_statistics */`, i believe, to tell eslint to treat that variable like it's a global, but the proper solution is to use modules (CJS modules, with a bundler, is just fine) and *not* to have any globals whatsoever.
