### ISSUE TITLE
'styles' was used before it was defined

### ISSUE THREAD

**Issue by vigyanhoon** [airbnb/javascript#2368]
Hi,

No matter what I do, I can't get rid of this error:

ESLint: 'styles' was used before it was defined.(@typescript-eslint/no-use-before-define)

Due to this I am not able to use airbnb in eslint. Mine is a react-native project where styles are defined after component definition by convention.

eslint

```
{
    "env": {
        "browser": true,
        "es6": true,
        "node": true
    },
    "extends": [
        "airbnb-typescript",
        "airbnb/hooks",
        "plugin:@typescript-eslint/recommended",
        "prettier",
        "prettier/react",
        "prettier/@typescript-eslint",
        "plugin:prettier/recommended"
    ],
    "globals": {
        "Atomics": "readonly",
        "SharedArrayBuffer": "readonly"
    },
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": 2018,
        "sourceType": "module",
        "project": "./tsconfig.json",
        "createDefaultProgram": true
    },
    "plugins": [
        "react",
        "@typescript-eslint",
        "react-native"
    ],
    "rules": {
        "react-native/no-unused-styles": 2,
        "react-native/no-inline-styles": 2,
        "react-native/no-color-literals": 2,
        "no-use-before-define": "off",
        "@typescript-eslint/no-use-before-define": "error"
    }
}
```

**Comment by vigyanhoon** [comment]
I have also tried "no-use-before-define": ["error", { "functions": true, "classes": true, "variables": false }]

Which works well when not using airbnb. Thanks.

**Comment by ljharb** [comment]
That convention contradicts the styleguide. Define the styles before the component,

The rule you’re reporting, however, is from the typescript eslint plugin, which isn’t part of Airbnb. You’ll have to disable that if you want to deviate from the guide and define them after.
