### ISSUE TITLE
javascript/react - Misleading example 

### ISSUE THREAD

**Issue by Mooli88** [airbnb/javascript#2369]
In [Props](https://github.com/airbnb/javascript/tree/master/react#props) --> Exception:

```
function HOC(WrappedComponent) {
  return class Proxy extends React.Component {
    Proxy.propTypes = {
      text: PropTypes.string,
      isLoading: PropTypes.bool
    };

    render() {
      return <WrappedComponent {...this.props} />
    }
  }
}
```

Since [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) is a reserved name in JS this example might confused / mislead readers

**Comment by ljharb** [comment]
It's not a reserved anything; it's just a builtin global. It certainly might be confusing to shadow a builtin, however - a PR to tweak the name would be fine.

**Comment by baxti776** [comment]
What do you want? 
--
Sent from Mail.ru app for Android Saturday, 30 January 2021, 02:10am +05:00 from Jordan Harband  notifications@github.com :
