### ISSUE TITLE
Default values for the React /jsx-filename-extension rule

### ISSUE THREAD

**Issue by 97Yates05** [airbnb/javascript#2372]
TSX files and JSX files should be equivalent, shouldn't TSX files contain JSX syntax for granted.Every time I need  this configuration，`'react/jsx-filename-extension': [1, { extensions: ['.tsx', '.jsx'] }]`.Is this unnecessary behavior

**Comment by ljharb** [comment]
This guide/config currently is not intended for use with TypeScript; if at some point we publish an additional config for TS, then this rule would surely be configured this way.

Closing in favor of #1919.
