### ISSUE TITLE
rule 17.1 is not working

### ISSUE THREAD

**Issue by VSavitar** [airbnb/javascript#2373]
It doesn't have any hints in this case. `"eslint-config-airbnb-base"` version is `"14.2.1"`
```
// bad
if (foo === 123
  && bar === 'abc') {
  thing1();
}

// good
if (
  foo === 123
  && bar === 'abc'
) {
  thing1();
}
```

**Comment by ljharb** [comment]
Not everything in the guide is lintable or linted.

If there’s something lintable that’s not linted, it’s either an oversight, or was an intentional choice, and we could figure that out in a PR.

**Comment by Jorabek1318** [comment]
Heloo
