### ISSUE TITLE
Translation of JavaScript Style Guide into Hindi language

### ISSUE THREAD

**Issue by rajdeep-ghosh** [airbnb/javascript#2374]
Hello, 

I would like to work on translating the JavaScript Style guide into my mother tongue Hindi language. Please allow me in doing so.

Thanks!

**Comment by ljharb** [comment]
Please feel free.

I suggest doing it on *not* the master branch - you'll need to make a pull request once done to add the link to the readme, and if you make a different branch name your default branch, you'll be better able to keep in sync. "main" works, but if this repo ever changes the default it'll be to "main", so i'd pick a different name.

I'll close this, but please send a PR once you're ready!
