### ISSUE TITLE
arrow-body-style / max-len conflict

### ISSUE THREAD

**Issue by NYKOL4Z** [airbnb/javascript#2375]
Hi,

I hope this is the right place to report this, but I'm having the following issue:

I have this code that throws a "**This line has a length of 108. Maximum allowed is 100. eslint(max-len)**" error.
`UserSchema.methods.comparePassword = (password, hashPassword) => bcrypt.compareSync(password, hashPassword);`

If I create a block for the function I get another error: "**Unexpected block statement surrounding arrow body; move the returned value immediately after the \`=>\`. eslint(arrow-body-style)**".
`UserSchema.methods.comparePassword = (password, hashPassword) => {`
`  return bcrypt.compareSync(password, hashPassword);`
`};`

Is there a way to fix this without disabling any of the rules?

Thanks!

**Comment by ljharb** [comment]
Here’s a few possibilities:
```jsx
UserSchema.methods.comparePassword = (password, hashPassword) => bcrypt.compareSync(
  password,
  hashPassword,
);
```

```jsx
UserSchema.methods.comparePassword = (
  password,
  hashPassword,
) => bcrypt.compareSync(
  password,
  hashPassword,
);
```
