### ISSUE TITLE
throws spurious error on test files: @testing-library/react' should be listed in the project's dependencies, not devDependencies.

### ISSUE THREAD

**Issue by JESii** [airbnb/javascript#2376]
Writing tests with `@testing-library/react`, eslint with airBNB trhows the error:
`'@testing-library/react' should be listed in the project's dependencies, not devDependencies.`

This is a test file, so I don't think this error should be thrown at this time... Is there a way to override/fix this one thing without impacting the proper application of the rule elsewhere?

**Comment by ljharb** [comment]
Yes. You need to configure the `no-extraneous-dependencies` rule to reference your test files.

This config specifies this list: https://github.com/airbnb/javascript/blob/f0df3a8680479ff0b897cd98a1eab6b156899214/packages/eslint-config-airbnb-base/rules/imports.js#L72-L95 which is pretty extensive, so if your test files aren't following one of those conventions, you may want to consider using one.

**Comment by JESii** [comment]
Thanks, @ljharb got it!

**Comment by DenisP01** [comment]
In TypeScript case

.eslintrc.json
`{
  "rules": {
    "import/no-extraneous-dependencies": [
      "error",
      {
        "devDependencies": [
          "test.{ts,tsx}", // repos with a single test file
          "test-*.{ts,tsx}", // repos with multiple top-level test files
          "**/*{.,_}{test,spec}.{ts,tsx}", // tests where the extension or filename suffix denotes that it is a test
          "**/jest.config.ts", // jest config
          "**/jest.setup.ts" // jest setup
        ],
        "optionalDependencies": false
      }
    ]
  }
}
`

**Comment by nathan-hyan** [comment]
> In TypeScript case
> 
> .eslintrc.json
> 
> ```
> {
>   "rules": {
>     "import/no-extraneous-dependencies": [
>       "error",
>       {
>         "devDependencies": [
>           "test.{ts,tsx}", // repos with a single test file
>           "test-*.{ts,tsx}", // repos with multiple top-level test files
>           "**/*{.,_}{test,spec}.{ts,tsx}", // tests where the extension or filename suffix denotes that it is a test
>           "**/jest.config.ts", // jest config
>           "**/jest.setup.ts" // jest setup
>         ],
>         "optionalDependencies": false
>       }
>     ]
>   }
> }
> ```

Thank you so much! This worked for me
