### ISSUE TITLE
eslint-config-airbnb-base: config is invalid

### ISSUE THREAD

**Issue by maddhruv** [airbnb/javascript#2377]
Getting the error
```
Configuration for rule "import/no-cycle" is invalid:
        Value "∞" should be integer.
```
while using the latest airbnb base, ref- https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/imports.js#L237

**Comment by guidop91** [comment]
Getting the same error. I found that it was resolved if the string `"∞"` was replaced with the JS variable `Inifinity`.

**Comment by ljharb** [comment]
This should not happen if your dep graph is valid - ie, all peer dep requirements are satisfied.

run `npm ls` and make sure it exits successfully?

**Comment by maddhruv** [comment]
> run npm ls and make sure it exits successfully?

yes, it does,
did a fresh install and still facing the same

**Comment by maddhruv** [comment]
Solved 🏁 
The peerDependency for `eslint-plugin-import` was outdated. Updating it helped.

**Comment by ljharb** [comment]
For anyone else who lands here, any time `npm ls` fails, your entire dep graph is invalid and you can’t assume anything will work.
