### ISSUE TITLE
How to Properly Setup the Extends Array

### ISSUE THREAD

**Issue by thecodeclimber** [airbnb/javascript#2395]
This is my current setup of the `extends` array in my `.eslintrc.js` file:

```
  extends: [
    'plugin:react/recommended',
    'plugin:react-hooks/recommended',
    'airbnb',
    'airbnb/hooks',
    'plugin:@typescript-eslint/recommended',
    'plugin:prettier/recommended',
  ],
```

I am not sure, though, that I did this the right way.  Here are my questions.

First, do I need to include either `'plugin:react/recommended'` or `'plugin:react-hooks/recommended'`?

Secondly, if I do need to include those plugins, do I place them **before** `airbnb` and `airbnb/hooks` or **after**?  In other words, should it be like this:

```
  extends: [
    'plugin:react/recommended',
    'plugin:react-hooks/recommended',
    'airbnb',
    'airbnb/hooks',
    ...
  ],
```

Or like this:

```
  extends: [
    'airbnb',
    'airbnb/hooks',
    'plugin:react/recommended',
    'plugin:react-hooks/recommended',
    ...
  ],
```

**Comment by ljharb** [comment]
Generally you wouldn’t want to include either of those, since the Airbnb config handles both:
```
“extends”: [
  “airbnb”,
  “airbnb/hooks”,
]
```
should be sufficient.

**Comment by thecodeclimber** [comment]
Thanks :)
