### ISSUE TITLE
Why is complexity set to 11 (or at all)?

### ISSUE THREAD

**Issue by barraponto** [airbnb/javascript#2400]
Following up on #1758, why is the `complexity` rule set to 11 or even set *at all*?
I mean, it is off by default and users who turn it on might be surprised it is set to 11 ([it defaults to 20](https://eslint.org/docs/rules/complexity)). Can we just drop it from the base configuration?

**Comment by ljharb** [comment]
The default was [added in v2](https://github.com/eslint/eslint/commit/1288ba435d6758394bf97495583159b32742bfaa), so I assume originally 11 was just the arbitrary number we [chose initially](https://github.com/airbnb/javascript/commit/daea8a638f1f42cd609f1b68b748ad323be31c10#diff-59022d4de06a1e2feef2e874d52cec710b166bfdc40ebc6b97d5130964395785R8), and then it never got updated when the default of 20 was added.

As to why it’s set at all, every single rule is set to its defaults so as to be explicit. We could certainly change the 11 to 20 - although this rule isn’t useful, so i wouldn’t expect any users to turn it on.

**Comment by kirans08** [comment]
@ljharb Can I update this ?

**Comment by ljharb** [comment]
@kirans08 set the 11 to 20? Sure.

**Comment by kirans08** [comment]
@ljharb 
Yes

I have created a pull request for the same

**Comment by kirans08** [comment]
@ljharb 
Sorry, I had to close the first pull request due to issues with user settings for that commit

I have created a new pull request - https://github.com/airbnb/javascript/pull/2420

**Comment by ljharb** [comment]
Please never create duplicate pull requests; it would be better to have zero than to have two.

**Comment by kirans08** [comment]
OK 👍🏼 
Will avoid duplicate pull requests going forward
