### ISSUE TITLE
Why not commit lockfiles? (package-lock.json)

### ISSUE THREAD

**Issue by GitGangGuy** [airbnb/javascript#2409]
I just noticed that you guys have decided to not commit the npm lockfile `package-lock.json`, although the general consensus is to do so. I'm curious why you have done that, as I don't really understand the purpose of it either.

**Comment by ljharb** [comment]
Only apps should have lockfiles.

Dev-only lockfiles (package-lock.json and yarn.lock) achieve nothing in a package except artificially insulating maintainers from problems their users will experience. It's thus hostile to a package's consumers to use a lockfile.

There is no "general consensus" to do so, there's mostly just "npm's default behavior" which the majority cargo-cults.

**Comment by GitGangGuy** [comment]
@ljharb Thanks for answering, but I'd just like to clarify what you're saying here: Because the only packages declared in `package.json` are for development, there's no need for a lockfile? Shouldn't the lockfile still provide consistency across development environments because it contains the whole dependency tree? I also don't really understand how having a lockfile would affect consumers of the `eslint-config-airbnb*` packages negatively?

**Comment by ljharb** [comment]
No, that's not what I'm saying. I'm saying that package-lock doesn't get published - so, consumers of a package don't "get" that lockfile. So, consumers will get the latest version of both direct and transitive dependencies - but the package was only tested with "whatever is in its lockfile", so the package's tests might be passing while the consumers' code is broken.

**Comment by GitGangGuy** [comment]
@ljharb And how are misleading CI test results and broken consumer code good? ^^

**Comment by ljharb** [comment]
They're not - that's what "having a lockfile" gets you.
