### ISSUE TITLE
ESLint: Failed to load config "airbnb" to extend from.

### ISSUE THREAD

**Issue by ruanblima** [airbnb/javascript#2414]
I'm trying to set up a project with eslint, and when starting the configuration I have the following error:

![Captura de tela 2021-04-24 113801](https://user-images.githubusercontent.com/57442366/115962446-d60a3980-a4f1-11eb-86bc-6e5778a26898.png)

**Comment by ljharb** [comment]
You chose not to install them. Run npm install (or yarn install)

**Comment by ruanblima** [comment]
Install eslint globally?

**Comment by ljharb** [comment]
No - locally, in your project. Literally run the command `npm install` or `yarn install`.

**Comment by ruanblima** [comment]
I ran but still giving the same error.

**Comment by ljharb** [comment]
Try on the actual command line, not in your editor’s terminal.

**Comment by ruanblima** [comment]
I tried both in cmd and in PowerShell but it continues with the error.

**Comment by ruanblima** [comment]
It was a problem when installing eslint, I installed each plugin individually and it worked.
