### ISSUE TITLE
Remove Math.pow from `no-restricted-properties` and use `prefer-exponentiation-operator` instead.

### ISSUE THREAD

**Issue by aSqrd-eSqrd** [airbnb/javascript#2421]
Since ESlint has the helpful [`prefer-exponentiation-operator`](https://eslint.org/docs/rules/prefer-exponentiation-operator) rule it would be nice if `Math.pow` was removed from the `no-restricted-properties` definitions in [`rules/best-practices.js`](https://github.com/airbnb/javascript/blob/dc3af3a90ebf56a5e9df2d4c7b40d6518200bb87/packages/eslint-config-airbnb-base/rules/best-practices.js#L260) in favor of the `prefer-exponentiation-operator` rule.

This has the benefit to us stubborn folks who want to use the `eslint-config-airbnb` or `eslint-config-airbnb-base` packages but want to override the rule to allow the use of `Math.pow`.  The `no-restricted-properties` ESlint rule can't be selectively modified, eslint/eslint#7957. It has to be completely duplicated and the desired change made in the duplicate.  The `Math.pow` entry in `no-restricted-properties` doesn't really fit in with the "intent" of the other entries in the no-restricted-properties` objects and since the `prefer-exponentiation-operator` rule exist it is a neat and tidy modification.

Thank you,
aSqrd-eSqrd

**Comment by ljharb** [comment]
That was added in eslint v6.7, and indeed, we will enable it when eslint 5 is dropped: https://github.com/airbnb/javascript/blob/1eadb93e377da1e56c3f91f26610e5d0a00738a9/packages/eslint-config-airbnb-base/rules/style.js#L444

**Comment by ljharb** [comment]
This was done in f3d3a075c

**Comment by SpraxDev** [comment]
> This was done in [f3d3a07](https://github.com/airbnb/javascript/commit/f3d3a075cda2acc02011e71991c10bb5b4a15278)

It looks like the README.md has not been updated yet to reflect that change (https://github.com/airbnb/javascript#es2016-properties--exponentiation-operator)

**Comment by ljharb** [comment]
@SpraxDev you're right; want to send a PR updating that?

**Comment by SpraxDev** [comment]
I've created #2768 @ljharb ^^
