### ISSUE TITLE
Failed to load config "airbnb-base" to extend from. Before this Error it run correctly

### ISSUE THREAD

**Issue by HypeNeutron** [airbnb/javascript#2427]
# This is my eslintrc.js
### How to fix this ?

![co2de](https://user-images.githubusercontent.com/40451633/118385855-e61ec000-b63c-11eb-850a-7f508f70175b.png)

**Comment by ljharb** [comment]
Do you have eslint-config-airbnb-base installed?

**Comment by HypeNeutron** [comment]
> 
> 
> Do you have eslint-config-airbnb-base installed?

Yes i do

**Comment by ljharb** [comment]
Then please file an issue on eslint itself; everything should be working.
