### ISSUE TITLE
Cannot execute $ npx install-peerdeps

### ISSUE THREAD

**Issue by Space7Panda** [airbnb/javascript#2436]
`$ npx install-peerdeps --dev eslint-config-airbnb`
```bash
install-peerdeps v3.0.3
Installing peerdeps for eslint-config-airbnb@latest.
npm install eslint-config-airbnb@18.2.1 eslint@^7.2.0 eslint-plugin-import@^2.22.1 eslint-plugin-jsx-a11y@^6.4.1 eslint-plugin-react@^7.21.5 eslint-plugin-react-hooks@^1.7.0 --save-dev

ERR undefined
```

node.js - v14.16.0
npm - v7.15.1

**Comment by ljharb** [comment]
What happens if you run the npm install command it prints out, directly?

(Either way this seems like a bug with install-peerdeps and not this repo)

**Comment by Space7Panda** [comment]
> What happens if you run the npm install command it prints out, directly?
> 
> (Either way this seems like a bug with install-peerdeps and not this repo)

```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: tsttst@1.0.0
npm ERR! Found: eslint@7.27.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.2.0" from the root project
npm ERR!   peer eslint@"^5.16.0 || ^6.8.0 || ^7.2.0" from eslint-config-airbnb@18.2.1
npm ERR!   node_modules/eslint-config-airbnb
npm ERR!     dev eslint-config-airbnb@"18.2.1" from the root project
npm ERR!   3 more (eslint-plugin-import, eslint-plugin-jsx-a11y, eslint-plugin-react)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0" from eslint-plugin-react-hooks@1.7.0
npm ERR! node_modules/eslint-plugin-react-hooks
npm ERR!   dev eslint-plugin-react-hooks@"^1.7.0" from the root project
npm ERR!   peer eslint-plugin-react-hooks@"^4 || ^3 || ^2.3.0 || ^1.7.0" from eslint-config-airbnb@18.2.1
npm ERR!   node_modules/eslint-config-airbnb
npm ERR!     dev eslint-config-airbnb@"18.2.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/s7p/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/s7p/.npm/_logs/2021-06-02T17_45_39_594Z-debug.log
```

Looks like `--force` helped for `npm i`, maybe there something similar for `npx` 🤔

**Comment by ljharb** [comment]
Looks like v1.7.0 of eslint-plugin-react-hooks is the problem. Change that to “latest” in your npm install command - don’t use force - and please file this on install-peerdeps. It appears it’s not grabbing the peer deps correctly.

**Comment by Space7Panda** [comment]
> Looks like v1.7.0 of eslint-plugin-react-hooks is the problem. Change that to “latest” in your npm install command - don’t use force - and please file this on install-peerdeps. It appears it’s not grabbing the peer deps correctly.

Yup, you are right. The following code works fine:
```bash
npm install eslint-config-airbnb@18.2.1 eslint@^7.2.0 eslint-plugin-import@^2.22.1 eslint-plugin-jsx-a11y@^6.4.1 eslint-plugin-react@^7.21.5 eslint-plugin-react-hooks@latest --save-dev
```

**Comment by KasirTiavina2110** [comment]
Hey guys, it not work, same error reappear after npm install eslint-config-airbnb@18.2.1 eslint@^7.2.0 eslint-plugin-import@^2.22.1 eslint-plugin-jsx-a11y@^6.4.1 eslint-plugin-react@^7.21.5 eslint-plugin-react-hooks@latest --save-dev.
So someone have other solution ? thanks
