### ISSUE TITLE
disable 'no-return-await' rule

### ISSUE THREAD

**Issue by Space7Panda** [airbnb/javascript#2437]
I guess `no-return-await` rule should be disabled according to the following issue:
https://github.com/eslint/eslint/issues/11878

Here is some resources:
- [zero-cost async stack traces](https://docs.google.com/document/d/13Sy_kBIJGP0XT34V1CV3nkWya4TwYx9L3Yv45LdGB6Q/edit)
- [V8 fast async](https://v8.dev/blog/fast-async)

Long story short:
> Here is the example slightly changed to have "return await". Try function "foo" with or without "await" in a current version of Chrome (node.js v12.4 worked too when I just tried).

>Without the "await" foo() does not appear in the stack trace, if it waits for bar() to finish it does appear. That asynchronous stack trace comes at "zero cost" and is enabled by default in current V8.

```js
(function () {
  async function foo() {
    // return bar();
    return await bar();
  }

  async function bar() {
    await Promise.resolve();
    throw new Error('BEEP BEEP');
  }

  foo().catch(error => console.log(error.stack));
})()
```

Without "await" in foo():
```bash
Error: BEEP BEEP
    at bar (<anonymous>:8:11)
```

```bash
Error: BEEP BEEP
    at bar (<anonymous>:8:11)
    at async foo (<anonymous>:3:12)
```
>Yes return await promise; is useless on the "happy path". But when there is a rejection...

>Of course there is a slight RAM cost, the context of the calling function now has to be kept around longer. Unless there is lots of looping or recursion going on that should not be relevant I'd say, compared to getting the stack trace when things go wrong in a lower-level promise creating async function.

**Comment by ljharb** [comment]
It very much should not be disabled. Stack traces are of zero importance compared to the correctness of the code, and `return await` outside of a `try` block is incorrect.

It's unfortunate that v8 has added a developer nicety that only works if you write your code incorrectly, but the solution is to apply pressure on v8 to fix it, rather than making your code worse.

**Comment by Space7Panda** [comment]
@ljharb so it's basically pointless because `return await` will return promise anyway and on top of that we will get some additional issues as slight RAM/Performance costs and bad code debugging?

**Comment by ljharb** [comment]
`return await` *adds* RAM/performance costs. In v8, `return await` improves stack traces, but in other engines it does not. In other words, following this rule deprives you of a slight improvement in one engine, but disabling this rule costs you performance in every engine and slightly improves the debugging experience in one engine.

You are free to decide tradeoffs for yourself - eslint is configurable. However, the recommendation of this guide is that the tradeoff is *far* from worth it, and the rule should be followed.

**Comment by Space7Panda** [comment]
@ljharb Thank you 😊
