### ISSUE TITLE
why javascript have to be like c ?

### ISSUE THREAD

**Issue by nfwyst** [airbnb/javascript#2439]
why there are so much rules that match c language syntax, that mean the es will to be next generation c language?

**Comment by ljharb** [comment]
I'm not sure what you mean specifically, but C was one of the major inspirations for JS, so it's not an accident that they're similar in a lot of ways.

What rules do you think match idiomatic C and are also surprising?

**Comment by VilgotanL** [comment]
This question is kinda weird because half of all programming languages are inspired by C
Such as Java, Javascript, C++, C#, PHP, Rust, Dart, and many more
Those have similar syntax to C but almost all others are inspired in some way by C
