### ISSUE TITLE
why setMonth(2-1) , the month is Mar

### ISSUE THREAD

**Issue by jackIsZlg** [airbnb/javascript#2440]
var dd = new Date();
dd.setFullYear(2021);
dd.setMonth(2-1);
dd.setDate(1);

![image](https://user-images.githubusercontent.com/25714655/123746430-39468c80-d8e4-11eb-8df8-9b579287cb1a.png)

**Comment by ljharb** [comment]
This doesn't seem relevant to airbnb's javascript styleguide.

The answer to your question, however, is that months are zero-indexed, and since `2-1` is 1, `setMonth(1)` sets February - but in your local timezone, that's March - and then when you set the date to 1, it's March 1st.

**Comment by jackIsZlg** [comment]
> This doesn't seem relevant to airbnb's javascript styleguide.
> 
> The answer to your question, however, is that months are zero-indexed, and since `2-1` is 1, `setMonth(1)` sets February - but in your local timezone, that's March - and then when you set the date to 1, it's March 1st.

var dd = new Date();
dd.setFullYear(2021);
dd.setMonth(2-1);
dd.setDate(23);

it is still March

![image](https://user-images.githubusercontent.com/25714655/123749844-714fce80-d8e8-11eb-8cd8-97bbbe2bdb14.png)

**Comment by ljharb** [comment]
Yes, it's June 28th, but you're in GMT +8, which means that February 28th is actually March 1st, so it's March once you do the setMonth.

Try console logging `dd` after each line.

**Comment by jackIsZlg** [comment]
> Yes, it's June 28th, but you're in GMT +8, which means that February 28th is actually March 1st, so it's March once you do the setMonth.
> 
> Try console logging `dd` after each line.

Ok，thanks， I see
