### ISSUE TITLE
Is `constructor` required for class components?

### ISSUE THREAD

**Issue by miko-github** [airbnb/javascript#2441]
# Is `constructor` required for class components?

Hi Everyone :wave:,
so, can i use class component alike below? :thinking: 
```jsx
// is this good?
class MyComponent extends React.Component {
  render(){
    return <div>...</div>;
  }
};
```

**Comment by ljharb** [comment]
It is not required, and should be omitted from any class that doesn’t use constructor arguments directly.

In this case, that should be a functional component.

**Comment by miko-github** [comment]
> It is not required, and should be omitted from any class that doesn’t use constructor arguments directly.
> 
> In this case, that should be a functional component.

### :heart: :star_struck:
**thank you** :heart_eyes:
> yes, i should use function component, but i did it **simple** :+1:
