### ISSUE TITLE
JSX Syntax or Call As Functions?

### ISSUE THREAD

**Issue by miko-github** [airbnb/javascript#2442]
# Which one is SIMPLE?
- [ ] jsx syntax
- [ ] call as function

### Components

``` jsx
// ./MyComponent.jsx
import React from 'react';

function MyComponent(props){
  return <span style="color: red"> my-component </span>;
}

export default MyComponent;
```

### JSX Syntax

> i meant JSX-DOM :sweat_smile: 

``` jsx
// ./MyParent.jsx
import React from 'react';
import MyComponent from './MyComponent.jsx';

function MyParent(props){
  return (
    <main>
      <h1> my-parent </h1>
      <MyComponent />
    </main>
  )
}

export default MyParent;
```
### Call As Function

``` jsx
// ./MyParent.jsx
import React from 'react';
import MyComponent from './MyComponent.jsx';

function MyParent(props){
  return (
    <main>
      <h1> my-parent </h1>
      { MyComponent() }
    </main>
  )
}

export default MyParent;
```

## OR

this is possible use CAF (call-as-function)? :thinking: 
and this is good or bad style guid for react? :thinking: 

thank everyone :hugs:

**Comment by ljharb** [comment]
Never, ever, call a component as a function. This breaks hooks and a bunch of other aspects of React.

**Comment by miko-github** [comment]
> Never, ever, call a component as a function. This breaks hooks and a bunch of other aspects of React.
# Thanks @ljharb :heart:

**Comment by miko-github** [comment]
# And ...

and what about variables?
alike
``` jsx
// ./MyComp.jsx
const MyComp = (<div> ... </div>);

export default MyComp;
```
and import usage
``` jsx
// ./MyParent.jsx
import React from 'react';
import MyComp from './MyComp.jsx';

function MyParent(){
  return(
    <main>
    ... stuff jsx
    { logic && (MyComp) }
    </main>
  )
}

```

- [ ] is this possible? :thinking:

**Comment by ljharb** [comment]
That is quite possible, but it's pretty weird to make jsx at module level (as opposed to inside a component), and it's even weirder to export it. The atom you should be preferring is "component", not "jsx".

**Comment by miko-github** [comment]
# Thanks Again :heart: :star:
