### ISSUE TITLE
[react] - which one good and which one isn't?

### ISSUE THREAD

**Issue by miko-github** [airbnb/javascript#2447]
# Hi Developers :wave: 

## which one is better?
> 1, 2, 3, 4, 5
>
> and why? :thinking: 

> NOTE : i using class instead className, just for clean view :hugs: :v: 

**1**
```jsx
function Parent({ children }) {
  return <div class="parent">{children}</div>;
}
```
---

**2**
```jsx
function Parent({ children }) {
  return <div class="parent">{children.map((child) => child)}</div>;
}
```
---

**3**
```jsx
function Parent({ children }) {
  return (
    <div class="parent">{React.Children.map(children, (child) => child)}</div>
  );
}
```
---

**4**
```jsx
function Parent({ children }) {
  return (
    <div class="parent">
      {children.map((Child) => (
        <Child />
      ))}
    </div>
  );
}
```
---

**5**
```jsx
function Parent({ children }) {
  return (
    <div class="parent">
      {React.Children.map(children, (Child) => (
        <Child />
      ))}
    </div>
  );
}
```
---

thanks for your answering :heart: :+1:

**Comment by ljharb** [comment]
2 and 3 are completely useless. 4 and 5 only works if every child is a component, which it probably won’t be. 

So, only 1 makes even the tiniest amount of sense.

**Comment by miko-github** [comment]
> 2 and 3 are completely useless. 4 and 5 only works if every child is a component, which it probably won’t be.
> 
> So, only 1 makes even the tiniest amount of sense.

# Thankfully :heart: :v: 


and what about below syntax? :thinking: 
```jsx
function Parent({ children }) {
  return <div class="parent">{...children}</div>;
}
```

**Comment by ljharb** [comment]
I don't believe that's valid syntax in JSX, so that wouldn't even compile. Have you tried it?

**Comment by miko-github** [comment]
> I don't believe that's valid syntax in JSX, so that wouldn't even compile. Have you tried it?

yes, I'm tried and give me **ERROR** :smile: 


thankful :heart: :heart:
