### ISSUE TITLE
[react] - is possible to toggle attributes in JSX?

### ISSUE THREAD

**Issue by miko-github** [airbnb/javascript#2448]
# Hi Develpers :wave:,

## Is possible to toggling attributes in jsx?

> NOTE : this is just simple, and no more

```jsx
// we imported MyComp
<MyComp { isSomeStuff() ? `data-attribute` : '' } />
```

**OR**

```jsx
<MyComp { isSomeStuff() ? ` id="id-value" ` : ` className="class names" ` } />
```
**and if not, how can i make it possible?**

:heart: :v:

**Comment by miko-github** [comment]
## And, Is this possible to use condition without return `undefined` or `null`?

**Example**

```jsx
<Comp class={`class-name ${ isStuff() && 'other-class-name' }`} />
```
if `isStuff()` isn't truth that return `false` or `undefined` and class name be like `'class-name false'` or `'class-name undefined'`

and how fix them without using `isStuff() ? 'other' : ''`?


thanks if you answering this :heart: :+1:

**Comment by ljharb** [comment]
In the first example, you’d use object spread - `<Comp {...(a ? { a: 1 } : { b: 2 }} />`

for the second, no - that’s js language syntax to produce a string. So the ternary is your only option.

for class names tho, check out https://npmjs.com/classnames

**Comment by miko-github** [comment]
> In the first example, you’d use object spread - `<Comp {...(a ? { a: 1 } : { b: 2 }} />`
> 
> for the second, no - that’s js language syntax to produce a string. So the ternary is your only option.
> 
> for class names tho, check out https://npmjs.com/classnames

# Thank you so much :heart:
