### ISSUE TITLE
Use one var declaration per variable will cause more performance

### ISSUE THREAD

**Issue by lvarayut** [airbnb/javascript#245]
In your guide, you recommended to use one var declaration per variable: 

```javascript
// bad
var items = getItems(),
    goSportsTeam = true,
    dragonball = 'z';

// bad
// (compare to above, and try to spot the mistake)
var items = getItems(),
    goSportsTeam = true;
    dragonball = 'z';

// good
var items = getItems();
var goSportsTeam = true;
var dragonball = 'z';
```

However, IMHO, I think that the first one is the best because it's more concise and also makes better performance. What do you think?

**Comment by goatslacker** [comment]
The second example shows the very reason we switched from one-var to multi-var style; but I can elaborate some more on more reasons why one-var sucks.

Aside from the possibility of leaking global variables by mistake.

If you're making a change where you're adding more variables, then your changeset will now include 2 lines:

```js
// old
var foo = 1,
      bar = 2;

// new
var foo = 1,
      bar = 2,
      baz = 3;
```

This messes up your git history.

Another reason is the funky indentation. Too many times I've seen this crop up:

```js
var foo = 1,
      bar = 2,
      baz = function () {
        // some really long method here
      },
      lorem = function () {
        // another method
      };

// begin function
```

As for performance, they both initialize variables, it's the same thing. http://jsperf.com/one-var-multiple-var

**Comment by lvarayut** [comment]
:+1:  Thanks for your response. It's reasonable.
