### ISSUE TITLE
*install-peerdeps* is not working.

### ISSUE THREAD

**Issue by dohaelee** [airbnb/javascript#2456]
I was update `npm` 5.x to 7.x version.
since then `npx install-peerdeps --dev eslint-config-airbnb` is not working.
(just npm told me 'ERR undefined`.)
What am I missing?

**Comment by ljharb** [comment]
Does `npm ls` succeed? Your dep graph has to be valid for most things to work.

**Comment by dohaelee** [comment]
> Does `npm ls` succeed? Your dep graph has to be valid for most things to work.
> 
> Also, make sure you're on the very latest npm 7; there's lots of bugs fixed.

Thx for the comment.
✅ `npm` version is `7.21.0` and `npm ls` succeed.  
But I still get the same error. (ERR undefined)
Is there anything else I can do?

**Comment by ljharb** [comment]
What happens if you run `npm install --save-dev eslint-config-airbnb@latest eslint@^5.16.0 || ^6.8.0 || ^7.2.0 eslint-plugin-import@^2.22.1 eslint-plugin-jsx-a11y@^6.4.1 eslint-plugin-react@^7.21.5 eslint-plugin-react-hooks@^4 || ^3 || ^2.3.0 || ^1.7.0`?

**Comment by dohaelee** [comment]
> What happens if you run `npm install --save-dev eslint-config-airbnb@latest eslint@^5.16.0 || ^6.8.0 || ^7.2.0 eslint-plugin-import@^2.22.1 eslint-plugin-jsx-a11y@^6.4.1 eslint-plugin-react@^7.21.5 eslint-plugin-react-hooks@^4 || ^3 || ^2.3.0 || ^1.7.0`?

It's working!
I think just only shortcut commands (`npx install-peerdeps --dev eslint-config-airbnb`) don't seem to work.

```console
$ npm install --save-dev eslint-config-airbnb@latest eslint@^5.16.0 || ^6.8.0 || ^7.2.0 eslint-plugin-import@^2.22.1 eslint-plugin-jsx-a11y@^6.4.1 eslint-plugin-react@^7.21.5 eslint-plugin-react-hooks@^4 || ^3 || ^2.3.0 || ^1.7.0

added 219 packages, and audited 220 packages in 6s

37 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

```console
$ npm ls

test@1.0.0 /Users/dohae/Documents/repos/til/test
├── eslint-config-airbnb@18.2.1
└── eslint@5.16.0
```

**Comment by ljharb** [comment]
In that case, please file a bug on https://www.npmjs.com/package/install-peerdeps
