### ISSUE TITLE
ES6/2015

### ISSUE THREAD

**Issue by hshoff** [airbnb/javascript#247]
This one's for the Airbnb team.

- [x] Document ES6/2015 style.
- [x] How to move to ES6/2015 guide.
- [x] Maintain ES5

Ongoing.

**Comment by ascott** [comment]
:100:

**Comment by kevingimbel** [comment]
looking forward! :+1:

**Comment by danielbayerlein** [comment]
:heart:

**Comment by lvarayut** [comment]
:beers:

**Comment by justjake** [comment]
Proposal: prefer to use functional array transforms using method-chaining and implicit-return fat-arrow functions:

```javascript
// bad
var result = [];
for (var i=0; i<initial.length; i++) {
  if (initial[i].attr.isAdmin) {
    result.push(initial[i].attr);
  }
}
result.sort(function(a, b) {
  return a.count - b.count;
});

// good
var result = initial
  .map((m) => m.attr)
  .filter((m) => m && m.isAdmin)
  .sort((a, b) => a.count - b.count);
```

**Comment by gaearon** [comment]
Proposal: always use `const` unless `let` is needed. Don't use `var`.
I think I saw this in Mozilla guide, saved my ass a few times.

**Comment by goatslacker** [comment]
That's in the works ;)

**Comment by justin808** [comment]
Is there a eslint/jshint configuration file? Is there a PR with ES6/JSX support? @gaearon do you mind sharing what you're using?

**Comment by goatslacker** [comment]
Yes, there will be a PR with both ES6 and JSX.

**Comment by hshoff** [comment]
Current plan:

1. open PR updating `README` to be ES6
  - es6 addresses a lot of currrent "best practices" mentioned in the current version
  - as Airbnb moves to ES6 it makes sense for the main `README` to be in ES6 since it documents our style
  - @goatslacker and the team have been hard at work on our ES6 style guide and we're excited to share with the community and get some feedback (soon!)
2. create a `es5` directory and move current `README` to `es5/README`
  - we realize not everyone is moving to es6 right now, we will continue to maintain the es5 styleguide in this repo
3. add links to es5 style guide for the sections that relate to changes from es5

We recognize this will be a big change to move the main repo document from es5 to es6, but we hope by moving forward it will add clarity and help push adoption of es6.

The benefit will be that the community can help each other learn/discuss best practices around es6.

Another benefit to this new structure is we can add additional style guides as their own folders, such as our internal `React` style guide and open those up to the community as well.

An open question is how we work with linter/formatter projects that support the airbnb style through presets and how we handle the es5 => es6 change there. Lots of folks are consuming the airbnb style through those configurations in their tool chain. We should make sure we don't step on any toes there because there's a lot of great work happening in that part of the javascript world.

Does this plan sound too scary? Sound reasonable? What are folks' thoughts on this? We're open to feedback as we make this transition.

**Comment by justin808** [comment]
@hshoff I just converted this tutorial project to use the current style guide with eslint, ES6, and ReactJs
https://github.com/justin808/react-webpack-rails-tutorial/pull/25. You can see the toolchain of npm packages to make eslint work. The only rule I disagree with is a 80 char line limit. 100 seems much more reasonable.

**Comment by hshoff** [comment]
Woo! Today's the day. Let's move this discussion on over to https://github.com/airbnb/javascript/pull/276

**Comment by hshoff** [comment]
Jumped the gun, still need to document a How to guide for migration. :grimacing:

**Comment by breandr** [comment]
Could someone explain the reasoning behind "When you access a complex type you work on a reference to its value"? Love the style guide!

**Comment by DinhNC** [comment]
I am looking forward. <3
But @hshoff :  "still need to document a How to guide for migration" +1:

**Comment by brandon-collins** [comment]
@breandr I think it can be demonstrated with an example.

    // this is a complex type which after creation is accessed by reference.
    var a = { one: 'one', two: 'two' };
    // this does not create a copy of a because it is accessed by reference.
    var b = a;
    b.one = 'three';
    
    // you will see that when a and b print they will both look like: { one: 'three', two: 'two' }
    console.log(a);
    console.log(b);

    // this is a primitive and not accessed by reference.
    var c = 'boom';
    var d = c;
    
    d = 'shoom';
    
    // you will se that when c and d print they will look different
    console.log(c);
    console.log(d);

**Comment by breandr** [comment]
Thanks for the explanation! But it's not what I was asking haha. I thought
the style guide was suggesting you should not do work directly on an object
but instead create a reference to it and do work on that. I thought maybe
it was an attempt to make it easier to move to immutable objects in the
future. But maybe it's not suggesting that at all and is just a reminder of
how objects work. If that's the case, it seems a little odd to be included
in a style guide. Am I missing something?

**Comment by brandon-collins** [comment]
@breandr I do believe the 'types' section is simply a reminder of the different data types in javascript and how they behave differently. I think it is a useful reminder especially to people new to javascript or programming in general. By reference vs by value still tricks me at times even after many years of programming. Perhaps they should clearly demarcate reminders from suggestions or annotate reminders as 'reminders'. I infer that the 'types' section is a reminder from the language they use but I did not write the style guide so I cannot be sure. The language 'when you...' is not suggesting anything which contrasts with 'use the...', or "don't use..."

**Comment by justjake** [comment]
@breandr I think one thing we could be clearer about here is that `const foo = {};` creates an immutable binding `foo` that refers to a regular object, _not_ an immutable object. It's important to distinguish between reference types and value types when it comes to `const` because you get different behavior in Javascript versus in other languages. You *can* mutate the value referenced, just not the binding.

**Comment by hzoo** [comment]
I've been adding some of the ES6 rules for JSCS (to help migrate to the new rules). I didn't make an issue for everything as there was a lot. It would be helpful to get some feedback/suggestions too!

**Already there**
`disallowKeywords: ['var']`: [airbnb/javascript#2.1](https://github.com/airbnb/javascript#2.1) jscs-dev/node-jscs/issues/1309
`disallowIdentifierNames: [arguments]`: [airbnb/javascript#7.6](https://github.com/airbnb/javascript#7.6) jscs-dev/node-jscs/issues/1305

**In Progress/Done**
`requireArrowFunctions `: [airbnb/javascript#8.2](https://github.com/airbnb/javascript#8.1) jscs-dev/node-jscs/issues/1383
`disallowParenthesesAroundArrowParams`: [airbnb/javascript#8.2](https://github.com/airbnb/javascript#8.2) jscs-dev/node-jscs/issues/1307
`requireShorthandArrowFunctions`: [airbnb/javascript#8.2](https://github.com/airbnb/javascript#8.2) jscs-dev/node-jscs/issues/1340
`requireSpread `: [airbnb/javascript#8.2](https://github.com/airbnb/javascript#4.3) jscs-dev/node-jscs/issues/1326
`requireTemplateStrings`: [airbnb/javascript#6.4](https://github.com/airbnb/javascript/tree/master#6.4)jscs-dev/node-jscs/issues/1330

**Haven't started**
`requireComputedPropertyInObject`: [airbnb/javascript#3.4](https://github.com/airbnb/javascript/tree/master#3.4) https://github.com/jscs-dev/node-jscs/issues/1384
`requireDefaultParameters`:  [airbnb/javascript#7.7](https://github.com/airbnb/javascript/tree/master#7.7) https://github.com/jscs-dev/node-jscs/issues/1387
