### ISSUE TITLE
Allow custom acc naming in reduce (excluding for no-param-reassign)

### ISSUE THREAD

**Issue by dartess** [airbnb/javascript#2476]
HI!

`no-param-reassign` makes an exception for the reducer accumulator nicely ('acc', 'accumulator').

But this names are not informative. You often want to have clearer names. A frequent case when I am in a chain of methods, and it is not immediately clear what will be stored in the accumulator.

How do you look at expanding the list of exceptions with regular expressions?

E.g. like this:

```
  ignorePropertyModificationsForRegex: [
    '^acc.+',
  ],
```

**Comment by ljharb** [comment]
That would be up to the eslint rule (and separately a good eslint rule would never allow a regex pattern to be supplied by config).

It's not up to the airbnb config what things rules support.

**Comment by ljharb** [comment]
(Separately, while reduce is great, there's very few use cases that aren't covered by Array flat/flatMap, and Object.fromEntries, so i'd bet that if you provided some reduce examples i could show you a better non-reduce version)

**Comment by dartess** [comment]
@ljharb  I apologize, I still don't understand English well.

You say that the rules configured with regular expressions are bad.

But you also added the label "needs eslint rule change/addition".

I don’t understand if my proposal is good or not? :D 

> (Separately, while reduce is great, there's very few use cases that aren't covered by Array flat/flatMap, and Object.fromEntries, so i'd bet that if you provided some reduce examples i could show you a better non-reduce version)

I really love iterating over array methods as well as Object.fromEntries. But right now I'm trying to brush up on the existing codebase without refactoring the code. This is where it came from. Probably, for a fresh codebase, my proposal is really not relevant. But I thought that I still had to open this issue.

**Comment by ljharb** [comment]
The label is added because there's nothing we can do unless eslint makes a change.

Separately, I don't think that would be a good change for them to make.

**Comment by dartess** [comment]
> The label is added because there's nothing we can do unless eslint makes a change.

Eslint already [has ](https://eslint.org/docs/rules/no-param-reassign#options)`ignorePropertyModificationsForRegex` config for `no-param-reassign`

**Comment by ljharb** [comment]
ah, thanks, i was missing that part. Must be a legacy option before they stopped allowing regex configs.

**Comment by ljharb** [comment]
In that case, it's something we could do, but your suggested regex seems more complex than just adding "accumulator".

I'd still like to see the code that warrants the change.
