### ISSUE TITLE
On v15 all imports are erroring.

### ISSUE THREAD

**Issue by WilsontheWolf** [airbnb/javascript#2496]
Hello there. I'm trying to update to v15 of airbnb base. However, upon doing so all of our imports are throwing 
`Cannot use import declarations in modules that export using CommonJS (module.exports = 'foo' or exports.bar = 'hi')  import/no-import-module-exports`
I haven't found anything about what is wrong in my code. If I could get some insight into what I'm doing wrong that would be greatly appreciated. Here is some info.

.eslintrc.json
```json
{
    "env": {
        "es2021": true,
        "node": true
    },
    "extends": ["airbnb-base", "prettier"],
    "parserOptions": {
        "ecmaVersion": 12,
        "sourceType": "module"
    },
    "rules": {
        "no-console": "off",
        "no-param-reassign": "off",
        "no-restricted-syntax": "off"
    }
}
```
Eslint version `^8.2.0`

A screenshot of the error
![image](https://user-images.githubusercontent.com/33164598/140973584-92573838-b5a3-44e0-8fb0-ee3ed59d7867.png)

**Comment by ljharb** [comment]
Are you using `module.exports =` in that file? (can you share the entire contents of the file, as text?)

**Comment by WilsontheWolf** [comment]
Sure. Here Is one of the files ```js
import fs from 'fs/promises';

const subscriptions = new Map();

export default async (client) => {
    /**
     * loads all modules and their subscriptions
     */
    const modules = await fs.readdir('./src/modules');

    await Promise.all(
        modules.map(async (moduleName) => {
            // Loads the module
            const module = await import(`./modules/${moduleName}/module.js`);
            // skips the module, in case it is disabled.
            if (module.enabled) {
                // Loads each of it's subscriptions into their according list.
                module.subscriptions.forEach((fun, event) => {
                    if (!subscriptions.has(event)) {
                        subscriptions.set(event, []);
                    }
                    subscriptions.get(event).push(fun);
                });
            }
        })
    );

    /**
     * Setting up all events.
     * binds all events inside the subscriptions map to call all functions provided
     */
    subscriptions.forEach((funs, event) => {
        client.on(event, (...args) => {
            funs.forEach(async (fun) => {
                try {
                    await fun(client, ...args);
                } catch (e) {
                    client.emit('error', e);
                }
            });
        });
    });
};
```
I just noticed it isn't all files, but actually just ones I import `fs/promises` in.

**Comment by ljharb** [comment]
Seems like I can reproduce this; looking into it.

Could you file an issue for this (with the same content) on `eslint-plugin-import` directly?

In the meantime, you can disable the rule in your eslint config to avoid the errors.

**Comment by WilsontheWolf** [comment]
Yeah I can do that. Thanks.

**Comment by ljharb** [comment]
The issue seems to be when you've named a variable `module` or `exports`, and also have at least one `import` statement present.

It's a bug in eslint-plugin-import; we'll try to resolve it there.

**Comment by hasnaindev** [comment]
@ljharb Was this issue resolved? I'm using WebPack along with HMR where WebPack provides a "module" variable. I looked at your comment and removed this line from code and the error vanished.

`if (module && module.hot) module.hot.accept();`

I took me several hours to get here and realize what exactly the issue was. I'm using the latest packages and the issue is still there. Thank you!

**Comment by ljharb** [comment]
@hasnaindev if it’s still there in v2.25.3 or later of the import plugin, please file a new issue there.

**Comment by ljharb** [comment]
@jt3k no, but you can file a new issue.
