### ISSUE TITLE
Incorrect error `no-promise-executor-return`

### ISSUE THREAD

**Issue by vladmandic** [airbnb/javascript#2497]
This is new error when using `eslint-config-airbnb-base` 15.0, it was not present in 14.x

This syntax
```js
  const wait= new Promise((resolve) => setTimeout(() => resolve(true), time));
```
Triggers:
> error  Return values from promise executor functions cannot be read  no-promise-executor-return

Simply wrapping function like this makes the problem disappear
```js
  const wait= new Promise((resolve) => setTimeout(() => { resolve(true), time); });
```

**Comment by ljharb** [comment]
The bug (in the core rule) is that the second one works. The proper way to do this is:

```js
const wait= new Promise((resolve) => { setTimeout(() => resolve(true), time); });
```

Using the concise form of an arrow function is good when the return value matters; it's harmful when the return value does not matter, which is the case for Promise executor functions.
