### ISSUE TITLE
Conditional Expressions & Equality section should be named Comparison operators

### ISSUE THREAD

**Issue by fvanderwielen** [airbnb/javascript#251]
Section 9 is named Conditional Expressions & Equality, however, its subject matter seems to be covering comparison operators. 

From the MDN:
Comparison operators: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators 
Conditional expressions: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator

**Comment by goatslacker** [comment]
Good catch, submit a PR :)
