### ISSUE TITLE
Point 3.8 looks unclear regarding spread operator.

### ISSUE THREAD

**Issue by Yatin-kathuria** [airbnb/javascript#2514]
Point 3.8 looks unclear regarding spread operator.
> refer the object spread operator over Object.assign to shallow-copy objects. Use the object rest operator to get a new object with certain properties omitted.

actually 
> The spread operator makes deep copies of data if the data is not nested. When you have nested data in an array or object the spread operator will create a deep copy of the top most data and a shallow copy of the nested data.

#### References
[Medium](https://medium.com/@kevinlai76/the-spread-operator-deep-and-shallow-copies-d193ac9b58bf)
[Stackoverflow](https://stackoverflow.com/questions/61421873/object-copy-using-spread-operator-actually-shallow-or-deep)

**Comment by ljharb** [comment]
What part is unclear?

The spread operator does not make a deep copy of anything; medium and SO are not authoritative references of anything. Nothing in JS makes a deep copy of anything.

**Comment by Yatin-kathuria** [comment]
I hope MDN is a good source to verify [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax)

This is from `copy an array` section on mdn
> Note: Spread syntax effectively goes one level deep while copying an array. Therefore, it may be unsuitable for copying multidimensional arrays, as the following example shows. (The same is true with Object.assign() and spread syntax.)

**Comment by ljharb** [comment]
Yes; "one level deep" is "shallow" which is "not deep".

**Comment by innManish** [comment]
@Yatin-kathuria , see my pull req,
gd or not
