### ISSUE TITLE
Unable to detect issues in react class components

### ISSUE THREAD

**Issue by sarbesh007** [airbnb/javascript#2519]
Linting works properly for react functional components but fails to load linting issues with react class components

here is my .eslintrc.json

`{
    "env": {
        "browser": true,
        "commonjs": true,
        "es6": true
    },
    "extends": [
        "airbnb",
        "airbnb/hooks",
        "prettier"
    ],
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": 12,
        "sourceType": "module"
    },
    "plugins": [
        "react",
        "prettier"
    ],
    "rules": {
        "prettier/prettier": "warn"
    }
}
`
here are the packages installed for linting

`"devDependencies": {
    "eslint": "^7.2.0",
    "eslint-config-airbnb": "18.2.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react": "^7.21.5",
    "eslint-plugin-react-hooks": "^1.7.0",
    "prettier": "^2.4.1"
  }`

**Comment by ljharb** [comment]
Please file an issue on eslint-plugin-react (or eslint-plugin-jsx-a11y) about the specific rules you expect to be warning on class components that aren’t.
