### ISSUE TITLE
Classification of an Object Naming Convention

### ISSUE THREAD

**Issue by haydaralrikabi** [airbnb/javascript#2543]
The [naming convention 23.8](https://github.com/airbnb/javascript#naming--PascalCase-singleton) lists the following classifications: (constructor / class / singleton / function library / bare object).
Which one of them best fit the given example there (shown below), and why?
```
const AirbnbStyleGuide = {
  es6: {
  },
};

export default AirbnbStyleGuide;
```

**Comment by ljharb** [comment]
That's not really enough context/information to know how it's intended to be used.

It's certainly not a constructor or a class (which are functions).

**Comment by innManish** [comment]
@haydaralrikabi see my pull req,
gd or not
