### ISSUE TITLE
 Configuration for rule "prefer-regex-literals" is invalid

### ISSUE THREAD

**Issue by frontendplace** [airbnb/javascript#2545]
I still get this error for the rule in the eslint-config-airbnb-base\rules\best-practices.js
 
Configuration for rule "prefer-regex-literals" is invalid:
        Value [{"disallowRedundantWrapping":true}] should NOT have more than 0 items.

When I run it with eslint directly I don't get the error but when I run this with eslint through gulp-eslint then I get this error. 
Does this mean the gulp-eslint version is too old or is this an error in the airbnb base settings?

using: 
"eslint": "^8.2.0",
"eslint-config-airbnb-base": "^15.0.0",
"gulp-eslint": "^6.0.0"

**Comment by ljharb** [comment]
You’re using too old an eslint version. Run `npm ls` to see if your dep graph is invalid.

**Comment by frontendplace** [comment]
"eslint": "^8.7.0", if I use this latest version I get the same error

**Comment by ljharb** [comment]
Then it's gulp-eslint. As you can see here: https://unpkg.com/browse/gulp-eslint@6.0.0/package.json gulp-eslint is broken. It should be listing eslint as a peer dep ONLY, but it lists it as a regular dep, and it's using v6, which is ancient.

I can't recommend strongly enough that you ditch gulp entirely.

**Comment by frontendplace** [comment]
thanks. yes looking at the dependency tree it still uses version eslint 6.8 and not updated since 3 years

**Comment by ljharb** [comment]
(－‸ლ) for your own sake, please ditch gulp and just invoke eslint using npm run-scripts :-)

**Comment by yashwanthvelupula** [comment]
function timer() {
  document.getElementById("timer").
  innerHTML = time;
}
    
function timer2() {
  document.getElementById("timer2").
  innerHTML = time;
}

function runAll() {
    let
    date = new Date(),
    mins = date.getMinutes(),
    secs = date.getSeconds();
    
    time = mins + " : " + secs;
    
    timer();
    timer2();
}

setInterval(runAll, 1000);
