### ISSUE TITLE
Some of your explanations are technically incorrect and even flat out wrong

### ISSUE THREAD

**Issue by velociwabbit** [airbnb/javascript#2546]
I  have always strongly disagreed with many of the lint values that Airbnb proffer as best styling practices.

Now I know why.

There are some justification and styles that are flat-out incorrect. Big hit +val is not ParseInt... 

And the roe vs wade logic of including semicolons is gobsmacking.

I just want to say thank you. And keep up the good work.

The more people that use your wisdom the less the competition for delivery of high-quality code in a timely fashion.

BTW +val has been used for at least 10 years before this list.  But of course, you know better!

**Comment by ljharb** [comment]
This is a really disruptive, unhelpful, and incoherent post, and a violation of airbnb's code of conduct.
