### ISSUE TITLE
Whether 11.1 is reasonable ? 

### ISSUE THREAD

**Issue by psrx** [airbnb/javascript#2548]
Don’t use iterators. Prefer JavaScript’s higher-order functions instead of loops like for-in or for-of

```js
const numbers = [1, 2, 3, 4, 5];

// bad ----> Very, very good
let sum = 0;
for (let num of numbers) {
  sum += num;
}
sum === 15;

// good ---> No!  No! No!
let sum = 0;
numbers.forEach((num) => {
  sum += num;
});
sum === 15;
```

I think it foolish to use forEach instead of forof
This is not pure function at all

In the example, the sum global variable is modified

**Comment by ljharb** [comment]
Yes, it’s reasonable. This has been discussed at great length on other issues.
