### ISSUE TITLE
Section 18.2 rules not enable?

### ISSUE THREAD

**Issue by thernstig** [airbnb/javascript#2549]
Looking at https://github.com/airbnb/javascript#comments--singleline and then these:

https://github.com/airbnb/javascript/blob/b4377fb03089dd7f08955242695860d47f9caab4/packages/eslint-config-airbnb-base/rules/style.js#L167-L174

https://github.com/airbnb/javascript/blob/b4377fb03089dd7f08955242695860d47f9caab4/packages/eslint-config-airbnb-base/rules/style.js#L184-L185

They do not correlate. Is that intentional? I _guess_ the documentation in the README is supposed to reflect what is configured in the rules, but my assumption might of course be incorrect.

**Comment by ljharb** [comment]
The readme is what’s in charge. The links are what rules can be used to enforce things. The config can’t enforce the entire guide (because it’s not possible) and doesn’t enforce everything the guide requires (because in practice, it’s been found to be too noisy), but the guide still is the source of truth.

**Comment by thernstig** [comment]
@ljharb I see, so the goal of the guide is to recommend to use what is described in 18.2, but then to add those rules myself?

Could this be made more clear in the guide from the start? I would guess users in general believe the rules defined in the config is a reflection of the guide's recommendation. At least when I spoke around to a few developer colleagues.

**Comment by ljharb** [comment]
They certainly shouldn’t conflict - the config will always be a subset of the guide. We however don’t, for example, use no-restricted-syntax to block every kind of loop, despite that being in the guide, because it gets too noisy for some codebases.

**Comment by thernstig** [comment]
Got it. Not clear from the README.md but at least I know now.
