### ISSUE TITLE
Should there possibly be a clearer error text for `react/function-component-definition`?

### ISSUE THREAD

**Issue by gpkc** [airbnb/javascript#2554]
For me, the current error description ("Function component is not a function declaration") is ambiguous when using arrow functions. I've read https://github.com/airbnb/javascript/issues/2505 and understand the reasoning but it is almost a matter of semantics whether an arrow function assigned to a const variable is a "declaration" or not, specially nowadays with ES6 being extremely widespread and people using both forms interchangeably. So it took me a while debugging this after upgrading some packages thinking it was something else. Maybe a note `(no arrow functions allowed)` or something like that would do it.

**Comment by ljharb** [comment]
sure, improving the error message here would be a fine PR. Perhaps "non-arrow function declaration"?

**Comment by ljharb** [comment]
That said, I'm going to close this, since it belongs filed on eslint-plugin-react, not here :-)
