### ISSUE TITLE
why is this flagged?

### ISSUE THREAD

**Issue by smlombardi** [airbnb/javascript#257]
This block of code:

````
_this.numericStepper = {
      'limit': [0], // no negative numbers
      'wheelStep': 1,
      'arrowStep': 1
    };
````
I get an warning "extra quotes for key".  Not sure why...

**Comment by tschwartz** [comment]
It's because you don't actually need the quotes for keys unless you wish to use a dash in the key.

**Comment by smlombardi** [comment]
If I take them off, js hint flags it an error.

**Comment by tschwartz** [comment]
This isn't going to be of much help... But I copied your code into a file, copied the airbnb .jshintrc local to that file and ran JS Hint on it and had not a single error.

**Comment by goatslacker** [comment]
Just copied this code into http://jshint.com/ and it works fine. Paste your .jshintrc config?
