### ISSUE TITLE
Style for Negative Variables

### ISSUE THREAD

**Issue by Zamiell** [airbnb/javascript#2570]
Hello, and thanks for the excellent style guide.

Does Airbnb take a stance on negative variables? For example,

```js
const foo = bar * -1;
```
```js
const foo = -bar;
```

Which is preferred? Which is easier to read, if any? Which could lead to less bugs, if any?
These are all questions I am thinking about, but the answer isn't clear to me.

Related: Rule 19.4 says to "Set off operators with spaces". Thus, it seems that the second code snippet isn't compliant with this rule. On the other hand, I'm not sure that it would apply in this situation.

**Comment by ljharb** [comment]
I don't think "negative variables" is really a term that exists :-)

Personally I'd use the latter, but I think it depends on the context - if it's next to other multiplications, maybe the former would make more sense. I don't think it's a common enough problem to have come up.

19.4 refers to binary operators; unary operators like `-` here should not have a space between the operator and the operand.
