### ISSUE TITLE
What should the filename be of a file with no default exports?

### ISSUE THREAD

**Issue by Istanful** [airbnb/javascript#2572]
The rules state that a file with a default export should exactly match the name of the default export. What should the filename be of a file with no default export? Should such a file exist at all?

Consider the following file:

```javascript
export function getItem(key) {
  return localStorage.getItem(key);
}

export function setItem(key, value) {
  return localStorage.setItem(key, value);
}
```

In this case the guidelines does not seem to have a clear answer. I would lean towards `localStorage.js`, but I could see how `LocalStorage.js` could be considered as well.

**Comment by ljharb** [comment]
I agree there’s no clear answer here. However I’m not sure what the point is of making this module when local storage itself already exists and could be referenced directly.

**Comment by Istanful** [comment]
@ljharb Absolutely! `localStorage` is just a silly example. I've seen several developers use the same pattern for other stuff, and I'd love something to point at when the situation arises! :D

**Comment by ljharb** [comment]
I’m not sure if they’re silly, but i don’t think they’re common enough to warrant an explicit rule, so I’ll close it.

**Comment by xiaohubei** [comment]
来信已收到，我会尽快回复你，谢谢来信！
