### ISSUE TITLE
Since use of 'ForOfStatement' is not allowed and 'no-param-reassign'

### ISSUE THREAD

**Issue by SeasideLee** [airbnb/javascript#2585]
I have read the whole thread of #1271 and #851, knowing this has been discussed thousands of times. However I still have problems with how to update a property of each item in an array like following code?

```js
for (const item of list) {
  item.prop1.prop2.prop3 += 1;
}
```

It's not allowed to rewrite as following code for 'no-param-reassign'.

```js
list.forEach((item) => {
  item.prop1.prop2.prop3 += 1;  // 'no-param-reassign' issue
})
```

It seems that the only way is replacing with a new array by `Array.map()` but what if the property is deep level as above? Should I write like this?
```js
list = list.map((item) => {
  ...item,
  prop1: {
    ...item.prop1,
    prop2: {
      ...item.prop1.prop2,
      prop3: item.prop1.prop2.prop3 + 1,
    },
  },
});
```

Thanks for suggestions!

**Comment by ljharb** [comment]
Yes, you should write it like that last example - mutation should be avoided, as should loops. I'd also suggest not reassigning to `list`, and making a new variable instead.
