### ISSUE TITLE
.eslintrc

### ISSUE THREAD

**Issue by iamstarkov** [airbnb/javascript#259]
There are _.jscsrc_ and _.jshintrc_ in the wild performed in Airbnb style. Is there any _.eslintrc_ implementation?

**Comment by justin808** [comment]
Wondering the same thing, especially if one will support ES6/JSX.

**Comment by RobLoach** [comment]
Related: https://github.com/airbnb/javascript/issues/247

**Comment by justin808** [comment]
FYI:  I just converted this tutorial project to use the current style guide with eslint, ES6, and ReactJs
https://github.com/justin808/react-webpack-rails-tutorial/pull/25. You can see the toolchain of npm packages to make eslint work. The only rule I disagree with is a 80 char line limit. 100 seems much more reasonable.

**Comment by ziflex** [comment]
so, where can I get config file with these rules? :)

**Comment by nkbt** [comment]
@ziflex apparently https://github.com/airbnb/javascript/blob/master/linters/.eslintrc

**Comment by ziflex** [comment]
@nkbt ooops, sorry, didn't see :(
