### ISSUE TITLE
Update NPM packages

### ISSUE THREAD

**Issue by konstantinschuette** [airbnb/javascript#2594]
https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base

It looks like the packages are updated frequently. But the last publish on NPM was 6 month ago:
https://www.npmjs.com/package/eslint-config-airbnb-base

Is it possible that you update the package in the near future?

**Comment by ljharb** [comment]
The updates don’t change anything; they’re just updating dependencies. There’s no value in publishing that.

**Comment by ljharb** [comment]
The last published version of both packages absolutely does, for a long time now. See #2478

**Comment by Naseem010** [comment]
should i update npm?
