### ISSUE TITLE
isNaN on string returns false

### ISSUE THREAD

**Issue by sacredwx** [airbnb/javascript#2602]
![image](https://user-images.githubusercontent.com/28864958/172442142-995fee4b-17cc-4d16-bf39-f67e9d414b88.png)

Controversial to the traditional isNaN

**Comment by ljharb** [comment]
Yes, this is intentional - isNaN coerces to a number first, and `Number.isNaN` only returns true for the literal `NaN` value.

I'm not sure why you're filing this here, though.

**Comment by sacredwx** [comment]
I understand now that it is intentionally, however super not intuitive.
You are literally asking `is not a number`..

**Comment by ljharb** [comment]
To be clear, this repo is for Airbnb's JavaScript style guide, not for the JS language itself.

Number.isNaN is asking "is it `NaN`", not "is it not a number".
