### ISSUE TITLE
Function component is not a function declaration

### ISSUE THREAD

**Issue by codedbyjordan** [airbnb/javascript#2609]
I'm trying to use the React style guide for a project but I have been fighting with it for ages. In the docs it says to use arrow functions in components that don't use state, but when I do it throws an error saying

`Function component is not a function declarationeslint[react/function-component-definition](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/function-component-definition.md)`

This is the component I have
```jsx
const MyComponent = () => {
  return (
    <div>
      <h1>My component</h1>
      <p>My example component</p>
    </div>
  )
};
```

When I change it to this, it works

```jsx
function MyComponent() {
  return (
    <div>
      <h1>My component</h1>
      <p>My example component</p>
    </div>
  )
};
```

Here's my `.eslintrc.json`

```json
{
  "extends": ["airbnb", "airbnb-typescript"],
  "parserOptions": {
    "project": "./tsconfig.json"
  }
}
```

I'm using the latest version of VS Code

**Comment by ljharb** [comment]
The docs say to never use arrow functions for components, EVER, whether they use state or not.

**Comment by shaurya074** [comment]
hey! Can i work on this?
