### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by tomekwi** [airbnb/javascript#263]
What I like about [JS standard](https://github.com/feross/standard) is not only its simplicity (no config), but also branding. But Standard is just a bunch of opinions – it's far from this guide in terms of comprehensiveness.

But yes, I'm a visual thinker – and I do buy stuff by their looks :) But I guess so do many other developers and designers. Just as a good readme with a green travis badge looks reassuring, so does a well-known logo.

How about developing something similar to this:

[![js-standard-style](https://raw.githubusercontent.com/feross/standard/master/badge.png)](https://github.com/feross/standard)

**Comment by tomekwi** [comment]
It could have the AirBnB logo and a simple slogan like

### “coded in JavaScript style”

You've got great designers out there, telling by https://www.airbnb.com :)

**Comment by nkbt** [comment]
I do believe "JS Standard Code Style" should be used here instead of the other one which actually is "JS Opinionated Code Style"

**Comment by hshoff** [comment]
Interesting. I wonder if it'd be nice to make a general style badge  that's extensible in a way so it's easy to tell based on the readme what style the repo follows whether it's Airbnb, Crockford, jQuery, idiomatic or Standard. I want to think about this some more and will try to follow up later this week.

**Comment by tomekwi** [comment]
@hshoff, one option is to use <http://shields.io/>:

![](https://img.shields.io/badge/code%20style-airbnb-brightgreen.svg?style=flat-square)

@nkbt how about naming it

## “Quality JS code style”

IMO “airbnb” isn't a name which conveys a meaning. Using “JS Standard” code style feels cool – like it's the right thing to do. But using “google” code style, “airbnb” code style, “facebook” code style – or whatever – feels dull. There's no feeling behind it, no subconcious association.

 

 

Think about it:

![](https://img.shields.io/badge/code%20style-Quality%20JS-brightgreen.svg?style=flat-square)

– doesn't that feel reassuring?

**Comment by tomekwi** [comment]
By the way, the NPM package *quality* is free :)

Whether we just want to put the readme there, or a zero-conf tool like <http://npm.im/standard>.

**Comment by goatslacker** [comment]
![code style - Airbnb](https://img.shields.io/badge/code%20style-Airbnb-ff5a5f.svg)

**Comment by nkbt** [comment]
@tomekwi, agree, using Airbnb in a shield tells almost nothing how "much standard" it is. And it apparently is the most standard code style according to different code style surveys.

`quality` imho is kind of misleading for js code style guide (but still less so as `standard`).

@gaearon, what do you think?

**Comment by tomekwi** [comment]
> code style - Airbnb

@goatslacker I know this is your brand's color. But it looks like red, and red in a badge has a bad connotation.

How about a neutral blue – the same <http://shields.io> uses for stable semver version numbers?

[![code style: airbnb](https://img.shields.io/badge/code%20style-airbnb-blue.svg?style=flat-square)](https://github.com/airbnb/javascript)

**Comment by tomekwi** [comment]
@nkbt agreed – but airbnb/javascript is more than a code style guide. It's a mixture of best practices, explanations, benchmarks and code style.

**Comment by gaearon** [comment]
I'd be wary of any adjectives. I don't think right answer to `standard` is to label something `quality`. Somebody else will then create `awesome`, `great`, and it all becomes meaningless.

If we have any actual data proving this is the most widespread style, I'd be tempted to call it `community`. Still, `airbnb` looks absolutely fine with me.

**Comment by tomekwi** [comment]
> If we have any actual data proving this is the most widespread style, I'd be tempted to call it community. 

Seems reasonable – looking at <http://sideeffect.kr/popularconvention/#javascript>, it seems like `airbnb` matches all conventions measured as most popular. And look at the number of stars :)

**Comment by tomekwi** [comment]
Here’s my suggestion, to keep the discussion going:

![](https://raw.githack.com/tomekwi/javascript/d406e25/badges/big.svg)

**Comment by tomekwi** [comment]
And another variation – [“compatible” with the current repo name](https://github.com/airbnb/javascript/issues/301#issuecomment-91662416), so to speak:

![](https://raw.githack.com/tomekwi/javascript/95fbf8b/badges/big.svg)

**Comment by justjake** [comment]
Here's a screenshot of our branding from http://airbnb.io
![airbnb open source logo thing](http://take.ms/iX6MD)

**Comment by nkbt** [comment]
@justjake love `a mostly reasonable` :+1:

**Comment by tomekwi** [comment]
> love a mostly reasonable :+1:

:+1: to that as well! It’s a longish name, but way better than “airbnb style”.

The problem with “airbnb style” is simple. The name is no longer valid when you fork the project. [And forking seems to be common and encouraged](https://github.com/airbnb/javascript/tree/2a1f4f4a9fce9002a28588b65097f214f161d500#in-the-wild).

**Comment by justjake** [comment]
should we rebrand to `Mostly Resonable Style`?

**Comment by goatslacker** [comment]
The Mostly Reasonable Guide to Writing JavaScript Like a Boss

**Comment by tomekwi** [comment]
:smile:

**Comment by ariporad** [comment]
@justjake: :+1: Personally, I like mostly reasonable. It would be even nicer to have zero-config. (I've used standard a few times, despite not liking it, out of laziness). If we had a cli mr, that linted the pwd like standard, that would rock. Also, [`mostly-reasonable`](http://npm.im/mostly-reasonable), is available on npm.

**Comment by justjake** [comment]
I took a look at Standard Plus and considered forking their stuff to copy the standard interface. It seems pretty easy to do, but I personally have low interest in taking on that work in my spare time.

**Comment by ariporad** [comment]
It's crazy easy, I will gladly do it. It just uses eslint. Although, it would be nice first if we:


[] change our name to mostly-reasonable

[] update eslint-config-mostly-reasonable to actually match the style guide.

    [] I personally am a fan of auto-generating it with #480. Although I think we should go one step further and generate the eslint config off that.

[] create an ES5 eslint config, and have eslint-config-mostly-reasonable be ES5 or maybe 6, then have eslint-config-mostly-reasonable/es5 eslint-config-mostly-reasonable/es6 and eslint-config-mostly-reasonable/react.








On Tuesday, Oct 6, 2015 at 7:28 PM, Jake Teton-Landis <notifications@github.com>, wrote:

I took a look at Standard Plus and considered forking their stuff to copy the standard interface. It seems pretty easy to do, but I personally have low interest in taking on that work in my spare time.

**Comment by r01010010** [comment]
You don't know me at all, but as someone who is interested in a code
convention or style... to me the "Standard Code Style" made me feel that it
was what I was looking for. Made me feel secure and confortable, the one.

So I vote for it.

Also I agree with all the rules proposed on it so..

2015-10-07 6:39 GMT+02:00 Ari Porad <notifications@github.com>:

> It's crazy easy, I will gladly do it. It just uses eslint. Although, it
> would be nice first if we:
>
>
> [] change our name to mostly-reasonable
>
> [] update eslint-config-mostly-reasonable to actually match the style
> guide.
>
>     [] I personally am a fan of auto-generating it with #480. Although I
> think we should go one step further and generate the eslint config off that.
>
> [] create an ES5 eslint config, and have eslint-config-mostly-reasonable
> be ES5 or maybe 6, then have eslint-config-mostly-reasonable/es5
> eslint-config-mostly-reasonable/es6 and
> eslint-config-mostly-reasonable/react.
>
>
>
>
>
>
>
>
> On Tuesday, Oct 6, 2015 at 7:28 PM, Jake Teton-Landis <

**Comment by hshoff** [comment]
We were discussing this in https://github.com/airbnb/javascript/pull/455#issuecomment-128103763, here's the quick recap: 

We started by talking about the name/branding of the package (related to https://github.com/airbnb/javascript/issues/263) and @ljharb brought up the wonderful idea of using scoped npm packages. So the one-liner command would become:

```bash
npm install @airbnb/javascript --save-dev
```

Hopefully scoped packages catches on so if your team (Super Cool Co.) forks the guide and publishes your own package it would be:

```bash
npm install @supercoolco/javascript --save-dev
```

Which I think is a nice benefit of the scoped package route and encourages teams to use our guide as a starting point for their team's style guide.

`@airbnb/javascript` will be the one-step install package.

**Comment by r01010010** [comment]
Oh, thanks hshoff

**Comment by tomekwi** [comment]
Fair enough! Good to have this thing closed. 😃

**Comment by amazingandyyy** [comment]
here is the markdown version for anyon need it 

```md
[![Airbnb Javascript Style Guide]((https://camo.githubusercontent.com/546205bd8f3e039eb83c8f7f8a887238d25532d5/68747470733a2f2f7261772e6769746861636b2e636f6d2f746f6d656b77692f6a6176617363726970742f393566626638622f6261646765732f6269672e737667)
)](https://github.com/airbnb/javascript)
```

[![Airbnb Javascript Style Guide]((https://camo.githubusercontent.com/546205bd8f3e039eb83c8f7f8a887238d25532d5/68747470733a2f2f7261772e6769746861636b2e636f6d2f746f6d656b77692f6a6176617363726970742f393566626638622f6261646765732f6269672e737667)
)](https://github.com/airbnb/javascript)

**Comment by olstenlarck** [comment]
Hm. Why this popped up in my notifications, huh?

Anyway. Just to join the thread with few words - i already added badges `code style: airbnb` at @tunnckoCore. Same as the StandardJS badge, but `airbnb` instead of `standard`.

**Comment by arb** [comment]
I realize this is closed, but here is what I'm planning on using

![https://github.com/airbnb/javascript](https://img.shields.io/badge/eslint-airbnb-4B32C3.svg)

`https://img.shields.io/badge/eslint-airbnb-4B32C3.svg`

airbnb word with the "eslint" purple. 

In case anyone else is looking for a cute badge (I was)

**Comment by olstenlarck** [comment]
Make sense. But why purple? ;d The only reason i set it to bright green is consistency on the first line of my badges - trying always to be green (code style, build, codecov, deps).

**Comment by arb** [comment]
Because that's the purple that eslint uses was my thinking. All of my badges are already not the same color so I figured I'd pick something that has some meaning.

**Comment by leo** [comment]
This is the way to go folks:

[![Code Style](https://badgen.net/badge/code%20style/airbnb/fd5c63)](https://github.com/airbnb/javascript)

Here's the code:

```markdown
[![Code Style](https://badgen.net/badge/code%20style/airbnb/fd5c63)](https://github.com/airbnb/javascript)
```

You can thank @amio for this one! 😄

**Comment by ljharb** [comment]
@leo @amio i've updated your post to include a more accurate airbnb color code :-)

**Comment by ljharb** [comment]
@olstenlarck and i've updated yours to use the correct capitalization of Airbnb (never AirBnB)

**Comment by olstenlarck** [comment]
Hm, didn't know that, thanks.
