### ISSUE TITLE
`isNaN` question

### ISSUE THREAD

**Issue by raegen** [airbnb/javascript#2631]
Years of sleepless nights, lack of physical activity and other bits of dev déformation professionnelle seem to have started to take their toll. I find myself in an uncomfortable position asking this, but be as it may, there's no shame in asking for help. I'm having real trouble understanding what the following change implies.

[29.1](https://github.com/airbnb/javascript#standard-library--isnan) Use Number.isNaN instead of global isNaN. eslint: [no-restricted-globals](https://eslint.org/docs/rules/no-restricted-globals)
> Why? The global isNaN coerces non-numbers to numbers, returning true for anything that coerces to NaN. If this behavior is desired, make it explicit.

So, my (surely) misunderstanding is that the proposed fixed `isNaN` functionality is stripped of implicit type coercion, returning `true` only for a literal `NaN` value. But that would basically reduce it to `isNaN = (a) => a !== a` which can't be the case, 
can it?

**Comment by ljharb** [comment]
Yes, that is precisely the case.
