### ISSUE TITLE
Why is there no rule for space before arrow function parenthesis?

### ISSUE THREAD

**Issue by slim-codes** [airbnb/javascript#2647]
I have been working on a project recently and the closeness of the parentheses of methods enclosing arrow functions with the arrow functions's parentheses confuses me a lot. For example:

```js
someMethod((parameter) => function's body)
```

```js
someMethod( (parameter) => function's body )
```

- The first example is confusing particularly when an array method like `reduce` expects an extra argument like `initialValue`. 
- Furthermore, one has to discern between the brackets of the arrow and the reducer's enclosing brackets. With spacing, it will take just a single glance at both spaces attached to the reducer's brackets (see second example below).
```js
const myArray = [ 10, 20 ]
const initialValue = 70;
console.log(myArray.reduce((total, value, index) => total + value,  initialValue)) //100

```

```js
const myArray = [ 10, 20 ]
const initialValue = 70;
console.log(myArray.reduce( (total, value, index) => total + value,  initialValue) ) //100

```

Below is an example taken from the arrow functions section of the airbnb JavaScript style-guide
```js
[1, 2, 3].map((number) => `A string containing the ${number + 1}.`); //airbnb example
```

```js 
[1, 2, 3].map( (number) => `A string containing the ${number + 1}.` ); // this is clearer
```

**Comment by ljharb** [comment]
That is very much not clearer to me, and is very much not the most common style in the JS ecosystem for decades, so it’s not a change we’re likely to make here.
