### ISSUE TITLE
Create a config without eslint-plugin-imports

### ISSUE THREAD

**Issue by paztis** [airbnb/javascript#2655]
eslint-plugin-imports is causing lot of performances issues.
But disabling all its rules from config is not enough. To get back original performances we need to fully remove the plugin declaration.

Airbnb didn't allow us to do this. If you import airbnb you automatically get it.
I don't want to stop using airbnb and loose all the other great rules because of this

Is it possible to create another config similar to the legacy one that imports everything except the eslint-plugon-import part ?
like this
```
module.exports = {
  extends: [
    './rules/best-practices',
    './rules/errors',
    './rules/node',
    './rules/style',
    './rules/variables',
    './rules/es6',
    // './rules/imports',
    './rules/strict',
  ].map(require.resolve),
  parserOptions: {
    ecmaVersion: 2018,
    sourceType: 'module',
  },
  rules: {},
};
```

**Comment by ljharb** [comment]
If merely including the plugin, with no rules enabled, is causing any issues, then that’s a problem with eslint.

If you’re seeing performance problems with rules, file issues on the import plugin directly.

The rules ensure correctness, which is always far more important than performance, so we won’t be making it easier to skip these critical rules.
