### ISSUE TITLE
What is the monorepo best practice using airbnb-base and airbnb

### ISSUE THREAD

**Issue by jiwon-mun** [airbnb/javascript#2656]
I gonna make monorepo project which has two difference env project.( node version and react version ) 

So I want to build like this
```
// .eslintrc.root.js
module.export = {
  "extends": [
    "airbnb-base",
  ]
};
```

// react-project/eslintrc.js
```
module.export = {
  "extends": [
    "../.eslintrc.root.js",
    "airbnb-react" // there isn't yet
  ]
};
```

// node-project/eslintrc.js
```
module.export = {
  "extends": [
    "../.eslintrc.root.js"
  ]
};
```

I was able to find only `airbnb-base` and `airbnb` plugin.

Can I make `airbnb-base` root settings and extend the react rules in `airbnb` at sub-workspaces?

**Comment by ljharb** [comment]
That seems fine, it's just that the react one is `"extends": ["airbnb"]`.

**Comment by jiwon-mun** [comment]
Thank you for quick response. :)

**Comment by eudinnou** [comment]
@ljharb but doesn't this mean that the rules will run twice? or if a rule option in the root eslintrc file is changed, it's going to be ignored?

**Comment by ljharb** [comment]
No, rules can’t run twice, but yes, it means that an override at the root won’t affect the nested directory.

**Comment by eudinnou** [comment]
you are fast, thanks!
