### ISSUE TITLE
Which one Qux or Quux

### ISSUE THREAD

**Issue by mrna0** [airbnb/javascript#2661]
Hello,

It should be qux after foo, bar and baz, but quux is also used.

qux is in 2 places in the document.
quux is in 7 places in the document.

I think using just one of the two would look more consistent in the document.

**Comment by ljharb** [comment]
The convention is "quux", but it's really not that important since it's just a nonsense word. I don't think it's worth opening a PR just for that.

**Comment by mrna0** [comment]
I get it.
Thank you.
