### ISSUE TITLE
What do you think about long numbers?

### ISSUE THREAD

**Issue by mrna0** [airbnb/javascript#2663]
Long numbers have always been difficult to read.
For example; 100000000

Maybe a numeric separators can be used for this.
For example; 1_000_000_00 

More;
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#literals
https://www.javascripttutorial.net/es-next/javascript-numeric-separator/

**Comment by ljharb** [comment]
I don't think airbnb has a convention here.

Personally, I've always done `1e8`, or if it's representing something in the order of 10<sup>6</sup>, `100e6` to emphasize "100 units, of whatever 10<sup>6</sup> represents".

**Comment by mrna0** [comment]
I use this too. But this was just an example. 
But I understand what you're saying.
Thank you.
