### ISSUE TITLE
All JsPref links are broken

### ISSUE THREAD

**Issue by mrna0** [airbnb/javascript#2668]
Hello, I had such a situation.
And I want to let you know too.

![image](https://user-images.githubusercontent.com/4294069/198855733-3402d86f-c2e6-48ed-8256-97fc1cd74812.png)

**Comment by ljharb** [comment]
yes, I’m aware jsperf is down - I’d prefer to leave these in case it ever comes back.

**Comment by mrna0** [comment]
Maybe we can use the wayback machine until it comes back.

https://web.archive.org/

I can change it if you want to see it.

**Comment by ljharb** [comment]
If the pages actually load so you can see the code samples, that'd be fine, but I didn't think that worked for jsperf.
