### ISSUE TITLE
[eslint] [base] a linter skips a rule 5.2 (use array destructuring)

### ISSUE THREAD

**Issue by vladyslav-karpus** [airbnb/javascript#2671]
The rule [5.2](https://github.com/airbnb/javascript#destructuring--array) dictates to use destructing for unpacking values from an array as opposed to the simple way which is marked as a bad practice. But a linter allows this practice. See [code](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/es6.js#L125)
```js
const arr = [1, 2, 3, 4];

// bad
const first = arr[0];
const second = arr[1];

// good
const [first, second] = arr;
```

**Comment by ljharb** [comment]
The linter need not enforce everything in the guide.

Either way, there's no eslint rule that's capable of enforcing that, due to a lack of type information. Some things you just have to catch in code review.
