### ISSUE TITLE
`Configuration for rule "react/function-component-definition" is invalid`

### ISSUE THREAD

**Issue by TheInfamousGrim** [airbnb/javascript#2690]
I'm trying to use eslint .

I get the above error ⬆️ and it states that: Value ["function-declaration","function-expression"] should be equal to one of the allowed values.

I think the only way to solve the issue is to downgrade to a previous version. 

Here's my package.json in the root folder:

`{
  "name": "fakebook",
  "version": "1.0.0",
  "description": "A fullstack application designed to mimic facebook in a fake and fun way",
  "main": "index.js",
  "scripts": {
    "start": "node server/server.js",
    "dev": "nodemon server/server.js",
    "lint": "eslint .",
    "lint:fix": "eslint . --fix"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/TheInfamousGrim/Fakebook.git"
  },
  "author": "George Fincher",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/TheInfamousGrim/Fakebook/issues"
  },
  "homepage": "https://github.com/TheInfamousGrim/Fakebook#readme",
  "devDependencies": {
    "eslint": "^8.2.0",
    "eslint-config-airbnb": "^18.0.4",
    "eslint-plugin-import": "^2.25.3",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-react": "^7.28.0",
    "eslint-plugin-react-hooks": "^4.3.0"
  }
}`

here's a picture of my client server architecture

<img width="157" alt="architecture-fakebook" src="https://user-images.githubusercontent.com/89855075/206398964-652d9fa0-3ac1-4d43-9135-5118b9d875d6.png">

**Comment by ljharb** [comment]
You may need to update your deps. Can you make a repro repo, if that doesn't solve it?

**Comment by TheInfamousGrim** [comment]
I updated the deps and that fixed it. Sorry that it was so mundane.
