### ISSUE TITLE
How can I contribute to this great open-source ?

### ISSUE THREAD

**Issue by ProPhycient5** [airbnb/javascript#2691]
Hi everyone ✋🏾, I found this project quite interesting, so I yearn to contribute. As a newbie, how can I start contributing to this great project ?

I mean, what are the steps I need to follow or go through fundamentally so that I am in a position to contribute fruitfully ??

**Comment by ljharb** [comment]
There's not much that needs contribution here, but you could look for issues with the "help wanted" label.
