### ISSUE TITLE
Documentation for 'no-use-before-define' is missing

### ISSUE THREAD

**Issue by cseas** [airbnb/javascript#2708]
The rule is set to error in the config:
https://github.com/airbnb/javascript/blob/1eadb93e377da1e56c3f91f26610e5d0a00738a9/packages/eslint-config-airbnb-base/rules/variables.js#L54

But there's no mention of it in the guide:
https://github.com/airbnb/javascript/blob/master/README.md

This rule should be mentioned under the Variables section.

**Comment by ljharb** [comment]
I’d probably expect it in https://github.com/airbnb/javascript#hoisting.

**Comment by MohitBansal321** [comment]
@ljharb let me know where you should want to put in

**Comment by ljharb** [comment]
@MohitBansal321 I think we actually need a new 14.5 talking about why relying on hoisting should be avoided.

**Comment by MohitBansal321** [comment]
> no-use-before-define

so this rule is only applicable to the new 14.5?

**Comment by ljharb** [comment]
Yes, because the guide doesn't actually discuss not relying on hoisting, but the config has been enforcing that for a very long time.

**Comment by Vivek-04022001** [comment]
Could you please let me know if this issue is still open for contributions? If so, I would be very interested in working on it. Thank you!
