### ISSUE TITLE
Sentence "Enforce spacing inside of computed property brackets" is confusing

### ISSUE THREAD

**Issue by manjuu-eater** [airbnb/javascript#2711]
>   - [19.16](#whitespace--computed-property-spacing) Enforce spacing inside of computed property brackets. eslint: [`computed-property-spacing`](https://eslint.org/docs/rules/computed-property-spacing)

When I read this sentence, I thought like this:
```javascript
// bad: freedom spacing (hard to read)
obj[foo ]
obj[ 'foo']
const x = {[ b ]: a}
obj[foo[ bar ]]

// good: forced to spacing inside brackets (easy to read)
obj[ foo ]
obj[ 'foo' ]
const x = { [ b ]: a }
obj[ foo[ bar ] ]
```

But, it was wrong. Correct answer is this:

>   - [19.16](#whitespace--computed-property-spacing) Enforce spacing inside of computed property brackets. eslint: [`computed-property-spacing`](https://eslint.org/docs/rules/computed-property-spacing)
> 
>     ```javascript
>     // bad
>     obj[foo ]
>     obj[ 'foo']
>     const x = {[ b ]: a}
>     obj[foo[ bar ]]
> 
>     // good
>     obj[foo]
>     obj['foo']
>     const x = { [b]: a }
>     obj[foo[bar]]
>     ```

I have some possible solutions:
1. Change the word "enforce" to "avoid".
2. Exclude explaining about spacing in "{}" from sample code.
(already talken in about `eslint: object-curly-spacing` and `eslint: block-spacing`)

or, 

1. Use ESLint official sentence "Enforce **consistent** spacing inside computed property brackets".

Similar Issues and PRs exist already and some have been merged:
- https://github.com/airbnb/javascript/pull/1946
- https://github.com/airbnb/javascript/issues/2127
  - https://github.com/airbnb/javascript/pull/2452

reference: https://www.merriam-webster.com/dictionary/enforce

**Comment by ljharb** [comment]
"enforce" is the correct English word, because it does not imply either "forced" or "prohibited", and because "no spaces" is also "spacing".

Similarly to #1946, we could tweak the wording here, but just like https://github.com/airbnb/javascript/pull/1946#pullrequestreview-171808707, this would be both an acceptable but valueless change. Feel free to submit a PR if you feel strongly about it.
