### ISSUE TITLE
Revisit standing on Iterators and Generators

### ISSUE THREAD

**Issue by rcampbel** [airbnb/javascript#2715]
So is there any intention to revisit the standing on [Iterators and Generators](https://github.com/airbnb/javascript#iterators-and-generators)?  I'm mostly instrested specifically in revisiting the advice given in [11.2 Don’t use generators for now.](https://github.com/airbnb/javascript#generators--nope)

Reason for asking

1. The reasons why are based off thoughts and usage that is more then 7+ years old now
1. Browsers and transpilers have come along way over the last 7+ years
1. With New APIs and Objects <br/>Examples where methods on the objects return an iterator and not an array:<br/>- [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map).[entries()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/entries)<br/>- [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set).[entries()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/entries)

**Comment by ljharb** [comment]
I think most of the advice still holds - generators are best avoided, and generators are transpiled the same as they were 7+ years ago.

I agree using _iterators_ is becoming more reasonable, especially with iterator helpers shipping soon, so that section may be revisited in the medium term.

**Comment by NagayamaToshiaki** [comment]
@ljharb But hey, why should we transpile generators now? Other than you might use outdated systems, you don't need to.

**Comment by ljharb** [comment]
What systems you use isn't really relevant; what systems you serve to is what you should be maximizing.

Either way, generators are just subpar syntax sugar for creating iterators; there's not much value to be had by using them anyways.
