### ISSUE TITLE
Consider adding `import/no-empty-named-blocks`

### ISSUE THREAD

**Issue by thernstig** [airbnb/javascript#2716]
Reference: https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-empty-named-blocks.md

`import/no-empty-named-blocks` was added here: https://github.com/import-js/eslint-plugin-import/blob/main/CHANGELOG.md#2270---2023-01-11

Would it be good addition to the default rules for `airbnb-base`?

**Comment by chetanguptaa** [comment]
yes, I don't think so...

**Comment by meddy672** [comment]
The rule is added its just set to `off`. [Rules for airbnb-base](https://github.com/airbnb/javascript/blob/5c01a1094986c4dd50a6ee4d9f7617abdfabb58a/packages/eslint-config-airbnb-base/rules/imports.js#L281).

**Comment by ljharb** [comment]
The TODO comment indicates that it will be enabled in a future semver-minor.

**Comment by thernstig** [comment]
@ljharb should this issue be closed now then? Since you added this last month:

```js
    // Reports the use of empty named import blocks.
    // https://github.com/import-js/eslint-plugin-import/blob/d5fc8b670dc8e6903dbb7b0894452f60c03089f5/docs/rules/no-empty-named-blocks.md
    // TODO, semver-minor: enable
    'import/no-empty-named-blocks': 'off',
```

**Comment by ljharb** [comment]
Sure.
