### ISSUE TITLE
error in Strings 6.3

### ISSUE THREAD

**Issue by seoulbit** [airbnb/javascript#2746]
edit

**Comment by seoulbit** [comment]
mistake

**Comment by joneardley1** [comment]
I don't understand what this is

**Comment by joneardley1** [comment]
This XML file does not appear to have any style information associated with it. The document tree is shown below.

<Error>

<Code>AllAccessDisabled</Code>

<Message>All access to this object has been disabled</Message>

<RequestId>ED9EKNMYZBCA3HK4</RequestId>

<HostId>Z/91CKjvEi9zkzISNkX9ks0TZ0O9nsFNPfFSmh7H43HZ2JaLc1hYG6gG1SLaa9D45lR4X96h9+8=</HostId>

</Error>

**Comment by joneardley1** [comment]
What is this
