### ISSUE TITLE
Get rid of JSCS' requirePaddingNewLinesAfterBlocks?

### ISSUE THREAD

**Issue by tomekwi** [airbnb/javascript#275]
It seems broken at the moment: https://github.com/jscs-dev/node-jscs/issues/1232

**Comment by markelog** [comment]
Will be fixed in the next version

**Comment by markelog** [comment]
Also, i wonder what you wanted to do in this repo, in order to fix that ticket

**Comment by tomekwi** [comment]
Just get rid of the rule until it's fixed

**Comment by hzoo** [comment]
jscs-dev/node-jscs#1232 should be fixed now.

**Comment by tomekwi** [comment]
:+1:

Dumb of me anyway. I didn’t realize that it’s *jscs* who manage the config. Sorry for the fuss.

**Comment by hzoo** [comment]
Yeah although I think it would be interesting to allow others to manage presets at some point in the future.
