### ISSUE TITLE
Obj.fn is undefined

### ISSUE THREAD

**Issue by KevinShowli** [airbnb/javascript#2763]
`
let obj = {
    fn: () => {
        return 'fn'
    }
}`

`setTimeout(() => {
    console.log(JSON.stringify(obj.fn)) 
}, 1000) // undefined`
`
console.log(JSON.stringify(obj.fn)) // undefined
`
Hi guys, I code a obj like this and I want to use obj.fn() immediately，but It's undefined (It will change  next time, I try to use settimeout, but It's still not work). I think it's maybe cause of function declaration. So how can I fix this. I want to use obj.fn() immediately. Thanks very much.

**Comment by KevinShowli** [comment]
My situation maybe little complex. I use webWorker in js, So, I need to deep copy this obj. Like below： ` const { arr, userPidsMap } = await workerFn(JSON.parse(JSON.stringify(treeRoot)), JSON.parse(JSON.stringify(currentTabData.data)))` Call currentTabData.data.fn() in webWorker.

**Comment by ljharb** [comment]
This isn’t a general purpose help venue, it’s for Airbnb’s JavaScript styleguide.

Either way, workers are separate threads, and mutations on one side won’t be visible on the other.
