### ISSUE TITLE
Configuration for rule "dot-notation" is invalid

### ISSUE THREAD

**Issue by rexkenley** [airbnb/javascript#2766]
I am encountering a lint issue which gave me this error message
![image](https://user-images.githubusercontent.com/10548251/235003287-8255fec6-f698-46b3-971b-3bcf1a4aaa17.png)

The best-practices.js has this 
![image](https://user-images.githubusercontent.com/10548251/235003385-2c84e926-952c-4ac5-820e-48f32bc00baf.png)

How do I address this? Thanks!

**Comment by ljharb** [comment]
What version of eslint do you have? If you run `npm ls`, and it exits nonzero, your dep graph is invalid and you can't expect anything to work.

**Comment by rexkenley** [comment]
We are using a monorepo and this is the main package eslint. 
![image](https://user-images.githubusercontent.com/10548251/235175318-b8cd1dd4-2ba7-4928-b6a8-2f74c31c59d2.png)

This is the local eslint config that is having the issue
![image](https://user-images.githubusercontent.com/10548251/235175637-091dcfb3-1769-46d9-a02b-9c829f5488bf.png)

local package eslint
![image](https://user-images.githubusercontent.com/10548251/235177089-edf402c2-d270-40c9-acc2-e83c49e9b29f.png)

**Comment by ljharb** [comment]
and where are you running the eslint command?

**Comment by ljharb** [comment]
Closing pending a response.

**Comment by rexkenley** [comment]
> and where are you running the eslint command?

From the local project level.

**Comment by ljharb** [comment]
@rexkenley if you run it in the repo root, does it work? Does the local project's eslint config have `root: true`?

Typically eslint is only installed at, and run from, a place configured as root: true, which is usually the repo root.

**Comment by rexkenley** [comment]
We are using a monorepo called Nrwl Nx. It has a "root" eslint, but we can customized it on a project basis. So folder1 can have a different of eslint rules compared to folder2.

https://nx.dev/

**Comment by ljharb** [comment]
Sure, you can do that with regular eslint, using overrides - but the eslint _versions_ i wouldn't expect to vary based on the project - altho if they did, then each project's eslint config would *have* to be root:true or you'd run into issues.

**Comment by rexkenley** [comment]
Looks like my dev didn't create the project properly. Please stand by.

**Comment by rexkenley** [comment]
The issue is there are a proper project setup. 

I was able to find this 
https://github.com/eslint/eslint/issues/15988

**Comment by rexkenley** [comment]
@ljharb , what I should I do to resolve the issue?

**Comment by ljharb** [comment]
@rexkenley tbh i think it's an issue with `eslint-config-airbnb-typescript`, which to be clear is not endorsed or maintained by Airbnb or this styleguide.

**Comment by rexkenley** [comment]
Ok, I will take it to them. Thanks!

**Comment by rexkenley** [comment]
@ljharb , I opened a ticket with eslint-config-airbnb-typescript but it looks like it is no longer actively maintained. 

Why would the error message point to eslint-config-airbnb?

**Comment by ljharb** [comment]
I assume because that package mutates this config, and then eslint finds this config first.

**Comment by rexkenley** [comment]
Looks like I found the culprit.

![image](https://github.com/airbnb/javascript/assets/10548251/755485a8-dbeb-46bf-bca4-9c81ee3f80f8)

**Comment by rexkenley** [comment]
@ljharb FYI

https://github.com/iamturns/eslint-config-airbnb-typescript/issues/320#issuecomment-1553043985
