### ISSUE TITLE
What is the point of the comments

### ISSUE THREAD

**Issue by KingsGlaive76** [airbnb/javascript#2786]
Greetings,

The second section of the guide is "References", which is a prescription to use "const" over "var". This section showcases a "bad" code example and a "good" code example. So far, so good.

The first section of the guide is "Types", which, as far as I can tell, doesn't offer any prescriptions at all. It is simply educating the reader on the how variables work in the JavaScript programming language. Furthermore, the section does not show any "bad" code examples or "good" code examples.

Is there a particular reason that this section is included in the style guide? It seems notably out of place - every other section seems to impart a specific coding prescription. There is a time and a place to teach JavaScript newbies the basics on how the language works, and it doesn't seem like it should be in a style guide.

**Comment by ljharb** [comment]
Over time the guide has evolved to be more prescriptive, but its origins were more descriptive. It’s perfectly fine for a style guide to have education in it, though.
