### ISSUE TITLE
naming conventions rules are not active by default!?

### ISSUE THREAD

**Issue by mok-liee** [airbnb/javascript#2795]
hi,

my .eslintrc is as follows:

```json
...
  "extends": [
    "airbnb",
    "airbnb/hooks",
    "eslint:recommended",
    "plugin:react/recommended",
    "plugin:react/jsx-runtime",
    "plugin:import/recommended",
    "plugin:cypress/recommended",
    "eslint-config-prettier"
  ],
  "plugins": ["react"],
...
```

i was wondering why the mentioned naming conventions (https://github.com/airbnb/javascript#naming-conventions) are not "active" by default.
i have to set the rules by hand in the rules section.

is that normal or a miss-implementation by me?

**Comment by ljharb** [comment]
Which ones are you finding inactive by default?

**Comment by mok-liee** [comment]
`id-length`, `camelcase`, `new-cap` are one of them. without setting these keys to warning or error in my .eslintrc rules section, i am getting no hints about these if i write, lets say:
```js
function g() {}
```

**Comment by ljharb** [comment]
`id-length` is a very opinionated one, and in practice can be annoying to enable.

`camelcase` is enabled: https://github.com/airbnb/javascript/blob/fd77bbebb77362ddecfef7aba3bf6abf7bdd81f2/packages/eslint-config-airbnb-base/rules/style.js#L24

`new-cap` is enabled: https://github.com/airbnb/javascript/blob/fd77bbebb77362ddecfef7aba3bf6abf7bdd81f2/packages/eslint-config-airbnb-base/rules/style.js#L254-L259 

Are you sure you're using the latest version of everything?

**Comment by mok-liee** [comment]
mhhh i think so, i `npm install`ed it today. thanks for the reference, i will check tomorrow, maybe the following extends are overwriting this rules 🤷

**Comment by ljharb** [comment]
I would certainly avoid eslint:recommended, as well as the react and import plugin's recommended configs - all that stuff is contained in the airbnb config.

**Comment by mok-liee** [comment]
wow nice, thank you for this tip. the internet is full of different guides and it is really hard to figure out what really happens in the background.

is there a way to get the actual active ruleset of eslint based on the actual configuration?

**Comment by ljharb** [comment]
Yes, eslint has a `--print-config` option.

**Comment by ljharb** [comment]
This seems answered; closing.

**Comment by 123zzw** [comment]
@ItsEnosgit
