### ISSUE TITLE
Parenthesis around single arguments in arrow functions

### ISSUE THREAD

**Issue by thejameskyle** [airbnb/javascript#281]
> Always use parentheses around the arguments. Omitting the parentheses makes the functions less readable and only works for single arguments.

> Why? These declarations read better with parentheses. They are also required when you have multiple parameters so this enforces consistency.
>
>  ```js
>  // bad
>  [1, 2, 3].map(x => x * x);
> 
>  // good
>  [1, 2, 3].map((x) => x * x);
> ```

This stuck out to me as odd. It's an intentional part of the spec to make it more readable for simple cases.

Anyways, I'm interested in discussing this.

**Comment by goatslacker** [comment]
The "read better" part is a bit subjective the more important point is that they're required for multiple params so if we're later adding more params then we'll also need to remember to add the parenthesis. This rule is more about enforcing consistency.

**Comment by thejameskyle** [comment]
Sure, the consistency is good. But I think the rule could likely be improved upon.

In my experience writing ES6 over the last year or so, 90% of the time when you are writing an arrow function expression it's with only a single param. 

If it got to be more than that it should likely be expanded to a block arrow function in which case it should always use parentheses.

ie. 
```js
// good
[1, 2, 3].map(n => n * 2);

// bad
[1, 2, 3].map(n => {
  return n * 2;
});

// good
var fn = (a, b, c) => {
  return a + b + c;
};

// bad
var fn = (a, b, c) => a + b + c;
```

This is how I've seen most people write their code when they submit issues to Babel.

**Comment by nkbt** [comment]
I go for readability over consistency in this case. Moreover it is way more often to have only one argument. At least as for my experience. Parenthesis is excessive for 95% of all my cases. To be honest I do lots of D3 and have the only argument for all function almost all the time.

Currying without parenthesis [looks awesome too](https://twitter.com/dan_abramov/status/583603566193090560)

![currying](https://pbs.twimg.com/media/CBlgWa1UIAAKHyv.png)

**Comment by goatslacker** [comment]
@hshoff any opinions here?

**Comment by hshoff** [comment]
Reminds me of the rule for using braces around multi-line blocks ([#Blocks](https://github.com/airbnb/javascript#blocks)).

I would be favor of updating the rule to match @thejameskyle's suggestion.
