### ISSUE TITLE
Anonymous react components are allowed in eslint config but not a good practice

### ISSUE THREAD

**Issue by christophehurpeau** [airbnb/javascript#2829]
Anonymous react components are allowed as `function-expression` according to the eslint config:
https://github.com/airbnb/javascript/blob/11ab37144b7f846f04f64a29b5beb6e00d74e84b/packages/eslint-config-airbnb/rules/react.js#L529

However it is not a good practice as discussed in https://github.com/airbnb/javascript/issues/2505 and as stated in
https://twitter.com/dan_abramov/status/1093901838179618816

Would a better configuration be `unnamedComponents: []` to avoid them completly ?

**Comment by ljharb** [comment]
This allows function *expressions*, which another rule prohibits from being anonymous. Expression components are perfectly fine.

**Comment by christophehurpeau** [comment]
> which another rule prohibits from being anonymous

it seems to be `func-names` which was turned off in my config. However it's a warning unfortunarly in airbnb's config: https://github.com/airbnb/javascript/blob/11ab37144b7f846f04f64a29b5beb6e00d74e84b/packages/eslint-config-airbnb-base/rules/style.js#L96
