### ISSUE TITLE
Advise against default parameter with side-effect

### ISSUE THREAD

**Issue by HerringtonDarkholme** [airbnb/javascript#285]
According to the ES6 spec, default arguments is evaluated `in the scope of the fresh activation (localEnv in ES5 10.4.3) for the current function`. This means every default argument behaves like a function that returns a value for the parameter and, thusly, can make side effect.

If side effect is done in default parameter, confusion and subtlety likely arise.  For a contrived example,

```
> var b = 1
> function count(a=b++) {
...  console.log(a)
... }
> count()
1
> count()
2
> count('hello world')
hello world
> count()
3
```

Arguments in JavaScript are evaluated eagerly, in applicative order, but  default parameter are (somewhat) evaluated by need, in normal order. It is quite possible for a ES6 newcomer, or even an experienced developer, accidentally forgets the evaluation strategy for default parameter. 

If a side effect does be desired, then a normal assignment statement is more explicit than default parameter. With more strokes to input, it also discourage side effect.

```
function count(a) {
   if (a === undefined) a = b++
}
```

After all, default parameter with side effect can be translated equivalently to ES5 `if ...` block. After all, it's just a matter of taste. So I think it is appropriate to place this in a style guide.

**Comment by nkbt** [comment]
Nice one. I could not imagine someone puts a side-effecty expression into a default parameter. But as soon as it is technically possible - one would. So strongly advise against it.

_Unless one participates in 1k.js challenge or something._

**Comment by goatslacker** [comment]
:+1: great observation for a rule, feel free to draft it as a PR against the es6 branch and we'll merge it in.

**Comment by ljharb** [comment]
Closing this for now - if an eslint rule exists somewhere that can help lint against this, we'll happily use it.
