### ISSUE TITLE
Style guide question: how to handle names with consecutive initialisms?

### ISSUE THREAD

**Issue by benmarch** [airbnb/javascript#2859]
I wasn't sure where to ask this (and feel free to close it) but I've been using this style guide for almost a decade and just ran into something I can't seem to reconcile: 

I created a function that builds a URL for an API endpoint from some parameters, and I can't find a good way to name it due to rule [23.9: Acronyms and initialisms should always be all uppercased, or all lowercased.](https://github.com/airbnb/javascript#naming--Acronyms-and-Initialisms)

Ideally, it would be `getAPIURL()` but that's ugly and hard to read because of the consecutive initialisms. Even worse, this API URL is for a micro-frontend, so it could be `getMFEAPIURL()` 😅 

Anyway, I could obviously make an exception in this case and use `getApiUrl()`, but I'm wondering if the community has an advice that might end up back in the style guide. Thanks!

**Comment by ljharb** [comment]
You're right that this one is tricky.

I personally find `Api` and `Url` to be highly objectionable, and would probably just use `getAPIURL()` and deal with it, or, something like `apiURL()` (omit the "get").

**Comment by benmarch** [comment]
Thanks @ljharb. I ended up going with something like `apiURL()` (there were two so they were `servicesURL()` and `mfeURL()`).
