### ISSUE TITLE
Invalid example in ES6 Modules section

### ISSUE THREAD

**Issue by sebmck** [airbnb/javascript#287]
The [Modules](https://github.com/airbnb/javascript/tree/es6#modules) section uses the "bad" example of:

```javascript
export default { es6 } from './airbnbStyleGuide';
```

this is however not valid syntax. What I think you mean is:

```javascript
export { es6 as default } from './airbnbStyleGuide';
```

**Comment by hshoff** [comment]
:+1:

**Comment by goatslacker** [comment]
:beers:
