### ISSUE TITLE
Support Biome extends

### ISSUE THREAD

**Issue by ianzone** [airbnb/javascript#2893]
Ref: https://biomejs.dev/reference/configuration/#extends

**Comment by ljharb** [comment]
I’m not sure what such support would even mean. The packages contained in this repo are for eslint, not biome, and if you’re following this guide, you’d be using eslint, not biome.

**Comment by ianzone** [comment]
Hi, I understand this repo is for eslint, I'm asking if the same rules or similar can be made to work with biome, since biome is a promising linter and formatter.

**Comment by ljharb** [comment]
I have no idea, since i don’t use biome. In theory you could construct a biome config that represents this guide as closely as possible, but unless Airbnb uses biome and informs me of that, it wouldn’t be something that’s done in this project.
