### ISSUE TITLE
Multiline comments

### ISSUE THREAD

**Issue by thomasttvo** [airbnb/javascript#2908]
The [multiline comment](https://github.com/airbnb/javascript#comments--multiline) section says all multiline comments need to use the jsdoc syntax `/** */`. Is this right? Does the author mean "All jsdoc comments" instead of "multiline"?  

Otherwise, it doesn't really make sense if we use jsdoc where we're not documenting a variable, class, or function

```js
/** 
 * This function does XYZ
 */ 
function xyz() {
  /**
   * This chunk of code does this because we don't like to do it the other way.
   * Otherwise, zombie apocalypse.
   */ 
 const a = b + 1;
 doSomething(a);

 /**
  * Here we're just having fun if nothing happens
  * Busines continues as usual
  */
 doSomething(b)
}
```

**Comment by ljharb** [comment]
It refers to all multiline comments, and the guide assumes you are not using jsdoc at all.

**Comment by ljharb** [comment]
No, I’d say both are fine.
