### ISSUE TITLE
Regarding Updation

### ISSUE THREAD

**Issue by abhiedward001** [airbnb/javascript#2935]
Is there any plan to update airbnb eslint rules to latest react and other javascript frameworks? Also saw some new eslint config changes.  Or is there any other eslint config which you prefer ?

**Comment by ljharb** [comment]
Regarding the first question, I’m not sure what needs updating. Regarding the second, as soon as the plugins we use all support flat config, so will we; bit we’ll keep supporting eslintrc until we no longer support an eslint that does.

**Comment by abhiedward001** [comment]
Regarding first question I mean to say that for example in redux we are directly mutating the state value in reducer function but that is okay as behind the scene Redux Toolkit's createSlice and createReducer APIs use Immer inside to allow us to write "mutating" update logic that becomes correct immutable updates. But airbnb eslint rule throwing me error saying this is wrong.

**Comment by ljharb** [comment]
Yes, using immer (directly or otherwise) is a bit of a conflict with this guide, because it encourages code that looks like mutation. My understanding is that redux hasn't been "in vogue" for many years, so I'm not sure there's much value in accommodating it now.
