### ISSUE TITLE
Link 404 not found

### ISSUE THREAD

**Issue by mthirumalai2905** [airbnb/javascript#2951]
THe provided npmjs link doesnt work https://github.com/airbnb/javascript?tab=readme-ov-file#objects--prototype-builtins part 3Object  3.7

**Comment by ljharb** [comment]
Seems like it works just fine, can you be more specific?

**Comment by mthirumalai2905** [comment]
@ljharb sorry my bad man it works now back then it was showing 404 hence i did raise a issue
