### ISSUE TITLE
Can we add on quiz sections on this repo too

### ISSUE THREAD

**Issue by mthirumalai2905** [airbnb/javascript#2957]
It will much usefull for beginners like me where i can find the topics as well as questions where i can practice them

**Comment by ljharb** [comment]
I think that would be a lot of work to maintain, and I'm not sure how valuable it would be - the best way to learn a programming language is to build something with it :-)

Thanks for the suggestion though!

**Comment by mthirumalai2905** [comment]
@ljharb  would that be okay if i make couple of good quality quizes as readme.md which is well maintained merge them if you appreciate orelse you can close that sir 

am really looking forward to collaborate on this. this way i can improve my core js skills which will help me skyrocket my development journey

**Comment by ljharb** [comment]
I'm not convinced of the value - feel free to drop a gist link here tho and i can take a look.

**Comment by mthirumalai2905** [comment]
Sir @ljharb what's a gist?

**Comment by mthirumalai2905** [comment]
Yes sure sir, I will raise a PR please review that later 😊

**Comment by mthirumalai2905** [comment]
Yes sure thanks sir, @ljharb

**Comment by mthirumalai2905** [comment]
@ljharb can u please check this or assign this to me i will make 100 questions for now i have just added basics but will increase the dificulty as i add more question Added Quiz #2958 please review the PR

**Comment by ljharb** [comment]
Note that i said a gist, not a PR.

**Comment by mthirumalai2905** [comment]
am sorry @ljharb so what should i do now gists means a local git repo from my personal github acc correct ?

**Comment by mthirumalai2905** [comment]
Good Morning Sir, @ljharb 
Can we please do this have u checked it if you had any free time 😊

**Comment by ljharb** [comment]
I'll take a look when I can.

**Comment by mthirumalai2905** [comment]
@ljharb  definetly

**Comment by ljharb** [comment]
https://github.com/airbnb/javascript/pull/2959#issuecomment-2032711270
