### ISSUE TITLE
Suggestion to add switch

### ISSUE THREAD

**Issue by ButuzGOL** [airbnb/javascript#296]
Does it make sense to add switch
Because it's not clear add spaces before case or not

```
switch (expression) {
  case expression:
    statements
    break;
  default:
    statements
}
```

Or

```
switch (expression) {
case expression:
  statements
  break;
default:
  statements
}
```

**Comment by nkbt** [comment]
Because you have indentation of 2 spaces and you do indentation after each `{` + new line, it becomes quite clear you should do.

```javascript
switch (expression) {
  case expression:
    statements
    break;
  default:
    statements
}
```
But yeah, could be mentioned because for some reasons autoformatters allow you not to indent `case` in `switch`, which is really weird case.

**Comment by kevinrenskers** [comment]
You might want to change your [eslint config](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/.eslintrc) now that 1.0.0 has been released:

`"indent": [2, 2, {"SwitchCase": 1}],`

**Comment by turadg** [comment]
+1  we use `extends: "airbnb"` and would like `"indent": [2, 2, {"SwitchCase": 1}]` to be in `eslint-config-airbnb`.

**Comment by gcoupelant** [comment]
+1

**Comment by ljharb** [comment]
fwiw I agree that if it's here, the first example (https://github.com/airbnb/javascript/issues/296#issuecomment-91070293) should be the one enforced by the config - however, I'd prefer to ban switch altogether :-) although that should be a different discussion.

**Comment by zakpatterson** [comment]
Some libraries make use of message passing, such as Redux, and the switch statement is very clean for handling message types to return state mutations.

See here:
https://github.com/rackt/redux#the-gist

So I would like to suggest that in addition to the indenting, we also allow for variable name reuse within those case statements.  This pattern is now very common:

```
case A: 
    const {propA, ...rest} = action
    return {propA + 1, ...rest};
case B:
    const {propB, ...rest} = action
    return {propB + 1, ...rest};
...
```
and that reuse of the rest name causes an error.

**Comment by postmeback** [comment]
If the PR serves the purpose, then shall we close it ?
