### ISSUE TITLE
"Prefix jQuery object variables with a $." Does this play well with AngularJS?

### ISSUE THREAD

**Issue by ddcahutton** [airbnb/javascript#297]
I am glad to see the dollar sign prefix endorsed. This practice, which I think this is often referred to as Hungarian notation, has helped me easily identify jQuery-wrapped objects.

I believe that AngularJS employs a different meaning for a $ prefix, e.g., `$scope.$value`; `$ignore`; `$watch`.

Aside from code readability—because, unless you have `var $scope = $('.scope')`, it should be _mostly_ clear from context that `$scope` is not a jQuery-wrapped object—has prefixing jQuery object variables with a `$` been known to cause any issues on a page that employs both jQuery and AngularJS?

**Comment by hshoff** [comment]
Hi @ddcahutton, thanks for checking out the guide.

We don't use Angular at Airbnb so we've never come across this issue, but I could see how that could be confusing.

If your team is using Angular, I would recommend when you fork the guide for the team to update the rule by changing the prefix from `$` to `$$` or `jQ` or some other consistent notation.
