### ISSUE TITLE
import/no-extraneous-dependencies shouldn't be a code style rule

### ISSUE THREAD

**Issue by angeloreale** [airbnb/javascript#2971]
BLUF
import/no-extraneous-dependencies shouldn't be a code style rule as It directly affects bundle sizes for ES Modules

- devDeps are not included in final bundle

**Comment by ljharb** [comment]
This style guide goes way beyond just style rules.

If eslint is warning on a dep in a non production file, it’s on you to configure it so it knows where dev deps are allowed.

**Comment by angeloreale** [comment]
So, is it a meta-style guide?

**Comment by angeloreale** [comment]
Are Airbnb ESLint rules meant for every library but every library that uses devDeps or peerDeps?

**Comment by ljharb** [comment]
Every library or application, full stop

**Comment by angeloreale** [comment]
Then my issue is valid, I'd suggest we re-open it.

**Comment by ljharb** [comment]
It’s not valid. Every project must use the dep categories appropriately. What file are you getting a warning in?

**Comment by angeloreale** [comment]
Vite config and Vitest setup

**Comment by angeloreale** [comment]
It's a component library, so I don't need any dependencies at all. Only devDeps and peerDeps.

**Comment by angeloreale** [comment]
Then along with a bunch of libraries do I also need to forget what treeshaking ever meant?

**Comment by ljharb** [comment]
Treeshaking is a) done at the application level in the bundler, b) unaffected by putting things in runtime vs dev deps afaik, and c) a really crappy tool to remove dead code that can’t ever achieve as much reduction as “never use battle files and only deep import what you need in the first place”.

**Comment by angeloreale** [comment]
A rollup on a rollup bundle can treeshake packages.

**Comment by ljharb** [comment]
Can but needn’t, because the end users bundler will do it anyways. And if you’re architecting the library, you should never use barrel files anyways and then the user doesn’t NEED to treeshake.

**Comment by angeloreale** [comment]
Do we need to increase the end user bundle time as points for style?

never and anyways are words I seldom use.

**Comment by ljharb** [comment]
Their bundle time is irrelevant.

**Comment by angeloreale** [comment]
Add a couple of dependencies tree on top and we're set for scale.

I think the creator of https://github.com/zloirock/core-js is still looking for a job because he didn't lint his code with Airbnb.

**Comment by ljharb** [comment]
The dep categories must match conceptually - otherwise, for example, vulnerabilities in deps won’t be surfaced to consumers.

**Comment by angeloreale** [comment]
Afaik https://github.com/snyk still allows you to enable devDeps scans.

**Comment by ljharb** [comment]
Not dev deps of dependencies. Who cares if you can check vulns on the library if the end user, whose bundle time you’re concerned with, can’t check their dependency graph properly?

**Comment by angeloreale** [comment]
Yeah, I should have used Airbnb style on Houston Spaceport, who cares a Raspberry PI will need an extra while to calculate a rocket launch microsystem/UI?

I'm not a prick, for prick's sake.

I believe we, and Airbnb, can keep this to a better standard.

**Comment by angeloreale** [comment]
How fast can we bundle a patch update during an incident?

**Comment by ljharb** [comment]
k this seems like it’s getting unnecessarily hostile.

This isn’t going to change; packages shouldn’t bundle and anything used at runtime should be listed in runtime deps. If you don’t like the rule, you’re free to disable it.
