### ISSUE TITLE
Create a rule to prohibit the use of the `test` function in regular expressions

### ISSUE THREAD

**Issue by PredokMiF** [airbnb/javascript#3009]
If RegExp with `g` flag using several times - this can lead to unexpected consequences.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test
I propose adding a rule prohibiting calling the `test` function in regular expressions

**Comment by ljharb** [comment]
That doesn’t seem viable, but either way such a rule would gave to exist before an issue here makes sense.
