### ISSUE TITLE
Does the "eslint-config-airbnb" contains the style set in "Airbnb CSS-in-JavaScript Style Guide"?

### ISSUE THREAD

**Issue by thinkerelwin** [airbnb/javascript#3022]
I really like the rules related to css-in-js set by Airbnb and I want to incorporate these rules into my project, but I can't find the relative plugin in the readme section here:

https://github.com/airbnb/javascript/tree/master/css-in-javascript#themes

if this style guide hasn't been implemented by "eslint-config-airbnb", is there any ESlint plugin doing it?

Thanks!

**Comment by ljharb** [comment]
I’m not sure how those things would be generally lintable, so no, it’s unlikely that any eslint plugin is doing it.

If you can figure out how to apply those restrictions with linting rules, a PR to add a new config entrypoint for it might be useful!
