### ISSUE TITLE
eslint-config-airbnb breaks with TIMING=1 env

### ISSUE THREAD

**Issue by steelbrain** [airbnb/javascript#3045]
In [`/whitespace.js`](https://github.com/airbnb/javascript/blob/e6080c7beed96700a599e7d86f1517bdc8269366/packages/eslint-config-airbnb/whitespace.js#L54) a subprocess is launched to print out the rules in JSON and the JSON response is parsed.

If ESLint is being run with `TIMING=1`, it prints how much time each rule takes, and because the linked child process invocation is forwarding the env as-is, it's json parsing will fail and the process breaks down.

Here's the patch I'm using internally. Happy to upstream if it looks good to y'all

```diff
diff --git a/whitespace.js b/whitespace.js
index dfdf95a18e69f4bba35fe53bb59bad5de3bccbf6..052a4fc2f4d56da3eadbd2cc377131529788840d 100644
--- a/whitespace.js
+++ b/whitespace.js
@@ -51,5 +51,10 @@ if (CLIEngine) {
   const path = require('path');
   const { execSync } = require('child_process');
 
-  module.exports = JSON.parse(String(execSync(path.join(__dirname, 'whitespace-async.js'))));
+  module.exports = JSON.parse(String(execSync(path.join(__dirname, 'whitespace-async.js'), {
+    env: {
+      ...process.env,
+      TIMING: undefined,
+    }
+  })));
 }

```

**Comment by ljharb** [comment]
Seems good - a PR that fixes it in both packages would be great.

are there any other env vars eslint respects?

**Comment by steelbrain** [comment]
> are there any other env vars eslint respects?

Based on a [code search of the ESLint repository](https://github.com/search?q=repo%3Aeslint%2Feslint%20%22process.env.%22&type=code) `TIMING` seems to be the only relevant one.

> Seems good - a PR that fixes it in both packages would be great.

Great, thanks! I'll put up a PR and ping you

**Comment by steelbrain** [comment]
A PR is up in https://github.com/airbnb/javascript/pull/3047 -- Thanks!
