### ISSUE TITLE
Please reconsider some rules

### ISSUE THREAD

**Issue by Rudxain** [airbnb/javascript#3066]
https://erkinekici.com/articles/linting-trap

> [!note]
> I apologize in advance if this has already been mentioned.
> I couldn't find dupes

**Comment by ljharb** [comment]
no-use-before-define is critical - code that relies on hoisting is harder to read and understand. arrow-body-style reduces git diff churn. no-plusplus isn't that big a deal, but you shouldn't be using loops at all, so it shouldn't come up. if a class method doesn't use the receiver, it shouldn't be one. no-param-reassign prevents a performance cliff, and the manipulation part only comes into play if you're mutating, which you should never be. default exports should always be preferred and adds tons of value. for-of is a loop, and loops are bad.

iow, i disagree with the majority of this article and don't see any reason to reconsider anything mentioned in it.

**Comment by Rudxain** [comment]
Fair enough, I agree. Especially `no-param-reassign`, I use it in my projects while awaiting [this](https://github.com/Fishrock123/proposal-const-function-arguments)
