### ISSUE TITLE
Is there a place for if (obj == null) or if (obj != null)?

### ISSUE THREAD

**Issue by justin808** [airbnb/javascript#307]
In the es6 guide, there’s a link to this article: https://javascriptweblog.wordpress.com/2011/02/07/truth-equality-and-javascript/#more-2108 from Angus.

Given the below snippet from Angus, the guidance on == vs === is a bit confusing

https://github.com/airbnb/javascript/tree/es6#comparison-operators-equality
```
Use === and !== over == and !=.
```

From Angus:
```
Common Examples of Equality Overkill

//unnecessary
if (typeof myVar === "function");
 
//better
if (typeof myVar == "function");
..since typeOf returns a string, this operation will always compare two strings. Therefore == is 100% coercion-proof.


//unnecessary
var missing =  (myVar === undefined ||  myVar === null);
 
//better
var missing = (myVar == null);
…null and undefined are == to themselves and each other.
Note: because of the (very minor) risk that the undefined variable might get redefined, equating to null is slightly safer.

//unnecessary
if (myArray.length === 3) {//..}
 
//better
if (myArray.length == 3) {//..}
```

**Comment by goatslacker** [comment]
This is because `typeof` operator **always** returns a string and `.length` is **always** a number so the `==` comparison operator is safe to use since you'll be reasonably comparing values of the same type.

While his advice is good, I would just always use `===` for consistency.
