### ISSUE TITLE
Is `var` discouragement appropriate?

### ISSUE THREAD

**Issue by alexreardon** [airbnb/javascript#309]
https://github.com/airbnb/javascript/tree/es6#references

It seems like a loss of a powerful language feature to not use function scoped variables `var`. JavaScript function scoping, and potential resulting closures once understood can be an extremely powerful language feature. Is discouraging the use of `var` in this case going against a core feature of the language?

**Comment by goatslacker** [comment]
I don't think so. Function scoping doesn't give you much benefits and hoisting is an often misunderstood feature of JS.

People already treat var like it's let. It is one of the reasons why the rule "always declare vars at the top" exists. Doing away with that rule is a good thing. 

By using const over var we also gain references that can't be reassigned. This makes your code easy to reason about in most cases. 

Closures work great with const.

I can't think of a case off the top of my head where you'd want to use var over let.

**Comment by alexreardon** [comment]
Obviously showing my ignorance in relation to `es6`. Just to clarify for future readers `let` has no functional difference regarding functional scope and closures to that of `var`. `let` variables are merely defined at a block level and not subject to hoisting.

As a side point though David Walsh had an interesting article on the topic here: http://davidwalsh.name/for-and-against-let

> Use let in places you know you need block scoping, and you've specifically thought about those implications. But continue to use var for variables that either cannot easily be block scoped, or which shouldn't be block scoped. There are going to be places in real world code where some variables are going to be properly scoped to the entire function, and for those variables, var is a better signal.

He has a few situations where he thought it would make sense to use `var` over `let`. However, his argument is based on *signalling* the developer which might not be the most compelling reason. There are dangers with using `let` (`var` can be more forgiving) but I do not see that as overly persuasive.

**Comment by goatslacker** [comment]
Makes sense.

If you replace all your `var` with `const` though then any `let` references declared at the top of the function are meant to be used across the entire function. Your mileage may vary :)

You can see an example of what I'm talking about here: https://github.com/goatslacker/alt/blob/master/src/alt.js#L366

By using `let` at the top I'm signaling that

* This reference will mutate.
* It'll be used throughout the function.

**Comment by goatslacker** [comment]
If you do think this needs to be clarified in the style guide though then lets figure out where and how.
