### ISSUE TITLE
Arguments casting to array.

### ISSUE THREAD

**Issue by EvanCarroll** [airbnb/javascript#311]
The current advice, 

```text
To convert an array-like object to an array, use Array#slice.

function trigger() {
  var args = Array.prototype.slice.call(arguments);
  ...
}
```

Actually breaks v8's compiling optimizer, just fyi. Any function you do that to can not be optimized. [See the bluebird docs for more info.](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#3-managing-arguments)

Also, [see my question on StackOverflow](http://stackoverflow.com/q/23509312/124486).

**Comment by goatslacker** [comment]
In this particular case we're favoring readability > performance.

Directly assigning to an Array with a fixed length (like it mentions in the bluebird docs for "Workaround") is way faster anyway but that doesn't mean we should always favor that pattern.

**Comment by EvanCarroll** [comment]
Well, just so long as you're comfortable totally forgoing javascript optimizations *everywhere* that pattern is used. Afaik, no browser can or will ever optimize if you leak arguments.

**Comment by goatslacker** [comment]
Thankfully we've got [rest](https://github.com/airbnb/javascript/tree/es6#es6-rest) in es6 so we don't have to ever use `arguments` :)

**Comment by ljharb** [comment]
Since now we should be using the rest operator, I'm going to close this.
