### ISSUE TITLE
No additional trailing comma – still relevant for ES6?

### ISSUE THREAD

**Issue by tomekwi** [airbnb/javascript#323]
As you point out in the spec, the question of the last trailing comma has been cleared in ES5.

Using ES6 syntax implies full support for ES5. As well as that, today’s transpilers like *babel* remove the last comma anyway:

```
$ echo "let something = [1, 2, 3,]" | babel
"use strict";

var something = [1, 2, 3];
```

You’re surely familiar with arguments for an additional trailing comma at the end. Why not allow it since the ES6 edition?

**Comment by goatslacker** [comment]
Yes I'm +1 for allowing it for transpiled code.

**Comment by tomekwi** [comment]
How about code executed as modules (`<script type="module">` and `import stuff from 'module'`)? AFAIK there is no native implementation yet – but when it comes, JS executed in a module will follow different rules. In particular, strict mode and 100% support for ES6 are implied.

**Comment by tomekwi** [comment]
:+1:
