### ISSUE TITLE
Suggestion for if else comments

### ISSUE THREAD

**Issue by VictorChen** [airbnb/javascript#325]
Is there a perference for adding comments in the `else` block of an `if` statement ?

For example:

Case 1:

```js
// comment about the if block
if (condition) {
  // comment about doStuff()
  doStuff();
} else {  // comment about the else block, what if this is too long ?
  // comment about doOtherStuff();
  doOtherStuff();
}
```

Case 2:

```js
// comment about the if block
if (condition) {
  // comment about doStuff()
  doStuff();
} else { 
  // comment about the else block

  // comment about doOtherStuff();
  doOtherStuff();
}
```

Case 3:

```js
// comment about the if block
if (condition) {
  // comment about doStuff()
  doStuff();

  // comment about the else block
} else {
  // comment about doOtherStuff();
  doOtherStuff();
}
```

Not sure if any of these is preferred... is there another way?

**Comment by goatslacker** [comment]
Case 3 but no indent on the comment above else block.

Rule of thumb, the comment goes directly above the line you're intending to comment.

**Comment by kevingimbel** [comment]
Depending on the complexity, I'd say it's okay to use numbers to indicate comments. I've found it useful in CSS/Sass to document magic numbers, hacks or other stuff that may needs a bit of explanation. 

A comment block above the declaration/function/block as shown below is better than long sentences inside the functions or blocks body IMO.

```js
/*
 * [1] Here doStuff() is described.
 * [2] Explanation about the else statement and when it is expected to be executed,
 *     this comment could get really long, maybe the execution depends on previous
 *     functions or the developer likes to write detailed comments - who knows?
 * [3] Explanation of doOtherStuff() and what happens when it is called or what will be
 *     returned, if anything is returned here at all. This comment may also be long.
 */
if(condition) {
  // [1]
  doStuff();
  // [2]
} else {
  // [3]
  doOtherStuff();
}
```

**Comment by nkbt** [comment]
I'd say - if you need to comment `else` case, then something is going wrong. More, if you need to comment something inside your function, then something is going wrong. That is a clear indication to split it and do some refactoring.
For almost all cases properly written JSDoc is more then enough.

**Comment by VictorChen** [comment]
To be honest, I kind of prefer something like this (only when there are comments):

```js
// comment about the if block
if (condition) {
  doStuff();
}
// comment about the else if block
else if (condition2) {
  doOtherStuff();
}
// comment about the else block
else {
  done();
}
```

This way, each `if` block is contained within `{...}`, instead of something like:

```js
// comment about the if block
if (condition) {
  doStuff();

// comment about the else if block
} else if (condition2) {
  doOtherStuff();

// comment about the else block
} else {
  done();
}
```

It seems odd to me that the `}` shows up under the comment of the other `if`.

**Comment by EvanCarroll** [comment]
I agree with @VictorChen. That's a valid point.

**Comment by ljharb** [comment]
In that scenario, why is your condition so unclear at-a-glance that a comment is required?

**Comment by EvanCarroll** [comment]
That could be said about any code.... If it's not self-commenting.. why?

**Comment by ljharb** [comment]
This issue only arises when code isn't self-documenting enough.

At any rate, the `}` and ` else` should always be on the same line. Any commenting form that allows for that is fine. Between the 3 cases in the initial example, I'd go with case 2 when case 1's comment is too long.

**Comment by EvanCarroll** [comment]
It's all style: `}` and `else` being on the same line is a preference. As, is commenting above a block. You have to decide which one should hold high precedence over the other. My preferences are,

1. for code to be as commenting as possible (when in doubt): that's why I opened https://github.com/airbnb/javascript/issues/726 (where the airbnb style prevents that).
2. for comments to always be above the code they're describing if there is any confusion. Here the style is again prohibiting that.

That's not say *should* is applicable for me or you. I don't vertical value whitespace at all. The whole argument for a cuddeled else is precisely that. I also like things to be lined up, and cuddling prevents that. Now that every text editor has fast an efficient syntax highlighting, I think that's less of an issue.

**Comment by ljharb** [comment]
Airbnb's preferences is to never separate `}` from `else`. Please feel free to fork this project if you'd like to make modifications for your own codebase!

**Comment by acoulon99** [comment]
lol
