### ISSUE TITLE
[Question] Which one is prefered?

### ISSUE THREAD

**Issue by felixsanz** [airbnb/javascript#334]
I'm using generators just for the example, thats not related to the variable scoping.

```javascript
function* foo() {
  let response;
  try {
    response = yield request({});
  } // ...
}
```
```javascript
function* foo() {
  try {
    var response = yield request({});
  } // ...
}
```

**Comment by goatslacker** [comment]
let is preferred

**Comment by felixsanz** [comment]
but let is block scoped and we don't need block scoping in this situation. Why not use `var` ? Thats a real useful case for `var`

**Comment by goatslacker** [comment]
is there a reason you want response to be hoisted and implicitly undefined outside of the try catch?

**Comment by felixsanz** [comment]
to make use of it after the try/catch block

**Comment by goatslacker** [comment]
It's perfectly valid JavaScript but it's weird. If you want to make use of it after the block then explicitly define it as undefined. Most linters are configured by default to warn on code like this.

**Comment by felixsanz** [comment]
If i use `let` **outside** of try/catch, i can have this:

```javascript
function* foo() {
  let response;
  try {
    response = yield request({});
  } catch (err) {
    // Error on request({})
  }

  doSomething1(response);
  doSomething2(response);
}
```

**Inside**, this problem appears:

```javascript
function* foo() {
  try {
    let response = yield request({});
    doSomething1(response);
    doSomething2(response);
  } catch (err) {
    // Error on .... who knows?
  }
}
```

**Comment by goatslacker** [comment]
Yup, that's correct. Depends if you want [Pokemon Exception Handling](http://www.dodgycoder.net/2011/11/yoda-conditions-pokemon-exception.html) or not but I favor the outside version :)

**Comment by felixsanz** [comment]
so.. outside version using `let` and initializing it before try/block?

`var` is dead? This was a good use case for it.

Thanks for your time!

**Comment by goatslacker** [comment]
You're free to use `var` as you wish, before `let` our code would look like:

```js
  var response;
  try {
    response = request({});
  } catch (err) {
    // Error on request({})
  }

  doSomething1(response);
  doSomething2(response);
```

Now we're just using `let` instead of `var` because it has many benefits.
