### ISSUE TITLE
[Question] Wrapping conditionals

### ISSUE THREAD

**Issue by felixsanz** [airbnb/javascript#335]
Is there any prefered way of doing this kind of things?

```javascript
if ((a == b) && (c > d * 2))
```

```javascript
if (a == b && c > d * 2)
```

```javascript
if ((a == b) && (c > (d * 2)))
```

etc

**Comment by goatslacker** [comment]
No we don't have any set styles for this sort of thing, that I'm aware of at least. cc @hshoff?

I'd favor the 2nd one only because it's obvious (to me) what takes precedence.

**Comment by felixsanz** [comment]
plus... what about multiline? 

```javascript
if (a == b && c > d * 2 && e <= f)
```
VS
```javascript
if (a == b
&& c > d * 2
&& e <= f)
```

Would be nice to add a section about this with your best practices

**Comment by nkbt** [comment]
```javascript
if (a == b &&
  c > d * 2 &&
  e <= f)
```

But only if exceeds max line width

**Comment by nkbt** [comment]
If conditions look too complex to read or are too long, then we take them out of `if` into separate nicely named vars.

```javascript
const isSomething = c > d * 2;
const isAnotherThing= e <= f;
if (isSomething && isAnotherThing)
```

**Comment by ljharb** [comment]
I definitely would never want multiline, and definitely would prefer adding the extra parens for readability (only for comparison and boolean operations).

**Comment by felixsanz** [comment]
Forgot to close it. Thanks guys!
