### ISSUE TITLE
ToBoolean abstract operation not used in comparison operator

### ISSUE THREAD

**Issue by matt-e-king** [airbnb/javascript#336]
Hey there! Really appreciate the contribution, especially with the newest additions in regards to ES6.

I did want to point out that the https://github.com/airbnb/javascript#comparison-operators--equality section is a little misleading as the ToBoolean abstract operator is not used in either the ``==`` or ``===`` equality operator as you mentioned
> Comparison operators are evaluated using coercion with the ToBoolean method and always follow these simple rules

The spec is pretty clear which abstract operators are used to coerce type during these comparisons as you can see here: http://www.ecma-international.org/ecma-262/5.1/#sec-11.9.3

I confirmed this with Kyle Simpson who has a extensive chapter on Coercion in his You Don't Know JS series: https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20%26%20closures/ch4.md

Here is the thread I had with Kyle: https://github.com/getify/You-Dont-Know-JS/issues/435

According to the spec, what is actually occurring during the comparison is a little more verbose that what should be explained in your guide, but I will leave that up to you guys since you've written such an awesome guide to date :)

Hope I helped in any form. Thanks!

**Comment by hshoff** [comment]
Hi @matt-e-king, thanks for checking out the guide!

You are correct, comparison operators do not use the `ToBoolean` method.

It is the conditional if statement that evaluate the equality expression's result with the `ToBoolean`.

I updated the language to make this more clear in: https://github.com/airbnb/javascript/pull/337
