### ISSUE TITLE
Packages publishing

### ISSUE THREAD

**Issue by nkt** [airbnb/javascript#339]
Did you think about describing right way for package publishing?
At least for node packages we are using `dependencies`, but for frontend packages, for exam-ple React, we should use `peerDependencies` for avoiding dependencies duplication.
Also there is no best practice for publishing packages that requires polyfills.

**Comment by listochkin** [comment]
We've talked about it on [FrontendUA](https://github.com/dev-ua/frontend-ua) but I will reiterate my point of view. `peerDependencies` seemed like a good idea when they were initially discussed by Isaac and Domenic Denicola, but ultimately they didn't work out as expected. Right now almost nobody uses them (with `Grunt` plugin ecosystem being a notable exception).

On the other hand `npm` has a build in support for [dependencies deduplication](https://docs.npmjs.com/cli/dedupe), that people often use with `Browserify`. Starting from version 3.0 `npm` will deduplicate packages during installation automatically. The implementation is already merged into a corresponding [branch](https://github.com/npm/npm/tree/multi-stage).

@othiym23 discussed this work in npm/npm#6912:

> The install / deduplication algorithm will only flatten the dependency tree as much as it can without introducing semver conflicts or other forms of dependency hell. If there is a conflict, then each dependency will get its own version of the conflicting dependency.

In future `npm` may also introduce some extra checks and warn you if some your dependency tree has a semver conflict and cannot be completely flattened.

**Comment by listochkin** [comment]
As for polyfills it seems like the current state of the art is not to declare them in `dependencies` at all. If you look at [Koa](https://github.com/koajs/koa/) and other ES6 packages they just point to a fact that a runtime has to be ES6-compatible in README.

In this case it's up to a user of the package to decide how to deal with new JS features. Some will already run a newer versions of node/iojs and will be able to run them natively. Others will add small polyfills to plug exactly the features they use, or just run TypeScript, Babel, etc.

**Comment by ljharb** [comment]
+1, peer deps are awful.

Typically a polyfill would not be a dependency, as @listochkin says.

**Comment by nkt** [comment]
@listochkin let's take `Object.assign` method, it's provide *must have* functionality for every application, but also there are set of polyfills for it: `lodash.assign`, `object.assign`, `babel(core-js)` and others.
I suggest formalize this rules and create guide for publishing frontend packages, that would describe all this stuff.

Example rule:
```md
**Polyfills**
You have to use polyfills for standard functionality (like `String.prototype.trim`),
instead of using third-party libraries (like `lodash`).
**Why?**
Because it reduces size of your package, and allows package's user
make choice about using polyfill or not. But you have to note about this requirement
in your readme.
```

**Comment by ljharb** [comment]
`object.assign` is just a function. It provides a `shim` method if you wish to polyfill, but it's not required or automatic. Thus, it's highly appropriate to use it as a straight dependency.

**Comment by nkt** [comment]
@ljharb it's not just function. [It's future functionality of js](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign).
I don't care about additional code in node project, but do in frontend.
What if in my project I'm going to use [react-expandable-nav](https://github.com/ctan1345/react-expandable-nav/blob/master/package.json#L10), [react](https://github.com/facebook/react/blob/master/src/stubs/Object.assign.js#L16) and [babel polyfill](https://github.com/zloirock/core-js/blob/master/modules/%24.assign.js#L5).
So `Object.assign` polyfill will be repeated three times.

**Comment by ljharb** [comment]
Yes, I'm aware, I own http://npmjs.com/object.assign :-) what I mean is, it can be used just as a function, without having to worry about polyfills etc.

What I would probably do in your situation, if I was concerned about 20 lines of code repeated thrice, is use a browserify transform or a webpack alias so that all three of them required the same polyfill.
