### ISSUE TITLE
Incorrect assumption about `let` vs `var`

### ISSUE THREAD

**Issue by ultimatedelman** [airbnb/javascript#342]
In your References section, you tell developers to only use `let` in their code. This is a poor choice that can lead to problems. `let` is not a replacement for `var`, it is a tool to be used alongside it. First off, using `var` to indicate a variable has functional scope is a very clear signal as to the life expectancy of that variable whereas using `let` is weaker. Functionally they are the same, of course, until you start refactoring and your `let` declared variables start disappearing.

Rather than advise developers to use only `let`, advise them to use `var` when the intent of the variable is to live in the full scope of the function and use `let` when the scope of the variable is meant to be limited (such as conditionals or loops, or even explicit `let` scopes).

For reference: http://davidwalsh.name/for-and-against-let

**Comment by goatslacker** [comment]
https://github.com/airbnb/javascript/issues/309

**Comment by goatslacker** [comment]
We actually only use `const` in our code: https://github.com/airbnb/javascript#references
...unless we need to mutate a reference of course.

And since we already [declared all our `var`'s at the top anyway](https://github.com/airbnb/javascript/tree/master/es5#variables) (4th bullet point), replacing them with `let` won't make a difference.

Thanks to `let` now we can [update that section](https://github.com/airbnb/javascript#variables) to a better rule:

> Assign variables where you need them, but place them in a reasonable place.

**Comment by ultimatedelman** [comment]
I'd also argue that your `const` advice is dangerous as well. You're suggesting people set `const` values to the result of a function?! That defeats the purpose of a `const`, actually making it a variable value (albeit immutable). The whole point of `const` is that it is a constant value, such as a "magic number" or a string that isn't supposed to change. What happens when you ultimately decide that you want to be able to change the value of your `const`? do you reassign it to a `let`? why??

**Comment by ljharb** [comment]
Just to point out: `const` is unfortunately named. It does **not** mean "the value is immutable" or even "the value is constant". It means "the variable's value will not be reassigned".

**Comment by goatslacker** [comment]
Variable is a bad word for it since it's no longer variable :)

They're references, and we are suggesting you never reassign them. This leads to better code.

For posterity:

const arr = []
arr.push(1)
arr.push(2)
arr.push(3)

arr // [1, 2, 3]

arr = {} // Error
