### ISSUE TITLE
A change in 8.2 - prefer shorter object return

### ISSUE THREAD

**Issue by hzoo** [airbnb/javascript#344]
https://github.com/airbnb/javascript#8.2

What do we think of using the shorter syntax for returning a single object from an arrow function?

```js
// bad
  [1, 2, 3].map((x) => {
    return { number: x };
  });

// good
  [1, 2, 3].map((x) => ({ number: x }));
```

an example from http://tc39wiki.calculist.org/es6/arrow-functions/

```js
// Parenthesize the body to return an object literal expression
let key_maker = val => ({key: val});
```

**Comment by ljharb** [comment]
This seems reasonable, but could be problematic if people forget that *without* the parens, it's a block with label statements, as opposed to an object - which is a very very common mistake.

By requiring `return`, the object literal is always in expression position, and thus avoids that ambiguity.

**Comment by hzoo** [comment]
> without the parens, it's a block with label statements

Yeah that's true. Maybe I guess requiring the opposite syntax could be better?

I'm going to try implementing both rules in JSCS so it should get caught in that case =). https://github.com/jscs-dev/node-jscs/issues/1385
