### ISSUE TITLE
Add standalone ESLint shareable config

### ISSUE THREAD

**Issue by popenkomaksim** [airbnb/javascript#349]
Hello.
In [ESLint 0.21.0 released](http://eslint.org/blog/2015/05/eslint-0.21.0-released/) they introduces such thing as [shareable config](http://eslint.org/docs/developer-guide/shareable-configs.html).
It provide teams import external configs as npm packages. 
What do you think about publishing ESLint config as [standalone npm packadge](https://www.npmjs.com/search?q=eslintconfig), like "eslint-config-airbnb"?

**Comment by popenkomaksim** [comment]
Wow! Incredible fast!

**Comment by popenkomaksim** [comment]
To make config searchable via [standalone npm packadge](https://www.npmjs.com/search?q=eslintconfig), please, extend packadge.json keywords with ```eslintconfig```:
```
  "keywords": [
    "eslint",
    "eslintconfig"
    "config",
    "airbnb",
    "javascript",
    "styleguide"
  ],
```

**Comment by justjake** [comment]
Done: https://github.com/justjake/javascript/commit/c3a94c15fd5385828f47e45b1e329a810d0ecfc3

**Comment by popenkomaksim** [comment]
@justjake you rock!
