### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by nkt** [airbnb/javascript#351]
Do you have any style guide about css?

**Comment by justjake** [comment]
We're working on one right now. I think we'll publish it in one or two
weeks.

**Comment by nkt** [comment]
@justjake great news! Don't forget about [csscomb](http://csscomb.com), which allows automate css/less/etc. formatting.

**Comment by najela** [comment]
@justjake It seems the two weeks timeline passed?

**Comment by justjake** [comment]
We're proud to have published our CSS style guide here: https://github.com/airbnb/css

**Comment by nkt** [comment]
Great, thanks!
