### ISSUE TITLE
componentDidUpdate is missing in react style guide?

### ISSUE THREAD

**Issue by ycavatars** [airbnb/javascript#358]
The react style guide doesn't contain `componentWillUpdate`. Should it be added after `componentWillUpdate`? Thanks.

**Comment by goatslacker** [comment]
:+1: yes

**Comment by ycavatars** [comment]
Already send a pull request https://github.com/airbnb/javascript/pull/359 :)

**Comment by hshoff** [comment]
Fixed in https://github.com/airbnb/javascript/pull/359
