### ISSUE TITLE
3.4 having syntax error?

### ISSUE THREAD

**Issue by HenryGau** [airbnb/javascript#368]
Please have a check, I think 3.4 is having syntax error right?
https://github.com/airbnb/javascript#3.4
```
  function getKey(k) {
    return `a key named ${k}`;
  }

  // good
  const obj = {
    id: 5,
    name: 'San Francisco',
    [getKey('enabled')]: true,
  };
```
is giving
Uncaught SyntaxError: Unexpected token [
    at Object.InjectedScript._evaluateOn (<anonymous>:895:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
    at Object.InjectedScript.evaluate (<anonymous>:694:21)
on Chrome

I think 
```
    [getKey('enabled')]: true,
```
is not valid.

**Comment by ljharb** [comment]
It's valid, but Chrome doesn't support computed property keys yet. Check it in http://babeljs.io/repl

**Comment by HenryGau** [comment]
Thanks
