### ISSUE TITLE
Exception to the "don't use iterators and generators" rules

### ISSUE THREAD

**Issue by cbankester** [airbnb/javascript#385]
If I may, I'd like to propose changing the "Don't use iterators" of [1] and "Don't use generators" of [2]. The advice to not use generators hinges on the inability to transpile well to ES5, which I totally agree with. However, in certain JS environments (namely Node.js/io.js), generators are supported, and I believe their use should only be advised against in situations where the code will be transpiled to ES5.

Thus, I think we should amend the lines appropriately to indicate that:

1. Generators can be used in situations where the code will not need to be transpiled

2. Iterators can be used in certain situations
  * Because, for instance, `for-of` loops combined with yielding inside a generator is a very useful technique, whereas `.forEach` loops combined with yielding inside a generator is not appropriate

3. Generators should follow some certain style. It would seem based on [3] that the style should be
  ```javascript
  function* foobar() {...}
  ```

I believe we should keep the information that is currently there in tact and simply add these rules as a note or special case or something. It is certainly a good idea, for instance, to prefer using array-prototype-given looping mechanisms instead of `for-of`/iterator loops in order to avoid unnecessary mutation (as is currently suggested in [1]).

[1] https://github.com/airbnb/javascript#11.1
[2] https://github.com/airbnb/javascript#11.2
[3] https://github.com/airbnb/javascript/issues/240

**Comment by goatslacker** [comment]
This is just the guide we internally follow at Airbnb. It's rare that we need to reach for a generator or iterator in our particular case. Generators are really nice for async but we'll just wait for async/await in ES2016 instead.

You're free to fork the guide and follow this separate style in your team though, in fact we encourage you to just use this as a blank template starting point for your own coding guide.
