### ISSUE TITLE
How do you feel about || fallbacks?

### ISSUE THREAD

**Issue by davidhariri** [airbnb/javascript#386]
Is this acceptable?

```
class Comment {
    constructor(args) {
        this.request_id = args.request_id || '';
    }
}
```

**Comment by nkbt** [comment]
I reckon something like this
```
class Comment {
    constructor(request_id = '') {
        this.request_id = request_id;
    }
}
```

**Comment by hshoff** [comment]
We prefer default parameter syntax to avoid mutating function arguments. https://github.com/airbnb/javascript#7.7

**Comment by davidhariri** [comment]
Thanks @hshoff :pray:

**Comment by davidhariri** [comment]
@nkbt don't think that accomplishes the same thing :grin:

**Comment by nkbt** [comment]
@davidhariri I missed you did not write `constructor(...args)`, but `constructor(args)`

But the idea is the same - better use default parameters.

**Comment by davidhariri** [comment]
@nkbt I tried to use `constructor(...args)` but it didn't accomplish what I'm looking for... Could i email you for assistance? I'm just now making the leap to ES6 syntax and need some guidance...

**Comment by nkbt** [comment]
@davidhariri sure thing, nik@butenko.me or gitter.im PM to `nkbt`

**Comment by hshoff** [comment]
@davidhariri I think you want something like this:

```js
class Comment {
  constructor({ request_id = ''}) {
    this.requestId = request_id;
  }
}
```

**Comment by nkbt** [comment]
@hshoff Exactly [Babel REPL](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=class%20Comment%20{%0A%20%20%20%20constructor%28{request_id%2C%20reply_id%2C%20message%20%3D%20%27%27%2C%20is_private%20%3D%20false%2C%20slug%20%3D%20%27%27}%29%20{%0A%20%20%20%20%20%20%20%20this.request_id%20%3D%20request_id%3B%0A%20%20%20%20%20%20%20%20this.reply_id%20%3D%20reply_id%3B%0A%20%20%20%20%20%20%20%20this.message%20%3D%20message%3B%0A%20%20%20%20%20%20%20%20this.is_private%20%3D%20is_private%3B%0A%20%20%20%20%20%20%20%20this.slug%20%3D%20slug%3B%0A%20%20%20%20}%0A}%0A%0Alet%20comment%20%3D%20new%20Comment%28{%0A%20%20%20%20request_id%20%3A%20%279865234620573523%27%2C%0A%20%20%20%20reply_id%20%3A%20%274673598706327469340%27%2C%0A%20%20%20%20message%20%3A%20%27Hello%20world!%27%2C%0A%20%20%20%20private%20%3A%20false%2C%0A}%29%3B)

**Comment by davidhariri** [comment]
@hshoff, @nkbt it's unfortunate I have to redefine all parameters:
```
this.requestId = request_id;
```
after the constructor-level default definitions...

is there no deconstruction method for that? something like `this = {...this}`?

**Comment by ljharb** [comment]
(re https://github.com/airbnb/javascript/issues/386#issuecomment-118203990) and `constructor({ request_id = '' } = {})` if you want the entire object, not just the property, to be optional.

@davidhariri I think you're looking for:
```js
constructor(options = {}) {
  Object.assign(this, options);
}
```
but that has the danger of overwriting properties you may care about. Alternatively:
```js
constructor(options = {}) {
  const whitelist = ['a', 'b', 'c'];
  whitelist.forEach(key => this[key] = options[key]);
}
```

**Comment by davidhariri** [comment]
@ljharb what would you use when defining a model?

**Comment by ljharb** [comment]
@davidhariri It entirely depends on the pattern I'm trying to follow. Personally I prefer to avoid shared mutable state, and mutation of any kind, so I don't think my personal choices tend to fit well with ES6 "class"es.

In this case, I'd probably keep model attributes somewhere *not* on `this` directly, and have `get` and `set` methods on the prototype, just like Backbone does.

**Comment by davidhariri** [comment]
Thank you @ljharb, I'll keep swimming...
