### ISSUE TITLE
Change name to "Best Practices"

### ISSUE THREAD

**Issue by franciscop** [airbnb/javascript#387]
According to [Wikipedia on Style Guide](https://en.wikipedia.org/wiki/Style_guide):

> A style guide is a set of standards for the writing and design of documents, either for general use or for a specific publication, organization, or field.

Also according to [Wikipedia on Best Practices](https://en.wikipedia.org/wiki/Best_practice):

> A best practice is a method or technique that has consistently shown results superior to those achieved with other means, and that is used as a benchmark.

This repository doesn't only deal with how to style the different elements in javascript (curly braces closing, indentation, etc), but it deals with *how* and *why* to write javascript in a certain way. It not only deals with visual features, but also with maintainability and performance.

That is why I think a better name would be "Best Practices" instead of "Style Guide". Any thoughts?

PS, I love it, thanks for publishing it (:

**Comment by BMorearty** [comment]
I, too, have noticed that this style guide has a lot of guidelines that have nothing to do with style. I think that's a big part of the reason it's so long (too long).

My suggestion: don't rename this style guide. Instead, split it into two. A Style Guide and a Good Practices Guide. (Don't call it "Best Practices," an arrogant name that implies there is no room for discussion.)

Either that, or just remove everything that's not style-related and let good practices be learned elsewhere.

**Comment by ljharb** [comment]
The word "style" deals with more than just syntax and punctuation. Everything is style-related.

**Comment by tomekwi** [comment]
I agree with @ljharb. This is what distinguishes this style guide, making is so awesome.

Not only saying *how* to write – but also *why* it should be written that way.
