### ISSUE TITLE
Add Cludo to list of companies that uses airbnb styleguide

### ISSUE THREAD

**Issue by Phatzor** [airbnb/javascript#388]
Hi,

Could I have you add Cludo (https://github.com/Cludo/javascript) to the list of companies using your fantastic JS styleguide.

**Comment by gliwka** [comment]
I would suggest to send a pull request.

**Comment by Phatzor** [comment]
Hi @gliwka I added the issue here since it was one of the options according to the documentation. I can however also create the pull request.
