### ISSUE TITLE
Request: Add more information on Testing section

### ISSUE THREAD

**Issue by ankitaggarwal011** [airbnb/javascript#392]
**Please add and explain more information on Testing section:**
* Regarding standards to follow in writing test suites in JavaScript. 
* Important pointers and tips.

Update: Removed the second point, since it would be included by default in the first point. Thanks to @BMorearty.

Thanks!

**Comment by goatslacker** [comment]
Not sure if this belongs in the style guide or not...

**Comment by BMorearty** [comment]
Maybe the first bullet point. 

The second bullet is confusing to me--not sure what's being asked for. 

The third one, I'd say no. Pointers and tips can be useful but not in the context of a style guide.

**Comment by ankitaggarwal011** [comment]
There are two points to consider here:

* Since it is ambiguous whether to include Testing section in a style guide, so Testing section can be altogether omitted.
* Other point is, since testing is an integral part of software development and different developers have different way of writing test suites, It could be important to include a few guidelines, pointers and tips regarding the same in the style guide.

I am more inclined towards the second point, but its equally apt to opt for first point as well. But yes, I agree there needs to be some discussion about the same.

**Comment by ilanbiala** [comment]
https://github.com/airbnb/javascript#testing has nothing right now unless I missed a link to another section.

**Comment by ljharb** [comment]
I've got a branch in progress that updates this section.
