### ISSUE TITLE
String concat speed

### ISSUE THREAD

**Issue by rjacoby** [airbnb/javascript#40]
In the [Strings section](https://github.com/airbnb/javascript#strings) the standard is:

> "Strings longer than 80 characters should be written across multiple lines using string concatenation."

I understand the clarity of code - but the performance is 80-100% worse. [jsPerf](http://jsperf.com/ya-string-concat)

The need for such long strings is debatable anyway, but isn't this kind of a steep performance penalty for code style?

**Comment by Nemoden** [comment]
So, why exactly strings concatenation is preferred by the Guide if it's 95% slower than joining it with the break symbol (\\)? It doesn't add much readability and extremely slow.

![js_perf_long_strings](https://cloud.githubusercontent.com/assets/795034/7037567/3e7dffe2-dde8-11e4-99ce-bcd1aa5996dc.png)

**Comment by nkbt** [comment]
@Nemoden maybe because of readability. When string concatenation becomes a bottleneck in the app, then it can be easily converted to the fastest way available.

**Comment by joooche** [comment]
Ok

**Comment by yonghu86** [comment]
well,it's not length.

**Comment by michaelmior** [comment]
I think concatenation is much more readable for the sole fact that you can keep the correct level of indentation. As I noted in my previous comment, I think concatenation of static strings should be removed by build tools so performance should not really ever be an issue.

**Comment by ibc** [comment]
> I think concatenation is much more readable for the sole fact that you can keep the correct level of indentation.

Or you can use a proper editor that properly indents extra lines if they belong to the same line.

**Comment by jonasninja** [comment]
It seems that the latest versions of Chrome have made performance a moot point. Here's a screenshot of revision 6 results. 
![image](https://cloud.githubusercontent.com/assets/4935079/9977082/02f0af1c-5ec9-11e5-9f79-0deb4bf9cb3c.png)

**Comment by ljharb** [comment]
Nowaways it's preferred to use an ES6 template string literal - which transpiles to a long string (with or without breaks, i forget). This entire issue seems like a moot point now :-)

**Comment by GrayedFox** [comment]
Not quite a moot point.... basically, referencing variables inside of a template literal is still much slower than string concatenation, however without referencing a variable (and simply using a template literal for line breaks) seems to have no performance impact... https://jsperf.com/es6-string-literals-vs-string-concatenation/4

**Comment by ljharb** [comment]
But also, "much slower" won't make any difference unless you're building millions of strings per second. It's identically fast for most use cases.
