### ISSUE TITLE
JSCS pattern

### ISSUE THREAD

**Issue by rootical** [airbnb/javascript#402]
What a wonderful set you have here. 

Sorry if someone has already asked, but a way to have some specially organized [JSCS](http://jscs.info/) config would help a lot. 

Thanks once more, 
Vadzim.

**Comment by caspervonb** [comment]
`jscs --preset airbnb`
[see preset option](http://jscs.info/overview.html#preset)

**Comment by rootical** [comment]
Oh, sorry and thanks.
