### ISSUE TITLE
ES5 Type Casting

### ISSUE THREAD

**Issue by MarkoCen** [airbnb/javascript#414]
In JavaScript ES5 Type Casting [Section](https://github.com/airbnb/javascript/tree/master/es5#type-casting--coercion)

*  **Perform type coercion at the beginning of the statement.**

```javascript
// bad
var totalScore = '' + this.reviewScore + ' total score';

// good
var totalScore = this.reviewScore + ' total score';
```

Based on the guide, should the first statement is good and the last is bad?

**Comment by ljharb** [comment]
The latter is good, specifically because `String(foo)` is always better than `foo + ''` or `foo.toString()`

Consider the following:
```js
var x = { toString: function () { return NaN; }, valueOf: function () { return Infinity; }};
[x.toString(), x + '', String(x)]
/* note that only the third item is both a string, and the toString value */
```

**Comment by MarkoCen** [comment]
Got it. Thanks!
