### ISSUE TITLE
Immutable Rule in for-of loop using 'const'

### ISSUE THREAD

**Issue by Rukenshia** [airbnb/javascript#417]
In [11.1](https://github.com/airbnb/javascript#11.1), it is mentioned that `for-of` loops should not be used because it could violate the immutable rule. What is you are using `const` instead of `let` for the value inside the `for-of` loop?

**Comment by goatslacker** [comment]
Most commonly you want to use a for loop to transform something into a value, say you want to filter an array of reduce it into a Boolean. In those cases using JS's built in functions is preferrable. 

There are exceptions though

**Comment by goatslacker** [comment]
Oops hit comment too early. 

Exceptions like if you need to break early or if you need to fine control the performance of a hot path. These rarely happen but in the event they do then a loop is ok.

**Comment by Rukenshia** [comment]
In my use-case, I am looping through `Set`s of class instances and just want to call some functions of them, that's why I am asking.

**Comment by goatslacker** [comment]
sets.forEach()?

You're not writing Airbnb code though so feel free to do whatever you want 😝

**Comment by Rukenshia** [comment]
I was actually just asking if my guess on that would be correct, I know that I am free to do whatever I want :p

**Comment by ljharb** [comment]
Sounds like this question is answered :-)
