### ISSUE TITLE
Consistent Use Of Trailing Commas for ES5 and ES6

### ISSUE THREAD

**Issue by destroyerofbuilds** [airbnb/javascript#419]
Allowing trailing commas as part of the ES6 style guide was justified in #323 by arguing that transpiling ES6 code using `babel`, which strips trailing commas, mitigates issues with older browsers.

However, it's quite standard practice to run tools, like `uglify`, against ES5 code prior to shipping the code. Tools like `uglify` also eliminate trailing commas, effectively providing the same issue mitigation afforded by `babel`.

Could the use of `uglify` be justification for allowing trailing commas in ES5 code (bringing ES5 style closer inline with the ES6 style)?

**Comment by goatslacker** [comment]
Yeah it's a fair point but we're not exactly using uglify universally so we still need to be aware of trailing commas for ES5. You're free to fork the guide and use trailing commas in ES5 yourself though.
