### ISSUE TITLE
Why does the .eslintrc prohibit unused function parameters? 

### ISSUE THREAD

**Issue by ariporad** [airbnb/javascript#426]
Hi,

I'm coming at this from a node point of view, so sorry if it's weird for client side JS.

Why do you prohibit unused function parameters in the .eslintrc? In node, (and AFAIK in the browser), ignoring one or more of your parameters for now isn't that big a deal (for example, if a callback gets err, info, res, ignoring info is fine.)

Thanks!
Ari

**Comment by tomekwi** [comment]
I often leave out parameters in the middle – like in `through2.obj((file, _, done) => {…})` and I’ve never had any problems. `(err, info, res) => [err, res]` should work just fine.

But if you have `(err, res, info) => [err, res]`, what do you need the `info` parameter for? To confuse people?

**Comment by ariporad** [comment]
This was a while ago, so I'm not sure exactly what it as, but if the info parameter was extra meta data, it might not be needed.

**Comment by justjake** [comment]
I agree -- If you submit a PR dropping this rule I'll happily merge it.

**Comment by ariporad** [comment]
@justjake: I actually opened two, because I noticed that something was messed up. #506 and #507 

Thanks!
