### ISSUE TITLE
javascript笔记

### ISSUE THREAD

**Issue by Jey100** [airbnb/javascript#429]
1,NaN
  NaN 是一个值(非常特殊的值)，类型为Number;
  例如：
  var name;
  var value = parseInt(name);
  alert(value);  //此时弹出NaN
  alert(value === NaN)  //全等判断，返回false
  alert(value == NaN)   //等值判断，返回false
  alert(Number.isNaN(AV));     //判断是否是NaN 返回true

  alert(typeof value)  // Number 类型
 
  **(不要用一个NaN，去判断是否等于NaN,因为他自己也不等于自己，这是js的特例，多么神奇)
 

2，空字符串也可以做为对象的成员名
   aa ={
    	"\0":"kobe",
 	'':"bryant",
        ' ':123
    }

	alert(aa["\0"]); //kobe （\0表示Nul字符）
	alert(aa[""]);   //bryant
	alert(aa[" "]);  //123

3，==相等   (值相同)   
   ===相同  （值相同，类型相同）

  例子1
  var str1 = "aa";
  var obj1 = new String(str1);
  alert(obj1 == str1);  //true
  alert(obj1 === str1); //false （值类型与引用类型，必然不同）

  例子2
  var obj1 = new String(str1);
  var obj2 = new String(str1);

  alert(obj1 == obj2);   //false 
  alert(obj1 === obj2);  //false
  
  **（两个引用类型的比较较运算中，==和===始终都是一致的，为false,
      因为他们都指向不同的内存地址，即不同的指针）
	  
	  
	  
4,字符参与序列检测
	var s1 = "abc";
	var s2 = "ab";
	var s3 = true;
	var s4 = "10"
	var s5 = 9;
	alert(s1 > s2) // true,两个字符比较时，比较序列值
	alert(s1 > s3) //false 此时，s1会转换为数值，并且为NaN,s3会转换为数值1，由于NaN与任何值比较都是false,所有返回false
	alert(s4 > s5) //true 此时，s4会转换为数值，为10，
	
	**(js中，当非Number类型变量参与比较时，都会将自己先转换为 Number类型，进行比较(字符与字符比较除外，他们比较序列值，这个也特殊 ))
	
5，多重求值","
	var i = 100;
	alert(i += 10,i*=2,i+=100,"value:"+i); //返回最后表达式的值 value:320

6，void 运算符
   	void是将其后的字面量当元表达式执行，并永远返回undefined。同时undefined不是关键词。。
	void有如下作用：
		a,通过采用void 0取undefined比采用字面上的undefined更靠谱更安全，应该优先采用void 0这种方式。
		b,填充<a>的href确保点击时不会产生页面跳转; 填充<image>的src="javascript:void(0)"，确保不会向服务器发出垃圾请求。

	
7,eval()函数
	var x = eval("1+2;var x =5;;;3+5;;function f(){};");
	var x2 = eval("1+2;var x =5;;;3+9;;function f(){return 100};f();");
	alert(x);  //返回8
	alert(x2);  //返回100(f()的返回值)
	
	**(当我们试图用eval()执行一批语句并返回结果值是，这些语句都将被忽略，然后返回"最后执行到的，有返回值"的那条语句的值)
	
	
8,函数调用
   //方法1
  (function(A){
	alert(A);
	})(1);
	
	
	//方法2
	(function(C){
		alert(C);
	}(2));

    //方法3
	void function(D){
	   alert(D);
	}(3);
	
	//错误4（错误的调用 ）
	function(D){
	   alert(D);
	}(3);
	
	** 方法3中，如果没有void运算符，讲发生语法错误，因为错误4会按照完整的函数声明来解释，脚本引擎会解析成：
	   function(D){
	       alert(D)
	   };(3)   //此时;(3)不会被编译通过
	

9,get/set
  var per={
	_name:null,
	_age:0,
	set name(a){this._name = a},
	get name(){return this._name},
  }
	per.name="kobe";
	alert(per.name);  //kobe    Ecmascript5 才支持的写法，ie9+ 才可以支持

	
10,with 语句可以方便地用来引用某个特定对象中已有的属性(严格模式下，会被禁用)
	function foo(){
		this.name="kobe";
		this.say = function(){alert(123)}
	}
	var per = new foo();
	with(per){
	 name="yaoming";
	}

	alert(per.name);  //yaoming
	
11,关于严格模式
  严格模式指示前缀如果出现在代码中间，则它将被忽略
  "use strict"
  var eval;  //严格模式
  
  var xa;
  "use strict"  //由于前面有代码，这行，将被忽略
  ;"use strict"  //或者这样，，这行，将被忽略
  var eval; 
  
  
12,js的二义性
  12.1 "+"
	  alert("3"-1);  //2
	  alert("3"+1);  //31
	  
  12.2 "()"
      alert((1,2,3));  //3
	  alert(1,2,3);    //1
	  
13, 无论通过 arguments 还是形式参数，都可以修改入口参数的值
14, 永远不可能通过修改参数来影响到函数外部的普通变量，但是，可以修改对象的成员
	var name = "aa"
	function F(p1){
		p1 = 123; //修改参数
	}
	F(name);
	alert(name) // 依然是aa
	
	----------------------------------------
	
	var obj = {name:"cc"};
	function F(p1){
		p1.name = 234 //修改参数成员属性
	}
	F(obj);
	alert(obj.name); //此时已经变成 234 
	***传入的obj相当于是一个指针地址，或者应用，自己总结

**Comment by iamstarkov** [comment]
sorry, can you translate your issue, so we can discuss it?

**Comment by luckymore** [comment]
@iamstarkov he taked a note in your place :cry:

**Comment by iamstarkov** [comment]
@luckymore =(

**Comment by ljharb** [comment]
I'm going to close this for now - @jey100, please reopen if you can offer a translation.
