### ISSUE TITLE
block-scoped-var error when using destructuring in function argument

### ISSUE THREAD

**Issue by olalonde** [airbnb/javascript#434]
I am refactoring an Express app to es6 and tried to do this:

```javascript
module.exports = {
  index: ({
    app,
    query: { limit = 10, page = 1, type },
    params: { param1, param2 },
  }, res, next) => {
     // some code
  },
};
```

It runs and compiles as expected using babel. However, eslint gives me a bunch of `block-scoped-var` errors:

```
"limit" used outside of binding context. (block-scoped-var)
etc.
```

Is this against the Airbnb style guide? Is there a way to fix the `.eslintrc` for that use case?

**Comment by nkbt** [comment]
I raised this issue in eslint repo
https://github.com/eslint/eslint/issues/2253

**Comment by olalonde** [comment]
@nkbt oh I see. So it's likely just a bug with eslint.

**Comment by nkbt** [comment]
@olalonde yes, it is confirmed. Someone picked this bug today, so hopefully will be fixed. I recommend to disable this rule until then.
