### ISSUE TITLE
Defensive programming benefit of the bang method ("!") is not correct.

### ISSUE THREAD

**Issue by heavysixer** [airbnb/javascript#44]
First off this is a great document, and thanks for sharing it. I have read the entire file end-to-end as I work on my own personal style guide. However, I was looking at your module example and you assert that "!" protects you from concatenation errors. However, I don't think this is correct. Consider the following example:

```
// => SyntaxError: Unexpected token !
!function(){console.log("ham");}()!function(){console.log("cheese")}();
```

Maybe I am misunderstanding how you expected things to work.

I think you still need to prepend a semicolon to truly protect yourself from concatenation errors.

```
;!function(){console.log("ham");}()
```

**Comment by p3k** [comment]
@iod you still would have to add prefix void with a semicolon if you want to prevent errors with sloppy code on concatenation. Nevertheless, I lik the idea with void very much.

**Comment by rstacruz** [comment]
or a comment would be fine @p3k, which you might have when using eslint:

```js
/* global define */
void function () {
}(...)
```
