### ISSUE TITLE
More frequent versions bumps

### ISSUE THREAD

**Issue by einarlove** [airbnb/javascript#440]
Have been trying to figure out why the rules in the [README](https://github.com/airbnb/javascript/blob/master/README.md) are not applied to my linter, but I see now that the styleguide has not been updated to [NPM](https://www.npmjs.com/package/airbnb-style) in over 2 months.

I would encourage more frequent [versions bumps](https://github.com/airbnb/javascript/commit/df5029b5a55602a0b65f6a0a8dd7ac9a757caea8) and updates to the [NPM module](https://www.npmjs.com/package/airbnb-style).

**Comment by lauritzsh** [comment]
I was planning on creating a related issue regarding infrequent bumps too after I had woken up, so funny to see this just created. Lots of changes have been made, most significant is probably the React guidelines to `.eslintrc` and updated rules such as `comma-dangle`. 

Is it possible to publish a new `eslint-config-airbnb` package with the updated rules? It would be very much appreciated.

**Comment by einarlove** [comment]
Was actually [eslint-config-airbnb](https://www.npmjs.com/package/eslint-config-airbnb) I was refering to, so thanks for mentioning it.

**Comment by rpominov** [comment]
+1, we had to copy fresh version of the config file to our project before `0.0.7` because `0.0.6` was too outdated. I'd really appreciate more frequent releases.

**Comment by ljharb** [comment]
The version is now being bumped frequently.

Please note that I now consider "breaking" to be when something in the style guide changes (and an associated linter rule changes), "minor" to be when a pre-existing rule in the styleguide begins becoming enforced, and "fix" to be when a pre-existing linter rule was using the wrong options, and is fixed to match the styleguide.
