### ISSUE TITLE
Can I use eslint-config-airbnb without eslint-plugin-react?

### ISSUE THREAD

**Issue by txchen** [airbnb/javascript#451]
I am not using react, so it would be better for me to just install eslint.

Is it possible to move the jsx related configs to a separated file?

**Comment by timkurvers** [comment]
I think this is being discussed over at #366.

**Comment by txchen** [comment]
I actually created a package for this: https://github.com/txchen/eslint-config-airbnb-lite

**Comment by timkurvers** [comment]
Very nice, thanks for the heads-up!

**Comment by justjake** [comment]
the official package now has a react-free version (as of v0.0.8)!

simpy `npm install --save-dev eslint-config-airbnb` and add `{ "extends": "airbnb/base" }` to your .eslintrc

see here: https://www.npmjs.com/package/eslint-config-airbnb

**Comment by txchen** [comment]
@justjake that's sweet! thanks for the information!

**Comment by rsp** [comment]
@justjake @txchen Using `"extends": "airbnb/base"` in .eslintrc is **deprecated**, see:
* https://www.npmjs.com/package/eslint-config-airbnb#eslint-config-airbnbbase

Currently the way to avoid using `eslint-plugin-react` is to use `eslint-config-airbnb-base`, see:
* https://www.npmjs.com/package/eslint-config-airbnb-base

It requires only `eslint` and `eslint-plugin-import` as peer deps and you use it with `"extends": "airbnb-base"` in .eslintrc - or with `"extends": "airbnb-base/legacy"` for ES5 and below.

**Comment by Raulis** [comment]
after doing all this I get this error:
![image](https://user-images.githubusercontent.com/20267355/35443026-2b729a38-02b2-11e8-9730-1183a5a2154f.png)
What does that mean?

**Comment by ljharb** [comment]
Not sure where that error comes from; does it work on the command line?

**Comment by Raulis** [comment]
hello @ljharb !
I get the same error just more stuff. I am new at this. Not really know much about terminal and stuff.
![image](https://user-images.githubusercontent.com/20267355/35476750-f1a9cd78-03bd-11e8-951a-168b6d506958.png)

**Comment by ljharb** [comment]
It looks like you’re running a global eslint; try uninstalling that one and running the local one through an npm run-script (be sure any editor or IDE you’re using also uses the local one)

**Comment by Raulis** [comment]
hmm... I tried like this: `./node_modules/.bin/eslint js.js`

Get the same error, not sure what I am doing wrong here.
```
Cannot find module 'eslint-config-airbnb-base'
Referenced from: Y:\Google drive\www\projektai\portfolio\.eslintrc
Error: Cannot find module 'eslint-config-airbnb-base'
Referenced from: Y:\Google drive\www\projektai\portfolio\.eslintrc
    at ModuleResolver.resolve (Y:\Google drive\www\projektai\portfolio\node_modules\eslint\lib\util\module-resolver.js:74:19)
    at resolve (Y:\Google drive\www\projektai\portfolio\node_modules\eslint\lib\config\config-file.js:515:25)
    at load (Y:\Google drive\www\projektai\portfolio\node_modules\eslint\lib\config\config-file.js:584:26)
    at configExtends.reduceRight (Y:\Google drive\www\projektai\portfolio\node_modules\eslint\lib\config\config-file.js:421:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (Y:\Google drive\www\projektai\portfolio\node_modules\eslint\lib\config\config-file.js:403:28)
    at loadFromDisk (Y:\Google drive\www\projektai\portfolio\node_modules\eslint\lib\config\config-file.js:556:22)
    at Object.load (Y:\Google drive\www\projektai\portfolio\node_modules\eslint\lib\config\config-file.js:592:20)
    at Config.getLocalConfigHierarchy (Y:\Google drive\www\projektai\portfolio\node_modules\eslint\lib\config.js:226:44)
    at Config.getConfigHierarchy (Y:\Google drive\www\projektai\portfolio\node_modules\eslint\lib\config.js:180:43)
```

**Comment by ljharb** [comment]
Have you npm installed the config locally as well?

**Comment by basickarl** [comment]
```
  "devDependencies": {
    "eslint": "^4.16.0",
    "eslint-config-airbnb-base": "^12.1.0",
    "eslint-plugin-import": "^2.8.0",
    "mocha": "^5.0.0",
    "nyc": "^11.4.1",
    "squel": "^5.12.0"
  }
```

```
[Error - 11:21:03] Cannot find module 'eslint-config-airbnb/base' Referenced from: /Users/kmorrison/dev/prn/.eslintrc.json
```

**Comment by basickarl** [comment]
```
  "devDependencies": {
    "eslint": "^4.16.0",
    "eslint-config-airbnb-base": "^12.1.0",
    "eslint-plugin-import": "^2.8.0",
    "mocha": "^5.0.0",
    "nyc": "^11.4.1",
    "squel": "^5.12.0"
  }
```

```
[Error - 11:21:03] Cannot find module 'eslint-config-airbnb/base' Referenced from: /Users/km/dev/prn/.eslintrc.json
```

**Comment by basickarl** [comment]
```
  "devDependencies": {
    "eslint": "^4.16.0",
    "eslint-config-airbnb-base": "^12.1.0",
    "eslint-plugin-import": "^2.8.0",
    "mocha": "^5.0.0",
    "nyc": "^11.4.1",
    "squel": "^5.12.0"
  }
```

```
[Error - 11:21:03] Cannot find module 'eslint-config-airbnb/base' Referenced from: /Users/karl/dev/prn/.eslintrc.json
```

**Comment by ljharb** [comment]
And does eslintrc.json have a slash in it or a hyphen?

**Comment by felipealvesgnu** [comment]
@ljharb Add` "extends": "airbnb-base"` with hyphen
