### ISSUE TITLE
Missing no-undef in .eslintrc

### ISSUE THREAD

**Issue by baodang** [airbnb/javascript#454]
I think you should turn this rule on by default.

http://eslint.org/docs/rules/no-undef

This rule can help you locate potential ReferenceErrors resulting from misspellings of variable and parameter names, or accidental implicit globals (for example, from forgetting the var keyword in a for loop initializer).

**Comment by ljharb** [comment]
We do have https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/.eslintrc#L180

**Comment by baodang** [comment]
Sorry, I do not know that react/jsx-no-undef can cover no-undef. It works when I call eslint directly but not when I use gulp-eslint. Thank you anyway.

**Comment by jakezatecky** [comment]
I can also vouch that having `react/jsx-no-undef` turned on is not sufficient for `no-undef` to trigger in `gulp-eslint` or in an IDE such as WebStorm. At least it's easy to add that rule to the `.eslintrc` that's extending `airbnb`.

**Comment by sylvaingi** [comment]
Same here, without `no-undef` referencing a variable that does not exist (e.g. typo) is not caught by eslint.

**Comment by aaronjensen** [comment]
Yep, it doesn't catch it. Maybe it did at one point, but it no longer seems to.

**Comment by justjake** [comment]
ok.

**Comment by taion** [comment]
I'm seeing the same issue. Is this set of rules intended to be used on top of e.g. `eslint:recommended`, or is it supposed to be standalone?

**Comment by justjake** [comment]
Seems like a legit issue. Does anyone have a PR?

**Comment by aaronjensen** [comment]
Sure @justjake, #484

**Comment by taion** [comment]
@justjake 

Seems like there's 3 possible approaches here:

1. Just add the missing ESLint rules - you're also missing a few things like `no-dupe-args` that you probably want
2. Extend `eslint:recommended` which provides (most of) the missing rules
3. Take advantage of `defaults/configurations/airbnb` from https://github.com/walmartlabs/eslint-config-defaults - looks like they have something that's intended to follow your style guide as well, but is pretty thoroughly broken out by section, and explicitly enumerates all ESLint rules

Which do you think is the right way to go?

**Comment by justjake** [comment]
@taion I am planning to switch to walmart's configs, but I've merged #484 in the mean time

**Comment by taion** [comment]
By that, do you mean merge in the Walmart configs into this repo? Or do you suggest switching to `eslint-config-defaults/configurations/airbnb` entirely?

**Comment by justjake** [comment]
I mean removing the js files in eslint-config-airbnb and replacing them with a copy of the files in eslint-config-defaults/configurations/airbnb

**Comment by taion** [comment]
:+1: I really like how they structured it.

**Comment by taion** [comment]
@justjake Are you looking for a PR to replace the rules? Otherwise, would you mind cutting a 0.0.9 that includes the `no-undef` rule? Looking to simplify my `.eslintrc`s.
