### ISSUE TITLE
Add a .jsbeautifyrc file  to automatically format code based on style guide

### ISSUE THREAD

**Issue by AchoArnold** [airbnb/javascript#462]

**Comment by hshoff** [comment]
Will do! We'll add it in the upcoming plan: https://github.com/airbnb/javascript/pull/455#issuecomment-128103763

**Comment by Wasmoo** [comment]
+1

**Comment by jamesvillarrubia** [comment]
+1

**Comment by ljharb** [comment]
Please use Github emoji reactions on the original post instead of commenting "+1" - the existing 2 such comments have been removed, as will any future ones.

**Comment by betweenbrain** [comment]
In checking #455, I don't see a `.jsbeautifyrc` file. Am I missing something, or does this still need completing? I'd be happy to work on generating one if needed.

**Comment by ljharb** [comment]
I think my concern is that it wouldn’t be kept up to date with the eslint config; separately, eslint autofix should handle any autoformatting that jsbeautify can do. Is there anything you have in mind that jsbeautify is uniquely capable of doing?

**Comment by betweenbrain** [comment]
Thanks! I appreciate that concern and agree with you. I will need to look into eslint autofix and see if there is a gap between it and jsbeautify.
