### ISSUE TITLE
add "everything-else" before "render"

### ISSUE THREAD

**Issue by t128** [airbnb/javascript#477]
hi,

can we add *everything-else* before *render* to the [*react/sort-comp*](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md#rule-options) rule?

At the moment it's complaining about my function not being placed after render:
```javascipt
[...]
myMagicFunc() {},
render() {},
[...]
```

**Comment by slava-sh** [comment]
Here is a PR: #461.

**Comment by t128** [comment]
ohh, sorry i searched for "everything-else" without finding your pr
