### ISSUE TITLE
Discourage use of const

### ISSUE THREAD

**Issue by gajus** [airbnb/javascript#485]
ES6 const does not provide read-only data structure.

> The const declaration creates a read-only named constant.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const

The documentation is incorrect/misleading. It provides a constant reference to a value:

```js
const foo = 'test';

foo = 'bar';
```

Produces:

```
Line 3: "foo" is read-only
```

Thats because `foo = 'bar'` is attempting to assign a new value reference.

However,

```js
const foo = {};

foo.bar = 'bar';
```

Does not produce error, because value reference does not change – the value itself changes. Therefore, this is not a read-only value.

This creates false expectations about the data structure.

**Comment by nkbt** [comment]
`const foo = {};` is still better then `let foo = {}` since you cannot re-assign variable afterwards.

The issue of assigning properties is just the language specific. I don't think `const` crates false expectations.

**Comment by justjake** [comment]
Our styleguide reads:

> **2.1 Use const for all of your references; avoid using var.**
>  Why? This *ensures that you can't reassign your references* (mutation), which can lead to bugs and difficult to comprehend code.

I think "can't reassign your references" is a good summary of what you get from `const`. If you want to add another sentence to rule 2.1 along the lines of "data referenced by `const` may still be mutable" then I encourage you to open a pull request.

Internally we spent a bit of time discussing how much we should explain `const` when we were writing the ES6 styleguide, and settled on the current text of the rule, but if this is an issue for others then I think a little more explanation is warranted.

**Comment by AdamBrodzinski** [comment]
> but if this is an issue for others then I think a little more explanation is warranted.

@justjake I had the same issue. If the idea is to do "can't reassign your references" then it makes sense (though not obvious from the readme). Also this is totally fine if that's what Airbnb decides to do... i'm just bringing this up to try and clarify my understanding.

I thought the purpose of `const` was to be able to quickly scan down the code and determine if that variable's value will be changed in that scope? Using `let` on an object that changes would obviously throw a warning in that case.

Do you know of a rule or plugin that will override and would prefer `let` if you're changing the value of the object/array? I'm not really sure where to start looking.

eg:

```javascript
const colors = {red: '#f00'};
colors.red = '#00f';   // >>> prefer let for variables that change
colors.green = '#0f0';
```

**Comment by nkbt** [comment]
@AdamBrodzinski easy, just never assign properties of your objects.

Instead use something like this:

```js
const colors = {red: '#f00'};
const newColors = {
  ...colors, 
  red: '#00f', 
  green: '#0f0'
};
```

For arrays: 
```js

const arr = [1,2,3];
const pushed = [...arr, 4];
const unshifted = [0, ...arr];
```
And other things like `.slice` or `.concat` are already immutable.

I can't see why anyone would want to modify property of the object or an item in the array unless in some very special cases of perf optimization (as the last step, since it would hardly be a perf bottleneck in the first place)

And for more advanced usage there are libs like `ImmutableJS`.

PS: I'd love to see an eslint rule to disallow property reassign for `const` (well, and `let` too) objects or arrays.

**Comment by justjake** [comment]
@AdamBrodzinski I think it's easier to learn what the language means by `const` than to create a linting infrastructure that understands `const` to mean something different. I think you might be able to write your own eslint rule for this; I suggest looking at the rules that forbid using certain things (like the no-eval rule, or the no-window-stuff rules) some of which look at how things are reassigned in the scope.

sorry I can't help more =/

**Comment by gajus** [comment]
Babel-eslint has it.

**Comment by nkbt** [comment]
@gajus thanks, I'll have a look, that would be really handy.

**Comment by AdamBrodzinski** [comment]
@nkbt Yea that's a good point... using the spread syntax makes it trivial to copy the data over.
@justjake also a good point I guess I just need to get used to it... feels kind of dirty to modify a `const` :laughing: 
@gajus thanks i'll check it out!

Thanks guys much appreciated!
