### ISSUE TITLE
Request for more clarity on the specific reasons generators are discouraged

### ISSUE THREAD

**Issue by chadaustin** [airbnb/javascript#487]
"They don't transpile well".  Does that mean correctly?  Performance?  Code size?

I know this is Airbnb's guide, but given it appears to be the most popular ES6 style guide, more details could help other people make their own correct decisions.

**Comment by justjake** [comment]
@goatslacker want to handle this one?

**Comment by goatslacker** [comment]
Mostly code size. Regenerator runtime is required if you're using babel. Regenerator isn't bad, it's actually great (it also does async/await which I love) it's just that it's an extra bit of code that you have to ship.

Consider [this simple example](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=true&code=function%20*x()%20%7B%0A%20%20yield%202%0A%7D). It's a lot of code for something really small.

Then there's the actual usefulness of generators...

Bear in mind, when our style guide says "don't do X" it doesn't mean it's forever forbidden, rather you should strive not to do X unless there's a really good reason to do so.

...so generators are mostly useful for writing async code. A library like [koa](https://github.com/koajs/koa) makes extensive use of them. While generators are pretty nice over callbacks I do believe [async/await](https://github.com/tc39/ecmascript-asyncawait) is a way better developer experience. So if you're not using generators to write async code then that just leaves other things like writing lazy evaluating infinite lists.

And, if you're writing a lazy eval library I think you can coax better performance out of it if you avoid generators. Plus you'll likely end up with a better (subjectively), more functional (as in functional programming), API.

**Comment by hshoff** [comment]
@goatslacker we should link saying "more info" to your comment at https://github.com/airbnb/javascript#11.2

**Comment by chadaustin** [comment]
Thanks, @goatslacker!  100% agreed with @hshoff that it's worth linking to that comment in the guidelines. :)
