### ISSUE TITLE
Sometimes there is a requirement to use _this

### ISSUE THREAD

**Issue by softwarespot** [airbnb/javascript#493]
In the ES5 document it mentions using _this, but in ES6 it states () => {};. Surely there are occasions where _this is required? I use it sporadically of course, but I use it still.

**Comment by ljharb** [comment]
Can you think of one? I can't.

**Comment by softwarespot** [comment]
This (pardon the pun) maybe...

```javascript
App = {
    init: function () {
        // Init
        this.cacheDom(); // OK
    },
    cacheDom: function () {
        // Cache DOM
    },
    render: {
        page1: function () {
            // Need to re-cache DOM nodes
            // this.cacheDom(); // Doesn't work as this is referencing render.

            var _this = App.render;
            _this.cacheDom(); // This works
        },
        page2: function () {

        },
        page3: function () {

        }
    }
}
```

**Comment by ljharb** [comment]
In that scenario, `App.render.cacheDom()` works just fine. Using `_this` or `self` is for when you need to capture `this` for use in a closure - that doesn't apply to your scenario.

**Comment by softwarespot** [comment]
Fair point. I can't really think of a concrete scenario right now (checked my code and seems I don't use it apart from what I mentioned above.) Thanks
