### ISSUE TITLE
Include the rationale behind the rules, if there is one.

### ISSUE THREAD

**Issue by jwietelmann** [airbnb/javascript#495]
I realize that in some cases you may just have a stylistic preference ("We think this is more readable") and that in others, there is an objectively good reason for the rule that guards against programmers doing stupid things. But reading this guide does not illuminate that. For example, when I see "Wrap JSX tags in parentheses when they span more than one line" I'm not sure if that's just someone at AirBnB's style opinion or if there's a more objective reason.

So for everyone else in the world, it would be really nice to understand your reasons as we compare our own style rules to yours.

**Comment by goatslacker** [comment]
#269
