### ISSUE TITLE
ES5 settings for eslint

### ISSUE THREAD

**Issue by honzajavorek** [airbnb/javascript#496]
There seem to be ES5 rules for `eslint` created by someone else: https://github.com/1hella/eslint-config-airbnb-es5 Wouldn't it be worth to merge these two projects and provide ES5 configuration out of the box the same way as the one for ES6 is?

**Comment by ljharb** [comment]
@honzajavorek https://www.npmjs.com/package/eslint-config-airbnb-base - `"extends": "airbnb/base"`. If this doesn't suffice, please file specific issues and I'll be happy to address them.

@1hella: if you'd like to merge your project into ours, please file issues/PRs as needed.

**Comment by gaboesquivel** [comment]
@ljharb  I'm trying to setup ES5 for an angular 1.x client in our project, we use ES6 on the backend. 
however it doesn't seem to work out-of-the-box, specifically I'm seeing prefer arrow functions errors.
It would be nice if I could extend ES5 explicitly. I had to use `eslint-config-airbnb-es5` since I didn't want to do rule overwrites.

**Comment by ljharb** [comment]
We recommend using Babel and writing ES6. That said, I'd accept a PR that exposed an `es5` entry point to obviate the need for `eslint-config-airbnb-es5`.

**Comment by gaboesquivel** [comment]
got it, thanks

**Comment by shreyas-a** [comment]
I'm trying to use airbnb/legacy, but it fails to find the errors while airbnb/base works.

**Comment by brownieboy** [comment]
airbnb/base flagged my ES5 code with `no-var` errors, i.e. I have to use `let` and `const` instead of `var`.   But `let` and `const` are ES6 not ES5!!

So I've gone with eslint-config-airbnb-es5 too.

**Comment by ljharb** [comment]
@brownieboy please file a new issue, and i can update the legacy entry point to disable `no-var`.
