### ISSUE TITLE
Blank lines between definitions in a class?

### ISSUE THREAD

**Issue by jacobp100** [airbnb/javascript#503]
```js
class Foo {
  constructor() {
    super();
  }
  bar() {
    return 'baz';
  }
}
```

Should there be a blank line between the end of `constructor` and `bar`?

**Comment by tomekwi** [comment]
See [8.7](https://github.com/airbnb/javascript/tree/24dc126e4b11bb60d053fc6c93598488b9bf0455#18.7).
