### ISSUE TITLE
Can iterators be pretty and immutable?

### ISSUE THREAD

**Issue by tomekwi** [airbnb/javascript#504]
I hope to start a discussion about [11.1](https://github.com/airbnb/javascript/tree/24dc126e4b11bb60d053fc6c93598488b9bf0455#11.1).

I bet you know *[trine](https://github.com/jussi-kalliokoski/trine)*. The whole concept of the lib is based on iterators – to have a unified set of functions working with any sort of collection. It looks very elegant and “native” to JS:

```js
const characters = strings
    ::map(String.prototype.split::partial(""))
    ::reduce(Array.prototype.concat)
    .sort()
    ::uniq();
```

:+1: Using iterators this way doesn’t involve managing state, except when writing the utilies.

:+1: There’s no risk of mutating stuff. Every function is returns a new iterator.

:+1: One more bonus – the thing is lazy. So you can map over infinite collections, etc. Lots of functional programming goodness.

:-1: There’s one “but”. Working with iterators in such an elegant way is only possible with the [function bind syntax](https://github.com/zenparsing/es-function-bind). And that doesn’t come into the spec until ES 2016 (if at all). They do transpile cleanly to ES5 with babel though.

**Comment by goatslacker** [comment]
We don't use trine and have no plans to use trine in the near future.

But :+1: to trine in general IMO.

**Comment by ljharb** [comment]
For now, given our non-use of trine, and the function bind syntax's stage 0 status, I'm going to close this.

As either of these changes, we can re-evaluate this section.
