### ISSUE TITLE
No max-len ESLint rule?

### ISSUE THREAD

**Issue by screendriver** [airbnb/javascript#509]
Is there a reason why there is no [max-len](http://eslint.org/docs/rules/max-len) rule present in your [rules](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/base/index.js)?

**Comment by justjake** [comment]
Nope! Submit a PR and I'll merge it.

**Comment by screendriver** [comment]
With pleasure :sunglasses:

**Comment by pitaj** [comment]
Should this be closed since #639 defined it?

**Comment by ljharb** [comment]
Thanks, closed with #639.
