### ISSUE TITLE
Hyper Oslo using your style guide

### ISSUE THREAD

**Issue by sindrenm** [airbnb/javascript#512]
Hey guys,

The devs here at Hyper in Oslo, Norway love your style guide. Even though we didn't fork it (like normal people), we have a document based off of it here:

https://github.com/hyperoslo/javascript-playbook/blob/master/style.md

So thank you guys so much for putting this together, and if you feel like adding us to that list of yours then you're more than welcome!

**Comment by goatslacker** [comment]
Create a PR adding it to the list.

**Comment by sindrenm** [comment]
Thanks. Have a look ta #516. :smiley:
