### ISSUE TITLE
'id-length' is invalid

### ISSUE THREAD

**Issue by ariporad** [airbnb/javascript#515]
Hi,

I cloned this repo and (installed the dependencies, and) ran `npm run lint`, and I'm getting this error:

> /Users/Ari/Developer/airbnb-js-style/packages/eslint-config-airbnb/node_modules/eslint/lib/config.js:141
>                     throw e;
>                     ^
>
> Error: eslint-config-airbnb:
> 	Configuration for rule "id-length" is invalid:
> 	Value "data["1"].properties" has additional properties.
> 
> Referenced from: /Users/Ari/Developer/airbnb-js-style/packages/eslint-config-airbnb/.eslintrc
>     at validateRuleOptions (/Users/Ari/Developer/airbnb-js-style/packages/eslint-config-airbnb/node_modules/eslint/lib/config-validator.js:88:15)
>     at /Users/Ari/Developer/airbnb-js-style/packages/eslint-config-airbnb/node_modules/eslint/lib/config-validator.js:101:13
>     at Array.forEach (native)
>     at Object.validate (/Users/Ari/Developer/airbnb-js-style/packages/eslint-config-airbnb/node_modules/eslint/lib/config-validator.js: 100:35)
>     at loadConfig (/Users/Ari/Developer/airbnb-js-style/packages/eslint-config-airbnb/node_modules/eslint/lib/config.js:107:19)
>     at /Users/Ari/Developer/airbnb-js-style/packages/eslint-config-airbnb/node_modules/eslint/lib/config.js:135:46
>     at Array.reduceRight (native)
>     at loadConfig (/Users/Ari/Developer/airbnb-js-style/packages/eslint-config-airbnb/node_modules/eslint/lib/config.js:119:36)
>     at getLocalConfig (/Users/Ari/Developer/airbnb-js-style/packages/eslint-config-airbnb/node_modules/eslint/lib/config.js:243:23)
>     at Config.getConfig (/Users/Ari/Developer/airbnb-js-style/packages/eslint-config-airbnb/node_modules/eslint/lib/config.js:371:22)

I'm not sure what's causing it. I've just spend the past hour debugging it.

**Comment by ljharb** [comment]
Looks like we need to bump `eslint` up to at least `1.3.0` - the version in which the "properties" option was added to `id-length`.

For now, `npm install eslint@1.3.x` should fix it for you locally.

**Comment by ariporad** [comment]
I'll send pr when I get home in a few hours 



Thanks!Ari
