### ISSUE TITLE
callback && callback();

### ISSUE THREAD

**Issue by Znarkus** [airbnb/javascript#52]
Was reading through the style guide, but couldn't find anything about this. Instead of

```
var callback;

if (callback) {
    callback();
}
```

I've started using

```
var callback;

callback && callback();
```

Which I haven't found any issues with. Would this style guide frown upon this?

**Comment by yisibl** [comment]
What about `callback?.()`

**Comment by ljharb** [comment]
@yisibl thats equivalent to `if (callback != null) { callback(); }`, so that’d be fine (once eslint supports parsing that syntax, and once this guide permits it)
