### ISSUE TITLE
Possible typo at #21.3

### ISSUE THREAD

**Issue by DannyNemer** [airbnb/javascript#523]
At item [21.3](https://github.com/airbnb/javascript#21.3), the guide reads:
> Use `parseInt` for Numbers and always with a radix for type casting.

However, the example displays:
```javascript
// good
const val = Number(inputValue);

// good
const val = parseInt(inputValue, 10);
```
**Question**: Is the first of the above examples supposed to be `// bad` (not `// good`), or should the guide read "Use `parseInt` **or `Number`** for Numbers..."?

Thank you.

**Comment by ljharb** [comment]
`parseInt` is only meant to take a `String`, and will also discard non-number characters - ie, `parseInt('3a', 10)` will be `3`, but `Number('3a')` will be `NaN` - so they're slightly different there. `Number` is also the proper way to coerce non-string values to numbers.

My guess is that the wording should be changed to encourage proper usage of both.

**Comment by DannyNemer** [comment]
Thank you for your response. I agree and opened a pull request to address this: #524.
