### ISSUE TITLE
Strict mode rule in ESLint

### ISSUE THREAD

**Issue by feimosi** [airbnb/javascript#529]
Either I'm missing something out or there's a typo in:
https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/strict.js#L3-L4
Why would we forbid using the strict mode? The comment says something completely different, so shouldn't there be a `function` value?

**Comment by ljharb** [comment]
The comment used to say `"// babel inserts 'use strict'; for us"` prior to https://github.com/airbnb/javascript/commit/daea8a638f1f42cd609f1b68b748ad323be31c10#diff-5d49d135b1d778d63733bd8e19f485c9L29 - seems like perhaps we just need to fix the comment. @taion?

**Comment by taion** [comment]
Yeah, I just copied over the comment from `eslint-config-defaults` instead of re-using the old comment there. I didn't realize that their comment there was so confusing, though.

**Comment by feimosi** [comment]
OK, now I see, thanks.
