### ISSUE TITLE
Turn on no-mixed-spaces-and-tabs`

### ISSUE THREAD

**Issue by mattdipasquale** [airbnb/javascript#539]
If you want to "*disallow* mixed spaces and tabs for indentation", then the line should be:

        no-mixed-spaces-and-tabs: [2, false],

Line: https://github.com/airbnb/javascript/blob/16f81fbb25ae9aced9b647da5aea1dbcbf9a85e3/packages/eslint-config-airbnb/rules/style.js#L52

Documentation: http://eslint.org/docs/rules/no-mixed-spaces-and-tabs.html

Example: https://github.com/eslint/eslint/blob/master/.eslintrc#L46

**Comment by mattdipasquale** [comment]
Hmm... I think I've gotten confused by the comment. Is the comment explaining what the line is doing or what the rule does when turned on?

**Comment by ljharb** [comment]
The comment is explaining what the rule does when turned on.

That said, I think this should be turned on, as "smart tabs" are gross, and we don't use tabs at airbnb anyways. A PR is welcome.
