### ISSUE TITLE
Unused local variable in react render

### ISSUE THREAD

**Issue by ggarek** [airbnb/javascript#543]
Hello, recently i found a use case when unused local variable could be allowed.

The use case:
I need to omit some own props in React component render method, because i want to pass the rest of the props to other component (e.g. own child).
The *prop1, prop2, prop3 are used* in components handlers and thus they are not used in render.
I want to leverage es6 destructuring assignment to omit some keys and get the rest props packed in a newly created object. Thus the omited props appear as unused local variables. This makes ESLint sad.

I could use something like `_.omit(this.props, [ 'prop1', 'prop2', 'prop3' ])`, but why not use the almost native es6 ability? 
The other option would be to allow unused variables in React component render method if the destructuring assignment contains `...rest`.

Here is a code sampe:

```
render() {
    const {
      prop1,
      prop2,
      prop3,
      ...restProps
      } = this.props;

    return (
      <OneComponent>
        <OtherComponent {...restProps}/>
      </OneComponent>
    );
  }
```

What could you suggest regarding the use case?

**Comment by ljharb** [comment]
Object rest/spread syntax is an ECMAScript proposal, and is not part of ES6/2015. At Airbnb, we currently only use syntax that is in a published spec.

Once this syntax is finalized and part of a published spec, many of us do think it does make sense to allow unused object destructuring properties when a rest property is present - we'll have to address that at that time.

**Comment by ggarek** [comment]
Thanks for the explanation. This makes sense. :+1: 

[There is no rest element in an object assignment pattern in ecma-262 indeed.](http://www.ecma-international.org/ecma-262/6.0/#sec-destructuring-assignment)
