### ISSUE TITLE
consistent-return and promises

### ISSUE THREAD

**Issue by olalonde** [airbnb/javascript#548]
I kind of like the consistent-return rule except when using promises. I often find myself writing this style of code:

```javascript
const something = () => {
    return somePromise().then((someval) => {
      if (!someval) return;
      return someOtherPromise();
   });
};
```

What should I put as return value in the first return? `return null` fixes the

**Comment by ljharb** [comment]
`return null` or `return undefined` or `return Promise.resolve()` or `if (someval) { return someOtherPromise(); }` are all some options

**Comment by justjake** [comment]
I don't like consistent return and usually turn it off on a file by file basis, or across a project.

**Comment by graingert** [comment]
@ljharb `if (someval) { return someOtherPromise(); }` doesn't work, because there's an implicit return undefined, which is what this rule is trying to prevent.

**Comment by ljharb** [comment]
Ah, true. in that case, `return someval ? someOtherPromise() : Promise.resolve();` is probably ideal.
