### ISSUE TITLE
Space before left parenthesis in anonymous function literals

### ISSUE THREAD

**Issue by siclait** [airbnb/javascript#55]
From Crockford:

> If a function literal is anonymous, there should be one space between the word function and the ( (left parenthesis). If the space is omited, then it can appear that the function's name is function, which is an incorrect reading.

```javascript
div.onclick = function (e) {
  return false;
};

that = {
  method: function () {
    return this.datum;
  },
  datum: 0
};
```
Source: [Code Conventions for the JavaScript Programming Language](http://javascript.crockford.com/code.html)

**Comment by leizhao4** [comment]
I vote for the Crockford style. `function` is a keyword which should be followed by a space. Just like in `if ()`, `for ()` and `while ()`. I find `function()` as ugly as `if()`, `for()` and `while()`.

**Comment by matbhz** [comment]
I feel like `function` and `()` should be together because they are part of a same statement, such as a mathematics function `f(x)`.

The space in the middle of `if ()` suggest that something extra is going to be needed: they are different things which must in cooperation, whereas `function()` with no space is the whole thing by itself.

**Comment by leizhao4** [comment]
@matbhz I don't think it's a whole thing. The full expression syntax is `function [name]() {}` where function is a keyword meaning we are going to declare a function, followed by a space and an optional name, and a parameter list, and the function body. The function name is optional but I don't think the space should go away. Having a space in `function () {}` clearly shows that the function has no name.

The function name and `()` is a whole thing. But the `function` keyword is outside of it.

**Comment by goatslacker** [comment]
+1 to that @leizhao4

**Comment by ljharb** [comment]
+1 as well, `function [name](` ftw

**Comment by L2L2L** [comment]
I agree, and always follow.

**Comment by nathanbuchar** [comment]
:+1: @leizhao4

**Comment by mattdipasquale** [comment]
@leizhao4 you're a FUCKING GENIUS!!! https://youtu.be/tuhPPOXnyKo

**Comment by ljharb** [comment]
This is addressed [here](https://github.com/airbnb/javascript#7.11).

**Comment by nicoder** [comment]
should the ES5 examples be updated then ? (they currently use `function()`)

**Comment by ljharb** [comment]
@nicoder thanks, done in 1e1772b340702e55d0933997d5af733afb8c7584
