### ISSUE TITLE
Constructor using class statement - Browser doesn't allow it

### ISSUE THREAD

**Issue by joebien** [airbnb/javascript#550]
Can someone help me out. I'm trying to follow this suggestion for creating constructor. But firefox gives an error - 'SyntaxError: class is a reserved identifier'

Constructors
9.1 Always use class. Avoid manipulating prototype directly.

class Queue {
    constructor(contents = []) {
      this._queue = [...contents];
    }
    pop() {
      const value = this._queue[0];
      this._queue.splice(0, 1);
      return value;
    }
  }

**Comment by ljharb** [comment]
You can't use ES6 syntax reliably cross-browser. We use babel to transpile ES6 syntax.

"class" syntax isn't enabled yet in Firefox. http://kangax.github.io/compat-table/es6/ may be helpful here.

**Comment by joebien** [comment]
Ah. Thanks.
