### ISSUE TITLE
why disable `no-const-assign` in eslint es6 config?

### ISSUE THREAD

**Issue by rhbecker** [airbnb/javascript#559]
On [es6.js, line 35](https://github.com/airbnb/javascript/blame/master/packages/eslint-config-airbnb/rules/es6.js#L35), the [`no-const-assign`](http://eslint.org/docs/rules/no-const-assign.html) config is disabled, but reassigning a `const` seems like the sort of thing one would want to get warned about.

Is this on purpose? If so, can you explain the reasoning?

**Comment by tleunen** [comment]
Funny, I just had the same issue.
And the comment says "disallow", but in fact, with a value of 2. the rule allows the assignment for a const variable...
```
// disallow modifying variables that are declared using const
'no-const-assign': 0,
```

**Comment by rhbecker** [comment]
@tleunen: 2 isn't supposed to prevent you from using `const`, but rather considers *re*assignment to be an error. See the docs for examples: http://eslint.org/docs/rules/no-const-assign.html

Or maybe I'm misunderstanding your reply?

**Comment by tleunen** [comment]
Yep sorry, I was saying the assignment after the declaration of course ;)
so something like
```js
const myVar = 2;
myVar = 1;
```
Currently, because the rule is set as 0 in airbnb, it allows it but it should not allow that.

**Comment by ljharb** [comment]
This rule should definitely be enabled. There's no reason to ever allow reassigning to `const`.

A PR to fix this is quite welcome!

**Comment by yiconic** [comment]
when a var set as const it cant be change ....
