### ISSUE TITLE
Why is babel-eslint required?

### ISSUE THREAD

**Issue by nzakas** [airbnb/javascript#565]
ESLint supports all of ES6 plus the experimental object rest/spread that React uses. Is it possible to remove babel-eslint as a dependency? (It would make linting faster.)

**Comment by ljharb** [comment]
What version of eslint added support? We're still using a rather old version, and haven't yet had the time to upgrade.

**Comment by nzakas** [comment]
Support for what?

**Comment by ljharb** [comment]
> all of ES6 plus the experimental object rest/spread that React uses

**Comment by nzakas** [comment]
All of this has been supported since 1.0.0:
http://eslint.org/blog/2015/07/eslint-1.0.0-released/

**Comment by ljharb** [comment]
We're still on 0.24. As soon as we update past 1.0, we'll drop babel-eslint.

**Comment by nzakas** [comment]
:+1:

**Comment by taion** [comment]
@ljharb 

Do Airbnb not use e.g. ES7 extensions at all?

While ESLint might cover all of ES6, it doesn't seem to cover things like class properties and async/await (maybe just with arrow functions?) that people actually use.

**Comment by taion** [comment]
AKA my stuff all broke as soon as I upgraded to 1.0.0.

As an alternative, if you want to keep `babel-eslint` out of the core config, it might be nice to have an `airbnb/babel` (and just let users take care of installing `babel-eslint` themselves, which really with npm3 they'd have to do anwyay).

**Comment by ljharb** [comment]
@taion no, airbnb does not use any ES7 extensions at all - only things that are in the spec (stage 4 for post-ES6 stuff).

**Comment by taion** [comment]
Fair enough. Do you think an `airbnb/babel` would fit here?

**Comment by ljharb** [comment]
Since we don't use `babel-eslint` internally anymore, I'm not sure what the purpose would be - you can add it as a parser to your own `eslintrc` that extends our config, and you can define any rules you like in there?

**Comment by taion** [comment]
That's what I ended up doing - same ruleset, just needed ESLint to not choke on ES7 features (they weren't getting linted in any particularly interesting way anyway).

**Comment by iamstarkov** [comment]
so, is there any progress here?

**Comment by taion** [comment]
Nothing actionable here - just add the parser setup to your own `.eslintrc`. Easy enough.

**Comment by iamstarkov** [comment]
got it, thank you
