### ISSUE TITLE
0.1.1 on npm?

### ISSUE THREAD

**Issue by tleunen** [airbnb/javascript#571]
Could you please publish 0.1.1 on npm? :)
Thanks!

**Comment by taion** [comment]
:+1: want to get rid of my override to disable `id-length` :laughing:

**Comment by ljharb** [comment]
I'll be publishing `v1.0.0` soon which requires `eslint` `v1.0` and higher, and includes this fix.

**Comment by ljharb** [comment]
Actually, `v0.1.1` already existed as a tag - I've just published that.
