### ISSUE TITLE
MEAN STACK DEVELOPER - AI TECH FIRM - NYC TOP DOLLAR - FULL TIME - AWS & NLP

### ISSUE THREAD

**Issue by alexgutterson** [airbnb/javascript#585]
A client of mine is looking for exceptional engineers who specialize in the MEAN stack. They are located in midtown NYC and can pay top dollar. The firm is focused on AI/NLP and is looking for a strong foundation with both MEAN and AWS. Python and Java are plus skills.

If anyone is interested in hearing more, or would know someone that could possibly be interested you can reach me directly via email or over the phone. Otherwise don't hesitate to respond via GitHub.

Cheers!
Alex

Alexander Gutterson
CEO/Founder
Jay Alexander LLC
(E) Alex@jAlexanderLLC.com
(T) 646-979-0709 (feel free to text)

**Comment by ljharb** [comment]
It is highly inappropriate and not appreciated to post recruitment spam on our style guide.
