### ISSUE TITLE
airbnb eslint presets, which require all required presets inside them 

### ISSUE THREAD

**Issue by iamstarkov** [airbnb/javascript#588]
eslint add possibility for presets to have all required deps with them in [1.10](http://eslint.org/blog/2015/11/eslint-v1.10.0-released/). See eslint issues eslint/eslint#4407 and eslint/eslint#4263 so basically it should be possible to do short `npm install --save-dev eslint-config-airbnb eslint` instead of long and verbose `npm install --save-dev eslint-config-airbnb eslint-plugin-react eslint`. I think it’s easier and more cleaner approach.

I [tried this feature on small eslint presets](https://github.com/iamstarkov/eslint-test#readme) and it seems to be working. What do you think about implementing this way into airbnb presets?

**Comment by ljharb** [comment]
Can you elaborate on this? Reading the eslint issues, it seems like they simply fixed an "extends" bug such that this isn't a problem anymore.

**Comment by justjake** [comment]
Seems like a good idea @iamstarkov - but our current strategy allows one to install `eslint-config-airbnb` and use only the ES5 stuff if you don't want the react deps. Which is more important - lighter install weight, or reduced doc reading and install verbosity?

**Comment by kesne** [comment]
Would the install weight really matter that much? These should just be dev dependencies.

**Comment by iamstarkov** [comment]
btw, we dont need babel-eslint here, because es2015+ already can be handled by eslint itself (see https://github.com/airbnb/javascript/issues/565)

**Comment by iamstarkov** [comment]
> our current strategy allows one to install eslint-config-airbnb and use only the ES5 stuff if you don't want the react deps. Which is more important - lighter install weight, or reduced doc reading and install verbosity?

maybe then this thing should be exported to separate `eslint-condfig-airbnbn-base`

**Comment by iamstarkov** [comment]
but i get your point

**Comment by iamstarkov** [comment]
> install eslint-config-airbnb and use only the ES5 stuff if you don't want the react deps

so one, who wants only to lint es5 code will get also `/base`. and one who wants to lint `es6` code will also get `/legacy`. So its still a bit overloaded in terms of install weight and time

**Comment by iamstarkov** [comment]
what about splitting in three packages?

* `/base` will become `eslint-config-airbnb`
* `/legacy` will become `eslint-config-airbnb-legacy`
* `eslint` will become `eslint-config-airbnb-react`, extended by `eslint-config-airbnb` with `eslint-plugin-react` in deps. (not sure eslint will pickup `eslint-plugin-react` from here, but it should)

**Comment by iamstarkov** [comment]
> btw, we dont need babel-eslint here, because es2015+ already can be handled by eslint itself (see #565)

I mean its still in [readme](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb)

**Comment by iamstarkov** [comment]
no, its not. sorry, will remove related comments

**Comment by iamstarkov** [comment]
> Can you elaborate on this? Reading the eslint issues, it seems like they simply fixed an "extends" bug such that this isn't a problem anymore.

yep, @nzakas did it

**Comment by nzakas** [comment]
> eslint add possibility for presets to have all required deps with them in 1.10. 

First, let's define terms. What you're talking about is a shareable config, not a preset. Second, this isn't strictly true. What we did was fix an issue where `extends` for local filenames is calculated from the config file rather than the current working directory. You can only have a shareable cutting depend on another shareable config if you reference the local file path or if the second shareable config is installed as a peer of the first. 

Plugins are a completely different story and will not work unless they are installed as a peer dependency of ESLint.

We are still investigating strategies for allowing you to directly create dependencies for shareable configs.

**Comment by iamstarkov** [comment]
@ljharb @justjake whats your opinions about:

> * `/base` will become `eslint-config-airbnb` with removed `/legacy` inside
* `/legacy` will become `eslint-config-airbnb-legacy`
* `eslint` will become `eslint-config-airbnb-react`, extended by `eslint-config-airbnb` with `eslint-plugin-react` in deps. (not sure eslint will pickup `eslint-plugin-react` from here, but it should)  
> —[from comment above](https://github.com/airbnb/javascript/issues/588#issuecomment-159456784)

**Comment by iamstarkov** [comment]
this issue hurts me every time i want to use eslint-config-airbnb

**Comment by iamstarkov** [comment]
it didnt shipped with v3?

**Comment by ljharb** [comment]
Whatever was in master shipped with v3 - I don't think this has been worked on yet.

**Comment by ljharb** [comment]
https://www.npmjs.com/package/eslint-config-airbnb-base now exists, so you don't need the extra deps for "base".

`eslint` still requires that plugins be explicitly installed at the top level, so there's no solution beyond continuing to spin out separate packages, and continuing to need to install peer deps manually.

**Comment by iamstarkov** [comment]
@ljharb thank you for your work here

**Comment by iamstarkov** [comment]
i still a bit struggling about react plugin required for my non-react projects. @ljharb would you mind if I create another issue to discuss it?
