### ISSUE TITLE
eslint throwing wrong error on `react/sort-comp`

### ISSUE THREAD

**Issue by hawsome** [airbnb/javascript#595]
![screen shot 2015-11-30 at 3 33 45 pm](https://cloud.githubusercontent.com/assets/567126/11487973/e0427094-9777-11e5-82a6-1373b372205d.png)

Why you do dis?

This follows correct ordering of handlers here: https://github.com/airbnb/javascript/tree/master/react#ordering

**Comment by hshoff** [comment]
Hey @hawsome thanks for checking out the guide. Looks like there's a stray capital `L` at the end of `Will`. So it's not matching `componentWillMount` which won't throw an error with your order.

**Comment by Aweary** [comment]
@hshoff I'm seeing this error with two methods that I have that aren't part of the component lifecycle.
<img width="745" alt="screen shot 2015-12-04 at 9 24 57 am" src="https://cloud.githubusercontent.com/assets/6886061/11593260/f4055db4-9a68-11e5-80c0-10cb6717c497.png">
But `submitPendingFilter` **does** come before `renderMobileFilter`
<img width="629" alt="screen shot 2015-12-04 at 9 25 10 am" src="https://cloud.githubusercontent.com/assets/6886061/11593281/0c19603a-9a69-11e5-943e-3868c8beb647.png">

**Comment by ljharb** [comment]
@Aweary That's using class properties, which Airbnb doesn't yet use (because they're still at an early stage in the proposal process), so it's likely the rule isn't compatible with them.
