### ISSUE TITLE
Why don't we have Promises in the style guide?

### ISSUE THREAD

**Issue by goatslacker** [airbnb/javascript#597]
This seems like something that should be written about.

**Comment by ljharb** [comment]
I `Promise` that we will!

**Comment by goatslacker** [comment]
I will cheerfully `await` this.

**Comment by hshoff** [comment]
How did we not `catch` this earlier?

**Comment by goatslacker** [comment]
It silently fell through.

**Comment by ljharb** [comment]
It might have been a `.race` condition

**Comment by gergoerdosi** [comment]
https://github.com/airbnb/javascript/issues/216

**Comment by ljharb** [comment]
@gergoerdosi Thanks! We'll resolve both issues soon.

**Comment by ljharb** [comment]
Closing in favor of #216.
