### ISSUE TITLE
Peer Dependencies

### ISSUE THREAD

**Issue by saponifi3d** [airbnb/javascript#603]
Peer dependencies are being deprecated in NPM v3, can you please remove the peer dependency and just make `eslint-config-airbnb` use `eslint` as a normal dependency or whatever.

**Comment by ljharb** [comment]
Peer dependencies are not deprecated in npm 3 (which is already out), they just aren't installed by default. Currently, you need to add `eslint` as a dependency to your own project.

**Comment by saponifi3d** [comment]
thanks for the super fast response, and okay. i guess i'm a bit sad, because i don't actually have a dependency on `eslint` since i'm using `gulp-eslint`, so it feels a little weird that i have to have both.
