### ISSUE TITLE
Cannot override the `space-in-parens` rule

### ISSUE THREAD

**Issue by AvraamMavridis** [airbnb/javascript#611]
I am using the airbnb eslint rules, but I can not override the `space-in-parens`  rule, any idea? 

This is my file

```js
module.exports = {
    "extends": "airbnb",
    "rules":{
        "space-before-function-paren": 2,
        "space-in-parens": [2, "always"],
    },
    "plugins": [
        "react"
    ]
};
```

**Comment by ljharb** [comment]
Hmm, that should definitely work - you may want to file an `eslint` issue?

**Comment by AvraamMavridis** [comment]
Yap, I will do that

**Comment by ljharb** [comment]
Closing this for now - please follow up if it turns out to be an eslint bug.
