### ISSUE TITLE
Stance on React 0.14 stateless function components

### ISSUE THREAD

**Issue by jaroslawr** [airbnb/javascript#612]
The React part of the coding standard, with its insistence of using classes for components, when read literally seems to be prohibiting the now officially recommended stateless function components:

```
var Aquarium = ({species}) => (
  <Tank>
    {getFish(species)}
  </Tank>
);
```

https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html

I guess this was just written before React 0.14. Any chances of taking some more explicit stance on those in the coding standard?

**Comment by goatslacker** [comment]
We don't use React 0.14 just quite yet so we don't have a stance on it.

If you're just looking for opinions then I believe that stateless function components should make up a vast majority of your components therefore I'd use those over `React.createClass` and `extends React.Component`.

**Comment by justjake** [comment]
I agree with @goatslacker - stateless functional components are fantastic, and once we upgrade to 0.14 we'll upgrade our styleguide to extol their virtues.

**Comment by jacobrask** [comment]
Maybe the linter could even suggest to use a stateless functional component if no lifecycle methods or component state is used?

**Comment by goatslacker** [comment]
Can't we close this? Is there more work that needs to be done here?

@jacobrask that seems like a feature request for eslint-react

**Comment by ljharb** [comment]
I think #575 clarifies our stance.

I filed https://github.com/yannickcr/eslint-plugin-react/issues/405 for that feature request. We'll also need https://github.com/yannickcr/eslint-plugin-react/issues/357 and https://github.com/yannickcr/eslint-plugin-react/issues/354.

**Comment by ljharb** [comment]
Linking to https://github.com/yannickcr/eslint-plugin-react/issues/214 instead of https://github.com/yannickcr/eslint-plugin-react/issues/405
