### ISSUE TITLE
Grammar mistake in 3.4 block

### ISSUE THREAD

**Issue by yuanwang33** [airbnb/javascript#614]
#### a grammar mistake in 3.4 block

- [3.4](#3.4) <a name='3.4'></a> Use computed property names when creating objects with dynamic property names.

  > Why? They allow you to define all the properties of an object in one place.

    ```javascript

    function getKey(k) {
      return `a key named ${k}`;
    }

    // bad
    const obj = {
      id: 5,
      name: 'San Francisco',
    };
    obj[getKey('enabled')] = true;

    // good
    const obj = {
      id: 5,
      name: 'San Francisco',
      [getKey('enabled')]: true,
    };
    ```
##### the square brackets around "getKey('enabled')" in the second last line should be removed.

**Comment by ljharb** [comment]
@yuanwang33 if they're removed, it would be a syntax error. computed properties require the square brackets to explicitly indicate it's a computed property.

If you try the "good" example in a REPL or console with the brackets removed, you'll see the error.
