### ISSUE TITLE
Recommended import grouping and order?

### ISSUE THREAD

**Issue by mhahn** [airbnb/javascript#616]
Is there a recommended import grouping and order for es6 modules?

python has some specifications in PEP as well as some logical extensions: https://code.google.com/p/soc/wiki/PythonStyleGuide#Imports_grouping_and_order

given that es6 imports are reversed, ie instead of:

`from <module> import <function>` (python)
its 
`import <function> from <module>`

sorting by module isn't as intuitive

**Comment by ljharb** [comment]
What are the reasons you think ordering matters?

Typically we tend to group external deps first, then relative imports, but beyond that, no particular ordering. If I had to pick, I'd say alphabetical (within "external" and "relative").

**Comment by mhahn** [comment]
its mostly because i write more python than js and am used to alphabetically sorting within groupings (as specified in the google python style guide).

i do think its easier to quickly parse whats being imported/avoid duplicate imports if it has some logical order.

**Comment by goatslacker** [comment]
We don't have a concrete opinion on ordering. Alpha, external, whatever are all good though.

**Comment by benknight** [comment]
I agree with @mhahn, perhaps because I've also spent a lot of time writing Python according to PEP8 standards.

Import ordering matters because:

1. Code consistency. Broken windows theory.
1. Easier to to visually scan and see dups.

It's the same argument for any code style guideline, so the argument that it "doesn't matter" isn't really valid.

**Comment by ljharb** [comment]
There's already an eslint rule in our config that prevents dupes, so there's no need for a human to ever worry about that anymore.
