### ISSUE TITLE
object-shorthand rule should be enabled

### ISSUE THREAD

**Issue by amageed** [airbnb/javascript#621]
It seems that the object-shorthand rule is incorrectly disabled.

Per the guidelines, object-shorthand is recommended, specifically under [object method shorthand](https://github.com/airbnb/javascript#3.5) and [property value shorthand](https://github.com/airbnb/javascript#3.6).

Also, the comment in [`eslint-config-airbnb/rules/es6.js`](https://github.com/airbnb/javascript/blob/28a83da1d11a200014c7d33abf95b5b1bbf7b604/packages/eslint-config-airbnb/rules/es6.js#L42-L43) indicates that it's a requirement, however the rule is set to 0 (disabled):

```js
    // require method and property shorthand syntax for object literals
    'object-shorthand': 0,
```

This should be changed to:

```js
    // require method and property shorthand syntax for object literals
    'object-shorthand': 2,
```

Thanks!

**Comment by ljharb** [comment]
Thanks, good catch!
