### ISSUE TITLE
21.3 Numbers

### ISSUE THREAD

**Issue by cawa-93** [airbnb/javascript#623]
A little test:
```javascript
(function(num) {
	"use strict";
	console.time('minus zero');
    for (let i = 0; i < 10000000; i++) {
        let a = num - 0;
    }
	console.timeEnd('minus zero');


	console.time('Number');
    for (let i = 0; i < 10000000; i++) {
        let a = Number(num);
    }
	console.timeEnd('Number');


	console.time('parseInt');
    for (let i = 0; i < 10000000; i++) {
        let a = parseInt(num, 10);
    }
	console.timeEnd('parseInt');

})('5457885654');
```
gives the following result:
```
minus zero: 1777.696ms
Number: 4624.230ms
parseInt: 4289.564ms
```
If you use the not a number:
```javascript
(function(num) {
	"use strict";
	console.time('minus zero');
    for (let i = 0; i < 10000000; i++) {
        let a = num - 0;
    }
	console.timeEnd('minus zero');


	console.time('Number');
    for (let i = 0; i < 10000000; i++) {
        let a = Number(num);
    }
	console.timeEnd('Number');


	console.time('parseInt');
    for (let i = 0; i < 10000000; i++) {
        let a = parseInt(num, 10);
    }
	console.timeEnd('parseInt');

})('some text');
```
gives the following result:
```
minus zero: 601.545ms
Number: 3379.065ms
parseInt: 3813.081ms
```
This demonstrates that the use of "Number()" is not the fastest method.

**Comment by ljharb** [comment]
First, performance is the last thing one should be concerned about when writing code — it's often easy to speed up clean code, it's often hard to clean up fast code.

Second, microperformance tests like this are both not representative of real-world application performance, and highly specific to the engine you're running them on - actual JIT optimizations are unpredictable. (Also, you haven't tested the truly equivalent construct to `Number(foo)`, which is `+foo`, and is likely very fast)

Finally, as your own tests show, unless you're synchronously coercing millions of values to a number, you aren't going to notice a speed difference.

Thanks for your input!
