### ISSUE TITLE
no-param-reassign with props

### ISSUE THREAD

**Issue by growlsworth** [airbnb/javascript#626]
Hey AirBnB,
What are your thoughts about preventing object manipulation on params as well:
http://eslint.org/docs/rules/no-param-reassign.html. I know I'm surprised when I pass an object to a function and the function manipulates the object.

The [current value](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/best-practices.js#L77) is set to `2`. What do you think about changing it to `[2, { "props": true }]`?

Thanks!

**Comment by ljharb** [comment]
I think absolutely this should be turned on - I wasn't aware that was even an option.

A PR that updates the README, and updates the lint rule (including linking to the rule docs), would be very welcome.

**Comment by growlsworth** [comment]
Sweet. Will do it.

**Comment by growlsworth** [comment]
closed via #627

**Comment by EvanCarroll** [comment]
This is silly. At least for the reason give because you're not preventing object manipulation with this. In fact, you're just obstructing it to silence the linter.

```javascript
var o = {f:1};
var f = (o)=> {let a=o; a.g=2};
f(o);
console.log(o.g);
```

This is going to print 2, and not generate any errors in the linter. If you're doing it for this reason, I'd *highly* suggest you reverse this patch.

**Comment by ljharb** [comment]
@EvanCarroll You are welcome to disable the rule in your own codebase if you don't like it. I [commented](https://github.com/eslint/eslint/issues/5306#issuecomment-184869856) a bit more on your eslint issue about why this is important.
