### ISSUE TITLE
Broken Hyperlinks on webpage.

### ISSUE THREAD

**Issue by josisusan** [airbnb/javascript#628]
Hi,
Hyperlinks for ES5 and React listed under Other Style Guides are broken on http://airbnb.io/javascript/

**Comment by ljharb** [comment]
We use the automatic github pages generator, and it doesn't seem to support nested READMEs.

We're pretty likely to just remove that page and redirect people directly to the github repo, since that's what's most up to date.

**Comment by hshoff** [comment]
@josisusan thanks for the heads up! That was my fault for not updating the page. Links should work now.

:beers:

**Comment by josisusan** [comment]
:+1:  :bow:
