### ISSUE TITLE
Alignment of closing bracket of opening tag for components with multi-line properties and children

### ISSUE THREAD

**Issue by lencioni** [airbnb/javascript#630]
The style guide has an example of de-indenting the closing bracket of the opening tag for components with multi-line properties and children:

```jsx
// children get indented normally
<Foo
  superLongParam="bar"
  anotherSuperLongParam="baz"
>
  <Spazz />
</Foo>
```

However, it does not list any reasoning for this, so I wonder if it is arbitrary. I'd like to propose adjusting the alignment of the closing bracket of the opening tag for these components so that they line up with the props instead of the opening bracket. Example:

```jsx
// children get indented normally
<Foo
  superLongParam="bar"
  anotherSuperLongParam="baz"
  >
  <Spazz />
</Foo>
```

I think this is better for 2 reasons:

1. This is really minor, but since children are props, it makes sense for them to be visually grouped with the rest of the props.
2. More importantly, this style makes it easier to see how components are nested ([as I mentioned in my proposal for this rule](https://github.com/yannickcr/eslint-plugin-react/issues/64#issuecomment-157767905)). e.g.:

```jsx
<MyComponent
  myProp="..."
  >
  <MyComponent
    myProp="..."
    >
    <MyComponent
      myProp="..."
      >
      Children
    </MyComponent>
  </MyComponent>
</MyComponent>
```

This can be enforced with the following configuration:

```js
"jsx-closing-bracket-location": [2, {
  "nonEmpty": "props-aligned", // Align the bracket with the last prop
  "selfClosing": "tag-aligned" // Align the bracket with the opening tag
}]
```

What do you think?

**Comment by ljharb** [comment]
Strong -1 for this change. Your change is analogous to:
```js
var obj = {
  foo:
    {
    a: 3
  }
};
```

The `>` isn't a child of `MyComponent`, it's part of it, so it shouldn't be nested an additional indentation level. Also, we shouldn't be using non-semantic alignment anywhere.

**Comment by lencioni** [comment]
Thanks for considering my proposal and for the fast response!

However, I disagree with your analogy. I think that the style as currently stated is somewhat more analogous to:

```js
var obj = {
  foo: 'something',
children: [
  'a',
  'b'
]
};
```

whereas I think that what I am proposing is somewhat more analogous to:

```js
var obj = {
  foo: 'something',
  children: [
    'a',
    'b'
  ]
};
```

> we shouldn't be using non-semantic alignment anywhere

I'm not sure I understand what you mean by non-semantic alignment. Will you please help me understand?

**Comment by ljharb** [comment]
Sure - what I meant by that is, "adding whitespace for the sole purpose of visually aligning things". Things should be aligned to match their appropriate nesting level, only.

**Comment by lencioni** [comment]
Got it. That makes sense to me. I do, however, think that what I am proposing is semantic alignment.

**Comment by ljharb** [comment]
The `>` is aligned on the same level as one of its children. Perhaps:
```js
// bad
switch (foo) {
case bar:
  break;
case baz:
  break;
}

// good
switch (foo) {
  case bar:
    break;
  case baz:
    break;
}
```
is a better analogy? Basically, if you see a line that's a deeper semantic level than the one before it, then it *must* be indented one level further. Applying that, your proposal would become:
```js
<MyComponent
  myProp="..."
  >
    <MyComponent
      myProp="..."
      >
        <MyComponent
          myProp="..."
          >
            Children
        </MyComponent>
    </MyComponent>
</MyComponent>
```

**Comment by lencioni** [comment]
I think that example does make some sense, since `children` is a prop and the body of the tag is the value of this prop. But really I can see good arguments in favor of all 3 styles--with many coding style rules this is probably just one of those things that doesn't have a totally right answer and you just need to pick something reasonably pragmatic. :)

For anyone following along at home who uses Vim, the good news is that there is an open PR for vim-jsx that will add support for the current Airbnb style of alignment. https://github.com/mxw/vim-jsx/pull/75

Thanks for the discussion @ljharb! :tophat:

**Comment by ljharb** [comment]
Thanks for the contribution and the discussion! Feel free to fork the styleguide as well if you'd like to include our own modifications :-)
