### ISSUE TITLE
Enable react/no-is-mounted?

### ISSUE THREAD

**Issue by lencioni** [airbnb/javascript#633]
Hi folks, since [`isMounted` is an anti-pattern](https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html), is not available when using ES6 classes, and is on its way to being officially deprecated, what do you think about enabling the [react/no-is-mounted](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-is-mounted.md) rule that was recently released with [3.12.0](https://github.com/yannickcr/eslint-plugin-react/blob/master/CHANGELOG.md#3120---2015-12-20)? If you are up for it, I'd be happy to submit a PR. (Do you think it should be a warning or an error?)

**Comment by ljharb** [comment]
That seems reasonable to me - let's let a few more folks chime in first.

If enabled, it should definitely be an error - people ignore warnings.

**Comment by lencioni** [comment]
Agreed. Plus I see that you just enabled the rule to require ES6 classes anyway: https://github.com/airbnb/javascript/commit/c98990c0f957edeb943a992e3dda4e755004d57b

**Comment by ljharb** [comment]
Ah, that's true - given that, we might as well enable this rule as well :-) PR welcome!

**Comment by ljharb** [comment]
(please add a note in the styleguide as well, along with the rule change)
