### ISSUE TITLE
Work together on eslint-config-defaults

### ISSUE THREAD

**Issue by baer** [airbnb/javascript#638]
Hello! I wanted to propose a collaboration between this repo and https://github.com/walmartlabs/eslint-config-defaults.

I originally set out to build config-defaults because I was tired of copy pasting my eslint config around and trying to keep them up to date across lots of projects. Eslint's `extends` key fixes the distribution problem but there are still two issues:

1. Managing the eslint config file is a pain in the ass even though it is centralized. New rules are added, removed, moved and deprecated all the time!
2. Just get up and running for a new project was not straightforward and I strongly believe that code quality tooling should be well suited to those who are just starting out. They're often the ones who need it most after all.

---

It's obvious that you all saw the same problems and it has been enormously helpful to a lot of people. and we've already worked together in #366 and #526 but I want to take your config one step further and I am asking for your help. With eslint-config-defaults I want to try to centralize the config from a few thought leaders around the web so that folks have fast, standard and up to date options from the start.

I've been maintaining an "unofficial" airbnb config for a while now but it's duplicate effort and my hope is to try to collaborate/consolidate. For my part, I am committed to staying on top of the latest rules (and deprecations). I should mention that you all have quite a few missing rules already :).

Potential Objections(?):
- **We need quick access to the repo to make changes.** - I'm happy to try to get your maintainers added to the project.
- **The project is under walmartlabs and I'm not too sure I like that.** - It's possible we could spin this out into it's own org - I'd have to talk to legal and such about what we can do.
- **We don't want to install all the configs!** - Maybe we can do what babel does and have multiple npm packages under the same project. We can figure that out.
- **This project is really popular and is an exceptional part of our OSS portfolio that we're not going to shut down.** - You could easily take config-defaults as a dependency and keep this exactly how it is. Really, this repo's strength is it's plain english documentation and is kindof an awkward place to store ESLint rules.

Anyway, I wanted to start a conversation and see if we can make it work for both of us.

@justjake @taion @ljharb @hshoff

**Comment by taion** [comment]
I'm just a bystander here - but even as a (hopefully) non-novice user, I was really confused in initially figuring out whether I was supposed to use `eslint-config-airbnb` or `eslint-config-defaults` for my projects. It wasn't at all obvious which was more correct.

On a separate note, though, you may want to consider including https://github.com/rackt/eslint-config-rackt. I don't know that it's used anywhere outside of the rackt repos (I personally don't use it for anything I have that isn't under the rackt org), but React Router and Redux are pretty popular libraries, so I dunno.

**Comment by taion** [comment]
Gah I'm an idiot who didn't turn on notifications for rackt/eslint-config-rackt.

**Comment by ljharb** [comment]
Regarding the two issues you've mentioned:
1) "Managing the eslint config file is a pain in the ass". This has proven not to be true in practice. In addition, we now use `eslint-find-rules --unused` to ensure that we're not missing any rules, even when eslint or our plugins update.
2) "Just get up and running for a new project was not straightforward" - beyond improving documentation (which is always a good thing), I don't see how the "defaults" project improves this in any way. All it does is present a paralysis of choice, and often out-of-date sub-configs (you're up to v5 on our config, but v7 is published, and v8 is coming soon).

You're welcome to include `eslint-config-airbnb` as a proper npm dependency, and let people use it that way, and collaboration is great! But, I don't see a valuable direction to go here, or even any direction that wouldn't make the issues you mentioned *worse*.

I'm going to close this, but will be happy to reopen if a viable direction appears.
