### ISSUE TITLE
Naming convention for plain object properties

### ISSUE THREAD

**Issue by satazor** [airbnb/javascript#640]
I couldn't find the convention for naming properties in plain objects. Some people use camelCased properties while others use underscored properties. What's the airbnb convention on this?

Thanks.

**Comment by caspervonb** [comment]
Identifiers in general are covered by https://github.com/airbnb/javascript#22.2

Care to cite some examples in the wild using underscored identifiers? curious as thats the one thing I've always perceived as uniform within the community.

**Comment by satazor** [comment]
So it falls under the camel case conventions? Is there any exceptions when building rest api responses?

**Comment by justjake** [comment]
The REST API bit is kinda a sticky wicket. Our Ruby styleguide specified snake_case properties, so all our serialized Ruby objects in our REST responses are snake_case.

However according to this styleguide your object properties should be camelCase. /shrug

**Comment by satazor** [comment]
I see. Should we make this more explicit in the README with an example?

**Comment by ljharb** [comment]
I'm not sure if we want to codify an example of mixed casing. Ideally, everything is camelCased, but it's definitely a practical reality that server responses may be snake_cased. The decision of where the boundary lies is a tricky one and a subjective one, and while each codebase may need to make its own choice where to draw it, many will be able to stick with the ideal.

**Comment by satazor** [comment]
The `camelcase` option defined in eslint-airbn has `properties: 'never'` which is inline with "camel case is preferred". Thanks for your responses.
