### ISSUE TITLE
Document best practices for test assertions

### ISSUE THREAD

**Issue by zeke** [airbnb/javascript#646]
There's an issue on enzyme https://github.com/airbnb/enzyme/issues/97 about strengthening the assertion styles to avoid false positives:

> A great first task would be removing this rule override, and fixing our tests and docs to use, for example, .to.equal(true) instead of .to.be.true

The issue mentions that the `to.be.true` style violates this styleguide, but I wasn't able to find any content here that alludes to this.

**Comment by Ensive** [comment]
@ljharb 
How actual this issue is?
Do you think we need to add something like:
> Do not use `to.be.true`, etc. in your tests, but use `.to.equal(true)`

Shall we put it within [Testing](https://github.com/airbnb/javascript#testing) section?

**Comment by ljharb** [comment]
Yes, but specifically, a section on never using "noop" matchers - ie, anything that doesn't end in a function call - because the cost of a typo is a silent passing test. In other words, `expect(x).to.be.yogurt;` will merrily pass, whereas `expect(x).to.be.yogurt()` will correctly throw, failing your test.

**Comment by zeke** [comment]
Thanks for following up on this, @ljharb 👍 

Since opening this issue (over three years ago!), the `standard` linter has been updated to no longer allows expressions like `to.be.true`, which has protected me from accidentally using that assertion style in projects.

**Comment by ljharb** [comment]
@zeke this config has protected you from that for [3.5 years](https://github.com/airbnb/javascript/commit/daea8a638f1f42cd609f1b68b748ad323be31c10).
