### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by roccomuso** [airbnb/javascript#654]
Is it worth a full translation in italian? I can fork and then PR.

**Comment by frenzzy** [comment]
Did you see [translations list](https://github.com/airbnb/javascript#translation)?
  - ![it](https://raw.githubusercontent.com/gosquared/flags/master/flags/flags/shiny/24/Italy.png) **Italian**: [sinkswim/javascript-style-guide](https://github.com/sinkswim/javascript-style-guide)

You can improve the Italian translation by sending your PRs to there

**Comment by roccomuso** [comment]
Sorry, i've missed it.
