### ISSUE TITLE
How is the style guide related to eslint-config-airbnb? 

### ISSUE THREAD

**Issue by inetfuture** [airbnb/javascript#665]
For example, there is a rule about `prefer-arrow-callback` in [style guide](https://github.com/airbnb/javascript#arrow-functions), but I don't see it in eslint-config-airbnb? Aren't they supposed to be matched?

**Comment by ljharb** [comment]
They are indeed, but they'd fallen out of sync, and we're still working on bring them together. A PR is welcome for any places you see something in the styleguide that doesn't have an equivalent rule defined in the config.

**Comment by inetfuture** [comment]
OK, I'll send PR then.
