### ISSUE TITLE
Tab button > two spaces indentation

### ISSUE THREAD

**Issue by Triang3l** [airbnb/javascript#67]
Personally, I think that it's better to use Tab button to indent code than two spaces.

First of all, its width is configurable by the coder. So if a coder likes 2-space indentation, he can set this in settings, if he likes 4-space indentation, he can set this in settings as well.

Second, tab is 1 character, so it takes 2 times less space than two spaces.

It's also quicker to add, remove or count indentation level with tabs. It's easy to get lost while removing a level of indentation from a deeply indented block unless you have a special editor configured to remove 2 spaces at once. With tabs, you don't have to divide the number of spaces by 2 to get current indentation level, and it's faster to navigate in indentation with arrow keys.

And, 2-space indentation is barely convenient. Its width is even less than line height.

Contrary to popular belief, using tabs _to indent_ does not make the code look broken in different editors (except for Microsoft Word, but nobody codes in it). You just shouldn't use tab inside or after a line of code.

This article explains how to use tabs correctly: http://blogs.msdn.com/b/cyrusn/archive/2004/09/14/229474.aspx

**Comment by r01010010** [comment]
I also prefer tabs, it's simply easier to hit a tab once than a space two or four times.
