### ISSUE TITLE
Add section on nested/multiline ternaries

### ISSUE THREAD

**Issue by ljharb** [airbnb/javascript#671]
Specifically, prohibiting nested ternaries (to match https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/style.js#L63-L64) and perhaps discouraging multiline ternaries (not sure if there's a rule for it).

**Comment by bgvianyc** [comment]
opened a PR: https://github.com/airbnb/javascript/pull/673

**Comment by ljharb** [comment]
Done in #673.
