### ISSUE TITLE
return indentation on second line?

### ISSUE THREAD

**Issue by olalonde** [airbnb/javascript#672]
Couldn't find if this was mentioned in the guide.

```javascript
const a = () => {
  return somepromise().then(() => {
    // do something
  }).then(() => {
    // do something
  });
};
```

vs

```javascript
const a = () => {
  return somepromise()
    .then(() => {
      // do something
    })
    .then(() => {
      // do something
    });
};

**Comment by ljharb** [comment]
The former, for the first `.then`. I'm not sure if the guide has an opinion on the second one (but the first `})` must be on the same indentation as `return`, ie, the line on which the `(` and `{` began)

**Comment by olalonde** [comment]
Thanks (though I just edited the issue to make it more clear). So the general rule is to close `})` at the same indentation that they were opened right?

**Comment by ljharb** [comment]
Absolutely.

Given your edits, I think either one is appropriate, but I'd probably prefer the first one.
