### ISSUE TITLE
Why are some rules well defined but turned off (react/jsx-curly-spacing)?

### ISSUE THREAD

**Issue by ikornienko** [airbnb/javascript#693]
For example the rule [react/jsx-curly-spacing](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/react.js#L25):

```
    'react/jsx-curly-spacing': [0, 'never', { 'allowMultiline': true }],
```
isn't just set to ``0``, but has defined behavior ``'never'`` and options ``allowMultiline``. Does it mean that you recommend this behaviour, but you're not making it error (``2``) in 3.x because it'll break a lot of stuff? Therefore will it become enabled in 4.0.0? Or is it for internal discussion like "we're proposing this rule to look like this, if there are no objections, it'll be enabled with next major release"?

**Comment by ljharb** [comment]
All the rules have their defaults explicitly present. We're slowly progressing to enforce as many rules as possible - we just haven't gotten to that one yet.

A PR to enable it, and add the relevant section under https://github.com/airbnb/javascript/tree/master/react#spacing, would be very welcome!

Since it's a new guide section, it would be a breaking change, which means that it would be in v4.0.0 if it were merged now.

**Comment by ikornienko** [comment]
Oh, I see, it specifies the default values for this rule. So it probably just means that there is no one opinion about it. This rule seems to be a good one to actually _have_ some behavior defined (different preferences in whitespaces is one of the most popular reasons that leads to unclear diffs).

Is this issue enough to start discussion about this particular rule ``react/jsx-curly-spacing``, or is there some more formal process? Likely it's not the only one rule you need to review/discuss, and if it's already in your TODO list, please feel free to close this issue.

**Comment by ljharb** [comment]
In this case, it would match what we already consistently use internally at Airbnb - which are the current settings: never, and allowMultiline set to true.

**Comment by ikornienko** [comment]
@ljharb thanks for the clarifications (looks like your comment was some seconds before mine). Great, now I know what to expect and will be prepared! Amazing job, thank you for that!
