### ISSUE TITLE
Arrow functions and parentheses: "good" example in 8.2 does not follow suggestions in 8.4

### ISSUE THREAD

**Issue by dominiks-cliqz** [airbnb/javascript#694]
[8.4](https://github.com/airbnb/javascript#8.4) suggests (emphasis added):
>  If your function takes a single argument and doesn’t use braces, omit the parentheses. **Otherwise, always include parentheses around arguments.**

However, [8.2](https://github.com/airbnb/javascript#8.2) provides a "good" example not following the above suggestion:
```javascript
// good
[1, 2, 3].map(number => {
  const nextNumber = number + 1;
  return `A string containing the ${nextNumber}.`;
});
```
This might be confusing to readers as it raises the question: is this a good example, or is it not? Adding parentheses around ```number``` would help to clarify.

**Comment by ljharb** [comment]
Thanks, this is just an artifact of a previous lack of clarity in this rule. This should indeed have parens around the arg.

**Comment by ljharb** [comment]
Closed in #714

**Comment by davidfloegel** [comment]
Sorry for putting another comment here but I didn't want to open a new issue for that.

We're using your eslint setup in our company and were wondering why you decided to require parenthesis around the arg if it's a multiline function. like:
```javascript
// bad
foo( x => {
   const b = x * 2
   return x
} ) 

// good
foo( ( x ) => {
```

So, why do you require parenthesis around the `x` argument ?

Thanks in advance!

**Comment by ljharb** [comment]
(To clarify, there should not be spaces inside the invoking parens, in both examples, and you're missing semicolons)

Here's the way our thinking went:
1. The guide must ensure there's always only one choice for parens or not.
1. Consistency suggests we choose "always use parens"
1. However, the aesthetics of inline one-arg arrows with parens were not acceptable to all engineers at Airbnb, some of whom required being able to omit the arg parens in some cases.
1. We compromised, and came up with this rule, which provides one choice in all situations.
