### ISSUE TITLE
Lack of "react/jsx-uses-react": 1,

### ISSUE THREAD

**Issue by framerate** [airbnb/javascript#704]
Redoing my .eslintrc based on yours (thanks for that!) and I noticed I had to add `react/jsx-uses-react` to my eslint.

Link: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-uses-react.md

Is there a reason you guys aren't using it? Or maybe the react plugin options don't carry over from the extend?

Thanks!

**Comment by ljharb** [comment]
Looks like you may need #703? We should certainly be using that.

**Comment by framerate** [comment]
Yeah I Just issued that PR since it was ambiguous. should the readme be updated to include some react plugins as well?

I worked through your eslint into something I liked and ended here:

```
{
    "extends": "airbnb/base",

    "plugins": [
        "react"
    ],

    "rules": {
        "react/jsx-uses-react": 1,
       # my other changes don't matter in this case
    }
}
```

Did you expect  `"react/jsx-uses-react": 1,` to be inherited?

**Comment by ljharb** [comment]
I would expect it to be set to what is defined here https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/react.js#L70

Ah! you extended `airbnb/base` but not `airbnb/react` :-)

**Comment by framerate** [comment]
Doh! All that fun with the pull request for nothing!

Funny how you miss the little things until you show it to someone else... Thanks @ljharb
