### ISSUE TITLE
Why class based componets better then createClass components?

### ISSUE THREAD

**Issue by isergey** [airbnb/javascript#708]
Comparing two ways to define  the React components, it seemed to me that the creation of a component through createClass more succinctly. 
Link.propTypes = propTypes, link.defaultProps = defaultProps, onclick={this.onClickDiv.bind(this)} - looks like a crutch. For me, these moments do not look very convenient.
What are advantages of class based components. Thank you for your reply and great product!

**Comment by emyk** [comment]
createClass will probably be deprecated some time in the future ([ref](https://facebook.github.io/react/blog/2015/03/10/react-v0.13.html)).

If you can use the es6 classes, I'm assuming you're using babel as well. With ES7 property initializers you dont have to jump through those hoops you are describing, and can do

```
class Button extends React.Component {
  static propTypes = {};
  static defaultProps = {};

  state = {};

  onClick = (event) => {
    // handle event
  };

  render() {
    return <button onClick={ this.onClick }>woah</button>
  }
}
```

**Comment by ljharb** [comment]
One note: static and instance properties aren't ES7, they're currently a stage 1 proposal for some future ES version.

However, the advantages of using `class`-based components far outweigh the minor inconvenience of `Foo.propTypes = {}; Foo.defaultProps = {};` etc.

**Comment by pablopaul** [comment]
@ljharb Would you mind to write down "the advantages"?

**Comment by ljharb** [comment]
For one, they're massively faster since they don't autobind all methods like createClass does.
