### ISSUE TITLE
Template Strings Spacing

### ISSUE THREAD

**Issue by felixsanz** [airbnb/javascript#716]
In Template Strings:

```javascript
// good
function sayHi(name) {
  return `How are you, ${name}?`;
}
```

Do you prefer `${name}` over `${ name }` ?

For variables that seems obvious (no space), but template strings allows much more, like `${ (name) ? name : 'No name' }`, where i think spacing makes it more clear.

> I didn't test that expression, i can be wrong :stuck_out_tongue:

**Comment by ljharb** [comment]
Definitely no space - spaces only go inside curly braces for JS object literals. (and in that ternary example, no unnecessary parens around the conditional)

**Comment by ljharb** [comment]
More to the point, I'd urge you to use an intermediate variable if your interpolation value is complex enough that you think spaces are needed - for readability and to obviate the spacing ambiguity.

**Comment by felixsanz** [comment]
Right, thanks!

**Comment by felixsanz** [comment]
Oh, btw. I tried it before asking and ESLint didn't complain. Maybe it's possible to add the rule for this into the airbnb linter?

http://eslint.org/docs/2.0.0/rules/template-curly-spacing

**Comment by ljharb** [comment]
That rule isn't in eslint v1 (http://eslint.org/docs/rules/template-curly-spacing) so that would be great to add after v2 is released.

**Comment by felixsanz** [comment]
Also, adding a section in **readme.md** with good/bad example about template curly spacing would be nice (maybe when v2 is released).

I was about to make a PR myself, but i don't want to mess with section numbers because i would add this to **6.5** and move the eval thing to **6.6**, but i don't know if that would be accepted.

Leave this open if you want, or close it if you consider so. My question was answered, thanks again.

**Comment by ljharb** [comment]
That's a great idea. Let's leave this open until we update to eslint v2, at which point, we can add this section to the guide along with the linter rule (a separate PR to the guide in the meantime would be great too)
