### ISSUE TITLE
`no-unused-vars` and `prefer-template` rules conflict

### ISSUE THREAD

**Issue by feimosi** [airbnb/javascript#717]
Having the following code:
```js
    var someString = giveMeMyString();
    this.paragraph = `some article with $(someString)`;
```
I get `no-unused-vars` error.
If I change it to:
```js
    var someString = giveMeMyString();
    this.paragraph = 'some article with ' + someString;
```
I get `prefer-template` error.
How it's possible no one came across this? Am I doing something wrong?

**Comment by gergoerdosi** [comment]
The template string syntax is `` `${variable}` ``. Change `$(someString)` to `${someString}`.

**Comment by feimosi** [comment]
Thanks a lot! That was a terrible oversight.

**Comment by chris-mac** [comment]
Still getting this issue and I am using the correct syntax ${variable}

**Comment by ljharb** [comment]
@chris-mac can you provide the code in question? Note that the "correct syntax" refers to the backticks, NOT single/double quotes, surrounding the literal.

**Comment by chris-mac** [comment]
Ah thank you! I blame context switching between Ruby, Bash and JS :)
