### ISSUE TITLE
Point 22.5. Reference to this context.

### ISSUE THREAD

**Issue by Pencroff** [airbnb/javascript#718]
I have read JavaScript Style Guide and in point [22.5](https://goo.gl/5kp8fa) you are suggested `arrow functions` or `Function#bind` instead of closure to `this` context.
Base on [test](http://goo.gl/UlfoVv) `Function#bind` works much slower. Arrow functions has some magic with `this` context. And from my opinion using arrow function with `this` reference require very deep understanding [standard behavior](https://goo.gl/EFhI4C) (means Senior Level Developers).
What the reason for avoiding closure for `this` context?
```
// Why is it worse then next example?
// It's more clear for next reading
function foo() {
  const that = this;
  return function () {
    console.log(that);
  };
}

// good
function foo() {
  return () => {
    console.log(this);
  };
}
```

**Comment by ljharb** [comment]
Performance is the last thing one should be concerned about when programming - accurately conveying programmer intent is far more important. It's easy to make clean code fast, it's hard to make fast code clean. (yes, `.bind` is usually slow, and arrow functions transpile in babel down to a closure with the `var self = this` pattern, so their performance is equivalent)

Arrow functions don't have "more magic" as much as they *don't* provide a binding for `this` (or `super` or `arguments`), which normal functions *do* provide - so if anything they have *less* magic :-).

Although arrow functions are new, and as such, may seem strange to experienced JS developers, in our experience they've helped illustrate the many meanings of `this` by providing a syntactical construct that more closely mirrors people's intuition.

**Comment by Pencroff** [comment]
It seems I am a bit conservative and I will think about arrow functions in a relationship to our real examples.
But I would like to understand your point about binding.
Why is making closure for `this` context is less readable then `.bind` syntax?
```javascript
function foo() {
  const that = this;

  return function () {
    console.log(that);
  };
}

function foo() {
  return newFoo.bind(this);

  function newFoo() {
    console.log(this);
  }
}
```
Using closure in JS it's usual practice with very low cost. Isn't it?

**Comment by ljharb** [comment]
It's only a low cost to people familiar with the pattern. Both are a very high cost to everyone else, because it requires knowing more about how `this` works.
