### ISSUE TITLE
Strict mode rule

### ISSUE THREAD

**Issue by markelog** [airbnb/javascript#722]
You have this - https://github.com/airbnb/javascript/blob/44cc90f31cf09655a0363827af082335defd619a/packages/eslint-config-airbnb/rules/strict.js

But on latest nodes you might not want to use transpiler, besides, you might want to use something different then babel.

Also such limitation is not on `README`. 

Considering all that, i would propose to remove it

**Comment by ljharb** [comment]
Any transpiler must, by spec, put "class" and "module" code in strict mode. In addition, it is a very bad idea to not use a transpiler with the current state of spec compliance in engines, and browser support.

If you want to ignore these best practices and the "use strict" pragma is needed, you can certainly override the "strict" rule in your own `.eslintrc` file.

**Comment by tleunen** [comment]
Do you suggest to use a transpiler, even on node?
Cause [Babel-node is not meant for production](https://babeljs.io/docs/usage/cli/#babel-node).

**Comment by markelog** [comment]
> Any transpiler must, by spec, put "class" and "module" code in strict mode

Yes and obviously, but the code outside of the say `class` will not be in the strict mode.

In latest chrome, for example, level of support of es6 features at 91%, so if i write application only for that specific browser or if create chrome app i don't need to use a transpilier, but with your code-style i'm prohibited to `use strict`, which goes against those best practises you mentioned.

Node 5.1 supports a lot of new features without using any flags like `harmony`. 6 version, presumably, will be at the same level as latest chrome. 

I also can use a **different** transpiler. It seems you missing that point.

> If you want to ignore these best practices and the "use strict" pragma is needed, you can certainly override the "strict" rule in your own .eslintrc file.

I did, i also can override every single rule you have! What a cool world we live in! 

mm, sorry, couldn't resist :)

**Comment by markelog** [comment]
And btw, one day, you would need to stop to use transpiler, since transpiler is still considered as tmp measure, so what are you gonna do then? If you would just add `use strict` everywhere, then there wouldn't be any guarantee your code would still work, whereas not using the `use strict` is "very bad idea".

**Comment by tleunen** [comment]
@markelog you can still use a transpiler to only add the `use strict` ;) (only use this transform https://babeljs.io/docs/plugins/transform-strict-mode/)

**Comment by ljharb** [comment]
It's not a temporary measure imo - we'll likely be using transpilers forever, because there will likely continue to be engine inconsistencies, and new syntax, forever. (which different transpiler would require the "use strict" statements? anything that did would be broken, and you shouldn't use that)

However, if we stopped using a transpiler, "use strict" would be redundant, because everything inside of a module is strict - and **all** code should be inside a module.

Even if you're only targeting one browser (for some crazy reason) or if you're targeting a specific version of node, new constructs are always slower than old ones, so there's performance reasons to transpile as well as correctness reasons.

**Comment by markelog** [comment]
> we'll likely be using transpilers forever

That would be really sad, and it seems other people have different opinions about that - https://twitter.com/sebmck/status/682349535214104576

> Even if you're only targeting one browser (for some crazy reason)

https://developer.chrome.com/apps/about_apps and there is a lot of use-cases beside that.

> if you're targeting a specific version of node

End application of course targets the one version of node.

> new constructs are always slower than old ones

That statements really has no grounds, some of them are slower, some of them are much faster.

All and all i don't like the tone of this discussion nor the attitude to i what i think is reasonable suggestion. 

I'm out.

**Comment by tleunen** [comment]
The thing is @markelog is that this repo is used by Airbnb for their specific needs.
If you need something else, you can fork and change whatever you want.

All the tickets created are just discussions and then they decide what to keep/reject. At least, that's how I see it.

btw @ljharb you can easily target one single browser when you're making an internal tool. Not great, but it can save some dev time as well.

**Comment by ljharb** [comment]
@tleunen re https://github.com/airbnb/javascript/issues/722#issuecomment-182491769, yes, `node` doesn't even have a spec-compliant "let" and "const" yet.

**Comment by ljharb** [comment]
@markelog fwiw, I do agree that strict mode/transpilers should be mentioned on the readme. I'd love to accept a PR that added a note about it at the top.
