### ISSUE TITLE
Style critique on no-unused-vars.

### ISSUE THREAD

**Issue by EvanCarroll** [airbnb/javascript#726]
You have `no-unused-vars` set in your [eslint profile](https://github.com/airbnb/javascript/blob/396e4611c42416aa3b2af6ed193c3684251d9f68/packages/eslint-config-airbnb/rules/variables.js) to [`'args': 'after-used'`](http://eslint.org/docs/rules/no-unused-vars.html). That's not always good because it forces a callback to forgo arguments if it's not using them...

```javascript
view.model.login.call(view.model, {
  error: function (model, xhr, options) {
    // only use model, xhr
  }
}
```

If it only uses `model` (the first argument), that means it has to look like this..

```javascript
view.model.login.call(view.model, {
  error: function (model) {
    // only use model
  }
}
```

Which means finding out the order of subsequent arguments means you have to look it up. It also means the signature of the function is in some cases forced to not-match the invocation as in the case where you provide a callback, and the callback is always invoked with three whether or not you need those arguments (as is the case above). This really kills a clean form of code-documentation.

My suggestion is to go from

    "no-unused-vars": [2, {"vars": "all", "args": "after-used"}]

to 

    "no-unused-vars": [2, {"vars": "all", "args": "none"}]

**Comment by ljharb** [comment]
That's a very good point, and imo is indeed the primary argument against "after-used".

Adding extra unused arguments increases the function length, and can cause confusion when reading the function definition. However, the main benefit I think this rule adds is catching a bug when you *intended* to reference the extra argument but in fact did not. Forcing the user to edit the function signature to match their usage helps prevent this.

If your desire is documentation, then `function (model /* , xhr, options */) {` seems like it would both suffice and satisfy the linting rule.

If we wanted to recommend fully documenting the unused parameters, then similarly, for consistency, this would mean that an `Array#map` callback must always have 3 parameters, even if you're not using the "key" or "array" parameters. This doesn't seem ideal.

**Comment by ljharb** [comment]
This is a rule you are welcome to override in your own codebase, as well as by forking this project. We use this style at Airbnb, and "you have to look [the signature] up" is something we consider a good thing when editing a function.

Thanks for your input!
