### ISSUE TITLE
Update to eslint 2.0

### ISSUE THREAD

**Issue by Joshua-F** [airbnb/javascript#732]
ESLint 2.0 has been officially released and introduced some breaking changes. Any plans to support 2.0?

http://eslint.org/docs/user-guide/migrating-to-2.0.0

**Comment by ljharb** [comment]
Yes, in #730.

**Comment by Joshua-F** [comment]
Oops, my mistake I should have looked at closed issues first. Sorry for the bother.

**Comment by ljharb** [comment]
No problem :-)
