### ISSUE TITLE
ESLint 2.0.0 Released -- New Rules to Consider

### ISSUE THREAD

**Issue by knpwrs** [airbnb/javascript#733]
To quote the [blog post](http://eslint.org/blog/2016/02/eslint-v2.0.0-released):

>  There are several new rules for this release:
> 
> * [`array-callback-return`](http://eslint.org/docs/rules/array-callback-return)
> * [`id-blacklist`](http://eslint.org/docs/rules/id-blacklist)
> * [`keyword-spacing`](http://eslint.org/docs/rules/keyword-spacing)
> * [`newline-per-chained-call`](http://eslint.org/docs/rules/newline-per-chained-call)
> * [`no-confusing-arrow`](http://eslint.org/docs/rules/no-confusing-arrow)
> * [`no-empty-function`](http://eslint.org/docs/rules/no-empty-function)
> * [`no-extra-label`](http://eslint.org/docs/rules/no-extra-label)
> * [`no-implicit-globals`](http://eslint.org/docs/rules/no-implicit-globals)
> * [`no-new-symbol`](http://eslint.org/docs/rules/no-new-symbol)
> * [`no-restricted-imports`](http://eslint.org/docs/rules/no-restricted-imports)
> * [`no-self-assign`](http://eslint.org/docs/rules/no-self-assign)
> * [`no-unmodified-loop-condition`](http://eslint.org/docs/rules/no-unmodified-loop-condition)
> * [`no-unused-labels`](http://eslint.org/docs/rules/no-unused-labels)
> * [`no-useless-constructor`](http://eslint.org/docs/rules/no-useless-constructor)
> * [`no-whitespace-before-property`](http://eslint.org/docs/rules/no-whitespace-before-property)
> * [`one-var-declaration-per-line`](http://eslint.org/docs/rules/one-var-declaration-per-line)
> * [`prefer-rest-params`](http://eslint.org/docs/rules/prefer-rest-params)
> * [`sort-imports`](http://eslint.org/docs/rules/sort-imports)
> * [`template-curly-spacing`](http://eslint.org/docs/rules/template-curly-spacing)
> * [`yield-star-spacing`](http://eslint.org/docs/rules/yield-star-spacing)

**Comment by knpwrs** [comment]
Looks like there are also some configured rules which have changed:

![image](https://cloud.githubusercontent.com/assets/174864/13025661/f91f53a0-d1da-11e5-8e41-495a2ace48e8.png)

**Comment by kesne** [comment]
This is being fixed in #730.

**Comment by knpwrs** [comment]
Looks like I need to work on my searching skills.
