### ISSUE TITLE
So many errors for a single console statement

### ISSUE THREAD

**Issue by segmentationfaulter** [airbnb/javascript#734]
Have a look at this screenshot http://imgur.com/kRDv5Z7

I have been using your eslint configurations, I never got these errors which are showing in this screenshot in the past, can you help me with this issue please?
thank you

**Comment by lencioni** [comment]
Hi @segmentationfaulter, sorry about the errors. I believe that these are due to ESLint 2.0 coming out yesterday. The upgrade for this project is being tracked in #730 and is expected to be finished in the next couple of days. In the meantime, your best bet might be to stick with ESLint 1.x.

**Comment by ljharb** [comment]
Sadly we used the wrong range in our `peerDependencies` and it includes 2.0 (and shouldn't). https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/package.json#L49 should be `^1.0.0`.

Closing in favor of #730.

**Comment by ljharb** [comment]
Published v5.0.1 so that this won't happen to new installs.
