### ISSUE TITLE
Remove peer-dependency from eslint-config-airbnb

### ISSUE THREAD

**Issue by steve-gray** [airbnb/javascript#737]
Can I suggest a small change to eslint-config-airbnb to remove the peerDependency on eslint? The reasoning behind this is:

- Some plugins like gulp-eslint compartmentalise the eslint dependency, but with the package-level peerDependency it means that we end up getting an NPM warning at the root package that nobody can do anything about.

- Other packages may want to read/leverage the rule sets, and shouldn't have to take the NPM warning to do so.

Its kind of implicit that the plugin requires _something_ that leverages the eslint ruleset standard, so I'm not sure that an explicit peerDependency is actually a requirement anyay.

**Comment by ljharb** [comment]
It may be implicit in docs, or in the name, but without a software-level dependency, it's easy to miss.

You won't get the peer dep warning if `eslint` is deduped to the top level - but I'd love to hear about use cases where another package uses these rules but doesn't itself have an `eslint` dependency.

In addition, it's critical to denote version compatibility - right now we only support 1.x, not 2.x - how would we communicate that except via one of the dependency groups?

**Comment by ischyron** [comment]
we should put that in README.md. 
The gulp-eslint uses 2.x and for eslint-config-airbnb we need 1.x

**Comment by ljharb** [comment]
@ischyron the package.json already has a peerDependency of 1.x.

**Comment by ischyron** [comment]
does it makes sense to put in the docs in addition to peerDependency ?
I was trying to figure out the linting difference between command-line eslint and gulp-eslint and took a while to see the peerDependency.

I guess it  is not easy migrate all configs to eslint 2.0 ? 
I would really like run with { es6: true }

**Comment by ljharb** [comment]
No. `npm` warns on the command line about it. If you ignore that warning on the command line, you'll ignore the docs too. In addition, yes, eslint 2.0 is not a trivial upgrade. See #730 to track that.

In the meantime, just don't use the latest version of gulp-eslint if you want to use it with eslint-config-airbnb or eslint-plugin-react.

**Comment by ischyron** [comment]
got that part by explicitly taking 1.1.1 for gulp-eslint . 
Its not trivial, guessed that.

btw.. at the time I installed eslint-config-airbnb npm didnt warn me of the peerDependency.
I installed gulp-eslint on top.

**Comment by ljharb** [comment]
I'm going to close this for now - it would be inappropriate for a plugin or shared config not to have a software-level dependency on the thing it's configuring or plugging into.
