### ISSUE TITLE
Getting warning about eslint not being installed, but it's installed

### ISSUE THREAD

**Issue by cageygee3** [airbnb/javascript#739]
I have these lines in my package.json:

```
    "eslint": "^2.1.0",
    "eslint-config-airbnb": "^5.0.1",
```

And I see this when running `npm install`:

`npm WARN eslint-config-airbnb@5.0.1 requires a peer of eslint@^1.0.0 but none was installed.`

However, eslint is definitely installed:

```
$ npm info eslint version
2.1.0

$ ./node_modules/eslint/bin/eslint.js --version
v2.1.0
```

Anyone know what's going on here?

**Comment by ljharb** [comment]
Yes, eslint-config-airbnb is not yet compatible with eslint 2.x.

Please track that in #730.
