### ISSUE TITLE
comma-dangle eslint error in legacy rules

### ISSUE THREAD

**Issue by GeyseR** [airbnb/javascript#741]
Hi!

In https://github.com/airbnb/javascript/tree/master/es5#commas you have note about trailing commas: `Additional trailing comma: Nope. This can cause problems with IE6/7 and IE9 if it's in quirksmode. Also, in some implementations of ES3 would add length to an array if it had an additional trailing comma`

But comma-dangle rule is presented in airbnb/legacy rule set.

What do you think about excluding this rule from airbnb/legacy?

**Comment by ljharb** [comment]
(It's in https://github.com/airbnb/javascript/blob/88d508400941600a71f45a245748346af9e62d1d/packages/eslint-config-airbnb/rules/errors.js#L3-L4 which included here https://github.com/airbnb/javascript/blob/88d508400941600a71f45a245748346af9e62d1d/packages/eslint-config-airbnb/legacy.js#L4)

I think that perhaps the legacy ruleset should disallow trailing commas, and the ES6 rule set should require them - there's some rule rearranging that could be done here.

**Comment by ischyron** [comment]
how to turn on legacy ruleset via comment ?

**Comment by ljharb** [comment]
@ischyron I'm not sure why you'd want to do that - you could certainly toggle the rule for comma-dangle by a comment tho. Can you elaborate?
