### ISSUE TITLE
npm i fails with 5.0.1 on eslint 2

### ISSUE THREAD

**Issue by AvraamMavridis** [airbnb/javascript#743]
npm ERR! peerinvalid The package eslint@2.2.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-config-airbnb@5.0.1 wants eslint@^1.0.0

My package:

```
    "eslint": "^2.0.0",
    "eslint-config-airbnb": "^5.0.1",
```

Switching to `"eslint": "^1.0.0"` in my package or in airbnb's package:

```
  "peerDependencies": {
    "eslint": "^2.0.0",
    "eslint-plugin-react": "^3.16.1"
  },
```

is fixing the problem.

Is it a plan to "support" eslint 2 ?

**Comment by softwarespot** [comment]
Please see #730. This has been in discussion for a while now, also searching issues would have linked to this PR.
