### ISSUE TITLE
how to use global variable (Meteor JS)?

### ISSUE THREAD

**Issue by thearabbit** [airbnb/javascript#746]
I would like to override `allow to use global var in Meteor`.
```js
Data = {
.........
}
```

**Comment by thearabbit** [comment]
I tried
```js
"rules": {
    "comma-dangle": 0,
    "no-console": 2,
    "no-undef": 2
  }
```
but don't work

**Comment by ljharb** [comment]
This is an `eslint` question, not one for this styleguide - http://eslint.org/docs/user-guide/configuring.html#specifying-globals will be helpful.

**Comment by thearabbit** [comment]
Excuse me,  I use this for default but I would like to override
```js
"extends": "airbnb",
  "rules": {
    "comma-dangle": 0,
    "no-console": 2,
    "no-undef": 2
  }
```

**Comment by ljharb** [comment]
@thearabbit Please read the `eslint` docs for more information.

**Comment by thearabbit** [comment]
Thanks, but I am newbie for atom (from WebStorm).
So I don't sure for `no-undef, no-console` or not.
Could you help me?

**Comment by ljharb** [comment]
@thearabbit Again, please read http://eslint.org/docs/user-guide/configuring.html#specifying-globals. You probably want to add a "globals" section in your eslint config next to "rules", to specify that "Data" is a global variable you don't want a warning about.
