### ISSUE TITLE
Trailing commas in Object/Array literal

### ISSUE THREAD

**Issue by trantorLiu** [airbnb/javascript#75]
Are trailing commas good style in javascript?
I always use them for convenience.

``` javascript
var tom = {
  name: 'Tom',
  age: 20,
  friends: [
    'Jerry',
  ],
};
```

**Comment by felixsanz** [comment]
@hshoff  So now this changed?

**Comment by hshoff** [comment]
@felixsanz yup! we switched to Babel which removes trailing commas and we get the added benefit of cleaner diffs. https://github.com/airbnb/javascript/blob/7e15ccf4cb39d370e085c860901cce5d9d01d810/README.md#19.2
