### ISSUE TITLE
[rule links] reduce visual clutter proposal

### ISSUE THREAD

**Issue by hshoff** [airbnb/javascript#750]
My quest for less clutter continues (https://github.com/airbnb/javascript/pull/695)

[meteor/javascript](https://github.com/meteor/javascript) has a clever solution for rule linking, they inline the eslint logo and link to the rule. 

I propose we adopt a similar style but with links at the end.
# Current
- [2.1](#2.1) <a name='2.1'></a> Use `const` for all of your references; avoid using `var`. eslint: [`prefer-const`](http://eslint.org/docs/rules/prefer-const.html), [`no-const-assign`](http://eslint.org/docs/rules/no-const-assign.html)
  
  > Why? This ensures that you can't reassign your references, which can lead to bugs and difficult to comprehend code.
  
  ``` javascript
  // bad
  var a = 1;
  var b = 2;
  
  // good
  const a = 1;
  const b = 2;
  ```
- [2.2](#2.2) <a name='2.2'></a> If you must reassign references, use `let` instead of `var`. eslint: [`no-var`](http://eslint.org/docs/rules/no-var.html) jscs: [`disallowVar`](http://jscs.info/rule/disallowVar)
  
  > Why? `let` is block-scoped rather than function-scoped like `var`.
# Proposal
- [2.1](#2.1) <a name='2.1'></a> Use `const` for all of your references; avoid using `var`. [<img src='http://eslint.org/img/logo.svg' height=18 alt='prefer-const' title='prefer-const' />](http://eslint.org/docs/rules/prefer-const.html)[<img src='http://eslint.org/img/logo.svg' height=18 alt='no-const-assign' title='no-const-assign' />](http://eslint.org/docs/rules/no-const-assign.html)
  
  > Why? This ensures that you can't reassign your references, which can lead to bugs and difficult to comprehend code.
  
  ``` javascript
  // bad
  var a = 1;
  var b = 2;
  
  // good
  const a = 1;
  const b = 2;
  ```
- [2.2](#2.2) <a name='2.2'></a> If you must reassign references, use `let` instead of `var`. [<img src='http://eslint.org/img/logo.svg' height=18 alt='prefer-const' title='prefer-const' />](http://eslint.org/docs/rules/no-var.html) [<img src='https://raw.githubusercontent.com/jscs-dev/jscs-dev.github.io/master/favicon.ico' heigh=18 alt='disallowVar' title='disallowVar' />](http://jscs.info/rule/disallowVar)
  
  > Why? `let` is block-scoped rather than function-scoped like `var`.

**Comment by gergoerdosi** [comment]
This has the disadvantage of searching. Sometimes when linting shows an error, I copy the ESLint rule from the command line and search for it in the style guide to find the relevant part. This won't be possible with icons.

**Comment by hshoff** [comment]
@gergoerdosi excellent point, hadn't considered that use case

**Comment by hshoff** [comment]
How about this instead?

  - [2.2](#2.2) <a name='2.2'></a> If you must reassign references, use `let` instead of `var`. <img src='http://eslint.org/img/logo.svg' height=18 />[`no-var`](http://eslint.org/docs/rules/no-var.html) <img src='https://raw.githubusercontent.com/jscs-dev/jscs-dev.github.io/master/favicon.ico' heigh=18 />[`disallowVar`](http://jscs.info/rule/disallowVar)

**Comment by ljharb** [comment]
Personally I don't find it visually cluttering to have the rules present, nor the word "eslint" or "jscs" - and in fact i might be grepping through all "eslint" instances in the doc if I wanted to review things.
