### ISSUE TITLE
Conflicting rules 'no-confusing-arrow' and 'arrow-body-style'

### ISSUE THREAD

**Issue by robbinjanssen** [airbnb/javascript#752]
Currently I'm using `eslint` with the airbnb config to lint my project. However since the last update (6.0.1) i've found somewhat conflicting rules, the 'no-confusing-arrow' rule and the 'arrow-body-style' rule.

Take this piece of code:
```js
export const conflict = (a) => a > 1 ? 'yes' : 'no';
```
This triggers the [`no-confusing-arrow`](http://eslint.org/docs/rules/no-confusing-arrow) rule.

According to the rule it should be written as following:
```js
export const conflict = (a) => {
  return a > 1 ? 'yes' : 'no';
};
```
However this triggers the [`arrow-body-style`](http://eslint.org/docs/rules/arrow-body-style) rule.

Any idea how to solve this while keeping the shorthand if?

Versions used:
```
"eslint": "^2.2.0",
"eslint-config-airbnb": "^6.0.1",
```

**Comment by lencioni** [comment]
Does it work if you use parentheses? 

```js
export const conflict = (a) => (a > 1 ? 'yes' : 'no');
```

**Comment by elliottsj** [comment]
Adding parentheses still triggers `no-confusing-arrow` for me.

**Comment by ljharb** [comment]
Looks like this is also an [eslint bug](https://github.com/eslint/eslint/issues/5332).

I'll disable `no-confusing-arrow` until they've fixed it - will release a patch later today.

**Comment by ljharb** [comment]
Published as v6.0.2

**Comment by tb** [comment]
```export const conflict = a => (a > 1 ? 'yes' : 'no');``` worked for me

**Comment by TokugawaTakesi** [comment]
@tb Conflict with `no-extra-parens`.
