### ISSUE TITLE
Performance problem in Array#push (4.2)

### ISSUE THREAD

**Issue by mahmoudmy** [airbnb/javascript#758]
#### 4.2: Use Array#push instead of direct assignment to add items to an array.
But this has low performance baed on this: http://www.jstips.co/en/insert-item-inside-an-array/

**Comment by ljharb** [comment]
Performance is far less important than clean, maintainable, testable, consistent code. In their linked jsperf, even the slowest of those is around 500-700 thousand operations per second - how many times are you actually pushing stuff into an array?
