### ISSUE TITLE
How to deal with DOM manipulation

### ISSUE THREAD

**Issue by LukasBombach** [airbnb/javascript#766]
I have a function that manipulates the DOM, something like this

```javascript
function (el) {
  el.expando = {};
}
```

(btw: I believe there are valid reasons why I do write data to the DOM like this, but I do not want to go off topic)

Obviously this triggers a `no-param-reassign` error. I am not sure if there is a way of manipulating the DOM in such a way without violating the style guide–or is there? Are there any ways to deal with this?

**Comment by ljharb** [comment]
Since `data-` attributes are the proper and sanctioned place to store your own data on a DOM element, and you can use `.setAttribute` to set them, that's what I'd recommend.

If you stick to your approach, your only recourse is to override the linter rule, perhaps with an inline comment.

**Comment by LukasBombach** [comment]
But you can only write strings (i.e. serialized objects) to data-attributes. I am writing actual data to the DOM object (like jQuery's data method). In my case I am writing a WYSIWYM-library where I map DOM-nodes to nodes of an internal document representation. In this context it not only seems a good solution, but also the right _semantic_ context to write data to DOM nodes even though it is pretty en-vogue not to do that.

**Comment by LukasBombach** [comment]
For the record, [StackOverflow's community's opinion](http://stackoverflow.com/questions/35637770/how-to-avoid-no-param-reassign-when-setting-a-property-on-a-dom-object) on that matter seems to be to disable this rule—at least for that part of the application.

**Comment by ljharb** [comment]
At Airbnb, we don't store any data in the DOM - so if you want to do so, you may have to deviate from our style guide where applicable.

As far as semantics, what you actually want is a `WeakMap` of DOM node to internal nodes, and definitely not to store information on the actual DOM nodes. However, `WeakMap` requires native support, and `Map` can't be polyfilled in ES3 (read: IE 8 and below) so that may not be an option.

**Comment by LukasBombach** [comment]
Ok, thank you very much!

**Comment by ljharb** [comment]
@dandv the better alternative is creating new objects; and with respect to the DOM, the better option is using something like React rather than touching the DOM directly. `prefer-rest-params` has nothing to do with this, it just removes uses of `arguments`.
