### ISSUE TITLE
JSHint link in ES5 style guide is expired

### ISSUE THREAD

**Issue by incleaf** [airbnb/javascript#769]
https://github.com/airbnb/javascript/tree/master/es5#resources

Hi, I wanted to download the .jshintrc file that follows airbnb style guide but the link is expired

**Comment by ljharb** [comment]
You're right - it's missing the `.`. Correct link is https://github.com/airbnb/javascript/blob/master/linters/.jshintrc

**Comment by incleaf** [comment]
Haha I didn't know that :) I sent the PR with fixed link

**Comment by ljharb** [comment]
Fixed in #770 - thanks!
