### ISSUE TITLE
no-unused-vars rule don't work while extending the airbnb's config

### ISSUE THREAD

**Issue by artptr** [airbnb/javascript#773]
[This repo](https://github.com/artptr/eslint-airbnb-no-unused-vars-bug) reproduces the bug in `eslint-config-airbnb`.
There is an error while checking the `test.js`:

```
  1:5  error  'Foo' is defined but never used  no-unused-vars
```

The error appears despite that the parent config contains appropriate `no-unused-vars` setting.
It disappears only if we remove the airbnb's config (default or legacy) from the `extends` property.

The error appears on the ESLint 1.10.3 and 2.2.0

**Comment by ljharb** [comment]
According to the eslint docs, setting the "vars" option should still warn about unused local vars - that error is correct, and that var is unused, meaning that line could be deleted and your program would work the same.

**Comment by ljharb** [comment]
( I'm referring both to https://github.com/artptr/eslint-airbnb-no-unused-vars-bug/blob/master/.eslint-project-rules.json#L3 and to the redundant https://github.com/artptr/eslint-airbnb-no-unused-vars-bug/blob/master/.eslintrc.json#L8 )

btw thanks for the reproduction repo, that makes it super easy to understand what's going on!

**Comment by vkrol** [comment]
@ljharb Foo is the global variable, not local.

**Comment by ljharb** [comment]
Every file in node is in a module context, which means it's not at all a global variable.

**Comment by ljharb** [comment]
@vkrol you can verify that by checking `global.Foo` against `Foo` inside that file.

**Comment by artptr** [comment]
So the `airbnb/legacy` is not for a browser environment, but for an old Node.js environment, right?

**Comment by ljharb** [comment]
@artptr it's for both. but `eslint` runs with node, and assumes your files are run with node. You should be using browserify or the like to wrap your files anyway such that nothing in your browser runs directly in the global scope.

**Comment by artptr** [comment]
@ljharb but if we remove the `"airbnb/legacy"` string from `extends` property then all will be ok and local `"no-unused-vars": [2, { vars: "local" } ]` rule will be work because it will decide that `Foo` is a global variable in a script in a browser.

**Comment by artptr** [comment]
Also it may be returned to assumed behavior by adding
```
"env": {
  "node": false
}
```

**Comment by ljharb** [comment]
Right - this isn't a bug, because in 2016 everything should be run in a node context, and only after running through browserify/webpack should it be shipped to a browser.

You're certainly free to override the env settings in your eslint config, however!
