### ISSUE TITLE
version 6.1.0 fails without eslint-plugin-react

### ISSUE THREAD

**Issue by heldr** [airbnb/javascript#781]
Since 6.1.x update, **airbnb/base** cannot extend eslint-config without eslint-plugin-react.

It throws the following error:
```shell
Error: Cannot find module 'estraverse-fb'
```

**Comment by ljharb** [comment]
This seems like a duplicate of #751?

**Comment by heldr** [comment]
Actually not, 751 is just a warning from npm.

**Comment by heldr** [comment]
nvm, it's a babel-eslint error.

**Comment by ljharb** [comment]
Thanks, could you link to the issue on babel-eslint?

**Comment by heldr** [comment]
https://github.com/eslint/eslint/issues/5476

**Comment by ljharb** [comment]
See https://github.com/airbnb/javascript/pull/829
