### ISSUE TITLE
prefer-stateless with event handlers is problematic

### ISSUE THREAD

**Issue by kesne** [airbnb/javascript#784]
I noticed with the latest version of the config that I get a lot of prefer-stateless warnings on components that just use props and event handlers. However, this is hard to do when the `react/jsx-no-bind` rule is enabled, which stops you from making functions for event handlers in the render path.

For example, here's a component that only uses props and an event handler that the linter will tell me to turn into a stateless component.

```javascript
class MyComponent extends React.Component {
  constructor(props) {
    super(props);

    this.handleClicked = this.handleClicked.bind(this);
  }

  handleClicked() {
    this.props.onClicked(this.props.name);
  }

  render() {
    return (
      <button onClick={this.handleClicked}>Click Me</button>
    );
  }
}
```

However, in the attempt to do so, you need to create a function in the render path, which causes the `react/jsx-no-bind` lint rule to blow up on you.

```javascript
function MyComponent({ onClicked, name }) {
  return (
    <div onClick={() => onClicked(name)}>Blow Me Up</div>
  );
}
```

You can work around this by defining the function outside of the JSX, but at that point you're just working around the linter.

**Comment by ljharb** [comment]
This is a [current bug](https://github.com/yannickcr/eslint-plugin-react/issues/491#issuecomment-194042537) in `eslint-plugin-react` - components with instance methods should *not* be made stateless, because they *have* state - `this` is their state.

For now, I'd just disable the rule.

**Comment by ljharb** [comment]
This should be fixed now in eslint-plugin-react. The next release of the linter config will definitely include it (if the current one doesn't already)

**Comment by barrymichaeldoyle** [comment]
You could have set it up like this:

```
const blowMeUp = (onClicked, name) => () => onClicked(name);

function MyComponent({ onClicked, name }) {
  return (
    <div onClick={blowMeUp(onClicked, name)}>Blow Me Up</div>
  );
}
```

**Comment by ljharb** [comment]
@barrymichaeldoyle while that's fine for that use case (passing it into a div), for a custom component that would be bad because it'd create a new function every render - the only option there is a class-based component.

**Comment by barrymichaeldoyle** [comment]
Ah right, good point.

**Comment by ljharb** [comment]
@obouchari you can see in the example [here](https://github.com/airbnb/javascript/issues/784#issuecomment-417659185) that every render - every time `MyComponent` gets called - `blowMeUp` will be called, and will create a brand new function, that will be `!==` to the one passed on the previous render. For HTML elements like div, it doesn't matter, but if instead of a div it was a `class Foo extends React.PureComponent`, then the PureComponent optimization (ie, not rerendering when the props are all `===` from the previous render) would be bypassed, and you'd get an unnecessary rerender. These rerenders can add up to big performance problems on a larger page.

**Comment by ljharb** [comment]
@obouchari if you create it on every *render* then that’s a problem; but the constructor of a class component isn’t called on every render.

**Comment by obouchari** [comment]
Got you!  Thanks, that was really helpful.
