### ISSUE TITLE
object spread

### ISSUE THREAD

**Issue by vvo** [airbnb/javascript#788]
Are you using object spread? I had to add:

```js
  "parserOptions": {
      "ecmaFeatures": {
          "experimentalObjectRestSpread": true
      }
  }
```

To my eslintrc to have it working. Thanks

**Comment by ljharb** [comment]
Since object spread is not yet standard (it's still only [stage 2](https://github.com/tc39/ecma262)), we do not yet support or recommend it.

**Comment by silverlight513** [comment]
@ljharb, You say you don't use it or recommend object spreads but they're [here](https://github.com/airbnb/javascript#objects--rest-spread) in the styleguide. Does Airbnb support them now?

**Comment by ljharb** [comment]
Yep, as of last week, they're now stage 3

**Comment by silverlight513** [comment]
Everyone still needs to use a transpiler right now to use them though. Is the reason they've been added is because they're more of a certainty now and the spec is less likely to change. (Sorry, not up to speed on the stage process)

**Comment by ljharb** [comment]
@silverlight513 yes, the guide assumes you're using babel, and encourages it (and the linter config requires it implicitly).

Yes, in stage 3, features only change in response to browser feedback about implementation feasibility or web compatibility, and this one in particular is highly unlikely to change.
