### ISSUE TITLE
Mistake in "bad example" constructor definition with semicolons

### ISSUE THREAD

**Issue by nyanon** [airbnb/javascript#792]
https://github.com/airbnb/javascript#constructors
Have:
```
Queue.prototype.pop = function () {
  const value = this._queue[0];
  this._queue.splice(0, 1);
  return value;
}
```
Need to write semicolons ";" in the end:
```
Queue.prototype.pop = function () {
  const value = this._queue[0];
  this._queue.splice(0, 1);
  return value;
};
```
Also same in https://github.com/airbnb/javascript#modules

**Comment by ljharb** [comment]
I see the example you're referring to in the constructors section (although since it's under "bad", it's ok to have other things wrong in it) but I don't see the semicolon example you're referring to in the modules section?

**Comment by lencioni** [comment]
> although since it's under "bad", it's ok to have other things wrong in it

While I agree with this, it is best if the "bad" examples only have things wrong with them that they are illustrating--for maximum clarity.
