### ISSUE TITLE
Running eslint with airbnb on the command line fails

### ISSUE THREAD

**Issue by LucasKA** [airbnb/javascript#811]
I was planning on running the airbnb linter in my pre-commit hooks, but if I try to run it on the cli using the react version "extends: airbnb", results in an error.

`eslint ./src/lib/constants.js --debug
  eslint:cli Running on files +0ms
  eslint:ignored-paths Looking for ignore file in /Users/Lucas/Development/the-culture-list/theCultureList +24ms
  eslint:ignored-paths Could not find ignore file in cwd +1ms
  eslint:glob-util Creating list of files to process. +1ms
  eslint:cli-engine Processing /Users/Lucas/Development/the-culture-list/theCultureList/src/lib/constants.js +2ms
  eslint:cli-engine Linting /Users/Lucas/Development/the-culture-list/theCultureList/src/lib/constants.js +1ms
  eslint:config Constructing config for /Users/Lucas/Development/the-culture-list/theCultureList/src/lib/constants.js +0ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Loading /Users/Lucas/Development/the-culture-list/theCultureList/.eslintrc +2ms
  eslint:config-file Loading config file: /Users/Lucas/Development/the-culture-list/theCultureList/.eslintrc +2ms
  eslint:config-file Loading airbnb +46ms
  eslint:config-file Attempting to resolve eslint-config-airbnb +0ms
  eslint:config-file Loading JS config file: /usr/local/lib/node_modules/eslint-config-airbnb/index.js +0ms
  eslint:config-file Loading /usr/local/lib/node_modules/eslint-config-airbnb/rules/react.js +1ms
  eslint:config-file Loading JS config file: /usr/local/lib/node_modules/eslint-config-airbnb/rules/react.js +0ms
/usr/local/lib/node_modules/eslint-config-airbnb/rules/react.js:
	Configuration for rule "react/display-name" is invalid:
	Value "data["0"].ignoreTranspilerName" has additional properties.

Referenced from: airbnb
Referenced from: /Users/Lucas/Development/the-culture-list/theCultureList/.eslintrc
Error: /usr/local/lib/node_modules/eslint-config-airbnb/rules/react.js:
	Configuration for rule "react/display-name" is invalid:
	Value "data["0"].ignoreTranspilerName" has additional properties.

Referenced from: airbnb
Referenced from: /Users/Lucas/Development/the-culture-list/theCultureList/.eslintrc
    at validateRuleOptions (/usr/local/lib/node_modules/eslint/lib/config/config-validator.js:118:15)
    at /usr/local/lib/node_modules/eslint/lib/config/config-validator.js:165:13
    at Array.forEach (native)
    at Object.validate (/usr/local/lib/node_modules/eslint/lib/config/config-validator.js:164:35)
    at load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:521:19)
    at /usr/local/lib/node_modules/eslint/lib/config/config-file.js:388:36
    at Array.reduceRight (native)
    at applyExtends (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:365:28)
    at load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:528:22)
    at /usr/local/lib/node_modules/eslint/lib/config/config-file.js:388:36`

Any ideas why it might be failing here?

**Comment by ljharb** [comment]
You're installing eslint globally - you want to install it locally instead, and run it via `npm run-script`. Global installs can't access other global installs.
