### ISSUE TITLE
'React' is defined but never used

### ISSUE THREAD

**Issue by scwood** [airbnb/javascript#818]
```
src/client/index.jsx
--------------------
error  'React' is defined but never used  no-unused-vars
```

My .eslintrc:

```json
{
  "extends": "airbnb",
  "plugins": [
    "react"
  ]
}
```

Package versions:

```json
"eslint": "^2.7.0",
"eslint-config-airbnb": "^6.2.0",
"eslint-plugin-react": "^4.2.3",
```

I've tried setting 'React' under globals, I've tried adding the `jsx-uses-react` rule, (which appears to be set already). Neither worked for me. Removing `"extends": "airbnb"` fixes this issue.

**Comment by ljharb** [comment]
What version of React do you have installed? What does `index.jsx` look like?

**Comment by scwood** [comment]
Hey thanks for the response.

```json
"react": "^0.14.8",
"react-dom": "^0.14.8",
"react-router": "^2.0.1"
```

```jsx
// index.jsx

import React from 'react';
import { render } from 'react-dom';

import routes from './config/routes.jsx';

render(routes, document.getElementById('app'));
```

```jsx
// config/routes.jsx

import React from 'react';
import { Router, Route, hashHistory } from 'react-router';

function HelloWorld() {
  return <div>Hello World</div>;
}

const routes = (
  <Router history={hashHistory}>
    <Route path="/" component={HelloWorld} />
  </Router>
);

export default routes;
```

**Comment by ljharb** [comment]
ok, so why are you importing React in `index.jsx` when you have no JSX, and you don't reference `React`?

**Comment by scwood** [comment]
Whoops. Seems obvious, now that you say it, thanks for the help.

**Comment by vance** [comment]
This is still a problem as it occurs in Unit tests which may not include jsx. 
![image](https://user-images.githubusercontent.com/145471/81116251-e341a900-8ed9-11ea-93cd-5afd85cf7747.png)
I've also tried overriding as such:
![image](https://user-images.githubusercontent.com/145471/81116302-f6547900-8ed9-11ea-8940-0c1f7332de14.png)

**Comment by ljharb** [comment]
@vance the rule only warns if there's jsx in the file, and the import is only necessary there, so it shouldn't cause any issue.

**Comment by vance** [comment]
Ah, duh.
