### ISSUE TITLE
Max line length of 100 characters: allow URLs?

### ISSUE THREAD

**Issue by andreyvolokitin** [airbnb/javascript#819]
It is common to have URLs in comments, but they do not fit in ```"maximumLineLength": 100``` rule

**Comment by ljharb** [comment]
That's why our linter config ignores URLs https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/style.js#L51 :-)

**Comment by andreyvolokitin** [comment]
Yep, I needed this for JSCS config also, but could not find the right place to open an issue, it seems like I need to go to some other repository... Maybe [here](https://github.com/jscs-dev/node-jscs/blob/master/presets/airbnb.json)

**Comment by ljharb** [comment]
aha, yes - we don't maintain the jscs preset currently, so you'd need to file it there.
