### ISSUE TITLE
Arrow function IIFE parens

### ISSUE THREAD

**Issue by shhac** [airbnb/javascript#828]
In section `20.1` there is the following

```
// bad
(function () {
  const name = 'Skywalker'
  return name
})()

// good
(() => {
  const name = 'Skywalker';
  return name;
}());

// good (guards against the function becoming an argument when two files with IIFEs are concatenated)
;(() => {
  const name = 'Skywalker';
  return name;
}());
```

The two arrow functions commented as good are actually invalid and will throw SyntaxErrors because you can't call them this early (per spec) as they are not CallExpressions, see http://stackoverflow.com/questions/34589488/es6-immediately-invoked-arrow-function

You would need to wrap them in extra parenthesis first.

**Comment by hedgehog34** [comment]
They are wrapped in enclosing parenthesis already. And they seem to work (at least transpiled by Babel), with and without parameter - [jsfiddle](https://jsfiddle.net/hedgehog34/c8sazLr6/)

**Comment by shhac** [comment]
@hedgehog34 
Babel doesn't throw errors because they are transpiled to `function` expressions, which is are _CallExpression_ so does not throw SyntaxErrors.

**Comment by ljharb** [comment]
Although we recommend babel even when native arrow functions are supported - and as such, the examples would continue to work - this is a good catch. I'll update the guide to fix this.

Immediately invoked functions really don't have a use case in a world with modules anyways, so nobody should really run into this case :-)
