### ISSUE TITLE
Clean install warns about the react and a11y plugin, but not the import plugin

### ISSUE THREAD

**Issue by tleunen** [airbnb/javascript#830]
I know there's a PR in the works to create a new "base" package, but I just did a clean install in a project and was surprised it didn't warn about the import plugin. Do you know why?
```
├── eslint-config-airbnb@7.0.0 
├── UNMET PEER DEPENDENCY eslint-plugin-jsx-a11y@^0.6.2
├── UNMET PEER DEPENDENCY eslint-plugin-react@^4.3.0
```

**Comment by ljharb** [comment]
Because we haven't published the updated package that uses eslint-plugin-import yet.

**Comment by tleunen** [comment]
Haha, make sense ;-)
