### ISSUE TITLE
release eslint-plugin-react@^5.0.0 version

### ISSUE THREAD

**Issue by tmc** [airbnb/javascript#832]

**Comment by ljharb** [comment]
Per https://github.com/airbnb/javascript/commit/4ab741190c2926c188edeefa9fb70ae0b8f585ec#commitcomment-17147175:
> at the moment, the plugin requires v4.3 of the react plugin. I plan on releasing an update soon, but you'll need to either ignore the warning or stick with v4.3 for now.

**Comment by ljharb** [comment]
v8.0.0 of `eslint-config-airbnb` is published.
