### ISSUE TITLE
eslint-plugin-jsx-a11y breaking changes

### ISSUE THREAD

**Issue by boldkhuu** [airbnb/javascript#839]
Lint works wrong with [eslint-plugin-jsx-a11y latest release](https://github.com/evcohen/eslint-plugin-jsx-a11y/releases/tag/1.0.0). They have several breaking changes on their rule names.

**Comment by ljharb** [comment]
This is both fixed in #838, and shouldn't be an issue since the published version of this linter config peerDepends on `^0.6.2` of the a11y plugin, which doesn't include v1.0.
