### ISSUE TITLE
Please document no-restricted-syntax

### ISSUE THREAD

**Issue by Arcanemagus** [airbnb/javascript#840]
After moving to `eslint-config-airbnb-base` from `eslint-config-airbnb` I am now getting warnings related to the `no-restricted-syntax` rule (specified [here](https://github.com/airbnb/javascript/blob/d06147d279549c08dacd2ef4835cbccf2b1f1159/packages/eslint-config-airbnb-base/rules/best-practices.js#L118)), but no documentation backing this up exists in [README.md](https://github.com/airbnb/javascript/blob/763416260ab791d2efd2cf175100d8e506bb7eaa/README.md).

Can the documentation be updated explaining the reasoning behind the choices in this rule?

----

In my particular case this was triggered on a `for...in` loop, so I'm _guessing_ that having `ForInStatement` in the list of forbidden nodes would fall into the [Iterators and Generators](https://github.com/airbnb/javascript/blob/763416260ab791d2efd2cf175100d8e506bb7eaa/README.md#iterators--nope) section.

**Comment by ljharb** [comment]
Yes, that's right - the guide [discourages](https://github.com/airbnb/javascript#iterators--nope) imperative loops of all kinds, which covers `for..in` as well as `break` and `continue`.

Labels are GOTO so I assume there'd be no question about those, `debugger` is already prevented with `no-debugger`, and `with` doesn't work in strict mode anyways.

**Comment by mhofman** [comment]
`break` statements are still needed for `switch` / `case` blocks.

**Comment by ljharb** [comment]
aha, that's a very good point. I'll remove that and publish a patch.

**Comment by ljharb** [comment]
Published as v1.0.2

**Comment by danez** [comment]
about `for..in`: We use this for looping over plain javascript objects, as there is no `.map` or `.forEach()`. How do you handle this case at airbnb?

**Comment by ljharb** [comment]
@danez `Object.keys(obj).forEach(key => { obj[key] })` - same works with `Object.entries` and `Object.values`, and with all the array iteration methods. There's never a need to use a loop.

**Comment by lxcid** [comment]
Since async/await is [stage 3](https://babeljs.io/docs/plugins/preset-stage-3/) and there's no way to async/await with higher-order functions like `forEach`, this is too restrictive for me.

**Comment by Arcanemagus** [comment]
@lxcid You can either add all the `Promise`s to an array and await on `Promise.all(stuff)` after the loop, or you can just disable the rule in your own ESLint configuration.

**Comment by lxcid** [comment]
Thanks! That was what I end up doing. Great tip!

**Comment by ljharb** [comment]
@lxcid `async`/`await` is stage 4, and is part of ES2017 which was published last month.

Indeed, `Promise.all` and functional approaches are the way to go here. `for..in` should never be used.
