### ISSUE TITLE
Naming convention for Promise.

### ISSUE THREAD

**Issue by skatpgusskat** [airbnb/javascript#848]
I'm so confused. In general case, we name the function like 'verb-what' like ``` getItem ```, ``` setQuantity ```, ``` request ```, etc.

On case of GET functions, we can guess what type or what kind of values will return.

How about the function which return promise witch will return some other values?
Or, a just Promise. How should I name that?

For example, there are a promise which will query the user's name from database, should the promise name be ``` getName ``` ? or ``` getNamePromise ```?

In first case(getName), other co-worker could misguess that this function will return name synchronously, so he could directly assign the variables value, like this,
```
const name = getName();
console.log(name) // Promise {[[PromiseStatus]]: "pending"....}
```

it doesn't seem good to add 'Async' suffix (```getNameAsync```). 
adding prefix 'promise' ( ```promiseGetName``` ) neither.

``` promiseGettingName ```
``` gettingName ```
...
hmm....

Any good idea for this?

**Comment by skatpgusskat** [comment]
Do the verbs, like 'fetch' or 'load', look like return promise?
Because when I use Fetch API, it was ok for name of 'fetch' which return promise.

**Comment by ljharb** [comment]
We haven't yet written up best practices for Promises (see #597 #216).

I'm not convinced any special naming is needed. Certainly add "Async" or "Promise" would be subpar.

**Comment by skatpgusskat** [comment]
But so many of .NET frameworks and libraries use 'Async' suffix so it make sure that function will return Task<> (promise) or that would need ```await```.

How we could think A function is Sync or Async? 
In browser(specifically react-redux environment), the programmer might not consider about Promise's naming because there are a few Promise work against Node.js.

Generally functions that name with prefix 'get' really look it return some value immediately, isn't it?
I think this could make developer confused it is Async function or Sync function. Should we have to check always it is really return value immediately or promise?

It is just my supposition, but this repository's guide is more fit to web frontend, not Node.js.

**Comment by ljharb** [comment]
JS doesn't have types - so you know what the function will return the same way as with every other function: by referring to its implementation/documentation. A convention in a codebase can certainly allow you to pre-memorize what it means, but you still have to learn its meaning in the first place.

Also, `async function` and `Async function` and "async function that takes a node-style callback" all mean that the term is confusing - at this point, `async function` means only a function that is syntactically guaranteed to return a Promise.

**Comment by ljharb** [comment]
Closing this in favor of #216.

**Comment by chardskarth** [comment]
I was searching for something like this: A naming convention to let my code readers know instantly that the variable is a promise. How about prepending **when**?

```
let fsJetpack = require("fs-jetpack");
let whenCurrentTree = fsJetpack.inspectTreeAsync(contentsPath);
```

I thought of the word when because of the ff reasons:

- it sounds like then. a promise standard word
- in english terms, it should mean 'when this happens'

**Comment by RichAyotte** [comment]
Now that `async/await` is the norm, how about prefixing with  **for**?
```js
const forCustomerData = new Promise(...)
const customerData = await forCustomerData()
```
