### ISSUE TITLE
Conditional expression in Arrow function

### ISSUE THREAD

**Issue by gabrielenosso** [airbnb/javascript#856]
The no-confusing-arrow rule is enabled, so the following syntax is an error:
```const fn = a => a ? 1 : 2;```

The arrow-body-style rule is enabled, so the following syntax is an error too:
```const fn = a => { return a ? 1 : 2; };```

So the only way to write it following the rules is the following one:
```const fn = a => { if (a) return 2; return 3; };```

Is this correct? Or is there another way to write the same stuff in a different way?

**Comment by tough-griff** [comment]
The `allowParens` option is set to true, so
```js
const fn = a => (a ? 1 : 2);
```
should not cause a linter error.

**Comment by medifle** [comment]
https://github.com/airbnb/javascript#arrows--confusing

Simply copy and paste the code seemed as `good` practice.

```js
const itemHeight = (item) => { return item.height > 256 ? item.largeSize : item.smallSize; };

itemHeight();

```

The error reports `1:30  error  Unexpected block statement surrounding arrow body  arrow-body-style
 `

**Comment by ljharb** [comment]
@medifle thanks, we don't lint the readme, so sometimes the examples can go out of sync.

**Comment by tejalbadgujar** [comment]
let fun = (question, yes, no) => {
    if (confirm(question)) yes();
    else no();
};

let asking = fun("Do you agree?", function() { alert("You agreed."); }, function() { alert("You canceled the execution."); });

is this right way or wrong way to explore the arrow ????

**Comment by ljharb** [comment]
@tejalbadgujar if your function doesn’t use `this` or `arguments` or `super`, and isn’t `new`ed, then there’s really no difference. All three of those functions could be arrows or normal ones, just the same.

**Comment by tejalbadgujar** [comment]
Got it
