### ISSUE TITLE
Difference in Linters? (JSHint vs ESLint)

### ISSUE THREAD

**Issue by mitsos1os** [airbnb/javascript#862]
Hi guys,
Just a simple question... Is there any difference in using the JSHint config file versus the eslint file (including all required packages)???

Are there any rules skipped (especially in JSHint which has smaller size than all base rules of ESLint)?

Thanks

**Comment by ljharb** [comment]
We don't use the jshint config, so I'm not actually sure how up to date it is. In general, jshint does not deal with style rules, so there's bound to be a lot of gaps in what jshint supports vs what eslint supports.

PRs are welcome to keep the jshint config up to date!
