### ISSUE TITLE
Peer dependencies changed within a specific version

### ISSUE THREAD

**Issue by trygveaa** [airbnb/javascript#863]
When depending on `eslint-config-airbnb` and specific versions of it's peer dependencies, the release of  `eslint-config-airbnb-base 1.0.4` made npm start to complain about `UNMET PEER DEPENDENCY` because it upgraded the peer dependency `eslint-plugin-import` from `^1.5.0` to `^1.6.0`.

In the project where this problem occurred, we depend on specific versions of all dependencies rather than specifying versions with caret or version ranges, because we want all developers to have the same environment. When `eslint-config-airbnb 8.0.0`, we updated the dependencies to be:

```
    "eslint": "2.8.0",
    "eslint-config-airbnb": "8.0.0",
    "eslint-plugin-import": "1.5.0",
    "eslint-plugin-jsx-a11y": "1.0.2",
    "eslint-plugin-react": "5.0.1"
```

`eslint-config-airbnb` depends on `eslint-config-airbnb-base ^1.0.2`. The latest version at the time were `1.0.2`, so that were installed. Both `eslint-config-airbnb 8.0.0` and `eslint-config-airbnb-base 1.0.2` specifies the peer dependency `eslint-plugin-import ^1.5.0`, so that worked fine.

However, when `eslint-config-airbnb-base 1.0.4` were released, it changed the peer dependency to `eslint-plugin-import ^1.6.0`. Since `eslint-config-airbnb` specifies the dependency with a caret, `eslint-config-airbnb-base 1.0.4` is now installed. Since `eslint-plugin-import 1.5.0` doesn't match the peer dependency `eslint-plugin-import ^1.6.0`, you get an `UNMET PEER DEPENDENCY` error.

I don't think one release of `eslint-config-airbnb` should change peer dependencies over time, which is in effect what happened here. I'm not completely sure what the best solution is, but maybe it would be to depend on a specific version of `eslint-config-airbnb-base`, instead of a caret version.

**Comment by ljharb** [comment]
Depending on specific versions at the top level does not, in fact, ensure all developers have the same environment. The only way to ensure that is to check `node_modules` into version control, or, to use shrinkwrap - both of which would have prevented the issue you're running into.

Dependencies can change with every release, as they're not directly part of the API that semver governs. More to the point, this could happen just as easily with two entirely unrelated packages (and often does in the React ecosystem), and you wouldn't usually have the recourse of filing an issue to a single repo about it.

What I'd recommend is for you to use semver ranges in package.json (to convey the right semantics for the version you expect) and then use shrinkwrap to ensure that, in fact, all developers have the same dependency tree. That way, you won't have sub-dependencies updating out from underneath you on every `npm install`.
