### ISSUE TITLE
A few questions regarding "line length of 100" rule

### ISSUE THREAD

**Issue by droganov** [airbnb/javascript#865]
Hi.
I'm dealing with SVG in react, And I'm getting linter errors for svg elements:

```
function getIcon(name) {
  switch (name) {
    case 'bell':
      return <path d="M14.65 8.512c-2.28-4.907-3.466-6.77-7.19-6.693-1.328.026-1.01-.963-2.022-.588-1.01.375-.143.924-1.177 1.773-2.9 2.383-2.634 4.587-1.288 9.84.567 2.213-1.367 2.32-.602 4.465.56 1.564 4.68 2.22 9.025.607 4.347-1.613 7.086-4.814 6.527-6.378-.765-2.146-2.31-.962-3.272-3.028zm-3.726 8.083c-3.882 1.44-7.072.594-7.207.217-.232-.65 1.253-2.816 5.69-4.463 4.44-1.648 6.916-1.037 7.175-.312.153.43-1.775 3.116-5.658 4.557zM9.676 13.1c-2.03.754-3.44 1.615-4.353 2.39.643.584 1.847.726 3.046.28 1.526-.564 2.465-1.865 2.094-2.903l-.016-.036c-.25.083-.508.172-.772.27z" />;
```

So the question is there a way to legalise svg-related tags?

Second question: I know that my scripts will be bundled, packed and delivered to the client as one looooong line. Assuming this is there a reason to use "line length" rule?

**Comment by ljharb** [comment]
That'd be up to `eslint` - I've filed https://github.com/eslint/eslint/issues/5805 to allow max-len to ignore long strings, but as of now you'd have to disable the entire rule for that line.

Linters deal with the code as you wrote it - how it ends up in the browser is always irrelevant. The rule is so that lines *in your editor* aren't too long.

**Comment by droganov** [comment]
@ljharb I think I could override this https://github.com/airbnb/javascript/blob/4540293d44ed2613d8ed6e478455a7433fad7a61/packages/eslint-config-airbnb-base/rules/style.js#L53

with `ignorePattern` to skip `path` elements for example?

**Comment by ljharb** [comment]
Sure, that seems reasonable.

**Comment by VladShcherbin** [comment]
Would be great to see this enabled.

**Comment by ljharb** [comment]
This is waiting on https://github.com/eslint/eslint/pull/7049 to be merged, and deployed.

**Comment by 1gory** [comment]
/* eslint max-len: ["error", { "ignorePattern": "<path([\s\S]*?)\/>" }] */
Is correct?

**Comment by ljharb** [comment]
This has been released.

@1gory ignorePattern might work, but the latest config ignores lines with long strings, so nothing need be done.

**Comment by maxr37** [comment]
> /* eslint max-len: ["error", { "ignorePattern": "<path([\s\S]*?)/>" }] */
> Is correct?

this worked for me, I had to double-escape the backslashes as mentioned in the documentation https://eslint.org/docs/rules/max-len
so it's like this
"ignorePattern": "<path([\\s\\S]*?)/>"

**Comment by rpivo** [comment]
@maxr37 did you mean `"ignorePattern": "<path([\\s\\S]*?)/>"`

**Comment by maxr37** [comment]
@rpivo yes, exactly as you said. I should have pasted using the code tag so it doesn't get escaped.
`"ignorePattern": "<path([\\s\\S]*?)/>"`
