### ISSUE TITLE
Conflicting rules

### ISSUE THREAD

**Issue by mastertinner** [airbnb/javascript#867]
Since `9.0.0` I'm getting lots of `no-extra-parens` errors. However, if I remove the parentheses, the errors turn into `react/wrap-multilines` errors. I think these two rules are conflicting.

**Comment by ljharb** [comment]
Can you provide an example? Per our guide, multiline jsx must indeed always be wrapped in parens, so if `no-extra-parens` is conflicting with that, I may need to disable it for now.

**Comment by ljharb** [comment]
Closed with https://github.com/airbnb/javascript/commit/56a524a47ed0b71f348d6bfaa42289d562f6bc5b

**Comment by mastertinner** [comment]
thanks, @ljharb!
