### ISSUE TITLE
Item 8.3 gives eslint error in airbnb-base

### ISSUE THREAD

**Issue by jacobp100** [airbnb/javascript#869]
Inputting the direct example from the style guide below gives a lint error of `no-extra-parens`.

https://github.com/airbnb/javascript#arrows--paren-wrap

```js
// good
[1, 2, 3].map(number => (
  `As time went by, the string containing the ${number} became much ` +
  'longer. So we needed to break it over multiple lines.'
));
```

**Comment by ljharb** [comment]
Per this, and #867, I think I'm going to have to re-disable `no-extra-parens`.
