### ISSUE TITLE
eslint-config-airbnb-base/legacy 'func' was used before it was defined

### ISSUE THREAD

**Issue by raxell** [airbnb/javascript#872]
Why the linter throws an error with this code?
```javascript
a();

function a() {
  // ...
}
```
I have bypassed the error in this way, but I don't like the idea of overriding the rules of the style guide.
```json
"no-use-before-define": ["error", { "functions": false }]
```
Should't it be the default behavior, instead of throw the error?
Am I forced to declare the function before the use, even if I use the "function declaration syntax"?

**Comment by ljharb** [comment]
Indeed the function should be declared before its use, whether it's an expression or a declaration - our guide discourages relying on hoisting.

**Comment by chirag04** [comment]
@ljharb what about circular dependencies among functions?

**Comment by ljharb** [comment]
@chirag04 Luckily those are incredibly rare. Typically I see a circular dependency as a code smell, between functions or between modules. However, there are definitely a few cases where it's necessary - and that's what inline eslint comments are good for.

It's OK if, eyes open, your code deviates from a style guide, but the code should be profusely apologizing for it with comments, as opposed to the guide bending to allow for usually-bad patterns.
