### ISSUE TITLE
Better method binding (arrow functions as class properties)

### ISSUE THREAD

**Issue by eloytoro** [airbnb/javascript#873]
The current style forces to keep track if the method has been binded or not, also causes redudant logic for each instance of the class, I would consider it bad style even if there's no other solution

Using arrow functions as class members makes them so they **always** have the class's context and it can't be changed. Which should be the proper behaviour for most react class methods.

```jsx
  // bad
  class extends React.Component {
    onClickDiv() {
      // do stuff
    }

    render() {
      return <div onClick={this.onClickDiv.bind(this)} />
    }
  }

  // bad
  class extends React.Component {
    constructor(props) {
      super(props);

      this.onClickDiv = this.onClickDiv.bind(this);
    }

    onClickDiv() {
      // do stuff
    }

    render() {
      return <div onClick={this.onClickDiv} />
    }
  }

  // good
  class extends React.Component {
    onClickDiv = () => {
      // do stuff
    }

    render() {
      return <div onClick={this.onClickDiv} />
    }
  }
```

**Comment by ljharb** [comment]
Class properties are not yet standard - still stage 1. Your "good" example would need to be inside the constructor, at which point, it's no different from your second "bad" example - which is why that's our "good" example.
