### ISSUE TITLE
Rule 3.6 (use property value shorthand) leads to refactoring errors

### ISSUE THREAD

**Issue by philippevk** [airbnb/javascript#874]
Consider the following code...

``` JavaScript
const url = 'http://some-service.com/';
const data = { foo: 'bar' };
$.ajax({ url, data });
```

One day you decide that "apiUrl" is a better name so you rename the variable and end up with...
``` JavaScript
const apiUrl = 'http://some-service.com/';
const data = { foo: 'bar' };
$.ajax({ apiUrl, data });
```

And now you have an error.
My example may seem a little contrived but it's pretty common to have options parameters in javascript. At some point your variables names might happen to align with the option names, but it's usually just a coincidence.

What is your opinion on this?

**Comment by ljharb** [comment]
That's certainly a possible refactoring hazard - when you rename the variable, you definitely need to check/change all object shorthand uses of it.

I'm not sure this is a big concern, though - any more than renaming the parameter name in `function ({ url }) {` to `function ({ apiUrl }) {` might be. Things dealing with object property names are often brittle, and generally test coverage is where you make your code more robust.

**Comment by philippevk** [comment]
I disagree! The difference is that when you rename an option it's obvious that calling functions will have to be adjusted. But renaming local variables is supposed to be 100% safe. Enforcing this rule makes you double check your local renames. Another thing to worry about.

As for the point about tests, I don't think it's a good argument since the reality is simply that tests are not part of all projects for various (good & bad) reasons.

**Comment by ljharb** [comment]
Renaming local variables is still 100% safe, but in the case of object shorthands, it's a concise form of "local variable" *and* "property name" - the changing of which, as you mentioned, typically makes it obvious that calls would have to be adjusted.

**Comment by philippevk** [comment]
I just realized I didn't mention something that might not be obvious. I was talking about automated renames of IDEs, not manual renames.

If you rename the variable manually (copy-paste each occurrence) then you will most probably see that you have to change the function call. But AFAIK auto-renames don't do it, so you'd have to double-check your IDE's work, which kinda defeats the purpose.

**Comment by ljharb** [comment]
Automated renaming in IDEs in a loosely typed language, without manual review, has always been unsafe.

**Comment by philippevk** [comment]
You are rightLocal variable renames are the exception

**Comment by ljharb** [comment]
It seems with the advent of concise object notation in ES6 in June of 2015, that's no longer the case.

**Comment by philippevk** [comment]
Anyway, it's not a big deal as I can simply disable the rule for my project. I just wanted to let you know of the issue. Whether you support this use case is your decision!

**Comment by ljharb** [comment]
Personally I'd report it as a bug in the IDE's auto-refactoring mechanism rather than disabling a useful rule :-) but as always, you're quite welcome to override whatever rules you wish!
