### ISSUE TITLE
Sublime 3 linter configuration for jshint

### ISSUE THREAD

**Issue by Startouf** [airbnb/javascript#880]
There is a [.sublime-package](https://github.com/airbnb/javascript/blob/master/linters/SublimeLinter/SublimeLinter.sublime-settings) file for use with sublime 2. 

Sublime 3 uses a different linter system and I am afraid this configuration may not be valid anymore. I will try to confirm if is still working or not. But maybe someone already has a configuration file for sublime 3 ?

**Comment by jamez14** [comment]
I followed the same steps as in the [SublimeLinter.sublime-settings file](https://github.com/airbnb/javascript/blob/master/linters/SublimeLinter/SublimeLinter.sublime-settings), with one modification.

1. Install SublimeLinter at https://github.com/SublimeLinter/SublimeLinter
2. Open user preferences for the SublimeLinter package in Sublime Text 2
    * For Mac OS X go to _Sublime Text 2_ > _Preferences_ > _Package Settings_ > _SublimeLinter_ > _Settings - User_
3. Paste the contents of this file into your settings file **within the "linters" section** (see my example file below)
4. Save the settings file

I also installed the [SublimeLinter-eslint](https://github.com/roadhump/SublimeLinter-eslint) package because SublimeLinter 3 requires you to install each linter separately. 

My SublimeLinter.sublime-settings user file looks like this...

```
{
    "user": {
        "debug": false,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Hands/Hands.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "load/save",
        "linters": {
            "eslint": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "jshint_options": {
                "browser": true,
                "camelcase": true,
                "eqeqeq": true,
                "eqnull": true,
                "indent": 2,
                "jquery": true,
                "latedef": true,
                "maxlen": 80,
                "newcap": true,
                "node": true,
                "quotmark": "single",
                "strict": true,
                "trailing": true,
                "undef": true,
                "unused": true
            }
        },
        "mark_style": "squiggly underline",
        "no_column_highlights_line": false,
        "passive_warnings": false,
        "paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": false,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "javascript (babel)": "javascript",
            "magicpython": "python",
            "php": "html",
            "python django": "python",
            "pythonimproved": "python"
        },
        "warning_color": "DDB700",
        "wrap_find": true
    }
}
```

**Comment by Startouf** [comment]
Actually I have just created a `.jshintrc` file at the root of my project and copy pasted the airbnp configuration and it seems to be working fine.

**Comment by ljharb** [comment]
At this point, `eslint` is the defacto standard, and we highly recommend using that.

**Comment by RifatMahmudno-1** [comment]
// SublimeLinter Settings - User
`
{
	"linters": {
		"jshint":{
			"args" : ["--config", "E:\\Extensions\\codeExt\\.jshintrc"],
		}
	}
}
`
I'm using this settings but not working. Plz help

**Comment by ljharb** [comment]
See the closing comment - use eslint.
