### ISSUE TITLE
suggestion: enable react/no-string-refs

### ISSUE THREAD

**Issue by jimbolla** [airbnb/javascript#884]
From the [rule details](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-string-refs.md):

> Currently, two ways are supported by React to refer to components. The first one, providing a string identifier is considered legacy in the official documentation. Referring to components by setting a property on the this object in the reference callback is preferred.

From the [React docs](https://facebook.github.io/react/docs/more-about-refs.html#the-ref-string-attribute):

> React also supports using a string (instead of a callback) as a ref prop on any component, although this approach is mostly legacy at this point.

**Comment by ljharb** [comment]
Not a bad idea - we do use the string form pretty extensively internally though :-/

**Comment by jimbolla** [comment]
Mass update with some regex black magic probably isn't that hard. References to `this.refs.thing` become `this.thing` and `ref="thing"` becomes `ref={c => { this.thing = c; }}`. The only issue I could see running into is if you already had a this.thing and it became a collision.

**Comment by mikecousins** [comment]
This collides with the http://eslint.org/docs/rules/no-return-assign rule.

**Comment by ljharb** [comment]
This can actually be closed now, since this rule is enabled.

@mikecousins it only collides with that rule if you are improperly omitting the arrow function's block braces - ie, you want `(ref) => { this.ref = ref; }`, NOT `ref => this.ref = ref`.
