### ISSUE TITLE
Revisit Array#length shortcut recommendation (15.3)

### ISSUE THREAD

**Issue by dlwalsh** [airbnb/javascript#888]
It seems to me the Array#length shortcut recommendation is not particularly helpful and potentially dangerous. Replacing `if (arr.length > 0)` with `if (arr.length)` is less explicit and therefore detracts from readability. (Is `arr.length` a boolean?)

Worse, it can lead to some unintended consequences. The following is a common pattern in React:

```js
{arr.length && (
  <ul>
    {arr.map(item => (
      <li key={item.id}>
        <MyComponent {...item} />
      </li>  
    )}
  </ul>
)}
```

When `arr` is an empty array, the intent of this code snippet is to render nothing. But it actually outputs `0`.

**Comment by ljharb** [comment]
That's a very good point.

I'd definitely like to change [this section](https://github.com/airbnb/javascript#comparison--shortcuts) to require explicit comparisons for strings and numbers - although I don't think it's necessary or useful for booleans.

**Comment by randallreedjr** [comment]
Do changes of this nature require a linter update?

**Comment by ljharb** [comment]
There's no linter rule I'm aware of that lints this, so I don't think so.

**Comment by rudzikdawid** [comment]
![just learn this](https://i.stack.imgur.com/35MpY.png)

**Comment by ljharb** [comment]
Learning http://zero.milosz.ca/ is why it is bad. Humans should not have to do that - explicit is better than implicit.
