### ISSUE TITLE
Eslint 'react/prop-types' occur even on Stateless Functions's Destructuring Parameter.

### ISSUE THREAD

**Issue by skatpgusskat** [airbnb/javascript#889]
![issue](https://cloud.githubusercontent.com/assets/3580430/15392314/4eaf8430-1e01-11e6-8cd0-5144dd51a8e4.png)

I don't know about what is really core of problem.
I think the reason is in 3 things,
1. airbnb's eslint
2. my eslint plugin on editor
3. or eslint itself.

I think function's Desturctured Parameter should pass to eslint. how do you think about?

**Comment by ljharb** [comment]
The parameters you are destructuring in your SFC are indeed its props, and your SFC indeed needs explicit `propTypes` defined. Everything is working perfectly.
