### ISSUE TITLE
Bind react methods with ES class fields

### ISSUE THREAD

**Issue by kasperekt** [airbnb/javascript#891]
What do you think about taking advantage of arrow functions lexical scope in React components?
```js
class MyComponent extends React.Component {
  myMethod = () => {
    this.setState({ ... });
  }
}
```
That would eliminate the problem with binding methods in constructor
```js
class MyComponent extends React.Component {
  constructor(props) {
    super(props);
    this.myMethod = this.myMethod.bind(this);
  }

  myMethod() {
    this.setState({ ... });
  }
}
```

I think it looks much nicer and more readable.

**Comment by ljharb** [comment]
Class properties are still stage 1, and we do not recommend using any proposals prior to stage 3.

Once the proposal has advanced enough, we are certainly likely to recommend it.
