### ISSUE TITLE
How to avoid no-param-reassign?

### ISSUE THREAD

**Issue by icetbr** [airbnb/javascript#898]
Hi, could I get some directions in the following scenarios? Reading similar questions, I don't get how copying the properties to a new object (Object.assign) is appropriate.

```
users.forEach(user => {
      if (user.age > 21) {
        user.canDrink = true;
      }
});

decks.forEach(deck => {
      deck.cards = utils.sort(deck.cards, myArrayWithCustomSortingRules);
});
```

Thanks

**Comment by ljharb** [comment]
```js
const usersWithCanDrink = users.map(user => Object.assign(user, {
  canDrink: user.age > 21,
}));

const sortedDecks = decks.map(deck => Object.assign(deck, {
  cards: utils.sort(deck.cards, myArrayWithCustomSortingRules),
}));
```

**Comment by icetbr** [comment]
OK, could I get some pointers on why to do this? I'm googling for "Object.assign", "avoid mutation in javascript", "javascript mutation evil" and things like this. Cannot find a good source.

I'm reading the polyfill, for instance, and it doesn't seem to add much to my approach.
- it checks I don't have a null value in my array
- it checks the object has the property already, and I'm not creating it on the spot

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign
```
if (typeof Object.assign != 'function') {
  Object.assign = function(target) {
    'use strict';
    if (target == null) {
      throw new TypeError('Cannot convert undefined or null to object');
    }

    target = Object(target);
    for (var index = 1; index < arguments.length; index++) {
      var source = arguments[index];
      if (source != null) {
        for (var key in source) {
          if (Object.prototype.hasOwnProperty.call(source, key)) {
            target[key] = source[key];
          }
        }
      }
    }
    return target;
  };
}
```

The closest rule I'm aware of is using methods to change an object state. So "user.setCanDrink(true)" would be better, but this seems to address a different concern.

**Comment by ljharb** [comment]
Oh, oops - the first argument to those `Object.assign`'s should be an empty object `{}` :-) that is what avoids the mutation.

**Comment by icetbr** [comment]
Yeah, but the method would be called something like "updateDrinkAgeStatus". The purpose of the method os to "mutate" the object. How would I go about doing that? If I should avoid mutation, how would I change an object data? Copying data into a new object gives me a new object.

There is some fundamental truth here I'm not seeing :-)

**Comment by ljharb** [comment]
@icetbr you're correct - if you have a method that is designed to mutate (something this guide discourages), then you'll run afoul of some of our rules. In this case, you may want to simply disable the rule using an eslint override comment. Alternatively, you could do `this.data = getNewTransformedCopyOfData(this.data)`.

**Comment by icetbr** [comment]
Yeah, I'm making an effort to see your point (to avoid mutate). I see something there. I will think more about this tomorrow. I will rewrite some of my code and see where this leads me. It is nothing critical, I'm just trying things in my spare time. I think you can close this issue, although I still would like some resources for reading. Is this related to functional programming? I will read into Immutable.js perhaps to check out their ideas.

Thanks so much for your time.

**Comment by ljharb** [comment]
@icetbr functional programming definitely espouses a no-mutation style, and most functional languages prohibit it. Immutable.js probably has some good resources.
