### ISSUE TITLE
Proposal: Enable comma-dangle linter rule

### ISSUE THREAD

**Issue by KevinGrandon** [airbnb/javascript#904]
Right now the README states that danging commas are good, but they appear to be disabled in .eslintrc[1]. I would propose that comma-dangle is enabled as a linter rule. It's good to be opinionated and this will prevent bikeshedding about style.

At the same time, maybe .eslintrc should be renamed to .eslintrc.js and export the configuration?

[1] https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/.eslintrc

**Comment by KevinGrandon** [comment]
Oops, when looking again it appears that this rule is defined here: https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/errors.js#L4

Can we be consistent and remove the one in eslint-config-airbnb-base/.eslintrc ?

**Comment by ljharb** [comment]
@KevinGrandon the `eslintrc` file you're talking about is for the package *itself*, and isn't something that anyone should be using or even discovering. The rules the package exports already comply with the styleguide.
