### ISSUE TITLE
import/no-unresolved raises false positives in many projects

### ISSUE THREAD

**Issue by chrisvfritz** [airbnb/javascript#906]
I think `import/no-unresolved` isn't the kind of rule that belongs in a linting config, because it makes a lot of assumptions about how modules are resolved, leading to false positives in many common cases. For example in Webpack, the use of aliases or non-traditional but registered extensions such as `.vue` will raise a linting error when Webpack actually has no problems resolving these files.

**Comment by ljharb** [comment]
The solution is to configure `eslint-plugin-import` with your custom resolution rules.

"What webpack does" is irrelevant - if you deviate from how the standard node require works, you're going to have to/want to configure *every* tool you use - webpack and eslint are just two of many.

**Comment by chrisvfritz** [comment]
Hmm... this plugin is definitely the only other tool that I've had to configure - even on large projects with very demanding build processes. So it does seem strange to have to duplicate that config, especially because it comes with no advantages I can see. Webpack and other build tools _already_ provide very helpful module resolution errors (on save with a dev server) and _never_ trigger false positives. 😕  

As someone who maintains a project generator for thousands of other developers, this is the only Airbnb rule I've had to disable completely - and it was in direct response to people opening issues about the confusing errors they get from ESLint when using Webpack aliases.

It seems clear this is a `wontfix` though, so I'll drop it.

**Comment by ljharb** [comment]
@chrisvfritz You can try to file an issue on https://github.com/benmosher/eslint-plugin-import about it - it may be possible for them to configure it to read webpack's configuration automatically.

**Comment by jimbolla** [comment]
There's a [webpack resolver for eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import/tree/master/resolvers/webpack) that handles things like extensions and aliases.

**Comment by alexicum** [comment]
@ljharb May be [eslint-import-resolver-webpack](https://github.com/benmosher/eslint-plugin-import/tree/master/resolvers/webpack) should be mentioned in [README.md](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/README.md) ?

**Comment by ljharb** [comment]
@alexicum i don't see the benefit; as I stated [here](https://github.com/airbnb/javascript/issues/906#issuecomment-223785677), deviating from node's require algorithm is not something that should be encouraged, even tacitly.
