### ISSUE TITLE
linting rule for https://github.com/airbnb/javascript#naming--filename-matches-export

### ISSUE THREAD

**Issue by mcfiredrill** [airbnb/javascript#907]
Is there any linting rule available for https://github.com/airbnb/javascript#naming--filename-matches-export?

**Comment by ljharb** [comment]
Not that I'm aware of, or else we'd be enforcing it :-)

**Comment by mcfiredrill** [comment]
Gotcha. Any idea of how difficult it would be to write one?

iPhone$B$+$iAw?.(B

2016/06/10 11:58$B!"(BJordan Harband <notifications@github.com> $B$N%a%C%;!<%8(B:

**Comment by ljharb** [comment]
@mcfiredrill no idea - please feel free to contribute to `eslint-plugin-import`, however, and we'd love to use the rule once it's written!

**Comment by mcfiredrill** [comment]
@ljharb Thanks, I'll try to check it out
