### ISSUE TITLE
Configuration for rule "prefer-arrow-callback" is invalid: Value "[object Object]" has more items than allowed.

### ISSUE THREAD

**Issue by chrisahardie** [airbnb/javascript#918]
I'm running the eslinter in atom, and whenever I make a change or save a js file I'm getting the following error:

> Error: C:\Users\chardie\Documents\Repos\spa-admin\node_modules\eslint-config-airbnb-base\rules\es6.js: Configuration for rule "prefer-arrow-callback" is invalid: Value "[object Object]" has more items than allowed.
> 
> Referenced from: C:\Users\chardie\Documents\Repos\spa-admin\node_modules\eslint-config-airbnb-base\index.js Referenced from: airbnb Referenced from: C:\Users\chardie\Documents\Repos\spa-admin.eslintrc
> Error: C:\Users\chardie\Documents\Repos\spa-admin\node_modules\eslint-config-airbnb-base\rules\es6.js:
> 	Configuration for rule "prefer-arrow-callback" is invalid:
> 	Value "[object Object]" has more items than allowed.
> Referenced from: C:\Users\chardie\Documents\Repos\spa-admin\node_modules\eslint-config-airbnb-base\index.js
> Referenced from: airbnb
> Referenced from: C:\Users\chardie\Documents\Repos\spa-admin\.eslintrc
>     at validateRuleOptions (C:\Users\chardie\Documents\Repos\spa-admin\node_modules\eslint\lib\config\config-validator.js:118:15)
>     at C:\Users\chardie\Documents\Repos\spa-admin\node_modules\eslint\lib\config\config-validator.js:165:13
>     at Array.forEach (native)
>     at Object.validate (C:\Users\chardie\Documents\Repos\spa-admin\node_modules\eslint\lib\config\config-validator.js:164:35)
>     at load (C:\Users\chardie\Documents\Repos\spa-admin\node_modules\eslint\lib\config\config-file.js:520:19)
>     at C:\Users\chardie\Documents\Repos\spa-admin\node_modules\eslint\lib\config\config-file.js:388:36
>     at Array.reduceRight (native)
>     at applyExtends (C:\Users\chardie\Documents\Repos\spa-admin\node_modules\eslint\lib\config\config-file.js:365:28)
>     at load (C:\Users\chardie\Documents\Repos\spa-admin\node_modules\eslint\lib\config\config-file.js:527:22)
>     at C:\Users\chardie\Documents\Repos\spa-admin\node_modules\eslint\lib\config\config-file.js:388:36

I saw this issue was discussed in https://github.com/airbnb/javascript/issues/897, and the suggested resolution was to uninstall the global eslint binary. I tried that, unfortunately it didn't work for me. Please let me know if you require further detail.

**Comment by ljharb** [comment]
It looks like you have `Repos/spa-admin.eslintrc`, but your actual project is `Repos/spa-admin/`. You want an `.eslintrc` in every project with "root" set to `true`, so that the project-specific config is not affected by a config file higher in the directory tree.

**Comment by chrisahardie** [comment]
@ljharb Very odd ... that file definitely doesn't exist in `Repos`, I tripled checked. I updated my .`eslintrc` at my project root to this:

```
{
    "env": {
        "browser": true,
        "es6": true
    },
    "parser": "babel-eslint",
    "plugins": ["react", "babel"],
    "extends": "airbnb",
    "rules": {
        "func-names": 0,
        "strict": 0,
        "quotes": 0,
        "react/prefer-es6-class": 0,
        "babel/generator-star-spacing": 0,
    },
    "root": true,
}
```

The path in the error has changed to point at the correct `.eslintrc` file, but the error persists:

```Error: C:\Users\chardie\Documents\Repos\spa-admin\node_modules\eslint-config-airbnb-base\rules\es6.js: Configuration for rule "prefer-arrow-callback" is invalid: Value "[object Object]" has more items than allowed.

Referenced from: C:\Users\chardie\Documents\Repos\spa-admin\node_modules\eslint-config-airbnb-base\index.js Referenced from: airbnb Referenced from: C:\Users\chardie\Documents\Repos\spa-admin.eslintrc
Error: C:\Users\chardie\Documents\Repos\spa-admin\node_modules\eslint-config-airbnb-base\rules\es6.js:
	Configuration for rule "prefer-arrow-callback" is invalid:
	Value "[object Object]" has more items than allowed.
Referenced from: C:\Users\chardie\Documents\Repos\spa-admin\node_modules\eslint-config-airbnb-base\index.js
Referenced from: airbnb
Referenced from: C:\Users\chardie\Documents\Repos\spa-admin\.eslintrc
    at validateRuleOptions (C:\Users\chardie\Documents\Repos\spa-admin\node_modules\eslint\lib\config\config-validator.js:118:15)
    at C:\Users\chardie\Documents\Repos\spa-admin\node_modules\eslint\lib\config\config-validator.js:165:13
    at Array.forEach (native)
   ...
```

I should point out I've been using the airbnb style guide for months with Atom's `linter-eslint`, it just started throwing this error this morning. Possible the cause of the error lies elsewhere?

Thanks for your help!

**Comment by ljharb** [comment]
What does `npm ls` show? Do you have the latest version of all the plugins installed?

**Comment by chrisahardie** [comment]
@ljharb You nailed it, I had a peer dependency missing. Not sure how I got into this state, really appreciate you lending a hand!
