### ISSUE TITLE
Consider to add rule that using .find() when selector with id in jQuery

### ISSUE THREAD

**Issue by minhbkpro** [airbnb/javascript#924]
This rules https://github.com/airbnb/javascript#jquery--find say:
```
// bad
$('.sidebar').find('ul').hide();

// good
$('.sidebar ul').hide();
```
but if using id selector it should be:
```
// bad (i mean it not good enough)
$('#sidebar ul').hide();

// this is best
$('#sidebar').find('ul').hide();
```
due to jquery performance https://learn.jquery.com/performance/optimize-selectors/#id-based-selectors

**Comment by ljharb** [comment]
The performance difference between ID-based selectors and class-based selectors since the time that was written has shrunk to a very small amount. The best practice nowadays is to never use IDs.
