### ISSUE TITLE
Array with objects

### ISSUE THREAD

**Issue by felixsanz** [airbnb/javascript#927]
What's prefered?

```javascript
const x = [{
  y: 'foo',
  z: 'bar',
}, {
  y: 'foo',
  z: 'bar',
}]
```

or

```javascript
const x = [
  {
    y: 'foo',
    z: 'bar',
  },
  {
    y: 'foo',
    z: 'bar',
  },
]
```

**Comment by ljharb** [comment]
Either seem acceptable to me.

**Comment by felixsanz** [comment]
The first is more beautiful but in the second you don't modify closing characters when adding new elements :confused:

**Comment by ljharb** [comment]
Thats a good point which does push more towards the second example.

**Comment by zbinxp** [comment]
I prefer the latter, it's clear and easy to modify. However the last comma
should be removed .

2016-06-23 16:12 GMT+08:00 Felix Sanz <notifications@github.com>:

**Comment by ljharb** [comment]
@zbinxp the final comma is required by our styleguide and linter config.

**Comment by dlwalsh** [comment]
I don't see the issue with adding a new element to the first example:

```js
   const x = [{
     y: 'foo',
     z: 'bar',
   }, {
     y: 'foo',
     z: 'bar',
+  }, {
+    y: 'foo',
+    z: 'bar',
   }]
```

The change is perfectly clear.

**Comment by felixsanz** [comment]
@dlwalsh you are modifying a line from the previous object just to add other object. If you want to add a new item, you shouldn't modify the others.

**Comment by dlwalsh** [comment]
I get what you're saying, but it doesn't strike me as an issue. No meaningful information was modified. The `}, {` line is just a glorified separator.

**Comment by suyuTech** [comment]
I prefer to use the second one.

**Comment by evilebottnawi** [comment]
@ljharb what style is preferred final?

**Comment by ljharb** [comment]
```js
const x = [
  {
    y: 'foo',
    z: 'bar',
  },
  {
    y: 'foo',
    z: 'bar',
  },
]
```
