### ISSUE TITLE
cannot override object-shorthand

### ISSUE THREAD

**Issue by MuffinLightning** [airbnb/javascript#933]
I can't seem to disable this rule...

here is my .estlintrc file:

```
{
	"parser": "babel-eslint",
	"plugins": [
		"react"
	],
	"env": {
		"node": true,
		"browser": true
	},
	"parserOptions": {
		"ecmaFeatures": {
			"jsx": true,
			"modules": true
		}
	},
	
	"extends": "airbnb",

	"rules": {
		comma-spacing: 2,
		new-cap: 2,
		object-shorthand: 0,
		one-var: [2, never],
		quotes: [1, single],
		space-before-blocks: 2,
		//react
		jsx-quotes: [2, prefer-double],
		react/jsx-curly-spacing: 2,
		react/jsx-max-props-per-line: [2, {maximum: 4}],
		react/jsx-no-duplicate-props: 2,
		react/jsx-no-undef: 2,
		react/jsx-indent: 0,
		react/jsx-indent-props: 0,
		semi: ["error", "always"],
		"indent": ["error", "tab", {"SwitchCase": 1}],
	}
```

But I still get:
> error    Expected method shorthand

**Comment by ljharb** [comment]
@MuffinLightning how are you running `eslint` - are you using a globally installed one, or the local one? What version of `eslint` do you have? (also, i'm not sure why you have the babel-eslint parser; it's not required for any of the features you're using there)

**Comment by MuffinLightning** [comment]
thanks for the reply @ljharb. Regarding babel-eslint parser, I guess I don't need it 👍 .

I am running eslint 2.15.5 , and it is local.

**Comment by ljharb** [comment]
@MuffinLightning the latest eslint is 2.13.1 - i'm not sure where you got v2.15?

**Comment by MuffinLightning** [comment]
@ljharb Oops sorry, was thinking npm for some reason x)

I am indeed running eslint 2.13.1.

**Comment by ljharb** [comment]
I assume if you remove "extends airbnb" that it no longer errors out?

If so, this sounds like an eslint bug itself, not an issue with our config plugin. Can you file it there?

**Comment by MuffinLightning** [comment]
@ljharb 

Thanks. The issue is resolved. I did something incredibly moronic that I'm too embarrassed to share :^)
