### ISSUE TITLE
"Bad option: 'esversion'." issue

### ISSUE THREAD

**Issue by haotangio** [airbnb/javascript#934]
I'm using the jshint presets of this repo with `"esversion": 6` option. But when I run grunt jshint job, it always throw "Bad option: 'esversion'." error which I don't know how to fix.

Did someone face this problem also?

**Comment by ljharb** [comment]
@haotangio what version of jshint are you running?

In general, `eslint` is the linter that the JS community has resoundingly settled on, so I'd recommend using that instead.
