### ISSUE TITLE
Allow peerDependency eslint@3.0.0

### ISSUE THREAD

**Issue by nutgaard** [airbnb/javascript#936]

**Comment by ljharb** [comment]
This is blocked by:
 - https://github.com/benmosher/eslint-plugin-import/pull/404
 - the release of https://github.com/sarbbottam/eslint-find-rules/pull/119
 - https://github.com/yannickcr/eslint-plugin-react/pull/657

**Comment by ljharb** [comment]
The base config is now published at v4.0.0. The main config is still blocked on a release of eslint-plugin-react (@yannickcr)

**Comment by geminiyellow** [comment]
hi @ljharb ,

Does that mean that can be upgraded to support eslint3?

```
Merge pull request #657 from jokeyrhyme/bump-deps-eslint-3  …
ljharb committed on GitHub 11 hours ago
```

**Comment by ljharb** [comment]
@geminiyellow no, because the update is not yet released (see the immediately preceding two comments).

**Comment by roderik** [comment]
A release candidate of the react plugin was released? Maybe a beta release for this project?

**Comment by ljharb** [comment]
I'm not a fan of rc's or alphas. I'm going to wait until the official release comes out - hopefully it will be soon, however.

**Comment by nwhitmont** [comment]
I just tried to install the package https://www.npmjs.com/package/eslint-config-airbnb but it failed with this error FYI

**Comment by merlinpatt** [comment]
v6.0.0 will be released in the coming hours according to the most recent comment on that thread

**Comment by merlinpatt** [comment]
And it just got released!!!

**Comment by ljharb** [comment]
v10.0.0 of [`eslint-config-airbnb`](https://www.npmjs.com/package/eslint-config-airbnb) is now published.
