### ISSUE TITLE
Consider removing the ES5 styleguide.

### ISSUE THREAD

**Issue by goatslacker** [airbnb/javascript#941]
It's probably out of sync with the main styleguide and we should be promoting the latest and greatest rather than clinging onto JS from 10 years ago.

I therefore propose we deprecate the ES5 folder.

We can move it out of this repo or perhaps even just point to a commit which has the file if people would like to view it.

**Comment by ljharb** [comment]
Sure, that makes sense. (more 1 year than 10 years, since ES6 only came out a year ago :-p)

After I finish #936, I'll make a tag for ES5, and add a link to that in the main readme, and then delete the ES5 stuff in a separate commit.

**Comment by cmalard** [comment]
Since ES6-7 is not working `on the wild` without using stuff like Babel, why being so hurried about removing it ?

**Comment by lencioni** [comment]
The main reason I see is that we no longer write ES5 code at Airbnb, so it will continue to drift. Since it is still available in git history, it will still be referenceable, but we won't have the burden of needing to maintain it anymore.

**Comment by ljharb** [comment]
@cmalard our guide recommends using babel, so if you're not using babel, you're already not following it :-p
