### ISSUE TITLE
export methods question

### ISSUE THREAD

**Issue by francoisromain** [airbnb/javascript#947]
Hello, This is a question, not a issue.

    export default {
        data () {
            return {
                …
            }
        }
    }

This makes an error on the `{` on the second line: `unexpected token`. 

What's the correct syntax? 

Thank you

**Comment by ljharb** [comment]
@francoisromain where did you get that error? Are you using Babel? That syntax looks correct to me.

**Comment by francoisromain** [comment]
@ljharb It comes from inside a vue.js template using babel from this file: https://github.com/vuejs-templates/webpack-simple/blob/master/template/src/App.vue

**Comment by ljharb** [comment]
@francoisromain modules are files, usually - you can't export anything from a script tag that's not of type "module". I'm not familiar with vue.js tho - you may want to file the issue on that repo.
