### ISSUE TITLE
generator-star-spacing rule change incompatible with async/await

### ISSUE THREAD

**Issue by lukebennett** [airbnb/javascript#948]
The `generator-star-spacing` rule was activated on the back of #887 and [included](https://github.com/airbnb/javascript/commit/8e125fa07cd9214b5e31e59095707ffae3284d13) in the v4.0.0 release. Unfortunately this rule breaks linting in codebases that use async/await syntax (see https://github.com/eslint/eslint/issues/6528).

The [guidance](https://github.com/eslint/eslint/issues/6528#issuecomment-228324958) from ESlint is to use the `eslint-plugin-babel` flavour of the `generator-star-spacing` rule instead. So async/await users upgrading to v4.0.0 will need to apply the following overrides to continue linting:

```
    'generator-star-spacing': 0,
    'babel/generator-star-spacing': [2, { 'before': false, 'after': true }]
```

As airbnb don't take a dependency on `eslint-plugin-babel`, this obviously isn't a fix you should be expected to adopt upstream. However, I wonder whether you should highlight this incompatibility in your readme? Perhaps a note added as 11.4?

I'd be happy to ping you a PR but wanted to get your take on it first.

**Comment by amilajack** [comment]
This rule also seems to have a syntax error:

```
/Users/amila/Documents/Projects/popcorn-time-desktop/node_modules/eslint/lib/rules/generator-star-spacing.js:68
            while (token.value !== "*") {
                        ^

TypeError: Cannot read property 'value' of undefined
```

**Comment by ljharb** [comment]
@amilajack I'm sure `eslint` would appreciate a bug report if you could figure out on which code that's erroring out.

@lukebennett Since this guide does not yet recommend using `async`/`await`, nor generators, I don't think it's worth mentioning just yet. Since `async/await` is now stage 4, hopefully `eslint` will support it soon - at which point, this incompatibility will go away.

**Comment by ljharb** [comment]
@lukebennett with eslint v3.6.0, which supports async/await, is this still a problem?

**Comment by taion** [comment]
This is all good now.

Separately, you may want to clarify whether https://github.com/airbnb/javascript#generators--nope applies to async/await as well.

**Comment by amilajack** [comment]
Seems like this should be closed
