### ISSUE TITLE
Trailing commas in function arguments

### ISSUE THREAD

**Issue by felixsanz** [airbnb/javascript#951]
What about trailing commas here?

``` javascript
const hero = (
  firstName,
  lastName,
  birthYear,
  superPower, // <-- this one
) => {
  // ....
};
```

It needs [http://babeljs.io/docs/plugins/syntax-trailing-function-commas/](http://babeljs.io/docs/plugins/syntax-trailing-function-commas/) and it's based on [this proposal](https://github.com/jeffmo/es-trailing-function-commas)

Does AirBnB encourages the use of trailing commas here?

**Comment by ljharb** [comment]
Not yet. In general terms, we recommend stage 3 proposals only, case-by-case.

In this specific case (which is recently stage 3), [eslint](https://github.com/eslint/eslint/issues/4352#issuecomment-232402622) can not yet parse it, so we do not yet recommend it.

I'm going to leave this open until eslint can parse trailing function commas in core, and then we can update the guide and resulting linter plugins.

**Comment by taion** [comment]
What's the most up-to-date upstream issue to track here? Is it https://github.com/ternjs/acorn/issues/441?

**Comment by ljharb** [comment]
That's probably the best one, yes.

**Comment by ljharb** [comment]
eslint v3.6.0 now supports this, but the `comma-dangle` rule does not, just yet. This is now waiting on https://github.com/eslint/eslint/pull/7181.

**Comment by graingert** [comment]
@ljharb fyi this is now available
