### ISSUE TITLE
Allow peerDependency eslint-plugin-jsx-a11y@^2.0.0

### ISSUE THREAD

**Issue by janpaul123** [airbnb/javascript#952]
Which can be done [independently](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/package.json#L50) of [updating to eslint@3.0.0](https://github.com/airbnb/javascript/issues/936).

**Comment by ljharb** [comment]
Indeed it can! However, I don't want to cut a release of the main config until I can include eslint 3, so I'm still blocked on https://github.com/airbnb/javascript/issues/936#issuecomment-230108045.

**Comment by janpaul123** [comment]
Alright, fair enough! Thanks @ljharb!

**Comment by ljharb** [comment]
(If it ends up taking forever, I'll cut a release in the meantime tho)

**Comment by lukebennett** [comment]
From the looks of https://github.com/yannickcr/eslint-plugin-react/issues/686 (which https://github.com/airbnb/javascript/issues/936#issuecomment-230108045 is blocked by), we could be waiting a while for `eslint-plugin-react` to hit v6.

How long is your definition of 'forever'? 😃

**Comment by wesbos** [comment]
Hearing from lots of folks that this is an issue. If anyone is reading this and keeps getting peer dep warnings you'll have to use eslint 2 for now..

```
npm install -g eslint@\^2.10.2 eslint-config-airbnb eslint-plugin-import eslint-plugin-react eslint-plugin-jsx-a11y@\^1.2.2
```

Hopefully we can get this released soon

**Comment by ljharb** [comment]
No matter what, you'll have to use eslint v2 with eslint-config-airbnb, until #936 is resolved.

**Comment by hpurmann** [comment]
This can be closed now that 10.0 is out, right?

**Comment by ljharb** [comment]
Yep! Thanks.

**Comment by janpaul123** [comment]
Yay, thanks for the great work!
