### ISSUE TITLE
Translation PT-BR

### ISSUE THREAD

**Issue by ronal2do** [airbnb/javascript#954]
Inspired by this great Airbnb work, I took the liberty of traduzilo for my language Portuguese Brazilian.

Follow this link.
https://github.com/ronal2do/airbnb-react-styleguide

**Comment by ljharb** [comment]
@ronal2do Thanks! Would you like to make a PR adding this to the translations section of the readme?

**Comment by ronal2do** [comment]
I`m send PR.  Ty

**Comment by ljharb** [comment]
Closed in #955.
