### ISSUE TITLE
The `imports` in tests for the rule `import/no-extraneous-dependencies`

### ISSUE THREAD

**Issue by Alex1990** [airbnb/javascript#959]
Some of the dependencies in test code are in `devDependencies`. When I lint the test code, some errors appear:

```shell
  1:1  error  'chai' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
```

This error is unexpected.

**Comment by ljharb** [comment]
@Alex1990 the default is for the entire project, which is to only allow dependencies. The proper solution is to make a `.eslintrc` in your "test" folder, that overrides the rule to allow devDependencies also.

**Comment by Alex1990** [comment]
Okay, so I must create two `.eslintrc` files.

**Comment by ljharb** [comment]
Yep! You probably already need one for your tests anyways, to enable the mocha env, or to allow for more nested callbacks than in your production code, etc :-)

**Comment by artisologic** [comment]
Hi @ljharb, I was surprised by this too. I understand what you mean and it makes sense if you have a separate `test` folder with all your tests in it. However, in our situation we have interleaved source and test files. I guess that would be impossible until we get https://github.com/eslint/eslint/issues/3611 with eslint?

So am I correct in thinking that the way forward for us is to override the rule to allow `devDependencies`?

**Comment by ljharb** [comment]
@artisologic unfortunately, that approach (interleaved source/test files) is incompatible with a great many tools. Indeed, until https://github.com/eslint/eslint/issues/3611 is done, it's simply not practical to use eslint and also use that approach - so I'd recommend avoiding that approach until all of the tools you use support a glob-style configuration.

If you persist in interleaving tests and source, no matter how you configure this rule, you'll lose out on the most important benefit - ensuring that everything your source requires is explicitly listed as a dependency.

**Comment by knpwrs** [comment]
Worth noting, with the latest published version of `eslint-plugin-import` you can use globs to configure the `no-extraneous-dependencies` rule: https://github.com/benmosher/eslint-plugin-import/pull/527

**Comment by ljharb** [comment]
Yes, take a look at who filed the issue requesting it :-p https://github.com/benmosher/eslint-plugin-import/issues/470

This will be released as an update soon.

**Comment by SimenB** [comment]
@ljharb It's been released a while now, are you going to update the default here (I can provide a PR for it)?

**Comment by ljharb** [comment]
@SimenB I'm waiting on https://github.com/benmosher/eslint-plugin-import/issues/602 , otherwise the globs have to be too accepting.

**Comment by ljharb** [comment]
`eslint-config-airbnb` `v13.0.0` is now released.
