### ISSUE TITLE
allowShortCircuit and allowTernary in no-unused-expressions

### ISSUE THREAD

**Issue by taion** [airbnb/javascript#963]
It's pretty common to write e.g.

```js
a && a();
```

Currently this fails the `no-unused-expressions` validation. However, using `allowShortCircuit` would allow this usage.

**Comment by ljharb** [comment]
This is definitely not a pattern we'd encourage. Abusing value selection operators for control flow is awful for readability - `if (a) { a(); }` is much preferred.

As always, feel free to override whatever linter rules you like in your own app :-)

**Comment by hshoff** [comment]
Previous discussion can be found here https://github.com/airbnb/javascript/issues/52 and we link to #52 in the [Resources](https://github.com/airbnb/javascript#resources) section under `other styles > conditional callbacks`

**Comment by taion** [comment]
Sure – I brought this up because these weren't explicitly set to `false` in the config, which seemed like a potential oversight, and because eslint-config-fbjs was disabling this rule because they wanted to use this pattern.

**Comment by ljharb** [comment]
Thanks, the missing options are indeed an oversight :-) I'll reopen.
