### ISSUE TITLE
Consider changing the maximum amount of characters per line from 100 to 80

### ISSUE THREAD

**Issue by kripod** [airbnb/javascript#964]
While the size of computer screens have increased, long line readability hasn't become an easier task for the human mind. Especially, if developers want to work on multiple snippets of code at once, lines should be narrow enough to avoid the appearance of horizontal scrollbars. Terminals also provide 80 columns of space per line, which is the legacy of the IBM punch card.

Further discussion can be read about the 80 chars per line coding standard [here](http://programmers.stackexchange.com/questions/148677/why-is-80-characters-the-standard-limit-for-code-width).

**Comment by turadg** [comment]
Text editors have advanced to wrap preserving indentation. Why not soft wrap?

**Comment by ljharb** [comment]
At Airbnb we use 100-char lines, and in fact are considering bumping the limit to 120. It's not horizontal scrollbars that harm readability, it's lines that have so much going on that it takes cognitive overhead to read them. In addition, terminals can provide as many vertical columns of space as you configure them to, so there's no need to limit them to the technological advancement of punch cards.

As always, feel free to fork the guide and/or override our rules as you like!

**Comment by lencioni** [comment]
I think that @kripod's argument is not that we should limit lines to 80 characters because of technological reasons, but rather for human readability reasons. Typographers generally agree that the ideal line length is between 45 and 75 characters.

https://www.smashingmagazine.com/2014/09/balancing-line-length-font-size-responsive-web-design/

**Comment by jimbolla** [comment]
@lencioni  But the readability of English prose and JavaScript are not strongly related. JS is much more structured and contains lots of punctuation. We also have color coding in our editors that assists in the readability of the code. If you took the midpoint of 45 and 75... 60 and reformatted all your JS to that line length, I bet it would be harder to read.

**Comment by ljharb** [comment]
Although some languages claim to be written like prose, most do not, and JS is not prose.

**Comment by kripod** [comment]
@ljharb I'm overriding the rule for sure, but I wanted to hear the opinion of others on the issue.

When you make a Google search for "80 chars per line", tons of result show up. Mostly because that's the "de facto standard" [defined by most programming style guides](https://en.wikipedia.org/wiki/Characters_per_line#In_programming) as of today.

**Comment by ljharb** [comment]
@kripod oh totally - but just because something has been a standard for decades doesn't mean it's ideal, it just means it's popular. (looking at you, Java)

**Comment by kripod** [comment]
80 chars per line also discourages the use of many callbacks embedded into each other: In modern ECMAScript, Promises and await/async should be widely used instead.

Even when aggressively using Flow type annotations, it isn't hard to keep the size of lines small, nor does it come with any compromises:

![](https://cloud.githubusercontent.com/assets/14854048/17147464/2cff69bc-5363-11e6-8ee4-681dfec199d3.png)

As the language evolves and the number of publicly available packages increase, smaller code with more functionality can be written. Besides that, I totally see your point, though: arguing about line size is like arguing about religion.

**Comment by ljharb** [comment]
Rather than using line length as a poor proxy for those, the guide/linter should check for the specific things you want to discourage. There's already a rule that can limit nested callbacks, for example.

**Comment by turadg** [comment]
@kripod if you add just a second parameter to your `evaluateHands` (with default arg) you're already over 80 chars.

👍 to lint for the specific things you want to discourage, like use of callback or large arity.

The "readability" argument for linting line length falls short (pun intended) because you can soft wrap in your editor to any length you, as the reader, prefer.

I lint with the Airbnb style but disable the max-len rule.
