### ISSUE TITLE
The boolean "good" casting could be better

### ISSUE THREAD

**Issue by ghost** [airbnb/javascript#97]
I wouldn't call this "good".
```js
var age = 0;
//...
var hasAge = !!age;
```
If you think about it there is no way to cast number to truth. All numbers are equally true, they are just numbers. The logical negation operator converts from numbers to bools but this is just a dumb legacy from C where there are no real bools and convenience but has nothing to do with good practice. And further - double negation a good practice - are you serious? This damages readability so much, it could really confuse young people making them wonder if this is some kind of new operator and even experienced developers will need to think about what it does. And if you are debugging and you are in some kind of confusion already this will only add to the confusion. Then you need to be aware of all language specifics like what negation does to strings, empty strings, arrays, empty arrays, objects, empty objects, bools, numbers, specific numbers. If it was strongly typed language like C it is better because you know the type of "age", but in JS, and particularly in debugging/undocumented/confused situation you don't know the type of age and the code will produce different results.

The right thing to do would be.
```
// bad.. just think about it - what does "not age" even means?
// further the intention is not clear
if ( !age ) {}

// good, the intention is perfectly clear
// further the code will work even with wrong types
if ( age > 0 ) {}
if ( age !== 0 ) {}

// good
var hasAge = (age > 0);
```

**Comment by goatslacker** [comment]
Pruning this one. Feel free to reopen if you feel strongly about it.

**Comment by ut3saturn** [comment]
Superb.  Can you tell if casting is being used here? Or does this == operator have its vulnerabilities as well?

console.log(23 == "23") 

Hard to tell if casting happens to the left side in order to compare it with the right. Would a true value occur?

**Comment by ljharb** [comment]
@ut3saturn I’m not sure what you’re asking, exactly - all == operations do type conversions. As for which side is coerced, the rules are consistent but hard to understand, which is why it’s better to make the coercion explicit and use ===.

**Comment by sstern6** [comment]
I was wondering what airbnb style guides thinks about the `!!`.

Is there a rule/pref for/against:

```
const arr = [1,2,3];

if (!!arr.length) {
  // do something
}
```

To ensure the that the check for `arr.length` is a boolean value not a truthy or falsey value?

**Comment by ljharb** [comment]
@sstern6 `!!x` is ideal to coerce to a boolean; but https://github.com/airbnb/javascript#comparison--shortcuts already discusses that you shouldn't rely on `0` being falsy; that for "length", you should always explicitly compare to a number.
