### ISSUE TITLE
jsx-sort-props is invalid

### ISSUE THREAD

**Issue by thalseth** [airbnb/javascript#979]
Configuration for rule "react/jsx-sort-props" is invalid: Value "data["0"].shorthandLast" has additional properties.

Anyone else experiencing this?

Details:
"eslint": "^3.2.2",
"eslint-config-airbnb": "^10.0.0",
"eslint-plugin-import": "^1.12.0",
"eslint-plugin-jsx-a11y": "^2.0.1",
 "eslint-plugin-react": "^6.0.0"

**Comment by ljharb** [comment]
@thalseth what does `npm ls` output? You might not have updated all the required peerDependencies.

**Comment by ljharb** [comment]
can you provide the output of `npm install` and your linter command? Is that command correctly an `npm run-script`, or are you incorrectly running a global `eslint`?

**Comment by thalseth** [comment]
Thank you for the awesome response time @ljharb. It was Atom / Atom Linter / linter-eslint returning the error. I was using an older globally installed eslint package. When i disabled "Use global ESLint installation" everything works fine 👍
