### ISSUE TITLE
react/no-string-refs recommendations conflict with no-return-assign

### ISSUE THREAD

**Issue by ryankask** [airbnb/javascript#980]
I've just upgraded to the latest version and one of issues the came up was with react/no-string-refs.

The docs here suggest the following:

```
<Foo
  ref={(ref) => this.myRef = ref}
/>
```

This causes a no-return-assign error. I'm not sure if it's possible but should this rule be relaxed in this case?

One way around it is wrapping the assignment in parenthesis:

```
<Foo
  ref={ref => (this.myRef = ref)}
/>
```

But that seems a bit off. Any suggestions?

**Comment by ljharb** [comment]
You want an arrow function that doesn't have a return value - like `(ref) => { this.ref = ref; }`. Does that solve the issue?

**Comment by hazratgs** [comment]
Try it like this
ref={arg => (this.deleteBtn = arg)}

**Comment by noahjohn9259** [comment]
thanks @ljharb

**Comment by thanhnha1103** [comment]
thanks @ljharb
