### ISSUE TITLE
How to use either extends airbnb and mocha in Eslint 

### ISSUE THREAD

**Issue by obbaeiei** [airbnb/javascript#988]
i'm new to Eslint
my eslintrc.js
> `module.exports = {`
`   "extends": "airbnb",`
`   "installedESLint": true,`
`   "plugins": ["react", "mocha"]`
`};`

Question:
When i try to lint a Mocha unit test file. it shows 'describe' is not defined. (no-undef)
It seems like Mocha plugin doesn't works.
Mocha plugin should add all of the Mocha testing global variables.
If I remove `"extends": "airbnb"` , then it will be fine.
How can i use both or just  prevent it to Lint Mocha testing files

Thank you, regard

**Comment by ljharb** [comment]
If you want mocha globals pre-defined, you need `"env": { "mocha": true }` somewhere in your eslint config. Adding the mocha plugin just provides rules that can be enabled - it doesn't set any configuration. I'm assuming the mocha plugin documentation should tell you how to add your own config.
