### ISSUE TITLE
About quotes in strings 

### ISSUE THREAD

**Issue by nyanon** [airbnb/javascript#992]
https://github.com/airbnb/javascript#strings--quotes

I see there:
```
// bad
const name = "Capt. Janeway";

// good
const name = 'Capt. Janeway';
```
But below I see reversed qoutes:
https://github.com/airbnb/javascript#es6-template-literals
```
// good
function sayHi(name) {
  return `How are you, ${name}?`;
}
```
What about adding `` in example? I mean sth like that
```
// bad
const name = "Capt. Janeway";

// good
const name = 'Capt. Janeway';

// also good
const name = `Capt. Janeway`;
```

**Comment by lencioni** [comment]
Thanks for the suggestion @nyanon. However, the backticks are template literals that allow for things like interpolation. We prefer to avoid them unless they are actually necessary and the quotes linter rule enforces this style. Perhaps we should add a "bad" example like:

```js
// bad
const name = `Capt. Janeway`;
```
