### ISSUE TITLE
Add topic about spaces in comments

### ISSUE THREAD

**Issue by felipethome** [airbnb/javascript#998]
The section 17 is about comments. One thing that was not covered, probably because almost everyone follow this naturally is space in comments. For example, single line comments should begin with a space, or block comments should have a line break right after it is open. There is a ESlint rule called `spaced-comment` that helps accomplishing this.

The problem is that I don't know if this worth increasing the size of the guideline, so I'm creating the issue before a pull request.

**Comment by ljharb** [comment]
I think it's fine to add a subsection under "comments" for this.

**Comment by nischayv** [comment]
Can I work on this issue?

**Comment by ljharb** [comment]
@nischayv absolutely!

**Comment by nischayv** [comment]
#1150 Add topic about spaces in comments

**Comment by ljharb** [comment]
Closed with #1150.
