### ISSUE TITLE
Add topic about spread over apply

### ISSUE THREAD

**Issue by felipethome** [airbnb/javascript#999]
Add a topic, maybe in section 7 (Functions), about using spread operator `...` instead of `apply()`. Like:

// bad
var args = [1, 2, 3, 4];
Math.max.apply(Math, args);

// good
var args = [1, 2, 3, 4];
Math.max(...args);

Related ESlint rule: `prefer-spread`

Don know if worth adding this, because my reason would be just: it is cleaner this way.

**Comment by ljharb** [comment]
Sure! Reasons include: it doesn't depend on `Function#apply` existing or working properly in the environment, so it's more robust; it's syntax, so the engine may be able to optimize it more; it's less verbose, so it's less likely to be done wrong.

**Comment by felipethome** [comment]
Nice, thanks for the reasons!

**Comment by ljharb** [comment]
Closed by #1001
